### ISSUE TITLE
Question: how to handle empty object

### ISSUE THREAD

**Issue by mb21** [lukeautry/tsoa#1001]
Our REST API returns an empty JSON object `{}` for some endpoints.

(You could argue this should be a HTTP 204 instead, but we thought it more consistent to always return HTTP 200 for success, and it might avoid some bugs in clients if they get an empty object instead of `null` or `undefined`.)

So far, we've used the lowercase `object` type in TypeScript to annotate that response (even though [some lint rules  discourage this](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md#default-options) "as it is currently hard to use due to not being able to assert that keys exist", but that's not a problem for this use-case). But with that we get the following warning:

```
> tsoa "spec-and-routes"

The type Object is discouraged. Please consider using an interface such as:
          export interface IStringToStringDictionary {
            [key: string]: string;
          }
          // or
          export interface IRecordOfAny {
            [key: string]: any;
          }
```

(it should probably recommend `Record<string, unknown>` instead of `IRecordOfAny` but anyhow...)

We've experimented around with such types, but they all generate weird-looking docs with redoc, e.g. with the `IStringToStringDictionary` it creates the example:

```
{
    "property1": null,
    "property2": null
}
```

But maybe that's more a problem with redoc? Because the `swagger.json` looks kinda fine:

    "schema": {
	    "properties": {},
	    "additionalProperties": {},
	    "type": "object"
    }

So probably we'll just change the API to return something like `{success: true}` instead of `{}`.

Or am I missing anything? btw. feel free to close this issue... but I was wondering what your thought were on this, and maybe my ramblings help somebody else in the future...

**Comment by michaeltnguyen** [comment]
Can you simply return `{}`?

```
@Get('/')
public async getSomething(): Promise<{}> {
  await something();
  return {};
}
```

That works for me and generates the following in swaggerUI

<img width="166" alt="Screen Shot 2021-06-18 at 9 44 34 AM" src="https://user-images.githubusercontent.com/14219683/122578763-d1f22800-d019-11eb-8eb7-8ba078c1bf12.png">

**Comment by WoH** [comment]
> But maybe that's more a problem with redoc? Because the swagger.json looks kinda fine

Pretty much that. I believe not only redoc, but also SwaggerUI do this when they generate samples based on the schema.

**Comment by mb21** [comment]
Thanks for the reply! Well, using the `{}` type is a bit of a foot-gun in TypeScript... again from typescript-eslint:

> - Avoid the `Object` and `{}` types, as they mean "any non-nullish value".
>  - This is a point of confusion for many developers, who think it means "any object type".
>  - See [this comment for more information](https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-675156492).

for example this compiles:

    const foo: {} = false

**Comment by WoH** [comment]
> Thanks for the reply! Well, using the {} type is a bit of a foot-gun in TypeScript... again from typescript-eslint:

That's not an issue with tsoa.
