### ISSUE TITLE
Nullable boolean body params should not be converted from null to false

### ISSUE THREAD

**Issue by karlismelderis** [lukeautry/tsoa#1024]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

there was a ticket but it's closed already:
https://github.com/lukeautry/tsoa/issues/761

## Expected Behavior

I expect tsoa not to manipulate data at all just to validate and don't depend on order of types in union

```ts
  goodNullable: null | boolean; // works
  badNullable: boolean | null; // breaks
```

## Current Behavior

null in post body is replaced with false

**Comment by WoH** [comment]
Similar to #1039 we should document this more clearly.

**Comment by grandopener** [comment]
I lost a bit of my day to debugging this today, and I don't agree that it's merely a documentation issue.  With issue #1039 I can see the reasoning: while it's surprising to a typescript programmer that it wouldn't find the "best" fit, it's at least a reasonable decision to just take the first type that fits and use it.  It does "fit".

By contrast, here, tsoa is not taking actions that the author permitted it to take: it is changing the input data.  That's not the same, and I assert that it is a legitimate bug.  A value of null should not match the `boolean` type at all (except to the extent that it is nullable, in which case it should preserve the null-ness).

If the type were `boolean | string` and the input were `""`, we would not expect that string value to be converted to a boolean value, even though it is falsy.  Similarly, null is falsy but it is not false and it should not be converted to false.
