### ISSUE TITLE
TypeScript compile errors with generated `routes.ts` (`Cannot find module '@tsoa/runtime'`, `Parameter 'status' implicitly has an 'any' type`)

### ISSUE THREAD

**Issue by Nezteb** [lukeautry/tsoa#1025]
## Sorting

- **I'm submitting a ...**

  - [X] bug report

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit
    - The closest I could find is https://github.com/lukeautry/tsoa/issues/289, but it was closed with no feedback.

## Expected Behavior

I've got a TypeScript/Express/TypeORM project and added `tsoa` to a single `getThingById` endpoint, and on running `pnpx tsoa routes && tsc` fails for the below error:

## Current Behavior
```
> tsoa routes && tsc
src/routes.ts:4:123 - error TS2307: Cannot find module '@tsoa/runtime' or its corresponding type declarations.
4 import { Controller, ValidationService, FieldErrors, ValidateError, TsoaRoute, HttpStatusCodeLiteral, TsoaResponse } from '@tsoa/runtime';
~~~~~~~~~~~~~~~
src/routes.ts:174:25 - error TS7006: Parameter 'status' implicitly has an 'any' type.
174         return function(status, data, headers) {
                            ~~~~~~
src/routes.ts:174:33 - error TS7006: Parameter 'data' implicitly has an 'any' type.
174         return function(status, data, headers) {
                                    ~~~~
src/routes.ts:174:39 - error TS7006: Parameter 'headers' implicitly has an 'any' type.
174         return function(status, data, headers) {
                                          ~~~~~~~
Found 4 errors.
```
## Steps to Reproduce

```json
// tsoa.json
{
  "controllerPathGlobs": ["src/**/*controller.ts"],
  "entryFile": "src/server.ts",
  "noImplicitAdditionalProperties": "throw-on-extras",
  "routes": {
    "routesDir": "app"
  },
  "spec": {
    "outputDirectory": "app",
    "specVersion": 3
  }
}
```

I also tried:
```json
...
"routes": {
  "routesDir": "src"
},
"spec": {
  "outputDirectory": "public",
  "specVersion": 3
}
```
```json
// tsconfig.json
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./src",
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "lib": ["dom", "es6", "es2017", "esnext.asynciterable"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "./app",
    "removeComments": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "target": "es6"
  },
  "exclude": ["node_modules", "app"],
  "include": ["src/**/*.ts", "src/**/*.tsx"],
```
```
// src/folders.controller.ts
export class FoldersController extends Controller {
...
  @Get("{folderId}")
  public async getFolderById(@Path() folderId: string): Promise<Folder | null> {
    const result = await this.folderService?.getFolderById(folderId);
    return result === undefined ? null : result;
  }
...
```

`Folder` is just an interface with some builtin typed properties.

## Context (Environment)

Version of the library: 3.8.0
Version of NodeJS: 14.17.0
Version of TypeScript: 4.3.2

- Confirm you were using yarn not npm: It fails with both `yarn` and `pnpm`.

**Comment by Nezteb** [comment]
I was able to fix this by running `yarn add @tsoa/runtime`, but that isn't mentioned anywhere in the docs, so I'm not sure if that's the "correct" fix. :thinking:

**Comment by WoH** [comment]
We have the runtime as a dependency, so I'm not sure what went wrong, but this is unlikely to be on our end.

**Comment by hrasekj** [comment]
Hello, today I struggled with this issue too. 

I'm using `pnpm` in my project. And the error is here because of `@tsoa/runtime` is dependency of dependency, which is fine, but not in pnpm's node_modules structure. [Read here for more info](https://pnpm.io/symlinked-node-modules-structure). It prevents "silly bugs", but in this case it leads to build error. And looks like yarn have the same node_modules structure.

So, should this be at least described in the docs? :thinking:

**Comment by fredleroy** [comment]
@WoH  Hello, I just  created a [PR](https://github.com/tsoa-community/docs/pull/85) to update the docs for this... It's the first time I do that (creating a PR) so don't hesitate to correct me if needed. Thanks
