### ISSUE TITLE
Mongoose v5.12+ throw error "Error: Unknown type: TypeQuery"

### ISSUE THREAD

**Issue by kYem** [lukeautry/tsoa#1026]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Should generate the route with latest mongoose version.

I seems this might broader issue with `typeof` support?

## Current Behavior

Updated mongoose to 5.12.1 or higher, tsoa can no longer generate controllers.

```
> tsoa spec-and-routes && tsc

There was a problem resolving type of 'SchemaType'.
There was a problem resolving type of 'Schema.Types.ObjectId'.
There was a problem resolving type of 'ObjectId'.
There was a problem resolving type of 'ValueValidation'.


Generate routes error.
 Error: Unknown type: TypeQuery
At: ###########/node_modules/mongoose/index.d.ts:2540:2540.
This was caused by 'OptionsConstructor: typeof SchemaTypeOptions;'
    at new GenerateMetadataError 
(###########/node_modules/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/exceptions.js:22:28)
````

## Steps to Reproduce

Annotate interface that have reference to Schema.Types.ObjectId

## Context (Environment)

Version of the library: tsoa@3.8.0

```
tsoa@3.8.0
mongoose@5.12.1
```
Version of NodeJS: v14.16.1

- Confirm you were using yarn not npm: happens on both

**Comment by WoH** [comment]
Duplicate
