### ISSUE TITLE
File upload guide does not work / is not up to date

### ISSUE THREAD

**Issue by tom-boothman** [lukeautry/tsoa#1028]
https://tsoa-community.github.io/docs/file-upload.html

This guide led me down a weird path that turned out was complicated and unnecessary.

There are some people talking about it in the issues of this repo but they mostly end up doing something very custom and that tends not to work.

Given that it's actually easy to upload files and use multipart/form-data in general can the website be updated with a better example? I'd submit a PR but I don't know where the repo is.

Here's a pared down version of the code I used, which works.

```typescript
import { Controller, FormField, Post, Route, UploadedFiles } from '@tsoa/runtime';

@Route('issues')
export class IssuesController extends Controller {
    /**
     * Raise an issue
     */
    @Post()
    public async createIssue(
        @FormField() title: string,
        @FormField() description: string,
        @UploadedFiles() files: Express.Multer.File[],
    ): Promise<void> {
        console.log(files);
    }
}
```

**Comment by tom-boothman** [comment]
Ah. I just found https://github.com/tsoa-community/docs/issues/35

**Comment by tom-boothman** [comment]
https://github.com/tsoa-community/docs/pull/39

**Comment by WoH** [comment]
Thank you very much, should be online any minute now.
