### ISSUE TITLE
response description from jsdoc @returns

### ISSUE THREAD

**Issue by laktak** [lukeautry/tsoa#1029]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Could you use the description from the jsdoc [@returns](https://jsdoc.app/tags-returns.html) tag to set the description of the default response?

## Current Behavior

At the moment the text "Ok" is used unless a `@SuccessResponse`/`@Response` is set and `@returns` is ignored.

**Comment by pauliyobo** [comment]
Hello, I would like to take this on, but I believe I need some clarification.
@laktak am I correct on assuming you would like the text of the default response to be set to the value of the @returns jsDoc comment?
If so, what should the behaviour be if @response and or @SuccessResponse are present?

**Comment by laktak** [comment]
I'd expect @returns to define the return value in case the function completes successfully (as HTTP Code 200). So if SuccessResponse is specified I'd expect it to overwrite jsdoc returns but @Response would have no conflict. 

Thanks for looking into this!

**Comment by laktak** [comment]
Thanks @pauliyobo :+1:
