### ISSUE TITLE
Support UndefinedKeyword

### ISSUE THREAD

**Issue by kibiz0r** [lukeautry/tsoa#1031]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [ ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Using `@types/node` 12.20.16 should still permit tsoa to generate `routes.ts` when using a custom error as below:

```ts
export interface CustomError extends Error {
  message: string;
  status: number;
}

@Route('GetTest')
export class GetTestController extends Controller {
  @Get('ThrowsError')
  @Response<CustomError>()
  public async getThrowsError(): Promise<TestModel> {
    throw {
      message: 'error thrown',
      status: 400,
    };
  }
}
```

## Current Behavior

```bash
harrinm@C02D11F7MD6T:~/git/tsoa|master> yarn test
yarn run v1.22.4
$ yarn --cwd tests test
$ yarn clean && cross-env NODE_ENV=tsoa_test ts-node --require tsconfig-paths/register ./prepare.ts
$ rimraf dist fixtures/*/routes.ts fixtures/*/customRoutes.ts
↻ Starting Swagger Spec Generation...
There was a problem resolving type of 'Error'.
There was a problem resolving type of 'CustomError'.
Generate routes error.
 GenerateMetadataError: Unknown type: UndefinedKeyword
At: /Users/harrinm/git/tsoa/tests/node_modules/@types/node/globals.d.ts:127:127.
This was caused by 'string | undefined'
    at TypeResolver.resolve (/Users/harrinm/git/tsoa/packages/cli/src/metadataGeneration/typeResolver.ts:309:13)
    at /Users/harrinm/git/tsoa/packages/cli/src/metadataGeneration/typeResolver.ts:62:84
    at Array.map (<anonymous>)
    at TypeResolver.resolve (/Users/harrinm/git/tsoa/packages/cli/src/metadataGeneration/typeResolver.ts:61:41)
    at TypeResolver.propertyFromSignature (/Users/harrinm/git/tsoa/packages/cli/src/metadataGeneration/typeResolver.ts:890:137)
    at /Users/harrinm/git/tsoa/packages/cli/src/metadataGeneration/typeResolver.ts:848:141
    at Array.map (<anonymous>)
    at TypeResolver.getModelProperties (/Users/harrinm/git/tsoa/packages/cli/src/metadataGeneration/typeResolver.ts:848:98)
    at TypeResolver.getModelReference (/Users/harrinm/git/tsoa/packages/cli/src/metadataGeneration/typeResolver.ts:622:29)
    at TypeResolver.getReferenceType (/Users/harrinm/git/tsoa/packages/cli/src/metadataGeneration/typeResolver.ts:563:30)
```

## Possible Solution

Not sure.

I'll at least be providing a PR to demo a failing test for it though.

## Steps to Reproduce

- Update `tests/package.json` to `"@types/node": "^12.20.16"`
- Add `@Response<CustomError>()` to `tests/fixtures/controllers/getController.ts`
- `yarn test`

...or run the PR I'll be putting up shortly to contrib a failing test demoing the problem.

## Context (Environment)

Version of the library: master
Version of NodeJS: 12.21.0

- Confirm you were using yarn not npm: [x]

## Detailed Description

In `@types/node` 12.20.16, DefinitelyTyped's [added `| undefined` to a lot of fields](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d75a4e3dd11692cd81bb06cd6aaa8baadc68d22e), to prepare for the upcoming `exactOptionalPropertyTypes` setting in TypeScript 4.4.

An unfortunate side-effect is that now tsoa has trouble handling a number of built-in types, including `Error`, which is a problem for us when we use it like so: `@Response<MyCustomError>()`

**Comment by WoH** [comment]
This issue is a duplicate, but since TS 4.4 now really does differentiate, we should reconsider the support.

**Comment by pauliyobo** [comment]
Hello.
Since undefined does not really have a type in json schemas, should that be considered like the null keyword is, or what should it resolve to, if anything?

**Comment by WoH** [comment]
I believe the best way would be:
On responses: To void
On parameters (Query/header):
  - if bare: remove
  - if union with T: mark parameter as optional
On properties:
  - if bare: remove the property
  - if union: mark the property as optional

**Comment by Hi-Fi** [comment]
I actually made some tried related to this, and currently swagger generation works fine, and 7 GET route generation tests are failing. Code isn't pretty, but as this feature is needed I'll try to form PR of it next week. If e.g. @foglerek doesn't have something already available?

**Comment by WoH** [comment]
> I actually made some tried related to this, and currently swagger generation works fine, and 7 GET route generation tests are failing. Code isn't pretty, but as this feature is needed I'll try to form PR of it next week. If e.g. @foglerek doesn't have something already available?

Please send the PR and I'll review what needs to be done for it to work well if needed.

**Comment by Hi-Fi** [comment]
@WoH Any pointers how to get PR working and support for undefined (as bare and in union) to TSOA?

**Comment by WoH** [comment]
> @WoH Any pointers how to get PR working and support for undefined (as bare and in union) to TSOA?

I'll try to provide actionable feedback as promised over the weekend. After taking a quick glance here's what I can already say: I think it's easier to add a primitive type we can represent instead of working around the symptoms of not having one.

**Comment by Hi-Fi** [comment]
Thank you, I'll try that approach. Just noticed that it was discussed earlier in this thread already.
