### ISSUE TITLE
TS2749: 'TsoaResponse' refers to a value, but is being used as a type here. Did you mean 'typeof TsoaResponse'?

### ISSUE THREAD

**Issue by carlnc** [lukeautry/tsoa#1037]
The documented use of  `@Res`/`TsoaResponse` produces a TS2749 error.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

**Tell us what should happen:**

* I expected to not have to use @ts-ignore everywhere.
* it should just work.

```ts
// https://github.com/typescript-eslint/typescript-eslint/issues/1824
/* eslint-disable @typescript-eslint/indent */
// eslint-disable-next-line max-classes-per-file
import {
    Controller,
    Get,
    Path,
    Res,
    Response as TsoaResponse,
    Route,
} from 'tsoa';

class Record {
    id: string;
    constructor(id: string) { this.id = id; }
}

class RecordService {
    async get(id: string) { return new Record(id); }
}

@Route('/')
export class TestController extends Controller {
    @Get('/test/:id')
    public async getRecord(
        @Path('id') id:     string,
        @Res()      res404: TsoaResponse<404, string>,
    ): Promise<Record> {
        return await (new RecordService()).get(id)
            || res404(404);
    }
}
```

## Current Behavior

* Works: `tsoa spec-and-routes`
* Does not work: `tsc -p ./tsconfig-build.json --outDir build`

Blows up with:

```
src/testController.ts:27:29 - error TS2749: 'TsoaResponse' refers to a value, but is being used as a type here. Did you mean 'typeof TsoaResponse'?

27         @Res()      res404: TsoaResponse<404, string>,
                               ~~~~~~~~~~~~
```

## Possible Solution

I just want to return a 404.  There must be an easier/cleaner way.

Given every new request creates a new controller instance, couldn't we have access to the Express request context via `this.`?

Alternatively, something like:

```
        return await (new RecordService()).get(id)
            || this.response(404);
```
or something.

In the mean time, `// @ts-ignore` everywhere.

## Context (Environment)

Version of the library: 3.8.0 (`cat node_modules/tsoa/package.json | jq '.version'`)
Version of NodeJS: v14.15.4 (`node --version`)

- Confirm you were using yarn not npm: [ using pnpm ]

**Comment by carlnc** [comment]
It appears the warning [here](https://tsoa-community.github.io/docs/error-handling.html#specifying-error-response-types-for-openapi) is no longer valid.

```
Please note that @Response has to be the tsoa import and can not currently be renamed
 (i.e. import {Response as TsoaResponse} from "tsoa")
``````

and instead I should be using the method further down in [Typechecked alternate responses](https://tsoa-community.github.io/docs/error-handling.html#typechecked-alternate-responses)?

The following works:

```
@Route('/')
export class TestController extends Controller {
    @Get('/test/:id')
    public async getRecord(
        @Path('id') id:     string,
        @Res()      res404: TsoaResponse<404, string>,
    ): Promise<Record> {
        return await (new RecordService()).get(id)
            || res404(404, undefined as unknown as string);
    }
}
```

It's a shame I can't just use `TsoaResponse<404, undefined>` 
... or just `TsoaResponse<404>`,
... or just `TsoaResponse`.


Actually.  Now that I read that notice a 10th time, I now realise it must not mean what I thought it meant, and I still have no idea what it does means.

**Comment by WoH** [comment]
[`Response`](https://tsoa-community.github.io/reference/modules.html#response) is a decorator, [`TsoaResponse`](https://tsoa-community.github.io/reference/modules.html#tsoaresponse) is a type. 
This is why the code throws:
```
src/testController.ts:27:29 - error TS2749: 'TsoaResponse' refers to a value, but is being used as a type here. Did you mean 'typeof TsoaResponse'?
```
if you import the Decorator and try to use it as a type (`import {Response as TsoaResponse}`.

Use `@Res` with `TsoaResponse`, don't rename anything.
