### ISSUE TITLE
Intersection with an union silently removes extras that shouldn't be removed

### ISSUE THREAD

**Issue by antmarot** [lukeautry/tsoa#1039]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Using an intersection where one of the subtype is the union of two partial interfaces should not remove fields that are allowed.

```ts
interface MyType { field?: string };
interface UnionLeft { foo?: string };
interface UnionRight { bar?: string };

type BodyType = MyType & (UnionLeft | UnionRight);
```

Given the types above, I expect that submitting the following body will not remove fields in the validation process.
```json
{
  "bar": "bar"
}
```

## Current Behavior

Submitting the body defined above will remove the `bar` field from the body — it is considered as an extra.

However, if you submit the following body, no fields are removed
```json
{
  "foo": "foo"
}
```
which indicates that the order is important (no fields are removed from the first type of the union).

## Possible Solution

I think this is due to the partial aspects of the types and the `'silently-remove-extras'` option set in the intersection validation.
Since the first type of the union validates against the body (with `silently-remove-extras`), the value is cleaned and the field is removed.

Note that if you use the "union of intersections" form instead of the "intersection of unions", it works as expected.

```ts
interface MyType { field?: string };
interface UnionLeft { foo?: string };
interface UnionRight { bar?: string };

type InterOfUnions = MyType & (UnionLeft | UnionRight); // doesn't work
type UnionOfInters = (MyType & UnionLeft) | (MyType & UnionRight); // works
```

## Context (Environment)

Version of the library: ^3.8.0
Version of NodeJS: v14.17.0

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
I think this is mainly a documentation issue. The way we validate is we try to find the first match we can find (while being 'allowed' to silently removing extra properties) and tsoa can fulfil the requirements by stripping `bar` and selling it as `MyType & UnionLeft;`
This is also an optimization that prevents iterating through a very large amount of possible schema combinations to find what you may reasonably expect to be the best match here.
