### ISSUE TITLE
Proper way to ignore a field from documentation

### ISSUE THREAD

**Issue by oreporan** [lukeautry/tsoa#1041]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

I'm trying to hide a specific field from a request body, and it seems the only way to do this is to use 
`@ignore` on the field as such:

```ts

    /**
     * @example "https://path.to.directory/"
     * @pattern (https|s3):\/\/.+
     * @ignore
     */
    destination_url?: string;

```

However, combined with 
```json
   "noImplicitAdditionalProperties": "throw-on-extras",
```
It throws an error. 

So if I want a hidden field, this doesn't suffice

## Expected Behavior

a hidden field passes validation but is just not documented

## Current Behavior

if we use `throw-on-extras` -> throws on hidden field
if we use `ignore` -> everything passes

## Possible Solution

ignored fields should pass validation in `routes.ts`

**Comment by oreporan** [comment]
any updates here?

**Comment by WoH** [comment]
You can allow this via index signature. Any other idea doesn't align well with the goal of bringing implementation and spec together as close as possible. For my personal taste, we've already wandered off that path too much.
Another possible approach is to move this from a body property to a hidden query parameter.

**Comment by oreporan** [comment]
can you point me to an example regarding index signature?

**Comment by WoH** [comment]
> can you point me to an example regarding index signature?

```
interface WithIndex {
  a: string,
  b: string,
  [name: string]: any
}
```

**Comment by oreporan** [comment]
@WoH but if I add `[name: string]: any` then `throw-on-extras` will never throw...

**Comment by oreporan** [comment]
can you please reopen this?

**Comment by felipe-muner** [comment]
any solution?

**Comment by BlairAllegroTech** [comment]
We have a similar issue, we are using a form of Opaque types in Typescript
```typescript
type OpaqueType<LABEL, T extends number | string> = T & {
    readonly TAG: LABEL;
};

type MySpecialIDType =  OpaqueType<"MY_TYPESAFE_ID", string>
class SomeController  {
   getItem(id: MySpecialIDType): {id : MySpecialIDType } { .... }
}
```

We would like to prevent the `TAG` field from ending up in the schema and validation
