### ISSUE TITLE
Vulnerability on auto generated routes

### ISSUE THREAD

**Issue by sazalihisham88** [lukeautry/tsoa#1042]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Description

Hi my team is currently using semgrep to do SAST on our source code. In the test result, there are `Improper Control of Generation of Code ('Code Injection')` vulnerabilities on several places in `route.ts`, which is auto-generated. Since this is auto generated code, is there any way for me to eliminate this vulnerability? Kindly find attached test report and my `route.ts` file.

Thanks.

[reports-and-route-files.zip](https://github.com/lukeautry/tsoa/files/6883267/reports-and-route-files.zip)

## Context (Environment)

Version of the library: v3.4.0
Version of NodeJS: v12.16.3

**Comment by devnev** [comment]
The relevant lines seem to be:

```ts
        Object.keys(headers).forEach((name: string) => {
            response.set(name, headers[name]);
        });
```

and

```ts
        const values = Object.keys(args).map((key) => {
            const name = args[key].name;
            switch (args[key].in) {
                //snip
                case 'query':
                    return validationService.ValidateParam(args[key], request.query[name], name, fieldErrors, undefined, {"noImplicitAdditionalProperties":"throw-on-extras"});
                //snip
            }
        });
```

with the concern being `Bracket object notation with user input is present, this might allow an attacker to access all properties of the object and even it's prototype, leading to possible code execution.`

`Object.keys` returns the object's own properties, so I don't see how this allows access to any other properties of the relevant objects. Also neither `headers` nor args is even user input. Could this be a false positive, @sazalihisham88 ?

**Comment by sazalihisham88** [comment]
@devnev seems like false positive. i am closing this issue. thanks!
