### ISSUE TITLE
Dynamics header name from ENV in Router

### ISSUE THREAD

**Issue by chendu** [lukeautry/tsoa#1045]
In Router, when we get header value with env configured header name, it's will not be well handled. When we change to a const value, it works fine

the tsoa version using
```
"@tsoa/runtime": "^3.8.0",
```

- [x] This work
```ts
import { Controller, Get, Header, Route, Tags } from 'tsoa';

const USER_ID_HEADER = 'x-user-id'; // difference on this line
@Route('api/test')
@Tags('Test')
export class TestRouter extends Controller {
  @Get()
  public async testaaa(@Header(USER_ID_HEADER) userId: string) {
    console.log(userId);
  }
}
```
- [x] This DOESN'T work
```ts
import { Controller, Get, Header, Route, Tags } from 'tsoa';

const USER_ID_HEADER = process.env.USER_ID_HEADER || 'x-user-id'; // difference on this line
@Route('api/test')
@Tags('Test')
export class TestRouter extends Controller {
  @Get()
  public async testaaa(@Header(USER_ID_HEADER) userId: string) {
    console.log(userId);
  }
}
```

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
import { Controller, Get, Header, Route, Tags } from 'tsoa';

const USER_ID_HEADER = process.env.USER_ID_HEADER || 'x-user-id';
@Route('api/test')
@Tags('Test')
export class TestRouter extends Controller {
  @Get()
  public async testaaa(@Header(USER_ID_HEADER) userId: string) {
    console.log(userId); // except to print the header value passed in HTTP request
  }
}
```

## Current Behavior

currently, it will return a mandatory validation error.
```json
{
    "error": "INVALID_PARAMETERS",
    "message": {
        "userId": {
            "message": "'userId' is required"
        }
    },
    "transactionId": "33bc2e48-d9a6-4f4e-8c0a-221793d3f901"
}
```

```ts

```

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
It's impossible to find out what the header name will be at compile time (which is a prerequisite for us to generate a static OpenAPI spec), so this will not work.
