### ISSUE TITLE
validateBuffer has non-prefixed, unused arguments

### ISSUE THREAD

**Issue by alucky4eg** [lukeautry/tsoa#1046]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

## Expected Behavior

current definition
file: packages/runtime/src/routeGeneration/templateHelpers.ts
line: 457
```ts
  public validateBuffer(name: string, value: string) {
    return Buffer.from(value);
  }
```

## Current Behavior
for a `tsconfig.json` settings with `
```json
{
  "compilerOptions": {
    "noUnusedParameters": true
  }
}
```
ive got error:
```
node_modules/@tsoa/runtime/src/routeGeneration/templateHelpers.ts:457:25 - error TS6133: 'name' is declared but its value is never read.

457   public validateBuffer(name: string, value: string) {
                            ~~~~


Found 1 error.
```

## Possible Solution
```ts
  public validateBuffer(_name: string, value: string) {
    return Buffer.from(value);
  }
```

## Context (Environment)

Version of the library: 3.8.0
Version of NodeJS: v16.4.2
Version of Typescript: 4.3.5

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
Feel free to submit a PR
