### ISSUE TITLE
promise.any dependency leaks into codegen, requiring pnpm clients to include it as a direct dependency

### ISSUE THREAD

**Issue by kibiz0r** [lukeautry/tsoa#1051]
pnpm goes to great pains to prevent devs from requiring packages that they don't explicitly depend on, so when `@tsoa/cli` generates this section of `routes.ts`...

```ts
// @ts-ignore - no great way to install types from subpackage
const promiseAny = require('promise.any');
```

...that will fail if the dev's express app doesn't add a direct dependency on `promise.any`.

This creates a bit of a weird circumstance, where not only is that dependency leaking out, there is also no guarantee that the client code's dependency is in-sync with the vendor code's dependency.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

Related issue: #1050

...but that one is a false report regarding `@tsoa/runtime`'s declared dependencies. This is regarding `@tsoa/cli`'s codegen.

## Expected Behavior

- Have a tsoa express app using pnpm
- Generate routes
- Run express app without runtime error on requiring promise.any

## Current Behavior

- Running express app throws runtime error on requiring promise.any

## Possible Solution

Perhaps the dependency could be confined to the runtime package and then exposed as a re-export, so that the codgen can function nearly the same way but without imposing this caveat onto the client package.

e.g.

```ts
// @ ts-ignore - no great way to install types from subpackage
const { promiseAny } = require("@tsoa/runtime");
```

(There may even be properly-exported type declarations at that point?)

## Context (Environment)

Version of the library: 3.9.0
Version of NodeJS: 12.18.2

- Confirm you were using yarn not npm: [ ]
  - Uhhh.... using pnpm, so.... ¯\\_(ツ)_/¯

**Comment by WoH** [comment]
I cba to find out, but would a peerDep work?

**Comment by gaggle** [comment]
For now I've had to install promise.any as a dependency, so I think peer dep would probably have given me a warning to indicate the issue.

I can't speak for those who need this feature as my runtime (Node 16) supports Promise.any, but I'd argue it's possible the easiest way out of this for the maintainers and your users is to simply remove the need for the shim and increase the lowest supported Node version when you're ready to make that backwards-breaking change. 

Doesn't have to be now, you know your audience best and you decide when, but if this shim is only here to support old Node versions then I trust there'll come a time where you'll want to remove it.

**Comment by WoH** [comment]
Node 14's EOL is April, 2023. At that point certainly.
