### ISSUE TITLE
tsoa/cli

### ISSUE THREAD

**Issue by JimmyBjorklund** [lukeautry/tsoa#1057]
Hi thanks for making tsoa/cli and runtime it's really nice. 
I have a question would it be possible to make the client backward compatible with tsoa e.g make below work.  

  "scripts": {
    "tsoa": "tsoa spec-and-routes -c tsoa.json"
  },

As it is right now i get tsoa not found ;)
Thanks again for great work
Jimmy

**Comment by WoH** [comment]
What we export from the `tsoa` package is only the thinnest of wrappers around the `@tsoa/cli`:
```ts
#!/usr/bin/env node
import { runCLI } from '@tsoa/cli';

if (!module.parent) runCLI();
```

If you want to avoid the `tsoa` package, you should take a look at providing this wrapper yourself.

**Comment by JimmyBjorklund** [comment]
We do this for now
"scripts": {
    "tsoa": "node ./node_modules/@tsoa/cli/dist/index.js spec-and-routes -c tsoa.json"
}
