### ISSUE TITLE
Method descriptors do not support variables

### ISSUE THREAD

**Issue by karlismelderis** [lukeautry/tsoa#1060]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior

we tried to reuse existing variable/const/enum in Method and Path but path end up as `undefined` in OpenAPI spec

```ts
enum aliases {
  TEST_ALIAS = 'test-alias',
}

@Route('/example/{exampleId}/test')
export class DeliverablesController extends Controller {
  @Put(aliases.TEST_ALIAS)
  public createOrUpdateTest(
  ): any {
    return {};
  }
}
```

## Context (Environment)

Version of the library: 3.9.0
Version of NodeJS: 16

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
We will not be able to statically analyze arbitrary variables (for obvious reasons), but the enum or consts that are defined in the same file should work.

**Comment by WoH** [comment]
What we need is an additional case here:
https://github.com/lukeautry/tsoa/blob/d016cfc2d1d5a200777c9c715d7e894b2c6b2de3/packages/cli/src/metadataGeneration/initializer-value.ts#L4

Which looks for PropertyAccessExpression where you can either check the `Type`, which should be (based on flags) a `StringLiteral` with a value, or check if the Symbol has a `valueDeclaration` of kind `SyntaxKind.EnumMember`.

See [the AST](https://ts-ast-viewer.com/#code/KYOwrgtgBAggNgSwIYGdgqgbwFBSgFQFEBlfAfRgBkBJGYqAXigHIAXdVgWiUVWYBpsAX2zYAAgCUA9mHYAKZgHpgADyQQADnGCLMq9VuDUAJkMXsUrZgEpsqjVIBOrKAGM4qDABFgiAG7AjkgARtooAMJSIKyOUnDajlCq7CDGGJHRsfGBWLhQYgAKsnLwyGgoAHREpBQ0dLZ4GmChCK5ujsBI7ADyjgCqGsZdwPgccnnWAFxQSCAAnrl4eB2sYI4gWEIA3HkiIkA) which makes this a lot easier to grasp.

**Comment by ra100** [comment]
Hi @WoH  I started to look at it, but took a different turn, would this be acceptable as partial solution?

https://github.com/ra100/tsoa/commit/36379bb8b35ee655b480a9fc9b46f270de2111ff#diff-1197e792461515aaa55fe7e4150b036cae3a633207d7185e4b592cee92f67438R67-R76

https://github.com/ra100/tsoa/commit/36379bb8b35ee655b480a9fc9b46f270de2111ff#diff-9a480fd48e2143ce29e9efdbbae10036ff73e84aea7cd2739c47cdedca56e241R136

**Comment by WoH** [comment]
Your solution is in fact preferable, since I assumed from my flawed memory that we were already extracting the path via `getDecoratorValues`, which we didnt't do. Ideally, you could add a test for the Enum example, so we cover that as well.

**Comment by ra100** [comment]
Ok, will add the enum test too. Should I add some units too, or just these integration will cover it?

**Comment by WoH** [comment]
https://github.com/lukeautry/tsoa/blob/master/tests/unit/swagger/pathGeneration/getRoutes.spec.ts

This already has most of the setup you'd want, making sure the relevant routes exist would be helpful.

**Comment by WoH** [comment]
Roughly something like:

```ts

  it('should generate a path for a GET route with const argument', () => {
    verifyPath(baseRoute + 'path_from_constant');
  });

  it('should generate a path for a GET route with Enum argument', () => {
    verifyPath(baseRoute + 'path_from_enum');
  });

```

**Comment by ra100** [comment]
I hope it looks better now. And does it make sense for this case to figure out some negative tests? :)
