### ISSUE TITLE
'bodyParser' is deprecated

### ISSUE THREAD

**Issue by gfox1984** [lukeautry/tsoa#1064]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior

I have followed the guide to get started and when I create app.ts with the supplied code, I have a "deprecated" warning on bodyParser on VS Code:

```
'bodyParser' is deprecated.ts(6385)
index.d.ts(19, 5): The declaration was marked as deprecated here.
(alias) function bodyParser(options?: (bodyParser.OptionsJson & bodyParser.OptionsText & bodyParser.OptionsUrlencoded) | undefined): NextHandleFunction
(alias) namespace bodyParser
import bodyParser
@deprecated
```

## Expected Behavior

No deprecation warnings.

## Steps to Reproduce

Follow the steps at https://tsoa-community.github.io/docs/getting-started.html

## Context (Environment)

Version of the library: 3.9.0
Version of body-parser: 1.19.0
Version of @types/body-parser: 1.19.1
Version of NodeJS: 14.15.4

- Confirm you were using yarn not npm: [x]

## Possible Solution

After some research, I came across this: 
 - https://github.com/expressjs/body-parser/issues/428
 - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52314

This is a known issue with the current type definitions. The best workaround I could find was to replace `bodyParser.json()` and `bodyParser.urlencoded()` with `express.json()` and `express.urlencoded()` as suggested in https://stackoverflow.com/questions/24330014/bodyparser-is-deprecated-express-4

I know this is "just" a guide to get started, but updating it would save a few minutes or hours to people like myself who just started using tsoa :)

**Comment by akc42** [comment]
@WoH Again I don't understand the decision to close.  As I pointed out in #52314 I am NOT using express and I don't want to import it just to avoid a depreciation warning.  I am using it like this

```
  const bodyParser = require('body-parser');
  const Router = require('router');
...
  const routerOpts = {mergeParams: true};
  const router = Router(routerOpts);  //create a router
...
  const api = Router(routerOpts); 
...
  api.use(bodyParser.json());
```
Why is this depreciated?
