### ISSUE TITLE
tsoa's package.json should use specific versions of @tsoa/runtime and @tsoa/cli

### ISSUE THREAD

**Issue by kibiz0r** [lukeautry/tsoa#1078]
Trying to downgrade the `tsoa` package to a previous version ends up having no effect, because it delegates all of the important work to `@tsoa/runtime` and `@tsoa/cli`, which will always be on the latest (minor) version.

Consumers who use a flat dependency manager can work around this easily by explicitly depending on the sub-dependency versions they need. Isolated dependency managers like pnpm can work around it, too, by using hooks to intercept when `tsoa`'s package.json gets resolved, but these solutions are rather brittle and non-obvious to new developers on a project.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Possible Solution

Set dependencies in `tsoa/packages/tsoa/package.json` to specific versions of `@tsoa/runtime` and `@tsoa/cli`

## Steps to Reproduce

Depend on a specific, earlier version of `tsoa`. See that the latest `@tsoa/runtime` and `@tsoa/cli` get installed anyway.

## Context (Environment)

Version of the library: all up to 3.11.1 so far
Version of NodeJS: 12.18.2

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
That is what we want (not depending on a specific version, but a range), in all cases where I don't decide to break bw compat in a SemVer patch accidentally.

**Comment by kibiz0r** [comment]
I definitely want to rely on semver, as a consumer, but I also need to have an escape hatch and I don't have that here. Every version of `tsoa` from 3.3.0 to the latest is functionally equivalent to the latest, cuz the parent package doesn't really do anything except grab the latest implementation. If it had some logic of its own, it would make sense to grant the underlying stuff the freedom to move around a bit, but if it's just re-packaging the underlying stuff, it kinda breaks semver.
