### ISSUE TITLE
@Example doesn't read value from an imported variable

### ISSUE THREAD

**Issue by nikosgpet** [lukeautry/tsoa#1079]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

This is a repost of issue https://github.com/lukeautry/tsoa/issues/834 because I don't think it has been addressed. 

`@Example()` should be able to read a variable value imported from another file.

With

```ts
// file a.ts
export const example = {someKey: 'someValue'}
// file b.ts
import example from a
...
@Example(example)
...
```
tsoa should generate the correct response example from the imported variable.

## Current Behavior

It now creates an empty object `{}` if the variable is imported. It works if the example value is directly supplied to the decorator or defined in the same file.

Being forced to give the example in the same file is particularly inconvenient for very long jsons that can make the file quickly unreadable.

**Comment by must** [comment]
+1 on this I'm experiencing the same issue

**Comment by megmut** [comment]
+1 I have this issue too.. can we get any input on this please? :(

**Comment by kingyue737** [comment]
I'm experiencing this issue in 4.0.0 rc.0.
`@Example()` doesn't read value of variable defined in the same file. Instead, it generates an empty object "Example1".
