### ISSUE TITLE
Duplicate required properties in swagger in definitions.

### ISSUE THREAD

**Issue by luminblade** [lukeautry/tsoa#108]
When a method returns a class defined with a property that is defined both in the class and the constructor, the property is duplicated in the required section of the generated swagger.json, making it invalid.

One solution is to only define the property in the constructor, but this can reduce readability, especially on large classes.

This code produces duplicate required properties for "prop1".

```
export class ExampleModel {
	public prop1: string;
	public prop2?: string;

	constructor(prop1: string) {
		this.prop1 = prop1;
	}
}

@Route('example')
export class ExampleController extends Controller {

	@Get('duplicate')
	public async duplicate(@Query() summary?: string): Promise<ExampleModel> {
		let ex = new ExampleModel('value');
		return Promise.resolve(ex);
	}
}
````

```
"ExampleModel": {
	"description": "",
		"properties": {
		"prop1": {
			"type": "string",
				"description": ""
		},
		"prop2": {
			"type": "string",
				"description": ""
		}
	},
	"required": [
		"prop1",
		"prop1"
	],
		"type": "object"
}
````

**Comment by shaunlmason** [comment]
@luminblade This has been a consistent nagging issue in my use as well.  I *think* I have it fixed, just waiting on a review.

Thanks for the feedback.
