### ISSUE TITLE
tsoa does not implement the OpenAPI spec for root level security

### ISSUE THREAD

**Issue by marklawlor** [lukeautry/tsoa#1082]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The OpenApi Spec (both v2 & v3) allow for a root level `security` to specify a `securityDefinition` to be used for the entire API. 

As described by the spec

> A declaration of which security mechanisms can be used across the API. The list of values includes alternative security requirement objects that can be used. Only one of the security requirement objects need to be satisfied to authorize a request. Individual operations can override this definition. To make security optional, an empty security requirement ({}) can be included in the array.

This declaration will be used for all routes, unless a route specifies their own `security` definition.

## Current Behavior

The root level security schema is ignored. All controllers must be individually secured.

## Possible Solution

`tsoa` should follow the OpenAPI spec and use the `security` definition on all routes if a root level `security` definition is present. 

Additionally, this should be configurable via the `spec` option in the `tsoa.config` (currently have to use `spec.spec.security` for it to be present in the schema).

## Steps to Reproduce

```
  "entryFile": "src/index.ts",
  "controllerPathGlobs": ["src/**/*Controller.ts"],
  "spec": {
    "outputDirectory": "build",
    "specVersion": 3,
    "securityDefinitions": {
      "GlobalSecurityDefinition": {
 "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "spec": {
      "security": ["GlobalSecurityDefinition"]
    }
  },
  "routes": {
    "routesDir": "build",
  },
}
```

## Context (Environment)

Version of the library: v3.11.2

## Detailed Description

The OpenAPI spec purposefully allows a top level security definition to prevent user error when defining routes.

**Comment by dustin-relicx** [comment]
Bump. This would be really great for us.

**Comment by WoH** [comment]
@dustin-relicx would you like to volunteer for a PR?

**Comment by dustin-relicx** [comment]
@WoH I floated me tackling this as an option and we'll see if I'm given the time.

I don't really understand your second part. I think the original suggestion makes sense since it's a root-level configuration that's mapping closely with the actual OpenAPI spec. But I barely know what I'm talking about 😂

**Comment by marklawlor** [comment]
@WoH Can you post a video example of your suggestion? I don't quite understand.

Within the spec `security` is on the root of the document, I think putting it within a decorator might lose its context, and cause people to mistake it with the route level `security` attribute.

**Comment by WoH** [comment]
My proposal was to extend the tsla config's security definitions iirc.

**Comment by tboothman** [comment]
Are people still interested in this? I suspect most peoples apis are either no auth or all auth (excluding maybe a login endpoint), so this will save people time and mistakes by just turning on auth for all endpoints.

I think we should do what @marklawlor proposed except add the definition for the global security as a new field to the spec part of tsoa.json to make it clear the config will change the behaviour of the code.

```json
{
    "spec": {
        "securityDefinitions": {
            "my_security": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        },
        "rootSecurity": [{
            "my_security": []
        }]
    }
}
```
I think the format should match that of the [openapi spec for route security](https://swagger.io/docs/specification/authentication/#security) for simplicity, which helpfully also matches the [internal definition of security that tsoa uses](https://github.com/lukeautry/tsoa/blob/e311bdc95bb83fbec8458af9726f069e674e851c/packages/runtime/src/metadataGeneration/tsoa.ts#L33)

I've only read a bit of the codebase and I was initially thinking you could add this to the template generation with a new field - but that would make accounting for `@NoSecurity()` (Which has no explanation in the documentation) impossible.

Should be able to change https://github.com/lukeautry/tsoa/blob/e0579e3a53bde1828a88464fa191f8454674f046/packages/cli/src/metadataGeneration/controllerGenerator.ts#L112 to account for root level security so root level security would apply to all controllers which would apply to all methods (unless `@NoSecurity()`).

Thinking on it the metadataGeneration looks suspiciously like openapi ... is that what generates the openapi spec too? My suggestion would probably apply security to every method individually in the swagger.json .. which .. might be bad? (maybe not .. that's what everyone using this api is generating currently anyway)

I can have a go at making a PR for this, but I think your counter proposal confused people @WoH so I also don't want to work on this if it won't be accepted

**Comment by WoH** [comment]
My initial comments were trying to make sure this plays nicely with the [securityDefinitions](https://github.com/lukeautry/tsoa/blob/master/packages/runtime/src/config.ts#L175).

As you mentioned with rootSecurity, we should make sure we can differentiate properly between global and controller-wide Security. My initial suggestion was a simpler version of what you proposed (just a boolean, string or string[] indicating which definitions are global) but from what I can tell yours makes more sense.

**Comment by WoH** [comment]
> Thinking on it the metadataGeneration looks suspiciously like openapi ... is that what generates the openapi spec too?

Kinda, it's the base for both the SpecGenerator to build the spec and the routes stuff to generate the routes file.
