### ISSUE TITLE
Property Level Vendor Extension

### ISSUE THREAD

**Issue by DjakaTechnology** [lukeautry/tsoa#1085]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Allow us to generate vendor extension on property's attribute:
```yaml
    User:
      properties:
        name:
          type: string
          x-version: V3.36
```

```ts
export class User {

  /**
   * @example "John Doe"
   * */
   @Extension("x-version", "V3.36.0")
  name: string

}
```

## Current Behavior

Currently the `@Extension` annotation will be ignored and nothing happen
```yaml
    User:
      properties:
        name:
          type: string
```

## Possible Solution
`tsoa` should also consume the `@Extension` in the property model.

I've made an adjustment to `tsoa` so it can support those needs [on my fork](https://github.com/DjakaTechnology/tsoa/tree/feature/property-extension)

## Context (Environment)
Version of the library: v3.11.2

- Confirm you were using yarn not npm: [x]

## Detailed Description
Sometime we need to put a vendor extension on the property level, usually its for documentation purpose or internal tools needs. One of the example is [Microsoft's mutability](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-mutability) where it used to define mutabiltiy rule of the property.

My team currently using standard yaml and considering to migrate to tsoa for spec generation only. Our team require information of `Added since` so we create `x-version` as vendor extension so the documentation will look like this:

![image](https://user-images.githubusercontent.com/19620593/134001292-71a3765f-b30f-464e-96f3-7e1fd175371d.png) 

but during the assesment it seems `tsoa`  doesn't support property level vendor extension yet. 

## Breaking change?
No

**Comment by WoH** [comment]
Since we have an `Extension` decorator, this makes sense imo. Ideally, we should also read from an `@extension` JSDoc tag to cover interfaces.

**Comment by DjakaTechnology** [comment]
> Since we have an `Extension` decorator, this makes sense imo. Ideally, we should also read from an `@extension` JSDoc tag to cover interfaces.

Sounds good, I'll create a PR that read from both extension and JSDoc soon
