### ISSUE TITLE
minor "bug" with variable assignment of referenceType in typeResolver

### ISSUE THREAD

**Issue by simllll** [lukeautry/tsoa#1088]
I stumpled upon this code line, it's already there fore 3 years, but it still seems wrong to me:
https://github.com/lukeautry/tsoa/blob/bfa2c9ba1b43d845eb01a954cf9cbf37c529ef76/packages/cli/src/metadataGeneration/typeResolver.ts#L745

everything is assigned to the referenceType from realReferenceType, except the refName which is assinged to "itself".. I guess it's not doing any harm, due to the reason that refName is set before to the object anyways. 

So not reall a bug with an impact, but I guess it's still wrong ;)

**Comment by WoH** [comment]
https://github.com/lukeautry/tsoa/pull/1084 covers this
