### ISSUE TITLE
Documentation should mention that koa-body is required for use

### ISSUE THREAD

**Issue by Mossop** [lukeautry/tsoa#1093]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

When using with koa it seems that koa-body (or presumably something else that provides a value for `context.request.body`) is required to be installed and enabled.

## Current Behavior

Given a controller such as:
```ts
interface LoginParams {
  email: string;
  password: string;
}

export interface UserState {
  email: string;
  isAdmin: boolean;
}

@Route()
export class MainController extends Controller {
  @Post("login")
  public async login(@Body() params: LoginParams): Promise<UserState> {
    // ... implementation not important
  }
}
```

Without koa-body installed the koa template attempts to parse data from `context.request.body` which by default in koa is undefined. The validation then fails throws a rather confusing error about `params` not being defined.

## Possible Solution

Add some documentation specific to how to set up koa for use. Maybe add some notes to the @Body and @BodyProp decorators saying that koa-body is required for their use. This could also potentially be picked up as part of validation to give a nicer error to help developers who fail to find the docs.

**Comment by WoH** [comment]
Can you please file this [here](https://github.com/tsoa-community/docs)?

**Comment by huzaifahj** [comment]
@Mossop I have come across this issue too. Did you manage to file it?

```ts
app.use(koaBody())
```

should be added before

```ts
const router = new KoaRouter()
RegisterRoutes(router)
app.use(router.routes()).use(router.allowedMethods())
```
