### ISSUE TITLE
tsoa cli dependency vulnerability

### ISSUE THREAD

**Issue by grahamplata** [lukeautry/tsoa#1097]
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

tsoa doesn't contain high `HIGH SEVERITY` cve through dependencies 

## Current Behavior

Snyk Flags `tsoa@3.11.2` with a `HIGH SEVERITY` via 

```
Regular Expression Denial of Service (ReDoS)
Vulnerable module: ansi-regex
Introduced through: @tsoa/cli@3.11.2
```

[Link](https://app.snyk.io/test/npm/tsoa/3.11.2)

## Possible Solution

Update cli dependencies `yargs` to `15.3.0` as this clears all vulnerabilities 

## Steps to Reproduce

Run snyk cli against repo

## Context (Environment)

Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [X]

## Breaking change?

No

**Comment by WoH** [comment]
Fixed in [v4.0.0-alpha.0](https://github.com/lukeautry/tsoa/releases/tag/v4.0.0-alpha.0), see [Snyk Advisor](https://snyk.io/test/npm/tsoa/4.0.0-alpha.0).

**Comment by anttitakalahti** [comment]
could you also update it to v3 please?

**Comment by WoH** [comment]
No https://github.com/lukeautry/tsoa/pull/1098#issuecomment-946720968

**Comment by ReeceSwyftx** [comment]
@WoH is there any ETA on the next release?
