### ISSUE TITLE
Tsoa @UploadedFile and @FormField return undefined

### ISSUE THREAD

**Issue by midoelhawy** [lukeautry/tsoa#1099]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

__________________________________________________________________________________________________

I have a problem with Tsoa nodejs File upload 

I wrote the method based on the [tsoa documentation][1] but the output varible is always undefined 

This is my method 

[![enter image description here][2]][2]

> Blockquote

```typescript
  @Post('/uploadNewExporterTemplate')
  public async uploadNewExporterTemplate(
    @Query() templateName: string,
    @Query() unit: string,
    @Query() testWith: string,
    @UploadedFile() file: Express.Multer.File,
  )  {

    const mul = multer()

    
    console.log(file,unit,testWith);
    
    return {stat:"Ok",ss:templateName}
  }
```
And this is the swagger result 

[![enter image description here][3]][3]

and finally this the debug result 

[![enter image description here][4]][4]

[![enter image description here][5]][5]

  [1]: https://tsoa-community.github.io/docs/file-upload.html
  [2]: https://i.stack.imgur.com/YrNc0.png
  [3]: https://i.stack.imgur.com/pXeIZ.png
  [4]: https://i.stack.imgur.com/q9pdK.png
  [5]: https://i.stack.imgur.com/qQUfu.png

**Comment by midoelhawy** [comment]
The problem still exists

**Comment by WoH** [comment]
I'm not sure, but manually setting up multer again may be the reason maybe?

```ts
  @Post('/uploadNewExporterTemplate')
  public async uploadNewExporterTemplate(
    @Query() templateName: string,
    @Query() unit: string,
    @Query() testWith: string,
    @UploadedFile() file: Express.Multer.File,
  )  {
    console.log(file,unit,testWith);
    
    return {stat:"Ok",ss:templateName}
  }
```

Seems fine.

**Comment by midoelhawy** [comment]
I don't think so, because currently I'm using multer in request object to get around the problem.
i am using `@UploadedFile () file: Express.Multer.File,` just to show the input type file in the swagger interface, but the upload management I handle it outside of TSOA

**Comment by dhatGuy** [comment]
I'm experiencing this. The FormField values are returning undefined.

```
@Post("/")
  @Security("jwt")
  @Middlewares(imageUpload.single("image"))
  async newMenu(
    @FormField() title: string,
    @FormField() description: string,
    @FormField() price: number,
    @FormField() categoryId: number,
    @FormField() cafeteriaId: number,
    @UploadedFile() image: Express.Multer.File | undefined
  ): Promise<menu> {
    ...
  }
```

And I get this error
```
Caught Validation Error for /api/menus: {
  title: {
    message: "'title' is required",
    value: undefined
  },
  description: {
    message: "'description' is required",
    value: undefined
  },
  price: {
    message: "'price' is required",
    value: undefined
  },
  categoryId: {
    message: "'categoryId' is required",
    value: undefined
  },
  cafeteriaId: {
    message: "'cafeteriaId' is required",
    value: undefined
  }
}
```

Using Postman
![image](https://user-images.githubusercontent.com/51405947/161252130-9bad2bfc-c3c7-4e3f-92dc-030efc3c7aeb.png)

**Comment by Typiqally** [comment]
This issue still persists, has any fix been found?

**Comment by webdevprashant** [comment]
I am getting same issue, Any solution to debug this issue

**Comment by Flecart** [comment]
I'm getting this issue too

**Comment by pharapeti** [comment]
Likewise

**Comment by mjroeleveld** [comment]
Same problem.

**Comment by ZumelzuR** [comment]
same issue here

**Comment by MMagesh23** [comment]
Same issue

**Comment by sephentos** [comment]
Does anyone have an alternative otherwise to get a FormData or json payload and a file upload at the same time? Would be really nice if this problem could be solved otherwise

**Comment by Fortur** [comment]
same
