### ISSUE TITLE
OpenAPI extension

### ISSUE THREAD

**Issue by fwiedmann** [lukeautry/tsoa#1102]
Hey!

What are your thoughts about adding the possibility to define spec extension in the tsoa.json?

https://swagger.io/docs/specification/openapi-extensions/

For example I would like to add the x-logo field in the info object.

**Comment by fwiedmann** [comment]
Sorry that I didn't fill the default issue template. I'm in the GitHub Mobile App and no template was shown.

**Comment by WoH** [comment]
My thought is that's already possible.

**Comment by fwiedmann** [comment]
How? 😊

**Comment by fwiedmann** [comment]
As far I understood the source code that the info object will only be generated from the information in the package.json.

**Comment by WoH** [comment]
https://github.com/lukeautry/tsoa/blob/master/packages/runtime/src/config.ts#L128 ff

**Comment by fwiedmann** [comment]
Thanks, I've missed the specMerging field!

**Comment by fwiedmann** [comment]
So I've tried to add the `x-logo` extension field and specified `specMerging`.

In the `tsoa.json`:

```json
"specMerging": "recursive",
  "spec": {
   ...
    "info": {
      "x-logo": {
        "url": "https:example.com",
        "altText": "Company Logo"
      }
    },
  ...
    }
```

After running `tsoa spec`, the generated spec does not contain the x-logo field.
