### ISSUE TITLE
Problems with Line-Endings in Git after rebuild of spec

### ISSUE THREAD

**Issue by panwauu** [lukeautry/tsoa#1106]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Two rebuilds should not lead to a git diff.

## Current Behavior

If I change branch and rebuild the swagger.json, the file is moddified in git. Git diff leads to:
```
warning: LF will be replaced by CRLF in server/src/swagger.json.
The file will have its original line endings in your working directory
```
I am using Windows btw.

Has somebody already faces this issue and is able to give me a hint? 
Thanks you all for your help and for this great library.

**Comment by pauliyobo** [comment]
Hello.
@panwauu 
It looks like your line endings configuration are set to CRLF, while tsoa utilizes LF, which may lead to the issue you are facing
Consider giving a look [here](https://git-scm.com/book/it/v2/Customizing-Git-Git-Configuration#_core_autocrlf) to see how to change your line endings.
Hope this helps
