### ISSUE TITLE
request.user from authentication is undefined in Koa controller

### ISSUE THREAD

**Issue by kingjerod** [lukeautry/tsoa#111]
I can't get the user set inside a Koa app from the authentication. The authentication.ts is just:

`return Promise.resolve({'name' : 'Bob'});`

I've double checked inside the routes.ts file that the user is getting set:

```
koaAuthentication(context.request, name, scopes).then((user: any) => {
    set(context.request, 'user', user);
    console.log('User inside routes.ts: ', context.request.user); // prints out {'name' : 'Bob'}
    next();
})
```
Inside controller:
```
@Get('current')
@Security('test')
async getUser(@Request() request: any) : Promise<ApiResponse>  {
    console.log('User in controller: ', request.user); //undefined
}
```

Is the injection putting in the incorrect request? I can't find where in the source code it gets injected.

**Comment by kingjerod** [comment]
I figured it out. There is a second request object under the injected request object that contains the user in the controller. This is rather confusing and not documented.  Example:

```
  @Get('getUser')
  @Security('api_key')
  @Response(404, "User not found")
  async getUser(@Request() request: any) : Promise<ApiResponse>  {
    console.log(request.user); //undefined
    console.log(request.request.user); //it's here
  }
```

**Comment by oreporan** [comment]
Is this still the case? Do I need to put `request.request.user` in order to get the user object? This is not how its documented...

**Comment by dgreene1** [comment]
@oreporan the documentation in the readme is up to date with Koa.
