### ISSUE TITLE
How can I create nested routes?

### ISSUE THREAD

**Issue by Muratcol** [lukeautry/tsoa#1114]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Being able to create nested routes with tsoa

## Current Behavior

here is a controller that I am currently using. With this, I can continue operations such as GET, POST, PUT. However, I want to add a new controller to this controller by forwarding this address.

Currently I'm using this: GET, PUT, POST `/v2/dataset/{datasetId}`

And I want to connect a new controller after that step, (Also been able to reach `datasetId` and  `feedId` params)

GET, PUT, POST  `/v2/dataset/{datasetId}/feed/{feedId}`

```
ts

@Route("dataset")
export class DatasetController extends Controller {

    @Get("{datasetId}/feed/{feedId}")
    public async get(
        @Path() datasetId: string
        @Path() feedId: string
    ): Promise<Dataset> {
        // *****  In some way, I want to bind/call a new controller at this stage continue my operations with new sub-controllers. *****
        return new DatasetServices().get(datasetId);
    }
    @SuccessResponse("200", "Created") // Custom success response
}
```

**Comment by asontha** [comment]
any update here?

**Comment by PetrKubes97** [comment]
I've found this issue since I didn't see it in the docs, but 

@Route('/v2/dataset/{datasetId}/feed/') 
export class FeedController... {

}

seems to work out of the box.
