### ISSUE TITLE
Request to add a github action to the repo 

### ISSUE THREAD

**Issue by Jassi10000** [lukeautry/tsoa#1116]
Feature request :
This is an awesome and an engaging repository , plus due to hacktoberfest'21 many open source enthusiasts ( preferably students who are first time contributors ) open issues and PRs which eventually help repo to grow
I think there should be a github action to welcome contributors on their each issue and PR so as to make repository more interactive

If you love the idea , please assign this to me

**Comment by WoH** [comment]
Would be a nice addition, please go ahead 👍🏽

**Comment by Jassi10000** [comment]
For this the assignment is not needed  ?

**Comment by WoH** [comment]
We usually don't assign tasks.

**Comment by Jassi10000** [comment]
Ok sure , will send a PR soon
