### ISSUE TITLE
Destructuring parameter missing

### ISSUE THREAD

**Issue by ugrg** [lukeautry/tsoa#1120]
## Sorting
  - [*] bug report
  - [ ] feature request
  - [ ] support request

## Expected Behavior
Correct generation parameter list
正确的生成参数列表。

## Current Behavior
目前情况是运行时报错，显示session无法从undefined中解构
TypeError: Cannot destructure property 'session' of 'undefined' as it is undefined.

## Possible Solution
可以考虑为匿名变量生成一个别名，而不是现在的undefined.
Generate an alias for the anonymous variable instead of undefined

## Steps to Reproduce
```ts
@Route('demo')
class Demo extends Controller{
    @Pose()
    login(
       @Body() {username,password}:{username:string,password:string},
       @Request() {session}:express.Request
    ){    
        return {message:'test'}
    }
}
```

## Detailed Description
我观察了一下生成的`routes.ts`，其中的args被设置成了
I looked at the generated routes. Ts, where args is 
```json
{
        undefined: {"in":"request","required":true,"dataType":"object"},
}
```

**Comment by WoH** [comment]
Is it correct to assume `@Pose` is a typo in the description, not the source?

**Comment by karlismelderis** [comment]
I think we hit same bug.
at it worked in some past versions.

used to work
```ts
@Body() {apples, oranges}: OrchardPostBody,
```

now we need change to:
```ts
    @Body() body: OrchardPostBody,
  ): Promise<void> {
    const {apples, oranges} = body;
```
