### ISSUE TITLE
Suggestions for / Problems with default MiddlewareTemplate

### ISSUE THREAD

**Issue by schirkan** [lukeautry/tsoa#113]
1. Typo in `README.MD` in section "Override route template":
"mi**n**ddlewareTemplate" -> "middlewareTemplate"
2. Import statemant for `lodash` throws compile error. User `require('lodash')`
3. Don't set `request.user` in `authenticateMiddleware()`. This should be done in the authentication module. (eg. passport) => No need for `lodash` module anymore
4. Controller methods can also return non Promise-types. The `promiseHandler()` could easily handly this by using: `return Promise.resolve(promise).then((data: any) => { ...`

**Comment by isman-usoh** [comment]
@schirkan Thank you.
