### ISSUE TITLE
koa integration overwrites content-type of response

### ISSUE THREAD

**Issue by mrl5** [lukeautry/tsoa#1134]
This applies only to koa (express and hapi properly return `content-type`) and is related to this known koa bug https://github.com/koajs/koa/issues/1120 - I've discovered it while working on PR #1129 (https://github.com/lukeautry/tsoa/pull/1129#pullrequestreview-803538341)

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [ ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

koa returns custom `content-type` just like express and hapi currently does

## Current Behavior
koa ignores `this.setHeader('content-type', 'application/vnd.mycompany.myapp.v2+json');` and returns `application/json`

## Possible Solution

as described in https://github.com/koajs/koa/issues/1120#issue-287864646 by @brunoabreu
> I can make it work if I write the header after setting the body. It only affects json responses.

so the solution is as simple as this:
```diff
diff --git a/packages/cli/src/routeGeneration/templates/koa.hbs b/packages/cli/src/routeGeneration/templates/koa.hbs
index 6716837..b2d2ee9 100644
--- a/packages/cli/src/routeGeneration/templates/koa.hbs
+++ b/packages/cli/src/routeGeneration/templates/koa.hbs
@@ -204,8 +204,6 @@ export function RegisterRoutes(router: KoaRouter) {
 
     function returnHandler(context: any, next: () => any, statusCode?: number, data?: any, headers: any={}) {
         if (!context.headerSent && !context.response.__tsoaResponded) {
-            context.set(headers);
-
             if (data !== null && data !== undefined) {
                 context.body = data;
                 context.status = 200;
@@ -217,6 +215,7 @@ export function RegisterRoutes(router: KoaRouter) {
                 context.status = statusCode;
             }
 
+            context.set(headers);
             context.response.__tsoaResponded = true;
             return next();
         }
```

## Steps to Reproduce

1. use `koa` as a server
2. use this controller:
```ts
@Route('MediaTypeTest')
export class MediaTypeTestController extends Controller {
  @SuccessResponse('202', 'Accepted')
  @Post('Custom')
  async postCustomProduces(@Body() model: UserRequestModel): Promise<UserResponseModel> {
    const body = { id: model.name.length, name: model.name };
    this.setStatus(202);
    this.setHeader('content-type', 'application/vnd.mycompany.myapp.v2+json'); // express and hapi returns it, koa ignores
    return body;
  }
}
```
3. generate routes
4. do request (e.g. with `curl`)
```bash
$ curl -i \
    -H 'content-type: application/json' \
    -X POST -d '{"name": "foo"}' \
    http://localhost:3000/MediaTypeTest/Custom
```

## Context (Environment)

Version of the library: `3.14.0`
Version of NodeJS: `v14.17.6`

- Confirm you were using yarn not npm:
  [x] I confirm I've used `yarn`

## Detailed Description

I think everything was described already

## Breaking change?

hard to tell, I guess not

**Comment by mrl5** [comment]
I can provide a fix if maintainers agree that it's a bug that can be fixed as proposed

**Comment by WoH** [comment]
Seems like a no-brainer, can you open a PR?

**Comment by mrl5** [comment]
> Seems like we should obviously fix this, can you open a PR?

how about pushing additional commit that fixes it to the https://github.com/lukeautry/tsoa/pull/1129 ? this is kind of related and additional benefit is that I can introduce integration tests :)
