### ISSUE TITLE
tsoa 4: Require TypeScript >=4.1

### ISSUE THREAD

**Issue by WoH** [lukeautry/tsoa#1135]
I'm thinking about requiring TypeScript >=4.1 for the next major version of tsoa.
However, I would like to gather some feedback before making a final decision.

## Why?

Template Literal Types: We can't use them, or we'd have to ship type definitions for both >=4.1 and <4.1, and I'm not really interested in maintaining both.

## What can you do?
Vote thumbs up if you're on TypeScript >=4.1, or are in the process of upgrading if we ship tsoa 4, thumbs down if that would be something you want to avoid.

**Comment by AudunWA** [comment]
I'm all for requiring a newer version of TypeScript to enhance tsoa! Here are my thoughts:
* tsoa is built around TypeScript's strong type system, and improvements in TS will probably be positive for tsoa as well.
* TypeScript 4.1 is more than a year old and should be well adopted by now. Personally I'd jump straight to TS 4.2+ (all the way to 4.5?) if it introduces changes that can benefit tsoa. Of course, we don't want to require a new version if it doesn't bring anything to the table, as it will keep users from upgrading if they can't upgrade TS yet.

**Comment by WoH** [comment]
Maybe a bit of context: I'm working on fixing the breaking changes in order to use the TS 4.5 Compiler API in the cli (for type analysis), which is mostly unrelated to the TS version a user needs to be on. TypesScript code written for 4.1 can be analyzed with the 4.5 Compiler API just fine, even if the type checker would find issues.

What's creating the breaking change at hand are the type declarations we generate as exports. These ones need to be understood by the user's TS version.

**Comment by WoH** [comment]
Also, as a PSA: I released the first alpha for 4.0.0 so everyone can make sure there are no unforseen issues.
