### ISSUE TITLE
Website link is broken

### ISSUE THREAD

**Issue by alexandervandekleutab** [lukeautry/tsoa#1136]
- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

On this page:
https://tsoa-community.github.io/docs/decorators.html

The first link for `@Response` links to https://tsoa-community.github.io/docs/%22error-handling%22 which 404s. You want it to link to https://tsoa-community.github.io/docs/error-handling.

**Comment by WoH** [comment]
Please file/fix this in the [docs repo](https://github.com/tsoa-community/docs/issues).
