### ISSUE TITLE
OIDC Security OpenAPI `openIdConnect`

### ISSUE THREAD

**Issue by E-gy** [lukeautry/tsoa#1137]
Add \[explicit\] support for OpenAPI 3 security scheme with [`type: openIdConnect`](https://swagger.io/docs/specification/authentication/openid-connect-discovery/).

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Detailed Description

OpenAPI 3 ([as well as 3.1](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#security-scheme-object)) provide support for Open ID Connect Discovery security scheme, with
```yaml
type: openIdConnect
openIdConnectUrl: https://example.com/.well-known/openid-configuration
```

The corresponding interface has to be declared and added to the [`Security`](https://github.com/lukeautry/tsoa/blob/master/packages/runtime/src/swagger/swagger.ts#L382) type, and the addition documented.

PS: Because JS and types and such, declaring
```json
"securityDefinitions": {
	"oidc": {
		"type": "openIdConnect",
		"openIdConnectUrl": "https://example.com/.well-known/openid-configuration"
	}
}
```
in `tsoa.json` generates corresponding YAML correctly. This issue is more about typed/_explicit_ support for it & documentation.

## Breaking change?

Nope, just _explicit_ support & documentation for a security schema.

**Comment by meehawk** [comment]
Hi @WoH I'd like to take up on this issue. This is my first time contributing to TSOA and any guidance will be awesome
