### ISSUE TITLE
Support local Declaration (.d.ts) Files

### ISSUE THREAD

**Issue by carlnc** [lukeautry/tsoa#1138]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behaviour

In our projects we declare our types in `.d.ts` files.

For example:

(`controllers/person/PersonController.ts`)
```ts
import { Controller, Get, Path, Route } from 'tsoa';
import { PersonService }                from './personService';

@Route('/customer/{customerId}')
export class PersonController extends Controller {

    @Get('/people/{personId}/hobbies')
    public async getHobbies(
        @Path() customerId: string,
        @Path() personId: string,
    ): Promise<ServiceA.Person.Hobbies> {
        return (new PersonService()).getHobbies(customerId, personId);
    }
}
```

(`controllers/person/Person.d.ts`)
```ts
// An example with a namespace
namespace ServiceA.Person {
    type Hobbies = Hobby[];
    interface Hoby {
        name: string;
        frequency: number;
        frequencyUnit: 'perDay' | 'perWeek' | 'perMonth';
    };
}
```

When running `tsoa spec` or `tsoa routes` I get the error:

```
Error: No declarations found for referenced type Hobbies.
```

From what I can tell, it appears that tsoa filters out `.d.ts` files ([here](https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/utils/importClassesFromDirectories.ts#L13) used by [here](https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/metadataGeneration/metadataGenerator.ts#L44)), even ones in that would be normally listed in `tsconfig.json`'s "`include`" property.

If I modify [the call to `ts.createProgram()`](https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/metadataGeneration/metadataGenerator.ts#L44) to include the local `.d.ts` files, `spec` and `route` work. 👍 

I'm wondering, is there a better way to allow the local `.d.ts` files to be exposed to the typescript (ts) program/compiler?

## Possible Solution

Perhaps adding a new option to `tsoa.json`?

For example:

```json
{
  "controllerPathGlobs": [
    "src/**/*Controller.ts"
  ],
  ...
  "declarations": [
    "src/",
    "../../shared-mono-repo-package/types/"
  ]
}
```

If the `declarations` array is provided then
-  those folders/files could be `glob`ed for `.d.ts` files
- which could then included in the list of files passed to `ts.createProgram()`

## Context (Environment)

Version of the library: 3.14.0
Version of NodeJS: v14.15.4

- Confirm you were using yarn not npm: - Neither.  `pnpm`

## Breaking change?

* Shouldn't be a breaking change

**Comment by cwilso03** [comment]
I'm encountering this same issue.  What's the official TSOA recommended way to handle such conditions?  I see the bot marked the issue as stale and then closed it.  Should I open a new issue?
