### ISSUE TITLE
Generate routes: Error: Unknown type: AnyKeyword.

### ISSUE THREAD

**Issue by kingjerod** [lukeautry/tsoa#114]
If I have a controller method return `Promise<any>` the route generation (and swagger) throws this error. Seems like any is not supported?

**Comment by connected-jlovelock** [comment]
Also having this issue.

**Comment by isman-usoh** [comment]
Fix: 0534cbdbe2931efb58b0ee1d1780632bb3869b76

Example https://github.com/lukeautry/tsoa/blob/0534cbdbe2931efb58b0ee1d1780632bb3869b76/tests/fixtures/controllers/methodController.ts#L102
