### ISSUE TITLE
Can't access response in authentication function

### ISSUE THREAD

**Issue by eungkyu** [lukeautry/tsoa#1145]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I want to set header or cookie in authentication function

## Current Behavior

I can't access the response In authentication function,
so that I can't manipulate header nor cookies in expressAuthentication function

## Possible Solution

Pass response object to authentication function

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 3.14.1
Version of NodeJS: 16.13.0

- Confirm you were using yarn not npm: [ ]

**Comment by SalhiYassine** [comment]
Any news on this?

**Comment by normandanielmq** [comment]
Any news?

**Comment by fage88** [comment]
Can this be re-opened?

I want to be able to access the koa response object to validate a user has access to an object before we return it to them (based on the scopes in the @Security annotation)
