### ISSUE TITLE
Koa generated routes overlaps on fixed & variable paths

### ISSUE THREAD

**Issue by ClemWiz** [lukeautry/tsoa#1147]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Given this controller:
```ts
import { Controller, Get, Path, Route } from "tsoa";

@Route("/test")
export class TestController extends Controller {
    @Get("/all")
    async getAll(): Promise<number[]> {
        return [1,2,3];
    }

    @Get("/{id}")
    async getOne(@Path() id: number): Promise<number> {
        return id;
    }
}
```

I should receive
```json
[1, 2, 3]
```
when consuming `/test/all`;

## Current Behavior
But I receive:

```json
{
    "fields": {
        "id": {
            "message": "invalid float number",
            "value": "all"
        }
    }
}
```
As i set breakpoints in debug mod, I can see that the first route is called, then the second one and the validation fails on the second call. I feel like there is a next/middleware call that shouldn't happen, but I fail to capture the way `tsoa` is built and generate the routes' templates.

## Possible Solution
I know it's not a real solution, but if I comment the line
`return next();`
in the `returnHandler(...)` method of the generated `routes.ts`, I have the correct behavior.

## Steps to Reproduce
To reproduce the current behavior:
1. You can clone this [repo](https://github.com/ClemWiz/tsoa-paths)
2. Launch the server using `yarn start`
3. Use `curl --location --request GET 'localhost:8080/test/all'`

If you want the correct behavior (without using `tsoa`), you can:
1. Comment the l.12 `RegisterRoutes(router);` 
2. Un-comment the l.9-10.
3. Use `curl --location --request GET 'localhost:8080/test/all'`

## Context (Environment)

Version of the library: 3.14.1
Version of NodeJS: 14.16.1

- Confirm you were using yarn not npm: [x]

## Detailed Description

Has I said, I'm not familiar with the `tsoa` source code and I fail to understand a lot of mechanics used here. So I can't provide any good change that won't brake the whole purpose of the library. I can only guess that - at some point - the generated template tools functions keep calling `next` until they either fail to match the route path (so route is considered "consumed") or fail to validate the given arguments (so an exception is raised).

If my guesses are right, maybe we should not allow the first behavior and stop calling next when we matched at least one path.
I know that `koa` fixed their [existing bug](https://github.com/koajs/router/releases/tag/v9.1.0)) with same behavior [using](https://github.com/koajs/router/pull/93) a `context._matchedRoute` property, and I can see the value shifting between calls (first value is `"test/all"`, second value is `"test/:id"`)

**Comment by WoH** [comment]
The issue is that the routes are overlapping. Didn't you get a warning when you generated the routes?

**Comment by ClemWiz** [comment]
No, you can try it with the repo I gave, the routes are generated without problem:
```sh
[*** tsoa-paths](main)$ yarn tsoa routes
yarn run v1.22.17
$ ***/tsoa-paths/node_modules/.bin/tsoa routes
Done in 1.33s.
```

```ts
export function RegisterRoutes(router: KoaRouter) {
        // [...]
        router.get('/test/all',
            async function TestController_getAll(context: any, next: any) {
            // [...]
        });
        // WARNING: This file was auto-generated with tsoa. Please do not modify it. Re-run tsoa to re-generate this file: https://github.com/lukeautry/tsoa
        router.get('/test/:id',
            async function TestController_getOne(context: any, next: any) {
            // [...]
        });
```

**Comment by mrl5** [comment]
+1

I also came across this bug - many thanks @ClemWiz for reporting.

It's actually the only stopper for me for switching from express to koa

**Comment by WoH** [comment]
This should generate a warning. If there's a difference between express and koa, we should mitigate that if possible.

**Comment by mrl5** [comment]
> This should generate a warning. If there's a difference between express and koa, we should mitigate that if possible.

if I understand correctly there are 2 things to be done:
1. ensure that code generated for `koa` behaves just like code generated for `express`
2. agnostic fix (both `koa` and `express` or whatever else) that generates warning for case when both `router.get('/test/:id')` and `router.get('/test/all'` are defined?

pls correct me if I'm wrong @WoH

**Comment by ClemWiz** [comment]
I've searched a bit on how koa/koa-router handle routes and `next` and it seems that routes doesn't need to return `next()`. In fact nothing has to be returned. The only thing that could be returned without blowing things up is `context`.

https://github.com/koajs/router/blob/1aead99e0e0fdb8666e9c6fa2f52b0463c622025/lib/router.js#L80

I've tried some hacks on the generated `routes.ts` and it seems to work, but I'll need someone to look over my shoulder in case I'm going in the wrong direction:
```ts
function returnHandler(context: any, next: () => any, statusCode?: number, data?: any, headers: any={}) {
    if (!context.headerSent && !context.response.__tsoaResponded) {
        // ...
        return next ? next() : context; // if next is not given, return context
    }
}
```

```ts
router.get('/test/all',
    async function TestController_getAll(context: any, next: any) {
        // ...
        // last argument next -> undefined
        return promiseHandler(controller, promise, context, undefined, undefined);
});
```

**Comment by Shiou-Ju** [comment]
Hi, everyone! 

Before the PR, I made a temporary workaround by adding a `middleware` implemented to check if a flag intentionally set in `ctx` is altered, at each route.  

Whenever a route path consumes and shall not pass ctx to another path at same route, this middleware returns ctx without calling next and things work fine to me.

An example of such middleware shown as below.  Shall be placed at each route using `@Middlewares` decorator.

```ts
const workaroundMiddleWare = () => {
  const middleware = async (ctx, next) => {
    const shallReturnCtx = !!ctx.body?.someFlag;
    if (shallReturnCtx) {
      return ctx;
    }

    return await next();
  };

  return middleware;
};

```
