### ISSUE TITLE
Serialize and Parse Metadata

### ISSUE THREAD

**Issue by dpomerantz-jci** [lukeautry/tsoa#1149]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I would like the option to save the metadata discovered by tsoa instead of using it to generate specs or routes.  Further, I would like tsoa to be able to load metadata from a file.  This would allow us to make small tweaks to the model.

## Current Behavior

The metadata is discovered, used, and destroyed with each involcation of tsoa.

## Possible Solution

I have already written a solution.  Sorry for not creating the ticket first.  The solution is to do the following:
1)	Add a new option to cli so that it can save the metadata file as a serialized xml or yaml file.

2)	Add an option to the tsoa.json configuration file which directs tsoa to load metadata from a file rather than discover it.

- Confirm you were using yarn not npm: [x]

## Detailed Description

I think the general description covers it.  Add a new option "metadata" which saves the metadata as a json/yaml file.  Add another option which allows metadata to be parsed from that file if so configured.

## Breaking change?

No

**Comment by WoH** [comment]
I'm not sure if I can derive a use case based on the issue description yet, but my initial feeling is that this may be too niche to be part of tsoa. To enable this, the existing primitives (custom template + `generateRoutes()`) could be combined to make this possible.

Maybe you can provide more details on which part of the metadata you'd be interested in, since I'd consider this internal data whose format may change between minor/patch releases.

**Comment by dpomerantz-jci** [comment]
Thank you for your review and questions on this request.  I would be open to an alternative where a "plugin interface" could be developed so that I specify a method to alter the metadata directly in memory, however I'm not sure that I feel comfortable developing that as it would be more disruptive to the application.  The goal is to allow the metadata to be modified so that the generated spec and routes are modified as desired.

My use case is as follows:  We use express on node to build our models and controllers, and so our data model follows the ts norm using PascalCase and camelCase.  For reasons beyond my control, we are required to publish our APIs in snake_case, and so the goal is to find a way to develop in camelCase, but send/receive snake_case on the wire.  Through my research, I have found that the way to do that is to use express middleware, like express-humps to modify the json, but that happens outside of tsoa, and leaves us with a need to modify the spec and route files to match our output from humps.  I evaluated a few options, and the one with the lowest impact appeared to be serializing the metadata to a file, running humps on the appropriate parts of the metadata, then parsing it back into metadata for generating of spec and routes.

I would be open to alternatives which allow us to meet our use case, but as I mentioned, I already developed this feature.  I am working through some GitHubt authentication issues, and hope to have a PR created for it today.  

Thanks!

**Comment by dpomerantz-jci** [comment]
I created a PR which would resolve this feature request.  I understand that before it is merged, the feature will need to be reviewed and accepted, but I wanted to get up here for further review itself.

https://github.com/lukeautry/tsoa/pull/1150

**Comment by dpomerantz-jci** [comment]
Another option has come to mind:  I have no problem modifying swagger.json after creation, but route.ts is a bit more involved.  Since tsoa uses lodash templates and lodash can do the same thing as humps, could the express routes template be updated to do what I am asking?  For instance, I see the following:

        {{#if properties}}
        "dataType": "refObject",
        "properties": {
            {{#each properties}}
            "{{@key}}": {{{json this}}},
            {{/each}}
        },
        "additionalProperties": {{{json additionalProperties}}},
        {{/if}}

What would we need to do to tell the template executor to perform a lodash transformation on @key inside of {{ and }}?  I will try to look at the tsoa, but if you are able to explain and answer if this would be a valid solution, we may be able to move on and close this.

Thank you in advance.

**Comment by WoH** [comment]
I hate to suggest adding another middleware to the bloated stack I tend to see with express apps, but you could add one that handles the translation between casing and post process the openapi doc in a similar fashion

**Comment by dpomerantz-jci** [comment]
I have looked at the handlebars documentation, and it looks like we may be able to use a helper.  I will look into this to see if it is able to be used without changing tsoa code.  Thanks.

**Comment by dpomerantz-jci** [comment]
Thank you.  express-humps, mentioned above, is a thin middleware which will translate between camel and snake case.  It's small and does one thing.  This appears to be what you recommend.  We can do the same thing with the swagger spec, no problem.  The issue for me is the routes.ts file, which is less structured.  This is why munging the metadata before routes is generated fixes the issue for us, and if we are munging it for routes, we might as well munge it for specs too.  This is why the feature makes sense, because we can use the same utility (humps) to convert type and property names to snake case in both express and in the generated tsoa files, but we need access to the metadata before it is generated, hence the feature request.

I have looked into handlebars, and we could probably do something similar for routes by adding a helper and modifying the template (We would still have to separately change swagger.json after creation).  The roadblock I am seeing here is that to do that we would have to change tsoa code to register the helpers.  Would you be amenable to adding arbitrary helpers to tsoa, or creating an interface for users to register their own helpers before template execution?  Otherwise, I don't see a way to add helpers, and I think that's what you were saying.

My preferred approach is still to add a way to write a function which gets called after a metadata is created, but I'm not sure how to do that.  My next preference is to serialize and parse the metadata.  Are you considering accepting that feature?

**Comment by WoH** [comment]
>  This appears to be what you recommend. We can do the same thing with the swagger spec, no problem. The issue for me is the routes.ts file, which is less structured. This is why munging the metadata before routes is generated fixes the issue for us, and if we are munging it for routes, we might as well munge it for specs too. This is why the feature makes sense, because we can use the same utility (humps) to convert type and property names to snake case in both express and in the generated tsoa files, but we need access to the metadata before it is generated, hence the feature request.

I think there's a fundamental difference here in thinking about the validation. 
If the middleware runs before validation (which is my assumption), it'll supposedly change the casing from snake to camel and therefore subsequently pass the validation that's declared in camelCase.

> Would you be amenable to adding arbitrary helpers to tsoa, or creating an interface for users to register their own helpers before template execution? Otherwise, I don't see a way to add helpers, and I think that's what you were saying.

More likely than exposing internal metadata.

**Comment by dpomerantz-jci** [comment]
> I think there's a fundamental difference here in thinking about the validation. If the middleware runs before validation (which is my assumption), it'll supposedly change the casing from snake to camel and therefore subsequently pass the validation that's declared in camelCase.

I'm sorry, but I'm not sure I'm following this.  We want to convert from camel to snake out-bound, and snake to camel in-bound.  We want our domain objects to be in camelCase, but the wire format to be snake case.

> > Would you be amenable to adding arbitrary helpers to tsoa, or creating an interface for users to register their own helpers before template execution? Otherwise, I don't see a way to add helpers, and I think that's what you were saying.
> 
> More likely than exposing internal metadata.

I'm fine with this.  Ideally I could write a function in a specific format, and use a config file to call it.  It should also be faster at build time.  I'm not sure that I possess the skills to make such a change to tsoa, but I've already written a method in the format `function munge(metadata: Tsoa.Metadata)`.  Since you are not in favor of serializing the metadata, it's simpler to maintain a fork which has one additional line.  Will you accept that request and allow us to utilize it?

**Comment by WoH** [comment]
> I'm sorry, but I'm not sure I'm following this.  We want to convert from camel to snake out-bound, and snake to camel in-bound.  We want our domain objects to be in camelCase, but the wire format to be snake case.

That's exactly what I'm talking about.

> I'm fine with this.  Ideally I could write a function in a specific format, and use a config file to call it.  It should also be faster at build time.  I'm not sure that I possess the skills to make such a change to tsoa, but I've already written a method in the format `function munge(metadata: Tsoa.Metadata)`.  Since you are not in favor of serializing the metadata, it's simpler to maintain a fork which has one additional line.  Will you accept that request and allow us to utilize it?

Yes ofc, this is a MIT licensed project.

**Comment by dpomerantz-jci** [comment]
Please accept this thread as a request to add the feature where custom functions can be plugged in and run after metadata is collected, but before files are created.  If you need me to create a new thread for that, please let me know, and I will.  Thanks!
