### ISSUE TITLE
Library code includes TS code

### ISSUE THREAD

**Issue by satvik-s** [lukeautry/tsoa#1151]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Only `dist` should be exported as part of the library

## Current Behavior

Currently, inside `node_modules` `src` as well as `dist` are present

## Possible Solution

Update `tsconfig` or `npmignore` to exclude `src` from exported package

## Steps to Reproduce

- install latest version from npm
- check `node_modules/@tsoa`

## Context (Environment)

Version of the library: `3.14.1`
Version of NodeJS: `14`

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
@satvik-s can you explain what this bug is and how it is affecting you?

**Comment by satvik-s** [comment]
@WoH when I install `tsoa`, `src/` is also present which I think should not be part of the exported library code

```
$ ls node_modules/tsoa/src
cli.ts		index.ts
```

the convention is to only have `node_modules/tsoa/dist` present in exported code

i think the linked PR should fix it

**Comment by WoH** [comment]
I get what you are suggesting, but even if it were a convention, it's not a good trade-off imo. If the advantage is really only a small reduction in download size, but you lose the ability to jump into your node_modules, fiddle with the source and try out quick hacks or easily debug your dependencies, I'm not convinced it's worth making that change.

**Comment by satvik-s** [comment]
`.ts` code although readable won't be executed right? even if someone was to play around with it, the changes made in those files won't be reflected back, so they end up becoming more like good docs

i wanted to raise it up as i thought it might have been missed when setting up the library but if it is a conscious decision, I do not feel that strongly to not include that
