### ISSUE TITLE
Allow derived middleware variables

### ISSUE THREAD

**Issue by satvik-s** [lukeautry/tsoa#1152]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

If there is a middleware that accepts a header like `x-user-data` and goes on to JSON-ify that and add variables like `username`, `ip`, etc. to the request before passing to the controller, how can that be generated in spec?

## Current Behavior

The only way I can imagine that being possible currently would be like the following

```ts
    @Post()
    @OperationId('testId')
    public static async controller(
        @Body() body: BodyType,
        @Header('x-user-data') username: string,
        @Inject() ip: string,
```

## Context (Environment)

Version of the library: `3.14.1`
Version of NodeJS: `14`

- Confirm you were using yarn not npm: [ ]

## Detailed Description

I might have missed some part of code that allows for what I am trying to achieve here. If that is the case, please do point out. Otherwise, would be happy to hear thoughts regarding this

**Comment by rkulla-hbo** [comment]
👍

**Comment by WoH** [comment]
Please take a look at Method Decorators. You can write your own one, tsoa already skips `@Inject()` annotations. The Decorator can wrap the original method, extract the header and pass whatever you want into the placeholders (`@Inject()` params)

You'd write something like 

```ts
@ExtractHeader()
@Post()
public async handle(
  @Header('x-whatever') whatever, // So this is documented
  @Inject() ip,
  @Inject() somethingElse
) ...
```

**Comment by mgarabedian** [comment]
@WoH Ive been trying to figure this out. Do you have an example for  @ExtractHeader(), which would somehow populate 'userName'?  I don't understand how the injection works

**Comment by ChrisSimoniMBT** [comment]
+1 on wanting to know how this ectract header decorator works on wrapping the controller function
