### ISSUE TITLE
How to update Swagger UI?

### ISSUE THREAD

**Issue by Muratcol** [lukeautry/tsoa#1155]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

In our API we use TSOA to create routes and swagger documentation. And it works very well. We are very pleased.

However, I am using an example that is in the repo and I think the `swagger-ui` folder in this example is old, so the interface looks old and I cannot choose the servers to which the requests will be sent.

[This](https://github.com/lukeautry/tsoa-example/tree/master/src/swagger-ui) is the `swagger-ui` I'm using in my app

How can I update this `swagger-ui` file. I couldn't find a resource on this topic in the documentation.

This is my current UI

![Screenshot (71)](https://user-images.githubusercontent.com/58704132/146367225-d03617f6-1122-477d-8895-e05bb52173c1.png)

Expected behavior: (Another API using swagger):

<img width="1279" alt="Screenshot (73)" src="https://user-images.githubusercontent.com/58704132/146367594-05009466-1288-4d07-afcb-c26562e9c851.png">

This is my tsoa.json file:

```
{
    "routes": {
        "basePath": "/v2",
        "entryFile": "./src/Server.ts",
        "routesDir": "./src/Routes/v2",
        "authenticationModule": "./src/Middleware/Authentication/authentication.ts",
        "middleware": "express"
    },
    "spec": {
        "specVersion": 2,
        "outputDirectory": "./dist/Docs",
        "entryFile": "./src/Server.ts",
        "host": "localhost:8080",
        "basePath": "/v2",
        "spec": {
            "info": {
                ...
            },
            "securityDefinitions": {
                "jwt": {
                    "type": "apiKey",
                    "name": "token",
                    "in": "query"
                }
            },
            "servers": [
                {
                    "url": "http://localhost:8080",
                    "desription": "Local development server"
                },
                {
                    "url": "https://api-acceptance.io",
                    "desription": "Acceptance server"
                },
                {
                    "url": "https://api-prod.io",
                    "desription": "Production server"
                }
            ],
            "tags": [
                {
                    "name": "Dataset",
                    "description": "Create a dataset, list, remove, export etc."
                }
            ]
        }
    },
    "entryFile": "./src/Server.ts"
}
```

As you can see above, I'm using `"specVersion": 2,` When I upgrade it to 3 I can't read the generated JSON file

![Screenshot (72)](https://user-images.githubusercontent.com/58704132/146367637-4a1fffcd-2fdc-4772-a078-f2e44abf720c.png)

**Comment by WoH** [comment]
This is the most convenient way to serve the OpenAPI document: https://www.npmjs.com/package/swagger-ui-express

**Comment by Muratcol** [comment]
@WoH Perfect! Thanks, that works.

But now the controllers that I set Mongoose model as response type give errors as below. Do you know the reason for these?

f.e

```ts

    @Tags("Feed")
    @Post("{datasetId}/feed")
    @Security("jwt", ["feedManagement"])
    public async save(
        @Body() requestBody: DatasetFeedRequests.SaveRequest | DatasetFeedRequests.SaveRequest[],
        @Path() datasetId: string,
        @Request() req: any
    ): Promise<Datasets.DocumentDefinition> {   <========HERE=============

        const accountId = req.user.accountId;
        const userId = req.user.userId;

        this.setStatus(Response.Statuses.SAVE);
        const feed = await FeedServices.save(datasetId, requestBody, accountId, userId);

        await ActionLog.create({
            accountId: accountId,
            subjectId: datasetId,
            subjectType: "feed",
            action: `creation`,
            userId: userId
        });

        return feed;

    }
```

And errors are looks like this:

![Screenshot (74)](https://user-images.githubusercontent.com/58704132/146388120-fa6b760e-2391-4602-a228-35cae4c097e9.png)
