### ISSUE TITLE
Enhance @Example to support labels which will display when using OpenAPI 3.0

### ISSUE THREAD

**Issue by Albertowska** [lukeautry/tsoa#1157]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I would like to be able to set custom example labels when using `@Example` decorator

Sample generated YAML:

```yaml
...
paths:
  /token:
    post:
      operationId: GetOAuth2Token
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
              examples:
                Bearer Token:
                  value:
                    access_token: TOKEN
                    token_type: Bearer
                    expires_in: 60
                OTP Token:
                  value:
                    access_token: TOKEN2
                    token_type: Otp
                    expires_in: 60
...
```

Here is a suggested approach to implement it:
```ts
@Example<TokenResponse>(
	{
		access_token: "TOKEN",
		token_type: "Bearer",
		expires_in: 60
	},
	"Bearer Token"
)
```

## Current Behavior

Currently, there is no option to define labels for examples using `@Example` decorator. All examples when using OpenAPI 3.0 are named as "Example 1", "Example 2"...

Current generated YAML for same example:
```yaml
...
paths:
  /token:
    post:
      operationId: GetOAuth2Token
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
              examples:
                Example 1:
                  value:
                    access_token: TOKEN
                    token_type: Bearer
                    expires_in: 60
                Example 2:
                  value:
                    access_token: TOKEN2
                    token_type: Otp
                    expires_in: 60
...
```

## Possible Solution

A simple approach is to allow a 2nd optional parameter "label" on the `@Example` decorator, so when required, developers can input a label for the example

## Context (Environment)

Version of the library: 3.13.0
Version of NodeJS: v14.16.1

- Confirm you were using yarn not npm: [x]

## Detailed Description

The main goal is to be able to setup example labels when using the `@Example` decorator so they are later reflected on the Swagger document. This will only affect when generating OpenAPI 3.0 documents as they support multiple examples.

Labelled examples are a good way to provide extra information on an endpoint, specially when different data may be returned on the same endpoint on different scenarios.

Example labels functionality already exists when using JS Doc, however, is not ideal as it requires writing plain text JSON and using a `@Res()` parameter.

## Breaking change?

This change is backwards compatible will older versions as label must be kept as an optional attribute

**Comment by Albertowska** [comment]
If you agree with the suggested approach, I volunteer myself to implement the change

**Comment by WoH** [comment]
Extending `@Example()` in order to add labels makes sense, warning for OpenAPI 2 should be similar to #1000, which added  labels to parameters.
