### ISSUE TITLE
Version 3.x.x Yargs Dependency Vulnerability Needs Fixed

### ISSUE THREAD

**Issue by NSpencer4** [lukeautry/tsoa#1158]
As we await a stable latest version, my team has noticed on v3.14.1 there is a vulnerability within the tsao cli -> yargs dependency tree. Upon pulling the repo I noticed there were 40+ dependency vulnerabilities. I want to fix these issues in the meantime as we wait for v4.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
There should be no dependency vulnerabilities.

## Current Behavior
There are 40+ vulnerabilities in v3 and 1 of which is showing in audits to downstream applications.

## Possible Solution
PR to come

## Steps to Reproduce
Pull the repository, install dependencies and run an npm or yarn audit.

## Context (Environment)

Version of the library: 3.14.1
Version of NodeJS: any

- Confirm you were using yarn not npm: [ x ]

## Detailed Description
Bump versions of dependencies with vulnerabilities.

## Breaking change?
There shouldn't be any breaking changes here relating to yargs. But thorough testing through the suite will be necessary.

**Comment by WoH** [comment]
yargs dropped node 6 support. This is a (the main) breaking change.

3.x is not the branch where v3.14.0 was released from, so bumping deps there is not a good use of time I'm afraid.
