### ISSUE TITLE
regression: `keyof X` on `type X = { a: unknown; b: unknown }` produces `dataType: any`

### ISSUE THREAD

**Issue by devnev** [lukeautry/tsoa#1162]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
export interface File {
  type: Types;
}

export type Types = keyof Items;

export type Items = {
  type1: unknown;
  type2: unknown;
};

@Route("foo")
export class FooController {
  @Get("bar")
  public async bar(): Promise<{ file: File }> {
    return { file: { type: "type1" } };
  }
}
```

The resulting routes and spec should be something like:

```ts
const models: TsoaRoute.Models = {
    "Types": {
        "dataType": "refAlias",
        "type": {"dataType":"enum","enums":["type1","type2"],"validators":{}},
    },
    // WARNING: This file was auto-generated with tsoa. Please do not modify it. Re-run tsoa to re-generate this file: https://github.com/lukeautry/tsoa
    "File": {
        "dataType": "refObject",
        "properties": {
            "type": {"ref":"Types","required":true},
        },
        "additionalProperties": false,
    },
    // WARNING: This file was auto-generated with tsoa. Please do not modify it. Re-run tsoa to re-generate this file: https://github.com/lukeautry/tsoa
};
const validationService = new ValidationService(models);
```

## Current Behavior

It produces `{"dataType":"any"}` in the routes as follows, and has a similar result in the spec.

```ts
const models: TsoaRoute.Models = {
    "Types": {
        "dataType": "refAlias",
        "type": {"dataType":"any","validators":{}},
    },
    // WARNING: This file was auto-generated with tsoa. Please do not modify it. Re-run tsoa to re-generate this file: https://github.com/lukeautry/tsoa
    "File": {
        "dataType": "refObject",
        "properties": {
            "type": {"ref":"Types","required":true},
        },
        "additionalProperties": false,
    },
    // WARNING: This file was auto-generated with tsoa. Please do not modify it. Re-run tsoa to re-generate this file: https://github.com/lukeautry/tsoa
};
const validationService = new ValidationService(models);
```

## When keyof works

Note that removing one of the two fields `type1` or `type2` from the `Items` type results in the expected output being generated:

```ts
export interface File {
  type: Types;
}

export type Types = keyof Items;

export type Items = {
  type1: unknown;
};

@Route("foo")
export class FooController {
  @Get("bar")
  public async bar(): Promise<{ file: File }> {
    return { file: { type: "type1" } };
  }
}
```

produces

```ts
const models: TsoaRoute.Models = {
    "Types": {
        "dataType": "refAlias",
        "type": {"dataType":"enum","enums":["type1"],"validators":{}},
    },
    // WARNING: This file was auto-generated with tsoa. Please do not modify it. Re-run tsoa to re-generate this file: https://github.com/lukeautry/tsoa
    "File": {
        "dataType": "refObject",
        "properties": {
            "type": {"ref":"Types","required":true},
        },
        "additionalProperties": false,
    },
    // WARNING: This file was auto-generated with tsoa. Please do not modify it. Re-run tsoa to re-generate this file: https://github.com/lukeautry/tsoa
};
const validationService = new ValidationService(models);
```

## Relation to 4.x

Although not strictly a regression in 4.x - I could reproduce with both 3.14.1 and 4.0.0-alpha.1 - I only noticed this bug when checking for regressions with the upgrade, and found that a model that previously produced the proper enum list is now producing the `any` dataType as shown above. The model in question is a little more complex and I have not yet narrowed down the case where the regression occurs, and if its caused by the TSOA upgrade or the related Typescript upgrade. However the model in question does use a union of two `keyof` types, so the changes to union handling could have affected the likelihood of encountering this bug.

## Steps to Reproduce

1. Set up a standard tsoa project.
2. Copy in controller and model as in the `expected behaviour` section
3. Run `yarn run tsoa routes`
4. Check generated routes file. 

## Context (Environment)

Version of the library: 3.14.1 and 4.0.0-alpha.1
Version of NodeJS: v14.18.2

- Confirm you were using yarn not npm: [✓]

**Comment by WoH** [comment]
This may well be related to a TS Compiler API bump, but it would be helpful to not only bisect i.o.t. confirm but take a look at how we can fix the regression and maybe backport the fix?

**Comment by devnev** [comment]
@WoH I've now also encountered this regression while doing upgrades of dependencies, including typescript, without upgrading TSOA to 4.0. So I think you're right that this is due to the typescript upgrade and affects 3.x releases too. I guess wether it warrants a backport depends on your support strategy.

**Comment by WoH** [comment]
V4.0 should fix that, can you confirm? See https://github.com/lukeautry/tsoa/pull/1163
