### ISSUE TITLE
Generating OperationId from method name

### ISSUE THREAD

**Issue by bhugoVilela** [lukeautry/tsoa#1164]
## Sorting

- **I'm submitting a Feature Request**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

OperationId gets automatically generated from Method name if an `@OperationId` tag is not provided

## Current Behavior

I find myself adding `@OperationId` tags with the same name of the method in almost all methods.

## Possible Solution

add a config option to tsoa.json and/or a Cli param that allows this behaviour to activate. 
eg: `--extractOperationIdFromMethodName`

I took a quick glance at the code and it appears to me that this is easily done by altering the behaviour of `@tsoa/cli/src/metadataGeneration/methodGenerator.ts` on `MethodGenerator.getOperationId` or `MethodGenerator.Generate()`
but as I said, I only took a quick glance, I'm sure there's other things you have to account for

- [ ] Confirm you were using yarn not npm

I am using npm but I don't think this is of concern.

## Breaking change?

Not if the behaviour has to be activated with a flag

**Comment by WoH** [comment]
I'm not sure what I'm missing, but by default, the method name is the `operationId` we set, unless you override it with `@OperationId()`.

**Comment by bhugoVilela** [comment]
Oh my apologies for wasting your time, I was seeing the swagger spec through SwaggerUI where it doesn't show the operationId, but it's in the spec alright. All good.

Thank you.
