### ISSUE TITLE
Fix for IoC with Controller base class

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#117]
Hey!

In order to make inversify work with the Controller base class, please add this to the example.

./inversify/ioc.ts:

import { decorate, injectable } from "inversify";
import {  Controller } from 'tsoa';
decorate(injectable(), Controller )

Comment: we have to decorate this a posteriori because not everybody uses inversify.

Cheers.

**Comment by AndyGura** [comment]
Thank you, egandro, it helped. Will be nice to have this merged

**Comment by egandro** [comment]
I just asked Luke for GIT access ;) 

I hope I can do that by myself soon :)
