### ISSUE TITLE
Tsoa string validation doesn't work for "string | null" properties

### ISSUE THREAD

**Issue by oblomingo** [lukeautry/tsoa#1170]
I'm submitting a bug report
I confirm that I used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Validation should work for dto objects with annotated properties even if it can be a null:
 ```ts
export type User  = {
    id: number;
    /**
     * user email
     * @type {string}
     * @minLength 1
     * @maxLength 10
     */
    email: string | null;
    name: string;
    status?: "Happy" | "Sad";
    phoneNumbers: string[];
  }
```
Dto value:
```json
{
  "email": "emailNameL0ngerThan10Symbols@mail.com",
  "name": "name",
  "phoneNumbers": [
    "119"
  ]
}
```
Endpoint response with Bad request status code and error description (email length incorrect).
## Current Behavior
Endpoint validation passes incorrect dto object.

## Context (Environment)
"tsoa": "^3.14.1"
"express": "^4.16.4",

**Comment by WoH** [comment]
You might want to check out #997 and the referenced issue for context.

This should be fixed but can reasonably considered a breaking change, please upgrade to the v4 alpha. It should work there. If not, I'll reopen this discussion.

**Comment by oblomingo** [comment]
Unit type validation works with 4.0.0-alpha.2 version, but validation error has a lots of unnecessary technical details and it is hard to understand the meaning of the error message, for example I have a property:
```ts
   /**
    * user email
    * @maxLength 10
    */
   email: string | null;
```
I'm getting an error:
```json
{
    "message": "Validation Failed",
    "details": {
        "requestBody.$0.email": {
            "message": "Could not match the union against any of the items. Issues: [{\"requestBody.$0.email\":{\"message\":\"maxLength 10\",\"value\":\"PCPNPsdfsdfsdfsdfsfgsdgf\"}},{\"requestBody.$0.email\":{\"message\":\"should be one of the following; [null]\",\"value\":\"PCPNPsdfsdfsdfsdfsfgsdgf\"}}]",
            "value": "PCPNPsdfsdfsdfsdfsfgsdgf"
        }
    }
}
```
As you can see "maxLength 10" text mixed with other technical details and it could be unclear for API user.
