### ISSUE TITLE
Tsoa validation doesn't work with long pattern values and validation messages

### ISSUE THREAD

**Issue by oblomingo** [lukeautry/tsoa#1172]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Export type with long pattern added. Since the pattern string has a length bigger than 100 symbols (eslint max 100), pattern part moved to next line. Reject message moved to next line and starts from whitespace.

- Validation mechanism should use pattern from different rows and search for the regexp match.
- email@company.com value should pass validation
- incorrectemail value should be rejected with message: **Invalid email. Value is expected to match the pattern [a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)***

```ts
/**
 * Stringified email.
 * See [RFC 1123](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address).
 *
 * @pattern [a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?
 * (?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*
 *  Invalid email. Value is expected to match the pattern 
 * [a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9]
 * (?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9]
 * (?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*
 * 
 * @format email
 */
export type Email = string;
```
## Current Behavior

-  email@company.com can't pass validation, probably, because validation mechanism includes newline symbol into regexp expression.
- An error message omits first message word: **email. Value is expected to match the pattern \n[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9]\n(?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9]\n(?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)***
- Multiline reject messages renders  new line **\n** symbols.
## Steps to Reproduce
Use provided type 

## Context (Environment)

Version of the library: ^4.0.0-alpha.2
Version of NodeJS: 

- Confirm you were using yarn not npm: [x ]

**Comment by igarioshka** [comment]
In current behavior, the generator splits the pattern and error message by first space -so 
```
/**
 * @pattern [p]
 * this is a message
 */
```
would resolve in:
```
{
  "pattern": {
    "errorMsg": "is a message",
    "value": "[p]\nthis"
  }
}
```
There is a possibility to use multiple lines in error message, as long as the error message is split with the pattern by a space, this would somewhat mitigate the issue, as the error message. As current IDEs like to trim end line spaces, one solution would be to use the tag as:
```
/**
 * @pattern [p] this
 * is a message
 */
```
unfortunately, new lines in this context get escaped, resulting in the following error message:
```
{
  "pattern": {
    "errorMsg": "this\nis a message",
    "value": "[p]"
  }
}
```

**Comment by ggbruno** [comment]
The problem is with multiple lines in regex. Value can't evaluate the regex with \n.
This can be archived by removing \n from pattern value in validatorUtils.js, just like is done with quotes.
So, a pattern like this:
```
 * @pattern [longlinep]
 * [morep]
```
will evaluate to
```
{
  "pattern": {
    "value": "[longlinep][morep]"
  }
}
```

The problem with error in a new line, maybe can be solved with two new lines?
```
 * @pattern [longlinep]
 * [morep]
 *
 * ERROR LINE
```
will evaluate to
```
{
  "pattern": {
    "value": "[longlinep][morep]"
    "errorMsg": "ERROR LINE",
  }
}
```
Of course, two newlines will give the same problem @igarioshka have reported (the value will be "...p]\n\nERROR") but this can be easily parsed to correct the errorMsg for pattern. So, the ideia is:
In value: One newline: remove; two newlines: Add data to errorMsg.

**Comment by igarioshka** [comment]
That's a great idea! We can postprocess the error message in the function that handles validation errors, removing all unnecessary newlines.
Now, only the pattern length would be difficult, as there would need to be a change in validatorUtils.

**Comment by ggbruno** [comment]
I made an implementation of the idea. It removes the newlines and allow the error message with double newlines.

https://github.com/ggbruno/tsoa/commit/2907652adf790c76ef9e365538c2ebb3a1a606d8
