### ISSUE TITLE
TypeScript compile error: 'HttpStatusCodeLiteral' only refers to a type, but is being used as a value here

### ISSUE THREAD

**Issue by oblomingo** [lukeautry/tsoa#1174]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
There is no console errors
## Current Behavior
There are two console error on typescript compilation:

- project/node_modules/@tsoa/runtime/dist/interfaces/response.d.ts(3,51): error TS1110: Type expected.
- project/node_modules/@tsoa/runtime/dist/interfaces/response.d.ts(3,54): error TS2693: 'HttpStatusCodeLiteral' only refers to a type, but is being used as a value here.
tsoa.json
```ts
{
  "entryFile": "src/index.ts",
  "noImplicitAdditionalProperties": "throw-on-extras",
  "controllerPathGlobs": [
    "src/**/*Controller.ts"
  ],
  "spec": {
    "yaml": true,
    "outputDirectory": "src",
    "specVersion": 3,
    "specFileBaseName": "swagger-auto-generated"
  },
  "routes": {
    "routesDir": "src",
    "routesFileName": "routes-auto-generated.ts"
  }
}
```
## Steps to Reproduce
Use 4.0.0-alpha.2 version, 3.14.1 version has no errors
## Context (Environment)

Version of the library: 4.0.0-alpha.2
Version of NodeJS: v14.18.1

- Confirm you were using yarn not npm: [x]

**Comment by oblomingo** [comment]
I've found that build fails for typescript version < 4.1. After typescript upgrade the error disappeared.

**Comment by WoH** [comment]
Given that [this breaking change is documented](https://github.com/lukeautry/tsoa/releases/tag/v4.0.0-alpha.0) and the feedback on requiring TS4.1 (https://github.com/lukeautry/tsoa/issues/1135) was pretty clear, I don't think there's anything else we should do here.

**Comment by oblomingo** [comment]
Agree, thank you.
