### ISSUE TITLE
Functions Yielding a String Array not Working when Applying Multiple Security Methods

### ISSUE THREAD

**Issue by valerie-thomas** [lukeautry/tsoa#1178]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submitted

## Expected Behavior
It should be possible to call a function that returns an array of strings when providing an object to Security to apply multiple security methods. Calling a function that returns a string array seems to work when using the Security decorator with a single input, but when providing multiple inputs it doesn't (code snippet from the related controller route):
`  @Security({
    FirstAuth: testStrArr(),
    OtherAuth: []
  })`

And the test function returning a string array:
`export function testStrArr() {
  return ['test'];
}`

## Current Behavior

Instead of calling the function and using the returned array, the tsoa compiler seems to ignore the first auth entirely, passing only the second auth method (OtherAuth) into the final routes file. If the function call is replaced with an array of string literals, it works as expected.

## Possible Solution

In both cases that I've tested, the function that was being called was defined in a separate file from where I was supplying it to the Security decorator. I suppose it's possible that the instructions for imports for Security differ based on whether it's called with a single method specified vs. multiple, and that the issue is with finding the specified function itself (although I would expect tsoa to throw an error if that was the case).

## Steps to Reproduce

1. Take the GetWithAndSecurity test from the [SecurityTestController](https://github.com/lukeautry/tsoa/blob/master/tests/fixtures/controllers/securityController.ts) 
`  @Response<ErrorResponseModel>('404', 'Not Found')
  @Security({
    api_key: [],
    tsoa_auth: ['write:pets', 'read:pets'],
  })
  @Get('OauthAndApiKey')
  public async GetWithAndSecurity(@Request() request: RequestWithUser): Promise<UserResponseModel> {
    return Promise.resolve(request.user);
  }`

2. In the repo, add a function that returns an array of strings
3. Set api_key to the output of this function
4. Build the solution and check routes.ts to verify that api_key was not added to the array for authenticateMiddleware

## Context (Environment)

Version of the library: 3.7.0
Version of NodeJS: 12.22.8

- Confirm you were using yarn not npm: [x]

## Breaking change?

This shouldn't be a breaking change since the functionality already seems to not be working as expected.

**Comment by keslerm** [comment]
Okay so I just lost a bunch of time on this because it's an extremely subtle thing that's very easy to miss.

There are two ways to generate the security tags, like the way you are doing it and adding multiple `@Security` tags

What's very easy to miss in the docs is each of these behaves differently

https://tsoa-community.github.io/docs/decorators.html#security

The gist is doing it like this:

```js
@Security({"method1": {}, "method2": {})
```
Validates as an AND so every method must pass.

In contrast doing it like this:

```js
@Security("method1")
@Security("method2")
```

This operates as an OR and just one of them has to pass.

I think at least the documentation that I linked could be updated to emphasis this point more as well as including the same point on the other spot that discusses authentication here: https://tsoa-community.github.io/docs/authentication.html

**Comment by WoH** [comment]
This is a bit of a caveat, I agree that we should add this to the docs.
The reason this doesn't work is that we don't run functions (which could have arbitrary side effects) at compile time to evaluate them.

**Comment by valerie-thomas** [comment]
Ah, got you. I'll mark this as closed since it sounds like it's a design choice instead of a bug. Thanks for clarifying!
