### ISSUE TITLE
securityDefintitions is missing bearer scheme in spec version 3

### ISSUE THREAD

**Issue by Inoir** [lukeautry/tsoa#1183]
securityDefinitions types is missing 'type: http' + 'scheme: bearer'. Only type provided currently is 'type: http' + 'scheme: basic'

## Sorting

- **I'm submitting a bug**

  - [ x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [ x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Since bearer scheme is possible with spec v3 it should be also definable without any errors

```ts
securityDefinitions: {
      'jwt': {
        type: 'http',
        scheme: 'bearer',
        description: 'Enter JWT',
        bearerFormat: 'JWT',
      },
    }
```

## Current Behavior

TS throws an error, since type is unknown
![Screenshot 2022-02-02 at 01 01 30](https://user-images.githubusercontent.com/5294072/152071670-4e1954d9-06cb-439b-b8af-b151471ccfa3.png)

## Possible Solution

Add the correct type

```ts 
export interface BearerSecurity3 extends BaseSecurity {
    type: 'http';
    scheme: 'bearer';
    bearerFormat: 'JWT'
  }
```

## Steps to Reproduce

1. Create a ts file with object type "ExtendedSpecConfig"
2. define securityDefinitions like written above
3. see error

## Context (Environment)

Version of the library: 3.14.1

- Confirm you were using yarn not npm: [ x]

**Comment by alejamp** [comment]
Any workaround for this issue?

**Comment by Nautigsam** [comment]
I am interested in working on this. I will let you know if I have any question.

**Comment by Nautigsam** [comment]
At least it works in version X, I could add the following to the `spec` section in `tsoa.json`:
```json
"securityDefinitions": {
  "BearerAuth": {
    "type": "http",
    "scheme": "bearer"
  }
}
```
Spec generation works as intended and I can set my token in SwaggerUI.

I will still add a proper support for typing though. I will also add a check in v2 generation because `http` scheme is not supported for this version of the specification.
