### ISSUE TITLE
open api spec overrides

### ISSUE THREAD

**Issue by BottlecapDave** [lukeautry/tsoa#1184]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior

I'm working on a project which is using an opaque type to guard code from using the wrong identifiers for the wrong types. Below is an example of how this is done via an `OpaqueString`. 

```ts
export type OpaqueString<Key extends string> = string & { __opaque: Key };
export type UserId =  OpaqueString<'UserId'>

export interface IUser {
  id: UserId;
}

@Route('/users')
export class UserController extends Controller {
  @Post('{id}')
  public getUserById(
    @Path() id: UserId
  ): IUser {
    return {
       id: 'test-id'
    };
  }
}
```

However, the generated route and open api spec doesn't like this and produces something like the following:

```json
{
  "components": {
    "examples": {},
    "headers": {},
    "parameters": {},
    "requestBodies": {},
    "responses": {},
    "schemas": {
      "OpaqueString_UserId_": {
        "allOf": [
          {
            "type": "string"
          },
          {
            "properties": {
              "__opaque": {
                "type": "string",
                "enum": [
                  "UserId"
                ],
                "nullable": false
              }
            },
            "required": [
              "__opaque"
            ],
            "type": "object"
          }
        ],
        "description": "A string with some type safety so the value can only be used in the right context"
      },
      "UserId": {
        "$ref": "#/components/schemas/OpaqueString_UserId_"
      },
  }
  ...
}
```

I couldn't find a way of making this be treated as a string.

## Possible Solution

Ideally these opaque strings would just be interpreted as strings, but understand this is a bit of a niche situation. Therefore it might be nice to be able to override types with their open api definitions.

```tsoa.json
{
  "spec": {
    "overrides": [
      {
        "target": "OpaqueString_UserId_",
        "definition": {
          "type": "string"
        }
      }
    ]
  }
}
```

Or to provide even more flexability would be a typescript function which is provided a type that could then return the spec.

## Context (Environment)

Version of the library: 3.14.1
Version of NodeJS: 14.17.4

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
Recommended way is to separate the type system abuse from your models at the edge of the Program.

I.e. have an interface which is the correct representation (in this case `id: string`)and use that in the controller's return type.
