### ISSUE TITLE
Config basePath option should be put in methods url instead of server section in spec generation

### ISSUE THREAD

**Issue by stefanoimperiale** [lukeautry/tsoa#1198]
## Sorting

- **I'm submitting a ...**

  - [X ] bug report
  
- I confirm that I
  - [ x ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

The basePath option should be used to create the methods url instead of the server url. That's because if you are going to use an openapi tool for code generation (i.e. https://openapi-generator.tech/) the methods generated will point to wrong urls (you will miss the basePath prefix). 

## Expected Behavior

```json
{
  "spec": {
    "basePath": "api",
    "outputDirectory": "../build",
    "specVersion": 3
  },
}

```

Generated spec:
![image](https://user-images.githubusercontent.com/30474939/155201907-c681cf27-a4bc-4394-bcf5-87c636178e56.png)

Code generated with `openapi-generator`
``` ts
async createUserRaw(requestParameters: UserApiCreateUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'undefined';

        const response = await this.request({
            path: `/api/users`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }
```

```ts

```

## Current Behavior

![image](https://user-images.githubusercontent.com/30474939/155202661-0220f1a0-c880-4850-9fcd-4308c654d6f4.png)

Code generated with `openapi-generator`
```ts
async createUserRaw(requestParameters: UserApiCreateUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'undefined';

        const response = await this.request({
            path: `/users`,  //here the error
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

```

## Possible Solution
I created a PR

## Context (Environment)

Version of the library: 3.14.1
Version of NodeJS: v16.13.1

- Confirm you were using yarn not npm: [ x]

## Breaking change?

This fix could change the spec generation if you use the v2 because the basePath option is used to map the baseUrl property. I added an another option that will be used only for the v2
```ts
  /**
   * Base API path; e.g. the 'v1' in https://myapi.com/v1
   */
  basePath?: string;

  /**
   *  Base URL path (used only in specVersion 2)
   */
  baseUrl?: string;
```

**Comment by WoH** [comment]
While this does not look ideal, I am not really looking to add another config which is specific to one OpenAPI version only.
As you can see in the screenshot, the `/api` is still there but moved to the Servers dropdown
