### ISSUE TITLE
Please fix line endings to LF

### ISSUE THREAD

**Issue by dguard** [lukeautry/tsoa#12]
To reproduce problem:
git clone https://github.com/lukeautry/tsoa-example
cd tsoa-example
npm i
npm start

Got error:
> tsoa swagger --swaggerDir=./dist --entryFile=./src/server.ts --host=localhost:3000 --basePath=/v1

/usr/bin/env: «node\r»: No such file or directory
(like there: https://github.com/nwjs/nw-builder/issues/75)

To fix that issue on Ubuntu 16.04 (and I suppose on other linux and MacOS as well) I replaced line endings for the file node_modules/tsoa/dist/cli.js from CRLF to LF (using WebStorm, I suppose that other editors support that feature as well and probably there is exist some command line tool to do it)

Thanks you guys, I really like tsoa - wish you success!

**Comment by lukeautry** [comment]
Nice find @dguard . I've pushed an update that runs dos2unix on distributed scripts after build; that will prevent this issue when the package is published from a Windows machine.

Also updated tsoa-example project to use the latest version, so you should just be able to npm install + npm start.

Thanks again, and let me know if you're still having trouble!

**Comment by dguard** [comment]
Yes, it works like a charm, thanks!

**Comment by lukeautry** [comment]
@dguard I changed the library used for this and actually published from a windows machine. When you got an opportunity, please upgrade to 0.0.58 and confirm that the issue is still resolved.

Thanks!
