### ISSUE TITLE
Question on Maps

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#120]
Hello again,

i am currently working on a code generator to create a client from the swagger files.

Based on this Typescript Definition

```
export interface TestSubModelContainer {
  [key: string]: TestSubModel2;
}
```

... this route code is created...

```
"TestSubModelContainer": {
    properties: {
    },
    additionalProperties: { "typeName": "TestSubModel2" },
},
```

... and this swagger.json entry is made.

```
"TestSubModelContainer": {
    "description": "",
    "properties": {},
    "type": "object",
    "additionalProperties": {
        "$ref": "#/definitions/TestSubModel2"
    }
},
```
Question: Can I make the educated guess that empty properies and a single additionalProperties is a dictionary (at last for tsoa)?

Example: 

```
{
   "foo": instanceOf$ref,
   "bar": instanceOf$ref,
}
```

**Comment by dgreene1** [comment]
> “Can I make the educated guess that empty properies and a single additionalProperties is a dictionary (at last for tsoa)?”

Yes. And more importantly, that’s how Swagger / OpenAPI Spec describes a dictionary. Read more here: https://swagger.io/docs/specification/data-models/dictionaries/
