### ISSUE TITLE
Record<string, unknown> does not allow additional properties

### ISSUE THREAD

**Issue by yannbriancon** [lukeautry/tsoa#1204]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

A body with a field `attributes: Record<string, unknown>` and should allow additional properties even with `"noImplicitAdditionalProperties": "throw-on-extras",` in tsoa.json.

## Current Behavior

A body with a field `attributes: Record<string, unknown>`  with `"noImplicitAdditionalProperties": "throw-on-extras",` in tsoa.json triggers a validation error:

```
{"requestBody.attributes":{"message":"\"test\" is an excess property and therefore is not allowed","value":{"test":"test"}}}
```

## Steps to Reproduce

1. Add an interface `interface GeometryPostBody { attributes?: Record<string | number, unknown> }`
2. Set the interface as the expected body of a POST request
3. Try to POST with the body `{"attributes": {"test": "test"}}`
4. Receive a validation error `{"requestBody.attributes":{"message":"\"test\" is an excess property and therefore is not allowed","value":{"test":"test"}}}`

## Context (Environment)

Version of the library: 3.14.1
Version of NodeJS: v16.13.1

- Confirm you were using yarn not npm: [ ]

**Comment by yannbriancon** [comment]
Hello all!

If it can help, I found a workaround by replacing `Record<string, unknown>` by `{ [key: string]: unknown }`.

It would still be great to find how to fix the real issue with Record 😉

**Comment by SebastienGllmt** [comment]
I also ran into this issue. I was hoping to do something like
```typescript
type Foo = string;
Record<Foo, number>
```
But not only does this not work, `{ [key: Foo]: number}` doesn't work either and instead fails with `Error: Only string indexers are supported`. This is unfortunate since I was hoping to split Foo as a separate type so that I can proper give it decorators.

**Comment by m1cm1c** [comment]
@SebastienGllmt I've had the same problem as you. I want to accept a body of type `Record<UUID, {data: string, signature: string}>` where `type UUID = string`.

@yannbriancon's `{ [key: string]: unknown }` trick works for this and I think it will work for you too. I can choose the type to be `{[key: string]: {data: string, signature: string}}` for TSOA. This type even is compatible with `Record<UUID, {data: string, signature: string}>` that I then can use in the rest of my application without casting.

**Comment by stevenwchien** [comment]
I have a related question based on the above. According the Swagger definition for "Free-form object": https://swagger.io/docs/specification/data-models/data-types/#object, the following specifications are equivalent representations:

```yaml
type: object
```

```yaml
type: object
additionalProperties: true
```

```yaml
type: object
additionalProperties: {}
```

However, using the type `{ [key: string]: unknown }` becomes:

```yaml
type: object
properties: {}
additionalProperties: {}
```

The additional `properties` field is messing with an auto-generated API documentation tool that I'm using. Does anyone know how to remove this `properties` field using `tsoa`? I can always do it manually, but was hoping to be able to generate the Swagger and feed it into the documentation tool automatically. Thanks!
