### ISSUE TITLE
Incorrect ESM code generated

### ISSUE THREAD

**Issue by BenjaminAfrolabs** [lukeautry/tsoa#1205]
The ESM code generation imports promise.any incorrectly

## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behaviour

Correct import to be used for `promise.any` in ESM mode in the generated code

```ts
import promiseAny from 'promise.any'
```

## Current Behaviour

```ts
import * as promiseAny from 'promise.any'
```

## Possible Solution

In the import, remove the `* as `

## Steps to Reproduce

Set routes to ESM and install the latest promise.any

## Context (Environment)

Version of the library: 4.0.0-rc.0
Version of NodeJS: ts-node (typescript 4.5.5, node v17.4.0)

- Confirm you were using yarn not npm: [ ]

## Detailed Description

A small fix for the ESM code generation that imports promise.any incorrectly

**Comment by WoH** [comment]
Fyi, you should be able to set `esModuleInterop` to `true` for now, and it should be fine.
