### ISSUE TITLE
When trying to use variables inside the @Extension decorator they don't appear in the resulting swagger

### ISSUE THREAD

**Issue by Dizzzmas** [lukeautry/tsoa#1213]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

When using the `@Extension` decorator
```ts
  @Extension('x-google-backend', {
    address: `https://${GOOGLE_PROJECT_REGION}-${GOOGLE_PROJECT_ID}.cloudfunctions.net/`,
  })
```
( use case: Google Cloud API Gateway requires the configuration to be specified this way in the extensions )

I expect it to translate to

```json
"x-google-backend": {
"address": "https://myregion-myproject.cloudfunctions.net/"
}
```

## Current Behavior

However, I'm getting an empty object instead
```json
"x-google-backend": {
"address": {}
}
```

After experimenting I've found out that it's because of me trying to put the variables into the string. Without the `${GOOGLE_PROJECT_REGION}-${GOOGLE_PROJECT_ID}` part everything works fine.

## Steps to Reproduce

Try to put a variable in the `@Extensions` decorator and see what's in the generated swagger.

## Context (Environment)

Version of the library: 3.14.1
Version of NodeJS: 16.3.1

- Confirm you were using yarn not npm: I used NPM

**Comment by WoH** [comment]
Caveat here is: We don't know what that env var is. We don't evaluate/run the JS, we try to statically look at the code and find out what the OpenAPI spec should be.
