### ISSUE TITLE
Autogenerate path names from controller methods

### ISSUE THREAD

**Issue by calvinwyoung** [lukeautry/tsoa#1214]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Detailed Description

I'm interested in using tsoa to generate an RPC-style backend, and would like to autogenerate URL paths from the names of the controller methods. The current tsoa API request me to define both a controller method as well as a path:

```ts
@Put('/create-foo')
async createFoo(@Body() params: CreateFooRequest): Promise<void> {
 ...
}
```

I'd love to be able to auto-generate the path name from the controller method so all I'd need to do is:

```ts
@Put()
async createFoo(@Body() params: CreateFooRequest): Promise<void> {
  ...
}
```

Does tsoa support this use case? Is there a simple workaround for enabling this behavior?

**Comment by aargondizza** [comment]
Wow I'd really love this too!
