### ISSUE TITLE
Incorrect ESM code generated (relative import statements)

### ISSUE THREAD

**Issue by RaafatTurki** [lukeautry/tsoa#1224]
I've converted my typescript project to emit ESM code (according to [this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm) guide) and now my tsoa generated routes throw an error.

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path/to/project/build/routes/user/controller' imported from /path/to/project/build/gen/routes.js
```
it's because the generated `routes.ts` import my controller as `/path/to/project/build/routes/user/controller` without a `.js` at the end (a really important thing when it comes to ESM)

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
this should be how `routes.ts` imports controllers in ESM
```ts
// what ESM requires
import { UsersController } from './../routes/user/controller.js';
```

## Current Behavior
```ts
// generated routes.ts
import { UsersController } from './../routes/user/controller';
```

## Possible Solution

this can be easily fixed by appending a `.js` [here](https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/routeGeneration/templates/koa.hbs#L11) however I believe that will make the koa tempalte ESM only.

a smarter solution can be done [here](https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/routeGeneration/routeGenerator.ts#L103) which basically appends the `.js` conditionally depending on if `package.json` has `"type": "module"` or not.

## Steps to Reproduce

1. setup an ESM typescript project following [this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm) guide
2. setup a koa project (based on the koa test project within this repo)
3. `tsoa routes`
4. `tsc`
5. `node ./build/index.js`

## Context (Environment)
`esModuleInterop` option within `tsconfig.json` makes no difference

Version of the library: 3.14.1
Version of NodeJS: v17.8.0

- Confirm you were using yarn not npm: [ ] (I was using pnpm)

## Breaking change?
It won't be if implemented correctly (the 2nd method in **Possible Solution**)

**Comment by WoH** [comment]
Please use the v4 RC and set esm: true.

**Comment by insanity54** [comment]
For future searchers, `esm: true` goes inside `tsoa.json`, nested within routes.

tsoa.json
```json
{
  "routes": {
    "esm": true
  }
}
```

See https://github.com/lukeautry/tsoa/issues/1272#issuecomment-1169734557
