### ISSUE TITLE
Version 4 Timeline

### ISSUE THREAD

**Issue by sdoward** [lukeautry/tsoa#1225]
Congratulations on a great library!

We have decided to adopt Tsoa  at my work place. But we are considering waiting for 4.0.0 before we roll it out to our full code base. We want to avoid migration work if possible. So in oder to plan I thought I would ask if you have an idea on the date of the next major release?

Thanks

**Comment by WoH** [comment]
I don't make any specific commitments for Open Source, but you can use the 4.0 release candidate (`yarn add tsoa@next`), I do not expect any major changes until 4.0.0.
It is ready to release unless significant bugs emerge, currently I am not aware of any such bug.

**Comment by sdoward** [comment]
@WoH thanks for the quick response. I completely understand.

With regards to making that release, is there something you are waiting for? Or is there something I can help with?

**Comment by WoH** [comment]
I am waiting for spare time to allocate towards free work to review outstanding PRs and cut a release.
