### ISSUE TITLE
error: uncaughtException: Class extends value undefined is not a constructor or null TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by TarekHelwani** [lukeautry/tsoa#1226]
I am trying to use tsoa and swagger-ui-express in my new project (typescipt + express) for api documentation

i followed the docs for tsoa and have something like this in my code

export class VendorController extends Controller {

}

when i ever u run the server i get this error

error: uncaughtException: Class extends value undefined is not a constructor or null TypeError: Class extends value undefined is not a constructor or null

when i remove the extend it works! , anyone has idea what is happening ?

**Comment by euaaron** [comment]
Same thing also happens when using swagger-ui with Next.js... this is probably a swagger-ui problem, not tsoa's.

**Comment by douglasg14b** [comment]
This appears to be happening in a brand new project, no swagger-ui involved at all :/
