### ISSUE TITLE
Bug: swagger files gets an schema validation error if no title and no version is provided

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#123]
Hello again,

swagger.json files gets a validation error, if there is no default title and version in the info field.

This happenes, wenn calling "tsoa swagger" from a directory without a package.json.

Please put some default values.

**Comment by egandro** [comment]
Fixed this?

**Comment by isman-usoh** [comment]
Sorry, I forgot to push the remote repo

**Comment by isman-usoh** [comment]
Fix f034256
