### ISSUE TITLE
Multer is missing for config.d.ts

### ISSUE THREAD

**Issue by stephannielsen** [lukeautry/tsoa#1230]
`config.d.ts` references `multer` but it's not included/referenced in tsoa runtime, causing an error message.

```
p_1      | $ rm -rf /build && tsoa spec-and-routes && tsc
p_1      | node_modules/@tsoa/runtime/dist/config.d.ts(2,39): error TS2307: Cannot find module 'multer' or its corresponding type declarations.
```

Nevertheless, I can still access my OpenAPI spec and SwaggerUI. I am not using any form/multi endpoints from the spec, that might be why it still works. Also I cannot say how a real API would be affected, currently this is just a few mock controllers to produce a spec.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

No error when running tsoa in docker container / building docker image. Peer dependency is shipped / declared correctly (?)

## Current Behavior

When running `tsoa spec-and-routes` I see this message:

```
p_1      | $ rm -rf /build && tsoa spec-and-routes && tsc
p_1      | node_modules/@tsoa/runtime/dist/config.d.ts(2,39): error TS2307: Cannot find module 'multer' or its corresponding type declarations.
```

Nevertheless, I can still access my OpenAPI spec and SwaggerUI. I am not using any form/multi endpoints from the spec, that might be why it still works. Also I cannot say how a real API would be affected, currently this is just a few mock controllers to produce a spec.

Note: I only see the message when calling tsoa during a Docker image build, but when going into `node_modules/@tsoa/.../config.d.ts` VS code is also claiming that `multer` is missing.

Adding `multer` as dev dependency gets rid of the warning in the logs and in VS code, but it feels strange that I have to add the dependency explicitly to my project.

## Steps to Reproduce

If needed, I can provide more details and a small repro later on.

## Context (Environment)

Version of the library: 3.14.1 and 4.0.0-rc1
Version of NodeJS: 16 (LTS, Alpine Image as base for Docker image)

- Confirm you were using yarn not npm: [x]

**Comment by frederikhm** [comment]
I also encountered this bug with tsoa 4.1.0. 
I was **not** using docker, but still unable to tun `yarn run tsc --outDir build --experimentalDecorators` due to the error. manually installing multer and  @types/multer as dev dependencies fixed the problem.

**Comment by dertrockx** [comment]
> I also encountered this bug with tsoa 4.1.0. I was **not** using docker, but still unable to tun `yarn run tsc --outDir build --experimentalDecorators` due to the error. manually installing multer and @types/multer as dev dependencies fixed the problem.

This also worked for me (I manually installed multer and @types/multer too).

**Comment by mbledkowski** [comment]
I have the same problem

**Comment by jackvhall** [comment]
A fresh install of `tsoa@latest` leaves me with this problem still.

**Comment by WoH** [comment]
[4.1.3](https://www.npmjs.com/package/tsoa/v/4.1.3) is latest
[5.0.0-alpha.2](https://www.npmjs.com/package/tsoa/v/5.0.0-alpha.2) is next

**Comment by grug** [comment]
I'm still finding this with version 4.1.3

**Comment by DeveloperMartin** [comment]
still in version 4.1.3
