### ISSUE TITLE
Any way to prevent tsoa from resolving types from other packages?

### ISSUE THREAD

**Issue by bhavitsharma** [lukeautry/tsoa#1237]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Problem

Is there a way in the CLI/flag to prevent open-api from creating types which are imported from other packages? Example, we have a controllers file in package let's "A". Now in the controller's file, people are importing package "B" which is being exposed as the return type of some controller's get/set endpoint. Ideally we'd like to restrict it so that people create their own models in the same package "A".

## Expected Behavior

tsoa CLI throws an error if it's creating a type which it needs to resolve from external dependency. 

## Current Behavior

It doesn't throw an error.

**Comment by WoH** [comment]
1) we only produce definitions for types that are "needed" (meaning (in-)directly referenced by endpoints)
2) You can control which files are included (i.e. available to the declaration scan) in your program using the tsconfig.

tsc --listFilesOnly may be helpful
