### ISSUE TITLE
Feature Request: Enhance the swagger.json file with meta comments

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#124]
Hello everybody,

as in my previous posts, i am currently developing a code generator for the swagger files.

I'd like to discuss an optional feature that would be of great use for my needs.

We currently flatten every symbol the TS parser detects.

E.g.

```
export namespace TestSubModelNamespace {
  export interface TestSubModelNS extends TestSubModel {
    testSubModelNS: boolean;
  }
}
```

creates this

```
		"TestSubModelNamespace.TestSubModelNS": {
			"description": "",
			"properties": {
// ton's of properties of TestSubModelNS and TestSubModel 
			},
...
		},
```

But we know that we have a Namespace, a parent class and a parent interface.

I suggest adding optional meta comments to the description (as JSDoc does the trick for the parser)

Example:

```
		"TestSubModelNamespace.TestSubModelNS": {
			"description": "@Namespace: TestSubModelNamespace\n@IsClass\@BaseClass: TestSubModel",
...
		},
```

What do you think about this?

**Comment by egandro** [comment]
This would be of very great help to me.

```
My description of the method.

$Namespace$: The namespace
$Controller$: The controller
$Method$: The Method
```

Also for the Complex Types it would be great to have

```
My Description of the Interface or Class

$Namespace$: The namespace
$Name$: The Name
$Type$: Class / Interface
```

**Comment by dgreene1** [comment]
We’d be open to a PR for this. However, I do wonder if a custom attribute (like `x-namespace-meta`) might be a better choice than description.

We can reopen the issue @egandro when/if you create a PR for this. But due to the age of the issue we’ll close it for housekeeping purposes.
