### ISSUE TITLE
isInt validation fails when property passed as string

### ISSUE THREAD

**Issue by igarioshka** [lukeautry/tsoa#1241]
When decorating a numeric property with `@isInt` decorator, the validation fails to catch the validation error when that property is passed as a string. 

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I'd expect consistency in runtime validation or an additional validation layer for the property to be exactly number when the model states it's a number. 

## Current Behavior

Given
```
export type MyFavDto = {
/**
   *  Order number.
   *
   * @isInt
   */
  order: number;
}
```
Runtime validation fails with request as integer ie:

```
{
"order": 10000000000000000000000,
}
```
but passes validation with request as 
```
{
"order": "10000000000000000000000", // notice the quotes
}
```

## Possible Solution

I've traced the logic to the interaction of the template helper with the validate library:
the template helper passes the value to the validator as a string:

**[templateHelpers.ts#L156](https://github.com/lukeautry/tsoa/blob/master/packages/runtime/src/routeGeneration/templateHelpers.ts#L156)**
```
 if (!validator.isInt(String(value))) {
```

**isInt.js** 
```
var int = /^(?:[-+]?(?:0|[1-9][0-9]*))$/;
var intLeadingZeroes = /^[-+]?[0-9]+$/;

function isInt(str, options) {
return regex.test(str) ... ;
}
```
* In case when the value is passed in JSON as an integer, that string becomes '1e+22' (scientific notation), so the regexp fails as there are letters and a plus sign in the middle. 
* In case when the value is passed in JSON as an string, that string remains '10000000000000000000000' so the regexp check passes as there are no letters and plus signs.

I guess there is a possibility to provide min/max as a workaround, but this doesn't seem as expected behavior. 
I also think that if the client would be generated from spec, the typings would match. 
The case though seems to be unexpected.

## Context (Environment)

Version of the library: 4.0.0-alpha.2
Version of NodeJS: 

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
I think this would be best changed/discussed over at [validator.js](https://github.com/validatorjs/validator.js)

**Comment by igarioshka** [comment]
To me this seems more of a problem in the way that tsoa uses the validator.js library. From the validator.js perspective, the string passed is in fact an integer (not confined to the range of an integers that javascript uses). 

from the documentation:
> isInt (tsoa special since TS does not know integer as a type)

So passing a string value (surrounded with quoted) into a field that expects a integer is breaching the contract.

As a solution, a layer of validation can be added to check if the property is passed as expected (i.e. without quotes):

```
const notInteger = '1111111000000000000000';
const isInteger = 1111111000000000000000;
const isDecimal = 11111110000000000000.00;

console.log(Number.isInteger(notInteger)); // false
console.log(Number.isInteger(isInteger));   // true
console.log(Number.isInteger(isDecimal)); // true
```

**Comment by igarioshka** [comment]
So my question is - is Tsoa intended to validate types provided in payloads? 
Having in mind that it binds the parameters to the methods, it seems that it should.
the table below shows the inconsistency i behavior when comparing to string payloads.

| Model definition  | Value Passed | Behavior|
| ------------- | ------------- | ------------- |
| <pre>/**<br>* @maxLength 255<br>*/<br>firstName: string;</pre> | `"firstName": 5` | <pre>"requestBody.firstName": {<br>      "message": "invalid string value",<br>      "value": 5<br>}</pre> |
| <pre>/**<br>* @isInt <br>*/<br>order: number ;</pre>  | `"order": "10000"`  | * no error <br> * value set to 10000 (implicit conversion)   |
| <pre>/**<br>* @isBool <br>*/<br>active: boolean ;</pre>  | `"active": null`  | * no error <br> * value set to false  |
| <pre>/**<br>* @isBool <br>*/<br>active: boolean ;</pre>  | property omitted | * no error <br> * value set to false  |
