### ISSUE TITLE
tsoa for schemas + something else for paths

### ISSUE THREAD

**Issue by tallalnparis4ev** [lukeautry/tsoa#1246]
Hello there,

I am trying to document a typescript express API that doesn't use controllers, it simply does router.get('/path', handler). 

As of now both paths and schemas are auto documented via swagger-jsdocs. Swagger-jsdocs has a lot of redundancy, especially for the schemas. 

My question is: is there a way to use tsoa for my schemas and something else (i.e. swagger-jsdocs or anything that you recommend) for my paths.

I'm looking purely for OpenAPI autogeneration (other features don't matter as much), thanks very much.

**Comment by WoH** [comment]
I'd say that's something you don't want to do with tsoa. But you can take a look at the controller generator and the type resolver for inspiration. If your dependency on express isn't set in stone, I'd say you should take a look at fastify, their OpenAPI plugin and typebox to get a similar experience where types, validation, routes and the OpenAPI spec are in sync, while still having the ability to use functions to handle requests.

**Comment by tallalnparis4ev** [comment]
> I'd say that's something you don't want to do with tsoa. But you can take a look at the controller generator and the type resolver for inspiration. ~If your dependency on express isn't set in stone, I'd say you should take a look at fastify, their OpenAPI plugin and typebox to get a similar experience where types, validation, routes and the OpenAPI spec are in sync, while still having the ability to use functions to handle requests.~

Thanks for the super fast reply!

Why do you not recommend getting the OpenAPI schemas `tsoa` generates for interfaces (because it does this REALLY cleanly) and passing this to whatever I decide to use for generating the OpenAPI for paths?

Also, please could you point me to the code where `tsoa` converts TypeScript interfaces to OpenAPI ?

**Comment by tallalnparis4ev** [comment]
After exploring many projects that take TypeScript interfaces to OpenAPI schemas, `tsoa` is the best by far. A hacky solution that works is to make some dummy controller, then use `tsoa-cli` to generate the OpenAPI schemas.

One solution that works:
```typescript
import { B } from "./b"

interface User extends B{
  a : number
}

interface Anotha1 {
  lol: string
}

interface ToDocument{
  user: User | Anotha1
}

@Route("ThisIsSuperHacky")
class ThisIsSuperHacky {
  @Get("")
  public async ThisIsSuperHacky(): Promise<ToDocument> {
  }
}
```
