### ISSUE TITLE
Announcement: Code Generator for Angular2/4 Client, Node Rest Client, Android Retrofit Client

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#125]
Hello everybody,

I'd like to announce my code Generator (based on TSOA Swagger files)

https://github.com/egandro/nicassa-generator

It can currently create clients (based on swagger files) for:

- Angular 2 / 4 (Typescript)
- NodeJS (Typescript via UniRest)
- Android 5.x (Java via Retrofit 2)

Other tools like a Java Client or a C# Client can be created without any efford.

The generator can also create a Database Access Layer for:

- Sequelize Typescript (Using the Sequelize ORM Mapper) in NodeJS (MySQL, MSSQL, Postgres, Sqlite)
- Android Java (Using the ORMLite Mapper) (SQLite)

The Schema Informations are read from the Database ("Model First Approach") using this tool

https://github.com/egandro/nicassa-parser-db

The Typescript Entities generated for the Databaase Layer can be directly used as Entities in the Controllers for TSOA.

I think this is the most complete approace for a tool like this for tsoa.

If you are willing to help - ask :)

**Comment by myflowpl** [comment]
Have you checked the swagger-codegen-cli ?
https://github.com/swagger-api/swagger-codegen#to-generate-a-sample-client-library
i'm using it to generate my angular 2+ client from swagger json file (one you can get from tsoa) and it works fine for me, it also allows to generate client for node, node+ts and tons of other languages
what is the purpose of doing other generator  ?

**Comment by egandro** [comment]
I needed support for:

- sequelizejs (Postgres, SQlite, MSSQL, MySQL) ORM Mapper -> Typescript Code
- Android SQLite (ORM Mapper -> Java Code)
- Android REST (Retrofit -> Java Code)
- Angular 2 REST (based on swagger).

The single point of truth is the server database e.g. Postgress or MSSQL for my main projects.
I change a Table or create a View. Push one button and I have ORM Mapper + REST Server + Client up and working.

I am not aware of any tool that can do all this things - of course - there are tools that can handle parts far better then my generator.

**Comment by myflowpl** [comment]
> The single point of truth is the server database

this explains a lot
ok, so for me it's not good way of designing your app
but I just have different approach, database as a plugin not as single source of truth

good luck with your work

**Comment by egandro** [comment]
The DB is the single source of trouth :)

I use database first with SAP PowerDesinger.

But I have more than one DB and more then one API and more then one Programming Language / Technologie :)

In the end you write DTOs or Entites by a text editor - that's what the generator creates automaticually.
