### ISSUE TITLE
Property annotations on nested objects

### ISSUE THREAD

**Issue by stephannielsen** [lukeautry/tsoa#1250]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

In my model we are using nested objects and I was wondering if we can apply property validation comments on higher level so that they are passed down to lower levels.

To explain this better:

We have top level model exposed `ValueCollection`. This object has a few properties which are of a generic type `Value<T>` with `T` being something like `number` or `string`. We have specific interfaces for `IntValue` and `FloatValue` where `value` is of type `number` and further restricted to `int` and `float` via tsoa annotations. This works fine.

Now, in our situation we sometimes have further restrictions on the `value` property, e.g. `minimum` or `maximum`. But we cannot use the `@minimum` annotation on the outer model and pass them down to the specific property. Adding them on `IntValue` directly is also not possible as we would have to create separate models for each constraint combination.

Is there a way to declare a custom annotation/validator which applies `@minimum` and so forth to the lower level properties?

```tsw
interface Value<T> {
  value?: T;
  comment?: string;
}

export interface IntValue extends Value<number> {
  /**
   * @isInt
   */
  value?: number;
}

export interface FloatValue extends Value<number> {
  /**
   * @isFloat
   */
  value?: number;
}

export interface ValueCollection {
    value1?: IntValue; // allows only positive integers
    value2?: IntValue; // positive integers with min=3
    value3?: IntValue; // positive intergers with min=3 and max=20
    value4?: FloatValue; // floats
}
```

## Context (Environment)

Version of the library: 4.0.0
Version of NodeJS: 16

- Confirm you were using yarn not npm: [x]

**Comment by stephannielsen** [comment]
I did try to use annotations on `ValueCollection` like this, but that does not work as the annotation expects a number as first parameter - `value` is the property the minimum restriction should be applied to:

```tsw
export interface ValueCollection {
    /**
     * @minimum value 0
     */
    value1?: IntValue; // allows only positive integers
    value2?: IntValue; // positive integers with min=3
    value3?: IntValue; // positive intergers with min=3 and max=20
    value4?: FloatValue; // floats
}
```

**Comment by WoH** [comment]
```ts
export interface ValueCollection {
    /**
     * @minimum 0
     */
    value1?: IntValue; // allows only positive integers
}
```

Is this what you want?

**Comment by stephannielsen** [comment]
That doesn't work. `IntValue` is an object: `{ value?: number; comment?: string; }`. So the `@minimum` can't be applied - which property should it pick. I would like to specify, for which property of `IntValue` the `@minimum` is valid for: `@minimum <property> <value>`.

**Comment by stephannielsen** [comment]
Still open request.
