### ISSUE TITLE
Add @types/multer as peerDependency

### ISSUE THREAD

**Issue by azven-aumni** [lukeautry/tsoa#1251]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The `yarn build` CircleCI test should pass.

## Current Behavior

<img width="1410" alt="Screen Shot 2022-05-10 at 4 15 23 PM" src="https://user-images.githubusercontent.com/103446917/167740726-0ef95223-2bf3-434a-84f2-4052a4260a55.png">

## Possible Solution

I'm not aware of any solutions, so either a bug fix for this issue or a workaround would be appreciated.

## Steps to Reproduce

1. A Snyk scan has identified that tsoa@3.14.1 had vulnerable dependencies. 
2. I created a PR to upgrade to tsoa@4.0.0, which is then ran through a number of CircleCI tests. 
3. The last test `yarn build` fails due to the following error: `node_modules/@tsoa/runtime/dist/config.d.ts:43:18 - error TS2709: Cannot use namespace 'MulterOpts' as a type.`
4. The PR cannot be approved and merged.

## Context (Environment)

Version of the library: 4.0.0
Version of NodeJS: 16.14.2

- Confirm you were using yarn not npm: [x]

## Detailed Description
A fix for error TS2709.

## Breaking change?
No

**Comment by WoH** [comment]
This happens if you don't have `@types/multer` in your dependencies. I think we could require these types at least as a peerDep.

**Comment by RobbeCl** [comment]
@WoH Just a question: why wouldn't we want to import it as a dependency since we are importing it in `packages/runtime/src/config.ts`

**Comment by dxphilo** [comment]
Would love to pick up this issue if it is not yet assigned to anybody.
