### ISSUE TITLE
Literal string union treated as enum

### ISSUE THREAD

**Issue by eysi09** [lukeautry/tsoa#1259]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I have the following literal string union in my code:

```typescript
type MyUnion = "foo" | "bar"
```

With tsoa version 3.2.1, the following Swagger spec was generated:

```
"MyUnion": {
  "anyOf": [
    {
      "type": "string",
      "enum": [
        "foo"
      ],
      "nullable": false
    },
    {
      "type": "string",
      "enum": [
        "bar"
      ],
      "nullable": false
    }
  ]
},

```

This is what I'd expect. See also: https://github.com/lukeautry/tsoa/commit/c9d3ce499be2c2763bc759c5241d1eef21984a45

## Current Behavior

On tsoa 3.14.1 and 4.1.0 I now get the following:

```
"MyUnion": {
  "type": "string",
  "enum": [
    "foo",
    "bar"
  ]
},
```

Isn't the former the expected behaviour? Shouldn't the union translate to `"anyOf"` like it did in version 3.2.1 and below?

I use a separate tool to generate TS types from the Swagger spec. Before this change it returned `MyUnion = "foo" | "bar"` as expected. Now it returns:

```
enum MyUnion {
    Foo = "foo",
    Bar = "bar"
}
```

So in any case it looks like a breaking change between these minor versions.

My best guess is that it got introduced with https://github.com/lukeautry/tsoa/pull/793/ (although not quite sure).

## Possible Solution

Revert the changes made in https://github.com/lukeautry/tsoa/pull/793/ (if my guess if correct).

## Steps to Reproduce

1. Add the following type: `type MyUnion = "foo" | "bar"`
2. Generate the Swagger spec with Tsoa >= 3.14.1
3. Notice how the generated spec doesn't use "anyOf".

## Context (Environment)

Version of the library: 3.14.1
Version of NodeJS: 14.18.2

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
First, I agree that this behavior is unfortunate. But I think just from reading the different outputs, the newer output is more readable and therefore easier to understand. We did indeed put in a step to explicitly fold these string unions into one enum, explicitly to make it easier on tools that generate specs for various languages. I'm not sure what tool you are using, but I would ask them to evaluate why they would produce different results in each case.
