### ISSUE TITLE
Using enum values as interface property names results with "undefined" properties

### ISSUE THREAD

**Issue by maciejgoscinski** [lukeautry/tsoa#1264]
When using computed property names in interfaces, originating from enums or constants, I end up with property "undefined" in my result OAS.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Detailed Description

When using computed property names in interfaces (referring to an enum value or constant), such as:

```
export enum SupportedLanguage {
  en = "en",
  pl = "pl"
}

export interface Test {
  [SupportedLanguage.en]: string;
}
```

I end up with a property called "undefined" in my target OAS:
```
"properties": {
	"undefined": {
		"type": "string"
	}
},
```

## Expected behaviour
In the optimal scenario, I'd expect a property "en" of type "string".

In the suboptimal scenario, if this kind of notation is not to be supported, I'd expect a clear error message when generating OAS instead of weird output.

**Comment by WoH** [comment]
Would you like to submit a PR that supports this construct properly?

**Comment by KennyLindahl** [comment]
Hey, i have no experience working in this code base and i don't think i have time to get into it as i'm already late on a delivery.
But the issue is pretty general, enums is not possible to use as keys.

Do you think you have time to fix it?

**Comment by wilker7ribeiro** [comment]
I'm having the same problem with the latest version (v6.2.0).
For future reference if someone want to do a PR, I was able to change some files [here](
https://github.com/lukeautry/tsoa/commit/1a245cc9def133d9d68bb1b798064e8a70e7111e) get it to work.
Don't know if it was the right way of fixing but maybe help.

**Comment by jackey8616** [comment]
@wilker7ribeiro 
Feel free to submit a PR with proper test cases covered, We'd happy to review and give you feedback!

**Comment by wilker7ribeiro** [comment]
> @wilker7ribeiro Feel free to submit a PR with proper test cases covered, We'd happy to review and give you feedback!

Opened the PR https://github.com/lukeautry/tsoa/pull/1610
