### ISSUE TITLE
Generic interfaces generate invalid schema name

### ISSUE THREAD

**Issue by TimoGlastra** [lukeautry/tsoa#1266]
Not sure If I'm doing something wrong here, as it seems like something that is supported by tsoa, but when generating the swagger files for generic interfaces, the names of the schemas will contain characters (mainly %) that SwaggerUI / OpenAPI can't work with. Sanitizing the schema name manually and then running the server fixes the issue

## Sorting

  - [x] bug report

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

TSOA should generate a valid swagger.json file. Currently SwaggerUI can't resolve the reference, and pasting this in editor.swagger.io also informs the schema name is not valid:

```
Semantic error at components.schemas.FormatPayload_%5BExampleFormat%5D_
Component names can only contain the characters A-Z a-z 0-9 - . _
Jump to line 8
```

This is the schema where I manually sanitized the FormatPyaload_ExampleFormat_ name, which works:

```json
{
  "components": {
    "schemas": {
      "FormatPayload_ExampleFormat_": {
        "properties": {
          "example": {
            "properties": {
              "theValue": {
                "type": "string"
              }
            },
            "required": ["theValue"],
            "type": "object"
          }
        },
        "type": "object",
        "description": "Get the payload from a list of Format interfaces"
      }
    }
  }
}

```

I expect to write the code the same as it currently present, just that the generated swagger.json file is different.

## Current Behavior

```json
{
  "components": {
    "schemas": {
      "FormatPayload_%5BExampleFormat%5D_": {
        "properties": {
          "example": {
            "properties": {
              "theValue": {
                "type": "string"
              }
            },
            "required": ["theValue"],
            "type": "object"
          }
        },
        "type": "object",
        "description": "Get the payload from a list of Format interfaces"
      }
    }
  }
}

```

```ts
import { Body, Controller, Post, Route } from "tsoa";

export interface Format {
  key: string;
  value: unknown;
}

export interface ExampleFormat extends Format {
  key: "example";
  value: {
    theValue: string;
  };
}

interface CreateUserRequest {
  formats: FormatPayload<[ExampleFormat]>;
}

/**
 * Get the payload from a list of Format interfaces
 *
 * @example
 * ```
 *
 * type CreateOfferFormat = FormatPayload<[ExampleFormat]>
 *
 * // equal to
 * type CreateOfferFormat = {
 *  example: {
 *   theValue: string;
 *  }
 * }
 * ```
 */
export declare type FormatPayload<Fs extends Format[]> = {
  [Format in Fs[number] as Format["key"]]?: Format["value"];
};

@Route("example")
export class ExampleController extends Controller {
  @Post()
  public async createUser(
    @Body()
    requestBody: CreateUserRequest
  ) {
    console.log(requestBody);

    return 10;
  }
}
```

## Possible Solution

A possible solutions is to take into account characters allowed by OpenAPI. From the error message at editor.swagger.io this includes:

```
Component names can only contain the characters A-Z a-z 0-9 - . _
```

## Steps to Reproduce

1. 2. 3. 4.

Repo: https://github.com/TimoGlastra/tsoa-error

To reproduce:

1. clone the repo
2. `yarn install`
3. `yarn build`
4. See the generated swagger.json in the build folder with incorrect characters
5. `yarn start`
6. open http://localhost:3000, see the error displayed in swagger ui
7. Copy the swagger.json file and paste it at editor.swagger.io. See the error displayed in the error about incorrect naming.

## Context (Environment)

Version of the library: 4.1.0
Version of NodeJS: 16.13.0

- Confirm you were using yarn not npm: [x]

## Detailed Description

Change I want to propose is to generate valid OpenAPI schema names for generic interface that doesn't use percent encoded names.

## Breaking change?

This will be a breaking change, and will most likely affect open api generator as the interface names will be different. However I highly doubt any OpenAPI generator can work with percent encoded schema names.

**Comment by WoH** [comment]
The behaviour you're seeing is a bail out because our name generation didn't expect `[X]` in the model name. If we can find a better substitution, I'd happily merge a PR.
