### ISSUE TITLE
Include TypeScript interface/type in output schemas (without it being used in a route)

### ISSUE THREAD

**Issue by huzaifahj** [lukeautry/tsoa#1274]
I would like to do this in a controller file:

```ts
export interface User {
    name: string
}
```

And have it output in the `swagger.json` file under `components.schemas`.

Is there a way to do this without using the interface in a route? I would like to use the `openapi-typescript-codegen` package to generate a client with that interface as a "model".

**Comment by WoH** [comment]
This is not intended use, but there are JSON schema generators that you might wanna take a look at.
