### ISSUE TITLE
File Uploads: Multer - require is not defined in ES module scope

### ISSUE THREAD

**Issue by FrozenKiwi** [lukeautry/tsoa#1278]
(https://github.com/lukeautry/tsoa/blob/7d3cbf1ee20e657ad445fd2f942224e0ef2ae612/packages/cli/src/routeGeneration/templates/express.hbs#L25)

Generated code includes a require, which won't run.

## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Generated code should be ESM compliant (the rest of it is)

## Current Behavior

`ReferenceError: require is not defined in ES module scope, you can use import instead`

## Possible Solution

`import multer from 'multer';`

## Steps to Reproduce

https://github.com/thecointech/thecoin/tree/dev/apps/nft-service

Check this out, `yarn && yarn gen:swagger && yarn dev`

## Context (Environment)

Version of the library: 4.1.0
Version of NodeJS: v16.15.0

- Confirm you were using yarn not npm: [X]

## Detailed Description

Replace require with import fixes the issue.

## Breaking change?

No

**Comment by nomorechokedboy** [comment]
Hi @FrozenKiwi . I see that you have fixed this bug, but I am still facing it, can you help me?

**Comment by FrozenKiwi** [comment]
Hey @nomorechokedboy , first make sure you're up-to-date (I think 4.1.1 is the first version to include this).

If you're still having trouble, a better place to ask questions is usually StackOverflow.  Drop a link here and I'll help if I can.
