### ISSUE TITLE
Use allOf in OpenAPI to describe $ref properties

### ISSUE THREAD

**Issue by tallalnparis4ev** [lukeautry/tsoa#1280]
- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [ ] support request

Ran into this issue that was warned about on docs:
![image](https://user-images.githubusercontent.com/47358379/177176693-5262b48f-551a-40f6-8df0-134e48502d9e.png)

Can't you do:
```yaml
id:
  allOf:
    - $ref: '#/components/schemas/id'
    - description: Any description users like
```

Or is there something extra I'm missing? If it's easy as I say and you'd like it implemented, let me know and I'll get working.

**Comment by WoH** [comment]
What you suggested is a list of objects:
`[ { $ref: '#/components/schemas/id' }, {description: Any description users like}]`
This will not fork unfortunately

**Comment by WoH** [comment]
I don't think allOf would work here because the second element is not a valid schema object and/or would break a lot of tooling.
