### ISSUE TITLE
Single @BodyProp not being output with specGenerator3

### ISSUE THREAD

**Issue by theca11** [lukeautry/tsoa#1287]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Using a single `@BodyProp()` in a controller function should generate a corresponding output in the spec (v3)

## Current Behavior
No output for the `@BodyProp()` if it's the only one in the function. However, if there are 2+ `@BodyProp()`s they are correctly gnerated in the output. specGenerator2 doesn't have this issue.

## Possible Solution
I'm very new to tsoa, but the issue seems to have been introduced in [PR#1179](https://github.com/lukeautry/tsoa/pull/1179), especifically here: https://github.com/lukeautry/tsoa/blob/ab360b38d028b2fff813239bf3e8d8c5ec691b0f/packages/cli/src/swagger/specGenerator3.ts#L284 
That condition obviously prevents a single `@BodyProp` to be pushed to the output spec file.

## Steps to Reproduce

1. Write a simple controller:
```ts
@Put('test1')
public test1(
  @BodyProp() firstParam: string,
): void {
  return
}

@Put('test2')
public test2(
  @BodyProp() firstParam: string,
  @BodyProp() secondParam: string,
): void {
  return
}
```
2. Generate spec (v3)
3. Output will contain requestBody for `test2` but not for `test1`

## Context (Environment)

Version of the library: v4.1.1
Version of NodeJS: v16.15.1

- Confirm you were using yarn not npm: [x]

**Comment by MadMadJax** [comment]
Hi theca11, we also discovered this on Friday. I am in the process of creating a PR for the test and fix.
