### ISSUE TITLE
Hidden Controller referencing model should not generate model

### ISSUE THREAD

**Issue by marcusglowe** [lukeautry/tsoa#1290]
First of all, we love using tsoa. Thank you!

Today, when a hidden controller references a model / schema, it is included in the final output. This does not seem like it would be intended behavior.
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

When running `yarn tsoa spec`, you should get this:

```yaml
components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas: {}
    securitySchemes:
        basic:
            scheme: basic
            type: http
info:
    title: api
    version: 0.1.0
    contact: {}
openapi: 3.0.0
paths: {}
servers:
    -
        url: /v0
```

## Current Behavior

When running `yarn tsoa spec`, you get this:

```yaml
components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas:
        TestPayload:
            properties:
                key:
                    type: string
            required:
                - key
            type: object
    securitySchemes:
        basic:
            scheme: basic
            type: http
info:
    title: api
    version: 0.1.0
    contact: {}
openapi: 3.0.0
paths: {}
servers:
    -
        url: /v0

```

## Possible Solution
Ideally, it would be possible to use @Hidden on the model or the `@ignore` jsdoc, but neither seem to work for me.

## Steps to Reproduce

Controller example:
```ts
import { Hidden, Route, Controller, Get } from 'tsoa';

type TestPayload = {
  key: string;
};

@Hidden()
@Route('test')
export class TestController extends Controller {
  @Get()
  async route(): Promise<TestPayload> {
    return {
      key: 'value',
    };
  }
}

```
1. 2. 3. 4.

## Context (Environment)

Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [x]

## Detailed Description
Should not find any metadata from hidden controllers

**Comment by marcusglowe** [comment]
Our workaround, for now, is to use two separate tsoa generation scripts:
1. generates all routes (including those inside of a special `hidden` folder)
2. generates the spec (glob ignoring the `hidden` folder - thank you for implementing globbing :) )
This works but it requires us to organize our code around the tool, which isn't ideal

**Comment by jackey8616** [comment]
@marcusglowe
The feature you want is, `Hidding models which been use in a Hidden controller` ?

**Comment by marcusglowe** [comment]
Yes that's right!
