### ISSUE TITLE
Custom middleware does not work with esbuild because emitDecoratorMetadata is not supported

### ISSUE THREAD

**Issue by jsamilow** [lukeautry/tsoa#1293]
https://github.com/lukeautry/tsoa/issues/961

According to this ticket, `tsoa` doesn't rely on the `emitDecoratorMetadata` TS option. That seemed correct at the time of writing, but sadly appears to no longer be true: https://github.com/lukeautry/tsoa/blob/acdfeb4d398fa7416dd10e251029d9e109c216d3/packages/runtime/src/decorators/middlewares.ts#L41

Because `esbuild` doesn't support `emitDecoratorMetadata`, it appears that custom middleware via the `@Middlewares` annotation cannot be used with `esbuild.` 

Is there any advice for a workaround?

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml

```

```ts

```

## Current Behavior

```yaml

```

```ts

```

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
You need decorators/reflection, but I am not sure why the snippet you referenced would need the emitted metadata

**Comment by jsamilow** [comment]
Maybe I am misreading, but you are using `Reflect.getMetadata`: https://github.com/lukeautry/tsoa/blob/acdfeb4d398fa7416dd10e251029d9e109c216d3/packages/runtime/src/decorators/middlewares.ts#L52-L53

According to the [documentation](https://www.npmjs.com/package/reflect-metadata) for this library, you need emitted metadata.

**Comment by jsamilow** [comment]
Any update? Note that the middleware works fine when I run the application with `ts-node`, so it's plainly the use of `esbuild` that's tripping things up. If you're open to a pull request to remove the dependency on `reflect-metadata` I would look into how much work is involved.

**Comment by WoH** [comment]
I don't know what the status is for esbuild on supporting decorators. My understanding is that emitDecoratorMetadata only adds additional information about the shape of the target which we don't rely on afaik.

Current workaround: Use TS-Node, TSC or SWC

**Comment by jsamilow** [comment]
We fixed it. It turns out the issue is `import {Middlewares} from 'tsoa`. It works if we do `import {Middlewares} from '@tsoa/runtime` I guess I was barking up the totally wrong tree. Sorry about that.

**Comment by bkiac** [comment]
@jsamilow thanks for the suggestion! Build fails if I'm importing from `tsoa` but it works just fine with `@tsoa/runtime`
