### ISSUE TITLE
Upload Error when uploading two files

### ISSUE THREAD

**Issue by jadliaissam** [lukeautry/tsoa#1295]
## Sorting

- **I'm submitting a ...**

  - [ X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [ X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
When uploading two files with two different fields using two @UploadedFile annotations, TSOA should handle the upload as it does for a single file and process the request with the file extracted and put into the corresponding variable. When I inspected the generated files, I fond that TSOA use multer's single method to resolve file upload.
```

```ts

```

## Current Behavior
When uploading two files with two separate fields, Multer throws an error: UNEXPECTED FIELD

```yaml

```

```ts

```

## Steps to Reproduce

```ts
export class GlobalController extends Controller {
  @Middlewares([upload])
  @Post("testUpload")
  public async testUpload(
    @FormField() title: string,
    @FormField() description: string,
    @UploadedFile() file: any,
    @UploadedFile() file2: any,
  ): Promise<IResponseType> {
    console.log(file, file2, title, description);
    return {
      detail: "Upload !",
      success: true,
    };
  }
```

## Context (Environment)

Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [ ]

## Detailed Description
change the multer method from single() to other alternatives to support multiple file fields in same request

**Comment by WoH** [comment]
Did you try `@UploadFiles()`?

**Comment by jadliaissam** [comment]
thank you for your response, the thing is I need two separate file fields in the same request, For example : we may need for a new product an image before unboxing and another after unboxing, so I need two separate file fields. Of course, it is possible to send the two files using @uploadFiles() under the same filefield and judge by the order but this is not deterministic and the order is not guaranteed to be respected by Frontend teams.

From my investigation, the problem is due to using multer's single() method to handle the fileUpload, so I can see two possible solutions:
1) make it possible that the user  implements his own multer processing (not the current handleFile approach which makes you lose the benefits of TSOA and make you write the documentation of this route manually), the user can thus select the method to use from multer (fields, single, any , ...). 
2) Alter the current approach to detect if there are multiple @UploadFile fields and act accordingly by changing single to another method.

**Comment by jimmyshe** [comment]
I meet the same issue, wondering how to solve it.

**Comment by jadliaissam** [comment]
Got no definitive solution, this pushed me to migrate to NestJs. Now I am happy
