### ISSUE TITLE
Problem resolving Typegoose's ArraySubDocumentType

### ISSUE THREAD

**Issue by ferranblanche** [lukeautry/tsoa#1299]
When trying to make use of Typegoose's Helper Type `ArraySubDocumentType`, TSOA throws the following Error:

```
$ tsoa spec-and-routes
There was a problem resolving type of 'DocumentType<Episode, BeAnObject>'.
There was a problem resolving type of 'ArraySubDocumentType<Episode>'.
There was a problem resolving type of 'Series'.
Generate routes error.
```

Find here an example of how the Typegoose's Helper Type `ArraySubDocumentType` is implemented:

```
class Episode {
  @prop()
  public title?: string;
}

class Series {
  @prop({ type: () => Episode })
  public episodes!: ArraySubDocumentType<Episode>[];
}

const SeriesModel = getModelForClass(Series);

const series = new SeriesModel({ episodes: [{ title: "first-episode" }, { title: "second-episode" }]})

series.episodes[0].parent() === series;
series.episodes[0].parentArray() === series.episodes;
```

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The routes are generated seamlessly.

## Current Behavior

Currently throws the following Error:

```
$ tsoa spec-and-routes
There was a problem resolving type of 'DocumentType<Episode, BeAnObject>'.
There was a problem resolving type of 'ArraySubDocumentType<Episode>'.
There was a problem resolving type of 'Series'.
Generate routes error.
```

**Comment by ferranblanche** [comment]
Find the documentation on Typegoose's Helper Type `ArraySubDocumentType` here:
https://typegoose.github.io/typegoose/docs/api/types/document-type/#helper-type-subdocumenttype

**Comment by WoH** [comment]
If you look at the source, I'm sure even if we could support that, I don't think this would be helpful in any way.

Maybe I'll take a look to know why it breaks out of curiousity, but I can guarantee you the produced type would be an absolute mess.

**Comment by ferranblanche** [comment]
Hi @WoH, thanks for your quick reply.

We ended up solving it by explicitly stating that episodes do have an ID and it gets generated automatically by typegoose:
```
import { prop } from '@typegoose/typegoose';
import { Types } from 'mongoose';

class Episode {
  @prop({ auto: true })
  public _id?: Types.ObjectId;

  @prop()
  public title?: string;
}
```

That makes series simpler:
```
class Series {
  @prop({ type: () => Episode })
  public episodes!: Episode[];
}

const SeriesModel = getModelForClass(Series);
```

ℹ️ _Just as a side note_: We wanted to use Typegoose's Helper Types to make it as seamless to work with SubDocuments as it is to work with Documents themselves.

Thanks again for your reply, @WoH . I'm closing this issue.
