### ISSUE TITLE
Schema generation no longer works with Typescript 4.8

### ISSUE THREAD

**Issue by meseta** [lukeautry/tsoa#1300]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Running `cli spec`, with any typescript version installed that matches the current dependency specified in package.json (currently ^4.5.4) correctly generates an openapi schema

## Current Behavior
When Typescript 4.8.3 is installed, running `cli spec` generates a schema with no routes or paths.
when Typescript 4.7.4 is installed, everything is fine

## Possible Solution

Pin typescript version number in cli's package.json to <4.8.0 until a solution can be found. Resolve whatever has changed between 4.7.0 and 4.8.0. From some light debugging, it would appear that `extractNodeFromProgramSourceFiles()` is no longer extracting any controllerNodes

End-users using yarn can workaround this by pining subdependency version by using selective dependency resolution. Add `resolutions` to package.json:
```json
  "resolutions": {
    "@tsoa/cli/typescript": "~4.7.4"
  },
```

## Steps to Reproduce

1. install in a way so that cli will use Typescript 4.8.3
2. run `cli spec` on a project that was previously working with earlier versions of typescript
3. observe generated package.json does not include any routes and paths

## Context (Environment)

Version of the library: 4.1.1
Version of NodeJS: 16.126.0

(note: using Yarn 3.2.3 with PNP)
- Confirm you were using yarn not npm: [x]

## Breaking change?

Yes. If anyone installs with the latest typescript 4.8.3, TSOA spec generation will not work

**Comment by simllll** [comment]
Experience the same issue, but somehow only in one of our apis... I will debug it later and let you know if I find something.
