### ISSUE TITLE
No routes generated when following the Getting started guide

### ISSUE THREAD

**Issue by amda-phd** [lukeautry/tsoa#1301]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The `routes.ts` file is produced and contains models and routes based on the provided controllers.

```json
\\ package.json
{
  "name": "tsoa-hello-world",
  "main": "build/src/server.js",
  "scripts": {
    "build": "tsoa spec-and-routes && tsc",
    "start": "node build/src/server.js"
  },
  "dependencies": {
    "body-parser": "^1.20.0",
    "express": "^4.18.1",
    "tsoa": "^4.1.1"
  },
  "devDependencies": {
    "@types/body-parser": "^1.19.2",
    "@types/express": "^4.17.13",
    "@types/node": "^18.7.13",
    "typescript": "^4.7.4"
  }
}
```

```json
// tsoa.json
{
  "entryFile": "src/server.ts",
  "noImplicitAdditionalProperties": "throw-on-extras",
  "controllerPathGlobs": ["src/**/*Controller.ts"],
  "spec": {
    "outputDirectory": "build",
    "specVersion": 3
  },
  "routes": {
    "basePath": "/api/v1",
    "routesDir": "src",
    "middleware": "express"
  }
}
```

```ts
\\ healthController.ts
import { Get, Route, Controller } from "tsoa";
import { Health } from "./health";
import { HealthService } from "./healthService";

@Route("health")
export class HealthController extends Controller {
  @Get()
  public async getHealth(): Promise<Health> {
    return new HealthService().get();
  }
}
```

A complete sample of a simplified implementation of the tsoa's Getting Started Guide can be found [here](https://github.com/amda-phd/tsoa-hello-world).

## Current Behavior

Running `yarn tsoa routes` produces a `routes.ts` file, but it doesn't contain any of the information from the controllers or any route.

```ts
// routes.ts
import { Controller, ValidationService, FieldErrors, ValidateError, TsoaRoute, HttpStatusCodeLiteral, TsoaResponse, fetchMiddlewares } from '@tsoa/runtime';
import type { RequestHandler } from 'express';
import * as express from 'express';

const models: TsoaRoute.Models = {
};
const validationService = new ValidationService(models);

export function RegisterRoutes(app: express.Router) {
    function isController(object: any): object is Controller {
        return 'getHeaders' in object && 'getStatus' in object && 'setStatus' in object;
    }

    function promiseHandler(controllerObj: any, promise: any, response: any, successStatus: any, next: any) {
        return Promise.resolve(promise)
            .then((data: any) => {
                let statusCode = successStatus;
                let headers;
                if (isController(controllerObj)) {
                    headers = controllerObj.getHeaders();
                    statusCode = controllerObj.getStatus() || statusCode;
                }

                

                returnHandler(response, statusCode, data, headers)
            })
            .catch((error: any) => next(error));
    }

    

    function returnHandler(response: any, statusCode?: number, data?: any, headers: any = {}) {
        if (response.headersSent) {
            return;
        }
        Object.keys(headers).forEach((name: string) => {
            response.set(name, headers[name]);
        });
        if (data && typeof data.pipe === 'function' && data.readable && typeof data._read === 'function') {
            data.pipe(response);
        } else if (data !== null && data !== undefined) {
            response.status(statusCode || 200).json(data);
        } else {
            response.status(statusCode || 204).end();
        }
    }

    function responder(response: any): TsoaResponse<HttpStatusCodeLiteral, unknown>  {
        return function(status, data, headers) {
            returnHandler(response, status, data, headers);
        };
    };

    function getValidatedArgs(args: any, request: any, response: any): any[] {
        const fieldErrors: FieldErrors  = {};
        const values = Object.keys(args).map((key) => {
            const name = args[key].name;
            switch (args[key].in) {
                case 'request':
                    return request;
                case 'query':
                    return validationService.ValidateParam(args[key], request.query[name], name, fieldErrors, undefined, {"noImplicitAdditionalProperties":"throw-on-extras"});
                case 'path':
                    return validationService.ValidateParam(args[key], request.params[name], name, fieldErrors, undefined, {"noImplicitAdditionalProperties":"throw-on-extras"});
                case 'header':
                    return validationService.ValidateParam(args[key], request.header(name), name, fieldErrors, undefined, {"noImplicitAdditionalProperties":"throw-on-extras"});
                case 'body':
                    return validationService.ValidateParam(args[key], request.body, name, fieldErrors, undefined, {"noImplicitAdditionalProperties":"throw-on-extras"});
                case 'body-prop':
                    return validationService.ValidateParam(args[key], request.body[name], name, fieldErrors, 'body.', {"noImplicitAdditionalProperties":"throw-on-extras"});
                case 'formData':
                    if (args[key].dataType === 'file') {
                        return validationService.ValidateParam(args[key], request.file, name, fieldErrors, undefined, {"noImplicitAdditionalProperties":"throw-on-extras"});
                    } else if (args[key].dataType === 'array' && args[key].array.dataType === 'file') {
                        return validationService.ValidateParam(args[key], request.files, name, fieldErrors, undefined, {"noImplicitAdditionalProperties":"throw-on-extras"});
                    } else {
                        return validationService.ValidateParam(args[key], request.body[name], name, fieldErrors, undefined, {"noImplicitAdditionalProperties":"throw-on-extras"});
                    }
                case 'res':
                    return responder(response);
            }
        });

        if (Object.keys(fieldErrors).length > 0) {
            throw new ValidateError(fieldErrors, '');
        }
        return values;
    }
}
```

## Steps to Reproduce

1. `git clone https://github.com/amda-phd/tsoa-hello-world`
2. `yarn install`
3. `yarn tsoa routes`

Live version [here](https://codesandbox.io/p/github/amda-phd/tsoa-hello-world/csb-1fiu2l/draft/goofy-roentgen?workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cl7ezlfv0000plpfx81yd45ar%2522%252C%2522key%2522%253A%2522cl7ezlfrc00jg446l9p2n3off%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D).

## Context (Environment)

Version of the library: 4.1.1
Version of NodeJS: 16.15.0 (but also tested with 12.22.12 with the same result)
Version of Typescript: 4.7.4 due to [this issue](https://github.com/lukeautry/tsoa/issues/1300)

- Confirm you were using yarn not npm: [x]

## Detailed Description

The behavior is exactly as it was reported in this previously [opened issue](https://github.com/lukeautry/tsoa/issues/924), but no ignore patterns are being provided in this case. As mentioned in the previous issue, multiple glob patterns have been attempted, including the specific path to the controller and importing the controller on the `app.ts` file. All with the same result. When deliberately specifying an incorrect glob pattern, an error is returned, exactly as expected.

**Comment by WoH** [comment]
I guess you controller file is not placed inside the src folder?

**Comment by amda-phd** [comment]
Thank you @WoH for your answer. Yes, the `healthController.ts` file is inside `src/health`. This project is just an attempt to make tsoa work following the steps described in your [getting started](https://tsoa-community.github.io/docs/getting-started.html) guide. As mentioned, I have even tried referencing specifically the controller file in `controllerPathGlobs` and importing it directly at the `app.ts`, as it's often suggested in the documentation. None of those versions work. If I specify a deliberately incorrect path, I get an error, exactly as expected.
![Screenshot 2022-08-30 at 09 32 46](https://user-images.githubusercontent.com/53900519/187377406-31320a3d-b918-49d7-ae2a-407e33a0a0a6.png)

**Comment by dimonkov** [comment]
Same issue here - followed the Getting Started guide step by step, and no routes were registered in the end.
Problem persists regardless of the platform.

Tested on Linux, Windows, Mac - same effect.
No routes are registered, and none present in the swagger.json file.

**Comment by haimkastner** [comment]
Hi 
I had the same issue, I used npm till now, then due to this issue I run yarn install in the hope to fix it, but it isn't helped.

After digging into the dependencies tree in the `package-lock.json` and `yarn.lock` files, it seems that altho the `@tsoa/cli` requires the typescript  `^4.1.2` the npm decided to set the problematic typescript version `4.8.2`.

And once it's set, yarn is not removing it, after deleting the `node_modules` directory and running yarn install again, it works.

So probably you also have the problematic typescript version `4.8.2` somehow in your `node_module`, if so, try to delete the `node_modules` and try again, and also try to read the `yarn.lock` file to see if this version exists and why.

**Comment by amda-phd** [comment]
But bear in mind: before I opened this issue, I had already seen the [open issue](https://github.com/lukeautry/tsoa/pull/1302) about TypeScript and I'm using version 4.7.4 to prevent that from happening. After removing `node_modules` and even `yarn.lock` and doing `yarn install` from scratch, the problem persists.

**Comment by dimonkov** [comment]
How should I modify the package.json for proper resolution of typescript version?

**Comment by haimkastner** [comment]
A @WoH mentioned, adding this property to your package.json should do the work:
```json
"resolutions": {
    "@tsoa/cli/typescript": "4.5.5"
}
```

**Comment by haimkastner** [comment]
Maybe try to set a newer typescript version `4.7.4`.

Do you see why yarn is setting `4.8.2` in the tree or if you can share your `yarn.lock` file?

**Comment by amda-phd** [comment]
Adding @WoH's suggestion to `package.json`
> ```json
> "resolutions": {
>     "@tsoa/cli/typescript": "4.5.5"
> }
> ```
removing `node_modules` and `yarn.lock`and reinstalling the whole package hasn't changed the behavior for me. I still get an non-filled `routes.ts` file.

**Comment by WoH** [comment]
https://github.com/lukeautry/tsoa/releases/tag/v5.0.0-alpha.0

**Comment by vekexasia** [comment]
@WoH i tried 5.0.0-alpha.0 tasks ends up almost immediately and no file is generated. (build folder is empty.)

**Comment by WoH** [comment]
Yeah, yargs got messed up. I'll push out a fix

**Comment by amda-phd** [comment]
Changing the `typescript` version for all the project via resolutions has finally produced a valid `routes.ts` for me:
```ts
"resolutions": {
    "typescript": "4.7.4"
  }
```

**Comment by WoH** [comment]
@vekexasia should be g2g now, I tested vs. the sample repo provided by @amda-phd.

`yarn install && yarn add typescript tsoa@next && yarn routes`

now gives me a model, a controller and fetchMiddleware without type roblems.
Still expect some bumps with TS 4.8 though.
