### ISSUE TITLE
Missing ECMAScript modules (ESM) support in both controller search and routes generation

### ISSUE THREAD

**Issue by yashag-art** [lukeautry/tsoa#1307]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

In `tsoa.json` or the programmatic API, when providing the following configuration
```ts
{
  controllerPathGlobs: ["src/**/*.controller.mts"]
}
```
it should search all files ending with `.controller.mts`.

Also when generating `routes` with `tsoa` an option to generates a `routes.mts` files with correct imports of controllers should be provided.

Full `tsoa.json` file:
```json
{
  "entryFile": "./src/index.mts",
  "noImplicitAdditionalProperties": "throw-on-extras",
  "controllerPathGlobs": ["src/**/*.controller.mts"],
  "spec": {
    "specVersion": 3,
    "outputDirectory": "./src/docs/api",
    "entryFile": "./src/index.mts"
  },
  "routes": {
    "routesDir": "src/routes",
    "middleware": "express",
    "esm": true
  }
}
```

## Current Behavior

The following error pops up every time I run `tsoa spec`:
```shell
GenerateMetadataError: [src/**/*.controller.mts] globs found 0 controllers.
```
If I omit the `controllerPathGlobs` field in `tsoa.json` it finds all the decorators in my controller files, but I have no control over where the search occurs (and I tried multiple variations of the glob). Through the programmatic API it doesn't work (I get this error) either way (with the option provided or without it).

And when trying to generate routes with `tsoa routes` the TypeScript file created is:
1. A `.ts` file and not `.mts` as all my other files (there is no option to influence this)
2. contains a broken controller import:
```ts
import { SystemController } from './../system/system.controller..js';
```
Which not only has a broken syntax, but understandably generates this TypeScript error:
`TS2307: Cannot find module './../system/system.controller..js' or its corresponding type declarations.` 

## Steps to Reproduce

1. Create a `tsoa.json` file with a `controllerPathGlobs` field searching for `.mts` files
2. Create a `.mts` file with `tsoa` decorators with the scope `controllerPathGlobs` searches for
3. Run `tsoa spec`
4. Now that you receive the error, omit `controllerPathGlobs` and run `tsoa spec` successfully
5. Run `tsoa routes` with the configuration provided in the `tsoa.json` above and look at the generated file

## Context (Environment)

Version of the library: 5.0.0-alpha.1 (but also tested on 4.1.2)
Version of TypeScript: 4.8.2
Version of NodeJS: 16.16.0

- Confirm you were using yarn not npm: [ ]

**Comment by tboothman** [comment]
What is an mts file? What makes it different from a ts file? I'm probably out of the loop on something as I usually only compile code with typescript.

The reason you're getting imports with `..js` on the end is because of this mistake here: https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/routeGeneration/routeGenerator.ts#L183
It's removing any character then 'ts' at the end of the string. Just happened to work because everyone's files end in .ts, but yours don't.

**Comment by tboothman** [comment]
https://www.typescriptlang.org/docs/handbook/esm-node.html
TIL. Wow this is pretty horrifying.
Presumably if your files are .mts then it'd generate a .mjs file which means the import would need to be `import './mycontroller.mjs'` not the `.js` the esm config switch is adding now

**Comment by yashag-art** [comment]
Thank you for your response!

So in regards to the `mts` file extension, as you saw it is node's solution to the ESM system (or rather `mjs`). And while personally I agree it is pretty horrifying, it is the way to differentiate between the module systems going forward and it is being accepted and incorporated in the community more and more with each passing day. Which is why I believe it should be supported.

I completely understand it adds complexity to certain implementations, however I believe those changes are necessary so `tsoa` could be used in all Node TS projects.

As for the route's file name solution, when adding the following configuration:
```json
{
  "routes": {
    "routesFileName": "routes.mts"
  }
}
```
It results in the following error: ` Error: routesFileName should have a '.ts' extension`

**Comment by yashag-art** [comment]
I added support for the `.mts`/`.mjs` extensions in several places, but for some reason it doesn't allow me to push my new branch to origin. Open to any suggestions :)

**Comment by Kampfmoehre** [comment]
Was this solved somehow? I encounter the same problem in a new test project with ESM and TSOA.

**Comment by neilenns** [comment]
I also hit this today, using ESM (.mts) files with TSOA.

**Comment by Kampfmoehre** [comment]
> I also hit this today, using ESM (.mts) files with TSOA. 

I added PR #1455 to resolve this
