### ISSUE TITLE
Workaround needed for DeepPartial type defined in .d.ts

### ISSUE THREAD

**Issue by quaos** [lukeautry/tsoa#1310]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit
- Referring to: https://github.com/lukeautry/tsoa/issues/1138 (auto-closed as Stale)

## Expected Behavior

I have just introduced `DeepPartial` type into my codebase (backend API part), from which tsoa could previously generate OpenAPI specs normally. It should be able to resolve types specified in `*.d.ts` files, whether by adding to tsoa config or tsconfig.

```ts
// @src/types.d.ts

// Thanks to: https://grrr.tech/posts/2021/typescript-partial/
// and also: gustavohenke from https://stackoverflow.com/a/68699273/4119686
type DeepPartial<T> = {
  [attr in keyof T]?: T[attr] extends string | number | boolean | Date | null | undefined
    ? T[attr]
    : T extends Array<infer ArrayType>
    ? Array<DeepPartial<ArrayType>>
    : DeepPartial<T[attr]>;
};
```

```ts
// @src/models/params/update-item.ts

export default interface UpdateItemParams extends DeepPartial<Omit<ItemInfo, 'id' | 'slug' | 'createdAt'>> {
  // ...extra fields
}
```

```ts
// @src/controllers/api/my-items.ts

export default class MyItemsApiController {
  @Put('{id}')
  public async updateItem(
    @Path() id: string,
    @Body() reqData: UpdateItemParams
  ): Promise<UpdateItemResult> {
    // ...
  }
}
```

```js
// tsconfig.json

{
  "compilerOptions": {
    // ...
  },
  "include": ["src/cmd/**/*.ts", "src/*.d.ts", "tests/**/*.ts"],
  "exclude": ["node_modules"]
}
```

```js
// tsoa.config.json

{
  "entryFile": "./src/cmd/server.ts",
  "controllerPathGlobs": ["./src/controllers/**/*.ts"],
  "noImplicitAdditionalProperties": "silently-remove-extras",
  "spec": {
    "outputDirectory": "./api-docs",
    "specFileBaseName": "openapi-v1",
    "yaml": true,
    "version": "1",
    "specVersion": 3,
    "host": "localhost:8080",
    "basePath": "/api/v1",
    "securityDefinitions": {
      // ...
    }
  },
  "routes": {
    "basePath": "/api/v1",
    "routesDir": "./libs/tsoa/src/_generated",
    "middleware": "express",
    "authenticationModule": "./src/filters/tsoa-auth.ts"
  }
}
```

## Current Behavior

`tsc` can build the code normally, but I got `GenerateMetadataError: No declarations found for referenced type` when trying to generate OpenAPI spec file.

```
tsoa spec -c tsoa.config.json && tsoa routes -c tsoa.config.json

There was a problem resolving type of 'UpdateItemParams'.
Generate swagger error.
 GenerateMetadataError: No declarations found for referenced type DeepPartial. 
 in 'MyItemsApiController.updateItem'
    at /***/my-project/node_modules/@tsoa/cli/dist/metadataGeneration/methodGenerator.js:76:23
    at Array.map (<anonymous>)
    ...
```

Does anyone know a workaround?

## Possible Solution

The tool should refer to tsconfig.json, or has a section in its config file for handling this case

***UPDATE:*** I found an workaround, by including `types.d.ts` file within controller:

```
// @src/controllers/api/my-items.ts

// For TSOA
import '../../types.d.ts';
```

However this still looks like a hack. ***I need to comment the import line when building the files to run in Node, or else I'd get the error:*** (tried with both `import '../../types'` and `import '../../types.d.ts'`)

```
Error: Cannot find module '../../types.d.ts'
```

***UPDATE: As of 11.10.2022, the workaround above stopped working after new changes to another model interface***

```
GenerateMetadataError: No declarations found for referenced type DeepPartial
 in 'MyItemsApiController.updateItem'
```

## Steps to Reproduce

- Create a Typescript project
- Create file: `types.d.ts`, insert definition of `DeepPartial`, and include the path in `tsconfig.json`
- Create API endpoints that use `DeepPartial<SomeType>`
- Run `tsoa spec`

## Context (Environment)

Version of the library: 4.1.0
Version of NodeJS: 14.17.5
- Confirm you were using yarn not npm: [x]

**Comment by quaos** [comment]
***UPDATE: As of 11.10.2022, the workaround above stopped working after new changes to another model interface***

```
GenerateMetadataError: No declarations found for referenced type DeepPartial
 in 'MyItemsApiController.updateItem
```

**Comment by WoH** [comment]
@AnthonySLWhite please make sure they're part of your program and not skipped in type checking

**Comment by maint14** [comment]
try using 
`/// <reference path="path/to/file.d.ts" />`
for first line of your controller.
that's works for me
