### ISSUE TITLE
Avoid autogenerated response status in Controllers

### ISSUE THREAD

**Issue by pabloleonalcaide** [lukeautry/tsoa#1313]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Hi! First of all, congrats for this great project

I have a little problem with the infered response status (and response object): 

All my Controllers entry-point are `void` methods that can return a variety of responses (200 with content, 204 without content, 400 with error message...)
When a use annotations with some endpoint that return a response, `tsoa` infers automatically that, being a `void` method, the status code is 204 with no-content, even if I use the annotation @Response<MyResponse>(200, 'some description')

This is an example of my controller

```ts
  @Get()
  @Response<UserGetResponse>(200)
  public async execute(): Promise<void> {
    this.sendResponse(UserGetController.toResponse({user: undefined}));
  }

  protected sendResponse(params: Record<string, unknown>, statusCode?: number): void {
    this.response.status(statusCode || 200).json(params);
  }
```

## Current Behavior

With this code, currently `tsoa` generate two kind of responses instead of one (this is the swagger.json generated):

```json
"paths": {
        "/user": {
            "get": {
                "operationId": "Execute",
                "responses": {
                    "200": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UserGetResponse"
                                }
                            }
                        }
                    },
                    "204": {
                        "description": "No content"
                    }
                },
                "tags": [
                    "User"
                ],
                "security": [],
                "parameters": []
            }
        }
    },
```

## Possible Solution

I would like to find a way to ignore or override the inferred response (the status code 204 in my case) but I couldn't find anything in the Docs or the examples
¿It's possible?

## Context (Environment)

Version of the library: 4.1.2
Version of NodeJS: 16
Version of Express: 4.17.0

- [x] Confirm you were using yarn not npm

**Comment by jackey8616** [comment]
Try `this.setStatus(200)` 

https://github.com/lukeautry/tsoa/blob/f470d3eb312d426a16878dd1f8e6338481925686/tests/fixtures/controllers/methodController.ts#L96-L101

**Comment by pabloleonalcaide** [comment]
Hi @jackey8616 !!
Hi have tried with something like this, the `Status 204` dissapear in the Swagger UI, but also dissapear the Response example (`UserGetResponse` in this case)...  I think that `@SuccessResponse` don't allow me to define an object response, only the status code ¿is this correct?

```ts
  @Get()
  @SuccessResponse(200, 'User')
  @Response<UserGetResponse>(200)
  public async execute(): Promise<void> {
    const user = await this.useCase.execute();
    this.response.status(200).send(user);

    return Promise.resolve();
  }
```

I tried using both, `@SuccessResponse` and `@Response`, but the response interface is not shown in swagger UI , 
The `content` key dissapear in the swagger.json file=>

```
 "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserGetResponse"
                }
              }
            }
          },
```

**Comment by jackey8616** [comment]
`@SuccessResponse don't allow me to define an object response, only the status code ¿is this correct?`
Yes. You can use @Response

What exactly you expected?

**Comment by pabloleonalcaide** [comment]
I expected show only the info of the response 200 with his content using `@response`, but when I use 
```ts
@Response<MyResponse>(200)
```
The swagger.json file is generated with this (status-200 & `MyReponse` content) and another block with a `status-204` description that I don't want

**Comment by pcone** [comment]
I'm running into the same issue, I'm trying to use tsoa to generate openapi documentation for an API, but I'm *not* using the runtime tsoa functionality. I've got methods that conform to `(input: In) => Success | SomeError | NotFound', and I've decorated it with 

```
@Response<Success>(201, "description") 
@Response<SomeError> (400, "description") 
@Response<NotFound>(404, "description") 
```

This *almost* does what I need it to, except it generates an extra 200 Ok response in the documentation which I don't want.
