### ISSUE TITLE
Where is the API reference for version 4?

### ISSUE THREAD

**Issue by drhayes** [lukeautry/tsoa#1323]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The links I've found to the API Reference all point to this page: https://tsoa-community.github.io/reference/

I was expecting the docs for the most recent public release: 4.1.3. I was looking for docs about that sweet, sweet `Middlwares` decorator.

## Current Behavior

The API reference page is for v3.6.0. I don't see a way to switch to a v4 version.

I was looking for documentation about the new-ish `Middlewares` decorator but couldn't find it. Is that somewhere else besides the source code?

## Possible Solution

The docs are probably auto-generated. Maybe the generator needs to run for the recent release? Maybe a GitHub workflow should run on release that auto-generates them? That would fix the API Reference case now and in the future.

Maybe there should be a guide about it as well? The API Reference can be pretty terse.

I'm willing to help write the docs. I'm a relative tsoa newbie.

## Steps to Reproduce

1. Go to this page: https://tsoa-community.github.io/reference/
2. Look for `Middlewares` decorator documentation.
3. Check out the version number in the upper-left link.

## Context (Environment)

Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
Done
