### ISSUE TITLE
Express-routes in separate modules

### ISSUE THREAD

**Issue by BlackMoon** [lukeautry/tsoa#1324]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Dear developers, team

We migrate our express-based projects to TS + TSOA. 
Tsoa helps us a lot to save time on coding and type-checking.
But there are a few issues : 

Is it possible to generate each endpoint in a separate file in the controllers folder as we still need a route structure that is compatible with previous versions? 

As for swagger-gen - the generator successfully works as expected.

```yaml

```

```ts

```

## Current Behavior

```yaml

```

```ts

```

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 5.0.0-alpha.1
Version of NodeJS: 16

- Confirm you were using yarn not npm: [ ]

**Comment by pclements12** [comment]
This could potentially be solved by a more generic Route Generator like I have mentioned in #1340 
A serverless backend would need the same per route templates for each handler.

**Comment by WoH** [comment]
What @pclements12 said. Can you do this using #1342?
