### ISSUE TITLE
Is it possible to add a CHANGELOG.MD 

### ISSUE THREAD

**Issue by conradkirschner** [lukeautry/tsoa#1334]
## Changelog file to see what changed between versions

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Possible Solution

Adding a simple changelog that visualize changes that are done. 
Maybe highlight breaking changes, new features and bugfixes.

## Detailed Description

I saw that version 5 is already in alpha, but I doesnt get what what will be changed. 

## Breaking change?

I kept it in the template because it seems features can include breaking changes, therefore a changelog makes sense

**Comment by WoH** [comment]
As in [Releases](https://github.com/lukeautry/tsoa/releases)?
