### ISSUE TITLE
Feature Request: Map other decorators to tsoa decorators or to their associated functionality

### ISSUE THREAD

**Issue by rcollette** [lukeautry/tsoa#1336]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I am creating a controller using the decorators and base classes provided by [inversivy-express-utils](https://github.com/inversify/inversify-express-utils) and intend on using TSOA solely to produce documentation, not routes.

```ts
import {
  BaseHttpController,
  controller,
  httpGet,
  requestParam,
} from "@nota/inversify-express-utils";
import { HelloService } from "../services/Hello.service";
import { Get, Route } from "tsoa";

@Route("/api/v1/hello")
@controller("/api/v1/hello")
export class HelloControllerV1 extends BaseHttpController {
  constructor(private _helloService: HelloService) {
    super();
  }

  @httpGet("/:name")
  @Get("{name}")
  public async hello(@requestParam("name") name: string) {
    if (name === "throw") {
      throw new Error("Test of throwing an uncaught error.");
    }
    if (name === "bad") {
      // This might need to be done with another helper function to serialize to JSON and set 404 instead.z
      return this.badRequest("This is an example of a bad request");
    }
    return this.json(await this._helloService.hello(name));
  }
}
```

## Current Behavior
As you may note, there becomes a requirement to implement parallel decorators

## Context (Environment)

Version of the library: 4.1.3
Version of NodeJS: 16.17.0

- Confirm you were using yarn not npm: [ ]

## Detailed Description

I would like a way for TSOA to obtain decorator data from alternate decorators.   Logically I think of this as an abstraction via an overridable class and/or interface where I can provide an implementation that provides the necessary implementation.

After looking at the code I might be able to propose something more detailed.

**Comment by rcollette** [comment]
Related to #1326

**Comment by WoH** [comment]
There's a dirty secret the doctor doesn't want you to know about when it comes to this.
Import your httpGet as Get, we already support the colon syntax. Similarly, `controller` as `Route`

**Comment by rcollette** [comment]
first

**Comment by rcollette** [comment]
second?

**Comment by rcollette** [comment]
third
