### ISSUE TITLE
`@Deprecated()` decorator not working with `@FormField()`

### ISSUE THREAD

**Issue by Jule-** [lukeautry/tsoa#1345]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request (? I let you decide)
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Usage of `@Deprecated()` on `@FormField()` should set `deprecated: true` correctly, like in the doc [here](https://tsoa-community.github.io/docs/decorators.html#parameters-openapi-3-only).

Example:

```ts
@Get("v2")
public async findV2(
  @FormField() text: string,
  @Deprecated() @FormField() dontUse?: string
): Promise<any> {

}
```

## Current Behavior

No deprecation is generated in `openapi.json`.

## Context (Environment)

Version of the library: 4.1.3
Version of NodeJS: v16.17.1

- Confirm you were using yarn not npm: [ ]

**Comment by Jule-** [comment]
I think there might be some missing line here:
https://github.com/lukeautry/tsoa/blob/8d23f961621a6ae67a2498525d2e6766dc5faf6b/packages/cli/src/swagger/specGenerator3.ts#L385-L391

Adding this in the loop will feed the `openapi.json` file correctly:
```ts
if (properties[parameter.name].deprecated) {
  properties[parameter.name].deprecated = parameter.deprecated;
}
```

**Comment by WoH** [comment]
Would you like to submit this as a PR?

**Comment by Jule-** [comment]
@WoH Yeah, of course, if you want me to! I just do not know this project deeply, so needs to be carefully double-checked by someone. I have just followed my lead back to that line of code to understand what is missing from the documentation.

Let me put that in order. :wink:

(I will probably have one proposal following this one around `@FormField()` generation - spoiler end)

**Comment by Jule-** [comment]
@WoH is there some getting started content in order to contribute (other than [CONTRIBUTING.md](https://github.com/lukeautry/tsoa/blob/master/docs/CONTRIBUTING.md))? Because I've already struggled to run tests. It seems that this repo needs at least NodeJS v17 to run tests properly. (NodeJS v16.17.1 cannot run tests)

**Comment by WoH** [comment]
I'll check but node 16 should work just fine.
