### ISSUE TITLE
Use of @FileUpload adds a security sensitivity via multer() 

### ISSUE THREAD

**Issue by ClementValot** [lukeautry/tsoa#1351]
### Issue
When using `@UploadedFile` in a controller that requires a file to be uploaded 
e.g. 
```
export class myController extends Controller {
  @Post('/file')
  public async sendFile(
    @UploadedFile() myFile: File,
  ): Promise<void> {
    doSomething(myFile.buffer)
  }
}
```

The generated routes.ts automatically adds a new multer object 
e.g. [/packages/cli/src/routeGeneration/templates/express.hbs](https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/routeGeneration/templates/express.hbs)
```
{{#if useFileUploads}}
{{#if esm}}
import multer from 'multer';
{{else}}
const multer = require('multer');
{{/if}}
const upload = multer({{{json multerOpts}}});
{{/if}}
```

If no multerOpts are provided, the generated call to `multer()` raises a security issue that is for example picked up by code quality tools like Sonar ([Related Sonar issue](https://rules.sonarsource.com/typescript/RSPEC-5693)) 

[Documentation](https://tsoa-community.github.io/docs/file-upload.html#custom-multer-upload) indicates that in order to specify a maximum file size (or other multer options), a new multer() must be explicitly instantiated each time. 

Reading the code indicates that `multerOpts` can be provided directly in the `tsoa.json` config file ([Commit from December 2021](https://github.com/lukeautry/tsoa/commit/d975c2b8a9b26923e6198688b4a56827d67b700f) which is not reflected in the documentation)

### Suggestion
- The documentation should indicate the possibility of providing multerOpts in the tsoa config file
- The RouteGenerator should provide a default file size if not provided (Which should follow the recommendation of 8MB); If a developer wants to increase the content length limit they will have to explicitly specify their limit which makes them more aware of the underlying risk.

**Comment by WoH** [comment]
For the 5.0.0 we could make this breaking change, if you want to submit a PR, I think something between 5-8m may make sense for many people.
W/ regards to docs, the PR should be at https://github.com/tsoa-community/docs
