### ISSUE TITLE
Possible to get all query parameters in one object?

### ISSUE THREAD

**Issue by grug** [lukeautry/tsoa#1355]
Hey there,

Is it possible to have a GET endpoint where we can collate all query params into one parameter.

For example:

```ts
  type AllTheThings = {
    foo: string;
    bar: string;
    baz: string;
  };

  @Get()
  getBy(@Query things: AllTheThings ) {
    console.log(things); // { foo: 'asdaf', 'bar': 'asdasd', 'baz': '232313' }
    doSomeOtherThings();
  }
```

The use case for this is I want an endpoint that takes up to, say, 7 different query params to describe a filter to apply in a db query. Instead of having to manually pull all of those out, it would be convenient to get them in one object. An example request would be `foo.com/?foo=asdaf&bar=asdasd&baz=232313`

Hopefully this makes sense.

**Comment by WoH** [comment]
This is possible in the 5.x (currently alpha, looking to skip straight to RC next) using the `@Queries` Decorator.

**Comment by grug** [comment]
Any idea when 5.0 is likely to release?
