### ISSUE TITLE
Failing with TS1371 using generated routes for Koa

### ISSUE THREAD

**Issue by tipok** [lukeautry/tsoa#1360]
While generating routes for Koa I'm getting the following error while building with `tsc` or running with `ts-node`.

```
error TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.

import * as KoaRouter from '@koa/router';
```

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I would expect a type import as generated in the line above so it would be:

```ts
import type * as KoaRouter from '@koa/router';
```

## Current Behavior

Currently it's generating:

```ts
import * as KoaRouter from '@koa/router';

```

## Context (Environment)

Version of the library: 4.1.3
Version of NodeJS: v18.12.1

- Confirm you were using yarn not npm: [x]

## Breaking change?

Should not be a breaking change

**Comment by WoH** [comment]
Hi, could you confirm if this error is happening with the 5.0.0-rc.0?

**Comment by tipok** [comment]
Hi, unfortunately the error persists with 5.0.0-rc.0

**Comment by WoH** [comment]
Thanks for checking. Would you like to fix this via a PR?

**Comment by tipok** [comment]
Sure, already on it, there is an issue with IocContainerFactory and IocContainer, too. I would fix both in my PR, checking tests atm.
