### ISSUE TITLE
How to use @minDate | @maxDate jsDoc for models

### ISSUE THREAD

**Issue by neo7337** [lukeautry/tsoa#1364]
I have been using tsoa for a project and we want to use json schema validations for request body validations.
The documentation : https://tsoa-community.github.io/docs/annotations.html provides Date field annotations.
The current supported date annotations are
1. isDateTime
2. isDate
3. minDate
4. maxDate

I want to use minDate and maxDate to my schema to validate for the `current date` in the request body.

There is no supported example for the same.

I have tried the below

```
const isoDate = new Date().toISOString();

export class AddData {
/**
* @minDate {isoDate}
* /
inputDate: Date
}
```

But the tsoa spec-and-routes fail with the below error
`GenerateMetadataError: minDate parameter use date format ISO 8601 ex. 2017-05-14, 2017-05-14T05:18Z`

Can anyone provide a working example on how to provide dynamic current date value to the minDate and maxDate decorators

@isman-usoh if you could help as you wrote the feature, it would be great!

**Comment by jackey8616** [comment]
Jsdoc cannot put variables like this.

**Comment by neo7337** [comment]
documentation supports minDate and maxDate usage but no example.
does it only support string predefined value?

**Comment by WoH** [comment]
Yes, the variable interpolation is not a thing.
