### ISSUE TITLE
Setting response code when authenticationModule function fails

### ISSUE THREAD

**Issue by grug** [lukeautry/tsoa#1366]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

---

In `authentication.ts` (i.e. the file supplied as our `authenticationModule`), is it possible to return an HTTP status code other than 500 if the authentication fails?

For instance, if I have the following code for my `authenticationModule`:

```ts
function expressAuthentication(
  request: Request,
  securityName: string,
  roles?: string[]
): Promise<any> {
  if (securityName === 'jwt') {
    const token =
      request.body.token ||
      request.query.token ||
      request.headers['x-access-token']

    return new Promise((resolve, reject) => {
      if (!token) {
        reject(new Error('No token provided'));
      }

      verify(token, publicKey, function (err: any, decoded: any) {
        if (err) {
          reject(err);
        } else {
          if (roles) {
            for (let role of roles) {
              if (!decoded['realm_access'].roles.includes(role)) {
                reject(new Error('JWT does not contain required role.'));
              }
            }

            resolve(decoded);
          }
        }
      });
    });
  }

  return Promise.reject({});
}
```

Whenever the promise is rejected, tsoa just returns a `500 internal server error`.

Ideally if the token validation (or whatever auth you want to do) fails, it'd be nice to explicitly return a 401.

My questions are:

- Is this currently possible? 
  - If yes, how do we do this? I'm happy to submit a PR to the docs to demonstrate this.
  - If no, what are my alternative options?

**Comment by WoH** [comment]
Yes, you can reject the authentication with a custom error like an Authentication Error that you handle in an error handling Middleware and turn it into i.e. 401 Unauthorised

**Comment by grug** [comment]
Thanks for that @WoH - just out of curiosity, what is the shape of `AuthenticationError`? I can't see any reference to it in the `tsoa` codebase.

**Comment by WoH** [comment]
Whatever you need to distinguish it from an error that you want to turn into a 500.

`class AuthenticationError extends Error ...`

is the easy way

**Comment by WoH** [comment]
See: https://expressjs.com/en/guide/error-handling.html

**Comment by grug** [comment]
That's perfect - thanks so much. Great framework, by the way!
