### ISSUE TITLE
TSOA 2.x to 3.x  Upgrade Issue - breaking change

### ISSUE THREAD

**Issue by vhulugur** [lukeautry/tsoa#1367]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [ x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

When request payload is 
```json
{
"employeeId": "12345",
  "value": {
    "c-date": {
      "c-date": "2023-01-18"
    },
    "c-reason": {
      "label": "Patient Request - Keyboard",
      "id": "dischargeResonKeyboard"
    },
    "c-additional-notes": [
      {
        "text": "test text"
      }
    ]
  },
  "templateID": "xdghh"
}
```

is sent this is received as 
```json
{
"employeeId": "12345",
  "value": {
    "c-date": [{
      "c-date": "2023-01-18"
    }],
    "c-reason": [{
      "label": "Patient Request - Keyboard",
      "id": "dischargeResonKeyboard"
    }],
    "c-additional-notes": [
      {
        "text": "test text"
      }
    ]
  },
  "templateID": "xdghh"
}
```

Note all the objects are converted to Array[] instead it should retain them as object. 

## Context (Environment)

Version of the library: 3.3.0
Version of NodeJS: v18.12.1

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
I have no clue what this is supposed to tell be but here's the upgrade guide, maybe that helps. Please format the issue text correctly and we may have a chance to take a look.
https://tsoa-community.github.io/docs/upgrading.html#new-features

**Comment by vhulugur** [comment]
We are using npm. Note in the request  c-date is sent as object 
"c-date": {
      "c-date": "2023-01-18"
    }

but in the server side it's received as 
  "c-date": [{
      "c-date": "2023-01-18"
    }]

I will try my best to explain if you have any specific question.
