### ISSUE TITLE
Version 4.x.x to 5.x.x upgrade issue

### ISSUE THREAD

**Issue by azymnis** [lukeautry/tsoa#1368]
Suppose I have a package called `@internal/common` with a type definition that looks like this:

```
export enum UserType {
  Member = 'member',
  Admin = 'admin',
}
```

and a route file that looks like this

```
import { UserType } from '@internal/common';

type UserResponse = {
  userId: number;
  type: UserType;
}

@Route()
export class UserController extends Controller {
  @Get('user')
  public async getUser(): Promise<UserResponse> {
    return { userId: 123, type: UserType.Member };
  }
}
```

Then I get an error along these lines:

```
Generate routes error.
 GenerateMetadataError: No declarations found for referenced type UserType.
```

This used to work fine in tsoa 4.x.x

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Context (Environment)

Version of the library: 
Version of NodeJS:

**Comment by WoH** [comment]
Can you please share your tsconfig and tsoa config?

**Comment by azymnis** [comment]
I'll copy these here removing our private repo defs. If this is not enough info I can try to make a public repo with a minimal setup that reproduces the issue.

We are using yarn workspaces and our repo structure is like this:

```
/package.json
/tsconfig.json
/tsconfig.base.json
/packages/api/                                  <-- this uses tsoa
/packages/api/tsoa.json
/packages/api/tsconfig.json            <-- inherits from /tsconfig.base.json
/packages/common                         <-- contains the code that api depends on
/packages/common/package.json
/packages/common/tsconfig.json  <-- inherits from /tsconfig.base.json
```

This is what my `tsoa.json` looks like:

```
{
  "entryFile": "src/index.ts",
  "noImplicitAdditionalProperties": "throw-on-extras",
  "spec": {
    "basePath": "api",
    "outputDirectory": "../common/src/gen",
    "specVersion": 3,
    "securityDefinitions": {
      "cookieAuth": {
        "type": "apiKey",
        "name": "session",
        "in": "cookie"
      }
    }
  },
  "controllerPathGlobs": [
    "./src/controllers/**/*"
  ],
  "routes": {
    "routesDir": "src",
    "routesFileName": "generatedRoutes.ts",
    "authenticationModule": "./src/authentication.ts"
  }
}
```

And `tsconfig.json` looks like this:

```
{
  "extends": "../../tsconfig.base.json",
  "include": [
    "./src/**/*",
    "./src/**/*.json",
    "./scripts/**/*",
    "./__mocks__/**/*"
  ],
  "compilerOptions": {
    "outDir": "dist",
    "baseUrl": ".",
    "sourceMap": true,
  },
  "references": [],
}
```

with `tsconfig.base.json` looking like this:

```
{
  "compilerOptions": {
    "incremental": true,
    "target": "ES2019",
    "composite": true,
    "module": "commonjs",
    "lib": [
      "dom",
      "ESNext"
    ],
    "allowJs": true,
    "checkJs": false,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "strict": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "esModuleInterop": true,
    "useUnknownInCatchVariables": false,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "types": [
    "jest",
    "node"
  ]
}
```

I am using `yarn` version `3.2.4` with yarn workspaces. The root `tsconfig` is this:

```
{
  "compilerOptions": {
    "incremental": true,
    "target": "ES2019",
    "module": "commonjs",
    "lib": [
      "dom",
      "ESNext"
    ],
    "allowJs": true,
    "checkJs": false,
    "composite": true,
    "noEmit": false,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "strict": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "useUnknownInCatchVariables": false,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true,
    "types": [
      "jest",
      "node"
    ]
  },
  "include": [],
  "references": [
    {
      "path": "packages/api"
    },
    {
      "path": "packages/common"
    }
  ]
}
```

**Comment by WoH** [comment]
Does a `tsc --listFilesOnly` show the files containing the declarations as part of the output?

**Comment by azymnis** [comment]
> Does a `tsc --listFilesOnly` show the files containing the declarations as part of the output?

Yup it does. Doing: `yarn api run tsc --listFilesOnly | grep common`

Gives:

```
<ROOT>/packages/common/src/shared/types.ts
```

as part of the output (I have a package called `api` and one called `common`)

**Comment by WoH** [comment]
Hm, I am not aware of any changes that may have caused this. Maybe I can squeeze in time to reproduce this.

**Comment by azymnis** [comment]
I'll spend some time setting up a minimal repo that reproduces the issue

**Comment by WoH** [comment]
Can you see if copying it to tsoa config works?
https://github.com/lukeautry/tsoa/issues/868

**Comment by WoH** [comment]
Can you see if copying it to tsoa config works?
https://github.com/lukeautry/tsoa/issues/868

**Comment by azymnis** [comment]
@WoH unfortunately not.

Oh one thing that is maybe different with our setup: we are using yarn2 and packages

**Comment by azymnis** [comment]
@WoH when I get a little bit of time I will make a public repo that you can clone that repros the issue
