### ISSUE TITLE
Hiding unwanted schemas/types in the documentation 

### ISSUE THREAD

**Issue by AHerod** [lukeautry/tsoa#1376]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

Is there a way to hide some schemas in the generated documentation? I was thinking about something similar to the `@Hidden` decorator in the controllers. I've seen something similar implemented in [springdoc-openapi](https://springdoc.org/#how-can-i-ignore-some-field-of-model) - it hides the whole section but I would like to hide only the selected schemas.

**Comment by WoH** [comment]
We only crawl for declarations used via controllers and their methods. Hiding any models here would make your OpenAPI document incorrect.
