### ISSUE TITLE
Add additional types to swagger definition not referenced through a route

### ISSUE THREAD

**Issue by nixmike** [lukeautry/tsoa#1379]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Is there a way to ask for additional types to be included in the swagger file (for the user to benefit from autogeneration - imagine data sent via push notifications), w/o them being referenced in any route?

**Comment by WoH** [comment]
This is not currently possible, but maybe would be an interesting idea.
