### ISSUE TITLE
[Feature] @Crud()

### ISSUE THREAD

**Issue by conradkirschner** [lukeautry/tsoa#1380]
## Feature @Crud() Annotation

This framework works like charm together with typeorm. I could imagine a @ Crud() annotation would be helpful to be more faster when writing apis

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Possible Solution

Might could work similar to spring boot @ crud annotation. 
OR
similar to https://www.npmjs.com/package/@nestjsx/crud-typeorm

**Comment by jackey8616** [comment]
I've take a little bit look at `@Crud` decorator in `nestjsx/crud`:  

IMO, tsoa should focus on how we process OpenAPI spec, beyond this, make our user feel convenient.  
The usage of such decorator is kind of over design in tsoa, is more than convenient, it take too much works away from users which they should focus on their business logic but not tsoa.
