### ISSUE TITLE
GenerateMetadataError: Could not determine the keys on T

### ISSUE THREAD

**Issue by BottlecapDave** [lukeautry/tsoa#1384]
I am trying to upgrade to the latest tsoa and typescript. The specified code worked on previous versions, but is now reporting an error.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I expect a spec to be generated successfully. Either `key` should be the properties of IFoo or worse case a string.

```ts
import { Body, Post, Route } from 'tsoa';

interface IQueryWhere<T> {
    key: keyof T;
}

interface IQuery<T> {
    where?: IQueryWhere<T>[];
}
  
interface IFoo {
    name: string
}

interface IFooQuery
    extends IQuery<IFoo> {}

interface ISearchResponse<T> {
    items: T[];
}

@Route('/foo')
export class FooController {
  @Post('search')
  public async searchFoo(
    @Body() _query: IFooQuery
  ): Promise<ISearchResponse<IFoo>> {
    return { items: [] };
  }
}
```

## Current Behavior

The specified code snippet is producing the following error

```
This was caused by 'key: keyof T;'
There was a problem resolving type of 'IQueryWhere<IFoo>'.
There was a problem resolving type of 'IQuery<IFoo>'.
There was a problem resolving type of 'IFooQuery'.
Generate swagger error.
 GenerateMetadataError: Could not determine the keys on T
```

## Steps to Reproduce

1. Copy the specified code into a ts file
2. Run `tsoa spec` against the file

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: 18.14.0

- Confirm you were using yarn not npm: [ ]

## Detailed Description

N/A

## Breaking change?

N/A

**Comment by WoH** [comment]
Would you like to provide a PR that is able to handle type constructs like this?
