### ISSUE TITLE
Broken link on getting started page

### ISSUE THREAD

**Issue by toymachiner62** [lukeautry/tsoa#1385]
Broken link on [getting started](https://tsoa-community.github.io/docs/getting-started.html) page. 

![image](https://user-images.githubusercontent.com/485782/219492917-723cf37f-c691-4484-b574-901fff064323.png)

**Comment by WoH** [comment]
Should be linking to:

https://tsoa-community.github.io/reference/interfaces/_tsoa_cli.Config.html

Would you like to submit a PR at GitHub.com/tsoa-community/docs ?
