### ISSUE TITLE
tsoa generates route code that calls undefined promiseAny()

### ISSUE THREAD

**Issue by Craigfis** [lukeautry/tsoa#1388]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Generated routes.ts file should be compilable.

## Current Behavior

routes.ts contains this code:
```                request['user'] = await promiseAny.call(Promise, secMethodOrPromises);```
but promiseAny is not defined.

## Possible Solution

Should use Promise.any() instead?

## Steps to Reproduce

Create a controller method with:
  ```@Security('jwt')```
and   ``` @Request() request: express.Request<unknown>```

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: 18.13

- Confirm you were using yarn not npm: [x]

## Detailed Description

Building the generated code results in this error:
``` TS2552: Cannot find name 'promiseAny'. Did you mean 'Promise'?```

**Comment by Craigfis** [comment]
This happened when I was missing the 'authenticationModule' property in tsoa.json. Adding that resolved this issue. I would expect better error handling in this situation though.

**Comment by jackey8616** [comment]
@WoH 
I looked into the code [here](https://github.com/lukeautry/tsoa/blob/b1b8527/packages/cli/src/routeGeneration/templates/express.hbs#L9-L17)
I think the promiseAny import should not depends on authenticationModule existence.  

Maybe I can submit a PR move those statements outside authenticationModule examine if statement.
