### ISSUE TITLE
release new version to npm?

### ISSUE THREAD

**Issue by malbertSC** [lukeautry/tsoa#139]
Hey,

The current release on npm is broken with the most recent version of hapi, but https://github.com/lukeautry/tsoa/pull/115 fixes the problem.  Any chance of a release soon?  There's a PR out (https://github.com/lukeautry/tsoa/pull/135) that looks like it will make this easy.

Thanks!

**Comment by isman-usoh** [comment]
while waiting publish, use `npm i isman-usoh/tsoa.git#v1.2.5`

**Comment by isman-usoh** [comment]
while waiting, use `npm i lukeautry/tsoa#v1.2.3` or `npm i lukeautry/tsoa#npm`

**Comment by lukeautry** [comment]
@malbertSC Version 1.3 has been released. Sorry for the delay - we'll be automating this shortly.
