### ISSUE TITLE
Route with a suffix like ':download' doesn't work

### ISSUE THREAD

**Issue by Craigfis** [lukeautry/tsoa#1390]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
I should be able to define a route like:
```/products/:id:download```
where :id is a numeric resource id and ':download' is a literal part of the route.
(e.g. /products/45:download)

I have defined the controller method with:
```  @Get('{id}:download')```

## Current Behavior
tsoa generates swagger.json like:
```		"/prods/{id}{download}": {```
and routes.js like:
```        app.get('/prods/:id:download',```

At runtime it throws an error when trying to call the route indicating it is trying to parse ':download' as part of the id value.
id: { message: 'invalid float number', value: '583:download' } 

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: 18.13

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
> I should be able to define a route like:
/products/:id:download
where :id is a numeric resource id and ':download' is a literal part of the route.
(e.g. /products/45:download)

I don't agree, there's no way for express to tell if that `: download` is static or not.
We support both syntaxes by popular demand.
However, escaping should be possible.

**Comment by Craigfis** [comment]
I already have this implemented in an Express app. I'm trying to move that Express API over to using tsoa, but this is a blocker for me.
In Express this is written as:
```router.get('/:id([0-9]+)[:]download')```

Putting the square brackets around the colon like here doesn't work for tsoa though.

**Comment by jackey8616** [comment]
@Craigfis 
You can ref [this file](https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/utils/pathUtils.ts) to see are there anyway to match tsoa's path normalization method.  

IMO, your express solution `'/:id([0-9]+)[:]download` is kind of hacky, which tsoa will not consider support this usage.

**Comment by WoH** [comment]
Afaik `::download` is what you can do in express, you should be able to escape tsoa the same way. If not I'd be open for a PR, similarly for or `:{download}` I think.
This way, you can lift the validation logic into the types. I.e. (public download: 'download') as an arg.
