### ISSUE TITLE
Deactivate Swagger-Petstore under index.html

### ISSUE THREAD

**Issue by JoinerDev** [lukeautry/tsoa#1392]
Hey!

I'm new to TSOA. I'm currently using TSOA to generate an API, but I've noticed that i can access an example page under /swagger/index.html
Is there a way to deactivate this example "PetStore" Website?

Thanks in advance!

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Index.html should either throw a 404 or lead back to /swagger

## Current Behavior

Example Website shows under "index.html"

## Steps to Reproduce

1. Generate API via TSOA
2. Open /swagger/index.html    (for most people it'll more likely be /docs instead of /swagger)

**Comment by WoH** [comment]
This is not related to tsoa ;)
