### ISSUE TITLE
Add better support for Deno in generated routes

### ISSUE THREAD

**Issue by digital88** [lukeautry/tsoa#1393]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

When executing `generateRoutes()` function to build routes file, the generated controller import path are not prefixed with `.ts` extension. This breaks using this generated file in Deno, because Deno imports must end with `.ts` extension. Instead of manually fixing generated file, an option should be added, similar to existing option `esm`.

## Current Behavior

Generated routes file doesn't work in Deno out of the box. You have to manually add `.ts` extension to the end of controllers import path.

## Possible Solution

Add option similar to `esm` to make possible generation of controller imports with `ts` suffix in routes file.

## Steps to Reproduce

Run `generateRoutes()` function to generate routes file, then try to import it and run with Deno.

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: Deno
```
deno 1.31.1 (release, x86_64-unknown-linux-gnu)
v8 11.0.226.13
typescript 4.9.4
```

- Confirm you were using yarn not npm: [ ]
Neither yarn nor npm was used.

## Detailed Description

 
Here is code where controller import generation takes place:

https://github.com/lukeautry/tsoa/blob/70aefa027c3e30f5a060b5ddc456f0e6d25b80fe/packages/cli/src/routeGeneration/routeGenerator.ts#L140
```ts
  protected getRelativeImportPath(fileLocation: string) {
    fileLocation = fileLocation.replace(/.ts$/, ''); // no ts extension in import
    return `./${path.relative(this.options.routesDir, fileLocation).replace(/\\/g, '/')}${this.options.esm ? '.js' : ''}`;
  }
```
For some reason in this code the `ts` extension is explicitly removed. I propose adding an optional parameter (default value is `false`) to `options` object. When this parameter is `true`, `ts` suffix should be added to the end of the controller import, like currently done with `esm` option.

## Breaking change?

Not breaking.

**Comment by WoH** [comment]
Hi, we offer 2 options to deal with that. Rolling your own template and using your own route generator as extension points.

**Comment by digital88** [comment]
> Hi, we offer 2 options (extension points) to deal with that. Rolling your own template or using your own route generator.

Ok, thank you, I will try own generator.

Can you please tell me, why is `.ts` extension explicitly being removed in `getRelativeImportPath()`? I want to better understand the reason for removal and code in general.

**Comment by WoH** [comment]
https://github.com/lukeautry/tsoa/pull/755

**Comment by WoH** [comment]
This is how TypeScript has always historically done imports, hasn't it?
This is dependent on module (resolution), but '.ts' by itself doesn't work using node/commonjs.
You can trace it down to 2016 if you want to:
https://github.com/devnev/tsoa/commit/f44b84c809b80767425a078734e083be0f0dee81

**Comment by digital88** [comment]
This worked for me (didn't bother to check for `.js` at the end of route):
```ts
class CustomRouterGenerator extends DefaultRouteGenerator {
  protected getRelativeImportPath(fileLocation: string) {
    return super.getRelativeImportPath(fileLocation) + ".ts";
  }
}

const routeOptions: ExtendedRoutesConfig = {
    ...
    routeGenerator: CustomRouterGenerator,
};

await generateRoutes(routeOptions);
```
