### ISSUE TITLE
Question: how to return text/plain response

### ISSUE THREAD

**Issue by thobson** [lukeautry/tsoa#1394]
Is there a better way to return a plain text response vs a json string?

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```
@Get("test")
public async sendText(@Res() ok: TsoaResponse<200, string>): Promise<string> {
  return ok(200, "hello world")
}
```

I would like to send a response like

```
Content-Type: text/plain
hello world
```

## Current Behavior

```
@Get("test")
public async sendText(@Res() response: TsoaResponse<200, string>): Promise<string> {
  return response(200, "hello world")
}
```

and

```
@Get("test")
public async sendText(): Promise<string> {
 return "hello world"
}
```

Both send:

```
Content-Type: application/json; charset=utf-8
"hello world"
```

I also tried:

```
@Get("test")
public async sendText(@Res() response: TsoaResponse<200, string>): Promise<string> {
  return response(200, "hello world", { "Content-Type": "text/plain" })
}
```

which sends

```
Content-Type: text/plain; charset=utf-8
"hello world" (Note the quotes)
```

## Workaround

I've worked around this using;

```
@Get("test")
@Produces("text/plain")
public async sendText(@Request() req: express.Request): Promise<string> {
  req.res?.header("Content-Type", "text/plain; charset=utf-8")
  req.res?.send("hello world")
  return ""
}
```

It feels a bit hacky, I don't like returning the empty string. 

Is there a way of specifying that the TsoaResponse content type is something other than JSON?

Thanks!

**Comment by lukelindsey** [comment]
I'm using the same workaround as @thobson to expose metrics endpoint using `prom-client`. For example,

```
req.res?.set(`Content-Type`, client.register.contentType).send(await client.register.metrics());
return "";
```

I'm glad there's at least a workaround, but this definitely feels hacky.

**Comment by hpx7** [comment]
You should just be able to use `@Produces("text/plain")`

**Comment by lukelindsey** [comment]
@hpx7 that doesn't work. Without using res.send I wasn't able to get it to remove the quotes from the response as mentioned [here](https://github.com/lukeautry/tsoa/issues/1394#issue-1611399979).
 
 Tried this with and without `setHeader`
 
 ```
@Route("metrics")
export class MetricsController extends Controller {
  @Get()
  @Produces("text/plain")
  public async metrics(): Promise<string> {
    this.setHeader(`Content-Type`, client.register.contentType);
    return await client.register.metrics();
  }
}
 ```

**Comment by hpx7** [comment]
Ah I see, yeah you're right. It sets the right OpenAPI response type but it doesn't actually set the right header at runtime

**Comment by keslerm** [comment]
This is still an issue and definitely something that changed at some point since 4.1.1

**Comment by keslerm** [comment]
There's definitely something strange with how plain text gets encoded down.

Wrapping it as a ReadableStream also seems to end up with the expected result:

```
  public test1(): Promise<unknown> {
        return Readable.from(Buffer.from("some raw string here"));
  }
```
