### ISSUE TITLE
Question: Why some aliases are used and others not?

### ISSUE THREAD

**Issue by mathiasmah** [lukeautry/tsoa#1397]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

I don't fully understand how I can use aliasing properly with tsoa. 
I found multiple issues, where similar topics are discussed, but I didn't find exact answers to the questions I have. 

If I have the following types:
```
  export type StringAlias = string;
  export type MainObject = { a: string; b: string };
  export type PickObject = Pick<Object1, 'a'>;
  export type ReturnType = {
    string: StringAlias;
    object: PickObject;
  };
```
Tsoa generates this:
![grafik](https://user-images.githubusercontent.com/15261743/223670149-1dd0b612-bd09-45c8-bc84-bf57744fb8c0.png)

The type `StringAlias` is used to descripe the type `ReturnType`, but the type `PickObject` is not. 

Could you explain the reason for this? 
Is it technical or is it a design decision? 
Is there a way on how I can achieve this behavior also for `PickObject`?

**Comment by WoH** [comment]
All reference(d) types (interfaces, type aliases, enums, or any instantiations for generic types) create an OpenAPI component.

**Comment by timlopezarcurve** [comment]
Is there any way to get rid of this behaviour?? For example, we've got an object such as 

```
type Response = Pick<Object, "a", "b", "c"> 
```
it generates a type key:
"Pick_Object.-or-a-or-b-or-c." 

This breaks some generators -- any advice? Ideally I would prefer just the Response type (without the intermediaries)
