### ISSUE TITLE
How can I prevent TSOA to send ignored properties back to the client?

### ISSUE THREAD

**Issue by nimloth05** [lukeautry/tsoa#1400]
I have several cases where TSOA sends back ignored properties but should not do so: 

- Back refs inside a ORM model (parent child relationships)
- Secret data, that is needed for logic but should not be sent back to the client (e.g. password in a user object)

The fields are ignored via JS-Doc ignore and they don't appear inside the spec. But if the data is present in the response object, TSOA happily sends them back to the client.

So my question is simple: Hoy can I tell TSOA to remove properties that are ignored?

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X ] support request

- I confirm that I
  - [XXX ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Context (Environment)

- expressjs
- body-parser

**Comment by WoH** [comment]
Don't return them from the controller method.
Tsoa isn't really involved here.

**Comment by nimloth05** [comment]
@WoH Currently I have to "clean" the object before sending them back by hand. This is error proune, tedious and redundant. Even though, the information which field to ignore is already present. It's also counter intuitive since 'ignore' means ignore. 
 If Tsoa is not able to remove ignored fields from sending them back - ok. For me this looks like a missing feature: I can tell Tsoa to remove fields from incoming message Why not for outgoing?.). What extension mechanism does Tsoa provide to manipulate the objects before sending them back? Of course I would need access to the meta model. (Accessing the JSON method via body parser is not a problem, but the meta model is missing at this point)

**Comment by ealib** [comment]
@nimloth05 However, a good practice is to separate, in the design phase, the objects that arrive from the lower layers (ORM) from those that will travel on the wire (DTOs).

I, for example, often use [class-transformer](https://github.com/typestack/class-transformer) for this purpose, so as to confine the errors to a single piece of code, i.e. the decorations that then drive the [transformation](https://github.com/typestack/class-transformer/blob/develop/docs/pages/02-basic-usage.md) of the object that came out of the ORM's logical layer into the plain DTO object that TSOA will send as a response.

What you are looking for is likely `@Exclude`.
