### ISSUE TITLE
Type Alias override Description

### ISSUE THREAD

**Issue by ISaneI** [lukeautry/tsoa#1402]
When using a type alias, is there any way to override the Description, for example inside an interface?

### Example type alias
```ts
/**
 * DateTime Format according to ISO 8601
 * @pattern YYYY-MM-DDTHH:mm:ss.sssZ
 * @example "2019-08-24T14:15:22Z"
 */
export type Datetime = string;

```

### Example interface
```ts
export interface Test {
/**
 * Custom Description
 */
  created?: Datetime;
}
```

It would be great to override or even extend the `created?: Datetime;` Description. Maybe I'm missing something, but I found no solution so far… . It's always generating the Datetime JSDoc Description.

![image](https://user-images.githubusercontent.com/25959334/225025227-b2e0a90a-63e6-40e8-8c7a-310765c35d54.png)
 

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Context (Environment)

Version of the library: ^5.1.1
Version of NodeJS: 18.15.0

- Confirm you were using yarn not npm: [x]

**Comment by jackey8616** [comment]
[OpenAPI $ref doc](https://swagger.io/docs/specification/using-ref/).  
<img width="780" alt="image" src="https://user-images.githubusercontent.com/12930377/226087093-9a771c8b-43fe-477d-b792-433c601bbe40.png">

In OpenAPI3.0 we can use `allOf` to override fields inside $ref.  
For example, current spec:  

```json
{
  ...
  "schemas": {
    ...
    "DateTime": {
      "type": "string",
      "example": "2019-08-24T14:15:22Z",
      "description": "DateTime Format according to ISO 8601",
      "pattern": "YYYY-MM-DDTHH:mm:ss.sssZ"
    },
    "Test": {
      "properties": {
        "dt": {
          "$ref": "#/components/schemas/DateTime",
          "description": "Custom Description"
        }
      },
      "type": "object",
      "additionalProperties": false
    }
    ...
  }
  ...
}
```

After wrap with allOf:  

```json
{
  "schemas": {
    "DateTime": {
      "type": "string",
      "example": "2019-08-24T14:15:22Z",
      "description": "DateTime Format according to ISO 8601",
      "pattern": "YYYY-MM-DDTHH:mm:ss.sssZ"
    },
    "Test": {
      "properties": {
        "dt": {
          "allOf": [
            {
              "$ref": "#/components/schemas/DateTime"
            },
            {
              "description": "Custom Description"
            }
          ]
        }
      },
      "type": "object",
      "additionalProperties": false
    }
  }
}
```

**Comment by WoH** [comment]
We already put the description next to the ref, but SwaggerUI (following the spec) ignores it.
Jackey explained the details
