### ISSUE TITLE
Feature Req: A decorator describes ValidateErrorResponse

### ISSUE THREAD

**Issue by jackey8616** [lukeautry/tsoa#1403]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Detailed Description
Since that tsoa providing validate and throws ValidateError,  
I think we should also provide something like `ValidateErrorResponse` decorator to generate swagger spec.  

```ts
export function ValidateErrorResponse(
  statusCode?: HttpStatusCodeLiteral | HttpStatusCodeStringLiteral | OtherValidOpenApiHttpStatusCode,
  description?: string,
) {
  return () => Response<{
    [fieldName: string]: {
      message: string;
      value?: any;
    },
  }>(
    statusCode || 400,
    description || 'Error: Bad Request',
    {
      'data.fieldA': {
        message: '\'fieldA\' is required',
      },
    },
  );
};
```

Willing to submit such PR if community is ok with this.  
TBH, it's a little bit annoying for me to write same code in every controller.  

## Breaking change?
Nop.

**Comment by WoH** [comment]
I'm not sure why this would be at the controller level tbh. Isn't this more of a global thing usually?

For controllers, what does this provide that `@Response` does not?

**Comment by jackey8616** [comment]
Yes, I think your are right, we can find somewhere globally to generate spec.  
If developer want to override the default status code & description, they can use `@Response` decorator with `ValidateErrorType` at controller or method level.
