### ISSUE TITLE
Route generation at runtime

### ISSUE THREAD

**Issue by pdeveltere** [lukeautry/tsoa#1404]
Why is this library not doing the route generation at runtime? when the application starts, tsoa could check all the decorators at runtime and build the routes. there is no need to generate them beforehand?

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Make a generic RegisterRoutes function which iterates over all the metadata and generates the routes at runtime.

## Current Behavior

We need to build the routes with the cli beforehand.

**Comment by WoH** [comment]
Simpifies tooling and integration significantly.
If you wanna look for a project that does the runtime version, I can recommend fastify w/ typebox.
