### ISSUE TITLE
Authentication Scope - Accept non-string types

### ISSUE THREAD

**Issue by Cilooth** [lukeautry/tsoa#1406]
- **I'm submitting a ...**

  - [ ] bug report
  - [*] feature request
  - [ ] support request

- I confirm that I
  - [*] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The expressAuthentication function of the Security middleware should accept generic types (such as enums) instead of hard coded strings

This is currently not working:
```ts
export async function expressAuthentication(req: Request, securityName: string, scopes?: ScopeType[]) {
//...
}
```

## Current Behavior

This is the only working way to use this function without Type errors:
```ts
export async function expressAuthentication(req: Request, securityName: string, scopes?: string[]) {
//...
}
```

## Possible Solution

I have not yet started to work on a PR for this issue

## Detailed Description

Accept generic types for the scopes param of the authentication middleware instead of hardcoded strings.

**Comment by WoH** [comment]
We can't infer the actual `const` string literals from the tsoa config so I'm not sure how we would change the signature to something but all the possible ones. If you wanna submit a PR I'd be happy to take a look
