### ISSUE TITLE
How to represent Records

### ISSUE THREAD

**Issue by thobson** [lukeautry/tsoa#1407]
I have a model that looks something like this 

```
type Tenancy = string

enum Role {
  User, 
  Admin
}

type User {
  id: string
  roles: Record<Tenancy, Role[]>
}
```

The generated swagger schema looks like this:

```
{
  "Record_TenancySlug.Role-Array_": {
    "properties": {},
    "type": "object",
    "description": "Construct a type with a set of properties K of type T"
  },
  "User": {
    "roles": {
      "$ref": "#/components/schemas/Record_TenancySlug.Role-Array_"
    }
  }
}
```

As you can see the typing is lost and all we can deduce is that the roles property is an object.

Is there someway to generate stronger typings?

Thanks

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

**Comment by WoH** [comment]
Seems like a bug, happy to review PRs to fix this.
