### ISSUE TITLE
Setting Integer as the default number type

### ISSUE THREAD

**Issue by PetrKubes97** [lukeautry/tsoa#1408]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Detailed Description
Hi, is there a way to set integer as the default number type? 90% of the numbers in my app are integers, so I'm forced to do a lot of trickery like this. 

```
type IntOverrideForTsoa = {
    /** @isInt */ id: number,
    /** @isInt */ learning: number,
    /** @isInt */ learned: number,
    /** @isInt */ unseenWords: number,
}
const result: (typeof collection & IntOverrideForTsoa) = {
    ...collection,
    learning: learning.length,
    learned: learned.length,
    unseen: unseenWords.length
}
return result
```

**Comment by WoH** [comment]
Yeah, you should be able to group that under  a type alias, I'm pasting something similar that we use:
```ts
/**
 * Stringified UUIDv4.
 * See [RFC 4112](https://tools.ietf.org/html/rfc4122)
 * @pattern [0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}
 * @tsoaModel
 */
export type UUID = string;
```

**Comment by PetrKubes97** [comment]
Hm, not sure how to make it work. This still generates a double:
```
/**
 * @isInt
 * */
type Int = number;
const test: Int = 1
return test
```

**Comment by PetrKubes97** [comment]
Only way I can make it work is by putting `Promise<Int>` directly in the controller method type. According to my IDE, ts simplifies the type back to `number`. :(
<img width="736" alt="Screenshot 2023-03-22 at 15 33 43" src="https://user-images.githubusercontent.com/4227953/226984524-8072807c-0dba-4d29-a1b9-0dd32ed14abe.png">

**Comment by PetrKubes97** [comment]
Only way I can make it work is by putting `Promise<Int>` directly in the controller's method type. Also, according to my IDE, TS simplifies the type to `number`.

<img width="405" alt="Screenshot 2023-03-22 at 18 15 31" src="https://user-images.githubusercontent.com/4227953/226985260-204cd664-16eb-4e42-9a1b-08125d8b8d95.png">

**Comment by WoH** [comment]
The inline hints are based on the type checker that may simplify, but we visit that and produce a reused ref in the OpenAPI spec that'll work.

**Comment by PetrKubes97** [comment]
I've created a minimal example that produces the unexpected type:
https://github.com/PetrKubes97/tsoa-maybe-bug
Controller: https://github.com/PetrKubes97/tsoa-maybe-bug/blob/main/src/someController.ts
Generated schema: https://github.com/PetrKubes97/tsoa-maybe-bug/blob/main/build/swagger.json#L34

**Comment by WoH** [comment]
Thanks for the repro, I understand what the confusion is now. It should work when you set Int as the return type.
Otherwise we have to rely on the type checked in order to determine the inferred return type and TS seems to check that away so to say. (Pretty much similar to what happened in your editor)

**Comment by PetrKubes97** [comment]
Could I do a PR with the addition of`defaultNumberFormat: integer | double` to tsoa config. Seems that it would be only changing this line and some tests, right? 
https://github.com/lukeautry/tsoa/blob/ec9c3a4215887a7c7f3aabaa2f10a7f33fd89b14/packages/cli/src/metadataGeneration/typeResolver.ts#L466

**Comment by WoH** [comment]
I think the fix you're looking for is adding `Promise<Int>` as the return type of the function

**Comment by WoH** [comment]
> Could I do a PR with the addition of`defaultNumberFormat: integer | double` to tsoa config. Seems that it would be only changing this line and some tests, right?
> 
> https://github.com/lukeautry/tsoa/blob/ec9c3a4215887a7c7f3aabaa2f10a7f33fd89b14/packages/cli/src/metadataGeneration/typeResolver.ts#L466

I think this is best left to a custom template or route generator.

**Comment by PetrKubes97** [comment]
Hi, any updates on this? Do you think having a default number type config would be bad?
