### ISSUE TITLE
Queries with same parameters throw an error

### ISSUE THREAD

**Issue by SO-Eng** [lukeautry/tsoa#1410]
Hi,

first I want to say, really a great library and such a big help with swagger documentation etc.!
Now lets come to where I struggle and sadly that's the point where I can't go further with tsoa.

As I saw, you made a great step forward with [PR#1309](https://github.com/lukeautry/tsoa/pull/1309) so now it is possible to work well with many different parameters!
Okay, so far so good. What I don't get to work, a query with many same parameters, like:
?id=1&id=2&id=3....

If we take a look to the query standard, this should be implemented.

But maybe I just don't doing it right?
I would appreciate any help regarding this!

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Expected behavior to a query like:
?id=1&id=2&id=3.... => id = ["1", "2", "3", ...]
The result should end in an arry.

With express route is does work

```
app.get("/user", (req, res) => {
    const { id } = req.query
    console.log("ID is "+ id) 
});
```
// GET www.example.com/user?id=1&id=2&id=3
// ID is ["1", "2", "3"]

// GET www.example.com/user?id=12345
// ID is 12345

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: 16.13.2

**Comment by WoH** [comment]
> a look to the query standard

Which one?

> But maybe I just don't doing it right?

This is up to the underlying framework, if you target express, it's up to how you configured it.

**Comment by SO-Eng** [comment]
> Which one?

Of course, there is no global standard for queries. So the question is not incorrect.
But definitely it is possible and a usecase that is not so rare. I wouldn't say a common usecase, but a usecase.

> This is up to the underlying framework, if you target express, it's up to how you configured it.

I do target express, but when I work with 'res' and 'req' I can't use the typing of them, because they come from a 'foreign' library.
And there are allready issues opened here, to please allow Typings from 'foreign' libraries.
So tsoa won't do the routing, it throws errors.

I paste here my last try yesterday evening where i stucked:

```
@Route("user")
export class UserController {
  @Get()
  public async getUser(@Queries() id: { [x: string]: string } ) {

     return { status: id };
  }
}
```

// GET example.com/user?id=1&id=2&id=3 // Error
// GET example.com/user?id1=id1&id2=2&id3=3 // { id1: '1', id2: '2', id3: '3' }

**Comment by WoH** [comment]
If you take a look at the code tsoa generates in your routes.ts, we just pull it off the req. Which means if your query parser does what you want, tsoa does what you want.

**Comment by SO-Eng** [comment]
@WoH thanks!
Then I was complete on the wrong path!
That helped me a lot an made my day.

Thank you
