### ISSUE TITLE
Controller bug with @Body() union interface

### ISSUE THREAD

**Issue by EminSenol** [lukeautry/tsoa#1416]
The @Body() decorator is modifying the type of a single-element array when a union interface is being used.

### Interfaces
```ts
export interface RequestBody {
    content: JSONObject;
}

/**
 * A Union type for any basic type a JSON object can contain
 */
export type JSONTypes = string | number | boolean | null | JSONObject | Array<JSONTypes>;

/**
 * The definition of JSON safe object
 */
export interface JSONObject {
    [key: string]: JSONTypes;
}
```
### Controller 
```ts
import { Body, Controller, Post, Request, Route, Security, Tags } from "tsoa";
import ExampleService from "./Example.service";
import * as Response from "../../Interfaces/Responses/Response";
import { RequestBody } from "./ExampleRequests";

/** ROOT/example */
@Route("/")
export class ExampleController extends Controller {
    /**
     * Example route
     * @param test
     * @returns
     */
    @Tags("TestTag")
    @Post("run")
    @Security("jwt", ["exampleRight"])
    public async start(
        @Body() requestBody: RequestBody,
        @Request() req: Express.Request
    ): Promise<Response.ResponseBody> {
        console.log("====================================");
        console.log(requestBody);
        console.log("====================================");
        this.setStatus(Response.Statuses.SAVE);
        await ExampleService.exampleFunction();

        return {};
    }
}
```
### Post request payload

```json
{
    "content": {
        "simpleArray": [
            "1"
        ],
        "multiArray": [
            "1",
            "2"
        ]
    }
}
```
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

While logging the request body in the controller, our expectation is that the single-element array will remain unaltered.

```ts
{ content: { simpleArray: [ '1' ], multiArray: [ '1', '2' ] } }
```

## Current Behavior

When logging the request body in the controller, it can be observed that the single-element array has been modified.

```ts
{ content: { simpleArray: 1, multiArray: [ '1', '2' ] } }
```

## Possible Solution

Although any type can be used instead of JSONObject, it is not preferable. This is because using JSONObject improves the code's validation, readability, and understandability.

```ts
export interface JSONObject {
    [key: string]: any;
}
```

Also, apart from that, I would greatly appreciate any helpful solution suggestions you may have.

## Context (Environment)

Version of the library: 4.1.2
Version of NodeJS: 16.13.1

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
Unfortunately the order an coercion rules are not intuitive here. When validating, tsoa validates left to right applying coercion rules are we go. Therefore, ` [ '1' ]` can be coerced (because it is only one array element ) to 1 when validating against the number schema.
