### ISSUE TITLE
Set verbatimModuleSyntax to true

### ISSUE THREAD

**Issue by freund17** [lukeautry/tsoa#1418]
Pretty much #1044, but for the newer, slightly stricter flag.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
// routes.ts
import type { FieldErrors, TsoaRoute, HttpStatusCodeLiteral, TsoaResponse } from '@tsoa/runtime';
import { Controller, ValidationService, ValidateError, fetchMiddlewares } from '@tsoa/runtime';
```

## Current Behavior

```ts
// routes.ts
import { Controller, ValidationService, FieldErrors, ValidateError, TsoaRoute, HttpStatusCodeLiteral, TsoaResponse, fetchMiddlewares } from '@tsoa/runtime';
```

## Possible Solution

Changing this line:

https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/routeGeneration/templates/express.hbs#L4
https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/routeGeneration/templates/hapi.hbs#L4
https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/routeGeneration/templates/koa.hbs#L5

## Detailed Description

This stricter version requries *all* types to be explicitly imported as such. With `importsNotUsedAsValues` you could include type imports with your "normal" imports, but with `verbatimModuleSyntax`, this is no longer allowed.

For example:

```ts
// not allowed by neither `importsNotUsedAsValues` nor `verbatimModuleSyntax`
import { MyInterface } from 'whatever';
```

```ts
// fine with `importsNotUsedAsValues`, not allowed by `verbatimModuleSyntax`
import { someFunction, MyInterface } from 'whatever';
```

```ts
// fine with both
import { someFunction, type MyInterface } from 'whatever';
```

```ts
// fine with both
import { someFunction } from 'whatever';
import type { MyInterface } from 'whatever';
```

So just like #1044 before, this will require a small tweak to the handlebars template(s).

## Breaking change?

No

**Comment by WoH** [comment]
Inlining should also be fine, I'd prefer that style, but I'm not sure what TS version that requires.

**Comment by WoH** [comment]
VerbatimModuleSyntax requires more changes though afaik, so I'm not sure if it really makes a lot of sense rn

**Comment by freund17** [comment]
I just tested it using `routes.middlewareTemplate` in my `tsoa.json` and it seems to be all thats required for my application to compile. 🤷  (I'm using express.)

**Comment by WoH** [comment]
You're using ESM in your project then?

**Comment by freund17** [comment]
Yes, I am.

For completeness:

`package.json` with `"type": "module"`

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true,
    "isolatedModules": true,
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "noImplicitReturns": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "outDir": "dist",
    "sourceMap": true,
    "strict": true,
    "target": "ESNext",
    "useUnknownInCatchVariables": true,
    "verbatimModuleSyntax": true
  },
  "include": ["src"]
}
```

`tsoa.json`:

```json
{
  "entryFile": "src/app.ts",
  "noImplicitAdditionalProperties": "silently-remove-extras",
  "controllerPathGlobs": ["src/controllers/**/*Controller.ts"],
  "spec": {
    "outputDirectory": "dist",
    "specVersion": 3,
    "specFileBaseName": "openapi",
    "yaml": true
  },
  "routes": {
    "esm": true,
    "iocModule": "src/ioc",
    "middlewareTemplate": "./tsoa-route.hbs",
    "routesDir": "src/__generated__"
  }
}
```

As you can see, I'm using the `middlewareTemplate` with a custom version of the `express.hbs` template with the suggested fix applied. This seems to be working great.

So I thought to open a ticket in case anybody else has the same issue.

**Comment by alexng353** [comment]
I'm still seeing this issue in version 6.4.0. 

```bash
$ tsc --noEmit
build/routes.ts:4:10 - error TS1484: 'TsoaRoute' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.

4 import { TsoaRoute, fetchMiddlewares, ExpressTemplateService } from '@tsoa/runtime';
           ~~~~~~~~~


Found 1 error in build/routes.ts:4
```

**Comment by christiango** [comment]
I've made a PR #1676 to address this.
