### ISSUE TITLE
Documents

### ISSUE THREAD

**Issue by isman-usoh** [lukeautry/tsoa#142]
Hello, contributors, 
let's create a better document

Topic
- [ ] Introduction
- [ ] Getting stater
- [ ] tsoa.json
- [ ] tsoa CLI
- [ ] Controller
- [ ] Model and validation
- [ ] Authentication
- [ ] IoC
- [ ] Middleware
- [ ] Contributor Guide

Or would like to add another topic,

**Comment by AmazingTurtle** [comment]
What is the issue here? Please clarify.
