### ISSUE TITLE
express authentication middleware sends [object Object] in response body when Promise rejection occurs

### ISSUE THREAD

**Issue by rlubaschewski** [lukeautry/tsoa#1423]
So i am basically just trying to set the response body in my express authentication middleware when authentication fails.
I am stuck with a 401 response, but [object Object] in the body like this:

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>[object Object]</pre>
</body>
</html>
```

My tsoa.json:

```json
{
    "entryFile": "src/app.ts",
    "noImplicitAdditionalProperties": "throw-on-extras",
    "controllerPathGlobs": [
        "src/**/*Controller.ts"
    ],
    "spec": {
        "outputDirectory": "build",
        "specVersion": 3
    },
    "routes": {
        "routesDir": "build",
        "authenticationModule": "./src/authentication.ts"
    }
}
```

In my `authentication.ts` file, this behavior is caused by:

```ts
return Promise.reject({ status: 401 });
```

It is possible to set the status code of the response, but I can't seem to set the response body.
Is this expected behavior? Throwing an error will change the response body, but also print the whole call stack in the response.
How can I set the response body with Promise rejection?

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The response body could be set like this:

```ts
return Promise.reject({ status: 401, body: {  message: "..."  } });
```

or this

```ts
return Promise.reject({ status: 401, message: "..." });
```

## Current Behavior

```ts
return Promise.reject({});
```
will result in `[object Object]` being returned in the response body.

## Steps to Reproduce

1. setup an authentication middleware with express as documented [here](https://tsoa-community.github.io/docs/authentication.html)
2. trigger a Promise Rejection in the authentication process
3. `return Promise.reject({})`ts (like in the docs)
4. see response body

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: v16.17.0

- Confirm you were using yarn not npm: [x]

**Comment by verata-veritatis** [comment]
Having same issue
