### ISSUE TITLE
Question: how to specify format of a parameter?

### ISSUE THREAD

**Issue by ristiisa** [lukeautry/tsoa#1424]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

How to specify the format of the parameter with tsoa? For example if we have following declaration that specifies that the format of the parameter userId of type string is uuid.

```
 /:userId
   get:
     description: stuff
     tags:
      - User
     parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: string
          format: uuid
     responses:
       200:
         description: stuff
```

**Comment by ireoostacchini** [comment]
Hello, is it possible to reopen this item? I'm having the exact same problem - i.e. the 'format' annotation doesn't work for uuid

<img width="1096" alt="format uuid" src="https://github.com/lukeautry/tsoa/assets/5371242/20cf7f01-5535-4e60-8dde-c04665c40936">

**Comment by ristiisa** [comment]
wow that is some very brutal auto close
