### ISSUE TITLE
Refresh JWT in expressAuthentication

### ISSUE THREAD

**Issue by devskar** [lukeautry/tsoa#1428]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I would like to refresh the jwt automatically in the `expressAuthentication`. Before using tsoa I just had my middleware which rejected all requests without a cookie or invalid jwt and refreshed the JWT when it worked. I feel like that is a pretty common use case, so I am kind of confused how this would be done using tsoa since there is no access to the `response` in the `expressAuthentication`. Is there any possible solution or workaround. Or why is the response not available in the authentication?

## Context (Environment)

Version of the library: ^5.1.1
Version of NodeJS: PS C:\Users\Oskar\programming\spots\api> node -v
v18.12.1

**Comment by emoyly** [comment]
I truly don't know whether this is a good solution, but this is how I access it.

**1.** I create a "request context" using AsyncLocalStorage.
```ts
import { AsyncLocalStorage } from 'async_hooks'

export interface RequestContext {
    request: Express.Request,
    response: Express.Response
}

export const requestContext = new AsyncLocalStorage<RequestContext>()
```
**2.** I open a new context in each request with Express middleware
```ts
// ⬆️ Various middleware like body-parser

app.use((req, res, next) => {
    requestContext.run({
        'request': req,
        'response': res
    }, () => next())
})

// ⬇️ More middleware or start Express app
```
**3.** I have a function which returns the current request or response object anywhere in the app
```ts
/**
 * Get Express Response object from request context
 */
export function getRequest(): FullRequest {
    const store = requestContext.getStore()

    if (!store) throw new Error('Could not get request context')

    return store.request
}

/**
 * Get Express Response object from request context
 */
export function getResponse(): FullResponse {
    const store = requestContext.getStore()

    if (!store) throw new Error('Could not get request context')

    return store.response
}
```

This works really well (for me), but I'm sure there's a better way. This is inspired by how [Mikro-ORM deals with transations](https://mikro-orm.io/docs/installation#request-context), and I couldn't figure out a better way, so I just did the same.

**Comment by WoH** [comment]
You can still run that same middleware by registering it before you call RegisterRoutes also
