### ISSUE TITLE
Returning Error 500 Instead of 401 with security guarded routes

### ISSUE THREAD

**Issue by salvobee** [lukeautry/tsoa#1431]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
I'm developing an authentication module for an Express API using TSOA. 
I have implemented JWT token authentication using the expressAuthentication method as provided in the [documentation](https://tsoa-community.github.io/docs/authentication.html).

The problem I encountered is that when an unauthenticated user tries to access a protected route, instead of receiving a response with a 401 status code (Unauthorized), the API returns a 500 error (Internal Server Error).

```ts
// tsoa.json

"spec": {
    "securityDefinitions": {
      "jwt": {
        "type": "oauth2",
        "flow": "accessCode",
        "scopes": {
          "ads:store": "create ads"
        }
      }
    }
  },

// authentication.ts
export function expressAuthentication(
    request: Request,
    securityName: string,
    scopes?: string[]
): Promise<any> {
    if (securityName === "jwt") {
        const token = getBearerToken(request)

        return new Promise((resolve, reject) => {
            if (!token) {
                reject(new Error("No token provided"));
            }
            
            jwt.verify(token, ACCOUNT_API_PUBLIC_KEY, function (err: any, decoded: any) {
				if (err) {
					reject(new Error('No decodable token provided'))
				} else {
					for (let scope of scopes) {
						if (!decoded.scopes.includes(scope)) {
							reject(new Error("JWT does not contain required scope."));
						}
					}
					resolve(decoded.user);
				}
			})
		}
	}
}

// adController.ts

@Tags("Ads")
  @Post("/")
  @Security("jwt", ['ads:store'])
  public async storeAd(
      @Body() adAttributes: AdAttributes
  ): Promise<AdData> {
    return await storeAd(adAttributes);
  }
```
I would expect that when the token is not present or is invalid, the API responds with a 401 status code to indicate that the user is not authorized to access the resource.

## Current Behavior

The api return 500 status without giving any useful message

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS:  19.7.0

**Comment by emoyly** [comment]
If you throw an error inside the auth middleware, it will be handled just like any other error in your app.
This means that, if you don't have any error handling middleware further down the chain, every error will just become a code 500 server error.
So I'd recommend adding an error handler after all your other middleware. https://expressjs.com/en/guide/error-handling.html
Then you can create a custom error class, or just catch any error with the messages.

An example could look like this (must be the last middleware, after `RegisterRoutes(app)` and everything:
```ts
app.use((err: any, req: express.Request, res: express.Response, next: express.NextFunction) => {
    if (err instanceof Error) {
        if (err.message === 'No decodable token provided' || err.message === 'JWT does not contain required scope.') {
            res.status(401)
        } else {
            res.status(500)
        }
        res.json({ error: err.message })
        return
    }
    res.status(500)
    res.send('Unknown error :(')
})
```

**Comment by osnipezzini** [comment]
This don't fix bug, because we need to handle string error messages instead a strongly-typed Error.

**Comment by osnipezzini** [comment]
> If you throw an error inside the auth middleware, it will be handled just like any other error in your app/controllers. This means that, if you don't have any error handling middleware further down the chain, every error will just become a code 500 server error. So I'd recommend adding an error handler after all your other middleware. You can read about that at https://expressjs.com/en/guide/error-handling.html and https://tsoa-community.github.io/docs/error-handling.html#setting-up-error-handling Then you can create a custom error class, or just catch any error with the messages.
> 
> An example could look like this (must be the last middleware, after `RegisterRoutes(app)` and everything:
> 
> ```ts
> app.use((err: any, req: express.Request, res: express.Response, next: express.NextFunction) => {
>     if (err instanceof Error) {
>         if (err.message === 'No decodable token provided' || err.message === 'JWT does not contain required scope.') {
>             res.status(401)
>         } else {
>             res.status(500)
>         }
>         res.json({ error: err.message })
>         return
>     }
>     res.status(500)
>     res.send('Unknown error :(')
> })
> ```
> 
> Hope this helps! 😊


This don't fix bug, because we need to handle string error messages instead a strongly-typed Error.

**Comment by osnipezzini** [comment]
Please re-open this issue, authentication middleware don't return strongly-typed error that we previously throw.

![image](https://github.com/lukeautry/tsoa/assets/4562546/031f4eb6-77ec-4a5c-9a95-9347cbc9a2ee)

On my example, i can throw two types of Error, but i can't handle this errors because AuthenticationError turns another Error object on middleware
