### ISSUE TITLE
following get started results in duplicated builts

### ISSUE THREAD

**Issue by migs35323** [lukeautry/tsoa#1441]
#### Steps to Reproduce
 
1 follow the documentation get started https://tsoa-community.github.io/docs/getting-started.html
2 set up swagger folllowing the docs https://tsoa-community.github.io/docs/live-reloading.html#installing-swagger-ui-express

using yarn build ("build": "tsoa spec-and-routes && tsc")
results in the following structure:

```tree
project
├── build
│   ├── build
│   │   ├── routes.js
│   │   └── swagger.json
│   ├── routes.ts
│   ├── src
│   │   └── app.js
│   ├── swagger.json
│   └── tsconfig.tsbuildinfo
├── node_modules
├── package.json
├── src
│   └── app.ts
├── tsconfig.json
├── tsoa.json
└── yarn.lock
```

so, is this normal? shouldn't src be transformed in build (or out) or am i missing something?

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: 18 (LTS)
Version of TSC:  4.9.4
Version of yarn: 1.22.19

- Confirm you were using yarn not npm: [ X ]

**Comment by WoH** [comment]
That's ok
