### ISSUE TITLE
Suggestion: clarify if emitDecoratorMetadata is required or not in docs

### ISSUE THREAD

**Issue by aldenquimby** [lukeautry/tsoa#1443]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
- https://tsoa-community.github.io/docs/getting-started.html should make it clear whether or not `emitDecoratorMetadata` is required for tsoa to work properly

## Current Behavior
- It's unclear to me. My app appears to work fine with this turned off, but I also see `relfect-metadata` used in this repo
- Is it required to use custom middleware, but otherwise not needed?

## Possible Solution
- Clarify why `"emitDecoratorMetadata": true` is part of the suggested "imported" tsconfig
- If it is needed for some part of tsoa to work, consider breaking that out into an optional/separate package (eg `@tsoa/middleware`)

## Steps to Reproduce
- N/A

## Context (Environment)
 
Version of the library: 5.x
Version of NodeJS: 18

- Confirm you were using yarn not npm: [x]

## Detailed Description
- N/A

## Breaking change?
- N/A

**Comment by WoH** [comment]
It should only be needed for middlewares, yes

**Comment by aldenquimby** [comment]
@WoH great, thank you! Here's a partial fix that is a start: https://github.com/tsoa-community/docs/pull/77
