### ISSUE TITLE
Null value for boolean attribute is converted to false. How to alter this behavior? 

### ISSUE THREAD

**Issue by RohitRox** [lukeautry/tsoa#1444]
This is related to validation. Null values sent for attributes defined as boolean are converted to false.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current & Expected Behavior

When an attribute is defined as a boolean
For eg:
```ts
interface UserCreateRequest {
    preferredDelivery: boolean
}
```
and in payload/request body, if null is sent
For eg:
```ts
{
    "preferredDelivery": null
}
```

After the request passes through validation, the `preferredDelivery`'s value is observed to be false.
The expected behavior is that the null value should have been preserved.

## Possible Solution

I understand in some cases this is okay and desired, but is some cases this behavior is needed. And I couldn't find a way to alter this behavior.
The validator library (https://github.com/validatorjs/validator.js) seem to have `{ loose: false }` option but I could not find a way to use it here.
Any help or guidance on this?

**Comment by WoH** [comment]
Hi there, you can customize the template as well as the route generator (template is simpler and should be sufficient).

However, we should also discuss these groups of coercions and if we want to customize them (i.e. via config or hooks)

**Comment by jchadwick** [comment]
This issue is more obvious (and more obviously a bug vs intended behavior) when the boolean property explicitly allows nulls.  e.g.

```typescript
interface UserCreateRequest {
    preferredDelivery: boolean | null
}
``` 

This also improperly converts explicitly `null` values to `false`

**Comment by WoH** [comment]
> This issue is more obvious (and more obviously a bug vs intended behavior) when the boolean property explicitly allows nulls.  e.g.
> 
> ```typescript
> interface UserCreateRequest {
>     preferredDelivery: boolean | null
> }
> ``` 
> 
> This also improperly converts explicitly `null` values to `false`

Try `null | boolean`

**Comment by jchadwick** [comment]
WOW, WAIT... WHAT!?

Yeah, that works.  But _why_??  And can we make the more "standard" `boolean | null` work as well?

**Comment by WoH** [comment]
Validation is from left to right.
