### ISSUE TITLE
typescript should not be a production dependency of cli (v5.1.1)

### ISSUE THREAD

**Issue by alandotcom** [lukeautry/tsoa#1459]
The CLI bundles typescript as a production dep, which ends up conflicting with locally installed Typescript versions

https://github.com/lukeautry/tsoa/blob/v5.1.1/packages/cli/package.json#L40

## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

typescript should be listed as a devDep

## Current Behavior

typescript is a prod dep

## Possible Solution

move to devDeps and publish a patch version, 5.1.2

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: 20

- Confirm you were using yarn not npm: [X]

## Breaking change?

No

**Comment by WoH** [comment]
We are using the TypeScript API directly, so that's not a mistake.

**Comment by alandotcom** [comment]
Then why not make it a peer dep instead?
