### ISSUE TITLE
Usage of `$` in type names leads to invalid OpenAPI specs

### ISSUE THREAD

**Issue by alandotcom** [lukeautry/tsoa#1461]
I created a sample repo to explain what's happening:

If a controller is referencing a type that looks like `HelloWorld`, then the resulting OpenAPI spec will create a a schema that is invalid (based on https://apitools.dev/swagger-parser/online/ and a few other tools I've been using, including https://github.com/stoplightio/prism)

```ts
export namespace $Enums {
  export const Test = {
    hello: "world",
    foo: "bar",
  };
  export type Test = (typeof $Enums.Test)[keyof typeof $Enums.Test];
}

export interface HelloWorld {
  hello: $Enums.Test;
}
```

https://github.com/alandotcom/tsoa-bug/blob/56a15eeb600fd6526658417d464719b564fa777b/src/types.ts

## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I believe that `%24` should be `$` on this line:

https://github.com/alandotcom/tsoa-bug/blob/56a15eeb600fd6526658417d464719b564fa777b/src/swagger.json#L9

## Current Behavior

```yaml

```

```ts

```

## Steps to Reproduce

Example repo here https://github.com/alandotcom/tsoa-bug/tree/main

## Context (Environment)

Version of the library: latest
Version of NodeJS: 18

- Confirm you were using yarn not npm: [X] (used pnpm, but unrelated to the problem)

## Detailed Description

Changing the generated swagger spec to be valid

## Breaking change?

I don't think this would be a breaking change

**Comment by LucianBuzzo** [comment]
As far as I can tell, the issue occurs because the refname is URI encoded, so that the ref can be correctly resolved, but the same URI encoded string is being used as the key.
