### ISSUE TITLE
Error: Unknown type: BigIntKeyword

### ISSUE THREAD

**Issue by Super-Nim** [lukeautry/tsoa#1476]
Tsoa doesn't recognise `bigint` types and returns the error `Error: Unknown type: BigIntKeyword`.

## Sorting

- **I'm submitting a**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [have] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Tsoa should recognise `bigint` types and not return `Error: Unknown type: BigIntKeyword`.

I know there were two closed issues for this, but none gave a valid solution. 

Can I get a valid solution for this?

```yaml

```

```ts

```

## Current Behavior

```yaml

```

```ts

```

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [no, I was using npm]

**Comment by WoH** [comment]
This is somewhat intended. Serialize it as lossy number or as string, and type that.

**Comment by Super-Nim** [comment]
> This is somewhat intended (You can't serialize it as a JSON). Serialize it as lossy number or as string, and type that.

Ok, that makes sense. The typeError is from an imported package that uses `bigint` in some of its custom types, is there a way to configure this in tsoa.json?

**Comment by bipiane** [comment]
I have the same issue when trying to reuse the types generated by Prisma ORM.
