### ISSUE TITLE
Help with tsoa implementation clean architecture express and typescript

### ISSUE THREAD

**Issue by IamCocoDev** [lukeautry/tsoa#1478]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

Hi people i have a problem with using tsoa with typescript and express 

```json
{
  "entryFile": "src/index.ts",
  "noImplicitAdditionalProperties": "throw-on-extras",
  "controllerPathGlobs": ["src/**/*.ts"],
  "spec": {
    "outputDirectory": "public",
    "specVersion": 3
  }
}
```
Thas my folder structure
<img width="284" alt="image" src="https://github.com/lukeautry/tsoa/assets/48165276/e31fe828-c3f5-497e-abb9-a71ad2e7d45d">

I have this problem
<img width="889" alt="image" src="https://github.com/lukeautry/tsoa/assets/48165276/be1fa05b-7708-4c87-9dcc-f7704e083830">

This the code iam trying to use tsoa but cant work when run tsoa spec
```ts 
import { Router } from 'express';
import { IWebService, IWebServiceParams } from 'shared/ports';
import { Controller, Get, Response, Route } from 'tsoa';

@Route('Status')
export class StatusServiceExpress extends Controller implements IWebService {
  private route: Router = Router();

  constructor(public params: IWebServiceParams) {
    super();
    this.getService();
  }

  @Get()
  @Response(200, 'Up and running')
  getService() {
    this.route.get('/', (req, res) => {
      res.send('Up and running');
    });

    return this.route;
  }
}
```

And the lastone code its express server 

```ts
import express from 'express';
import { morganConfig } from 'config/morgan';
import { IWebServer, IWebService } from 'shared/ports';
import swaggerUi from 'swagger-ui-express';



export class ExpressWebServer implements IWebServer {
  init(options: { port: number; services: IWebService[] }): void {
    this.app.use(morganConfig)
    this.app.listen(options.port, () => {
      console.log(`🧩 Bff-template up and running. Port: ${options.port} enjoy and brake it`);
    });
    this.app.use(express.json());
    this.app.use(express.urlencoded({ extended: true }));
    this.app.use(express.static('public'));
    this.app.use(
      "/docs",
      swaggerUi.serve,
      swaggerUi.setup(undefined, {
        swaggerOptions: {
          url: "/swagger.json",
        },
      })
    )

    options.services.forEach((service) => {
      this.app.use(service.params.prefixUrl, service.getService());
    });
  }

  private app = express();
}
```

**Comment by IamCocoDev** [comment]
I discover what line of code do fail it 

```ts
import { Router } from 'express';
private route: Router = Router();

**Comment by ArkasDev** [comment]
You need to add the following code. To generate the required files you need to run `tsoa spec-and-routes`.

```
import {RegisterRoutes} from "../build/routes";
RegisterRoutes(app);
```

**Comment by IamCocoDev** [comment]
> You need to add the following code. To generate the required files just run `tsoa spec-and-routes`.
> 
> ```
> import {RegisterRoutes} from "../build/routes";
> RegisterRoutes(app);
> ```

I can't use that code he suggests because it edits the Swagger configuration and causes Nodemon to enter an infinite loop

**Comment by Alexander-Welsh** [comment]
@IamCocoDev you can add an `ignore` array to the `nodemon.json` file, which should avoid that infinite loop issue.

**Comment by IamCocoDev** [comment]
Thanks, @Alexander-Welsh, I have a question about how to work RegisterRoutes(app); because I can do all TSOA without this line!
