### ISSUE TITLE
MetadataGenerator.checkForMethodSignatureDuplicates is not working properly

### ISSUE THREAD

**Issue by pauline-greenly** [lukeautry/tsoa#1482]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
When generating two differents apis, with differentiate docs, where the base paths are "api/v1" and "api/v2".
TSOA should allow to generates two sames routes with two different base path. 
Example: 
POST /api/v1/users
POST /api/v2/users

Those two routes should work
```

## Current Behavior

```yaml
The generation of the routes does not work when the route are identical but not the base path.

Error :

Generate routes error.
 GenerateMetadataError: Duplicate method signature @post(suppliers) found in controllers: SupplierController#bulkImport, SupplierController#bulkImport

    at MetadataGenerator.checkForMethodSignatureDuplicates (/Users/paulinegangloff/Documents/offspend/node_modules/@tsoa/cli/dist/metadataGeneration/metadataGenerator.js:41:23)
    at MetadataGenerator.Generate (/Users/paulinegangloff/Documents/offspend/node_modules/@tsoa/cli/dist/metadataGeneration/metadataGenerator.js:138:14)
    at generateRoutes (/Users/paulinegangloff/Documents/offspend/node_modules/@tsoa/cli/dist/module/generate-routes.js:14:177)
    at routeGenerator (/Users/paulinegangloff/Documents/offspend/node_modules/@tsoa/cli/dist/cli.js:261:52
```

## Possible Solution

This line should take into account also the base path
```ts
const signature = method.path ? `@${method.method}(${controller.path}/${method.path})` : `@${method.method}(${controller.path})`;
```

## Steps to Reproduce

1. Create two identical controller, 1 in a v1 directory, the other in a v2 directory
2. Reproduce with this kind of command: 
```
tsoa routes --basePath api/v1 --configuration src/presentation/rest-api/v1/tsoa.json
tsoa routes --basePath api/v2 --configuration src/presentation/rest-api/v2/tsoa.json
```

## Context (Environment)

Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [x]

**Comment by jackey8616** [comment]
@pauline-greenly  tsoa can not recognize controller's base path by its folder name, thus the Generator can not process as you wish.

Once you execute the `tsoa routes` command, tsoa would take whole folder(including v1 and v2 folrder) to generate routes.

@WoH:
I think this is not a bug, since the issue author's usecase is slightly different to the usual way using tsoa.
We should provide some sort of decorator to mark controller's base path to do such things.
