### ISSUE TITLE
How to generate a swagger file for specific controllers or tags

### ISSUE THREAD

**Issue by DanyalKhawaja** [lukeautry/tsoa#1484]
## Sorting

- **I'm submitting a ...**

  - [x ] bug report
  - [x ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml

```

```ts

```

## Current Behavior

```yaml

```

```ts

```

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
https://github.com/lukeautry/tsoa/blob/master/packages/runtime/src/config.ts#L28
