### ISSUE TITLE
Post Form Fields

### ISSUE THREAD

**Issue by luminblade** [lukeautry/tsoa#149]
I can't seem to find how to identify a POST method where each fields is posted separately (like @Query() for GET).  All I can see is @Body(), but that creates an entire JSON object vs. separate fields  Am I missing something?

**Comment by lukeautry** [comment]
You just use @query(). It works with POST too.

**Comment by rucciva** [comment]
hi @lukeautry , i'm looking for specifying the body using url-form-encoded too, but it seems that using @query() with @post() doesn't seem to achieve it (the parameter is still going to be expected from url query)
