### ISSUE TITLE
 @Queries Can't support 'refObject' type

### ISSUE THREAD

**Issue by aramais21** [lukeautry/tsoa#1499]
## Sorting

- **I'm submitting a Bug Report**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

```ts
export class SearchDto {
    @IsOptional()
    @IsString()
    value?: string;
}

export class ListQuery {
    @IsDefined()
    @IsNotEmptyObject()
    @IsObject()
    @ValidateNested()
    @Type(() => SearchDto)
    search: any;
}

```

## Expected Behavior
The above could should not throw any error

## Current Behavior

Currently the above code throws this error
```
Generate routes error.
 GenerateMetadataError: @Queries('query') nested property 'search' Can't support 'refObject' type. 
 in 'Controller.list'
```

1. 2. 3. 4.

## Context (Environment)

Version of the library:  5.1.1
Version of NodeJS: 18.16

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
How would you serialize this? Nested object via query?
