### ISSUE TITLE
Support implicit return types

### ISSUE THREAD

**Issue by lukeautry** [lukeautry/tsoa#15]
Currently, the only way to mark a controller method's corresponding swagger definition is with explicit type notation:

```
@Route('GetTest')
export class GetTestController {

  @Get()
  public async getModel(): Promise<TestModel> {
    return new ModelService().getModel();
  }
}
```

The following edit would break generation:

```
@Route('GetTest')
export class GetTestController {

  @Get()
  public async getModel() {
    return new ModelService().getModel();
  }
}
```

If possible, we should find a way to get the 'implicit' type from a class method. This seems like it should be possible given that editors calling into the language service can do it.

**Comment by isman-usoh** [comment]
#140
