### ISSUE TITLE
Error handling - How to return status code and custom error message

### ISSUE THREAD

**Issue by eluft84** [lukeautry/tsoa#150]
Hi @lukeautry ,

unfortunately i have no idea how i can handle my errors get from my backend systems, eg. DB.
I have a Promise which rejects with an error message when an error occurs:

**Service:**
`return service.user.getUserInfo(id);`

**Controller:**
```
getUserInfo(id: string): Promise<UserObject> {

        let result = new Promise<UserObject>((resolve, reject) => {
            let query = dbConnection.getUser(id); //Returns a Promise
            query.catch((err) => {
                reject(new Error("user not found"));
            }).then((response) => {
                resolve(response);
            });
        });
        return result;
    }
```  

How can i manage to return a custom status code with an error?

Would be great if you can give me some ideas and advice ;)

**Comment by isman-usoh** [comment]
ApiError.ts
```ts
export class ApiError extends Error {
    private statusCode: number;
    constructor(name: string, statusCode: number, message?: string) {
        super(message);
        this.name = name;
        this.statusCode = statusCode;
    }
}
```
If use promise
```ts
public async getUserInfo(id: string): Promise<UserObject> {
  return dbConnection.getUser(id)
           .then(res => {
              return res;
           })
           .catch(err => {
               throw new ApiError("UserNotFount",400,"user not found");
           });
}
```
If use Async/Await
```ts
public async getUserInfo(id: string): Promise<UserObject> {
  try {
      const res = awit condbConnection.getUser(id);
      return res;
  } catch (error) {
      throw new ApiError("UserNotFount",400,"user not found");
  }
}
```

express.js
```ts
import * as express from "express";
import * as errorHandler from "api-error-handler";

const app = express();
...
app.use(errorHandler());
app.listen(3000);
```


response
```json
{
  "name": "UserNotFount",
   "status": 400,
  "message": "user not found"
}
```

**Comment by Faberle** [comment]
How do you annotate that function so the error is included in the swagger config?

**Comment by danieldietrich** [comment]
Any suggestions on @Faberle's question?
How do we instrument the tsoa  code generator such that error codes & error descriptions are included into the generated swagger config?

**Comment by hatim-heffoudhi** [comment]
Hello, 
Do you use koa or express  as a middleware ?

**Comment by lukeautry** [comment]
Looks like this is a solved problem.

**Comment by hatim-heffoudhi** [comment]
> Looks like this is a solved problem.

hey it's seem so :)

**Comment by douglasg14b** [comment]
> `import * as errorHandler from "api-error-handler";`

Where is this coming from? What is inside of it?? This is the "draw the rest of the owl" moment for me :/
