### ISSUE TITLE
OpenTelemetry for distributed tracing with TSOA

### ISSUE THREAD

**Issue by erangac** [lukeautry/tsoa#1503]
Does TSOA include built-in functionality for context management? For example, is there support for accessing the traceId from incoming HTTP requests, adding new spans, or propagating the current context to a new service?

What is the recommended approach for implementing these context management features in TSOA?

**Comment by WoH** [comment]
Sure, depending on the framework you target, you can write your own middleware/plugin that does that, or use the ones provided, for example tsoa for express, you would want to check out:
https://www.npmjs.com/package/@opentelemetry/instrumentation-express

**Comment by erangac** [comment]
In this particular scenario, it appears that manual context propagation is necessary. I am referring to a process similar to the following. 

https://github.com/musay0/node-samples/blob/v1.0.0/express-otel-boilerplate/src/invoker.ts

It would be beneficial to have a standardized mechanism provided by TSOA for this purpose.
