### ISSUE TITLE
Key of schema with `$` are generated, but `$` is invalid character.

### ISSUE THREAD

**Issue by bigen1925** [lukeautry/tsoa#1507]
Key of schema with `$` is generated when `$` is in type name, but `$` is invalid in schema name.

refs) https://swagger.io/specification/#:~:text=All%20the%20fixed%20fields%20declared%20above%20are%20objects%20that%20MUST%20use%20keys%20that%20match%20the%20regular%20expression%3A%20%5E%5Ba%2DzA%2DZ0%2D9%5C.%5C%2D_%5D%2B%24.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

`$` (the only character that can be used in ES identifier and invalid in openapi key ) should be replaced with `_` or `.` or `-`

When type definition is
```ts
type $DollarType = string;
```
, generated spec is expected like
```json
{
  "components": {
    "schemas": {
      "_DollarType": {
        "type": "string"
      }
    }
  }
}
```

## Current Behavior

When type definition is
```ts
type $DollarType = string;
```
, generated spec is
```json
{
  "components": {
    "schemas": {
      "$DollarType": {
        "type": "string"
      }
    }
  }
}
```

## Possible Solution

replace `$`

## Steps to Reproduce

https://github.com/bigen1925/tsoa-schema-key-with-dollar

## Context (Environment)

Version of the library: 6.0.0-rc.4
Version of NodeJS: v18.15.0

- Confirm you were using yarn not npm: [x]

## Detailed Description

nothing

## Breaking change?

may be NO.

**Comment by bigen1925** [comment]
This is relevant to #1468

**Comment by WoH** [comment]
Can you check with tsoa@next? This should be solved

**Comment by bigen1925** [comment]
@WoH 
I confirmed this is solved in `tsoa@next` !

Thank you so much!
