### ISSUE TITLE
Custom templates Handlebars

### ISSUE THREAD

**Issue by ymedaghri** [lukeautry/tsoa#1508]
Hi, I like your library and your work.
I have a very custom need where I need to generate my routes to publish them as AWS Lambdas, so they will not be using express, koa or Hapi, they are custom made.
I'd like to create a custom middleware for my need so I can generate the tsoa controllers as these new javascript "api lambdas".

Could I get some documentation on how I can do this ? 

Thank you !

## Sorting

- **I'm submitting an ask for help about custom templates**

  - [ ] bug report
  - [ ] feature request
  - [X ] support request

- I confirm that I
  - [ X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml

```

```ts

```

## Current Behavior

```yaml

```

```ts

```

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
https://github.com/lukeautry/tsoa/tree/master/tests/fixtures/custom

Hope this helps
