### ISSUE TITLE
Is there any way to exclude some methods from swagger?

### ISSUE THREAD

**Issue by chaowlert** [lukeautry/tsoa#151]
Suppose we have admin methods, and would like to generate routes via `tsoa routes`, but would like to exclude those methods in `tsoa swagger`. How could we do this?

**Comment by lukeautry** [comment]
@chaowlert This is a good idea. I think it should be possible to mark a method as @SwaggerIgnore or something like that.

**Comment by dgreene1** [comment]
This feature was actually added a while ago with the `@Hidden` decorator which was added with PR https://github.com/lukeautry/tsoa/pull/152
