### ISSUE TITLE
Is it possible to split routers with tsoa for lambdas?

### ISSUE THREAD

**Issue by Anasshahidd21** [lukeautry/tsoa#1514]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

When creating an express server, I create multiple routers and each router is exported as a lambda function to AWS. I want to do the same while using tsoa but I know that tsoa has more of a monolithic architecture, is there a way to get to it? right now when I do the exports it is exporting all of the server as one lambda function

**Comment by WoH** [comment]
Yes, via a custom route generator. There's one for AWS Lambda sketched out in the tests
