### ISSUE TITLE
Help requested: Using in-memory caching with TSOA

### ISSUE THREAD

**Issue by evakkuri** [lukeautry/tsoa#1518]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I'm looking to implement an in-memory cache for my TSOA API, and I'm wondering what would be the best way to implement this. I cannot set the cache in a controller, as controllers are recreated for each request, and probably having multiple caches would not work anyway.

Would dependency injection be the way to go here? However, I'm looking for a lightweight solution, as to start with I would only use caching for a single endpoint, and would not like to migrate the entire application to use DI.

Would there be some way of just passing a singleton cache instance to controllers as parameter? Or some other lightweight solution.

## Current Behavior

Not clear how to pass a common in-memory cache instance to requests

## Possible Solution

- Dependency injection?

## Steps to Reproduce

- None

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: 18.18.2

- Confirm you were using yarn not npm: [X]

## Detailed Description

Request for help with implementing in-memory caching for TSOA

## Breaking change?

- None suggested

**Comment by pquerner** [comment]
Implement a cache decorator which fetches or retrieves your item from the cache.
