### ISSUE TITLE
Allow providing function as well as string in @Route and @Get @Post etc

### ISSUE THREAD

**Issue by Khaaz** [lukeautry/tsoa#1522]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I would like to be able to call `@Route`, `@Post`, `@Get` etc with functions. In my specific case, I would like the return value from the function call. 

In my use case, I would want to use it like this:

```ts
@Route(OPEN_API.ACCOUNTS.router())
export class AccountsController extends Controller {
```

That doesn't work as it yield `undefined`, since it's executed at compile time (`OPEN_API.ACCOUNTS.router()` returns a string).

Ideally, and to make this more flexible for everyone, the ideal would be to be able to pass function like that:

```ts
@Route(() => "accounts")
@Route(() => OPEN_API.ACCOUNTS.router())
export class AccountsController extends Controller {
```

The decorator itself would execute the function and it would behave as expected.

## Current Behavior

Right now, since this is done at build / compile time, there is no way to get the result of the function and to pass that to tsoa.

You HAVE to provide a string:

```ts
@Route("accounts")
export class AccountsController extends Controller {
```

## Possible Solution

Allowing to pass function as well as string that would get resolved by tsoa directly

```ts
@Route(() => "accounts")
export class AccountsController extends Controller {
```

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: 20.9

- Confirm you were using yarn not npm: [X]

## Detailed Description

Modify the current parser so it parses function as well as string. And if it finds a function it just executed it to get the results.

## Breaking change?

Not a breaking change as we would still be supporting string

**Comment by yalcinozer** [comment]
Hey, I have a question. I have a controller which I use for doing some experiments while developing. I want to ignore that route/controller in production. Is there a way to do it? I am checking prod<=>dev status via `process.env.NODE_ENV`
Thanks

**Comment by ValentinGurkov** [comment]
It seems that things like
```ts
@Route(`v1/products/${ProductTypeKeysEnum.TRAINING}`)
```
also can't get evaluated.

**Comment by Khaaz** [comment]
:'(

**Comment by WoH** [comment]
I don't think we want to run arbitrary, functions at build time.

> It seems that things like
> 
> ```ts
> @Route(`v1/products/${ProductTypeKeysEnum.TRAINING}`)
> ```
> 
> also can't get evaluated.

This one, assuming it actually is an enum is a different issue, but I'm happy to review a PR for it.
