### ISSUE TITLE
When will TSOA 6.0 be released?

### ISSUE THREAD

**Issue by enrique-lozano** [lukeautry/tsoa#1526]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

It's been like a year since the last version was released to the npm store, and the package feels like a bit outdated. Are there any plans to release the version 6 soon?

**Comment by WoH** [comment]
This year
