### ISSUE TITLE
"$" char percent encoding causes reference and pointer resolving issue 

### ISSUE THREAD

**Issue by ashe0047** [lukeautry/tsoa#1530]
I am using Prisma generated types to generate the swagger document but Prisma generates Enum types using $Enum namespace resulting in the schema name being percent encoded causing reference and pointer resolving error as percent encoding is not decoded by swagger-ui

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml

```

```ts

```

## Current Behavior

```yaml

```

```ts

```

## Steps to Reproduce
Using a type var name with $ character should reproduce the same error

![image](https://github.com/lukeautry/tsoa/assets/63364968/44f74a63-7603-43d7-85e7-e89e8841aa72)
![image](https://github.com/lukeautry/tsoa/assets/63364968/59c22c4a-5355-41ce-8e1a-03ccca22001d)

1. 2. 3. 4.

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: 20.9.0

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
Should be gone in v6.
