### ISSUE TITLE
Snyk security vulnerability for inflight (one of tsoa indirect dependencies)

### ISSUE THREAD

**Issue by erlanggatjhie** [lukeautry/tsoa#1572]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior

Snyk has identified a security vulnerability within the tsoa packages:

[Inflight - Missing Release of Resource after Effective Lifetime](https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116)
```
Introduced through: tsoa@4.1.3 › @tsoa/cli@4.1.3 › yamljs@0.3.0 › glob@7.2.3 › inflight@1.0.6
Fix: No remediation path available.

Introduced through: tsoa@5.1.1 › @tsoa/cli@5.1.1 › yamljs@0.3.0 › glob@7.2.3 › inflight@1.0.6
Fix: No remediation path available.

Introduced through: tsoa@6.0.0 › @tsoa/cli@6.0.1 › yamljs@0.3.0 › glob@7.2.3 › inflight@1.0.6
Fix: No remediation path available.
```

## Possible Solution

The vulnerability comes from yamljs@0.3.0 which indirectly uses inflight. Unfortunately, both `inflight` and `yamljs` are not actively maintained. I am thinking if we can use [js-yaml](https://github.com/nodeca/js-yaml) or [yaml](https://github.com/eemeli/yaml) instead of `yamljs` to remediate the security issue. 

## Context (Environment)

Version of the library: 4.1.3, 5.1.1, 6.0.0
Version of NodeJS: 18

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
Not relevant to how we use that package in the cli.
But happy to review a PR if anyone is annoyed by the warning

**Comment by bill-titus** [comment]
> But happy to review a PR if anyone is annoyed by the warning

Thanks WoH.  Happy to hear the finding is not relevant to how we use that package.  The finding actually causes lots of lost time dealing with corporate security teams and especially government customers that monitor each finding.  Switching to a more maintained yaml library would be appreciated.  Thanks for the fix @mamerruddin!
