### ISSUE TITLE
Version 6.1.0 leads to missing packages, breaks existing builds

### ISSUE THREAD

**Issue by ManfredLange** [lukeautry/tsoa#1573]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I can upgrade from version 6.0.1 to 6.1.0 and expect there are no breaking changes.

```yaml

```

```ts

```

## Current Behavior

I just tried to upgrade from version 6.0.1 to version 6.1.0. The older version is just fine with no issues running our npm scripts.

However, with version 6.1.0 we now observe that packages are missing:
- `@hapi/boom`
- `@tsoa/cli`

These lead to compile/build errors because those packages cannot be found.

```yaml

```

```ts

```

## Possible Solution

Something in the direct or indirect dependencies has changed between version 6.0.1 and 6.1.0.

The problem can be solved by applying the following in `package.json`:
- add package `@hapi/boom` to the dependencies
- add package `@tsoa/cli` to the devDependencies

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 6.1.0
Version of NodeJS: 20.11.1
Version of TypeScript: 5.4.2

- Confirm you were using yarn not npm: [ ]

I'm using pnpm instead of npm but do not believe this to be the problem. Package `tsoa` worked just fine until an up to version 6.0.1 with pnpm across multiple TypeScript projects. There was no need to add any other package to make tsoa work.

## Breaking change?

Yes, this is a breaking change as we had to add the missing packages to `package.json` which we didn't have to list as dependencies before.

# UPDATE 10 Mar 2024

A possibly better option to resolve this is described in this comment: https://github.com/lukeautry/tsoa/issues/1573#issuecomment-1986996301

**Comment by shadowCruz** [comment]
+1 
```

Error: Cannot find module '@hapi/boom'
Require stack:
- /usr/src/app/node_modules/@tsoa/cli/dist/routeGeneration/templates/hapi/hapiTemplateService.js
- /usr/src/app/node_modules/@tsoa/cli/dist/index.js
- /usr/src/app/dist/tsoa/routes.js
- /usr/src/app/dist/app.js
- /usr/src/app/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@tsoa/cli/dist/routeGeneration/templates/hapi/hapiTemplateService.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/@tsoa/cli/dist/routeGeneration/templates/hapi/hapiTemplateService.js',
    '/usr/src/app/node_modules/@tsoa/cli/dist/index.js',
    '/usr/src/app/dist/tsoa/routes.js',
    '/usr/src/app/dist/app.js',
    '/usr/src/app/dist/index.js'
  ]
}
```

6.0.1 ftw :salute

**Comment by marudor** [comment]
FYI @ManfredLange the text you wanted to provide in the copyable boxes appears to be empty.

I also encountered this today though and downgraded back to 6.0.1.
Another issue besides being broken even in developent (due to `@hapi/boom` missing as I am using Koa) is that we now need `@tsoa/cli` as production dependency.
The generated routes now import the Template stuff from `@tsoa/cli`
Could we revert this? I would like to keep `@tsoa/cli` as a `devDependency`

**Comment by WoH** [comment]
@jackey8616 Can we fix the runtime imports into the cli easily?

**Comment by ManfredLange** [comment]
@marudor You wrote:
> FYI @ManfredLange the text you wanted to provide in the copyable boxes appears to be empty.

I don't understand what you are trying to say. Would you mind rephrasing, please?

**Comment by ManfredLange** [comment]
Further to this: It appears that the cli was a regular dependency for `tsoa` in version 6.0.1 already and this has not changed to 6.1.0 However, what has changed is that version 6.1.0 of the cli is missing the dependency on `@hapi/boom`.

Here is a snippet from the pnpm-lock.yml file when I use tsoa version 6.0.1:
```yml
  /tsoa@6.0.1:
    resolution: {integrity: sha512-Far5BFpFvMYVMZxt87O7hOFGpa6dALQ8XHhdDytry0IhIUJnRliVXLZ2t2KGcgNw0bIwsk+2XkWra18LL6cORA==}
    engines: {node: '>=18.0.0', yarn: '>=1.9.4'}
    hasBin: true
    dependencies:
      '@tsoa/cli': 6.1.0
      '@tsoa/runtime': 6.0.0
    dev: false
```

Here is the equivalent snippet for tsoa 6.1.0:
```yml
  /tsoa@6.1.0:
    resolution: {integrity: sha512-qFmOQEj6+EIjUesFxqwi8f5FjjpAhPRzj5StDueM23NexJgEUjc76ysghNV5IDf4wOOUCrNgI4krgwYw6trSDg==}
    engines: {node: '>=18.0.0', yarn: '>=1.9.4'}
    hasBin: true
    dependencies:
      '@tsoa/cli': 6.1.0
      '@tsoa/runtime': 6.1.0
    dev: false
```

Both of these were created starting with a clean slate. By clean slate I mean that I removed `node_modules`, local pnpm cache and also the `pnpm-lock-yml` file before running `pnpm install`. This ensured that the only information used is the packages listed in `package.json`.

From that snippet I read that `tsoa` has a dependency on `@tsoa/cli` which I think is not intended, and may not be what you want. Thank you, @marudor , for pointing that out!

Furthermore, once your lock file - npm, pnpm, etc. - has picked up the newer version of cli, i.e. 6.1.0, you will observe the issue with missing `@hapi/boom`.

To solve the problem for tsoa 6.0.1, you need to add the cli in version 6.0.1 explicitly.

To solve the problem for tsoa 6.1.0, you need to add the cli as well as `@hapi/boom` to the direct dependencies.

So, it appears as if the real bug twofold:
1. tsoa has a runtime dependeny on the cli
2. In version 6.1.0 the cli has a dependency on `@hapi/boom` which needs to be added as an extra step

While item 2 is "just" an extra step, the first one needs to be addressed. You don't want the cli in a production deployment. You want as little attack surface as possible. If it's not deployed in the first place, there is not way it can be attacked.

Happy to stand corrected, in case I overlooked something.

**Comment by ManfredLange** [comment]
On further investigating this issue, I think there is a fundamental problem with the package `tsoa`. It has a dependency on the cli and on the runtime.

And here is how you can resolve this issue while also avoiding the bug reported at the beginning of this discussion:

Everybody who follows the "Getting Started" instructions at https://tsoa-community.github.io/docs/getting-started.html will add package `tsoa` to their project. As a result all of them will have the cli as a runtime dependency!

I ran this little experiment:
1. Remove package `tsoa`
2. Add package `@tsoa/runtime` as a regular dependency
3. Add package `@tsoa/cli` as a devDependency
4. Replace imports of `tsoa` with imports from `@tsoa/runtime`

Then clear your npm cache, delete node_modules, lock file, etc. to start with a clean slate. Restore packages, build and run your tests.

With this setup I managed to change the cli to a dev dependency.

And this may be the best way to resolve this issue: clearly separating between the runtime and the dev tools. This has the additional advantage that everybody should be able to remove the cli from their production deployments.

Again, happy to stand corrected in case I overlooked something.

**Comment by Tantalon** [comment]
The generated routes.ts file imports from @tsoa/cli. These services would need to be moved from @tsoa/cli to @tsoa/runtime before we could eliminate @tsoa/cli in production.
https://github.com/lukeautry/tsoa/blob/118f090981f90078b348987cad7a3ae65a5c8d3a/packages/cli/src/routeGeneration/templates/express/express.hbs#L5

**Comment by ValentinGurkov** [comment]
I just want to leave a note that this is experienced for other frameworks too, not just hapi.

**Comment by jackey8616** [comment]
Messed up imports b/w cli & runtime has been take cared at #1574.
Still trying to find a way out to solve hapi & koa's dependencies.

cc @WoH

**Comment by ManfredLange** [comment]
> The generated routes.ts file imports from @tsoa/cli. These services would need to be moved from @tsoa/cli to @tsoa/runtime before @tsoa/cli could be removed from production.
> 
> https://github.com/lukeautry/tsoa/blob/118f090981f90078b348987cad7a3ae65a5c8d3a/packages/cli/src/routeGeneration/templates/express/express.hbs#L5

@Tantalon Excellent find, Robert! I didn't notice that. :+1:

**Comment by jackey8616** [comment]
#1574 fixes `mixed import b/w @tsoa/cli & @tsoa/runtime`.
#1575 fixes `@hapi import @ runtime, even not using such framework`.

Feel free to check it out, and comment any suggestion or potential problem.
apologize for the trouble cause by this refactor.
thank folks!

Origin problem was bring by #1545 in case anyone want to know.

**Comment by WoH** [comment]
@ManfredLange closing this, will reopen if we missed something

**Comment by ClementValot** [comment]
Still got it with tsoa 6.1.2 as devDependency and @tsoa/runtime 6.1.1 as dependency, which are the latest releases atm :/ 

```
D:\.npm-global\yarn.cmd run ts-check
../../../node_modules/@tsoa/runtime/dist/routeGeneration/templates/hapi/hapiTemplateService.d.ts:1:67 - error TS2307: Cannot find module '@hapi/hapi' or its corresponding type declarations.

1 import { Request as HRequest, ResponseToolkit as HResponse } from '@hapi/hapi';
                                                                    ~~~~~~~~~~~~

../../../node_modules/@tsoa/runtime/dist/routeGeneration/templates/koa/koaTemplateService.d.ts:1:36 - error TS2307: Cannot find module 'koa' or its corresponding type declarations.

1 import type { Context, Next } from 'koa';
                                     ~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  ../../../node_modules/@tsoa/runtime/dist/routeGeneration/templates/hapi/hapiTemplateService.d.ts:1
     1  ../../../node_modules/@tsoa/runtime/dist/routeGeneration/templates/koa/koaTemplateService.d.ts:1

Process finished with exit code 2
```

**Comment by WoH** [comment]
This should not be new though.
If you typecheck and include node modules, including unused declarations for hapi when you're using express, then should have always had a bad time.

**Comment by ClementValot** [comment]
I just upgraded from tsoa 6.0.1 and @tsoa/runtime 6.0.0 which didn't cause that specific issue, with the exact same setup otherwise 🤔

**Comment by jackey8616** [comment]
@WoH 
Can we split more sub package for `@hapi` & `koa` like:
```
$ yarn add tsoa @tsoa/hapi
```
or 
```
$yarn add tsoa @tsoa/koa
```
in the future?...

**Comment by jackey8616** [comment]
Will, idk,  its cost to much to do such things to split .hbs and template serivce.

**Comment by WoH** [comment]
No, makes no sense imo.
If we can import and what is already v. complicated because the package managers (pnmp) are kinda pushing this onto the user, that'll raise it as an issue here in any case.
TS can still make breaking changes, so does @types/* do often enough that we can't avoid it.

**Comment by WoH** [comment]
> I just upgraded from tsoa 6.0.1 and @tsoa/runtime 6.0.0 which didn't cause that specific issue, with the exact same setup otherwise 🤔

Upgrade to 6.1.3 please

**Comment by ClementValot** [comment]
> > I just upgraded from tsoa 6.0.1 and @tsoa/runtime 6.0.0 which didn't cause that specific issue, with the exact same setup otherwise 🤔
> 
> Upgrade to 6.1.3 please

Same issue :( 

I had a quick look at the commit, shouldn't the hapi/koa dependencies be added as direct dependencies in tsoa rather than runtime? (Or something something optional dependencies but I'm not good at those) 
I need them when I'm in dev/build mode so that the tsoa CLI can transpile, but my tsoa-powered software won't need these at runtime
