### ISSUE TITLE
Stupid bug in the TS parser with an interface named "Account"

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#158]
I can't name an interface "Account" :(

Typescript has already an interface "Account" within the predefined objects.

If I name my interface "Account" no routes can be created.

Solution: Better Symbol resolving or igore symbols from "npm_modules/typescript"

**Comment by egandro** [comment]
FIxed this in the getModelTypeDeclaration()

**Comment by mellodev** [comment]
@egandro is it possible for you to share your fix? I'm running into a similar issue I suspect your fix will resolve.

**Comment by egandro** [comment]
I did a merge request.
