### ISSUE TITLE
Can't Handle Optional File Field on multipart/form-data

### ISSUE THREAD

**Issue by shibukazu** [lukeautry/tsoa#1585]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The following code is an example of a post endpoint handler:
```ts
public async postHandler(
  @FormField("userId") userId: string,
  @UploadedFile("file1") file?: Express.Multer.File,
  ): Promise<Response> {}
```

The expected behavior is that this handler can handle multipart/form-data requests correctly when only userId is included in the request.

## Current Behavior

Currently, it outputs an error message like the following:
```
{
	"message": "Cannot read properties of undefined (reading 'length')"
}
```

## Possible Solution

This issue seems to be caused by an incorrect implementation of the template engine, specifically [expressTemplateService.ts line 89](https://github.com/lukeautry/tsoa/blob/1fb41980f20b7a16f14e623f46baf3a9ff0d041e/packages/runtime/src/routeGeneration/templates/express/expressTemplateService.ts#L89).
When the file field is optional in @UploadedFile and not included in the actual request, fileArgs becomes undefined. The current implementation does not account for this and tries to call the length property, resulting in the aforementioned error.
To address this issue, the implementation should be modified as follows:

```ts
case 'formData': {
    const files = Object.values(args).filter(param => param.dataType === 'file');
    if (param.dataType === 'file' && files.length > 0) {
        const requestFiles = request.files;
        const fileArgs = this.validationService.ValidateParam(param, requestFiles[name], name, fieldErrors, undefined, this.minimalSwaggerConfig);
        return fileArgs ? (fileArgs.length === 1 ? fileArgs[0] : fileArgs) : undefined;
    }
    else if (param.dataType === 'array' && param.array && param.array.dataType === 'file') {
        return this.validationService.ValidateParam(param, request.files, name, fieldErrors, undefined, this.minimalSwaggerConfig);
    }
    return this.validationService.ValidateParam(param, request.body[name], name, fieldErrors, undefined, this.minimalSwaggerConfig);
}
```

May I publish pull request for this issue?

## Context (Environment)

Version of the library: 6.1.4
Version of NodeJS: 18

**Comment by WoH** [comment]
@jackey8616
