### ISSUE TITLE
Add ability to split Swagger documentation to 2 swagger.json files (e.g. external and internal)

### ISSUE THREAD

**Issue by amozh** [lukeautry/tsoa#159]
The use-case is any website which has API and/or UI for administration - admin portal.

Usually there is a Public part of the API **(external)** which is available for customers and Private part **(internal)** used by developers and/or other internal users for monitoring and administration.

So it would be great to have them as separate `swagger.json` files and put internal documentation under security, so any user cannot see it without having specific permissions.

Most likely within TSOA it will be enough to be able to mark `Controllers`, `Methods`, `Query` and `Header` parameters as _Internal_ and generate separate `swagger.json` file for them. 
Permissions may be handled at the API level.

There is already implemented `@Hidden()` decorator, which could be used as a workaround, but if you mark endpoint as `@Hidden()` it will not be visible anywhere, hence we are loosing benefits of swagger docs for those endpoints.

Actually we don't have to limit ourselves only with `external` and `internal` - we might want to split documentation to `group1`, `group2`, `group3` but it is much more rare use-case.

Implementation of `External` and `Internal` documentation is not that complicated, it might include:
1) Additional config in `tsoa.json` to show specific title and description for internal doc.
2) New decorator, e.g. `@Internal()`
3) Update `Tsoa.Controller, Tsoa.Method and Tsoa.Parameter` models to have additional property `isInternal: boolean`
3) Update metadata generators to capture new decorator.
4) Update spec generator to filter `paths` and parameters corresponding to `isInternal` property.
5) Add few lines to cli to save 1 more file to file system.
 
Some ideas for logic in `src/swagger/specGenerator.ts`:
```javascript
...
private buildPaths(isInternalDoc: boolean) {
    const paths: { [pathName: string]: Swagger.Path } = {};
    
    this.metadata.controllers.filter(c => {
      if (isInternalDoc && c.isInternal || 
          isInternalDoc && !c.isInternal && c.methods.find(m => m.isInternal) ||
          !isInternalDoc && !c.isInternal) {
        return true
      }
      return false;
    }).forEach(controller => {
      // construct documentation using all methods except @Hidden
      controller.methods
        .filter(method => !method.isHidden)
        .filter(m => {
          if (!isInternalDoc && !controller.isInternal && !m.isInternal || 
              isInternalDoc && (controller.isInternal || m.isInternal || m.parameters.find(p => p.isInternal === true))) {
            return true
          }
          return false;
        })
        .forEach(method => {
          const path = `${controller.path ? `/${controller.path}` : ''}${method.path}`;
          paths[path] = paths[path] || {};
          this.buildMethod(controller.name, method, paths[path], isInternalDoc);
        });
    });

    return paths;
  }

  private buildMethod(controllerName: string, method: Tsoa.Method, pathObject: any, isInternalDoc: boolean) {
    ...
    ...
    pathMethod.parameters = method.parameters
      .filter(p => {
        if (!isInternalDoc && p.isInternal && ['query', 'header'].indexOf(p.in) > -1) { //if internal query string parameter and we are generating non internal documentation
          return false;
        }
        return !(p.in === 'request' || p.in === 'body-prop');
      })
      .map(p => this.buildParameter(p));
    ...
    ...
  }
...
```
Other changes are trivial.

I would love to implement this as soon as anybody agrees that it will fit to this framework.

**Comment by amozh** [comment]
Here is PR
https://github.com/lukeautry/tsoa/pull/160

**Comment by fhewitt** [comment]
My first idea, is that this should probably be implemented as a slightly more generic way with @Bundle('internal') @Bundle('public'). With this approach, you open the solution for more than 2 swagger file generation.

**Comment by amozh** [comment]
@fhewitt agree, that is what i was thinking as well. 
From description above:
> Actually we don't have to limit ourselves only with external and internal - we might want to split documentation to group1, group2, group3 but it is much more rare use-case.

Pr is just for demo purposes.

**Comment by dgreene1** [comment]
This is possible with the use of the `ignore` config option: https://github.com/lukeautry/tsoa/blob/master/src/config.ts#L18

You would need to run tsoa twice on your separate folders. I would recommend running tsoa programmatically as described in the readme so it will be easier to keep track of your separate configs. We’ll close the issue for housekeeping reasons since I just described a workaround, since you had a demo PR, and since this is the only request we’ve had for this kind of bespoken arrangement.
