### ISSUE TITLE
The latest version 6.1.4 causes new build issues. 

### ISSUE THREAD

**Issue by JimmyBjorklund** [lukeautry/tsoa#1590]
The latest version 6.1.4 causes new build issues. 

0.932 > tsc
0.932
3.885 node_modules/@hapi/hapi/lib/types/route.d.ts:2:68 - error TS2307: Cannot find module 'joi' or its corresponding type declarations.
3.885
3.885 2 import { ObjectSchema, ValidationOptions, SchemaMap, Schema } from 'joi';
3.885                                                                      ~~~~~
3.885
3.887 node_modules/@hapi/hapi/lib/types/server/server.d.ts:4:22 - error TS2307: Cannot find module 'joi' or its corresponding type declarations.
3.887
3.887 4 import { Root } from 'joi';
3.887                        ~~~~~
3.887
3.887 node_modules/@tsoa/runtime/dist/routeGeneration/templates/koa/koaTemplateService.d.ts:1:36 - error TS7016: Could not find a declaration file for module 'koa'. '/usr/src/app/node_modules/koa/lib/application.js' implicitly has an 'any' type.
3.887   Try `npm i --save-dev @types/koa` if it exists or add a new declaration (.d.ts) file containing `declare module 'koa';`
3.887
3.887 1 import type { Context, Next } from 'koa';
3.887                                      ~~~~~

**Comment by WoH** [comment]
Seems like skipLibCheck is false explicitly?
I'm not sure, but the joi part seems more like an issue with hapi's type declarations.
Not sure about koa though

**Comment by WoH** [comment]
[935af8e](https://github.com/lukeautry/tsoa/commit/935af8ef7ec143e128b53a9ca4e73f4bf6cde564) will fix koa.

**Comment by jackey8616** [comment]
> Seems like skipLibCheck is false explicitly? I'm not sure, but the joi part seems more like an issue with hapi's type declarations. Not sure about koa though

Confirm:
When I try to reproduce #1594, I create another clean repo using tsoa@6.1.5 locally.
`skipLibCheck` is false in default, after I explicitly set it to true, 
the `joi` import error gone.

**Comment by WoH** [comment]
@JimmyBjorklund what package manager are you using?

**Comment by lgoeckener** [comment]
I am having a similar issue with the latest version 6.1.5

```
backend-1   | ../node_modules/@hapi/hapi/lib/types/route.d.ts(2,68): error TS2307: Cannot find module 'joi' or its corresponding type declarations.
backend-1   | ../node_modules/@hapi/hapi/lib/types/server/server.d.ts(4,22): error TS2307: Cannot find module 'joi' or its corresponding type declarations.
```

`skipLibCheck` is turned off, but it doesn't feel good to me, to turn that on on production level.

Using npm (v10.2.4) on arm64v8/node:20.11.1-alpine3.19 (running on M1 Pro)

**Comment by JimmyBjorklund** [comment]
> @JimmyBjorklund what package manager are you using?
npm --version
10.2.3
node --version
v20.10.0

**Comment by WoH** [comment]
> I am having a similar issue with the latest version 6.1.5
> 
> ```
> backend-1   | ../node_modules/@hapi/hapi/lib/types/route.d.ts(2,68): error TS2307: Cannot find module 'joi' or its corresponding type declarations.
> backend-1   | ../node_modules/@hapi/hapi/lib/types/server/server.d.ts(4,22): error TS2307: Cannot find module 'joi' or its corresponding type declarations.
> ```
> 
> `skipLibCheck` is turned off, but it doesn't feel good to me, to turn that on on production level.
> 
> Using npm (v10.2.4) on arm64v8/node:20.11.1-alpine3.19 (running on M1 Pro)

You can always add joi to (dev)Deps yourself. That would be a fix we can also to, but it doesn't feel great.

**Comment by WoH** [comment]
Thanks @JimmyBjorklund for opening an issue over at the hapi repo: https://github.com/hapijs/hapi/issues/4491

**Comment by JimmyBjorklund** [comment]
Still an issue

**Comment by ClementValot** [comment]
Still an issue :/

**Comment by WoH** [comment]
If someone has a good way to fix this on our side, I'll reopen. The way I see it, add joi and don't use it, just to satisfy the type checker, declare it as any, or skip checking on it.

**Comment by JosChavz** [comment]
Still an issue until I installed `joi` but should be a dependency for this library tbh.

**Comment by JimmyBjorklund** [comment]
This is still an issue, is there runtime with only express support ?
