### ISSUE TITLE
Middleware after response

### ISSUE THREAD

**Issue by SwagiWagi** [lukeautry/tsoa#1593]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
Have the ability to have middlewares of specific routes be called after response has been sent
```

```ts

```

## Current Behavior

```yaml

```

```ts

```

## Steps to Reproduce

@Route("user")
export class UserController extends Controller {
	@Middlewares(validateUserId)
	@Get("{userId}")
	async getUser(@Path() userId: string) {
		this.setStatus(200);
		return {userId: userId};
	}
}

Now I want a logging middleware to be called (for example), specifically after the response has been sent.

## Context (Environment)

Version of the library: 6.1.5
Version of NodeJS: 20.11.0

- Confirm you were using yarn not npm: Using npm

**Comment by jackey8616** [comment]
I assume you are using Express,
there is two way to archive such feature.
1. custom template and make your own handler function,
     register every route with after middleware by yourself,
     details you search StackOverflow, I believe there is some example such as `Call middleware after response sent in Express`
2. tsoa indeed can does provides such feature by including an `AfterMiddleware` decorator.
     but I doubt the necessity of it right now.

cc @WoH need your opinion.

**Comment by WoH** [comment]
(req, res, next) => {

  next()

  console.log('post')
}

Should do it, right?

**Comment by SwagiWagi** [comment]
I believe an AfterMiddleware decorator would be a great feature.
It's great for use cases such as:
1. Tracking the number of completed requests (for billing purposes for example).
2. Logging.
3. Disposing resources.

I believe it wouldn't be much work, I can make a PR for this.

**Comment by jackey8616** [comment]
> ```ts
> (req, res, next) => {
> 
>   next()
> 
>   console.log('post')
> }
> ```
> 
> Should do it, right?

https://github.com/lukeautry/tsoa/blob/efdb468a5cedcb9bef345f1eed776e8fc621b443/packages/cli/src/routeGeneration/templates/express.hbs#L92-L116

Yes, just call next() in custom template, after L106 would work with after middleware.

**Comment by ericwooley** [comment]
Hi, sorry to bring up a dead issue. Would you be willing to accept a PR that would add this as an option? Calling next() should probably be called by default, but I understand that might break things for some people. 

It took me a long time to figure out that my cleanup middleware wasn't being hit only for routes handled by tsoa. Yes I can make a custom template, but like the guide says, thats potentially brittle. 

Ideally there could be an option in the config `"callNextAfterSuccess": true`, that would be mentioned in the documentation and on be default.

**Comment by ericwooley** [comment]
Sorry to bring up a dead issue. But this doesn't appear to have been implemented. 

I'm happy to do the PR if needed, or maybe there is discussion elsewhere as to why this wasn't added?
