### ISSUE TITLE
ErrorHandlerMiddleware is ignore with 6.1.*

### ISSUE THREAD

**Issue by VincentClair** [lukeautry/tsoa#1598]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

When an error is thrown, custom ErrorHandlerMiddleware catches the error and returns a response with according errorCode (400, 403, 429, etc.). Works as expected with 6.0.*

## Current Behavior

When an error is thrown, custom ErrorHandlerMiddleware is ignore and app hangs up, nothing happens. Breaks with upgrade to 6.1.4 and 6.1.5, and routes regenerated.

## Context (Environment)

Version of the library: 6.1.*
Version of NodeJS: 20.*

- Confirm you were using yarn not npm: [ ]

## Breaking change?

It seems that is related to the new way of generated routes that handles requests.
I have passed many hours to debug, but does not find something really more helpfull. Sorry !

**Comment by VincentClair** [comment]
Code example : 

```
const app = express();
const server = http.createServer(app);

RegisterRoutes(app);

app.use((
        err: APIError,
        req: express.Request,
        res: express.Response,
        next: express.NextFunction,
    ) => {
        try {
            if (res.headersSent) {
                next(err);
                return;
            }

            res.status(err.code)
                .json({ success: false });
        } catch (e) {
            console.debug(e);
            res.status(500);
            next(e);
        }
    });

server.listen(8080, () => {
    logger.info(`Server listening on port: ${port}`);
});
```

**Comment by VincentClair** [comment]
Find the soluton : put buildPromise inside try/catch
```
    async apiHandler(params) {
        const { methodName, controller, response, validatedArgs, successStatus, next } = params;
        try {
            const promise = this.buildPromise(methodName, controller, validatedArgs);
            const data = await Promise.resolve(promise);
            let statusCode = successStatus;
            let headers;
            if (this.isController(controller)) {
                headers = controller.getHeaders();
                statusCode = controller.getStatus() || statusCode;
            }
            this.returnHandler({ response, headers, statusCode, data });
        }
        catch (error) {
            return next(error);
        }
    }
```

**Comment by jackey8616** [comment]
@VincentClair thank you for locate the missing part, could you submit a PR including test cases let tsoa  prevent such issue in the future?

**Comment by VincentClair** [comment]
@jackey8616 have you an advice how to test this case ?
I suppose it's more an integration test to put in *-server.spec.ts ?

**Comment by jackey8616** [comment]
> @jackey8616 have you an advice how to test this case ?
> 
> I suppose it's more an integration test to put in *-server.spec.ts ?

Yes, you should add one test case in express, koa, hapi integration test.

You can take fixtures/getController.ts as example, duplicate the method with throwing an error or find and add handle case in .spec.ts of 3 of that framework.

**Comment by VincentClair** [comment]
Sorry, but i haven't find a way to add a proper test and I have no more time to pass on it.

It seems the solution has to be completed: when we use inversify (and probably all other solutions ?) we have to await for apiHandler to execute, so errors could be catched and pass to next(err). Otherwise, errors could pass through tr/catch due to async code.

https://github.com/lukeautry/tsoa/blob/efdb468a5cedcb9bef345f1eed776e8fc621b443/packages/cli/src/routeGeneration/templates/express.hbs#L106

```
{{#if ../../iocModule}}async {{/if}}templateService.apiHandler({
```

**Comment by jackey8616** [comment]
> Sorry, but i haven't find a way to add a proper test and I have no more time to pass on it.
> 
> It seems the solution has to be completed: when we use inversify (and probably all other solutions ?) we have to await for apiHandler to execute, so errors could be catched and pass to next(err). Otherwise, errors could pass through tr/catch due to async code.
> 
> https://github.com/lukeautry/tsoa/blob/efdb468a5cedcb9bef345f1eed776e8fc621b443/packages/cli/src/routeGeneration/templates/express.hbs#L106
> 
> ```
> {{#if ../../iocModule}}async {{/if}}templateService.apiHandler({
> ```

Never mind, I will take rest of things, thanks for your informations.
I will submit a PR to fix this ASAP.

**Comment by jackey8616** [comment]
@VincentClair
can you provides more context, everything seems works fine with error handler.
test cases is covered with throwing error inside controller, and it can be correctly catched from outside global error handler.

**Comment by VincentClair** [comment]
Finally found the problem: if the throwing method is not async, error is neither caught by `apiHandler` nor generated template.

I have made a PR https://github.com/lukeautry/tsoa/pull/1602

**Comment by VincentClair** [comment]
@WoH When did you plan to publish the fix please ?
