### ISSUE TITLE
programmatic way to generate the spec and routes

### ISSUE THREAD

**Issue by kamit-transient** [lukeautry/tsoa#1604]
Hi,

I am trying to use the programmatic way to generate the spec and routes as I need to use env variables.

the approach mentioned in [docs here](https://tsoa-community.github.io/docs/generating.html)  is not very clear.

Would you please suggest how can generate the spec and route programmatically?

NOTE: I tried programmatically(using `ts-node tsoa.ts`) I always get the no controllers found issues however the same configurations work tsoa.json approach.

**Comment by poph2** [comment]
The `routeOptions` in the docs did not specify `controllerPathGlobs`. Try this:
```
const routeOptions: ExtendedRoutesConfig = {
        bodyCoercion: false, 
        noImplicitAdditionalProperties: "throw-on-extras",
        basePath: "/api",
        entryFile: "./api/server.ts",
        routesDir: "./api",
        controllerPathGlobs: ["./routeControllers/**/*Controller.ts"],
    };
```

**Comment by kamit-transient** [comment]
@poph2 
whatever controller glob pattern I provide, it always says zero controller found.

However, exactly the same glob pattern works with the `tsoa.json`   config file but I can not use this JSON file approach as i need to use env variables.

**Comment by luke-lacroix-healthy** [comment]
In my code, I use this:
```ts
await generateRoutes({
      authenticationModule: path.join(args.routesDir, 'authentication'),
      basePath: args.basePath,
      bodyCoercion: true,
      controllerPathGlobs: ['src/interfaces/http/**/*.controller.{ts,js}'],
      entryFile: args.entryFile,
      iocModule: path.join(args.routesDir, 'ioc'),
      noImplicitAdditionalProperties: args.noImplicitAdditionalProperties,
      routesDir: args.routesDir,
      rootSecurity: args.rootSecurity,
    });
```

The glob is relative to the `basePath` directory.

**Comment by kamit-transient** [comment]
@luke-lacroix-healthy would love to see the complete example of the above tsoa config .ts file.

Would you please share yous tsoa config?

**Comment by luke-lacroix-healthy** [comment]
@kamit-transient I don't know what you mean. There is no config file. The configuration is passed to the generateRoutes function and aside from the data, which is provided on the command line for me, that's the complete example.

**Comment by kamit-transient** [comment]
then how do you run this?

i use ts-node to run my `tsoa.ts` file. am I missing something ?

would you please share the command for example?

**Comment by kamit-transient** [comment]
here is how i am doing:

i have file named `tsoa.ts` with below content and then i use `ts-node tsoa.ts` command to run it. but it fails for me. is it the right way?

```
const {
    generateRoutes,
    generateSpec,
    ExtendedRoutesConfig,
    ExtendedSpecConfig,
} = require("tsoa");

// import {
//     generateRoutes,
//     generateSpec,
//     ExtendedRoutesConfig,
//     ExtendedSpecConfig,
// } from "tsoa";

(async () => {
    const specOptions = {
        "entryFile": "apps/project/src/app/app.ts",
        specVersion: 3,
        "outputDirectory": "./apps/project/generated/spec",
        "controllerPathGlobs": [
            "./apps/project/src/controllers/**/*controller.ts"
        ],
        "host": "http://dev.lionis.ai",
        noImplicitAdditionalProperties: "throw-on-extras",

    };


    const routeOptions = {
        "entryFile": "apps/project/src/app/app.ts",
        "routesDir": "apps/project/generated/routes",
        noImplicitAdditionalProperties: "throw-on-extras",

    };

    await generateSpec(specOptions, {
        "paths": {
            "@sharedtypes": [
                "apps/sharedtypes/index.ts"
            ]
        }
    });

    await generateRoutes(routeOptions, {
        "paths": {
            "@sharedtypes": [
                "apps/sharedtypes/index.ts"
            ]
        }
    });
})();
```

**Comment by luke-lacroix-healthy** [comment]
@kamit-transient My example shows passing the `controllerPathGlobs` to the `generateRoutes` function. You're not telling `generateRoutes` where to find your controllers so that it can output the code necessary to load them at run-time.

**Comment by kamit-transient** [comment]
is there any minimal example express.js repo, which uses this programmatic approach?

That would be helpful if any.

**Comment by joshcanhelp** [comment]
The problem here is that the `controllerPathGlobs` property is not shown on the `routeOptions` object, which is confusing. It should be:

```diff
(async () => {
+ const controllerPathGlobs = ["./routeControllers/**/*Controller.ts"];

  const specOptions: ExtendedSpecConfig = {
    basePath: "/api",
    entryFile: "./api/server.ts",
    specVersion: 3,
    outputDirectory: "./api/dist",
-   controllerPathGlobs: ["./routeControllers/**/*Controller.ts"],
+   controllerPathGlobs,
  };

  const routeOptions: ExtendedRoutesConfig = {
    basePath: "/api",
    entryFile: "./api/server.ts",
    routesDir: "./api",
+   controllerPathGlobs,
  };

  await generateSpec(specOptions);

  await generateRoutes(routeOptions);
})();
```

I don't see a repo for the docs site or I'd PR this 🤷
