### ISSUE TITLE
Custom parameters in controller

### ISSUE THREAD

**Issue by SwagiWagi** [lukeautry/tsoa#1607]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

I want to be able to have middlewares add custom parameters to my controller, for example:

```
const addCustomParamMiddleware = (req: express.Request, res: express.Response, next: nextFuncType) => {
  req.locals.tsoaCustomParams = {
    requestId: req.headers["x-request-id"]
  }

  next();
}

@middlwares(addCustomParamMiddleware)
@Get("{screenName}/details")
  public async details(@Path() screenName: string, @CustomParam("requestId") requestId: string): Promise<any> {
    //logic
  }
}

app.use(addCustomParamMiddleware);
registerRoutes(app);
```

**Comment by SwagiWagi** [comment]
up

**Comment by WoH** [comment]
If you are using decorators, you can use https://tsoa-community.github.io/reference/functions/tsoa.Inject.html

and do something like `fn(@Inject() @MyDecorator() injectedArg)`

Otherwise you can set it in the Middleware and use `@Request`

**Comment by WoH** [comment]
> Are there any examples of how to implement a custom decorator like `@MyDecorator`? I've been searching but haven't found one yet.

As in: How to write/use decorators?

https://www.typescriptlang.org/docs/handbook/decorators.html
