### ISSUE TITLE
Declare Auth schema without need to implement handlers

### ISSUE THREAD

**Issue by mishelen** [lukeautry/tsoa#1615]
## Sorting

- I'm submitting a question or possibly feature request.

  - [ ] bug report
  - [x] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Suppose I have `tsoa.json`:

```json
  "spec": {
    "outputDirectory": "src",
    "specVersion": 3,
    "securityDefinitions": {
      "AuthorizationHeader": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization"
      }
    }
  },
```

So I want to add authorization. But problem is in fact that it will currently not applied to any of endpoints when making swagger requests. To add it, I need to specify `"rootSecurity": [{ "AuthorizationHeader": []}]` and then provide `AuthorizationModule`, **while authorization is done externally via lambda auth.**

Question is how to provide authorization schema and apply globally without need to implement it?

## Context (Environment)

Version of the library: 6.2.0
Version of NodeJS: 20.12.2

**Comment by mohamedsalah2024** [comment]
@mishelen did you solve it?

**Comment by mishelen** [comment]
> @mishelen did you solve it?

yes, I just mutate swagger doc adding all security rules by hand
