### ISSUE TITLE
Make express request injectable

### ISSUE THREAD

**Issue by sourceful-mia** [lukeautry/tsoa#1616]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I am looking to get the user claims from my JWT so that I can get user id & name. I'd like to make this available everywhere as an injectable service, to avoid every controller route having to worry about passing the request down, and reduce the amount of parameters that need to go through every function.

## Possible Solution

I've tried to create a UserService where I inject the request, but it doesn't work:
```ts
import { Request } from "tsoa";
import { provide } from "inversify-binding-decorators";
import express from "express";
import { Buffer } from "buffer";

export type User = {
  id: string;
  name: string;
}

@provide(UserService)
export class UserService {
  constructor(@Request() private request: express.Request) {
  }

  async getCurrentUser(): Promise<User> {
    const authHeader = this.request.headers.authorization;
    const jwt = authHeader?.split(" ")[1];

    const claims = Buffer.from(jwt?.split(".")[1] ?? "", "base64").toString();

    return JSON.parse(claims);
  }
}
```

A couple of other ideas:
- using a middleware to preload the service and pass the header to it, but there's no way (I can find) to inject that service into my middleware.
- Make express.Request injectable, but again I'm not sure how I would go about this.

I really like tsoa and how it reduces the amount of `(req, res) => {}` functions in regular express servers, so I'm keen to avoid having to do this again with this library 😄

**Comment by midoelhawy** [comment]
Hi @sourceful-mia 

you need to define a new Request interface like :

```TS
import { Request } from 'express'
export interface baseHttpRequest extends Request {
  jwtUser?: IUser | null
  clientIp?: string
  deviceType?: string
  appVersion?: string // for andriod or IOS app version
  userAgent?: string
...
  middlewaresData?: {
    article?: IArticle // For example
  }
}

```

And next you can replce your `@Request() private request` by `@Request() private baseHttpRequest`
