### ISSUE TITLE
Add a minimal boilerplate repo to the docs. 

### ISSUE THREAD

**Issue by joel1st** [lukeautry/tsoa#1639]
## Sorting

  - [ ] bug report
  - [x] feature request
  - [ ] support request

## Detailed Description
I think we could benefit from a basic starter repo to help people quickly start a new project and try TSOA. 
Currently the docs are missing some config (eg. tsconfig.json settings) and there is a bit of debugging required to get up and running.

I'm aware that we have https://github.com/lukeautry/ts-app - but I think this is a little too involved for a starter repo.

As an example I've put together https://github.com/joel1st/tsoa-boilerplate which closely follows the guides from the docs and fills in the gaps where appropriate.

**Comment by WoH** [comment]
https://github.com/tsoa-community/starter is what the docs use for getting started

**Comment by joel1st** [comment]
Oh nice, I tried looking for this in the docs without any luck (and based off the repo activity I assume this is the case for others as well).

Have you got a link to where it is referee ced in the docs?



Sent from my Galaxy



-------- Original message --------
From: Wolfgang Hobmaier ***@***.***>
Date: 11/6/24 1:35 am (GMT+10:00)
To: lukeautry/tsoa ***@***.***>
Cc: joel1st ***@***.***>, Author ***@***.***>
Subject: Re: [lukeautry/tsoa] Add a minimal boilerplate repo to the docs. (Issue #1639)


https://github.com/tsoa-community/starter is what the docs use for getting started
