### ISSUE TITLE
Recently merged issue #1593 is a breaking change

### ISSUE THREAD

**Issue by miszczu-drako** [lukeautry/tsoa#1640]
https://github.com/lukeautry/tsoa/issues/1593 Merged 3 days ago changed behavior of express, by adding `next()`
It broke the previously established functionality that no other middleware was called if request was handled correctly by registered routes. Now, no matter what, middlewares after RegisterRoute are always called.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

From my point of view it is a breaking change. My code looks like this. The `logUnknownRoute` has been called only when a request has path not handled by RegisterRoutes. Now it is called always.

```ts
  app.use(logIncomingRequest);
  RegisterRoutes(app);
  app.use(logUnknownRoute);
  app.use(errorHandler);

```

## Possible Solution

I would ask you to make it configurable or revert the change made by #1593 

## Context (Environment)

Version of the library: 6.3.0
Version of NodeJS: v20.9.0

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
Reverted in v6.3.1

**Comment by miszczu-drako** [comment]
@WoH thanks for reacting so fast. I really appreciate it.
