### ISSUE TITLE
Accessing raw body: Stripe webhook signing

### ISSUE THREAD

**Issue by kevinroleke** [lukeautry/tsoa#1645]
My application needs to receive and verify webhook events from Stripe. This works by passing a Buffer of the raw POST request body into the Stripe client. Unfortunately, @Body() does not suffice. 

## Sorting

  - [ ] bug report
  - [X] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I should be able to do something like this
```ts
@Post('stripe-webhook')
public async stripeWebhook(@Raw() rawBody: Buffer, @Header('stripe-signature') signature: string): Promise<void> {
...
}
```

**Comment by Helloworldexampledotcom** [comment]
{
"id": 
"ccsbtxn_1Q1HxNGYzuvBwPjVKYtrMUtS",
"object": 
"customer_cash_balance_transaction",
"created": 
1726881473,
"currency": 
"usd",
"customer": 
["cus_QHns0BD0KXqgcB"](https://dashboard.stripe.com/customers/cus_QHns0BD0KXqgcB),
"ending_balance": 
1171179800,
"funded": {
"bank_transfer": {
"id": 
"ccsbtxn_1Q1HxNGYzuvBwPjVKYtrMUtS",
"reference": 
"Strut",
"type": 
"us_bank_transfer",
"us_bank_transfer": {
"id": 
"ccsbtxn_1Q1HxNGYzuvBwPjVKYtrMUtS",
"network": 
"ach",
"sender_name": 
"",
},
},
},
"livemode": 
false,
"net_amount": 
72737900,
"type": 
"funded",
}

**Comment by fabian-meisinger** [comment]
Just ran into the same issue and found that it's enough to use the express.raw middleware for the specific route, before adding the json middleware:
```ts
app.use('/stripe-webhook', express.raw({ type: '*/*', limit: '10mb' }));
app.use(json());
RegisterRoutes(app);
```
The route in the controller can then receive a Buffer like this:
```ts
    @Post('stripe-webhook')
    public async handleStripePushNotification(
        @Request() request: express.Request,
        @Body() body: Buffer
    ): Promise<void> {
        const rawBody = body.toString('utf-8');
        const signature = request.headers['stripe-signature'] as string;
        const secret = "whsec_...";
        const event = stripe.webhooks.constructEvent(rawBody, signature, secret);
    }
```
Hope this helps anyone else who's using stripe with tsoa.
