### ISSUE TITLE
Variables in service class instance are getting wiped out on each request to the controller.

### ISSUE THREAD

**Issue by vedtam** [lukeautry/tsoa#1648]
Hi Guys, 

Despite me reusing the same service instance, variables set within the service instance are gone whenever I try getting `getCrawlStatus`. Does that mean that each request uses a new instance of the controller?

```
@Route('crawler')
export class CrawlerController extends Controller {
  private crawlerService: CrawlerService;

  constructor() {
    super();
    this.crawlerService = new CrawlerService();
  }

  @Post('crawl')
  public async crawl(@Body() body: { siteId: number }): Promise<any> {
    return this.crawlerService.crawl(body.siteId);
  }

  @Get('status/{siteId}')
  public async getCrawlStatus(@Path() siteId: number): Promise<any> {
    return this.crawlerService.getCrawlStatus(siteId);
  }
}
```

If I create a global variable in the service, above the class, the data is persisted.

Thanks!

**Comment by WoH** [comment]
> Does that mean that each request uses a new instance of the controller?

Yes.
If you want to hook into this, you can provide your own iocModule, then you can return the same class instance every time.
