### ISSUE TITLE
expressAuthenticationRecasted functions is undefined in generated routes

### ISSUE THREAD

**Issue by skitscha** [lukeautry/tsoa#1655]
## Sorting

- **I'm submitting a ...**

  - [ x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [ X ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I expect that in the following code snippets, tsoa will properly enforce the security header that is defined in the swagger.json.

```ts
 securityDefinitions: {
      api_key: {
        type: "apiKey",
        name: "apikey",
        in: "header",
      },
    },
```
```ts
import { Controller, Get, Route, Security } from "tsoa";
import os from "os";
import { HealthResponse } from "types/health";

@Route("health")
@Security("apiKey")
export class HealthController extends Controller {
  /**
   * Returns health of the service. Used to determine whether a deployment is healthy.
   */
  @Get()
  public async getHealth(): Promise<HealthResponse> {
    return {
      nodeHost: os.hostname(),
      gitSha: process.env.GIT_COMMIT,
    };
  }
}

```

## Current Behavior

Tsoa errors while attempting to build and generate swagger for this code.

```
error TS2304: Cannot find name 'expressAuthenticationRecasted'.

198                             expressAuthenticationRecasted(request, name, secMethod[name], response)
```
![image](https://github.com/user-attachments/assets/35815918-f0b5-46ef-b8a4-87c2ec0db9ad)

## Possible Solution

You can see this error by copying the provided code blocks.

## Steps to Reproduce
1. Create a project with a apiKey security definition in the tsoa config file
2. Use that security definition on a controller
3. Attempt to build the api

## Context (Environment)

Version of the library: 6.4.0
Version of NodeJS: 20.15.1

- Confirm you were using yarn not npm: [ x ]

## Detailed Description

N.A

**Comment by s00d** [comment]
hello, need authenticationModule - https://tsoa-community.github.io/docs/authentication.html#authentication
