### ISSUE TITLE
Support @title keyword annotation

### ISSUE THREAD

**Issue by DominykasValutis** [lukeautry/tsoa#1656]
Would it be possible to add support for `title` annotation, which is supported keyword in Ope

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues)

The same request has been made (and closed) [#1633](https://github.com/lukeautry/tsoa/issues/1633), but it was not implemented.

## Current Behavior

No support for `title` keyword annotation.

## Possible Solution

Add `title` to `validatorUtils.ts` as a string value.

## Context (Environment)

Version of the library: 6.3.1
Version of NodeJS: 20.11.1

- Confirm you were using yarn not npm: [x]

## Detailed Description

This would allow to generate OpenAPI spec with title keyword in schema reference.

## Breaking change?

No breaking changes.

**Comment by stskrp** [comment]
Hello, any plans when this [PR](https://github.com/lukeautry/tsoa/pull/1657) can be merged?
This is actual for our team too
