### ISSUE TITLE
Issues with Validation of intersection of object and string

### ISSUE THREAD

**Issue by sinomsinom** [lukeautry/tsoa#1661]
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

I'm using a somewhat esoteric type in my code:
```ts
type TypedId<T> = ObjectId & {__type?:T}
```
Where ObjectId is basically just a string and tsoa correctly recognizes ObjectId as an alias for string.
The intersection with `{__type:T}` is completely unused in the actual code and only there so typescript doesn't erase the generic when passing variables of this type around, which helps with type-safety and automatic type inference when passing around ObjectIds that refer to objects of a specific type.
The issue comes up when then trying to make a request to an endpoint that expects a field of this TypedId type, since it doesn't accept plain strings and throws an error.

## Expected Behavior

Validation should allow fields of an intersection of string with a potentially empty object to be just a string.

## Current Behavior

The validation throws an error when passing in just a string

**Comment by WoH** [comment]
While this is a TS hack that works by casting, it's imo not a good basis for validation types. Not a bug imo
