### ISSUE TITLE
relative import path (modulePath) should contain .js extension 

### ISSUE THREAD

**Issue by christophe-g** [lukeautry/tsoa#1668]
Ideally relative Import path should contain the `.js` extension in the auto-generated `routes.js` file. 

This would avoid  an `[ERR_MODULE_NOT_FOUND]` errors in context not allowing extensionless module reference.   

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior

Generated code fail to run in some restricted context. 

## Expected Behavior

Auto-generated `routes.js` is always able to load imported modules

## Possible Solution

- Run a post generation script to add missing `.js` extension. For instance, https://www.npmjs.com/package/fix-tsc-es-imports. 

- Add `.js` in [`import { {{name}} } from '{{modulePath}}.js';` templates]( https://github.com/lukeautry/tsoa/blob/d573d6fa4303b5c4236e06fac722bf3934b85359/packages/cli/src/routeGeneration/templates/express.hbs#L7) -

I can propose a PR i that make sense

**Comment by mhammerc** [comment]
Hello,

By reading the configuration file documentation: https://github.com/lukeautry/tsoa/blob/master/packages/runtime/src/config.ts

I found that you can set
```jsonc
// tsoa.json
"routes": {
  "esm": true
}
```

The `.js` will be added automatically in the `routes.ts` file.
