### ISSUE TITLE
Bug in Swagger.json Generator

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#167]
The swagger.json generator may create invalid swagger file.

I am currently using swagger-parser (https://github.com/BigstickCarpet/swagger-parser) to validate the swagger.json files.

In rare circumstances a wrong parameter section is created:

```
   @Security('jwt')
   @Post('save')
   public async save( @Request() req: any, @Body() whatever: Whatever[]): Promise<boolean> {
      return await this.svc.save(<JwtData>req.user, whatever);
   }
```

The part in the swagger file is

```
"parameters": [
   {
      "in": "body",
      "name": "prices",
      "required": true,
      "type": "array",
      "items": {
         "$ref": "#/definitions/Whatever"
      }
   }
]
```

According to the documentation, a body requires a schema and no items.

```
"parameters": [
   {
      "in": "body",
      "name": "prices",
      "required": true,
      "type": "array",
      "schema": {
         "$ref": "#/definitions/Whatever"
      }
   }
]
```

**Comment by dgreene1** [comment]
I believe this was fixed in https://github.com/lukeautry/tsoa/commit/d27126d326265e68fc7a003e0b1eb0bdea5e63ec. If it's still reproduce-able, we can reopen.
