### ISSUE TITLE
@Tags decorator can only be used for functions

### ISSUE THREAD

**Issue by maxuai** [lukeautry/tsoa#1705]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

`@Tags` decorator is allowed for classes and functions, see the [docuemntation](https://tsoa-community.github.io/docs/decorators.html#tags)

## Current Behavior

`@Tags` decorator is only allowed for functions

## Possible Solution

add `ClassDecorator` to the returned types

## Context (Environment)

Version of the library: 6.5.0
Version of NodeJS: 20.12.2

- Confirm you were using yarn not npm: [x]

## Detailed Description

seems like the decorator have been refactored but the `@Tags` decorator was restricted to be only used for functions

## Breaking change?
https://github.com/lukeautry/tsoa/commit/d14174662de2fa23f01e7e3f0934ab622cb62b51

**Comment by jackey8616** [comment]
#1702 fixes this.
