### ISSUE TITLE
Support TypeScript 5.7 "rewriteRelativeImportExtensions" option

### ISSUE THREAD

**Issue by Azlond** [lukeautry/tsoa#1714]
[TypeScript 5.7](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7-beta/#path-rewriting-for-relative-paths) will support a new compilerOption called "rewriteRelativeImportExtensions", which allows importing `.ts` extensions for relative paths.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Allow for a config option in `tsoa.json` to have tsoa output `.ts` imports in routes.ts.

```ts
// should create the following import in routes.ts when rewriteRelativeImportExtensions is enabled
import { UserController } from './../src/controllers/userController.ts';
```

## Current Behavior

`npx tsoa spec-and-routes` creates the following `routes.ts`:
```ts
import { UserController } from './../src/controllers/userController.js';
--------------------------------^
// This relative import path is unsafe to rewrite because it looks like a file name, but actually resolves to "../src/controllers/userController.ts".

```

## Possible Solution

Allow for a `rewriteRelativeImportExtensions`-tsoa-config option, which would not rewrite the `.ts`-extensions to `.js`.

Or read the `tsconfig.json` used in the project and determine the `rewriteRelativeImportExtensions` setting.

## Steps to Reproduce

1. Install TypeScript 5.7 beta
2. enable `rewriteRelativeImportExtensions` in `tsconfig.json` compilerOptions
3. use tsoa

## Context (Environment)

Version of the library: tsoa@6.2.1
Version of NodeJS: 20

- Confirm you were using yarn not npm: [X]

## Detailed Description

Allow for a config option e.g. called `rewriteRelativeImportExtensions`, which supports the new TypeScript 5.7 feature `rewriteRelativeImportExtensions`

## Breaking change?

None

**Comment by WoH** [comment]
What's the advantage over `esm: true`, which already creates `.js`?

**Comment by Azlond** [comment]
I can't see the comment for which I received an email, so I'll just reply to this issue in general.
There's no advantage over ` esm: true`, as it's a different use case. `rewriteRelativeImportExtensions` allows to import `.ts` files, so that TypeScript-runtimes without build/transpile-step can correctly handle the file resolution.

You can see an example in the beta announcement I linked in my first message.
