### ISSUE TITLE
boolean | null auto translates to false ? 

### ISSUE THREAD

**Issue by JimmyBjorklund** [lukeautry/tsoa#1720]
Hi 
Have an update request that looks like this 
```
interface UpdateRequest {
  u: boolean | null
}

@Put("g/{id}")
async updateU(id: string, @Body() body: UpdateRequest ): Promise<void> {
   console.log("update", body);
}
```
When trying to pass null to the variable u it auto translates to false instead of null that one would expect.
Is this expected? 
/Jimmy

**Comment by JimmyBjorklund** [comment]
Found another strang thing if i set 
`
u: "null" | boolean;
`
Then passing both null and "null" seems to work, this seams wrong if i set a string "null" then null should not work ?

**Comment by ajball** [comment]
Ran into the same bug. My workaround:

```
// tsoa.json
{
  ...
  "routes": {
     ...
    "bodyCoercion": false
  }
}
```
