### ISSUE TITLE
Global error handling using tsoa annotations

### ISSUE THREAD

**Issue by doshprompt** [lukeautry/tsoa#174]
I am trying to setup something similar to what is shown in the README but am unable to find the right way to import some of the annotations:

```js
@Response('400', 'Bad request')
@DefaultResponse<ErrorResponse>('Unexpected error')
@Get('Response')
public async getResponse(): Promise<TestModel> {
    return new ModelService().getModel();
}
```

I am unable to import `@DefaultResponse` and `@ErrorResponse` could you please provide a full/more concrete example? Ideally, it would be nice to send the error thrown by validateArgs in case a required param is missing

**Comment by alfetch** [comment]
Having same issue.. Any ideas?

**Comment by endor** [comment]
The documentation is out of date here. Check `tests/fixtures/controllers/securityController.ts` on how to use `Response` and an `ErrorResponseModel`.
