### ISSUE TITLE
global tags configuration 

### ISSUE THREAD

**Issue by crazyx13th** [lukeautry/tsoa#176]
Hi there, 

we need sonthing like this - to define the tags - inside the root of the swagger.json

![grafik](https://user-images.githubusercontent.com/8912561/33219113-e58f1052-d140-11e7-84be-e229617edfef.png)

Thx!

Greetings
crazyx13th

**Comment by 0v3rst33r** [comment]
```
@Route('some_route')
@Tags('pet')
@injectable()
export class PetController { // or whatever you want to call your Controller of course
```
Can ignore the `@injectable()`, I am using `inversify`.

Just do the other `@Tags` on your other controllers for `store` and `user`.

**Comment by crazyx13th** [comment]
but is no global setting, right? how can I add the description fo example? thx
