### ISSUE TITLE
OpenAPI 3.x?

### ISSUE THREAD

**Issue by chadbr** [lukeautry/tsoa#178]
Any plans to support 3.x (sorry - just getting started here; I'm not even sure what it means vs. 2.x)

Thanks - Chad

**Comment by cKhoff** [comment]
any updates on this ?

**Comment by dgreene1** [comment]
It's available now thanks to PR https://github.com/lukeautry/tsoa/pull/249. Set specVersion to the number 3 in tsoa.json to start outputting OpenAPI 3.
