### ISSUE TITLE
Reverse TypeScript

### ISSUE THREAD

**Issue by WORMSS** [lukeautry/tsoa#179]
Hello, I am prob looking in the wrong place for this, but I am looking for the opposite of what this package does.

I have a json swagger of an API, and looking to make controllers and models for using the API. (Hopefully TypeScript, but not a concrete requirement)

Google has been very difficult because all results I have found are talking about making the swagger output from the controllers and models such as this package.

Any help from the community would be greatful.

**Comment by artemyarulin** [comment]
https://github.com/swagger-api/swagger-codegen does exactly that

**Comment by lukeautry** [comment]
Closing, out of scope of this project but link above should get you what you need.
