### ISSUE TITLE
Turn off request payloads validation

### ISSUE THREAD

**Issue by jakubzloczewski** [lukeautry/tsoa#181]
Hi, first of all thanks for really great library.

Is there any way to turn off request payload validation? I would like to have more control around this and handle validation by myself.

Best, 
Jakub

**Comment by jakubzloczewski** [comment]
After short investigation I found that it should be possible by adding something like that:

{{#if !disableValidation}} ... {{/if}} to remove getValidatedArgs declaration and call
in
tsoa/src/routeGeneration/templates/express.ts
tsoa/src/routeGeneration/templates/hapi.ts
tsoa/src/routeGeneration/templates/koa.ts

@lukeautry, let me know what do you think about this.

**Comment by egandro** [comment]
I was thinking about this, too.

What you really want is s custom error when the problem occures.

E.g. maxLength 20 -> you want a custom error for this.

Maybe we can do this with jsdoc?

**Comment by lukeautry** [comment]
Maybe this can be handled with validators, but in your case @jakubzloczewski , it sounds like you should want to completely skip validation. I think that's a reasonable use case.

**Comment by jakubzloczewski** [comment]
Ahhh, I forgot to say something about my walk around.

- In order to skip validation at all I added [custom template](https://github.com/lukeautry/tsoa#override-route-template) for my express application
- I'm throwing my custom schema validation errors
- I added to express global error handler which maps different [types of errors](https://www.npmjs.com/package/make-error) to suitable http statuses and responses

At this point I don't have errors well documented in swagger file but it is sufficient for me. I guess it could be done somehow with [@DefaultResponse](https://github.com/lukeautry/tsoa#specify-error-response-types-for-swagger) decorator.

@egandro you can achieve this with turning off validation and validate request body with [Joi](https://www.npmjs.com/package/joi). You have to keep in sync Joi schemas with types of request objects - It's not perfect but in works.

**Comment by egandro** [comment]
So what you want is not "no validation". 

What you want are custom errors :) Thats's a whole different story!

Yes - I love this idea - but ... it should be possible to have internationalisation - and this is related to the JWT / Security system (which is application dependant).

So we should make this customizable.

**Comment by dgreene1** [comment]
@jakubzloczewski since your [custom template](https://github.com/lukeautry/tsoa#override-route-template) is working for you, I'm going to close this issue. If someone else would like this feature, they're welcome to comment again and we can consider reopening the issue. But to be honest, having the validation is most of the reason why tsoa exists. So to turn off the validation seems rather strange.

**Comment by amdave** [comment]
@dgreene1 @egandro mind if we reopen this? I'll explain my use case.

I use [Zod](https://github.com/colinhacks/zod) for validation. It's a bit more robust than tsoa's validation, and the methods in our service layer aren't always called through an API. Sometimes they handle pub/sub messages, are run from scripts, or are invoked by other systems that bypass the REST endpoint.

I'd like to avoid handling two types of validation errors, and just disable tsoa for these APIs.

Please let me know what you think. Thanks.

**Comment by amdave** [comment]
I'd like to keep using tsoa annotations because they provide excellent API documentation. Just without the validation.

**Comment by meyraa** [comment]
I would like to have the tsoa validation for almost every API except for a few, where I need more complex validation, with a lot of exceptions. In those cases, I would like to disable them. Is this possible?

**Comment by WoH** [comment]
One of our goals to have the docs, types and the validation be as close as possible. Therefore, the easiest approach here would be to type the body (?) as unknown or the most generic type that makes sense and take it from there. This way, validation is basically a no-op.

**Comment by meyraa** [comment]
But with unknown/generic type, you also have no or wrong documentation. But we use tosa for that great feature to generate API doc with the interfaces.

We have in some cases strict validations before save that will check for multiple things like: 
- Is an ID set (tsoa will find this)
- Is the given ID valid
- Is a given property unique
- Are there at least 3 elements in an array for every type
- Did the user send a date for a boolean type attribute
- ...

This validation gets used by multiple APIs. If this validation fails the user will get all error messages at once, so he knows what went wrong. 
> Missing Attribute ID in Stylerule "Blue Area"
> Wrong Datatype for Filter in Stylerule "Blue Area"
> Invalid Attribute with ID 5 in Stylerule "Red Area"
> ...

Right now we have three options:
- Making the ID optional --> which will generate the wrong API documentation. ID is not optional.
- Sending the user an error message just for the ID (with tsoa) and later validating the rest and sending her the other errors --> which isn't user-friendly.
- Remove tsoa validation completely --> many other API's use them and we would need to add a validation there.

For our use case it would be enough to have a decorator `@NoValidation` you can add if you don't want to have an API validated.

**Comment by tcd** [comment]
Can I ask why this was closed? 
I wasn't able to find any solution in this issue for disabling validation.

**Comment by WoH** [comment]
Didn't align really well for me to take a look, I'd rather handle the Validation Errors to return error messages in line with the domain logic in the example provided as rationale. Would you like to work on this?

**Comment by spik3r** [comment]
Like some of the other comments I'm using zod to handle my validation since it allows for more control & flexibility than just the types. 

**It's a hack** but in case it helps someone else who just wants to disable tsoa validation I used the following in my `server.ts` before calling `RegisterRoutes(app)`

`
ValidationService.prototype.ValidateParam = (
  property,
  rawValue,
  name = '',
  fieldErrors,
  parent = '',
  minimalSwaggerConfig
) => rawValue;

RegisterRoutes.prototype.getValidatedArgs = (
  args: any,
  request: any,
  response: any
) => Object.keys(args);
`

**Comment by vbelius** [comment]
I would also like to disable validation. Simply a decorator that can achieve this per endpoint would be great.

**Comment by WoH** [comment]
See either the previous comment, use a custom template or a custom route generator if need be.

**Comment by Ivan-Shesterkin** [comment]
TSOA is a great library with a cool philosophy. However, there are a few things that can't be achieved with it currently:

Using the same variable to customize the text of multiple errors isn't possible.
Customizing error text for inevitable validation failures, like providing a specific error message for enum mismatches, is not straightforward.
Extending checks flexibly can be challenging. For instance, you've set a base pattern validation for English letters in a primary text interface, but you want to add different length constraints for various object fields. Some specialized validation libraries handle this more effectively.
It would be preferable, for instance, to have a configuration option in the spirit of "isValidationEnabled" with a default value of true. This would allow for toggling validation on or off. Many libraries let you create an interface based on a schema. This interface, formed from the schema, could be conveniently used as an interface in controllers decorators like `@Body`, `@Queries`.
