### ISSUE TITLE
Path Variables in @Route()

### ISSUE THREAD

**Issue by jpbernius** [lukeautry/tsoa#182]
Is it possible to somehow use Path Variable in `@Route()` Decorator.

What I want to do:
```
@Route("A/{id}/B")
@injectable()
export class BController extends Controller {

    @Get()
    public async get(id: string): Promise<any> {
        return await {};
    }
}
```

This leads to the following error:
```
$ tsoa swagger
Generate swagger error.
 Error: @Path('id') Can't match in URL: ''. 
```

What I currently need to do:
```
@Route()
@injectable()
export class BController extends Controller {

    @Get("A/{id}/B")
    public async get(id: string): Promise<any> {
        return await {};
    }
}
```

**Comment by egandro** [comment]
Yeah we should fix.

**Comment by jamestharpe** [comment]
Has any progress been made on this? Or have there been any elegant workarounds identified?

**Comment by candyapplecorn** [comment]
Just discovered this bug today. Still doesn't work.

**Comment by dgreene1** [comment]
Isn't this the workaround?
```ts
@Route()
@injectable()
export class BController extends Controller {

    @Get("A/{id}/B")
    public async get(id: string): Promise<any> {
        return await {};
    }
}
```

**Comment by vinniimiranda** [comment]
> Isn't this the workaround?
> 
> ```ts
> @Route()
> @injectable()
> export class BController extends Controller {
> 
>     @Get("A/{id}/B")
>     public async get(id: string): Promise<any> {
>         return await {};
>     }
> }
> ```

This is a workaround, but when you go to swagger UI it's doesn't work propely. 
This feature would be nice to have, and we will stick to REST.

**Comment by dgreene1** [comment]
@vinniimiranda I’ve updated the workaround. You have to have something in the route tag. I use this particular approach in my own project and it works fine in Swagger UI.

**Comment by vinniimiranda** [comment]
I have, here's.
![image](https://user-images.githubusercontent.com/33462844/62941148-c09bbd00-bdab-11e9-936d-7bb448d9d2be.png)

But i also have another controller like this: 
![image](https://user-images.githubusercontent.com/33462844/62941250-fccf1d80-bdab-11e9-8b2a-04602eb117b4.png)

When a click on /exams/{id}/notes he opens up both above.

**Comment by dgreene1** [comment]
@vinniimiranda that’s because they share the same value in @Tags. If you change that then swagger UI will update to what you’re expecting.

**Comment by vinniimiranda** [comment]
I realize that, but both belongs to Exams. Anyways, this path variable would save a lot of time.
