### ISSUE TITLE
Not unique operation id in generated swagger.json file

### ISSUE THREAD

**Issue by mengyiyuan** [lukeautry/tsoa#183]
Hello,

I have been using tsoa v2.0.1 to generate the swagger.json file with `./node_modules/.bin/tsoa swagger`, but encountered this semantic error "Operations must have unique operationIds." when I checked the json file against the v2 OpenAPI specification.

When I checked the generated swagger file, it seems that the operation id is set to be the method name in controllers. For example, I have 3 controller classes each with a method called createMultiple, then I ended up with 3 same operation id of "createMultiple".

I searched the issues and found the pull request https://github.com/lukeautry/tsoa/pull/87 which was already merged into master, but I did not see the behaviour of the operation id being {ControllerName}{MethodName} or even the old behaviour ({ControllerName}-{MethodName}) as described in the pull request. 

May I know what I have missed? Any help is appreciated, thanks!

**Comment by dgreene1** [comment]
I suspect that at the time @mengyiyuan tried this, PR #87 was merged but not deployed. It was deployed a long time ago, and I don’t believe that this is an issue anymore.

**Comment by picturelink** [comment]
Just so others don't fall into the same trap as myself, #87 (09 April 2017) was reverted by 
#0352cfe2 on 22nd October 2017. So the current behaviour is in fact as @mengyiyuan  described.

**Comment by Dancia** [comment]
Why was it reverted? Ran into the same issue.

**Comment by jbhurruth** [comment]
Just hit this issue too. Can we reopen this?
