### ISSUE TITLE
Ignore model types that are not used in swagger

### ISSUE THREAD

**Issue by AmazingTurtle** [lukeautry/tsoa#184]
I have many types floating around because I use definetely typed. As of now, tsoa only allows to name types that are *globally* unused. Consider having `@types/elasticsearch` installed for example. I don't use `CreateDocumentResponse` in any of my controllers. The elasticsearch typings exposes all the typings globally, therefore these are available. However I'm not using these for my controller. 

A better solution would be to lookup existing models __that are actually in use__ by controllers already.

Please fix this to avoid confusion.

```
Multiple matching models found for referenced type CreateDocumentResponse; please make model names unique. Conflicts found: "...root/node_modules/@types/elasticsearch/index.d.ts"; "...root/src/models/api/createDocumentResponse.ts".
```

**Comment by lukeautry** [comment]
See the @tsoaModel feature (new): https://github.com/lukeautry/tsoa#dealing-with-duplicate-model-names
