### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by taicho** [lukeautry/tsoa#187]
@lukeautry First and foremost I want to say I love the idea behind this framework / library. That being said, it would be nice to see some form of extensibility added beyond the templates. I'm really torn - I want to use this library on a substantial project but I'm concerned that time will be consumed trying to accommodate some inadequacies present.

Obviously, the simple answer could be "just fork it" and make the changes necessary...although looking at the stack of PRs it's obvious that you aren't able to devote as much time to this project as much as you'd like (which I totally understand).

Nevertheless, I have a couple humble suggestions as to what would make this library more viable and help gain adoption in addition to reducing maintenance:

- Add support for an @Custom decorator e.g. @Custom(name: String, value : any);
- Add support for the ability to specify a handler in tsoa.json associated with a name provided in an @Custom attribute that points to js/ts file containing the inputs/output required by tsoa for the swagger-gen and swagger-routes stage...

Anyways...many ways obviously to slice this cake and this may not be the best one but the point is that it would go along way towards making this library a staple in Node-TypeScript-Swagger development and projects if the emphasis was shifted towards extensibility. If this doesn't occur I may attempt to do the same but it seems like a really great opportunity to push your library further if that's your desire...

Cheers

**Comment by karpoff** [comment]
agree about custom decorators
for example I'm using authorization middleware and I want to pass user object to controller handle
now I can use
```
    @Get('some')
    public async getSome(@Request() request: express.Request): Promise<any> {
        return myHandler(request.user);
    }
```

but I want to use
```
    @Get('some')
    public async getSome(@User() user: IMyUserInterface): Promise<any> {
        return myHandler(user);
    }
```
and then change route template to pass request.user into controller method
it is more user-friendly

**Comment by lukeautry** [comment]
@taicho Thanks for the note. As you've pointed out, there's quite a stack of issues and pull requests around this library. However, it is not abandonware.

The good news is that I now personally depend on tsoa in production and therefore have more skin in the game to improve this library than ever. I will have more time to devote towards improving this library in the near future, and I think there are several steps we can take with regard to extensibility that makes this lib a true "staple".

**Comment by Thavaprakash** [comment]
Hi @lukeautry, Can you integrate Webpack(ts-loader) instead of `tsc` in this project as webpack has many features.

**Comment by lukeautry** [comment]
I doubt we'd want to use Webpack on this since it's a purely server-side library. What kind of webpack features would you be likely to use?

**Comment by dgreene1** [comment]
I’m also a maintainer, so @taicho you can cc me on any enhancements you’d like to make. I just solved or closed 20 issues today. So if you want to make a new issue for a specifically proposed enhancement, we’re all ears. :)
