### ISSUE TITLE
operationId Question

### ISSUE THREAD

**Issue by taicho** [lukeautry/tsoa#188]
I'm making some adjustments locally to use tsoa in conjunction with swagger-tools. I was just curious, what was the reasoning behind not just making the operationId that is generated for each route in the swagger file not just match the method name(s) in the controller(s) exactly rather than automatically uppercase the first character as it does currently?

**Comment by taicho** [comment]
To be clear I have a workaround for my purposes but still, I was curious as to the reasoning behind this logic.

**Comment by egandro** [comment]
I also didn't like the idea that in 2.x the Name of the Controller is no longer present in the OperiationId.

We should make this more flexible.

**Comment by lukeautry** [comment]
I think there probably should be an @OperationId decorator that overrides any 'inferred' operationId

**Comment by redlock** [comment]
I've created a pull request that adds OperationId() decorator #273

**Comment by lukeautry** [comment]
Fixed with #277

**Comment by StingyJack** [comment]
I dont mean to necro this post but I think the point was that if there are two controllers like this

``` ts
@route('routeA')
export class ControllerA {
  @post("activate")
  public async activate() {
etc...


@route('routeB')
export class ControllerB {
  @post("activate")
  public async activate() {
etc...

```
... that tsoa should not generate an invalid OAS file that has duplicate operationID's of "activate", but rather should generate operationId's like "routeA_activate" and "routeB_activate" without having to specify any additional decorators.

**Comment by WoH** [comment]
You can do that via `config.operationIdTemplate`.
