### ISSUE TITLE
HTML Resonse

### ISSUE THREAD

**Issue by alekseymakhankov** [lukeautry/tsoa#194]
Hello, how I can change Error response from html type to json custom type?

**Comment by AmazingTurtle** [comment]
The default response type is json already. Can you please clarify your intents?

**Comment by alekseymakhankov** [comment]
@AmazingTurtle if I got some error then tsoa returns html reponse with error message

**Comment by AmazingTurtle** [comment]
Oh, I recommend using a middleware after registering routes. 
Check my gist: https://gist.github.com/AmazingTurtle/f15c0aa33aba7a222b96903ff310f590

**Comment by alekseymakhankov** [comment]
@AmazingTurtle Thanks!

**Comment by dgreene1** [comment]
Housekeeping
