### ISSUE TITLE
Raw boolean value false cannot be returned as response

### ISSUE THREAD

**Issue by andreasrueedlinger** [lukeautry/tsoa#197]
If you define a route to return a boolean and a value of `false` is returned, it gets "swallowed" by the templates and "NO_CONTENT" (204) is returned instead:
https://github.com/lukeautry/tsoa/blob/977b535ea22e198f61f5918b82017086c21837bb/src/routeGeneration/templates/express.ts#L112

A better check that data is reall null or undefined would fix the problem.

**Comment by andreasrueedlinger** [comment]
@lukeautry do you intend to change this? It would be quite an easy and small fix I guess

**Comment by lukeautry** [comment]
Yeah, I've actually run into this problem myself. Should be an easy one to fix. Feel free to take a stab at it as well if you have time.

**Comment by jamestharpe** [comment]
I gave it a try. Please have a look! https://github.com/lukeautry/tsoa/pull/233

**Comment by dgreene1** [comment]
Fixed in https://github.com/lukeautry/tsoa/pull/233
