### ISSUE TITLE
Security definitions

### ISSUE THREAD

**Issue by andrii-z4i** [lukeautry/tsoa#20]
Currently tsoa doesn't provide mechanism to set security decorators for methods in controller. It would be useful to extend library with such decorators. 
My expectation is that developer could set up decorator in next way
`
@Route("users")
export class Index {
    constructor() {
    }`

```
`@Get()
@Oauth2Security({enabled: true, scope: ['read', 'write']})
public async Get(userId: string): Promise<UserData> {
    return findUser;
}
```

`

**Comment by lukeautry** [comment]
@andrii-z4i Thanks for the feedback - I think you're right, this is an important thing to support.

I actually need this for one of my own projects, so expect to see some updates in the near future.

**Comment by lukeautry** [comment]
@andrii-z4i Do you believe this issue is adequately handled by the new configuration method introduced in 1.0.0?

**Comment by andrii-z4i** [comment]
@lukeautry Could you please point me out to the commit which you referring to, talking about configuration method? I've checked latest commits and something more or less related to that is `a`) my changes regarding `JWT` token support and `b`) your changes around splitting configuration files and having there some kind of  [oauth support](https://github.com/lukeautry/tsoa/commit/c2faf25f54d779fdb1cc7f423993231c37bbc920). If it is `b` then, to be honest, I didn't try it yet. 
I noticed that swagger.json generated by version 1.0.0 has validation errors and they are related to `tsoa_auth` and `api_key` fields. [Validation error example](https://online.swagger.io/validator/debug?url=https://z4inode.tk/swagger.json).

**Comment by egandro** [comment]
I love the idea of security attributes.

I suggest adding more levels of abstractions to that - e.g. applying stuff to the whole
controller and inherit it to methods. In asp.net there is

[Authorize]
public class AdminController : Controller
{
    . . .
}
or even
[Authorize(Roles="Administrators")]
public class AdminController : Controller
{
    . . .
}

Reference: https://msdn.microsoft.com/en-us/library/system.web.mvc.authorizeattribute(v=vs.118).aspx

**Comment by lukeautry** [comment]
@andrii-z4i @egandro There's now support for security/authentication decorators in 1.0.18. See the updated readme for documentation.
