### ISSUE TITLE
Pattern validation cuts off pattern string from '@' symbol, if pattern includes it

### ISSUE THREAD

**Issue by nemes1s** [lukeautry/tsoa#203]
Hello,

I have a pattern for website name matching like this:

`/**
   *  @pattern [-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)
   */
  website: string`

After build process, what actually is put to model is:

https://gyazo.com/73e0f0f812af48a43e71dadf20277f9f

I guess, everything after first occurrence of '@' symbol is cut off during compilation.

**Comment by AmazingTurtle** [comment]
Already known, https://github.com/lukeautry/tsoa/issues/162
