### ISSUE TITLE
trying to generate swagger and routes is not working sometimes

### ISSUE THREAD

**Issue by adithya421** [lukeautry/tsoa#206]
I am trying to generate swagger from tsoa by following commands, but it's not working sometimes when i am creating a new controller . its only generating/override by default route and swagger.json code. please fix it

commands:
tsoa swagger
tsoa routes

default swagger.json
{
	"basePath": "",
	"consumes": [
		"application/json"
	],
	"definitions": {},
	"info": {
		"title": "meetingRestApi",
		"version": "1.0.0",
		"license": {
			"name": "MIT"
		}
	},
	"paths": {},
	"produces": [
		"application/json"
	],
	"swagger": "2.0",
	"securityDefinitions": {}
}

default router

/* tslint:disable */
import { Controller, ValidateParam, FieldErrors, ValidateError, TsoaRoute } from 'tsoa';
import { LoginController } from './controllers/LoginController';
import { CustomerController } from './controllers/customerController';
import { VoteController } from './controllers/voteController';
import { CommitteeContoller } from './controllers/CommitteeContoller';

const models: TsoaRoute.Models = {
    "LoginResponse": {
        "properties": {
            "id": { "dataType": "string" },
            "user_id": { "dataType": "string" },
            "user_name": { "dataType": "string" },
            "email_id": { "dataType": "string" },
            "token": { "dataType": "string" },
            "last_sync": { "dataType": "string" },
            "customer_id": { "dataType": "string" },
            "customer_name": { "dataType": "string" },
            "committee_id": { "dataType": "string" },
            "committee_name": { "dataType": "string" },
            "board_type": { "dataType": "string" },
        },
    },
    "Login": {
        "properties": {
            "orgid": { "dataType": "string" },
            "result": { "dataType": "string" },
        },
    },
    "LoginRequest": {
        "properties": {
            "userId": { "dataType": "string", "required": true },
            "pass": { "dataType": "string", "required": true },
            "loginBean": { "dataType": "array", "array": { "ref": "Login" } },
        },
    },
    "Customer": {
        "properties": {
            "id": { "dataType": "string", "required": true },
            "customer_name": { "dataType": "string", "required": true },
            "login_id": { "dataType": "string", "required": true },
            "contact_name": { "dataType": "string", "required": true },
            "email_id": { "dataType": "string", "required": true },
            "customer_mb_no": { "dataType": "string", "required": true },
            "subcription_date": { "dataType": "string", "required": true },
            "street_name": { "dataType": "string", "required": true },
            "po_box_no": { "dataType": "string", "required": true },
            "city": { "dataType": "string", "required": true },
            "country": { "dataType": "string", "required": true },
            "lat": { "dataType": "string", "required": true },
            "lon": { "dataType": "string", "required": true },
            "status": { "dataType": "string", "required": true },
            "created_on": { "dataType": "string", "required": true },
            "updated_on": { "dataType": "string", "required": true },
            "remarks": { "dataType": "string", "required": true },
            "mdm": { "dataType": "string", "required": true },
        },
    },
    "CustomerResponse": {
        "properties": {
            "customers": { "dataType": "array", "array": { "ref": "Customer" }, "required": true },
        },
    },
    "GenericResponse": {
        "properties": {
            "status": { "dataType": "string", "required": true },
            "messageEn": { "dataType": "string", "required": true },
            "messageAr": { "dataType": "string", "required": true },
        },
    },
    "UserResponse": {
        "properties": {
            "id": { "dataType": "string", "required": true },
            "userId": { "dataType": "string", "required": true },
            "username": { "dataType": "string", "required": true },
        },
    },
    "VoteResponse": {
        "properties": {
            "id": { "dataType": "string", "required": true },
            "votetype": { "dataType": "string", "required": true },
            "comment": { "dataType": "string", "required": true },
            "createdOn": { "dataType": "string", "required": true },
            "updatedOn": { "dataType": "string", "required": true },
            "status": { "dataType": "string", "required": true },
            "syncid": { "dataType": "string", "required": true },
            "user": { "ref": "UserResponse", "required": true },
        },
    },
    "VoteRequest": {
        "properties": {
            "votetype": { "dataType": "string" },
            "comment": { "dataType": "string" },
            "userId": { "dataType": "string" },
            "resolutionId": { "dataType": "string" },
            "voteId": { "dataType": "string" },
            "pass": { "dataType": "string" },
        },
    },
    "Committe": {
        "properties": {
            "committeeId": { "dataType": "string", "required": true },
            "committeeName": { "dataType": "string", "required": true },
            "createdOn": { "dataType": "string", "required": true },
            "updatedOn": { "dataType": "string", "required": true },
            "status": { "dataType": "string", "required": true },
            "customerId": { "dataType": "string", "required": true },
            "boardType": { "dataType": "string", "required": true },
        },
    },
};

export function RegisterRoutes(app: any) {
    app.post('/meeting/login',
        function(request: any, response: any, next: any) {
            const args = {
                request: { "in": "body", "name": "request", "required": true, "ref": "LoginRequest" },
            };

            let validatedArgs: any[] = [];
            try {
                validatedArgs = getValidatedArgs(args, request);
            } catch (err) {
                return next(err);
            }

            const controller = new LoginController();

            const promise = controller.login.apply(controller, validatedArgs);
            promiseHandler(controller, promise, response, next);
        });
    app.get('/customer/all',
        function(request: any, response: any, next: any) {
            const args = {
            };

            let validatedArgs: any[] = [];
            try {
                validatedArgs = getValidatedArgs(args, request);
            } catch (err) {
                return next(err);
            }

            const controller = new CustomerController();

            const promise = controller.getAllCustomer.apply(controller, validatedArgs);
            promiseHandler(controller, promise, response, next);
        });
    app.delete('/customer/:customerId',
        function(request: any, response: any, next: any) {
            const args = {
                customerId: { "in": "path", "name": "customerId", "required": true, "dataType": "string" },
            };

            let validatedArgs: any[] = [];
            try {
                validatedArgs = getValidatedArgs(args, request);
            } catch (err) {
                return next(err);
            }

            const controller = new CustomerController();

            const promise = controller.deleteCustomer.apply(controller, validatedArgs);
            promiseHandler(controller, promise, response, next);
        });
    app.post('/vote/casting',
        function(request: any, response: any, next: any) {
            const args = {
                voteRequest: { "in": "body", "name": "voteRequest", "required": true, "ref": "VoteRequest" },
            };

            let validatedArgs: any[] = [];
            try {
                validatedArgs = getValidatedArgs(args, request);
            } catch (err) {
                return next(err);
            }

            const controller = new VoteController();

            const promise = controller.saveVote.apply(controller, validatedArgs);
            promiseHandler(controller, promise, response, next);
        });
    app.post('/vote/cancel',
        function(request: any, response: any, next: any) {
            const args = {
                voteRequest: { "in": "body", "name": "voteRequest", "required": true, "ref": "VoteRequest" },
            };

            let validatedArgs: any[] = [];
            try {
                validatedArgs = getValidatedArgs(args, request);
            } catch (err) {
                return next(err);
            }

            const controller = new VoteController();

            const promise = controller.cancelVote.apply(controller, validatedArgs);
            promiseHandler(controller, promise, response, next);
        });
    app.get('/committee/:name/:cid',
        function(request: any, response: any, next: any) {
            const args = {
                name: { "in": "path", "name": "name", "required": true, "dataType": "string" },
                cid: { "in": "path", "name": "cid", "required": true, "dataType": "string" },
            };

            let validatedArgs: any[] = [];
            try {
                validatedArgs = getValidatedArgs(args, request);
            } catch (err) {
                return next(err);
            }

            const controller = new CommitteeContoller();

            const promise = controller.getCommittee.apply(controller, validatedArgs);
            promiseHandler(controller, promise, response, next);
        });
    app.post('/committee/:name/:cid',
        function(request: any, response: any, next: any) {
            const args = {
                name: { "in": "path", "name": "name", "required": true, "dataType": "string" },
                cid: { "in": "path", "name": "cid", "required": true, "dataType": "string" },
            };

            let validatedArgs: any[] = [];
            try {
                validatedArgs = getValidatedArgs(args, request);
            } catch (err) {
                return next(err);
            }

            const controller = new CommitteeContoller();

            const promise = controller.addCommittee.apply(controller, validatedArgs);
            promiseHandler(controller, promise, response, next);
        });
    app.put('/committee/:commentId/:name/:cid',
        function(request: any, response: any, next: any) {
            const args = {
                commentId: { "in": "path", "name": "commentId", "required": true, "dataType": "string" },
                name: { "in": "path", "name": "name", "required": true, "dataType": "string" },
                cid: { "in": "path", "name": "cid", "required": true, "dataType": "string" },
            };

            let validatedArgs: any[] = [];
            try {
                validatedArgs = getValidatedArgs(args, request);
            } catch (err) {
                return next(err);
            }

            const controller = new CommitteeContoller();

            const promise = controller.updateCommittee.apply(controller, validatedArgs);
            promiseHandler(controller, promise, response, next);
        });
    app.delete('/committee/:commentId/:cid',
        function(request: any, response: any, next: any) {
            const args = {
                commentId: { "in": "path", "name": "commentId", "required": true, "dataType": "string" },
            };

            let validatedArgs: any[] = [];
            try {
                validatedArgs = getValidatedArgs(args, request);
            } catch (err) {
                return next(err);
            }

            const controller = new CommitteeContoller();

            const promise = controller.deleteCommittee.apply(controller, validatedArgs);
            promiseHandler(controller, promise, response, next);
        });

    function promiseHandler(controllerObj: any, promise: any, response: any, next: any) {
        return Promise.resolve(promise)
            .then((data: any) => {
                let statusCode;
                if (controllerObj instanceof Controller) {
                    const controller = controllerObj as Controller
                    const headers = controller.getHeaders();
                    Object.keys(headers).forEach((name: string) => {
                        response.set(name, headers[name]);
                    });

                    statusCode = controller.getStatus();
                }

                if (data) {
                    response.status(statusCode || 200).json(data);
                } else {
                    response.status(statusCode || 204).end();
                }
            })
            .catch((error: any) => next(error));
    }

    function getValidatedArgs(args: any, request: any): any[] {
        const fieldErrors: FieldErrors = {};
        const values = Object.keys(args).map((key) => {
            const name = args[key].name;
            switch (args[key].in) {
                case 'request':
                    return request;
                case 'query':
                    return ValidateParam(args[key], request.query[name], models, name, fieldErrors);
                case 'path':
                    return ValidateParam(args[key], request.params[name], models, name, fieldErrors);
                case 'header':
                    return ValidateParam(args[key], request.header(name), models, name, fieldErrors);
                case 'body':
                    return ValidateParam(args[key], request.body, models, name, fieldErrors, name + '.');
                case 'body-prop':
                    return ValidateParam(args[key], request.body[name], models, name, fieldErrors, 'body.');
            }
        });
        if (Object.keys(fieldErrors).length > 0) {
            throw new ValidateError(fieldErrors, '');
        }
        return values;
    }
}

Please help me

**Comment by lukeautry** [comment]
@adithya421 You'll need to import the new controller in the top level file (e.g. server.ts, index.ts, app.ts, whatever) - this helps tsoa figure out what controllers are included.

**Comment by adithya421** [comment]
Thank you @lukeautry its working fine 👍
