### ISSUE TITLE
Swagger.json and routes.ts file not generating code for newly added controllers

### ISSUE THREAD

**Issue by adithya421** [lukeautry/tsoa#207]
For the first time i.e
 if I created one controller and trying to generate swagger, routes its working fine. 
but if i add more new controllers and trying to run same commands below it not update swagger as well routes file. and if remove the swagger.json/routes.ts file to regenerate the code its only created default swagger.json file without any APIs and router with empty modes. Please advise

 npm run swagger
 npm run routes

**Comment by lukeautry** [comment]
@adithya421 Make sure to import the controller in your top level server file (see example server.ts).

**Comment by lukeautry** [comment]
Closing now - see previous comment. Let me know if you can't get this working.

**Comment by adithya421** [comment]
Thank you @lukeautry  its working fine after importing the controllers in server.ts file.
👍 🥇

**Comment by dgreene1** [comment]
Hi @lukeautry, I'd be happy to add to the documentation a section on how to regenerate the routes but I wanted to check in with you to see if a PR would be accepted for that?

Basically I would just add a section to the readme like this:
```
*How to regenerate*

Add a section to your package.json's script section with the following:
"tsoa:gen": "yarn tsoa swagger -c ./api/tsoa.json && yarn tsoa routes -c ./api/tsoa.json"

Then when you've made a change to an API, you simply run "yarn tsoa:gen"

Note: You can also integrate the swagger regeneration directly into your build step, but there are risks. To do that, add it to your build script in package.json:
"build:api": "tsoa:gen && yarn tsc -p ./api/tsconfig.json",
```

Does that look right to you? And more importantly, am I correct to call out that there are risks to automatically regenerate on every build?

**Comment by lukeautry** [comment]
I'm fine with it, feel free to open a PR.
