### ISSUE TITLE
[$100] extend not computed correctly by tsoa

### ISSUE THREAD

**Issue by Superd22** [lukeautry/tsoa#210]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=58538144)](https://www.bountysource.com/issues/58538144-extend-not-computed-correctly-by-tsoa?utm_source=58538144&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Hello,

I'm having an issue with an interface extending another, not correctly being constructed by tsoa.

More explicitly, My interface extends a custom Type that allows me to mask certain properties of a base class.

This is the custom type, it takes two generic, T being the base class to "extend" and "K" an array of keys in T.
```typescript
export type StringLiteralDiff<T extends string, U extends string> = ({[P in T]: P } & {[P in U]: never } & { [x: string]: never })[T];

export type Omit<T, K extends keyof T> = Pick<T, StringLiteralDiff<keyof T, K>>;
```

This is an example of how it might be used: 
```typescript
export class User {
    name:string;
    avatar:string;
    password:string;
    groups:id[];
}

export interface UserDisplay extends Omit<User, "password"> {
    displayColor:string;
}
```

User would, for example, be the way they are stored in the db, and UserDisplay the way we want to send the information to the front-end.

Typescript correctly types UserDisplay to:
```typescript
UserDisplay {
    name:string;
    avatar:string;
    groups:id[];
    displayColor:string;
}
```

however, after running tsoa, the resulting swagger types UserDisplay as simply: 
```typescript
UserDisplay {
    displayColor:string;
}
```

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=58538144)](https://www.bountysource.com/issues/58538144-extend-not-computed-correctly-by-tsoa?utm_source=58538144&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by endor** [comment]
I think `extend`s in general are computed correctly, but `MappedType`s like `Pick` aren't. I tried to debug this a little bit, but ended up not finding any members on the `MappedType` that I could pick up and use as properties on the extending interface. If anyone has a pointer on how to extract the members of a `MappedType`, please let me know and I can try to implement this.

**Comment by Superd22** [comment]
@endor This example was written just before TS 2.8 came out. But yeah we'd now probably use Exclude instead.
