### ISSUE TITLE
example project fails 

### ISSUE THREAD

**Issue by vijaysai07** [lukeautry/tsoa#212]
When I tried to run the example project it fails, expecting a type in one fo files under node_modules

**Comment by x1yy** [comment]
Typescript needs to be updated to the latest version. see https://github.com/lukeautry/tsoa-example/issues/6#issuecomment-302878265

**Comment by dgreene1** [comment]
If anyone wants to take ownership of their own example repo, we can add it to the readme. The current example repo may or may not get updated. The examples in the test files are probably the best resource for adopting current tsoa.

**Comment by lukeautry** [comment]
I updated the example repo, but we point to https://github.com/lukeautry/ts-app now, which is a better project.
