### ISSUE TITLE
Cannot use module path aliases

### ISSUE THREAD

**Issue by JakeStoeffler** [lukeautry/tsoa#213]
`tsoa routes` chokes if I use module path aliases as outlined in this article: https://medium.com/@caludio/how-to-use-module-path-aliases-in-visual-studio-typescript-and-javascript-e7851df8eeaa

Basically, the "paths" entry in tsconfig.json is not being respected by the tsoa routes crawler.  I can use the aliases without any problems *except* in my controllers and models since those are being crawled.  Since the paths mapping is a pretty standard feature of TypeScript (see Path Mapping section in [Module Resolution](http://www.typescriptlang.org/docs/handbook/module-resolution.html) docs), I feel like it should be supported.

**Comment by JakeStoeffler** [comment]
Nvm, just saw [this](https://github.com/lukeautry/tsoa#path-mapping) at the bottom of the README.

**Comment by VonSandberg** [comment]
Still not able to get it working with following dynamic alias (works fine in tsconfig.json). Any idea?

```
"compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"]
    }
  }
```

**Comment by ljwagerfield** [comment]
If you copy-paste the `compilerOptions` field from `tsconfig.json` into `tsoa.json` (i.e. key included) then it works for me.

I've raised a ticket for this, as it seems a little odd that the settings wouldn't be picked up from `tsconfig.json` automatically, and need duplicating into `tsoa.json`:

https://github.com/lukeautry/tsoa/issues/868

**Comment by douglasg14b** [comment]
The `moduleResolution` value seems to not be accepted for any values though, heads up.
