### ISSUE TITLE
Array as an Query Paramater does not get handled correct

### ISSUE THREAD

**Issue by Templum** [lukeautry/tsoa#219]
# General Information

Version of Typescript: 2.8.3
Version of Tsoa: 2.1.4

# Description of the issue

I defined the following endpoint which expects a string array via the query.

```javascript
@Get('/sample/endpoint')
public async getStuff(
@Query('arrayParam') shouldBeArray: string[] = ['Some','default','values']
): Promise<any> {...}
```
The actual request url should look like `host:port/sample/endpoint?arrayParam=Some,default,values`, which is also generated by the swagger ui. 
Another option would be `?arrayParam=Some&arrayParam=default&arrayParam=values` which works with some frameworks, like express.
So I would expect that at runtime ` shouldBeArray = ['Some','default','values']` instead it is `shouldBeArray = ['Some,default,values']`.

In addition, there seems also a more general issue with Enum(Strings).  If you update the previous method to expect an array of MyEnum like following.

```javascript
export type MyEnum = 'Ready' | 'Awesome'

@Get('/sample/endpoint')
public async getStuff(
@Query('arrayParam') shouldBeArray: MyEnum[] = ['Ready','Awesome']
): Promise<any> {...}
```
The actual request url should look similiar to the previous `host:port/sample/endpoint?arrayParam=Ready,Awesome`. Which will fail validation due to the previously shown actual content of arrayParam (`['Ready,Awesome']`). Guess the same should also happen if its an number[].

# Possible Solution

Based on the defined type, should be an array of primitives (with exception of string/number enums), than it should be possible to perform an `'Ready,Awesome'.split(',')` based on type you might add `.map(number=> parseInt(number))` and then perform the validation on the actual entries.

**Comment by Templum** [comment]
Nevermind just discovered that the Swagger UI is generating the wrong request string. Actually to pass a string array via query you do something like `arrayParam=Some&arrayParam=Default`. Will close this then.

**Comment by anro87** [comment]
Some problem for me. Any updates on that?

**Comment by sclarson** [comment]
Any chance you can reproduce the issue as a test?

**Comment by Templum** [comment]
What exactly do you require? The shown endpoint implementation should work as a test.

**Comment by dgreene1** [comment]
We’ll track this feature request for array and record type Query params in https://github.com/lukeautry/tsoa/issues/353#issuecomment-526405877

**Comment by dgreene1** [comment]
Actually this might be a distinct issue. Can someone help by just reproducing this problem?
