### ISSUE TITLE
Documentation - Please clarify what "tsoa" means

### ISSUE THREAD

**Issue by rdhelms** [lukeautry/tsoa#239]
Of urgent importance to all developers using tsoa, I'm sure, is the question "what does tsoa even mean?"

Is it an acronym?

Is it a word? 

Is it the Technical Standard Order Authorization?

Is it TypeScript, Swagger, or Aliens?

Please help.

**Comment by jasonhcarr** [comment]
Tragic State Of Affairs

**Comment by lukeautry** [comment]
Around the time I started on this library I had seen a talk on https://github.com/goadesign/goa at GopherCon. I lazily thought that tsoa would be a short and easy name to name this library. I think it was originally something really lame like typescript-swagger.

I just say "soa". There's a t there but it ends up sounding silent.

**Comment by rdhelms** [comment]
My burden of curiosity has been lifted 👍🏻

**Comment by jamestharpe** [comment]
And here I thought it was "**T**ype**S**cript **O**pen**A**PI" Specification this whole time :)
