### ISSUE TITLE
Error: Unknown type: TupleType

### ISSUE THREAD

**Issue by ericcarino** [lukeautry/tsoa#242]
Tuples appear to not be supported.   Is this correct or a bug?

```
export interface ClusterStats {
    ...
    prop1: Array<[string, Array<any>]>;
    prop2: Array<[string, Array<any>]>;
}
```

Error produced when trying to build swagger doc.

```
There was a problem resolving type of 'ClusterStats'.
Generate swagger error.
 Error: Unknown type: TupleType
    at new GenerateMetadataError (/Users/ecarino/go/src/github.com/nefeli/pangolin/dashboard/rest/node_modules/tsoa/dist/metadataGeneration/exceptions.js:17:28)
    at resolveType (/Users/ecarino/go/src/github.com/nefeli/pangolin/dashboard/rest/node_modules/tsoa/dist/metadataGeneration/resolveType.js:56:15)
    at resolveType (/Users/ecarino/go/src/github.com/nefeli/pangolin/dashboard/rest/node_modules/tsoa/dist/metadataGeneration/resolveType.js:69:30)
    at /Users/ecarino/go/src/github.com/nefeli/pangolin/dashboard/rest/node_modules/tsoa/dist/metadataGeneration/resolveType.js:496:23
    at Array.map (<anonymous>)
    at getModelProperties (/Users/ecarino/go/src/github.com/nefeli/pangolin/dashboard/rest/node_modules/tsoa/dist/metadataGeneration/resolveType.js:462:14)
    at getReferenceType (/Users/ecarino/go/src/github.com/nefeli/pangolin/dashboard/rest/node_modules/tsoa/dist/metadataGeneration/resolveType.js:281:26)
    at resolveType (/Users/ecarino/go/src/github.com/nefeli/pangolin/dashboard/rest/node_modules/tsoa/dist/metadataGeneration/resolveType.js:95:25)
    at Object.resolveType (/Users/ecarino/go/src/github.com/nefeli/pangolin/dashboard/rest/node_modules/tsoa/dist/metadataGeneration/resolveType.js:73:20)
    at MethodGenerator.Generate (/Users/ecarino/go/src/github.com/nefeli/pangolin/dashboard/rest/node_modules/tsoa/dist/metadataGeneration/methodGenerator.js:30:34)
```

**Comment by endor** [comment]
You're right. `Tuple` doesn't seem to be supported yet. At least I can't find a reference to it in `resolveType`. Any interest in adding it?

**Comment by endor** [comment]
I'll close this for now. Let me know if you have any other questions.

**Comment by HoldYourWaffle** [comment]
@endor I'm not sure why this was closed, the feature hasn't been added yet.
I have created a **very basic** implementation, once it's done I'll submit a PR. 
Right now it still lacks proper tests and schema/spec generation (I only need very basic parsing myself) but I think I'll have the time to add these things somewhere in the coming weeks.

**Comment by WoH** [comment]
@dgreene1 can we reopen this given for discussion maybe?

> @WoH I think it was be discourteous to API consumers to allow them to submit [“aString”, 4] when only [4, “aString”] is allowed. And since the order of mixed types can not be communicated via Swagger/OpenAPI3, I really don’t want to be on the hook for a miscommunication of that magnitude. I stated this in the issue for this PR, but I would only approve a PR that generated documentation for a homogeneously-types tuple since order doesn’t matter in that circumstance.

I have to slightly disagree here. I agree it's not perfect to have slight inconsistencies here. I'd definitely want a description that communicates the order.

However, not implementing this is not a better solution. It basically forces the API developer to accept anything (just like we would have to do) and check on their own, when a tuple could've been specified instead. At the end of the day, either tsoa or the developer will have to tell the api user that the order was not as expected (which can't be deduced from the spec alone **in both cases**.

**Comment by HoldYourWaffle** [comment]
> So I’m not sure that we should support heterogenous/mixed-type tuples until OpenAPI supports heterogenous tuples.

Do you mean "not support" as in error or just a warning? I don't think it's fair to error route generation just because a completely different feature doesn't support it. There's no additional processing required for heterogeneous tuples so as far as I can tell [here](https://github.com/HoldYourWaffle/tsoa-iso/blob/3fc757071e0cd6fdc8ca868d7b3dd3390c5261c7/src/swagger/specGenerator.ts#L175-L183), [here](https://github.com/HoldYourWaffle/tsoa-iso/blob/3fc757071e0cd6fdc8ca868d7b3dd3390c5261c7/src/swagger/specGenerator2.ts#L242-L248) and [here](https://github.com/HoldYourWaffle/tsoa-iso/blob/3fc757071e0cd6fdc8ca868d7b3dd3390c5261c7/src/swagger/specGenerator3.ts#L239) would be the appropriate places for a check and potential warning/error, so non-swagger users are not affected.

**Comment by HoldYourWaffle** [comment]
> If the specVersion is 2, then we warn "tuples are not allowed in Swagger 2. please change your specVersion config to 3"

I assume you only want this for heterogeneous tuples? Based on [this comment](https://github.com/lukeautry/tsoa/pull/451#issuecomment-524812258) I don't see a reason why homogeneous tuples wouldn't be possible in swagger 2.

> If the specVersion is 3 and if the tuple has mixed types (i.e. ["myString", 3]) then we warn that:

That warning looks good to me.

> I will re-open the issue if someone is interested in creating a PR that meets that acceptance criteria (and has unit tests that verify via test spies that the warnings are being written).

I'll probably be able to do it once I know how to generate the swagger/open api part.

**Comment by HoldYourWaffle** [comment]
https://github.com/lukeautry/tsoa/pull/451#issuecomment-536163359

**Comment by fantapop** [comment]
It looks like support for Tuples in openapi 3 will land in 3.1.0:

https://stackoverflow.com/questions/57464633/how-to-define-a-json-array-with-concrete-item-definition-for-every-index-i-e-a#answer-5746519

I see that RC0 was tagged in June. https://www.openapis.org/blog/2020/06/18/openapi-3-1-0-rc0-its-here Hopefully its coming soon!

**Comment by aktary** [comment]
This is still a problem in v5.1.1.

`export type TChatRequest = {
    question: string;
    history: [string, string][];
};`

causes:

> There was a problem resolving type of 'TChatRequest'.
> GenerateMetadataError: Unknown type: TupleType

**Comment by nezudevv** [comment]
I am running into this in 2026... 
Using: 
```
temperatureRange?: [number, number] | null,
```
Results in this error: Generate routes error.
 GenerateMetadataError: Unknown type: TupleType
I have the specVersion in the tsoa json file set to 3: `"specVersion": 3`
