### ISSUE TITLE
Using Example & SuccessResponse Decorators

### ISSUE THREAD

**Issue by Izabrr** [lukeautry/tsoa#245]
Is it possible to use both of them ? I want to add a description and an example for my success response on my endpoint but the swagger generated does not include my example.

NB: each decorator works fine separately

**Comment by jpramondon** [comment]
Hello,

I filed a similar issue (#255) on this, coming along with PR #256.
We happen to have the same problem with _@SuccessResponse_, but also when providing an example as a parameter for the _@Response_ decorator.

Cheers,

Jerome
