### ISSUE TITLE
namespace can not find in the types/index.d.ts

### ISSUE THREAD

**Issue by linxiaowu66** [lukeautry/tsoa#250]
Hi guys,
   Recently I use tsoa to generate the swagger docs. But I occur a  problem. As the tsoa support namespace parsing, so i defined a namespace in the index.d.ts, for example:

```
declare namespace test {
     export namespace test1 {
        export interface test2 {
        
       }
  }
}
```

Then in the controller method, i return the test2 as following:

```
...
testMethod(): Promise<test.test1.test2> {}
...
```

But Tsoa report this error:

`Unhandled rejection Error: No matching module declarations found for test`

So is Tsoa can not collect all type definition in the project ?

If not, has any way to solve this issue ?

Thanks in advance.

**Comment by endor** [comment]
I'm still fairly new to TS, so I'm not sure about this at all. It's also difficult to analyse this without the codebase. A few things though:

* `tsoa` generally scans the code starting from the `entryFile` in the configuration. so you will want to import all your controllers/files to reference in the `entryFile`.
* Wouldn't you need to export the `test` namespace?
* Wouldn't you need to import the `test` namespace in your controller?

**Comment by linxiaowu66** [comment]
@endor yes,  you are right, when I import the index.d.ts will solve this problem, I this `import` behavior  also make the code can not run even though it can generate the docs. So it is so conflict.

**Comment by daweimau** [comment]
Still an issue
