### ISSUE TITLE
Can't find documentation for tsoa decorators

### ISSUE THREAD

**Issue by gornostal** [lukeautry/tsoa#254]
Could you provide a link where I can read description for all decorators please?

Currently I'm tying to figure out how to use `@Example` and what does `@Tags` decorator do.

Thanks

**Comment by Superd22** [comment]
`@Tags` as the name implies sets the tag of the current controller and or method.

see : https://swagger.io/docs/specification/2-0/grouping-operations-with-tags/

**Comment by endor** [comment]
I'll close this for now. Please reopen if things are still unclear.

**Comment by gornostal** [comment]
Hi
My question was about tsoa documentation that describes all available
decorators.
"Tags" was an example of what I was looking for.

So I assume there's no such documentation. Am I wrong?

**Comment by endor** [comment]
There's no more documentation that the `README.md`. As described at the end of the README it can be useful to look at the example controllers in the tests. The [getController](https://github.com/lukeautry/tsoa/blob/master/tests/fixtures/controllers/getController.ts) documents how the `Example` and `Tags` decorators are used. We'd be happy to get more documentation, if you're up for it. (:

**Comment by gornostal** [comment]
Thanks for the examples
