### ISSUE TITLE
x-nullable is no Swagger

### ISSUE THREAD

**Issue by jpramondon** [lukeautry/tsoa#257]
Hey there,

We noticed a small change sneaked into the code recently:

https://github.com/lukeautry/tsoa/blob/f97c738b88c9af82dd09a83c1fb5399e40d5ca40/src/swagger/specGenerator.ts#L247

Is this an attempt to mark a model's property as required or mandatory ?
If so, then unfortunately this is a breaking change to anyone using AWS and its ApiGateway. Since _x-nullable_ is not a Swagger-valid property, the swagger.json file becomes invalid to anything trying to match it against the Swagger specification.

Additional input : The Swagger way to deal with required properties is described [here](https://swagger.io/docs/specification/data-models/data-types/).

For now, we'll just filter the _x-nullable_ properties out of the generated swagger file, but this point is worth a second look and discussion (before leaping to OpenAPI 3), which I'd like to have with you all if you're ok with this.

Cheers !

Jerome

**Comment by lukeautry** [comment]
Hey Jerome. That is indeed a change I put in. I couldn't find anything official in OpenAPI docs pertaining to nullable properties, but it is indeed something that needs to be expressed in some way. It could be turned into a configurable option.

**Comment by endor** [comment]
It could be worth removing this from the code and trying to push the OpenAPI 3 changes because there a valid `nullable` property exists.

**Comment by jpramondon** [comment]
Thanks for your replies, guys.

Indeed the swagger specification has something for _required_ fields, but seeing you used the word _nullable_, I wasn't sure this was exactly what you meant initially.

This below is the swagger way of expressing a required field:
```
type: object
properties:
  id:
    type: integer
  username:
    type: string
  name:
    type: string
required:
  - id
  - username
```

Again, _nullable_ might mean something else.

Just like @endor states, OpenAPI 3 offers a _nullable_ qualifer, so it's really worth keeping it for later use (I've seen he's working on the OpenAPI3 compatible version).
Which brings up another question for this coming version: will we be able to control which specification we want the file to follow (Swagger or OpenAPI3) ?

And another one: is it still worth working on the swagger file generation now the OpenAPI3 version is on sight ? I'm asking so to know if I'm taking some time to implement that or if I just let it like it is right now (without support for required fields).
On one hand, we've been living without this feature until now, on the other that would improve the swagger specification coverage.

Tell me what you think.

**Comment by endor** [comment]
I think there should definitely be the option to choose between Swagger/OpenAPI 2 and OpenAPI 3. That's what I've also done in my PR. If you're asking how much longer it will be before we can generate a proper OpenAPI 3 version - I can't really say. It depends on other people reviewing my code, contributing code and checking if it works as expected. Considering the speed at which things happen here, it might take a while ;)

I think what @lukeautry suggested, make using `x-nullable` optional, could be a good temporary solution for your problem. And we already support the swagger way of specifying required fields as far as I can see.

In the long term, I think spending time on the OpenAPI 3 version might be a better investment.

**Comment by jpramondon** [comment]
I didn't mean to try to rush things or sound impatient regarding OpenAPI 3. Your work on this is really appreciated.
But hey ! Since we do use Tsoa for quite a bit of time now and have a full blown continuous delivery process based on AWS (and its "infamous" gateway), would you like us to checkout your work and test it over it ?

**Comment by endor** [comment]
That would of course be greatly appreciated. And just for my understanding.. you create the swagger spec through tsoa from code and then feed that spec to AWS API Gateway to make a 1-to-1 mapping for all endpoints? What's the advantage over just plain ELB+EC2? I'm working currently also on setting up an AWS API Gateway, because I'd like some of my endpoints to be private (only reachable from within a private network), but I don't think I can do that via the swagger spec, can I?

**Comment by jpramondon** [comment]
Then I'll give your branch a try on our projects and see how it goes. Hopefully this will speed up the process a bit.

On what we do, I'll try to make it clearer:
- We do create the swagger file based on tsoa's decorators on our code
- Then the generated file is transformed twice before being submitted to the API Gateway, so it's checked for compatibility
- Only then, our API is sent for deployment on Kubernetes pods

Why it's transformed? Well it happens that the API Gateway has its own set of rules. These transformations are only there to comply to it. For instance endpoint parameters need to be specified in a specific manner using the _x-amazon-apigateway-integration_ property alongside _parameters_ for each patch. Also, its naming rules regarding models specifies a model name have to comply to a rather restrictive regex (something like [a-zA-Z]), which is incompatible with the way tsoa deals with array introspection (generating names with square brackets like MyModelName[])
There are a couple of other transformations that we do.

I don't know much about ELB, so I'm not sure I could compare both solutions properly. But if you have more specific questions on what and how we do, I'd gladly try to help.

Cheers,

Jerome

**Comment by endor** [comment]
Hei Jerome,

I do have some more questions. If you could ping me by email at frank@naa.li, I'll ask them there.

Cheers,
Frank

**Comment by Recodify** [comment]
@jpramondon hey, any chance you could share more about what transformations you're doing? I'm facing the same hurdles trying to use a TSOA generated swagger definition as part of a aws CI/CD process. Any code you be very much appreciated, if at all possible. Many thanks

**Comment by jpramondon** [comment]
Hi @Recodify,

We ended up writing a complete module that goes through our swaggers applying somewhere around 15 transformation rules (though you might not need as much as some are really specific to the way we deploy APIs).
Tell me where you're stuck and I'll try to help as the module is not opensourced (yet).

**Comment by dgreene1** [comment]
Since the desired solution of being able to use the nullable properties of Open API 3 is now possible thanks to PR https://github.com/lukeautry/tsoa/pull/249, I'm going to close this PR.
