### ISSUE TITLE
A little more info on how exactly tsoa's controller lookup works

### ISSUE THREAD

**Issue by cburnicki** [lukeautry/tsoa#258]
First of all, thanks for the great project. This has a real potential to speed up and simplify our development processes of smaller web apps.

I was just starting to build myself a minimal app that exposes it's endpoints in swagger UI. I defined a controller and set up `swagger` and `routes` commands. However, no routes are appearing in my swagger.json and I couldn't tell why they should.

The way I understand tsoa, running `tsoa swagger` will use my decorated controller definitions to create the swagger.json file. From that, running `tsoa routes` will create routes, in my case for the express web server. So my routes.ts does not contain any routes because there are no endpoints defined in my generated swagger.json file.
What I don't understand (and I couldn't find an explanation for this anywhere) is: Where does the `tsoa swagger` command find information about existing controllers whose endpoints should be added to the swagger specification. 

I wasn't able to find any specific information about this seemingly magic part.

My minimal tsoa stack can be found here: https://github.com/cburnicki/tsoa-base-stack

**Comment by endor** [comment]
Hei Christoph,

it says somewhere in the README `The controllers need to be included in the application in order to be linked.`. So in `tsoa.json` you specify the `entryFile`, which is your app. And in your app you will need to include your controllers in order for tsoa to find them. Quickly checking your repository, it seems you link to `src/index.ts` in your `tsoa.json`, but that file doesn't seem to exist.

**Comment by endor** [comment]
@cburnicki Up for implementing that?

**Comment by cburnicki** [comment]
@endor Sure. I get TS errors running `npm i && npm run build` on your dev branch. Am I missing something or is this one currently not stable?

**Comment by endor** [comment]
@cburnicki I just joined the project, so I'm not sure what the policy is, but it looks like the `dev` branch is 2 years old. When I made changes, I started from `master`.
