### ISSUE TITLE
How to give endpoints a tag? (all go to default)

### ISSUE THREAD

**Issue by pabloelustondo** [lukeautry/tsoa#26]
Hi, totally love this package and I am using the example to publish my own API. 
Not sure this is an issue or I did not figure out to do it.
How to give endpoints a tag? (all go to default now and collapsed)
Can i leave this expanded by default?
Thanks, you rock.

**Comment by lukeautry** [comment]
Glad you're enjoying it! @pabloelustondo I personally haven't used tags much so there isn't anything included right now for that.

That said, there is an open pull request #21 that implements adding tags. I had some questions for the person that opened that PR, but if you could read over that or propose a solution, it may be quite easy to implement.

I think the way I would expect it to work - based on my reading the documentation - would be something like this:

```
  @Get('Current')
  @Tags(['tag1','tag2'])
  public async getCurrentModel(): Promise<TestModel> {
    return new ModelService().getModel();
  }
```

Let me know what you think.

**Comment by artemnikotin** [comment]
Hi @lukeautry , our team also glad to use **tsoa** and we need tags. (yep it was our pull request about tags, but we did not understand all details of the project).
If you are going to implement tag support - we will be happy to use it later, but if you have no time on it now - we will try to create "good" pull request with fixed remarks.
For now "bad" pull request was closed.

**Comment by lukeautry** [comment]
@artemnikotin @pabloelustondo I've implemented operation tags in the latest package (1.0.7)

Taken from the test examples:

```
@Get('GeneratesTags')
  @Tags('test', 'test-two')
  public async getGeneratesTags(): Promise<TestModel> {
    return new ModelService().getModel();
  }
```

Generates:

```
"/GetTest/GeneratesTags": {
			"get": {
				"operationId": "getGeneratesTags",
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "",
						"examples": {},
						"schema": {
							"$ref": "#/definitions/TestModel"
						}
					}
				},
				"description": "",
				"parameters": [],
				"tags": [
					"test",
					"test-two"
				]
			}
		},
```

Let me know if you have any questions.

**Comment by empitegayan** [comment]
@lukeautry this is great!! can't we pass tag as object which includes all properties like below 

```
{
      "name": "pet",
      "description": "Everything about your Pets",
      "externalDocs": {
        "description": "Find out more",
        "url": "http://swagger.io"
      }
    },
```

**Comment by AntoineABI** [comment]
We need some global and/or controller wide tags configuration too. Please ;)

**Comment by dgreene1** [comment]
@empitegayan I know this is a very old post, but we'd be interested in a PR if you'd like to enhance the `@Tag` decorator to accept an object or a string so that you could add `description` as well as `name`. Btw, are you still using `tsoa`? How is it going for you? :)
