### ISSUE TITLE
Implement a "strict" requests checking mode 

### ISSUE THREAD

**Issue by mushketyk** [lukeautry/tsoa#264]
At the moment `tsoa` only validates if all fields in a request are present, but it does not prevent undeclared fields from being passed to a request handler.

For example, if we have an API like:

```typescript
export class CreateUserRequest {
  name: string

  surname: string
}

Route('users')
class UsersController {

  @Post()
  public async createUser(@Body() user: CreateUserRequest) {
    ...
  }
}
```

With this definition, `tsoa` will validate that both `name` and `surname` fields are present, but it allows sending a request with the following body:

```javascript
{
  "name": "John",
  "surname": "Doe",
  "id": "new-id" // Some malicious field passed in the request
}
```

`tsoa` allows to send a request like this and will pass additional fields to a request handler.

I think that `tsoa` should implement a "strict" mode (maybe even enabled by default) that should either:

* Filter out unexpected fields
* Return 400 if there are unexpected fields in a request

**Comment by mushketyk** [comment]
@endor I might help with this. How do you prefer to handle the "strict" mode? Should it be enabled by default? Should it return 4xx? Should this be configurable?

**Comment by fhewitt** [comment]
If should be configurable both on an global way through tsoa config (because it break backward compatibility if enabled by default, therefore need an easier global fix), and override by specific endpoints for fine control and progressive implementation through decorator `@Strict` or similar.

Yes, it should return a 400 Bad Request

**Comment by endor** [comment]
Why would you want some of your endpoints to be strict and some not? That would seem like an inconsistent API. You're probably right about keeping backwards compatibility by turning it off by default so it behaves as before, but once you turn it on, shouldn't it really be turned on for all?

**Comment by dgreene1** [comment]
> @endor From my point of view this should be default with an option to turn it off.

I agree. Yes, it would be a breaking change, but it's a change that would follow TypeScript's own design where you have to explicitly allow excess properties in defined interfaces. So as a newbie to `tsoa` it's a bit of a surprise to discover that the default is "not strict mode."

Btw, I'd also be interested in helping with this one. Has anyone started on a branch? (@mushketyk?) Or do we need more consensus before starting this work?

> @endor Why would you want some of your endpoints to be strict and some not? That would seem like an inconsistent API. You're probably right about keeping backwards compatibility by turning it off by default so it behaves as before, but once you turn it on, shouldn't it really be turned on for all?

I agree with @endor. @fhewitt, if you wanted to have an endpoint allow extra properties, then you could simply add this property to the interface: `[excessProperties: string] : ISomeType`.

**Comment by dgreene1** [comment]
This feature was added in https://github.com/lukeautry/tsoa/pull/385 and is currently being enhanced in https://github.com/lukeautry/tsoa/pull/411. Feel free to provide feedback in the [enhancement ticket](https://github.com/lukeautry/tsoa/pull/411).

Thank you for the great suggestion @mushketyk. It was fun working on this feature. If you wouldn’t mind sharing your enjoyment of the tsoa library on Twitter, Reddit, or on [dev.to](https://dev.to) we’d appreciate it. :)
