### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by MatthiasKunnen** [lukeautry/tsoa#275]
Swagger supports the use of Markdown. I propose that JSDoc be converted into Markdown, maybe behind a flag. This would allow us to have all the cool features of Markdown available in our Swagger documentation.

If this sounds like a cool feature, I can take a look at creating a PR in the following month or two.

**Comment by endor** [comment]
Hm, what does that entail? Can't you right now just write Markdown in your JSDoc description and it'll be passed on into the swagger specification?

**Comment by MatthiasKunnen** [comment]
I'm aiming at converting `{@link https://example.com}` into `[https://example.com]`. See http://usejsdoc.org/tags-inline-link.html. This could apply to more JSDoc structures I think.

**Comment by endor** [comment]
Ah, so there will basically be a predefined list of jsdoc decorators that will be transformed to Markdown. I think that makes sense. The only thing is that for example currently we also parse `@example` and make it into an example attribute in the swagger specification. So it might get a bit confusing, which decorators in the jsdoc end up where/how. But I think it could still make sense (:

Adding it behind a flag makes also sense to me.

**Comment by dgreene1** [comment]
Cool idea @MatthiasKunnen. But from what I can tell, JSDoc does not support markdown by default (but I'm only basing that off of what I found from a quick google search https://github.com/jsdoc/jsdoc/issues/1499). I don't think we should support this until JSDoc supports markdown as a standard. If it is part of the JSDoc standard, then we can reopen this issue.
