### ISSUE TITLE
What would be the best way to deal with Date/datetime type in GET request parameter?

### ISSUE THREAD

**Issue by pabloelustondo** [lukeautry/tsoa#28]
we are using this generator for our API we are declaring for now our data parameters as string. Is there a better way?. Any way to declare the format?

**Comment by lukeautry** [comment]
@pabloelustondo There's logic to deal with dates, but it's not accepted as a query parameter right now.

This is an easy fix and I'll push something out shortly and provide some quick usage tips.

**Comment by lukeautry** [comment]
@pabloelustondo This should be possible in 1.0.4; see https://github.com/lukeautry/tsoa/blob/master/tests/integration/server.spec.ts#L132

**Comment by pabloelustondo** [comment]
Thanks Luke, it works!
