### ISSUE TITLE
Error: @Path('args') Can't support 'array' type.

### ISSUE THREAD

**Issue by gitowiec** [lukeautry/tsoa#288]
I would like to
```
  @Get('do-something-important/{objecId}/{secret}/{hiddenParam}')
  @SuccessResponse('201', 'Created')
  public async doSomethingImportant(objectId: string, secret: string, ...args): Promise<EntityId> {
    const hiddenParam = args.pop();
    const result = await doSomethingImportantUseCase.run({ objectId, secret, hiddenParam });
    this.setStatus(201);
    return result;
  }
```
But I can't because of such error. 
I am simply looking for a way to hide a get path parameter from swagger.
How can I do it?

**Comment by dgreene1** [comment]
@gitowiec we don't support `...args`. My apologies. If you wanted to get `hiddenParam` then you would need to explicitly create the function property like you did with `secret`.
