### ISSUE TITLE
Problem with generated routes.ts

### ISSUE THREAD

**Issue by ekarlso** [lukeautry/tsoa#289]
There's tons of this:
src/routes.ts(3597,18): error TS7017: Element implicitly has an 'any' type because type 'AuditsController' has no index signature.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! epim-services@0.1.0 build-ts: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the epim-services@0.1.0 build-ts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ekarlso/.npm/_logs/2018-09-23T13_24_05_092Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lukeautry** [comment]
@ekarlso Is this still happening with 2.2.4?

**Comment by lukeautry** [comment]
Closing for now pending feedback.
