### ISSUE TITLE
how to pass back better custom error message and status code on 400 404.. 

### ISSUE THREAD

**Issue by pabloelustondo** [lukeautry/tsoa#29]
Hi Luke,
           Thanks again for your help before with datetime. Now we have this minor annoyance. When we have a GET with various parameters, say p1,..p,n2 and .. px is number but customer send string... the current error code is 400 and not message.
           We noticed that the router has a 'next' function but could not figure out  how to use it.
           We  want to return a proper custom error message and code.
           Eventually, I think, we we know your code better we may try to help you, but for now we are to newbies.
Thanks!, Pablo.

**Comment by lukeautry** [comment]
@pabloelustondo It should be possible to use custom errors. Check out https://github.com/lukeautry/tsoa/blob/master/tests/fixtures/server.ts#L26 as an example; this is just a standard Express convention.

The generated library code will call next if an error is thrown either in the built-in validation steps or inside your code itself. I've added some [tests](https://github.com/lukeautry/tsoa/blob/master/tests/integration/server.spec.ts#L166) and [examples](https://github.com/lukeautry/tsoa/blob/master/tests/fixtures/controllers/getController.ts#L111)

Let me know if you're still having trouble with this.

**Comment by pabloelustondo** [comment]
Thanks Luke. But yes, I am still struggling to understand how to  pass the control back in my controller after an invalid parameter has been detected by the router. Not sure I explained my propblem well. Let say my GET controller looks like this:

 @Get('routename')
    public async Get(dateFrom: string, dateTo: string): Promise<Data> {

When the router finds and error, I know it will call the 'next' but my problem is that I do not understand how to define this 'next' from my controller. 

Sorry for my newbiness

**Comment by lukeautry** [comment]
No problem. If it's confusing to you it's probably confusing to others too.

Yeah, so the controller itself (and any code it calls into) doesn't and shouldn't know anything about the "next" error handling. From the controller, you should just be throwing errors.

```
When the router finds and error, I know it will call the 'next' but my problem is that I do not understand how to define this 'next' from my controller.
```

Here are the scenarios I can think of - let me know which one of them sounds like yours.
- Consumer calls API, but the route doesn't exist. Express itself throws an error; there's no way from your controllers to define what, exactly, the nature of the error message is here. I believe it is possible to customize "route not found" behavior for Express, but that's not within the scope of this project.
- Consumer calls API, a route does exist, but the parameters passed fail validation. In this case, it's also not currently possible to override or define the nature of the error message; tsoa throws an "InvalidRequestException", which will contain a message about how validation failed, and is a '400' status code error.
- Consumer calls API, a route does exist, validation of parameters succeeds, but an error is thrown within a controller method. In this case, the error you throw *does* get passed all the way back up to the router and rendered as a response.

If you are case #3, then I think you're all set. If you're case #2, you will either have to settle for the built in tsoa errors, or I can look into allowing custom error types for validation errors.

**Comment by lukeautry** [comment]
@pabloelustondo Closing for now, let me know if the last explanation was off base.

**Comment by nemes1s** [comment]
@lukeautry Thanks for the explanation, but i have a #2 case scenario (validation fails), but the data returned to API consumer is: [object Object] with status code 400.

Though while debugging step by step, i see the validation error in routes.ts within try catch block and fails as expected. But for some reason it doesn't render the correct response for the consumer with failed messages.

Please help :)

**Comment by nemes1s** [comment]
Ok, don't bother, found my mistake

**Comment by tbranyen** [comment]
@nemes1s it'd be more helpful if you had posted what you found instead of saying you found your mistake. What mistake? What did you do to fix this error?

**Comment by tbranyen** [comment]
I ended up registering an express error middleware and was able to render JSON instead of a string:

```
// Render error instead of a string `[object Object]`.
app.use((err, req, res, next) => {
  res.status(err.status);
  res.json(err);
});
```

Hope this helps someone else.
