### ISSUE TITLE
Adding special attributes to swagger documentation

### ISSUE THREAD

**Issue by RckMrkr** [lukeautry/tsoa#294]
Hey there

We need to add a custom (not documented) attribute to the swagger file that gets generated. Is this at all possible now? It wasn't quite sure if this was possible through jsdoc, and if so, how.
Makes sense if it's not possible, but it's kind of a deal breaker in terms of us adopting.

Cheers
And I appreciate all the hard work you've put into this so far.

**Comment by lukeautry** [comment]
You can kind of do this by providing your own spec, which gets merged with the generated spec. What sorts of attributes are you wanting to add? Examples would help.

**Comment by RckMrkr** [comment]
We have a longer pipeline to handle which (and how) documentation gets shown publicly and what gets shown internally. To manage this we've added custom attributes on the routes and on the root (unsure if that's the technical name). Depending on these properties we then strip the routes which should not appear publicly.
Here's a small snippet of one of our current files (yaml):
```
swagger: "2.0"
...
x-trustpilot-servicename: "businessunits-api"
paths:
  v1/internal/business-units/:
    get:
      operationId: getInternalProspectorDataDeprecated
      x-trustpilot-api-visibility: internal
      x-trustpilot-api-security: oauth
      description: Gets all business units
```

**Comment by pavlrd** [comment]
Hi, 

we trying to add `x-example` attribute for the path, so it goes into the params, like:

```
parameters:
    -
        in: path
        name: id
        required: true
        type: string
        x-example: '42'
```

This is so we can automatically test the API based on swagger docs. Is there way to it?

**Comment by endor** [comment]
@RckMrkr Would tags be a way to do this? How would you add such custom parameters to your methods?

**Comment by RckMrkr** [comment]
I think we could possibly use tags. It would require us to make some changes in our end, but that's to be expected.

The way I imagined it would be a decorator on the functions:
```
@CustomAttribute("x-attribute", "value")
@Get('{id}')
public async getUser(id: number, @Query() name: string): Promise<User> {
    return await new UserService().get(id);
}
```
At least that makes sense for the extra properties that goes on the routes. I don't know of a good place to add it on a service level.

**Comment by endor** [comment]
It sound to me like such custom attributes could be a good addition to tsoa. Care to make an implementation? For your use-case, I think tags might be a good solution though.

**Comment by dgreene1** [comment]
I’m bumping this because (a) there are requested changes on the PR (b) this is a great feature idea and (c) I need to adjust the stale bot to not mark “help wanted” issues as stale.
