### ISSUE TITLE
Null values are replaced by undefined in parameter validator

### ISSUE THREAD

**Issue by slapersonne** [lukeautry/tsoa#296]
This is due to param validator using `property.default` if param is `undefined` or `null`, event if ther is no `property.default`, resulting in null values replaced by undefined.

This is an issue for our team because we use `null` values for deletion of attributes in our PATCH endpoints.

Would it be worth considering to return `property.default` only if there is a default value defined in the `PropertySchema`, and return the value otherwise ?

**Comment by Cerberuser** [comment]
I'd ask whether the nullability should be the default behavior, or should we perform check for union types to find out. For now perhaps default is better, since it's far easier and can be performed by the PRs now in process (#295, #297).

**Comment by slapersonne** [comment]
Closed by #297
