### ISSUE TITLE
Generated routes.ts has a no used parameter in promiseHandler.

### ISSUE THREAD

**Issue by ririgoye** [lukeautry/tsoa#298]
Compiling with     "noUnusedParameters": true    throws an error in generated file:

> routes.ts:321:63 - error TS6133: 'request' is declared but its value is never read.
> 321     function promiseHandler(controllerObj: any, promise: any, request: any, reply: any) {

The parameter is really not used. 
If it can't be removed, please prefix "request" parameter with _ in the template file. 
(tsoa/blob/master/src/routeGeneration/templates/hapi.ts)

**Comment by lukeautry** [comment]
This is fixed in 2.2.4.
