### ISSUE TITLE
authenticationMiddleware return error as JSON directly

### ISSUE THREAD

**Issue by Peekaboo1337** [lukeautry/tsoa#299]
Hello,
is there any way to return a JSON object from the authenticationMiddleware to the caller without changing the template? In some cases I just want to return a plain JSON object to the client to tell the client the reason why the authentication failed and can not work with the generic 401 return.

Best regards

**Comment by Peekaboo1337** [comment]
@lukeautry This looks awesome. Thanks a lot! Will implement!

**Comment by Burnett2k** [comment]
Just commenting to say this helped me out tremendously!  This advice could probably be placed in the main documentation since a lot of developers probably want the functionality to pass back a custom error message.
