### ISSUE TITLE
regarding your commit "handle date as query param": we need the "format:-date-time" in the swagger

### ISSUE THREAD

**Issue by pabloelustondo** [lukeautry/tsoa#30]
Hi Luke,
          Thanks a again but I think you just forgot a little detail. We noticed in your change-set  handle date as query param that you added a "format" to the label definition... but that 'format' does nto appear in the actual swagger.json and, so, it does not look good in the Swagger UI. It still appears as string. I think your just need to add that format to the swagger.json generator.

         Cheers!, Pablo.

**Comment by lukeautry** [comment]
@pabloelustondo Put out a fix for this in 1.0.5 which you can install now.

The problem was that response objects could include the format, but not parameters. Thanks for submitting the issue.

Let me know if you notice any other problems.
