### ISSUE TITLE
Regression:  Recent TsoaRoute.Security interface change is breaking route generation

### ISSUE THREAD

**Issue by jorshali** [lukeautry/tsoa#301]
The issue https://github.com/lukeautry/tsoa/issues/278 has resurfaced in version 2.2.2.  The following commit reverted the interface to it's original signature:

https://github.com/lukeautry/tsoa/commit/3b41bb14c34db464a0bfdfc9c221936671f8410f#diff-b15db146b8a2dfe397cd3f8a96abd3ca

By doing this, the change for https://github.com/lukeautry/tsoa/issues/278 once again generates a route that will not compile.

Note that version 2.2.1 is currently working, only 2.2.2 is affected by the commit described above.  If any further information is needed, please let me know. Thanks for the great project!

**Comment by lukeautry** [comment]
I changed the interface back; having a wide open dictionary type object ([key: string]: string} doesn't make sense when we know all of the possible properties.

What, exactly, is the route compiler error? I think whatever solution we come up with has to not use unsafe object references like what was mentioned above.

**Comment by jorshali** [comment]
That makes perfect sense, but the route generation no longer corresponds to the interface definition.  Here is the compile error:

```
src/routes.ts:188:35 - error TS2322: Type '{ "myAuth": undefined[]; }' is not assignable to type 'Security'.
  Object literal may only specify known properties, and '"azuread"' does not exist in type 'Security'.

188         authenticateMiddleware([{ "myAuth": [] }]),
```

If you need anything further, please let me know.

**Comment by jorshali** [comment]
My controller definition looks like the following:

```
@Route('myRoute')
@Security('myAuth')
export class MyController {
    @Get()
    public async find(@Request() request: any) {
        // ... ...
    }

    // ... ...
}
```

**Comment by lukeautry** [comment]
Ah, looks like this only comes up when doing the controller level Security decorator, not route level...looking into it.

**Comment by lukeautry** [comment]
@jorshali Let me know how 2.2.3 works for you.

**Comment by jorshali** [comment]
2.2.3 works great.  Thanks for the help!
