### ISSUE TITLE
Request is only showing path parameter not full express request

### ISSUE THREAD

**Issue by jk89** [lukeautry/tsoa#302]
Here is my code:

```
import { Get, Post, Route, Body, Query, Header, Path, Request, SuccessResponse, Controller, Patch, Put } from "tsoa";
import * as express from "express";

@Route("StripeMain")
export class StripeMainController extends Controller {

    @Post("createCustomer/{customerToken}")
    public async createCustomer(@Request() request: express.Request | any, customerToken: string): Promise<boolean> {
        console.log(this);

        if (request) {
            console.log("request", request);
            console.log("request.hasOwnProperty", request.hasOwnProperty("user"));
            console.log("request['user']", request.hasOwnProperty("user") ? request["user"] : null );
            console.log(Object.keys(request));
            console.log(request["request"]);
        }
        else {
            console.log("NO REQUEST????");
        }
        return;
    }
}
```

The prints I get as output:

StripeMainController { statusCode: undefined, headers: {} }
request dasdasas
request.hasOwnProperty false
request['user'] null
[ '0', '1', '2', '3', '4', '5', '6', '7' ]
undefined

So the customerToken I set in my request as "dasdasas", I'm looking for request.user which is attached with an app.use( (req, res, next) => {
//some logic todo with auth
req.user = {someUserObject}
} )

So how to I get the express request then as this does not seem to be working for me. I'm using the latest tsoa v^2.2.5

**Comment by jk89** [comment]
I guess my problem is really that my authentication is set within a top level express app which uses many other tsoa express sub apps. And I'm looking for a way to get access to the true request object from express so I can access the request.user from within my controllers. Whatever I've tried so far has just resulted in me getting path parameters as the request object.

```
export function authenticateMiddleware(security: TsoaRoute.Security[] = []) {
    console.log("IN AUTHENTICATION MIDDLEWARE");
    return (request: any, _response: any, next: any) => {
        console.log("request", request);
        request["user"] = request;
        next()
   }
}
```

**Comment by jk89** [comment]
I worked out a technique

**Comment by oreporan** [comment]
What is the solution to do this? my `req.user` is null even when I set it in the middleware

**Comment by dgreene1** [comment]
@oreporan if you can make a small github repository that demonstrates the issue and uses passportJS, I will reopen this issue and fix it in your example repo.

**Comment by WoH** [comment]
Please read: https://github.com/lukeautry/tsoa/pull/488

**Comment by oreporan** [comment]
#488 only speaks about the typescript definition, not the actual `Request` object

Should this work?

```js
app.use(attachUserToRequest)
v1(app); // tsoa
```


```js
export const attachUserToRequest = (req: Request, _res: Response, next: NextFunction) => {
    const {headers} = req;
    const {iss, sub} = getToken(headers.authorization);
    req['user'] = {sub};
    next();
};

```

```js
public async get(
        @Request() request: RequestWithAuthorizedUser
    ): Promise<any> {
        console.log('my user', request.user)
    }
```
