### ISSUE TITLE
latest editorconfig package breaks tsoa

### ISSUE THREAD

**Issue by KyleGalvin** [lukeautry/tsoa#303]
https://www.npmjs.com/package/editorconfig

I was having trouble setting my project up on a new system.. Tsoa commands were failing with a message saying it could not find the editorconfig package.

After some head scratching, it appears a new version has been released hours prior to my install.

adding the previous editorconfig 0.15.0 to my own package.json seems to be a temporary fix even though it is a transitive dependency through tsoa.

**Comment by lukeautry** [comment]
@KyleGalvin I'm not able to reproduce this. Do you have an error message you can share? This is transitive as you point out, tsoa -> typescript-formatter -> editorconfig.

**Comment by lukeautry** [comment]
Closing, but feel free to open if you can reproduce.
