### ISSUE TITLE
typescript delcared as production needed in package.json

### ISSUE THREAD

**Issue by harlequin** [lukeautry/tsoa#304]
The two packages are in the category "dependencies" but shall be moved to "devDependencies" 
to have smaller bundled packages

-  "typescript": "~2.8.4",
-  "typescript-formatter": "^7.2.0",

**Comment by lukeautry** [comment]
@harlequin tsoa actually uses the TypeScript compiler (and the formatter) directly at runtime, so I think it is appropriate and necessary to keep it as a production dependency. It also uses a particular version, so to stay interoperable with multiple TypeScript versions in the client app, this way seems safer.
