### ISSUE TITLE
Validator value 0 does not get checked

### ISSUE THREAD

**Issue by andreasrueedlinger** [lukeautry/tsoa#305]
If you use a validation value of `0` it does not get validated at all:
```ts
export interface Model {
  /**
   * @minimum 0
   */
  myValue: number;
}
```

This bug is caused by the conditions in `templateHelpers.ts` like `if (validators.maximum && validators.maximum.value) {`. You should rather use something like `if (validators.maximum && validators.maximum.value !== undefined) {` to allow 0-values!

**Comment by lukeautry** [comment]
Merged in the fix, will go into next release (> 2.2.5)
