### ISSUE TITLE
"Cannot find module" when executing tests in an environment named "test".

### ISSUE THREAD

**Issue by mlb6** [lukeautry/tsoa#308]
When I execute my tests in the Heroku CI environment, I get a different behaviour and my tests are failing.
I found in the default template that TSOA classes are imported differently if the environment is named "test".

template:
https://github.com/lukeautry/tsoa/blob/55af58611d075335dd3d63728177dfd537d624a8/src/routeGeneration/templates/express.ts#L5

canImportByAlias variable assignation:
https://github.com/lukeautry/tsoa/blob/55af58611d075335dd3d63728177dfd537d624a8/src/routeGeneration/routeGenerator.ts#L70-L76

I think this is probably useful for this repo in order to test the TSOA library, but this prevents users of the library to have an environment called "test".

I know that a workaround is to override the default template or by changing the name of my test environment, but I think this issue should be addressed.

Thanks.

**Comment by lukeautry** [comment]
Fixed in 2.3.2.
