### ISSUE TITLE
Media type versioning

### ISSUE THREAD

**Issue by neuroscar** [lukeautry/tsoa#309]
Hi,
I was wondering if it's possible version an API (implemented with koa) using tsoa for generating the routes, using media type versioning? So one can be able to define something like 
Accept: application/vnd.myname.v1+json for different routes.
Currently as far as I see that is not possible, or I am missing something?

Thanks in advance.

**Comment by lukeautry** [comment]
Not currently. I'd recommend creating a custom route handler for this case, although a stronger versioning story would be great.
