### ISSUE TITLE
Should typescript be a peer dependency?

### ISSUE THREAD

**Issue by lukewis** [lukeautry/tsoa#311]
My project is using Typescript 3.1.6.  My tsconfig.json includes the resolveJsonModule compiler option, however tsoa threw the following error:
```
Error: Unknown compiler option 'resolveJsonModule'.
```
It appears that tsoa lists typescript ^2.8.4 as a dependency.  Indeed, typescript 2.8.4 doesn't support the resolveJsonModule option, but it seems that tsoa should be picking up and using the typescript version my project is using.  I think this behavior would be accomplished if tsoa listed typescript as a peerDependency instead of a "real" dependency.

Thoughts?

**Comment by lukeautry** [comment]
I think we've had it as a peer dependency in the past, but this project uses the TypeScript compiler API directly. The compiler API has breaking changes regularly, so the library would just not work a lot of the time if the peer dependency is the wrong version of TypeScript.
