### ISSUE TITLE
Add support for @default parameter in JSDoc

### ISSUE THREAD

**Issue by joeboyscout04** [lukeautry/tsoa#313]
It would be great if we can add support for an `@default` attribute which would get put into the generated swagger. 

This would probably look similar to #238 just with the default attribute.  This mainly applies in interfaces where there is not an ability to set a default value.

**Comment by lukeautry** [comment]
Is this needed if you're setting a default value for the parameter in the method, e.g.

```
public async GetUsers(isEmployee = true) { ... }
```

**Comment by joeboyscout04** [comment]
We’re looking at the case in interfaces where there’s no method to set.

**Comment by lukeautry** [comment]
Got it.

**Comment by lukeautry** [comment]
@joeboyscout04 Implemented in 2.3.3.
