### ISSUE TITLE
Model validation with optional properties and additionalProperies broken

### ISSUE THREAD

**Issue by dpoetzsch** [lukeautry/tsoa#314]
The following type signature of a request body fails validation at runtime if the optional property `a` is not provided:
```typescript
interface CreationRequestBody {
    a?: string;

    // other keys are allowed as well
    [key: string]: any;
}
```
If I request this endpoint with an empty body I get the following output:
```
{ error: 'ValidateError',
  fields:
   { 'body..a'
      { message: 'No matching model found in additionalProperties to validate a',
        value: 'a' } } }
```

**Comment by endor** [comment]
As far as I know tsoa already allows sending more properties than explicitly defined in that interface. Why add the `[key: string]: any;`?

**Comment by dpoetzsch** [comment]
I did not know about this behavior, thanks for the tip.

Well then, I guess it is more useful for documentation purposes, by explicitly stating that other keys are allowed as well.

**Comment by tpaulshippy** [comment]
We just encountered this issue this morning. Thanks for getting it fixed. Looking forward to the release.
