### ISSUE TITLE
Handling of Response Codes / Types

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#32]
I'd love to have status codes and error response types to be defined in controllers.
So we can have it in swagger:
http://swagger.io/specification/#responsesDefinitionsObject

Example:

  @Get('Foo')
  @Response([200,201,400], [TestModel, void, FancyErrorModel])
  public async getFoo(): Promise<TestModel> {
    throw {
      message: 'error thrown',
      status: 400
    };
  }

Two more key ideas:

1) The default is  @Response([200], [TestModel]) 

2) There is a template to provide a different response code "tsoa.Response"

  @Get('Foo')
  @Responses([200,201,400], [TestModel, TestModel, FancyErrorModel])
  public async getFoo(): Promise<Response<TestModel>> {
    return await Response.withStatus(this.getModel(), 201);
  }

**Comment by isman-usoh** [comment]
@egandro 
```typescript
import {Post, Route, Request, SuccessResponse, Response, Controller } from 'tsoa';

@Route('Users')
export class UsersController extends Controller {

    @Response<ErrorResponse>('Unexpected error') // error response
    @SuccessResponse('201', 'Created') // custom success response
    @Post()
    public async createUser(@Body() requestBody: UserCreationRequest): Promise<void> {
        new UserService().create(request);
        this.setStatus(201); // set return status 201
        return Promise.resolve();
    }
}
```

**Comment by azaeng04** [comment]
@isman-usoh where does `ErrorResponse ` come from in your code?
