### ISSUE TITLE
Bad request explanation

### ISSUE THREAD

**Issue by Dancia** [lukeautry/tsoa#325]
Quoting from the HTTP specification for 400.x error codes:

> The 4xx class of status code is intended for cases in which the client seems to have erred. Except when responding to a HEAD request, the server SHOULD include an entity containing an explanation of the error situation, and whether it is a temporary or permanent condition. These status codes are applicable to any request method. User agents SHOULD display any included entity to the user.

Currently middleware just spits out 400 to user without explanation. I would like to add some explanation for user why his request failed. Example: User POSTS some data, but field is missing. It would be nice to have message in body saying, that field is missing. How do I do that?

How do you suggest to approach this case?

**Comment by crdrost** [comment]
FWIW I was working on a similar problem at US Engineering and what proved to be a really versatile way to handle errors like this in our internal TypeScript+OpenAPI framework was to just have a class for them as throwable. I'm not sure if `tsoa` already does something similar.

Producing code looks like 
```js
async postRequest({ modelId }, ...whatever) {
  if (!is_uuid(modelId)) {
    throw new HTTPError(400, "Model ID must be a UUID.");
  }
  const results = await getObjectsByIDs([modelId]);
  if (results.length === 0) {
    throw new HTTPError(404, `Object with model ID ${modelId} not found.`);
  }
  return doStuffWithObject(results[0]);
}
```

Customizing code looks like
```
class Custom404Error extends HTTPError {
  constructor() {
    super(404, "Not Found");
    this.headers.push(['Content-Type', 'text/plain']); // or whatever?
  }
}
```

and finally the framework itself needs to consume these things but that's as simple as

```js
try {
  // fill in however you'd normally handle sending a response
  const result = await handler(params, whatever);
  res.status(result.status).send(result.byes);
} catch (err) {
  // and if the error is one of these errors then that's cool, it goes just the same way,
  if (err instanceof HTTPError) {
    return res.status(err.status).send(err.bytes);
  }
  // unless it absolutely cannot.
  res.status(500).send("HTTP 500 Internal Server Error");
}
```

Just a thought for how it can be nicely designed in that promise landscape.

**Comment by dgreene1** [comment]
I just added a section in the readme (https://github.com/lukeautry/tsoa#specify-error-response-types-for-swagger) that links to [the preferred way](https://github.com/lukeautry/tsoa/issues/382) of sending a body back that contains the error message. If you have any questions, please let us know. :)
