### ISSUE TITLE
Vulnerabilities in 2.3.8

### ISSUE THREAD

**Issue by eric-caslake** [lukeautry/tsoa#326]
SNYK is flagging TSOA sub-dependencies as vulnerable in version 2.3.8

Low severity vulnerability found in validator
Description: Regular Expression Denial of Service (ReDoS)
Info: https://snyk.io/vuln/npm:validator:20180218
From: tsoa@2.3.8 > validator@8.2.0

Medium severity vulnerability found in mem
Description: Denial of Service (DoS)
Info: https://snyk.io/vuln/npm:mem:20180117
From: tsoa@2.3.8 > yargs@8.0.2 > os-locale@2.1.0 > mem@1.1.0

Recommendations from SYNK:
Upgrade validator to version 9.4.1 or higher.
Upgrade mem to version 4.0.0 or higher.

**Comment by dgreene1** [comment]
@eric-caslake I fixed the vulnerabilities in [this PR](https://github.com/lukeautry/tsoa/pull/357) and a new version of `tsoa` should be getting published soon.
