### ISSUE TITLE
Add release notes or changelog

### ISSUE THREAD

**Issue by surendra-y** [lukeautry/tsoa#327]
Hello,
It will be very helpful if we could have release notes and changelog. That way it will be easier to track new features and bug fixes.

**Comment by dgreene1** [comment]
Thank you. I agree and we've just started doing that. [See here](https://github.com/lukeautry/tsoa/releases). Thank your for being a member of our community. If you wouldn't mind sharing with people on twitter, reddit, or [dev.to](https://dev.to)?

Side note, a bunch of really helpful updates just made it out in version 
 2.4.4: https://github.com/lukeautry/tsoa/releases/tag/v2.4.4
