### ISSUE TITLE
How can we override correctly the error message ?

### ISSUE THREAD

**Issue by Davilink** [lukeautry/tsoa#330]
https://github.com/lukeautry/tsoa/blob/5a39fc2a18e6128cb952ad919d5642348f07c9a4/src/routeGeneration/templateHelpers.ts#L14-L25

If i set a isString, i want to dispay a custom code to indicate that the property wasn't a string, but if the property was missing i want to send a an another code, but if i have this : 
```
ILoginRequest: {
        properties: {
            oId: { dataType: "string", required: true, validators: {
                isString: {
                    errorMsg: "property.invalidType",
                },
                isRequired: {
                    errorMsg: "property.required"
                }
            } },
```

Which one TSOA will use ?

**Comment by bkawk** [comment]
I also want to be able to return a friendly error if the user fails to send a parameter or if the parameter is of the wrong type.
```
export interface IResponse {
  message: string;
  status: string;
  data: any;
}
....
@Route('/user')
export class RegisterController extends Controller {
  /**
   * This is a description of the register user method
   */
  @Post('/register')
  @Tags("Users")
  @OperationId('registerUser')
  @Response<IResponse>('400', 'Bad Request')
  @SuccessResponse('200', 'OK')
```
simply returns...
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>[object Object]</pre>
    </body>
</html>
```

**Comment by dgreene1** [comment]
The information on how to to intercept the error message is described here: https://github.com/lukeautry/tsoa/issues/382

From within your middleware, you have the opportunity to provide whatever formatted response you’d like.
