### ISSUE TITLE
Numeric Enums Still Don't Work

### ISSUE THREAD

**Issue by drdgvhbh** [lukeautry/tsoa#331]
Does this fix actually work? I'm still getting this issue. Currently on `tsoa#2.3.8`

Edit: Looks like it never got in even those this PR got merged. What happened?

_Originally posted by @drdgvhbh in https://github.com/lukeautry/tsoa/pull/106#issuecomment-462087394_

**Comment by drdgvhbh** [comment]
unstale so i can push plz!

**Comment by dgreene1** [comment]
@drdgvhbh I released this in version v2.5.4. Thank you for your contribution! :)
