### ISSUE TITLE
Does Tsoa not support extends the namespace model ?

### ISSUE THREAD

**Issue by linxiaowu66** [lukeautry/tsoa#334]
Hi guys,
   If I use this format to define my definitions, it will report this error: 

```
TypeError: Cannot read property 'kind' of undefined

at TypeResolver.resolveFqTypeName (/Users/linxiaowu/Github/tsoa/src/m
etadataGeneration/typeResolver.ts:293:14)
```

Example definition file as following:

```
declare namespace test {
  export interface Model {
    id: number;
  }
}

export interface TestModel extends test.Model {}
```

any solution about this issue ?

Thanks in advance.

**Comment by chaseoli** [comment]
`extend` should be supported. I had a similar error message before from using a try/catch in the tsoa controller. If this applies to your case instead use promises with `.catch` as an alternative to try/catch.

**Comment by linxiaowu66** [comment]
@chaseoli  `extend` has supported indeed, but if it extend a namespace, it will report error. even if i use try/catch to filter this error,  the entire logic can not generate full docs, is it?

**Comment by alokrajiv** [comment]
Hi. Stuck on the same/similar problem here. My model that extends [`mongoose.Document`.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8c15eef1b9a55d5a15b2a8a0e51efcf1b35bf37c/types/mongoose/index.d.ts#L3235)

I have a controller:
```
@Get()
  public async index(): Promise<MyModel[]> {
    try {
      return await MyModel.find({});
    } catch (error) {
      return error;
    }
  }
```
And the associated Model is:
```
export interface MyModel extends mongoose.Document {
  _id: String;
  foo: String;
  bar: String;
}
```

The above would throw an error during `tsoa routes`:

> There was a problem resolving type of 'MyModel'.
> Generate routes error.
>  TypeError: Cannot read property 'kind' of undefined

Any solution to this problem?

**Comment by dgreene1** [comment]
The solution is to not expose any interfaces from dependencies in your swagger/tsoa models. Basically, just make a copy of the interfaces you got from other libraries and use those instead. Trust me it will work ([see this explanation here on "structural subtyping" as to why this works](https://github.com/lukeautry/tsoa/issues/340#issuecomment-518229063)).
