### ISSUE TITLE
Option to restrict extra properties in request body

### ISSUE THREAD

**Issue by jorshali** [lukeautry/tsoa#336]
TSOA allows sending more properties than explicitly defined in an interface.  For example, if my interface expects an Employee JSON as the body defined as:
```
export class Employee {
  public username: string;
  public firstName: string;
  public lastName: string;
}
```
A caller could send the following body and it would be acceptable:
```
{
  "username": "johndoe",
  "firstName": "John",
  "lastName": "Doe",
  "employeeId": 1234
}
```
I'm requesting an option to disallow this through the tsoa.json configuration.  For example,
```
{
  "routes": {
    ... ...
    "strictProperties": true
  }
}
```
In the example above, the request body with the `employeeId` included would fail as a bad request if the `strictProperties` option was set to true.

To avoid impacting existing APIs this would be false by default.  If any extra properties were provided, a validation error would be returned with a bad request response.

**Comment by dgreene1** [comment]
@jorshali this feature was added via https://github.com/lukeautry/tsoa/pull/385 and released in last version. See the instructions in the updated readme: https://github.com/lukeautry/tsoa#how-to-ensure-no-additional-properties-come-in-at-runtime
