### ISSUE TITLE
[Question] Comparison to inversify-express-utils package

### ISSUE THREAD

**Issue by lonix1** [lukeautry/tsoa#339]
New user here. I was wondering what is the difference between `tsoa` and `inversify-express-utils`?

Not trolling, just trying to understand which is a better fit for my needs. I like the ASP.NET / Spring way of doing things, and I noticed that both packages offer such features.

Are they equivalent or are there any major differences?

**Comment by lukeautry** [comment]
Hey @lonix1 - from what I can see, `inversify-express-utils` does route creation, but it doesn't generate a Swagger specification.

Part of the draw of `tsoa` is that you can generate client SDKs and documentation easily.

**Comment by lonix1** [comment]
@lukeautry Thanks!

**Comment by lonix1** [comment]
@lukeautry Thanks!

I can't put my finger on it exactly, but it seems this library is more well rounded. I think that one was "added" to a container, whereas this one was meant to emulate aspnet/spring (IoC wasn't the point).

**Comment by lukeautry** [comment]
Yeah, I would say that this library was designed, first and foremost, to create real world APIs.

Check out https://github.com/lukeautry/ts-app for a full stack example of how `tsoa` fits in with an entire application.

**Comment by lonix1** [comment]
Wow that is one monster DDD example app! I use angular, but I'm gonna have fun digging into the server side of it! Thanks! You've structured it in a way that I miss from aspnet, in node everything is so... messy! :laughing: 

No IoC though?

**Comment by lukeautry** [comment]
Nope, but I don't think it would be too much trouble to add it in since
tsoa supports inversify.
