### ISSUE TITLE
Bug with Date type.

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#34]
Hi!

I noticed a but with a Date Type:

```
import { Get, Route } from 'swagger-ts';

export interface Hello {
	date: Date;
}

@Route('api/hello')
export class HelloController {
    @Get()
    public async getHello(): Promise<Hello> {
        thow "not implemented";
    }
}

```

/home/foo/projects/spielwiese/swagger-ts-bug/node_modules/swagger-ts/dist/metadataGeneration/resolveType.js:48
        throw new Error(`Multiple matching models found for referenced type ${typeName}; please make model names unique.`);
        ^

Error: Multiple matching models found for referenced type Date; please make model names unique.

**Comment by lukeautry** [comment]
@egandro Having a tough time reproducing this; many of the test project classes have Date types for properties and it's no problem.

What version of Node.js are you using? What version of TypeScript?

To be seeing this error, this line of code must not be working as expected: https://github.com/lukeautry/tsoa/blob/master/src/metadataGeneration/resolveType.ts#L35

**Comment by lukeautry** [comment]
Closing for now.
