### ISSUE TITLE
There was a problem resolving type of xxx

### ISSUE THREAD

**Issue by sshivananda** [lukeautry/tsoa#340]
I am trying to generate routes and swagger using typescript interfaces that are declared inside a module. This module is installed as an external dependency. However tsoa does not seem to be able to resolve references within the same module.

Stack trace
```There was a problem resolving type of 'Identifier'.
There was a problem resolving type of 'fhir.Patient'.
Generate routes error.
 Error: No matching model found for referenced type Identifier.
 in 'UsersController.Create'
    at new GenerateMetadataError (/Users/sshivananda/git/tsoa-fhir-sample/node_modules/tsoa/dist/metadataGeneration/exceptions.js:20:28)
    at /Users/sshivananda/git/tsoa-fhir-sample/node_modules/tsoa/dist/metadataGeneration/methodGenerator.js:60:23
    at Array.map (<anonymous>)
    at MethodGenerator.buildParameters (/Users/sshivananda/git/tsoa-fhir-sample/node_modules/tsoa/dist/metadataGeneration/methodGenerator.js:53:47)
    at MethodGenerator.Generate (/Users/sshivananda/git/tsoa-fhir-sample/node_modules/tsoa/dist/metadataGeneration/methodGenerator.js:42:30)
    at /Users/sshivananda/git/tsoa-fhir-sample/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:40:58
    at Array.map (<anonymous>)
    at ControllerGenerator.buildMethods (/Users/sshivananda/git/tsoa-fhir-sample/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:40:14)
    at ControllerGenerator.Generate (/Users/sshivananda/git/tsoa-fhir-sample/node_modules/tsoa/dist/metadataGeneration/controllerGenerator.js:29:27)
    at /Users/sshivananda/git/tsoa-fhir-sample/node_modules/tsoa/dist/metadataGeneration/metadataGenerator.js:59:58
``` 

The controller file looks like
```import {Route, Post, Body} from 'tsoa';
import 'fhir';

@Route('Users')
export class UsersController {

    /** 
     * Create a user 
     * @param request This is a user creation request description 
     */
    @Post()
    public async Create(@Body() request: fhir.Patient): Promise<void> {
        return;
    }

}
```

The interfaces are defined in an index.d.ts file which looks like
```
declare module fhir {
...
   interface Identifier extends Element {
        /**
         * usual | official | temp | secondary (If known)
         */
        use?: code;
   }
...
   interface Patient extends DomainResource {
        /**
         * An identifier for this patient
         */
        identifier?: Identifier[];
   }
...
}
```

If I fully qualify the reference to Identifier (as fhir.Identifier) then this error goes away - but then there are other attributes where it starts complaining.

A sample repo to reproduce this problem is at https://github.com/sshivananda/tsoa-fhir-sample/tree/feature/use-fhir-interfaces

**Comment by leolorenzoluis** [comment]
Same issue here.

**Comment by sshivananda** [comment]
Ended up working around by creating definitions that are fully qualified

**Comment by Bucky24** [comment]
I am running into the same issue.

`There was a problem resolving type of 'SimulationModels.CookingSimulationResult'.
Generate routes error.
 Error: No matching module declarations found for SimulationModels.`

TSC has no issue with this code, this seems to be a tsoa issue only.

**Comment by Bucky24** [comment]
Figure out that my issue was because my interfaces were coming from a separate module, being exported like this:

```
import * as SimulationModels from './models/simulation_models';

export {
    SimulationModels
}
```

TSOA doesn't appear to recognize this as a typescript object, which is fair, since it's not, but typescript itself has no problem with it. Moving the interfaces out of the external module solved the issue.

**Comment by sipanmargaryan** [comment]
Is there anyone who solved this issues ?

**Comment by dgreene1** [comment]
The solution is to make a copy of the interface that lives inside of your repo and that is not a dependency.

So for your problem, please create interfaces like this:
```ts
   // inside of your own ./src/models/patientModel.ts
   interface Identifier extends Element {
        /**
         * usual | official | temp | secondary (If known)
         */
        use?: code;
   }
   interface Patient extends DomainResource {
        /**
         * An identifier for this patient
         */
        identifier?: Identifier[];
   }
```

So instead of including the external dependency, include your internal representation:
```
import { Patient } from 'src/models/patientModels';

@Route('Users')
export class UsersController {

    /** 
     * Create a user 
     * @param request This is a user creation request description 
     */
    @Post()
    public async Create(@Body() request: fhir.Patient): Promise<void> {
        return;
    }

}
```

Thankfully, due to TypeScript's structural subtyping, the code won't care if the interfaces have different names. TS only cares that the data has the same structure. So this should not be a problem.

As an additional bonus, your API consumers will be happier because they won't get a broken contract change whenever you decide to update your external library. You now have an abstraction layer that you can transform into whatever the new version of your external library requires. Essentially your API consumers are blind to your internals (as they should be).

**Comment by Burnett2k** [comment]
> Ended up working around by creating definitions that are fully qualified

@sshivananda do you mind sharing what that looked like? I'm in the same boat right now and the Interfaces I'm trying to use are way to large for it to be scalable to create my own Interfaces for each of them. Ironically, I'm also using the Patient FHIR type.

**Comment by dgreene1** [comment]
The solution is here: https://github.com/lukeautry/tsoa/issues/340#issuecomment-518229063

**Comment by AmitThakkar** [comment]
I had a similar issue and below the compiler option in `tsoa.json` solved it:
```
    "compilerOptions": {
      "paths": {
        "custome-module": ["libs/custome-module/src/index.ts"]
      }
    }
```

https://github.com/lukeautry/tsoa/blob/master/packages/runtime/src/config.ts#L40

**Comment by nickzylstra** [comment]
> I had a similar issue and below the compiler option in `tsoa.json` solved it:
> 
> ```
>     "compilerOptions": {
>       "paths": {
>         "custome-module": ["libs/custome-module/src/index.ts"]
>       }
>     }
> ```
> 
> https://github.com/lukeautry/tsoa/blob/master/packages/runtime/src/config.ts#L40

official docs for anyone else landing here: https://tsoa-community.github.io/docs/path-mapping.html#path-mapping
