### ISSUE TITLE
Support anonymous implicit return types

### ISSUE THREAD

**Issue by wolever** [lukeautry/tsoa#341]
Currently the return type of a route needs to be explicitly named (even if not explicitly defined):

```typescript
@Get()
getWidget() {
  return new Widget()
}
```

But anonymous implicit return types are not supported:

```typescript
@Get()
getStatus() {
  return { status: 'working' }
}
```

I would propose (and volunteer to implement) a feature that will infer anonymous return types, then generate a corresponding model based on TypeScript's inferred type.

For example, the above example would generate the model:

```
const models: TsoaRoute.Models = {
  "GetStatusResult": {
    "properties": { "status": { "dataType": "string" } },
  },
};
```

Has this been attempted? And would a pull request for this be considered?

**Comment by dgreene1** [comment]
It's not entirely clear what you mean by "anonymous." Can you explain what value this would provide?

**Comment by wolever** [comment]
@dgreene1 "anonymous" in the sense that the return type has been inferred by TypeScript without explicitly defining a type / interface. From he example above:

```typescript
@Get()
getStatus() {
  return { status: 'working' }
}
```

Would generate a model similar to

```
const models: TsoaRoute.Models = {
  "GetStatusResult": {
    "properties": { "status": { "dataType": "string" } },
  },
};
```

The value would be better consistency with TypeScript (which makes no distinction between returning named types - ex `new Widget()` - and anonymous structures - ex `{ status: 'working' }`).

**Comment by endor** [comment]
To me this sounds like something worth having in tsoa. The only question for me would be how to document it. While it’s nice to support this, the recommended way should be a model, in my opinion, as that allows more documentation, and even just the name is or could be already documenting intent.

**Comment by dgreene1** [comment]
You reminded me of an important point @endor which is that the documentation (the Swagger json) would need a name for the model that is produced, right? So in order to support this, wouldn’t we need to dynamically generate a name behind the scenes? And that seems kind of silly to me when the developer can simply name the interface themselves.

**Comment by dgreene1** [comment]
Having slept on this, I agree that we should be explicit about interface names like others have said:

> as that allows more documentation, and even just the name is or could be already documenting intent.

Additionally, I think it's dangerous to have contracts that can "move." In other words, if the contract changes, consumers should know. I think having a statically defined interface is more aligned with the design goals of tsoa: namely to be clear about inputs and outputs.

So while it's a cool idea @wolever. I'm going to close this.
