### ISSUE TITLE
Cannot load generated swagger-ui from behind nginx

### ISSUE THREAD

**Issue by arketec** [lukeautry/tsoa#343]
The swagger-ui generated by TSOA works without issue locally, but when it is put behind a reverse proxy like Nginx, swagger UI fails with a 502 Gateway error. It seems to be ignoring the path set by Nginx (which makes sense), but I cannot seem to be able to find an option to change the path that swagger ui looks for swagger.json.

Here is some examples of what I am talking about.

Example localhost:
localhost:3000/api/docs  ----> loads swagger UI

Example nginx:
fakedomain.com/nginx/path/api/docs  -----> redirects to fakedomain.com/api/docs (502 error)

Is there a way to tell the swagger ui generator to append the nginx path (/nginx/path/) before looking for swagger.json?

I tried using the basePath parameter in tsoa.json, but it did not work

**Comment by lukeautry** [comment]
I think this is going be an issue with swagger-ui or your server. Generally, I've ended up serving swagger.json at some arbitrary static asset directory and pointing scripts/docs pages at it. I believe swagger-ui supports providing a custom swagger.json path. The spec file should be interpreted as a standalone document; no server context should be inferred from the path it is served from.

**Comment by arketec** [comment]
ok, I'll look into it with swagger-ui. thanks for the response
