### ISSUE TITLE
Only 'multi' collectionFormat is supported for array query parameters

### ISSUE THREAD

**Issue by seanprince** [lukeautry/tsoa#351]
There's no way to specify a query parameter array's collectionFormat - it is always set to 'multi'. So I can't create an API like this:

`GET /stuff?status=Active,Pending`

I am forced to create the API like this:

`GET /stuff?status=Active&status=Pending`

**Comment by taschmidt** [comment]
Can we reopen this? I would love it if this was supported so I could have a strongly-typed spec rather than just a generic `string` parameter that I have to call `.split(',')` on myself!

**Comment by WoH** [comment]
We support multi as it is what the querystring parser does by default.
If this is something you need, please take a look at https://github.com/lukeautry/tsoa/issues/810
