### ISSUE TITLE
updating to Swagger OpenApi 3

### ISSUE THREAD

**Issue by oreporan** [lukeautry/tsoa#355]
There are alot of great additions in [OpenApi 3](https://swagger.io/blog/news/announcing-openapi-3-0/)
I could take a try on updating

**Comment by dgreene1** [comment]
There's an open PR to support Open API 3, but it is stale and currently has merge conflicts: https://github.com/lukeautry/tsoa/pull/249

I'm closing this issue since it can be tracked in that link above.
