### ISSUE TITLE
how to correctly generate OpenAPI 3 document

### ISSUE THREAD

**Issue by Kampfmoehre** [lukeautry/tsoa#358]
Hi, I was trying the new OpenAPI 3 generation from [this pull request](https://github.com/lukeautry/tsoa/pull/249) but I wonder if I'm doing something wrong. There is no documentation so far, so I looked at the code, and figured out, I have to set the swagger.version property to 3.x. This is generating me an OpenAPI 3 compatible document, but isn't this also the field where I would set the application version? In the final document, the application version is always 3.0.0 now instead of the value from the package.json like before. Is this intended or am I missing something?

~~Also I would like to know, if it is planned to support config for multiple hosts or adding a cli option for the scheme. When generating for local testing, I want to use http, but the production and test servers of course use https. Right now it only uses the first value from the config, with no way to change that on generation.~~
Edit: Never mind, I figured that setting multiple schemes allows to change them in the Swagger UI.

Thanks for the info.

**Comment by 0v3rst33r** [comment]
Yes @Kampfmoehre I also noticed now that the `SpecGenerator` version and the API version are now the same thing.  So if my API version happens to be in the `3.x.y` range then only the `SpecGenerator3` version will kick in.

The `SwaggerConfig` type at the moment has a property:
```
  /**
   * API version number; defaults to npm package version
   */
  version?: string;
```

Can it have a `specVersion` property as well where one can override the default `2` with `3` when one wants to generate `OpenAPI 3`?

Then the `src/module/generate-swagger-spec.ts` file can rather check:
```
if (config.specVersion && config.specVersion === '3') {
```

This way the `OpenAPI spec` and `application API` versions can be decoupled.

Any thoughts on this @endor, @dgreene1 ?

I will be happy to apply such a change and submit a PR for it if the above suggested changes would be the acceptable approach.

**Comment by endor** [comment]
Sounds good to me.

**Comment by 0v3rst33r** [comment]
@endor I added PR #359 for the above.

**Comment by lukeautry** [comment]
#359 merged.
