### ISSUE TITLE
Add option to change output filename

### ISSUE THREAD

**Issue by HoldYourWaffle** [lukeautry/tsoa#360]
The `routes.ts` output filename is currently hard coded:
https://github.com/lukeautry/tsoa/blob/7c9dbd0798340c04721dfdca3f2fd31d8be3aca8/src/routeGeneration/routeGenerator.ts#L26

I'd love to have an option to change this filename. I was going to make a PR for this, but the fact that such a trivial thing hasn't been implemented yet makes me wonder if there's an actual reason for it.

**Comment by lukeautry** [comment]
There really isn't a reason. Feel free to PR to make it configurable.

**Comment by HoldYourWaffle** [comment]
#361

**Comment by dgreene1** [comment]
@HoldYourWaffle what is the value in having the file name be different?

I believe there is a larger value in that if you’re a developer who is familiar with tsoa then you know that there will be a routes.ts file in the project. This provides consistency so that developers familiar with tsoa can move from project to project.

That’s why I’m wondering what the value is for changing the file name. It would have to be higher value than the benefit of consistency.

**Comment by HoldYourWaffle** [comment]
The reason why I want to change filenames is because I use custom templates to generate both the server routes *and the client SDK* using TSOA. Having `client.ts` and `server.ts` makes a lot more sense in that case.

I do this because I want more control over generated code. Because both sides are in Typescript for me, Swagger/OpenAPI is an unnecessary middleman (and just generally very unhelpful). This also allows me to *easily* share things like type definitions across sides which is always very helpful.

**Comment by pdeak** [comment]
This feature is also very important for the swagger.json file. As of version 3 of the spec, it is no longer called Swagger. It is OpenAPI. It is wrong and misleading to call the output swagger.json.

It's more than just aesthetic though:  Visual Studio Code with the openapi-lint extension automatically picks up *swagger.json files as OAS2, and therefore the linting and intellisense is broken until the file is renamed to openapi.json, which it will treat as OAS3.

**Comment by HoldYourWaffle** [comment]
I completely forgot that there's another filename that generates when creating the PR, we should definitely fix that.

@dgreene1 Should we create a new issue of this or reopen this one?
I'd be happy to implement this, should I go for the same approach as with router generation?

**Comment by dgreene1** [comment]
Sure I'll reopen this issue so you can add that @HoldYourWaffle. And@pdeak we'll get working on that for you. :)

**Comment by HoldYourWaffle** [comment]
@dgreene1 Can you please assign me to this issue so I don't forget?

**Comment by deakster** [comment]
Thanks guys

**Comment by pdeak** [comment]
Thanks guys

**Comment by edbrannin** [comment]
I'd like to take a stab at renaming swagger.json/yaml.

Naming things is hard; any thoughts on what you'd want the setting to be called?  I see `outputDirectory` and `yaml` are the related settings in play.

Maybe `outputFilename`?  But it would default to `swagger` and not `swagger.json`, so maybe `outputBasename`?

**Comment by dgreene1** [comment]
I like `outputBasename` and `outputNameMinusExtension`. Please choose whichever name of those two that you’d like and start the PR. If any reviewers have a strong preference they can let you know during the PR review. Thank you so much! :)

**Comment by calvinwyoung** [comment]
@edbrannin @WoH Are there any plans to complete PR #589? I'd also love the ability to rename the swagger.json file
