### ISSUE TITLE
DELETE body is not supported

### ISSUE THREAD

**Issue by alex-borkun** [lukeautry/tsoa#362]
Hi,

Http request Body used with Delete method throws the following error:
> Error: @Body('request') Can't support in DELETE method.

[https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request](https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request)
> The spec does not explicitly forbid or discourage it, so I would tend to say it is allowed.

As per Quote from SO: request body is not forbidden according to Spec.
Can you please allow it?

**Comment by dgreene1** [comment]
If anyone is looking for an easy first contribution, this one is super easy. Check out this code as a jump start: https://github.com/lukeautry/tsoa/blob/f47caefdedb8cc62200886c81135b7be4070f317/src/metadataGeneration/parameterGenerator.ts#L56

@alex-borkun please consider submitting a PR for this if it's still a feature if it's still something you're interested in. We apologize for the slow response, there weren't many maintainers on this project at this time. Now I've been added along with a few others. So hopefully tsoa is still something that you're interested in using. We'll merge the PR and publish a new version in short order once someone submits it.
