### ISSUE TITLE
Compilation error in test using TypeScript 3.5.1

### ISSUE THREAD

**Issue by HoldYourWaffle** [lukeautry/tsoa#363]
While making some modifications to expand the possibilities of custom templates I encountered the following compile time error after I updated TypeScript 3.5.1. It doesn't look like a TypeScript bug to me, I think TS 3.2.2 simply didn't catch this mistake(?) before.

The error occurs here:
https://github.com/lukeautry/tsoa/blob/f7c0f17ae592045cae6fea3fb56db752a4677eb2/tests/prepare.ts#L13-L28

### Explanation
This index type says that values inside `securityDefinitions` can only be of the `Swagger.Security` type:
https://github.com/lukeautry/tsoa/blob/f7c0f17ae592045cae6fea3fb56db752a4677eb2/src/config.ts#L100-L102

https://github.com/lukeautry/tsoa/blob/f7c0f17ae592045cae6fea3fb56db752a4677eb2/src/swagger/swagger.ts#L328-L334

The `tsoa_auth` value is the one causing the error.
The TypeScript compiler doesn't give a very helpful explanation (probably due to the inferance-heavy type structure we have going on here) but it comes down to the fact that the value of `tsoa_auth` doesn't match any of the types in the aforementioned union.

With the power of the human brain I can infer that the value is probably supposed to be a `OAuth2ImplicitSecurity` because it's the only one with `flow: "implicit"`.
https://github.com/lukeautry/tsoa/blob/f7c0f17ae592045cae6fea3fb56db752a4677eb2/src/swagger/swagger.ts#L292-L297
This type is not a match however because there's an additional `scopes` property. This property would suggest that `tsoa_auth` is actually supposed to be an `OAuth2PasswordSecurity`, `OAuth2ApplicationSecurity` or an `OAutch2AccessCodeSecurity`, but none of these can be matched because of missing properties and the different `flow` value.

### Solutions
I'm not 100% sure what the generated spec is used for, but I think there are roughly 3 solutions:
1. Add an `any` type assertion. This solves the compilation error but I wouldn't recommend it for obvious reasons.
2. Remove the `scopes` property. This way the value would be properly typed as `OAuth2ImplicitSecurity`.
3. Something else. If the generated spec is used somewhere to verify that scoped securities are generated correctly we should probably think of a different solution like adding a separate security definition with one of the scoped security types.

**Comment by dgreene1** [comment]
This issue was fixed by PR https://github.com/lukeautry/tsoa/pull/375
