### ISSUE TITLE
Dependency Injection / Possible issue with reflect-metadata

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#37]
I'd like to add dependency injection to the controllers. I am no expert on IoC / DI frameworks on JavaScript, but i found this nice project: http://inversify.io/

There are some issues when using the required reflect-metadata npm package in swagger-ts.

The decorators can't be compiled correctly. No idea if I am just to stupid to use inversify or if there is a real issue.

But as reflect-metadata is a pretty common package, we should have a look at this.

**Comment by AmazingTurtle** [comment]
I‘m using inversify and it works like a charm with tsoa. Please state if your issue still persists. If so, please provide formatted sample code.

**Comment by egandro** [comment]
Can be closed. This was fixed ages ago.

**Comment by dgreene1** [comment]
> Can be closed. This was fixed ages ago.
