### ISSUE TITLE
Support for mapped types (including Omit)

### ISSUE THREAD

**Issue by manast-apsis** [lukeautry/tsoa#372]
Currently TSOA is not generating correct models for MappedTypes, and for some of them, like Omit it just giving an error:
```
There was a problem resolving type of 'Omit'.
There was a problem resolving type of 'MyModel'.
Generate swagger error.
 Error: Multiple matching models found for referenced type Omit; please make model names unique.
```

In particular Omit is really important when implementing Rest Apis. You may have a Model class, that represents all the fields part of the model, some may be mandatory other optional, however, in the REST api you will not support all these fields, for example, your model may have a "id" field, which is mandatory but it is autogenerated by the database when the model is stored. This is solved perfectly with the Omit type, unfortunately is not supported.
Would also be grateful for a workaround if you know any.

**Comment by dgreene1** [comment]
@manast-apsis we'd be open to a PR for this if you'd be interested in enhancing tsoa to support this.

**Comment by dgreene1** [comment]
I'll add this to the roadmap/project for version 3 of tsoa.

@fhewitt I'm cc'ing you hear so we can continue the conversation here that you started in #500

**Comment by fhewitt** [comment]
Ha I missed this one, searched for "Utility" based on TypeScript doc and "Pick". I re-add the documentation link form my ticket: https://www.typescriptlang.org/docs/handbook/utility-types.html

Same point than @manast-apsis : all utility types would be great, but `Omit` and `Pick` are probably the most the commons in the context of REST API.

Searching for a workaround and investigating further, I've tested handmade MappedType:
```
export type PickTest<T, K extends keyof T> = {
    [P in K]: T[P];
};
```
It didn't work either. But does not raise any error at swagger/routes generation. The object that use PickTest is generated in swagger file but with empty properties.

That seems to be a worst issue because it fail only at run time.

**Comment by fhewitt** [comment]
Also strongly linked with #469 which is a duplicate too.

**Comment by lucas-rudd** [comment]
@fhewitt any update on this? Or, has any work already been started?
Support for Pick would be fantastic, it allows our code base to be a bit more maintainable to just Pick properties from an Interface rather than create an entire new type for request/responses of our REST APIs.

**Comment by WoH** [comment]
There's a PR up #505 where you can track the progress. Please refrain from asking for ETAs but feel encouraged to take a look and submit your review if you're interested in seeing this go live.

**Comment by manast-apsis** [comment]
The mentioned PR #505 I am afraid does currently not resolve this issue.

**Comment by givethemheller** [comment]
@WoH Sorry for the multiple PR's in action - this particular issues has become the biggest blocker for me. Without utility types, I cannot define a base type and then create restricted sub types.
e.g.
```
RecordMaster 
RecordUser extends Pick<RecordMaster, "userData1" | "userData2">

```
I have created a branch and currently have working features for Pick, Omit and Partial when the utility is used inside of an interface definition.

If the utility interface is used in the declaration, it is not working.
e.g. 
```
export interface Record {
   goodType: string
   redactType: string
}

// Fails
export interface RedactedRecord extends Pick<Record, "goodType"> {}
```

When I run my tests with 
```
export interface TestModel extends Model, Pick<Record, "goodType"> {
   ...
}
```
goodType does not show up in the object data . The id property does still show up. 

Where in the process is the iterfaces extend's properties parsed?
How do you guys feel about the way I implemented the utility types?

It seemed like there should be a more typescripty way to do it, but this is what I could make work?

**Comment by WoH** [comment]
@givethemheller the 3.x branch/releases include support for this in a more generally applicable approach. Are there any issues with these? If so, please open up a new issue.

**Comment by givethemheller** [comment]
> @givethemheller the 3.x branch/releases include support for this in a more generally applicable approach. Are there any issues with these? If so, please open up a new issue.

I think I am realizing that a bunch of issues im having may be 3.x resolved.
npmjs isn't showing your 3.X release as current release level and when you check versions with intellisense it shows 2.5.x as latest. is that by intent?

https://www.npmjs.com/package/tsoa

**Comment by givethemheller** [comment]
also - sorry for re-opening. You should go ahead and lose this back out. I'm having some issues with this in 3.x - will re-open

**Comment by bytenik** [comment]
This isn't working for me in the latest version; I get:

> Error: No matching model found for referenced type Omit. If Omit comes from a dependency, please create an interface in your own code that has the same structure. Tsoa can not utilize interfaces from external dependencies. Read more at https://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD

The type in question is:
```
export interface NewIndicator extends Omit<IndicatorBase, 'formula'> {
    ownerId?: string | null;
    formula?: string;
}
```
