### ISSUE TITLE
Inject express response object to render specific view

### ISSUE THREAD

**Issue by maxfouquet** [lukeautry/tsoa#376]
Hi,

I use pug view engine and i would like to render view inside my controller

```javascript
import { Route, Get, Tags, Controller, Response } from 'tsoa'

@Route('/')
export class IndexController extends Controller {
    @Get('/')
    @Tags('Index')
    public index(@Response() res: Express.Response): any {
        res.render('index', { title: 'Welcome' })
    }
}
```

An idea to get around this?

**Comment by dgreene1** [comment]
When you say “get around this” what do you mean by “this?”

I think we’ll need more information to help you.

**Comment by maxfouquet** [comment]
It's possible to catch the Express.Request object like that : 

```
import { Route, Get, Tags, Controller, Request } from 'tsoa'

@Route('/')
export class IndexController extends Controller {
    @Get('/')
    @Tags('Index')
    public index(@Request() req: Express.Request): any {
     
    }
}
```

How can I get Express.Response object inside a controller using a decorator ?

**Comment by irstavr** [comment]
@maxfouquet I see you closed this issue - may I ask if you found any workaround at the end? I'm facing the same issue.. Thank you in advance 🌷
