### ISSUE TITLE
Request for new release for security

### ISSUE THREAD

**Issue by sg2231** [lukeautry/tsoa#380]
Hi,

Could you please publish a new release. We have some security issues from dependencies. 

With regards to snyk:

https://app.snyk.io/test/npm/tsoa/2.4.3?vulns%5B0%5D=vulnerable&vulns%5B1%5D=all&tab=issues

Latest version of package.json has already mitigated them.

Thanks

Svenn Helge

**Comment by dgreene1** [comment]
coming soon @sg2231 once we merge and release https://github.com/lukeautry/tsoa/pull/385. We're waiting on people to agree on the name for the new config option in https://github.com/lukeautry/tsoa/pull/385.

**Comment by dgreene1** [comment]
@sg2231 I just released version 2.4.4 which contains the secure versions. Thank your for being a member of our community. If you wouldn't mind sharing with people on twitter, reddit, or [dev.to](https://dev.to)?

Also, there were a bunch of other enhancements. Check those out in: https://github.com/lukeautry/tsoa/releases/tag/v2.4.4
