### ISSUE TITLE
How to Verify Endpoints Headers and Params via Auto-generated Swagger UI

### ISSUE THREAD

**Issue by luli0822** [lukeautry/tsoa#390]
Hello,

As addressed in the headline, is there a way to try out the endpoints with parameters annotated with @Path(), @Header(), @Query() in the endpoint?

**Comment by dgreene1** [comment]
There are many examples on how to use those decorators in this directory: https://github.com/lukeautry/tsoa/tree/master/tests/fixtures/controllers

And you can see those tested in the following test files:
https://github.com/lukeautry/tsoa/tree/master/tests/integration

As fare as "a way to try out the endpoints", I would recommend installing `tsoa` and give it a shot. If you want a test area, you can use this example repo:
https://github.com/lukeautry/ts-app
or if you want one that works in koa (and that has a SQL backend), you can use this more experimental example repository:
https://github.com/dgreene1/tsoa-koa-example-with-typeorm

**Comment by luli0822** [comment]
> There are many examples on how to use those decorators in this directory: https://github.com/lukeautry/tsoa/tree/master/tests/fixtures/controllers
> 
> And you can see those tested in the following test files:
> https://github.com/lukeautry/tsoa/tree/master/tests/integration
> 
> As fare as "a way to try out the endpoints", I would recommend installing `tsoa` and give it a shot. If you want a test area, you can use this example repo:
> https://github.com/lukeautry/ts-app
> or if you want one that works in koa (and that has a SQL backend), you can use this more experimental example repository:
> https://github.com/dgreene1/tsoa-koa-example-with-typeorm

I am sorry that I didn't address the question clearly, which was to figure out how to verify the endpoints using @Path() for example through autogenerated Swagger UI. But I think this might get done when we have the issue #389 resolved. Thanks very much for your prompt response.

**Comment by dgreene1** [comment]
@luli0822 you should be able to experiment with the validation that comes with the decorators even while your swagger.yaml is invalid. That's due to the fact that the validation is unrelated to the swagger.yaml. To see this, try hitting your API from [Postman](https://www.getpostman.com/) instead of Swagger UI. You'll see that you get the validation as expected.

**Comment by luli0822** [comment]
> @luli0822 you should be able to experiment with the validation that comes with the decorators even while your swagger.yaml is invalid. That's due to the fact that the validation is unrelated to the swagger.yaml. To see this, try hitting your API from [Postman](https://www.getpostman.com/) instead of Swagger UI. You'll see that you get the validation as expected.

Yes, it works well via Postman, but my client wanted to use Swagger if feasible.

**Comment by dgreene1** [comment]
> my client wanted to use Swagger if feasible

Yes, this other issue should be resolved now, see the other comment thread: https://github.com/lukeautry/tsoa/issues/389#issuecomment-520892764

And this issue we're currently in was resolved by the fact that tsoa does the request validation for you.
