### ISSUE TITLE
Support dyanimc controllers import glob

### ISSUE THREAD

**Issue by joni7777** [lukeautry/tsoa#395]
Hey!

I think it could nice to add an option to the routes config (later on to the swagger as well) to support controllers glob like RoutingControllers library

Example in the PR

**Comment by dgreene1** [comment]
@joni7777 I just released version 2.4.4 which contains this work. Thank your for being a member of our community. If you wouldn't mind sharing with people on twitter, reddit, or [dev.to](https://dev.to)?

Also, there were a bunch of other enhancements. Check those out in: https://github.com/lukeautry/tsoa/releases/tag/v2.4.4
