### ISSUE TITLE
Generate a property for readonly constructor args

### ISSUE THREAD

**Issue by WoH** [lukeautry/tsoa#403]
Follow up on #397:

Before #397:
```
export class TestClassModel {
  constructor(
    public publicConstructorVar: string,
    protected protectedConstructorVar: string,
    defaultConstructorArgument: string,
    readonly readonlyConstructorArgument: string,
    public optionalPublicConstructorVar?: string,
  ) {
  }
}
```

would generate properties for: `publicConstructorVar, defaultConstructorArgument, readonlyConstructorArgument, optionalPublicConstructorVar`.

After #397:
`publicConstructorVar, optionalPublicConstructorVar`

This is according to my understanding of the [TypeScript Specification for constructor parameters](https://github.com/microsoft/TypeScript/blob/master/doc/spec.md#831-constructor-parameters).

However, as it turns out, this is valid TS and `readonlyConstructorArgument` is accessible:

```
class ReadonlyClass {
  constructor(
    readonly readonlyConstructorArgument: string,
  ) {
  }
}

new ReadonlyClass("oh hi").readonlyConstructorArgument // => "oh hi"
```

Therefore, I think these parameters should generate properties:
`publicConstructorVar, readonlyConstructorArgument, optionalPublicConstructorVar`

Pinging @dgreene1, sorry for bothering you again, I hope I was able to make my issue coherent this time.
PR is at #402

**Comment by dgreene1** [comment]
#402 merged
