### ISSUE TITLE
Fileglob for Swagger doc generation

### ISSUE THREAD

**Issue by lucas-rudd** [lukeautry/tsoa#413]
Currently, the `entryFile` parameter takes a single argument.

With micro-service usage, consumers may have many services defined and independently deploy-able within a mono-repo.

Base files (such as tslint, tsconfig, etc) may be put at the root level for project level configuration, while others may be nested within the services.

The proposal here is to add support for an `entryFiles` key, which may be a fileGlob pattern, which will recursively generate routes based on the pattern provided, and output them in a location. This will allow for a single `tsoa.json` file at the root directory, and perhaps in the future, we could allow for an `extends` keyword in a subdirectory's `tsoa.json` to overwrite settings in the parent config.

The tsoa config at the root level would look some thing like this

```
{
    "swagger": {
        "outputDirectory": "./docs",
        "entryFiles": "./src/services/**/index.ts",
        "basePath": "/v1/api",
        "yaml": true,
        "specVersion": 2
    }
    ...
}
```

**Comment by dgreene1** [comment]
@lucas-rudd I am curiously waiting for mono-repos to become officially supported by typescript (you can [check out the future plans for official mono-repo support in TypeScript here](https://github.com/microsoft/TypeScript/issues/25600)). Until that happens, I'd really like to wait on adding that into tsoa since it could be subject to change.

So in the meantime, I would recommend that you use tsoa programmatically (you can see the readme for more information).

Here's how I would write a `tsoaCustomRunner.ts` it if I were trying to meet your needs:
```ts
import * as tsoa from 'tsoa';
import * as fs from 'fs';
import * as path from 'path';

function createDirRegardless(dirPath: string): void {
	if (!fs.existsSync(dirPath)) {
		fs.mkdirSync(dirPath);
		// tslint:disable-next-line: no-console
		console.log(`Created directory: ${dirPath}`);
	} else {
		// tslint:disable-next-line: no-console
		console.log(`This directory already existed so we'll keep moving: ${dirPath}`);
	}
}

async function main(): Promise<'done'> {
	// tslint:disable-next-line: no-console
	console.log('Started the tsoa generation');

	const buildDirectory = path.join(__dirname, 'build');
	const staticFileServingDir = path.join(buildDirectory, 'staticFilesToBeServed');
	createDirRegardless(buildDirectory);
	createDirRegardless(staticFileServingDir);

	const baseConfig: tsoa.SwaggerConfig = {
        outputDirectory: 'OVERRIDE ME PLEASE',
        entryFile: 'OVERRIDE ME PLEASE',
        host: 'localhost:3000',
        basePath: '/api/v1',
        noImplicitAdditionalProperties: true,
        yaml: true,
    };

    const configsPerMicroService: tsoa.SwaggerConfig[] = [
        createConfigForAMicroService({ baseConfig, partialConfig: {
            outputDirectory: staticFileServingDir,
            entryFile: path.resolve(path.join(__dirname, './src/services/microService1/index.ts'))
        }}),
        createConfigForAMicroService({ baseConfig, partialConfig: {
            outputDirectory: staticFileServingDir,
            entryFile: path.resolve(path.join(__dirname, './src/services/microService2/index.ts'))
        }}),
        createConfigForAMicroService({ baseConfig, partialConfig: {
            outputDirectory: staticFileServingDir,
            entryFile: path.resolve(path.join(__dirname, './src/services/microService3/index.ts'))
        }}),
    ]

    for (const aConfig of configsPerMicroService) {
        await buildSwaggerAndRoutes(aConfig);
    }

	return 'done';
}

function createConfigForAMicroService(input: {
    baseConfig: tsoa.SwaggerConfig,
    partialConfig: Partial<tsoa.SwaggerConfig>
}): tsoa.SwaggerConfig {
    return Object.assign({}, input.baseConfig, input.partialConfig);
}

async function buildSwaggerAndRoutes(swaggerConfig: tsoa.SwaggerConfig){
    const swaggerGenerationResult = await tsoa.generateSwaggerSpec(swaggerConfig);
	// tslint:disable-next-line: no-console
	console.log(`Generated swagger doc at: ${swaggerConfig.outputDirectory}`);

	const routeGenArgs: Parameters<typeof tsoa.generateRoutes> = [
		{
			basePath: '/api/v1',
			entryFile: './src/index.ts',
			middleware: 'koa',
            routesDir: './src',
            controllerPathGlobs: [
                './src/controllers/**/*.ts'
            ]
        },
        swaggerConfig
	];

	const routesGenerationResult = await tsoa.generateRoutes(...routeGenArgs);
	// tslint:disable-next-line: no-console
    console.log(`Generated automatic routes at: ${routeGenArgs[0].routesDir}`);

    return {
        swaggerGenerationResult,
        routesGenerationResult
    }
}

main()
	.then(() => {
		// tslint:disable-next-line: no-console
		console.log('Finished the tsoa generation');
	})
	.catch(err => {
		throw err;
	});
```

And you can call it via `yarn tsoa:gen` if you add it to package.json
```json
	"tsoa:gen": "ts-node tsoaCustomRunner.ts",
```

And as I wrote that example script for you, it became clear to me that each person's monorepo can (and is likely) set up differently. So that makes it even more important that developers with monorepos write their own NodeJS script that uses tsoa.

**Comment by lucas-rudd** [comment]
Hey @dgreene1, we're already using tsoa programmatically, and it works wonders. However, the one you've outlined looks a bit more comprehensive, and looks as though we could take some inspiration from it.

Currently, our generator file does not merge configuration from root/sub-directories, and it looks like yours would, which is a huge improvement to our current swagger generation process.

Thanks for the information on your thought process regarding the issue and the link you posted, I had not seen that issue before and will be sure to read it thoroughly.
