### ISSUE TITLE
Internal typeResolver cache causes issues when running generateRoutes before generateSwaggerSpec

### ISSUE THREAD

**Issue by ryankeener** [lukeautry/tsoa#417]
This cache is re-used when running `generateSwaggerSpec` after `generateRoutes` within the same node process.
https://github.com/lukeautry/tsoa/blob/200b887c5d472ec53810c18f4d8b90a774b5785d/src/metadataGeneration/typeResolver.ts#L17

This bit of code
https://github.com/lukeautry/tsoa/blob/200b887c5d472ec53810c18f4d8b90a774b5785d/src/metadataGeneration/typeResolver.ts#L256-L259

short circuits the code here
https://github.com/lukeautry/tsoa/blob/200b887c5d472ec53810c18f4d8b90a774b5785d/src/metadataGeneration/typeResolver.ts#L274
and here
https://github.com/lukeautry/tsoa/blob/200b887c5d472ec53810c18f4d8b90a774b5785d/src/metadataGeneration/typeResolver.ts#L529

which results in some models not being added to the `referenceTypeMap` here
https://github.com/lukeautry/tsoa/blob/200b887c5d472ec53810c18f4d8b90a774b5785d/src/metadataGeneration/typeResolver.ts#L123

**Comment by dgreene1** [comment]
@ryankeener, would you be interested in submitting a PR to fix this?

**Comment by ryankeener** [comment]
I dug into it far enough to provide the information above but I don't think I have a deep enough understanding of what's going on (nor the time to do so right now) to create a PR. For now I'm just brute-force clearing `tsoa` and its components from the `require.cache` before executing the second stage.

I _think_ duplicating these two lines into the `existingType` check also worked but I can't be sure about it. 
```ts
      if (existingType) {
        const modelType = this.getModelTypeDeclaration(type);
        const properties = this.getModelProperties(modelType, genericTypes);
        return existingType;
      }
```

**Comment by dgreene1** [comment]
@ryankeener this fix will go out in today's release. Please let me know if it works for you. Should be version 2.4.9.

**Comment by dgreene1** [comment]
k @ryankeener it was released. Please let us know if the issue is still occurring. See our release notes for other changes: https://github.com/lukeautry/tsoa/releases

**Comment by ryankeener** [comment]
@dgreene1 It works, thanks!
