### ISSUE TITLE
Warning line break tslint

### ISSUE THREAD

**Issue by novotl** [lukeautry/tsoa#418]
This issue is caused by #344. The first 3 lines of the generated routes file are
```
// WARNING: This file was auto-generated with tsoa. Please do not modify it. Re-run tsoa to re-generate this file: https://github.com/lukeautry/tsoa
/* tslint:disable */
/* eslint-disable */
```

The warning message should not be before the disable of tslint/eslint. For example the [max-line-length](https://palantir.github.io/tslint/rules/max-line-length/) fails for the default value of 120 characters.

**Comment by dgreene1** [comment]
@novotl Thank you for reporting this. I just published v2.4.8 which has the fix for this issue. My apologies for the inconvenience. Thank you for being a part of the tsoa community. :)
