### ISSUE TITLE
Missing support for dynamic controllers in the spec generator

### ISSUE THREAD

**Issue by joni7777** [lukeautry/tsoa#420]

**Comment by dgreene1** [comment]
@joni7777 I don’t understand what this PR is supposed to be accomplishing. I might be just tired so forgive the fact that I’m not picking it up from reading your code. But more importantly, we wouldn’t accept this until there’s a readme update that explains the value of this. So maybe when you push that change I can better understand the addition of this PR.

I’m mostly asking about this because I’m taking advantage of the dynamic route generation PR you recently submitted and there’s nothing that I find lacking in it. So I’m confused about what this enhances.

**Comment by joni7777** [comment]
After some digging, I found out that the generate swagger spec is working with the dynamic controllers glob because of 2 reasons:
1. The cache across same node process the TypeResolver share
2. If you generate the routes file first, and import it to the program entry point, when you generate the metadata for the spec generator, the program starts from the server entry point which imports the routes file which imports all the controllers because of early generation from the routes generator

Either we generate both at the same time using the same config and then the cache, the generate routes first is welcomed and not a bug or we need to fix the cache and add the controllers glob to the spec generator so people can generate only the spec using the dynamic controllers

**Comment by lukeautry** [comment]
IIRC, the purpose of the cache is to handle self-referencing types, although I think `inProgressTypes` sort of serves that same purpose.

I wonder if we deleted the cache totally, would tests still pass? I believe there is test coverage in place for the case I mention above.

**Comment by joni7777** [comment]
I think the cache is nice addition for all the reference type, just we need to clear it for every new run on files converted to program

**Comment by dgreene1** [comment]
@ryankeener, in your original issue report https://github.com/lukeautry/tsoa/issues/417 you said that the cache was causing issues. Can you clarify what those issue are?

In order for us to fix the bug we have to be able to reproduce the bug first. As soon as you can describe what you meant by “issue” we can add a unit tests that goes red and then fix the code so it remains green (ie “red green refactoring”).

**Comment by lukeautry** [comment]
> I think the cache is nice addition for all the reference type, just we need to clear it for every new run on files converted to program

Okay, yes. There should be a new instance of the cache for every top-level call of generateMetadata.

Re-using the cache can sometimes be useful when you're working with the module API (not CLI), and you don't want to redo the expensive work of generating metadata twice.
