### ISSUE TITLE
Authorization Header in Controllers Not Auto-generated

### ISSUE THREAD

**Issue by luli0822** [lukeautry/tsoa#423]
Hello,

From the latest 2.4.7, the initial issue that the Swagger 3.0 was not working properly got resolved. But I found that the @Header('Authorization') I wanted to apply in the endpoints in any controllers didn't appear in the auto-generated request. For example, 
```
    @Get('{userId}')
    @Security('jwt')
    @SuccessResponse(200, 'OK')
    @Response<ApiResponse>(500)
    public async getAllClaims(@Path() userId: string, @Header('Authorization') authorization: string): Promise<ClaimResponse> {
        try {
            let result = await this.claimService.getAllClaims(userId);
            this.setStatus(200);
            return createDefaultResponse(result);
        } catch(error) {
            this.setStatus(500);
            throw new Error(`System Error: ${error.toString()}`);
        }
    }
```
From Swagger, I clicked the _Try it Out_ and entered the required the path param and the header (see screenshot below)
![image](https://user-images.githubusercontent.com/11763452/63206144-f1664580-c07c-11e9-8f8f-187da1f5672c.png)

I tried using Postman to test the endpoint with the same param and the header, it worked well. So did `specVersion=2`

**Comment by dgreene1** [comment]
@luli0822 I’m glad to hear that it’s working within Postman. Since the authorization header is showing up as a requirement in Swagger UI I can see that tsoa is doing its job of putting that documentation into the swagger.yaml.

Since tsoa is producing the swagger.yaml properly and it is enforcing the requirement that the header exists, it is doing it’s job properly.

Issues with swagger-UI are outside of the scope of tsoa. I believe [this is the well documented bug that you’re encountering in Swagger-UI](https://github.com/swagger-api/swagger-ui/issues/4325). I have also experienced it myself, I’m hoping that someone will enhance swagger UI to properly support the ability to automatically attach an authorization header. Please direct questions on this matter to their library: https://github.com/swagger-api/swagger-ui/issues/4325

**Comment by luli0822** [comment]
> @luli0822 I’m glad to hear that it’s working within Postman. Since the authorization header is showing up as a requirement in Swagger UI I can see that tsoa is doing its job of putting that documentation into the swagger.yaml.
> 
> Since tsoa is producing the swagger.yaml properly and it is enforcing the requirement that the header exists, it is doing it’s job properly.
> 
> Issues with swagger-UI are outside of the scope of tsoa. I believe [this is the well documented bug that you’re encountering in Swagger-UI](https://github.com/swagger-api/swagger-ui/issues/4325). I have also experienced it myself, I’m hoping that someone will enhance swagger UI to properly support the ability to automatically attach an authorization header. Please direct questions on this matter to their library: [swagger-api/swagger-ui#4325](https://github.com/swagger-api/swagger-ui/issues/4325)

@dgreene1 thanks a lot for letting me know this existing issue from Swagger UI.

**Comment by Bhavykapadiya** [comment]
Hi @luli0822 You had resolved this issue?

**Comment by gardelin** [comment]
I faced same issue. Only way I could resolve this is by not using `Authorization` header. 
Instead I use other auth header e.g. `X-Access-Token`.

```
// tsoa.json
"securityDefinitions": {
    "jwt": {
        "name": "jwt",
        "type": "jwt",
        "scopes": {
            "read:book": "read books",
        }
    }
}

// BookController.ts
@Security('jwt', ['read:book'])
@Response('401', 'Unathorized')
@SuccessResponse('200', 'OK')
@Get()
public async listBooks(@Header('X-Access-Token') _token: string) {
    try {
        const books = await this.repository.listBooks();

        return this.success(BookConverter.toDtoList(books));
    } catch (e) {
        console.log(e);
        return this.serverError('Error while trying to list all books');
    }
}
```

Also i found that nestjs have same issue [#98](https://github.com/nestjs/swagger/issues/98). 
I know that is different library but if they were able to fix it I guess tsoa could also.
Didn't have time to compare nestjs/swagger to tsoa swagger.json file to check what is missing.

**Comment by jekakos** [comment]
Have the same issue, is this problem still exists? O_o

**Comment by isurutobeshore** [comment]
this worked for me
![image](https://github.com/lukeautry/tsoa/assets/134576936/76f9ebbc-3d92-4c2c-9bd7-8fefe8a4a854)

**Comment by dev-scripts** [comment]
@gardelin for me also `X-Access-Token` in headers works

**Comment by felipeosano** [comment]
<img width="645" alt="Image" src="https://github.com/user-attachments/assets/569b47cf-0b4b-4e8f-bb40-8dd47a8cd9c8" />

This is how it worked for me
