### ISSUE TITLE
Develop contributor guide

### ISSUE THREAD

**Issue by lukeautry** [lukeautry/tsoa#449]
We want to get as much help as we can to improve the reliability and usefulness of tsoa. With more and more people getting involved, it may be helpful to establish a `CONTRIBUTING` guide that makes this process easier.

This is basically an open-ended discussion thread to figure out if this 1) seems like something people would want and 2) if so, what we would like it to be.

To kick things off: Are there any contributor guides out there that you've seen and like? It probably makes sense to see how TypeScript does it: https://github.com/microsoft/TypeScript/blob/master/CONTRIBUTING.md

**Comment by dgreene1** [comment]
I put a contributor guidelines, a pr template, and an issue template into the repo. I'll leave this PR open so people can provide more input. Basically I coped what I found from the TypeScript and ElasticSearch contributor guidelines.

**Comment by dgreene1** [comment]
Closed by https://github.com/lukeautry/tsoa/pull/455
