### ISSUE TITLE
endpoints with the same path are ignored

### ISSUE THREAD

**Issue by dgreene1** [lukeautry/tsoa#453]
So this one is easy enough for the developer to figure out on their own and eventually rectify it, but it might be nice to add some good developer experience (DX) by throwing if a user has a duplicate route.

**Bad situation:**
If you have two endpoints in the same route with identical paths, then tsoa will not generate swagger for the second endpoint.

**Expected result:**

Tsoa should throw an error saying, `You can not have duplicate routes. The following route is a duplicate ${duplicateRoutePath}`

**Example:**

```ts
@Route('person')
@Tags('_Person Controller')
export class PersonController extends Controller {

    @Post()
    public async savePerson(
        @Body() newPerson: IPerson
    ): Promise<IPersonSaved> {
         //...
    }

    @Post()
    public async saveSchool(
        @Body() newSchool: ISchool
    ): Promise<ISchoolSaved> {
         //...
    }
}
```

You'll notice that the function names are different but since the paths are identical, it won't make the second one. If we were to throw, it would immediately make the developer aware. They would think "oh I didn't mean to put saveSchool in the person controller" or maybe "I meant to put it on @Post('school')".

This is just to help make tsoa a more pleasurable experience so that more people are interested in using it. :)

**Comment by HoldYourWaffle** [comment]
Definitely sounds like a good DX improvement to me, where would one look for a place to put such a check?

**Comment by dgreene1** [comment]
I’m not 100% sure of where it would go. It could either be a check in this array that is produced, or internal to MethodGeneraton.generate
https://github.com/lukeautry/tsoa/blob/09b9eb3018f15b619af583e37123b664b117ff03/src/metadataGeneration/controllerGenerator.ts#L45

**Comment by HoldYourWaffle** [comment]
I think putting it in the "controller interpreter" (the snippet you linked) would make more sense. I'll see if I can quickly add this.

**Comment by HoldYourWaffle** [comment]
Actually that might not be true, is it valid to have 2 separate controllers bound to the same path?

**Comment by Moohamed0058** [comment]
AqzAqz11

**Comment by pauliusg** [comment]
I am using versioning per endpoint method. I can have one deprecated version and one current version for the same endpoint method. Correct method routing is implemented by middleware which matches method version with version in request header.
With this restriction I can't see both methods (even one is deprecated) in my swagger documentation 😞

**Comment by WoH** [comment]
A) What would you want the API description to look like?
B) If you use middlewares this way, fine, but I don't think we want to support that.

**Comment by pauliusg** [comment]
@WoH, on my example case I have solved my issue by using different path. But I worry how to solve that for endpoints without path: https://prnt.sc/vck08p

**Comment by WoH** [comment]
From the Spec:
> Templated paths with the same hierarchy but different templated names MUST NOT exist as they are identical.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#patterned-fields

I think the PR is therefore only enforcing valid OpenAPI and

**Comment by pauliusg** [comment]
@WoH, thank you for pointing that. Looks like OpenAPI v3 does not suite for my use case of versioning per endpoint method via custom header 😞

**Comment by nitinpverma** [comment]
> @WoH, thank you for pointing that. Looks like OpenAPI v3 does not suite for my use case of versioning per endpoint method via custom header 😞

Hi @pauliusg, I am also in same boat. Did you find a way to have two method versions with same endpoints?

**Comment by bellaabdelouahab** [comment]
@nitinpverma hey hope you found a solution for this ?
