### ISSUE TITLE
@Deprecated decorator for controller endpoints

### ISSUE THREAD

**Issue by fabripautasso** [lukeautry/tsoa#465]
It would be nice to have a `@Deprecated` decorator to be able to update your swagger documentation to display endpoints that are not being used/maintained any more.

Right now you can accomplish this updating the `tsoa.json` file with the endpoints you want to deprecate.

**Comment by dgreene1** [comment]
That sounds like a useful feature. I’ll mark the PR as “help wanted.” Would you be willing to submit a PR for this?

**Comment by fabripautasso** [comment]
@dgreene1 sure, I will work on this feature
