### ISSUE TITLE
Generic type inside extends don't resolve

### ISSUE THREAD

**Issue by fhewitt** [lukeautry/tsoa#467]
Following the addition of generic type support (awesome addition! 👍) I've made some tests with it with the hope of simplifying my project, and one of my scenario is failing when I use extends over a generic class where the type used in the controller, is not generic itself.

## Sorting

* **I'm submitting a ...**
  - [X] bug report
  - [X] feature request
  - [ ] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Theses lines should works.

```ts
export interface ThingContainerWithTitle extends GenericContainer<TheThing> {
    title: string;
}

export interface GenericContainer<T> {
    id: string;
    list: T[];
}
```

While using `ThingContainerWithTitle` as a property/return type of a controller.

## Current Behavior
But I got

> There was a problem resolving type of 'T'.
> There was a problem resolving type of 'GenContainer'.
> There was a problem resolving type of 'ThingContainerWithTitle'.

## Investigation
It work if I create a whole chain of generic types:

```ts
export interface ThingContainerWithTitle<T> extends GenericContainer<TheThing> {
    title: string;
}

export interface GenericContainer<T> {
    id: string;
    list: T[];
}
```

Then using `ThingContainerWithTitle<TheThing>`. But it's just wrong.

## Context (Environment)
Version of the library: 2.5.1
Version of NodeJS: 10.14.1
* Confirm you were using yarn not npm: [X]

## Breaking change?
No breaking change: it would add a new case where the generic can be used, but should not affect existing ones.

**Comment by dgreene1** [comment]
@avizcaino please follow along here for updates since we closed #391 as a duplicate

**Comment by fhewitt** [comment]
Woohoo! You guys are my hero. Thanks for the fix! I'll apply it tomorrow.

I found it great to see my example naming in the unit test :)

**Comment by dgreene1** [comment]
> Woohoo! You guys are my hero. Thanks for the fix! I'll apply it tomorrow.

Thanks goes out to @WoH.

Btw @fhewitt, since you’re enjoying tsoa, please consider writing about tsoa on Twitter, dev.to, or reddit to spread the joy! :)
