### ISSUE TITLE
Data Model Property Description With JSDoc Syntax

### ISSUE THREAD

**Issue by Circle6** [lukeautry/tsoa#476]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Detailed Description

Seeing as you can currently use JSDoc syntax to generate parameter descriptions for tsoa controllers it would be nice if you could do something similar for property descriptions of the data models that get returned (I've searched but I don't believe there's a way to add type/interface descriptions at all as of now)

i.e. defining a model like this
```ts
/**
* @property {string} name This cat's name
* @property {number} age How old this cat is in human years
*/
interface Cat = {
  name: string;
  age: number;
}
```
Should generate swagger.json like this

```json
{
...
"definitions": {
  "Cat": {
    "properties": {
      "name": {
        "type": "string",
        "description": "This cat's name"
      },
      "age": {
        "type": "number",
        "description": "How old this cat is in human years"
      }
    }
  }
}
```

**Comment by WoH** [comment]
```ts
interface Cat = {
  /**
  * This cat's name
  */
  name: string;

  /**
  * How old this cat is in human years
  */
  age: number;
}
```

Is that what you're looking for?

**Comment by Circle6** [comment]
That is exactly what I'm looking for. I've been trying to find this for weeks thanks! You are wonderful :)

**Comment by dgreene1** [comment]
We can close this then since the correct way has been shared, right?
(If that doesn’t generate what you want in the swagger document then we can reopen)
