### ISSUE TITLE
What is the function of express/hapi/koa.d.ts?

### ISSUE THREAD

**Issue by HoldYourWaffle** [lukeautry/tsoa#486]
There are currently 3 declaration files that add an optional `user` field to the `Request` interface of the corresponding framework:

https://github.com/lukeautry/tsoa/blob/0d4f17aa651418a1fec735e096cc0d907ff0449f/src/koa.d.ts#L1-L6

https://github.com/lukeautry/tsoa/blob/0d4f17aa651418a1fec735e096cc0d907ff0449f/src/express.d.ts#L1-L6

https://github.com/lukeautry/tsoa/blob/0d4f17aa651418a1fec735e096cc0d907ff0449f/src/hapi.d.ts#L1-L6

What is the function of these declaration files? Do the generated routes use them in some way, and if so, why? As far as I know TSOA doesn't have anything to do with authentication/user management.

**Comment by dgreene1** [comment]
These files are there so that the internal tsoa code can test the security decorator.

**Comment by HoldYourWaffle** [comment]
Interesting, I somehow managed to completely miss the security features that TSOA has to offer (no idea how).

When looking into these security features I noticed something that has been unknowingly bothering me for months: TSOA adds a `user: any` property to the `express.Request` interface. This is a problem because it makes it impossible to add your own type to the user through declaration merging.

I think the type definitions for passport.js illustrate this very well. As you can see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/21da2006968b16817b57338b30a8ba4a83e9bba0/types/passport/index.d.ts#L13-L22), `@types/passport` adds a `user` property to `Request` with an empty interface.
Users can then add their own properties to this `User` using declaration merging:
```ts
// my-own-special-declaration.d.ts

declare global {
    namespace Express {
        interface User {
            // my amazing properties
        }
    }
}
```

TSOA defining its own `Request.user` with an `any`-type makes this impossible, because it 'overrides' the passport declaration. No matter what you try, `Request.user` will always stay as `any`.

The most obvious solution would be to add our own "template interface" for declaration merging and use that instead of `any`. Sadly this isn't really a good solution either because this would still conflict with (in this case) passport.js's interface, this time throwing a compile error instead of silently overriding.

Because TSOA is not an authentication library and just functions as a "pass-through" (as far as I can tell), I think the best solution would be to remove these declaration files.
To make the generated router pass compilation we could do two things:
- Add a note (with example) that tells users that they should add their own `user` property (through declaration merging) if that hasn't been done by another module yet.
- Use `as any` when we assign the user property.

I prefer the first method because you need to define the `user` property *somewhere* anyway in order to use it.

**Comment by HoldYourWaffle** [comment]
Hold on I might have misunderstood your comment, did you mean actual *test* tests, as in unit tests? (This doesn't invalidate my comment but it might change the implications)

**Comment by dgreene1** [comment]
So if you can find a way to get tsoa to compile after you’ve removed those declaration files then we’ll accept the PR.

**Comment by HoldYourWaffle** [comment]
I'll check this out in a bit.
Do you think a note on adding your own `user` declaration would be sufficient documentation for users?
