### ISSUE TITLE
Massive code duplication between router generation templates

### ISSUE THREAD

**Issue by HoldYourWaffle** [lukeautry/tsoa#487]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request
  - [x] suggestion

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
You generally want to minimize code duplication to avoid maintenance and readability issues.

## Current Behavior
**Very large** portions of `express.hbs`, `hapi.hbs` and `koa.hbs` are identical or have no functional difference.

## Possible Solution
My first hunch would be to extract the common portion(s) into a separate "base" template. The router-specific parts can then be 'included' into this base template.

## Breaking change?
Probably not because custom templates are not be affected by this change.

**Comment by dgreene1** [comment]
Sure, we’d accept this refactor
