### ISSUE TITLE
Support dependency injection for controllers

### ISSUE THREAD

**Issue by andreasrueedlinger** [lukeautry/tsoa#49]
As discussed already [here](7) and [here](../pull/25) it would be very convenient that the default templates support controllers managed by a DI-framework like `inversifyJS`.
I added a [PR](../pull/48) to solve the problem by adding the relative path to the IOC-module exporting the kernel in the `tsoa.json`.

**Comment by lukeautry** [comment]
@andreasrueedlinger This is live in 1.0.15. Thanks again!
