### ISSUE TITLE
generate swagger v2 without x-nullable

### ISSUE THREAD

**Issue by marknelissen** [lukeautry/tsoa#497]
#257 has been closed, stating that it is possible to mark a property as nullable by making use of the v3 spec. However, the original problem of #257 is the presence of x-nullable in v2 generated files.

This still causes the same problems for people having to use v2. As such, this addition should be removed or at least the option should be added to disable this behaviour through config.

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
No x-nullable in generated swagger.json.

## Current Behavior
Optional parameters are marked with x-nullable.

## Possible Solution
Remove the x-nullable generation or add config parameter to disable the generation.

## Steps to Reproduce

1. Use optional type in interface (eg. name?: string)
2. generate swagger.json

## Context (Environment)
Version of the library: 2.5.3
Version of NodeJS: v10.16.3
* Confirm you were using yarn not npm: [x]

**Comment by dgreene1** [comment]
@marknelissen can you clarify how this is a bug? Swagger v2 allows the use of custom properties. See here: https://swagger.io/docs/specification/2-0/swagger-extensions/

What I'm saying is that (without me knowing more about the situation) I believe that `x-nullable` is valid schema. However, if you're encountering a problem due to the presence of a custom property, please describe at which point in the process it's causing an issue for you.

The more information we have the better we can assist. Thank you.

**Comment by marknelissen** [comment]
Hi @dgreene1 , in general, this does not pose any problem. However, for my current project, the swagger.json needs to be submitted in order to publish the api in an api store. In order to do this, the API specification needs to meet the store standards. There are several rules (eg. no 200 response on POST), and among these is also a rule that trips regarding the presence of x-nullable in the generated swagger.json.

I opened this ticket, since it corresponds to the problem the OP of #257 was experiencing on Amazon, and the ticket never came to any real solution, since the OP ended up writing a module that reworked the generated json into something they could word with.

Since my problem could be fixed by not outputting x-nullable, I was interested in the proposed solution of #257 to disable the generation of x-nullable through a flag in the tsoa.json configuration. This would avoid me having to go through the file to remove all occurences, and be able to submit the generated swagger.json as is.

**Comment by dgreene1** [comment]
Okay, I changed it to be a feature request because I want to be clear to future readers that it’s not a bug and is in fact valid Schema.

But I think it’s reasonable to have a flag that removes all custom properties.

**Comment by marknelissen** [comment]
All right. I updated the original message to feature request.

**Comment by dgreene1** [comment]
@marknelissen this has been floating around for a while and no one has volunteered. Would you be willing to put a PR in for it yourself?

**Comment by marknelissen** [comment]
I'll take a look. However, since the end of the year is a very busy period, it might take me some time to get it done.
