### ISSUE TITLE
Add support for @Hidden() decorator for controllers

### ISSUE THREAD

**Issue by ryankeener** [lukeautry/tsoa#499]
In some cases I'd like to hide all endpoints for a particular controller (e.g. `/admin` endpoints).  Instead of adding the `Hidden()` tag on each endpoint it'd be cleaner to just add it to the controller and have it apply to all of its endpoints.

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Neither `find` nor `create` should appear in the Swagger file in the following case:
```ts
@Hidden()
export class HiddenController {
  @Get()
  public async find(): Promise<any> {  }

  @Post()
  public async create(): Promise<any> {  }
}
```

## Current Behavior
The `@Hidden()` decorator needs to be added to each endpoint method
```ts
export class HiddenController {
  @Get()
  @Hidden()
  public async find(): Promise<any> {  }

  @Post()
  @Hidden()
  public async create(): Promise<any> {  }
}
```

## Possible Solution
I jumped the gun and created this PR already: #498  

## Breaking change?
No.

**Comment by dgreene1** [comment]
Released in v2.5.6
