### ISSUE TITLE
Numeric enums in query don't work

### ISSUE THREAD

**Issue by Kampfmoehre** [lukeautry/tsoa#514]
Numeric enums don't work with tsoa when used in a query parameter.

## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
They just work.

```ts
export enum ExampleEnum {
  a = 0,
  b = 1,
  c = 2,
}
// ...

public async controllerAction(@Query() a: ExampleEnum) {
  // ...
}
```

## Current Behavior
If you send a request (either via swagger or anything else) tsoa validator is answering with

```json
{
  "fields": {
    "a": {
       "message": "should be one of the following; ['0', 1, 2]",
       "value": "1"
    }
  }
}
```
## Possible Solution
I debugged into the ValidationService and find out, that the value from request.query is always a string. This should maybe cast into the correct type before validateEnum is called?

## Steps to Reproduce
See above.

## Context (Environment)
Version of the library: 2.5.6
Version of NodeJS: v12.8.0
* Confirm you were using yarn not npm: [ ]

## Detailed Description
note: it works for 0 but not for the other values. See how 0 gets compiled as a string into routes.ts.
```ts
// ...
a: { "in": "query", "name": "a", "required": true, "dataType": "enum", "enums": ['0', 1, 2] },
```

**Comment by dgreene1** [comment]
I think the challenge here is that the query is always a string. So a fix for this would be able to safely try to parse the string as a number before making the comparison. However, when it comes to validating the body, JSON encoding clearly denotes the difference between a string and a number. So we wouldn’t want to match`{“a”: 1}` to `{“a”: “1”}`.

I’m sorry to push this onto you (the discoverer of the bug), but would you be interested in submitting a PR for this?

**Comment by dgreene1** [comment]
And feel free to say “no” and then we’ll know that someone else should pick up this bug fix.

**Comment by Kampfmoehre** [comment]
Hm I could take a look at it, but that will have to wait until at least November. Right now we are in the middle of something and I have no time do deep into this library.
Just for anyone that wants to look at this, my attempt would be to look at the Enum value type and cast the query value to the appropriate type without affecting any other validations.

**Comment by WoH** [comment]
This is related to the way we try to extract enums in header/query params.

@dgreene1 for context, we already try to parse `@Header('index'): index: number` etc., so enums should also do that.

This will be addressed in a way that works for the next major, if someone wants to take a look to fix this in a non-breaking fashion I'd be happy to review.
