### ISSUE TITLE
The server host can not be changed in swagger 3.0

### ISSUE THREAD

**Issue by yiqingithub** [lukeautry/tsoa#518]
After I generate the swagger.json when using swagger 3.0, I found that in the swagger.json, the url of servers is always 'https://localhost:3000/'. How could I change the servers url?
servers:
  - url: 'https://localhost:3000/'

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ * ] support request

* I confirm that I
  - [ * ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I could change the url which is contained in the server

```yaml

servers:
  - url: 'https://{the IP I defined}:{the port I defined}/'

```

```ts

```

## Current Behavior

```yaml

servers:
  - url: 'https://localhost:3000/'

```

```ts

```

## Steps to Reproduce

1. change the specVersion of swagger to 3.0 in tsoa.json	 
"swagger": {
		"specVersion": 3.0
2. define "swagger": "tsoa swagger" command in the package.json
3. generate the swagger.json by command "npm run swagger"

## Context (Environment)
Version of the library: 
tsoa 2.5.7

Version of NodeJS: 
v12.11.1

* Confirm you were using yarn not npm: [ ]
no, I just use npm

**Comment by WoH** [comment]
https://github.com/lukeautry/tsoa/blob/master/src/config.ts#L53

**Comment by yiqingithub** [comment]
Hi, WoH, thank u for your link, now I could change the host, but I just don't know how to change the "https" to "http", for example, I want to change the url "https://localhost:3000" to "http://localhost:3000" Do u know how to do?

**Comment by yiqingithub** [comment]
> https://github.com/lukeautry/tsoa/blob/master/src/config.ts#L53
> 
> Setting the host there should work.

Hi, WoH, thank u for your link, now I could change the host, but I just don't know how to change the "https" to "http", for example, I want to change the url "https://localhost:3000" to "http://localhost:3000" Do u know how to do?

**Comment by yiqingithub** [comment]
I just found that if I want to change the url "https://localhost:3000" to "http://localhost:3000", I could set the swagger config "schemes": ["http"], is that right? @WoH 
https://github.com/lukeautry/tsoa/issues/518#issuecomment-545390326

**Comment by MadsRF** [comment]
hey the link doesn't work anymore. any way to get a updated answer on this? thanks in advance
