### ISSUE TITLE
Empty string among union values causes union to be resolved as 'any' instead of 'string'

### ISSUE THREAD

**Issue by rgripper** [lukeautry/tsoa#522]
Unions `type YesNo = "Yes" | "No" | ""` will have swagger generated with type object, as typeResolver produces 'any' data type.

## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Generates a swagger type enum and all its values

## Current Behavior
Generates a swagger type object

## Steps to Reproduce
Generate swagger for `type YesNo = "Yes" | "No" | ""`

## Context (Environment)
Version of the library: 2.5.7
Version of NodeJS: 8
* Confirm you were using yarn not npm: [ ]

## Breaking change?
Potentially, as people may rely on empty strings to not produce correct swagger enum. Having empty strings in enums is very rare though.

**Comment by dgreene1** [comment]
@rgripper please fill out the full issue template with all of the information. We need to get more context and code examples. At the moment I don’t know what the issue is and how we would reproduce it. That’s why the issue template was created.

**Comment by rgripper** [comment]
@dgreene1 Feel free to point me to a test, that checks type resolver, so I could add a test.

**Comment by dgreene1** [comment]
@rgripper here’s a decent place to put a test like that for openapi 3: https://github.com/lukeautry/tsoa/blob/master/tests/unit/swagger/schemaDetails3.spec.ts#L182

**Comment by rgripper** [comment]
@dgreene1 Thanks, I've updated the tests to cover this.
