### ISSUE TITLE
Potential bug with excess properties + question about swagger UI authentication “try it out” button

### ISSUE THREAD

**Issue by smithbk** [lukeautry/tsoa#523]
My tsoa.json is given below and have two questions.  Thanks in advance.

1) How do I make the "Try It Out" button result in sending the basic authorization header?  When I click on the "Authorize" button, I can fill in the username and password, but it does not send the Authorization header when pressing the "Execute" button.

2) The "noImplicitAdditionalProperties" property does not result in throwing an exception when I pass a bogus field to one of my APIs.  Instead, the bogus field is just ignored.  Have I configured it correctly?  Is there something else that I am supposed to do?

{
        "swagger": {
                "outputDirectory": ".",
                "entryFile": "./src/main.ts",
                "noImplicitAdditionalProperties": "throw-on-extras",
                "securityDefinitions": {
                        "tsoa_auth": {
                                "type": "basic"
                        }
                }
        },
        "routes": {
                "basePath": "/",
                "entryFile": "./src/main.ts",
                "routesDir": "./src",
                "middleware": "express"
        }
}

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml

```

```ts

```

## Current Behavior

```yaml

```

```ts

```

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
Version of the library: 
Version of NodeJS: 
* Confirm you were using yarn not npm: [ ]

**Comment by dgreene1** [comment]
That functionality is provided by the swagger UI repository. Please open a PR with them.

**Comment by dgreene1** [comment]
I didn’t see your second question. Sorry about that. So yea, can you add the following to the PR so we can assist?

* the typescript code for the API controller and route
* the typescript code for all of those interfaces that are used in the code for the controller and route
* the data that you sent to the API (and please specify if you sent it as a query parameter, a route parameter, or as the body)

Thanks.

And to reiterate, the question about how to get the authorization button to work in the swagger UI page is something that can only be answered by that team.
