### ISSUE TITLE
tsc fails to compile if tsoa is installed globally

### ISSUE THREAD

**Issue by adhamhf** [lukeautry/tsoa#53]
I'm a typescript noob so this is probably something I'm doing wrong, but I can't figure it out...

I'm using nvm and have tsoa installed globally:

    npm install -g tsoa

tsc then gives me this error:

    endpoints/endpoints.ts(2,38): error TS2307: Cannot find module 'tsoa'.

which is the line where I import tsoa.  My module resolution strategy is set to node, and I think that's correct.  Could paths be conflicting in tsconfig.json?

```
    "paths": {
      "*": [
        "models/*",
        "endpoints/*",
        "generated/*"
      ]
    }
```

Help?

**Comment by lukeautry** [comment]
@adhamhf I think the issue here is that TypeScript is having a tough time finding typings for tsoa since it's installed globally. Have you tried installing tsoa as a local dependency in the project?

**Comment by adhamhf** [comment]
thanks @lukeautry!  that does work just fine.   trying to avoid that if possible.

**Comment by lukeautry** [comment]
In that case, I think you'll need to reference the typings in the tsoa package from your project somehow. It may be possible to do this through tsconfig and the "types" property.

**Comment by adhamhf** [comment]
by referencing the full path in tsconfig.json paths you can get this to work.
