### ISSUE TITLE
Github Actions have been disabled for the project

### ISSUE THREAD

**Issue by lukeautry** [lukeautry/tsoa#531]
As of November 13th, our Github Actions flows have stopped working. This seems to have something to do with plan changes, but there's no clear resolution at this time.

Related issue: https://github.com/ansible/community/issues/505

Retweet here for visibility: https://twitter.com/luke_autry/status/1195430088352894979

**Comment by rgripper** [comment]
@lukeautry Maybe this is applicable?
https://github.com/ansible/community/issues/505#issuecomment-554661894

**Comment by WoH** [comment]
It's back up and running.
