### ISSUE TITLE
express Request is undefined in TSOA route Controller

### ISSUE THREAD

**Issue by iasbm** [lukeautry/tsoa#532]
Hello 
I need to be able to access expressRequest in one of the TSOA controller.
here is my code....

import { Route, Get, Post, Delete, Request, Response, Header, Body, Security, Controller } from 'tsoa';
import * as express from 'express';

@Route('auth')
export class UserAuthController extends Controller {

  @Post('Login')
  public async login(@Body() request: IUserLoginRequest, @Request() expReq: express.Request): Promise<IUserLoginResponse> {
logger.debug('expReq is....'+expReq);
}

But the logger statement prints the "expReq" as undefined...
Request for help if i am doing anything wrong please....

**Comment by dgreene1** [comment]
Why didn’t you fill out the issue template? 

Please fill out the things that are missing like:
- the version of tsoa you see in your yarn.lock or package.lock
- if you’re using yarn or npm
- the version of Node
- the version of TypeScript

Also, I notice that you `@request` decorator is lower case but tsoa.Request is uppercase.

**Comment by iasbm** [comment]
Hi i have just reopened the same as new Issue by filling in the template with necessary details of versions of env.  No it is not @request, but it is actually @Request, but it automatically changed to lower case when i pasted the code in the   ##533

**Comment by dgreene1** [comment]
K we’ll track this in the other issue. Closing this one as a duplicate.
