### ISSUE TITLE
Use of TypeScript enums in @Security decorator

### ISSUE THREAD

**Issue by OrKoN** [lukeautry/tsoa#534]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

When a TypeScript Enum is used in the @Security decorator, it'd be great if the enum values would be used in the generated routes:

```ts
// controller.ts
enum MyEnum = {
   MY_SCOPE = "MyScope"
}

@Security("mySec", [MyEnum.MY_SCOPE])

// routes.ts

import { MyEnum } from 'controller.ts'

authenticateMiddleware([{ "mySec": [MyNum.MY_SCOPE] }])
```

## Current Behavior

Currently the above code produces a null value instead of MyEnum.MY_SCROPE in the generated routes.ts:

```ts
authenticateMiddleware([{ "mySec": [null] }])
```

## Possible Solution

Probably, the security generator needs to be modified to know what is the type of the security scope and how to import the enum if an enum is used.

## Steps to Reproduce

1. Use a TypeScript enum in the security decorator

## Context (Environment)
Version of the library: 2.5.9
Version of NodeJS: v10.17.0
* Confirm you were using yarn not npm: [ ]

**Comment by dgreene1** [comment]
You must not have searched for this since there already is an issue about this topic. I will close yours as a duplicate and reopen the stale issue: https://github.com/lukeautry/tsoa/issues/337
