### ISSUE TITLE
Nested Property Descriptions not being added to swagger output

### ISSUE THREAD

**Issue by jtfell** [lukeautry/tsoa#538]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Explanation

Accompanying issue for the issue raised in this [PR](https://github.com/lukeautry/tsoa/pull/535). It just modifies the tests to demonstrate the desired output

**Comment by dgreene1** [comment]
A low value but helpful feature. It’s an easy first PR.

Please note, the workaround is that people can make two interfaces instead of one nested interface.
