### ISSUE TITLE
Return type of file

### ISSUE THREAD

**Issue by jjm340** [lukeautry/tsoa#549]
Can one specify a return type of binary or file on a model property?

**Comment by dgreene1** [comment]
There was a PR to introduce this but it required corrections and the submitter never returned. Feel free to resubmit it with the requested corrections: https://github.com/lukeautry/tsoa/pull/228

**Comment by dgreene1** [comment]
@jjm340 have you considered opening a PR for this? All you'd have to do is copy the  #228 PR and make the [requested changes](https://github.com/lukeautry/tsoa/pull/228#pullrequestreview-274034476)

**Comment by jjm340** [comment]
I pulled down the PR to attempt to do this, but merging the latest was the problem. I'm not nearly familiar enough with the code base to do that. I can give it another shot, but I'm not sure if I'll have time.

**Comment by WoH** [comment]
If you're interested in working with me on this, I'd love to help you along the way @jjm340.

**Comment by jjm340** [comment]
I really appreciate that @WoH and will try and find time to take a look, but no promises at the moment.
