### ISSUE TITLE
Omitting the host property should make the host relative

### ISSUE THREAD

**Issue by dgreene1** [lukeautry/tsoa#555]
This is the v3 version for the compromise we made in https://github.com/lukeautry/tsoa/pull/547

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Assuming that the `host` property was not provided and the `basePath` is "v1" (correct me on this if I'm wrong @Eoksni / @jreusch-barco) but the desired output would be:
```yaml
"servers": [
		{
			"url": "/v1"
		}
	]
```
I'd like to be able to specify relative host, which is allowed by specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-4.

## Current Behavior
Currently if I omit host field in the swagger config or use empty "host": "", it gets replaced with http://localhost:3000. Using "host": "/" also doesn't work.

## Possible Solution
The solutions were discussed in the v2 version of this change: https://github.com/lukeautry/tsoa/issues/540

## Detailed Description

We will accept that if someone doesn't specify a host, then it should not default (since tsoa couldn't possibly know which host to default to). It should be relative.

## Breaking change?

Yes, this should be part of the v3 branch.

**Comment by jreusch** [comment]
> Assuming that the host property was not provided and the basePath is "v1" (correct me on this if I'm wrong @Eoksni / @jreusch-barco) but the desired output would be:

yep, nothing wrong thats correct. :)

**Comment by jreusch** [comment]
btw: thanks for opening this issue, i just came back with the intention of doing it after this time and saw that you were a few hours faster :)

**Comment by dgreene1** [comment]
Awesome. Thank you @jreusch :)

**Comment by jreusch** [comment]
hey hey
i would volunteer to do a PR for this.
do i see this right that the target for this PR should be the 3.x branch?

**Comment by WoH** [comment]
Yes. The 3.x does not have https://github.com/lukeautry/tsoa/pull/547 yet, so please keep that in mind :)

Thank you very much :heart:

**Comment by Burnett2k** [comment]
Please let me know when this issue is resolved. I'm using specVersion 3 and it always defaults to https with or without the host included.  Hopefully this is the same issue because I want the host to be protocol relative.

**Comment by jreusch-barco** [comment]
hey hey
according to
https://github.com/lukeautry/tsoa/blob/master/src/swagger/specGenerator3.ts#L119
you should already be able to specify the scheme.
it defaults to https yes, but when putting "schemes": ["http"] you should be fine?

**Comment by Burnett2k** [comment]
@jreusch-barco Thanks for that tip! I looked through the config and skipped over schemes.  As I learn these things I'm wondering if it would help to actually list out all the config options in the readme?

**Comment by jreusch-barco** [comment]
i think they'd be open to a PR with the readme.
or at least have something pointed to
 https://github.com/lukeautry/tsoa/blob/master/src/config.ts 
where the acutal implementation/comments are.
or maybe just a page where the jsdoc of this file is written, endless possibilities, someone just has to do it :)

**Comment by dgreene1** [comment]
@Burnett2k the readme already links to the config file. Our hope was that the JSDoc comments would be enough. Although it would be nice to have that in the readme, it would be a bad idea to have duplicate documentation. So a better route is to have an auto generated documentation page which JSDocs provides. There’s also a issue request that asks for us to create a website for tsoa, but that got stale since no one picked it up. https://github.com/lukeautry/tsoa/issues/454

So for now, hopefully the href link to the config TS file is enough for now.

**Comment by jreusch** [comment]
hmm seems this time the automatic closing did not work.
since the PR is merged i think this can be closed?
keeping track that this ends up in the releasenotes is most likely done via other means?

**Comment by dgreene1** [comment]
> hmm seems this time the automatic closing did not work.

@jreusch the auto-close feature of github only works when the fix hits master. In this case, our v3 branch is a long-living branch off of master that we manually publish as npm package v3.0.x.

Anyway, I'll add this fix to the release notes.

**Comment by jreusch-barco** [comment]
ah, thanks for the explanation, that actually makes sense :)
