### ISSUE TITLE
Optional properties should not be nullable by default

### ISSUE THREAD

**Issue by WoH** [lukeautry/tsoa#557]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
```json
"OptionalNotNullable": {
  "properties": {
      "optional": {
        "type": "string"
      },
    },
    "required": [],
    "type": "object",
    "additionalProperties": false
},
```

```ts
interface OptionalNotNullable {
  optional?: string
}
```

## Current Behavior
```json
"OptionalNotNullable": {
  "properties": {
      "optional": {
        "type": "string",
        "nullable": true
      },
    },
    "required": [],
    "type": "object",
    "additionalProperties": false
}
```

## Possible Solution
Don't mark [optional properties](https://github.com/lukeautry/tsoa/blob/master/src/swagger/specGenerator3.ts#L338) as `nullable: true`.

## Context (Environment)
Version of the library: 2.x
Version of NodeJS: any

- [x] Confirm you were using yarn not npm

## Detailed Description
If we have a representation of the concept (see propsal here: https://github.com/lukeautry/tsoa/issues/479#issuecomment-571134853) of `null` in OpenAPI spec, we should not mark any optional properties as `nullable: true` and instead use the explicit TS `null`.

## Breaking change?
Yes, should be 3.x

**Comment by nivnahmias** [comment]
hey, wondering if this has made it into v3-beta already? if not, is there an ETA on it?
thanks!
