### ISSUE TITLE
string literal enum types not working...

### ISSUE THREAD

**Issue by adhamhf** [lukeautry/tsoa#56]
I'm having trouble with string literal enums.

I have defined this:

    export type Status = 'Happy' | 'Sad';

Yet I get this error when I try to add it to my User model:

    Cannot read property 'text' of undefined

Any suggestions?

model:

```
export interface User {
    id: number;
    email: string;
    createdAt: Date;
    status?: Status;
}
```

controller:
```
    @Get('{userId}')
    public async Get(userId: number): Promise<User> {
        let user: User = {
            createdAt: new Date(),
            email: 'test2',
            id: userId,
            status: 'Happy'
        };
        return user;
    }
```

**Comment by lukeautry** [comment]
@adhamhf String literal types should work as of one of the last couple of releases.

A couple of comments - first, what version tsoa are you using?

Secondly, can you upgrade to 1.0.17 and verify that the error is still occurring, and if so, provide the full stacktrace (which will now be included with the error message)?

Thanks!

**Comment by lukeautry** [comment]
Closing this for now til I get some information back about your setup.
