### ISSUE TITLE
Emit better error if no controllers are discovered

### ISSUE THREAD

**Issue by Burnett2k** [lukeautry/tsoa#562]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [ ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

When I enable the tsconfig option noUnusedParameters and try to compile the app after routes have been generated, I get the following errors:

```

src/routes.ts:14:32 - error TS6133: 'app' is declared but its value is never read.

14 export function RegisterRoutes(app: express.Express) {
                                  ~~~

src/routes.ts:28:12 - error TS6133: 'promiseHandler' is declared but its value is never read.

28   function promiseHandler(controllerObj: any, promise: any, response: any, next: any) {
              ~~~~~~~~~~~~~~

src/routes.ts:57:12 - error TS6133: 'getValidatedArgs' is declared but its value is never read.

57   function getValidatedArgs(args: any, request: any): any[] {
              ~~~~~~~~~~~~~~~~

[11:53:57 AM] Found 3 errors. Watching for file changes.
```

```yaml
//@ts-nocheck
```

## Current Behavior

I receive multiple compilation errors from typescript and cannot build the application.

## Possible Solution

Adding `//@ts-nocheck` to the top of the file suppresses this issue.

## Context (Environment)
Version of the library: "tsoa": "^2.5.12"
Version of NodeJS: 
* Confirm you were using yarn not npm: [x]

**Comment by dgreene1** [comment]
If you’d like to submit a PR for this, we would accept it. But I don’t like the ideal of `ts-nocheck`. I think we should just delete u used variables.

**Comment by Burnett2k** [comment]
Agreed, it seems like a hack. But, I'm fairly new to this library and don't understand why it has these unused functions included.

I could add code to omit the `app` variable or replace it with a empty object `{}`.  But, that doesn't solve the issue where there is a `promiseHandler` function which is declared and never used. Same with `getValidatedArgs`.

I'm curious how you are getting around this problem? Do you just not use that configuration in your tsconfig or is something like tslint overriding that behavior?

**Comment by fantapop** [comment]
I ran into this as well with a new project and it turned out I hadn't configured the `controllerPathGlobs` yet in the tsoa.json configuration file.  During the build, tsoa didn't find any controllers to generate routes for and hence various of the validation functions weren't being called  in the generated routes.ts file.

**Comment by fantapop** [comment]
@Burnett2k are you able to repro this with the `controllerPathGlobs` configuration set?

**Comment by sundowndev** [comment]
I have the same issue, why is that happening?

**Comment by WoH** [comment]
Tsoa is not discovering your controllers. This can happen because the entryFile does not require/import your controllers or your controllerPathGlob is not set up correctly.
