### ISSUE TITLE
jsDoc cannot contain '@'

### ISSUE THREAD

**Issue by labe-me** [lukeautry/tsoa#563]
## Sorting

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
/**
 * @format email 
 * @pattern ^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$ 
 */
email: string
``` 
It should create a validator containing the full pattern :

```ts
"email": { 
  "dataType": "string", 
  "required": true, 
  "validators": { 
    "pattern": { 
      "value": "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"
    } 
  }
},
```

## Current Behavior

The pattern is split at @ and only the first part of the regex is used

```ts
"email": { 
  "dataType": "string", 
  "required": true, 
  "validators": { 
    "pattern": { 
      "value": "^[a-zA-Z0-9_.+-]+" 
    } 
  } 
},
```

## Context (Environment)
Version of the library: 2.5.12
Version of NodeJS: v10.15.3
* Confirm you were using yarn not npm: [X]

**Comment by dgreene1** [comment]
Would you be interested in submitting a PR for this @labe-me?

**Comment by labe-me** [comment]
> Would you be interested in submitting a PR for this @labe-me?

I don't have a lot of free time, but just in case if you can point me the part of the code which is in charge of parsing the jsDocs, I will take a look !

**Comment by dgreene1** [comment]
I just had to search for “pattern” in github because I don’t know all of the code either. Here you go: 
https://github.com/lukeautry/tsoa/blob/28e599d44571803e8c90697a0d78b95550d28077/src/utils/validatorUtils.ts#L84

**Comment by labe-me** [comment]
I believe the problem is not in the usage part but in the parsing part.

It looks like the jsdoc parser is blindly splitting on @, I tried to escape using @@ and \@ but didn't work.

Hope to find the time to inspect more carefully later.

**Comment by WoH** [comment]
Yes, this used to be an issue with TypeScript / the TS AST as far as I know. I remember running into this. I'll see if I can dig up the issue.

**Comment by sittingbool** [comment]
Hi, I am currently working on a solution for this. 
I'ts a bit hard reverse-engineering this.  Could someone point me to the code that creates the tags? It cuts off everything after the @ and creates a new tag for the word ofter the @. 
Possible solutions: 
1. This should not be done when the line is inside { }
2. make t possible to escape the @ using `\@` ans tell the TypeResolver or whatever parses that to not make it a tag if its `\@something`

**Comment by WoH** [comment]
This is mostly happening in TypeScript.
There's a tool for TS AST visualization, so I've recreated the situation here: https://ts-ast-viewer.com/#code/JYOwLgpgTgZghgYwgAgJIDFEoN4ChkHID0AVCfocicgAIAOcYkUIyAFsDRwHQID2AWwqESRYcggC4wADYAuZAGcwUUAHNcAX1xA

If you turn on the "options" -> "show internals", you can see the jsDoc contains 2 JsDocTags for the `string`.
So unless you wanna tackle this upstream, you will have to reimplement the way we parse from jsDocTags mostly [here](https://github.com/lukeautry/tsoa/blob/master/src/utils/validatorUtils.ts) and [here](https://github.com/lukeautry/tsoa/blob/master/src/utils/j).

**Comment by sittingbool** [comment]
I saw that but where where is the file-content read into AST? My idea would be to replace the `\@` with like `<<at>>` before handing over to  AST. And before creating docs replace `<<at>>` with `@` to have the correct outcome. should be a simple regex-thing.

**Comment by sittingbool** [comment]
Also I tried to do this using @Example() as a hotfix. But it never shows on my swagger...

**Comment by jfrconley** [comment]
From my own testing, it seem like ` quotes prevent the parser from stopping on @. Perhaps we could allow quoting patterns (or maybe all jsdoc fields) with back ticks that we then remove after parsing.

**Comment by jfrconley** [comment]
I made a PR that addresses this issue by allowing quoting of patterns using backticks
