### ISSUE TITLE
v3.x mapped type Swagger UI compatibility issue

### ISSUE THREAD

**Issue by Ze-Khan** [lukeautry/tsoa#565]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
interface IExample {
  a: string;
  b: number;
}
type AnB = Pick<IExample, 'a'|'b'>
@Get('/')
test(): AnB { }
```

```json
{
  "AnB": {
    "properties": {
      "a": {
        "type": "string"
      },
      "b": {
        "type": "number"
      }
    },
    "required": ["a","b"],
    "type": "object"
  }
}
```

## Current Behavior

```json
{
  "Pick_IExample.a'%7C'b_": {
    "properties": { "b": { "type": "number", "format": "double" }, "a": { "type": "string" } },
    "required": ["a", "b"],
    "type": "object",
    "description": "From T, pick a set of properties whose keys are in the union K"
  },
  "AnB": { "$ref": "#/components/schemas/Pick_IExample.a'%7C'b_" }
}
```
Swagger UI shows the following error:
```
Could not resolve reference: Could not resolve pointer: /components/schemas/Pick_IExample.a'%7C'b_ does not exist in document
```

## Possible Solution

The AnB schema is referencing another randomly named schema which somehow swagger ui is unable to read. If i copy the properties of "Pick_IExample.a'%7C'b_" into AnB however, the correct format is shown on swagger ui.

I also tried changing the name from "Pick_IExample.a'%7C'b_" to just "Pick_IExample" and the problem is resolved so i guess it might have something to do with the special symbols in the randomly generated name.

## Context (Environment)
Version of the library: v3.0.1
Version of NodeJS: v10.16.3

**Comment by dgreene1** [comment]
I’m gonna assign this to @WoH since I’m triaging some v2 stuff right now.

**Comment by WoH** [comment]
Do I read that correctly, the reference gets created properly, but SwaggerUI has issues because the name is "illegal"?

**Comment by Ze-Khan** [comment]
Glad I could help and thank you for being so responsive and always improving the library

**Comment by WoH** [comment]
I fixed the apostrophes, but Swagger will still complain.

OpenAPI specifies all URIs as permitted by JSON-Schema should be valid.

JSON Schema uses JSON-ref, which permits all URIs as laid out in RFC3986..

RFC3986 allows %encoding, which is what I'm doing to ensure there are no illegal characters. Althought the '|' does not have to be escaped (however, the %7C is exactly that, not sure what encodeURI() is doing here), but it should not cause SwaggerUI to complain.

I'll check if SwaggerUI knows about these issues and what potential remedies are. What's definitely not intended are the 'around the percentencoding and only on one side of the string literal list.

Maybe I'll have to replace %7C back to |

**Comment by Ze-Khan** [comment]
just for your info %26 which is & also doesn't work

**Comment by WoH** [comment]
I pushed the relevant changes (291280927a738928638cb307a48d34e1766ec154 and 4d13f3fb37d6f27b150b00c418f7b205b9481e46). I checked the output from the tests in SwaggerUI and didn't see any remaining issues.

Would be great if you could check the next release.

**Comment by WoH** [comment]
I'll ping @dgreene1 for another 3.x release.

**Comment by dgreene1** [comment]
@WoH i do plan on releasing this for you but I think it might be time to talk about me stepping down. I just accepted a UI Architect position so I won’t have as much time/focus/interest to work on server-side code.

**Comment by WoH** [comment]
@Ze-Khan would you mind checking if 3.0.3 solves this issue?
