### ISSUE TITLE
Doc for added jsDoc descriptors

### ISSUE THREAD

**Issue by sittingbool** [lukeautry/tsoa#569]
Hi, I was trying to integrate your system ito my new API and its a bit hard to understand this at first. Many things only came clear when digging deep into examples. For example where the RegisterRoutes comes from.

After figuring things out pretty much I started working and I wanted to describe my models better and see if its really validated like that.

So I saw in your tests/fixtures in the testmodel which descriptors you used in the commets. I also read references to jsDoc. But things like `@isInt` are not jsDoc, are they? Where can I get a documentation of which descriptors are available and how to set them up correctly?

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Possible Solution
1. More description on what generator do
2. more description on how to deal with models
3. have a README with documentation or a link to the docs if already existing

**Comment by WoH** [comment]
Right now, the Readme covers basic setup, but while the tests (Models and Controller fixtures) show a lot of the possibilities around specs and validation, it's hard to find them and there is a lot of room for improvement especially around the visibility.
We are always looking for doc contributions and would be very grateful if you'd be willing to provide a PR :+1:
