### ISSUE TITLE
koa route function has to return promise

### ISSUE THREAD

**Issue by myflowpl** [lukeautry/tsoa#57]
Otherwise it will fail when you await something inside the controller.

Line 30 in /src/routeGeneration/templates/koa.ts

Just add return before promiseHandler(...) call.

I really like this project, so i hope to contribute in the future, but for now, i would be really grateful for this quick fix with next release, thanks.

**Comment by lukeautry** [comment]
@myflowpl This is fixed as 1.1.1. Thanks!
