### ISSUE TITLE
RFC: Rework resolving TypeScript enums

### ISSUE THREAD

**Issue by WoH** [lukeautry/tsoa#571]
# Summary
[summary]: #summary

Currently, enum generation has some room for improvement. It supports constructs that should probably not be supported, in a fashion that leads to problems down the road.

# Motivation
[motivation]: #motivation

Currently, tsoa supports enums of 3 shapes of enum members:

- No initializer
- Literals
- Expressions

```ts
enum MyEnum {
  ONE //EnumMember without initializer
}

enum MyEnum2 {
  TWO = 2, //EnumMember with literal (number or string)
  THREE = 'THREE' as any //EnumMember with Expression (something as any), legal
  FOUR = 4 as any //EnumMember with initializer of type Expression and expression of type NumericLiteral, will silently casted to '4'
  FIVE = {} as any //EnumMember with initializer of type Expression, will silently be casted to '3'(!!!)
}
```

Metadata for MyEnum2:

```js
  "EnumStringValue": {
    "dataType": "refEnum",
    "enums": [2, "THREE", "4", "3"],
  },
```

While MyEnum2.THREE will work, since we are just casting a string enum member as any and tsoa will treat that properly since the current code only supports AsExpression with expression of type StringLiteral. However, Numeric literals would already be silently casted to strings. If the expression does not have a `text` property, the current fallback is `String(index)`, we end up with some pretty unreasonable behavior. (See MyEnum.FIVE)

I would suggest we should simply error if a user provides an Expression. We can only ensure we don't have to deal with arbitrary expressions that will be hard to validate if we cut this feature and address enum members with expressions at a later stage.

# Approach
[approach]: #approach

Whenever we encounter anything but a Numeric|StringLiteral as the initializer of an enum member, we throw an Error. Falling back to index should only be valid if there is explicitly no initializer.

NOTE: We can allow mixing strings and enums here, since we can split the enum into a numeric enum and a string enum combined using `anyOf` in OpenAPI.
Since swagger does not support this, we can save the metadata with the correct format and specify type string enum once we rework Swagger/OpenAPI validation, which will be another RFC at a later point, OR throw when we try to render a mixed enum using the SpecGenerator for Swagger.

# Drawbacks
[drawbacks]: #drawbacks

This is a breaking change.

**Comment by dgreene1** [comment]
I agree, the enum stuff is problematic. I think this is a fine proposal for OpenApi 3 and in our v3 branch. I'd leave the Swagger v2 generation alone (I assume that's what you would have done anyway).

**Comment by WoH** [comment]
For now, I'd just change from warning to error (Swagger), since that's what you  wanted to do for v3 If I remember correctly (please confirm). There is an idea in my head to rework enum validation and make it more consistent with other validations (number, string, boolean), that'll probably be more controversial, which is why I decided to separate it out.
