### ISSUE TITLE
Advice on not forgetting Security decorator

### ISSUE THREAD

**Issue by fantapop** [lukeautry/tsoa#572]
## Sorting

* I'm submitting a feature request

* I confirm that I used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
We have multiple types of Security including some methods which are unsecured.  I'm worried that we may accidentally forget to include a Security() decorator for some new method that is created.  Is there a way to require that its applied to every method?  I was thinking I could explicitly have `@Security('unsecured')` if I could require it.

## Current Behavior
I can't find a way to do this.

## Possible Solution
Another option I'd consider is if there was a linting rule that required it for each method or controller.

**Comment by WoH** [comment]
To enforce any kind of API design practice, I'd suggest looking at a linter that works on top of OpenAPI.
Maybe have a look at [Zally](https://github.com/zalando/zally) or [Speccy](https://github.com/wework/speccy)

**Comment by fantapop** [comment]
Interesting.  Thank you.
