### ISSUE TITLE
Custom Default OperationId generation

### ISSUE THREAD

**Issue by fantapop** [lukeautry/tsoa#573]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior
OperationId is set by default to the method name which is by default often not unique and can be overridden on a case by case basis using the `@OperationId` decorator.  This means if I want to use a more unique scheme, I need to override for every method.

## Possible Solution
Our apis our resource based so In order to generate a unique operationId I need to add the resource in there.  It's probably going to be something like <methodName><resourceName> everytime.   for example `getPet`, `createPet`, `deletePet`.  It would be cool, if I could just do something like globally override default operationId gen and then use a decorator like `@resource('pet')` on the controller. I could still use `@OperationId()` in more rare circumstances like `@OperationId('getPetById')`.   Or maybe something like `@OperationGenerator(functionName => functionName + Pet)` at the controller level.

**Comment by dgreene1** [comment]
Would a fix for this be to make sure that tsoa  always ensures the operation ID is unique?

As for the override, I think I would prefer a more generic solution like a decorator that takes a callback function. That way people could override it however they like.

**Comment by fantapop** [comment]
If the method of uniqueness caused an unfortunate operationId to be used in the resulting swagger file, I'd likely still want to customize it.  However if the method for creating uniqueness also resulted in okay names for the operations, it could be fine.  For example, if the file name was used alongside the method name it, I would be less likely to further try and customize it.  Although, changing the operationId like that would be nonbackwards compatible.

In otherwords my main concern is not actually the uniqueness bit.  It's more around having a thoughtfully named operation for downstream generated apis.

**Comment by dgreene1** [comment]
@WoH what are your thoughts on the above?

@fantapop breaking changes aren’t a problem since we’re about to cut a new major release and it could be part of that.

**Comment by WoH** [comment]
My thoughts are that this request is written under the assumption that we actually use the Decorators at runtime, which we (currently) don't do.
tsoa only does AST parsing at the moment, this would require a hybrid approach (AST parsing + Reflection (which would allow us to get the function result without writing an interpreter))
