### ISSUE TITLE
How to serve swagger api using just http

### ISSUE THREAD

**Issue by ysabri** [lukeautry/tsoa#576]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
I'm setting up a project quick and I want to host my swagger api using just http protocol for now.

## Current Behavior
I am currently setting the schema config to ["http"] but I am still not able to access it from my browser. 

## Context (Environment)
 Version of the library: 2.5.13
 Version of NodeJS: 12.12.0

 * Confirm you were using yarn not npm: [x]

**Comment by dgreene1** [comment]
There isn’t enough information in your ticket. Can you share a screenshot, or some logs?

And what do you mean by “swagger api?” Swagger is a specification.

So which of the following are you trying to do?
a) you’re trying to provide the swagger page?
c) you’re trying to provide a server that exposes restful endpoints?
d) you’re trying to serve the swagger JSON via a restful endpoint?

If you reply with as much information as you can provide, I’ll do my best to help.
