### ISSUE TITLE
Does this library handle "dynamic/generated" routes?

### ISSUE THREAD

**Issue by tnrich** [lukeautry/tsoa#583]
Does tsoa perform a static analysis of the code, or will it handle finding "generated" routes

My colleague asked a similar question here in typescript-rest-swagger: 
https://github.com/thiagobustamante/typescript-rest-swagger/issues/89

Thanks!

**Comment by WoH** [comment]
Static analysis

**Comment by tnrich** [comment]
Thanks @WoH
