### ISSUE TITLE
ValidateModel Overwrites Targets / Targets are not unique

### ISSUE THREAD

**Issue by nodehack** [lukeautry/tsoa#585]
When using decorators to validate the fields of your input models, fields with the same name get overwritten with other errors.

## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

BadArgument errors thrown by the param validators should have unique targets so they do not trample on other fields.  Also the target should indicate where exactly in the payload the issue is so it should indicate all parent nodes. For example:

```
interface A {
  /** @minLength 1 name must not be empty */
  name: string;
  /** @minLength 1 foo must not be empty */
  foo: string;
}

interface B {
  /** @minLength 10 name must be at least 10 characters */
  name: string;
  bar: A;
}

interface C {
  /** @minLength 4 name must be at least 4 characters */
  name: string;
}

interface MyInput {
  arg1: B;
  arg2: C;
}

@Post('/thing')
@Response(204, 'Did the thing')
public async doTheThing (@Body() body: MyInput) : Promise<void> {...}

```

If I call the doTheThing api with the following payload:
```
{
  "arg1": {
    "name": "",
    "bar": {
      "name": "",
      "foo": "pickles"
    }
  },
  "arg2": {
    "name": ""
  }
}
```
I should get:
```
{
  "error": {
    "code": "BadArgument",
    "message": "Validation Error",
    "details": [
      {
        "target": "body.arg1.name",
        "message": "name must be at least 10 characters"
      },
      {
        "target": "body.arg1.bar.name",
        "message": "name must not be empty"
      },
      {
        "target": "body.arg2.name",
        "message": "name must be at least 4 characters"
      }
    ]
  }
}
```

## Current Behavior

Fields with the same field name get overwritten with errors from previous validation steps.  The above example returns this result instead:
```
{
  "error": {
    "code": "BadArgument",
    "message": "Validation Error",
    "details": [
      {
        "target": "body.name",
        "message": "name must be at least 4 characters"
      }
    ]
  }
}
```
Notice how we lose the validation errors from the other 2 `name` fields and the target does not make it easy for us to find which name field is bad since the parent is just "body".

## Possible Solution

When validating the model, the parent variable should be updated to include the name of the field.  This will make the target unique to keep from overwriting other errors as well as make finding the problem with the request payload easier.

In validateModel after setting the name and parent variables I added the following hack and it was giving me more accurate errors:
```
if (parent === 'body.') {
  parent = '';
}
if (name !== 'body.') {
  if (parent && !parent.endsWith('.')) {
    parent = parent + '.';
  }
  parent = parent + name + '.';
}
```
This does not account for arrays which should also be considered when making any changes here.  A possible target for an array with an error could be `body.things[1].name` indicating the array item that fails validation.

## Steps to Reproduce

Provided in the example above.

## Context (Environment)
Version of the library: 2.5.12
Version of NodeJS: 10.15.3
* Confirm you were using yarn not npm: [ ]

## Detailed Description

See possible solution.

## Breaking change?

Probably not.  The current system is masking other issues but those systems should already be handling BadArgument exceptions.

**Comment by dgreene1** [comment]
Would you be interested in submitting a PR to fix this? It would help a lot of people! :)

**Comment by dimitor115** [comment]
@dgreene1 @WoH  I would like to try :smile: If there is still need to do it.

**Comment by WoH** [comment]
I think this may have been fixed by another PR, so please make sure this is still happening in the beta releases.

**Comment by WoH** [comment]
This should be fixed in v3
