### ISSUE TITLE
How to serve the swagger.json itself from the server.

### ISSUE THREAD

**Issue by iursinoliveperson** [lukeautry/tsoa#586]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x ] support request

* I confirm that I
  - [x ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

Is there a recommendation for how to serve the swagger.json itself in the server?

**Comment by dgreene1** [comment]
No, there is no standard recommendation. You should use whatever static file serving library you’re comfortable with that works with the version of swagger UI that you’d like. There are different ones for Koa and also for express.

While it’s not the 100% certain answer, you’re welcome to see how I did in my koa example: https://github.com/dgreene1/tsoa-koa-example-with-typeorm
