### ISSUE TITLE
Can't find documentation

### ISSUE THREAD

**Issue by InsOpDe** [lukeautry/tsoa#587]
I'm searching for various features of your project but could only retrieve them looking in test-files, issues or code. Thats rather cumbersome - I cannot find a proper documentation.
I'm aware that a similiar issue (#254) exists but would argue that it should stay open until it was fixed.

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
I expected some sort of document which tells me about topics like validation, models, available decorators, available decorators in JSDocs etc

## Current Behavior
I found a list of JSDoc decorators via [this](https://github.com/lukeautry/tsoa/issues/143) Issue which redirected me to the [specifications](https://github.com/lukeautry/tsoa/blob/121565d0facbe86d1793612cab0a8df666e5d6f9/tests/fixtures/testModel.ts#L236)

## Possible Solution
Maybe use the github wiki instead?

**Comment by WoH** [comment]
See #569.
