### ISSUE TITLE
Colon support for path parameters

### ISSUE THREAD

**Issue by itamarco** [lukeautry/tsoa#590]
## Sorting
 
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
My project is written in nest.js.
Path parameters are declared using a preceding colon.
e.g.
```ts
@Path('users/:id')
getUserById(@Param('id') id) {
  ...
}
```
Would like `tsoa swagger` to generate path `/users/{id}` with path param `id`.

## Current Behavior
When running `tsoa swagger` it fails with exception

## Possible Solution
add this line at the end of `normalisePath` function in `pathUtils.ts`:
```
normalised = normalised.replace(/\/:([^/]+)/g, '/{$1}');
```
in order to convert `:param` to `{param}` in the result swagger.json

## Steps to Reproduce
Define a path parameter using a preceding colon.
e.g.
```ts
@Path('users/:id')
getUserById(@Param('id') id) {
  ...
}
```

run `tsoa swagger`

**Comment by dgreene1** [comment]
Can you link to a repo that shows how your code is able to successfully integrate with NestJS?

I ask because it’s not currently on our list of supported frameworks but we would like to work with it.

**Comment by itamarco** [comment]
I forked version of tsoa https://github.com/SSCIsrael/tsoa
and use it as a dependency in this demo nest.js progect: 
https://github.com/SSCIsrael/nestjs-tsoa-integration

**Comment by itamarco** [comment]
@dgreene1 @lukeautry 
I have a PR ready (to support colon path params).
Could I please send it?

**Comment by dgreene1** [comment]
You can send the PR but I can’t guarantee that we’ll approve it since it would be strange to have two different types of delimiters.

cc @WoH

**Comment by WoH** [comment]
I think this is a welcome improvement for express users. My worries however are that we end up supporting an awkward subset of valid express style url definitions.
As an example: `/my/routes?` should be `/my/route{1}/` or at lease warn about incompatibilities.
