### ISSUE TITLE
Can not create an API with Post Data available in the Swagger UI

### ISSUE THREAD

**Issue by joppino** [lukeautry/tsoa#596]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

* I confirm that I
  - [X ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
When using @BodyProp decorator, I'd expect that those BodyProp parameters are then available as parameters in the Swagger UI. Instead I see that no parameters are available. If I use an interface as type, I end up with a JSON input, which I do not want (I need parameters like a=b&c=d passed in the post body.

## Current Behavior
The API is created, but with no input parameters in the Swagger UI when using BodyProp decorators.

## Steps to Reproduce

1. Create a new API with @BodyProp decorators as api parameters
2. Generate with TSOA

**Comment by dgreene1** [comment]
1) I can’t help you unless you provide the code that has the problem. Please follow the issue template that was provided.
2) We can’t control how Swagger UI works. That’s why the issue template also asks for the swagger YAML/JSON output so we can see if the mistake is on the tsoa side or on the swagger UI side. Please provide that too.

**Comment by WoH** [comment]
I assume this is a duplicate of https://github.com/lukeautry/tsoa/issues/516.

**Comment by khaino** [comment]
I faced similar issue. 
```
@Route('/todos')
export class CreateTodoController extends Controller {


  @SuccessResponse('201', 'Created') // Custom success response
  @Post()
  public async createTodo(@Body() requestBody: CreateTodo): Promise<void> {
    // new UserService().create(request);

    console.log(requestBody)
    this.setStatus(201); // set return status 201
    return Promise.resolve();
  }
}
```
tsoa.json
```
{
  "swagger": {
    "outputDirectory": ".",
    "entryFile": "./src/index.ts",
    "controllerPathGlobs": ["./src/rest/**/*.ts"],
    "noImplicitAdditionalProperties": "silently-remove-extras",
    "specVersion": 3,
    "schemes": ["http"]
  },
  "routes": {
    "basePath": "/",
    "entryFile": "./src/index.ts",
    "middleware": "koa",
    "routesDir": "./src/rest"
  }
}
```
If I send the following request body 
`curl -X POST "http://localhost:3000/todos" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"name\":\"string\",\"description\":\"string\"}"`
```
{
  "name": "string",
  "description": "string"
}

OR

{"requestBody" :{
  "name": "string",
  "description": "string"
}}

OR

{
"requestBody": "asdfasdfasd",
  "name": "string",
  "description": "string"
}
```
I got `{"fields":{"requestBody.requestBody":{"message":"'requestBody' is required"}}}` error

If I change `@Body()` to `@BodyProp()`, I got the following error

```
AssertionError [ERR_ASSERTION]: status code must be a number
      at Object.set status [as status] (PROJECT_PATH/node_modules/koa/lib/response.js:87:5)
      at Object.status (PROJECT_PATH/node_modules/delegates/index.js:92:31)
      at Object.<anonymous> (PROJECT_PATH/src/rest/routes.ts:93:31)
      at Generator.next (<anonymous>)
      at PROJECT_PATH/src/rest/routes.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (PROJECT_PATH/src/rest/routes.ts:4:12)
      at RegisterRoutes.router.post (PROJECT_PATH/src/rest/routes.ts:84:43)
      at dispatch (PROJECT_PATH/node_modules/koa-compose/index.js:42:32)
      at PROJECT_PATH/node_modules/koa-router/lib/router.js:353:16
```
https://stackoverflow.com/questions/60411081/status-code-must-be-a-number-error-on-post-request-tsoa-typescrpt

**Comment by joppino** [comment]
Worked for like 14 hours day for the past two weeks. I'll finish this soon, promised

**Comment by Farsen976** [comment]
Hello, any update for this PR ? I use  `@BodyProp`  on my project too and not have parameters on the UI is awful :/  @joppino ?
