### ISSUE TITLE
Responses other than 200 not being added to swagger gen.

### ISSUE THREAD

**Issue by ghost** [lukeautry/tsoa#598]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
With this method signature.

```ts
    @Response<ErrorResponse>(FORBIDDEN.status)
    @Response<ErrorResponse>(INVALID_REQUEST_SCHEMA.status)
    @Response<ErrorResponse>(INVALID_REGION.status)
    @Response<ErrorResponse>(INVALID_PASSWORD.status)
    @Post()
    public async postDevAccount(@Body() requestBody: DevAccountRequest): Promise<DevAccountResponse> {
```

I expected to get the ErrorResponse and usage of it in the swagger.json

## Current Behavior
Instead I get the error response generated but it not referenced anywhere in swagger.json
```json
"ErrorResponse": {
				"properties": {
					"code": {
						"type": "string"
					},
					"description": {
						"type": "string"
					},
					"status": {
						"type": "number",
						"format": "double"
					}
				},
				"required": [
					"code",
					"description",
					"status"
				],
				"type": "object",
				"additionalProperties": true
			},
```

```json
"/devaccount": {
			"post": {
				"operationId": "PostDevAccount",
				"responses": {
					"200": {
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/DevAccountResponse"
								}
							}
						},
						"description": "Ok"
					}
				},
```

## Steps to Reproduce
1. Write method signature like the above
2. run an npm script like "mkdir -p ./generated && tsoa swagger && tsoa routes"
3. observe that there is only one value in "response" for the method.

## Context (Environment)
Version of the library: 2.5.13
Version of NodeJS: v12.13.0
* Confirm you were using yarn not npm: [ ]

## Suggested solution

Provide more information in the README.md about how the @Response tag works assuming I'm just using it wrong.

**Comment by WoH** [comment]
Should work if you use a number instead of an enum.
If you're interesting in adding support for TS Enums there, I can point you towards where you should be looking.

**Comment by iursinoliveperson** [comment]
Ah, kind of like how in java it won't compile unless you use literals and references to literals in annotations. I see. Thanks.

**Comment by WoH** [comment]
I'm not familiar enough with Java to comment on them, but thinking of the tsoa decorators as annotations is a better mental model than a typical TS decorator, since we statically analyze them instead of evaluating them at runtime.

**Comment by iursinoliveperson** [comment]
So does that mean if I have response bodies predefined to handle different errors I can't share the response code and description between them and the openapi spec?

**Comment by WoH** [comment]
Right now, there is not. However, that's mostly a wiring issue.

We have a utility function [here](https://github.com/lukeautry/tsoa/blob/master/src/metadataGeneration/initializer-value.ts) that could probably already grab the number from an object property. However, the [method generator](https://github.com/lukeautry/tsoa/blob/master/src/metadataGeneration/methodGenerator.ts#L113) does not use that and instead only parses the number into a string.

If you'd be interested in this feature, I'd gladly accept a PR :beers:

**Comment by dimitor115** [comment]
@WoH If you are still interested in PR, I would like to try implementing this :smile:

**Comment by WoH** [comment]
Sure, would be a nice feature!
