### ISSUE TITLE
Support enums

### ISSUE THREAD

**Issue by lukeautry** [lukeautry/tsoa#6]
Acceptance Criteria:
- Enum properties/return types should generate valid swagger enum types
- Routing layer should validate enums

**Comment by danzel** [comment]
For my uses I'd like to declare an enum and have the field be the string values

```ts
enum ResultType {
    Success,
    FailureNoPermission
}
```

Should result in swagger like:
```js
"type": "string",
"enum": [ "Success", "FailureNoPermission" ],
```

Not sure if other people would like the numeric values.

**Comment by lukeautry** [comment]
I think the string representation that you've proposed is ideal. The number
representation is basically meaningless from a human readability standpoint.

**Comment by lukeautry** [comment]
@danzel Just wanted to provide an update here; enum support hasn't been straightforward, at least for the routing side of things. Generating the correct swagger spec is a straightforward, but wiring up the autogenerated routes to 1) convert strings to their enum values and 2) validate enum values takes a bit more work. Hope to have something in the next week or so.

**Comment by danzel** [comment]
Thanks, no hurry the string work around is fine :)

**Comment by egandro** [comment]
You can try using this:

`export type CaseEnum = "Unchanged" | "Capitalized" | "FirstLetterUppercase" | "CamelCase" | "PascalCase" | "Lower" | "Upper";

export const CaseEnum = {
    Unchanged: "Unchanged" as CaseEnum,
    Capitalized: "Capitalized" as CaseEnum,
    FirstLetterUppercase: "FirstLetterUppercase" as CaseEnum,
    CamelCase: "CamelCase" as CaseEnum,
    PascalCase: "PascalCase" as CaseEnum,
    Lower: "Lower" as CaseEnum,
    Upper: "Upper" as CaseEnum
};`

It feels like an enum - but it's actually a class/string

**Comment by maxcan** [comment]
@lukeautry  would it be easier to support string literal types instead of enums?

for example:
```typescript
type Auth = "Facebook" | "Google" 
```

**Comment by lukeautry** [comment]
@maxcan Yeah, I have a branch going to implement that exact thing; the issue you opened #39 is caused by the inability to parse a type alias/string literal type.

Feel free to take a stab at it though, it'll probably be next week sometime before it can be completed.

**Comment by maxcan** [comment]
@lukeautry which branch is it? None of the branch names seemed obvious

**Comment by lukeautry** [comment]
Sorry Max, didn't mean to imply it was a remote branch, just a local branch
that's exploring the idea of parsing string literal types.

**Comment by maxcan** [comment]
@lukeautry is it worth using it as a starting point?  If not, I can start off master, just tell me where to look in the code

**Comment by adhamhf** [comment]
hey @lukeautry I'm only interested in swagger support...  any chance you could share the code that gets enums to work with swagger?  I could then use it in a fork.

**Comment by alexey-pelykh** [comment]
@maxcan do you plan to add support for using string literal types as @Path arguments?

**Comment by maxcan** [comment]
@alexey-pelykh I'm actually not using tsoa at the moment - jumped over to the graphql dark side so I won't be making any more changes.  Happy to give some tips if you want to take it up though.

Max

**Comment by alexey-pelykh** [comment]
@maxcan yeah, I have no choice then :) I've looked through the code more or less, string literal as "pathable" type - just something that was missed out or there was a reason for not doing that?

**Comment by maxcan** [comment]
honestly, don't remember

**Comment by alexey-pelykh** [comment]
union (string literals) fails over here https://github.com/lukeautry/tsoa/blob/master/src/metadataGeneration/parameterGenerator.ts#L128

**Comment by alexey-pelykh** [comment]
So it's impossible to use ```type test = 'a' | 'b';``` in Header, Query or Path parameters

**Comment by maxcan** [comment]
ah ok, I see what you mean.  no, I never added support for that.  I imagine i shouldn't be too difficult though, just not on my radar.  maybe use the PR above as a guide?

**Comment by alexey-pelykh** [comment]
@lukeautry I'd love to submit a PR regarding enums-as-union-types and alias types, yet it bases on https://github.com/lukeautry/tsoa/pull/77 and https://github.com/lukeautry/tsoa/pull/75 so I'd like to ask to take a look on those

**Comment by J-Ibarra** [comment]
Hello any update for this support, actually I am try to add type and enum to response body but trow in TypeResolver, the enum name, UserType isnt equal to SafeArray

```
export enum MerchantStatus {
  active = 'active',
  pending = 'pending',
}

export class User {
  uid: string;
  merchantStatus: MerchantStatus;
}
```
`
Unhandled rejection Error: No matching model found for referenced type MerchantStatus. If MerchantStatus comes from a dependency, please create an interface in your own code that has the same structure. Tsoa can not utilize interfaces from external dependencies. Read more at `[https://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD](https://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD)

in this block filter its empty because 
![image](https://user-images.githubusercontent.com/4218738/79499179-8e0c2900-7ff8-11ea-867c-6f2b88c54468.png)

the typename no is SafeArray

**Comment by WoH** [comment]
Could you tell me if this issue still applies to the v3 beta releases?

**Comment by J-Ibarra** [comment]
> Could you tell me if this issue still applies to the v3 beta releases?

I just upgraded to version 3.0.4, and the problem persists

![image](https://user-images.githubusercontent.com/4218738/79511091-9a9a7c80-800c-11ea-831f-bc37e10783a2.png)

in the filter dont match 

` return (modelTypeDeclaration.name as ts.Identifier).text === typeName;` 

I noticed the change in the class **SpecGenerator**

`protected abstract getSwaggerTypeForEnumType(enumType: Tsoa.EnumType): Swagger.Schema2 | Swagger.Schema3;`

I can also see that the kind of enum is 245 `ClassDeclaration` and not 248 `EnumDeclaration`
