### ISSUE TITLE
Ability to generate swagger spec for specific authorization method

### ISSUE THREAD

**Issue by fantapop** [lukeautry/tsoa#604]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior

Generated swagger document contains all methods.

## Use Case

We use the same back end api for 2 different clients.  They use different authentication methods.  while some of the methods overlap, many do not.  I'd love to be able to generate a swagger file specific to each client.  This would also that client to know if a backwards incompatible change was isolated to api functions that it cared about.  It seems like a natural way to be able to divide a spec into multiple is with auth method.

## Possible Solution
Filter out paths during spec generation which are not allowed by the requested auth method.  I'm not sure about the schema objects.  Custom tsoa api json configs could be provided and passed at the command line.

## Context (Environment)
Version of the library: 3.0.2
Version of NodeJS: 12.12.0
* Confirm you were using yarn not npm: [x]

## Breaking change?
No

**Comment by fantapop** [comment]
I recognize this is not on the current roadmap.  Would you be willing to accept a PR for this functionality or is it out of line with future plans for TSOA?

**Comment by WoH** [comment]
I'd have to at least see the proposed changes to the API surface.
Right now I think this is a pretty uncommon requirement, so I'd see this as a post processing step applied to the generated OAS.

**Comment by fantapop** [comment]
I was able to implement this outside the framework by programmatically filtering the swagger doc.  It seems better to keep this outside of tsoa.
