### ISSUE TITLE
fields in ValidateError incorrect for arrays containing refObjects

### ISSUE THREAD

**Issue by fantapop** [lukeautry/tsoa#605]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Field names returned inside a ValidateError object should be sufficient to locate field inside a type.

## Current Behavior
The errors are missing the array index.  

## Possible Solution
It looks like the validateModel function is different caller contexts which should dictate how the parent is sent down to the child.  I was able to fix the exact problem I was running into by checking if the current element name looked like an array index. I don't know if this is a good general solution however.  I was going to submit a PR and then saw the guidelines to create an issue first.  https://github.com/fantapop/tsoa/commit/e6a5727f3aaff090ab17b9174c7c113b89ec6d39

## Context (Environment)
Version of the library: 3.0.2
Version of NodeJS:  12.12.0
* Confirm you were using yarn not npm: [x]

## Breaking change?
If people are relying on the incorrect paths then it would be broken for them after this fix.

**Comment by WoH** [comment]
I like the idea! Would you be able to submit a PR for the 3.x branch?
This way we don't break compatibility.

**Comment by WoH** [comment]
I looked at the code and noticed I fixed a similar issue for refType naming in aliases:

https://github.com/lukeautry/tsoa/blob/3.x/src/routeGeneration/templateHelpers.ts#L644

```
const parentName = modelDefinition.type.ref ? parent + name + '.' : parent;
```

I think we should probably fix the model name instead of checking.

**Comment by fantapop** [comment]
I totally agree this isn't the greatest fix. I'm unclear why we wouldn't always want to append name + '.' to create the new parent in this case.  When I make it this, a lot of the tests fail because it adds an additional layer to the expected field name.  For example, these https://github.com/lukeautry/tsoa/blob/3.x/tests/integration/dynamic-controllers-express-server.spec.ts#L666 become something like `'body.body.floatValue'`.  But it seems like for nested objects we'd always leave out some layers if we didn't have it. IMO, I'd actually want this to just be: `'floatValue'` because these fields are at the top level of the object from a clients perspective.  Is having the additional `body` that's currently in front of these being used for something or is it just there by happenstance?

On a related note, using a standard protocol such as [jsonpath](https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html) or [jsonpointer](https://www.npmjs.com/package/json-pointer) to describe these would be helpful for people consuming the api.  I noticed that its already pretty close to being jsonpath compatible.

**Comment by fantapop** [comment]
Okay, I dug a bit deeper into how this is being done.  Please take a look at the PR when you have time.  A couple other things I wanted to discuss:

1) does it make sense to leave the top level field name in the body? I think the current behavior is to use the variable name that the body is being stored in.   For our code base we put it in requestBody so I strip this value out before sending them to the client.  I think there is some argument to be made for being able to differentiate a field error from the various methods of receiving data (i.e. body, header, query, etc).  I could see receiving a parameter via the body and one in a query param with the same name and wanting to be able to report on an error for both. This can sort of be done today for `body` since that variable name gets prepended to the field path.  This pattern is not followed for header or query params and its a little annoying to deal with because that parent field name can change.  For example in these tests `map` is used at the top level.  https://github.com/lukeautry/tsoa/blob/3.x/tests/integration/dynamic-controllers-express-server.spec.ts#L812

I propose either
a) get rid of the top level item altogether so that each top level field in the type is at the top level for the field name.  Essentially make body look like headers and query params look today.
b) choose the string `body` as the prepender for what it will always be for body fields and annotate the other errors with their type (i.e. header, query) in a similar fashion.

2. I noticed a pattern in use for the intersection errors which is a little different than the others. That is that sometimes an error field name is the parent and then inside the message there is a nested json object for each error as opposed to having multiple top level errors.  Here is an example:  https://github.com/fantapop/tsoa/commit/13068bd19fd97fe57b05e2eb4f6a3b7d4caed73a#diff-ca2cb6dbbc5edbfa33be0b59816d0405R749

I propose unnesting these.  This will allow the offending subitem to be correctly targeted by a client.  Additionally, it can help to keep server implementation hidden from the client.

This would change the reference item above to:
```
          expect(body.fields['body.nestedObject.intersection.value2'].message).to.equal(
            "'value2' is required"
          );
```

3. As mentioned above, I'd be interested in hearing thoughts on using jsonpath or jsonpointer compatible string more formally for this key.  It's pretty close to both of them.

**Comment by WoH** [comment]
Thanks for digging into this. First of all, I agree with your assessment that consistency is lacking here and I'd accept any PR that moves us to a more consistent error interface. I'll have a look at your PR as soon as my schedule allows for it.
The best approach imo would be to be compatible with JSON pointers as defined in [RFC6901](https://tools.ietf.org/html/rfc6901) because this is the format OpenAPI uses itself.

**Comment by fantapop** [comment]
@WoH my PR that was merged addresses the original concern that that I was raising with this issue.  I like your suggestions around error key formatting and I think v3 beta is a good place to do those.  It seems like we should close this issue and make a new one for the consistency bit.  What do you think?

**Comment by WoH** [comment]
Once 3.0 is released, it'll be closed.
