### ISSUE TITLE
Make the 3.x Beta more obvious

### ISSUE THREAD

**Issue by givethemheller** [lukeautry/tsoa#609]
Would anyone object to mentioning the 3.x Release in big bold letters at the top of the Readme?

It wasn't obvious from the readme or npmjs that there was a 3.x release. Kinda need to spelunk the repo or look at some more detailed data farther down. I missed it in any case.

I put a lot of time into working on a problem that had been solved already in 3.x and I could have been working on more relevant bugs. 

Also, mad props to who ever did the work for utility types. I'd enjoy reviewing how you did it if you can point me at the PR

**Comment by WoH** [comment]
Once I feel like it's ready for a RC, I'll make sure it's more obvious. Right now, installing 2.5 is the safer approach recommended for most users.

**Comment by givethemheller** [comment]
I'm good with that, though I think you may be able to get a little more mileage out of folks like me. Thanks again for the package.
