### ISSUE TITLE
3.0 fails for utility types on route generation

### ISSUE THREAD

**Issue by givethemheller** [lukeautry/tsoa#610]
3.x Is not respecting Utility types. Fails to build. 

Reproduction repo provided.

## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
The generator should honor utility types.

## Current Behavior
Fails to build routes with Omit in the type decleration

## Reproduction steps
Clone https://github.com/givethemheller/tsoa-bug-tests
yarn install && yarn build

**Comment by WoH** [comment]
You'll need to add the types to the program. `Pick` is defined in `node_modules/typescript/...`

So, here is what I did: 
1. `yarn add tsoa@v3beta`
2. remove the ignore key in your tsoa config.
3. `yarn tsoa:swagger` ✔️
4. `yarn tsoa:routes` ✔️

**Comment by givethemheller** [comment]
Seeing multiple versions of Omit in my monorepo (Granted I used Pick for my example). Seems that some folks have re-emitted it. The TSOA package is complaining about multiple definitions found. 

I cant seem to get a "include" - "ignore" config to work. Trying to ignore the whole of node_modules and include the typescript package to avoid the conflict. Would that be a feature request or am I missing it in the docs?

**Comment by givethemheller** [comment]
Re-opening on account of the accidental closing.

Still need to resolve conflicts when multiple packages have declared or rather, redeclared a typescript utility type.

Solution would seem to be an "exclude" and "include" param. Block the whole of node_modules with exclude, honor specific folders in the "include".

**Comment by WoH** [comment]
Yeah, I don't think this has anything to do with the initial issue, feel free to open a new issue with a support request for handling multiple models with the same name.
