### ISSUE TITLE
v3.x @example tag does not work on model properties

### ISSUE THREAD

**Issue by jfrconley** [lukeautry/tsoa#615]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
@example tags placed on models should add examples to their respective properties

```ts
export interface TestInput {
    /**
     * a number prop
     * @example 2
     */
    number: number;
    string: string;
}
```

```json
"TestInput": {
  "properties": {
    "number": {
      "type": "number",
      "format": "double",
      "description": "a number prop",
      "example": 2
    },
    "string": {
      "type": "string"
    }
  },
  "required": [
    "number",
    "string"
  ],
  "type": "object",
  "additionalProperties": true
}
```

## Current Behavior
No example is generated for properties.

```ts
export interface TestInput {
    /**
     * a number prop
     * @example 2
     */
    number: number;
    string: string;
}
```
```json
"TestInput": {
  "properties": {
    "number": {
      "type": "number",
      "format": "double",
      "description": "a number prop"
    },
    "string": {
      "type": "string"
    }
  },
  "required": [
    "number",
    "string"
  ],
  "type": "object",
  "additionalProperties": true
}
```

## Context (Environment)
Version of the library: v3.x
Version of NodeJS: 12.16.1
* Confirm you were using yarn not npm: [x]

## Detailed Description
When writing complex models, it is much more ergonomic to include examples above individual properties.  Additionally, the inconsistency for @example support can be confusing.  This should be a fairly simple change.

## Breaking change?
Not that I can tell

**Comment by WoH** [comment]
I like the idea, but I'd add on that we don't support `@example` for parameters either, i.e.:

```ts
/**
 * @example name This is an example for name
 */
@Post('PostParamExample')
public async postParamExample(@Query() name: string): Promise<void> {
  return
}
```

**Comment by jfrconley** [comment]
That seems like a pretty simple change as well. My opinion is that @example should work everywhere description does.

**Comment by jfrconley** [comment]
I submitted a PR for this feature adding @example support for both parameters and properties
