### ISSUE TITLE
RFC: Provide Response Decorator for Express Users

### ISSUE THREAD

**Issue by WoH** [lukeautry/tsoa#617]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request
  - [x] RFC

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior
Currently, tsoa only supports 2 types of returns: The declared type of the controller method and `throw`, since TS does not limit what we can throw.
This however means that any return that is not of the declared Status (or 200) and the declared function return type must be thrown and caught, while documenting the caught error using the `@Response` decorator.
This may cause discrepancies between the documented type T used in `@Response<T>` and the return type another error handler may actually return.
While it may be impossible to avoid throwing and having a few additional `@Response<T>`, we should limit the amount of unnecessary throws.

```ts
  @Get('{id}')
  @Response<UnauthorizedError>(401, 'Unauthorized') // unchecked
  @Response<NotFoundError>(404, 'Design not found') // unchecked
  @Response<ValidationFailedResponse>(422, 'Validation failed') // unchecked
  @Response<StatusOnlyResponse>(500, 'Internal Server Error') // unchecked
  public async getDesignById(
    @Path() id: number,
    @Header('Authorization'): auth: string
  ): Promise<Design> {
    if (!this.isAuthorized(auth) {
       throw CustomError(401, "Unauthorized"); // unchecked, but we have to throw and hope our ErrorHandler makes this a UnauthorizedError
    }

    const design = findDesignById(id)

    if (!design) {
      throw CustomError(405, "message"); // unchecked, but we have to throw and hope our ErrorHandler makes this a NotFoundError, also 405 may be a mistake
    }


    return design;
  }
```

Furthermore, you can't ask tsoa for the Response object.

## Suggested approach
In order to safely add a `@Res()` decorator that documents the Response properly, I suggest a required type `TsoaResponse<StatusCode, ReturnType>` which enforces the response may only be assigned a specified status code and a specified ReturnType. `@Res` should cause the generation to fail if:

- the type of the Parameter is not `TsoaResponse`
- typeArguments are not present
- typeArg[0] is not provided and resolvable to a NumericLiteral (NumericLiteral or Enum)
- typeArg[1] is not provided

TypeScript should enforce that (via type TsoaResponse):
- The type assigned to `res.json()` is of type `ReturnType`
- The number assigned to `StatusCode` is a valid http status code.

```ts
  @Get('{id}')
  @Response<ValidationFailedResponse>(422, 'Validation failed') // tsoa failed
  @Response<ServerErrorResponse>(500, 'Validation failed') // server failed
  public async getParentDesignById(
    @Path() id: number,
    @Header('Authorization'): auth: string,
    @Res() unauthorizedResponse: TsoaResponse<401, UnauthorizedResponse>
    @Res() notFoundResponse: TsoaResponse<404, NotFoundResponse>,
  ): Promise<Design> {
    if (!this.isAuthorized(auth) {
       unauthorizedResponse(401, this.getErrorReturn(401)) // both status code and return type can be checked by ts
    }

    const design = findDesignById(id)

    if (!design) {
     notFoundResponse(404, this.getErrorReturn(404)) // both status code and return type can be checked by ts
    }


    return design;
  }
```

### Limitations

This means, we can probably unsafely apply a middleware that does not care about types, good APIs or any definition of reasonable behavior. You have been warned.

## Context (Environment)
Version of the library: 3
Version of NodeJS: 12
* Confirm you were using yarn not npm: [x]

## Breaking change?
No

**Comment by WoH** [comment]
Right now, if anyone is interested in this or a variation of this, I'd love to know what you think about the approach.

**Comment by michaelbeaumont** [comment]
Nice! This looks basically like what I want in https://github.com/lukeautry/tsoa/issues/387#issuecomment-608453128.

There I suggested that instead of a decorator `@Res`, the return type should be a union of possible responses and statuses, which I do like better, because what's the difference between `200` and `401` really? But I'm not sure whether decorators allow that much introspection.


I'm not totally sure why there is both the `@Response` function decorator and the `@Res` parameter decorator though?

**Comment by WoH** [comment]
`@Response` is used for documenting responses that are not returned according to method signature, i.e. what you try/catch.
`@Res` is an express response object. I'm not sure what the equivalent could be in koa.

The Problem with your implementation might be that it's going to involve a lot of change under the hood that I would not want to have to deal with (or, alternatively, most likely fundamentally break existing tsoa users, which is a non-starter)

**Comment by fgnass** [comment]
Why would I have multiple `@Res`-annotated method parameters that I don't even use inside the controller?
To me exposing the underlying response object feels like a code smell in the context of the controller pattern.

**Comment by WoH** [comment]
> Why would I have multiple @Res-annotated method parameters that I don't even use inside the controller?

If you don't use them, you don't need to declare them.

> To me exposing the underlying response object feels like a code smell in the context of the controller pattern.

What would your approach to multiple status code + response combinations be?
If we could rewrite tsoa from scratch, maybe returning one or an union `Response<Status, Headers, ReturnType>` would be fine, but as is, the response code is defined via decorator, so there is no way to know which response code is associated with which return type (in a way TypeScript can understand and check). If I'm missing something I'd be glad to know.

**Comment by fgnass** [comment]
I fully agree. If we want to stick to the imperative API, we have to resort to using decorators in some way to provide the mapping from status code to return type.

I think my confusion comes from the fact that the two parameters `unauthorizedResponse` and `notFoundResponse` are never accessed in your sample code. Maybe that's just a typo?

Personally I would prefer if error responses were returned in the same way as success responses rather than using a lower layer (Express) in the error case. Especially as this would be framework-agnostic.

I currently favour the `@Response<T>(200)` decorator as it feels the most natural to me and would only require a rather small change. That being said, a declarative API would probably be the cleanest solution in the long term.

**Comment by WoH** [comment]
> I fully agree. If we want to stick to the imperative API, we have to resort to using decorators in some way to provide the mapping from status code to return type.
> 
> I think my confusion comes from the fact that the two parameters `unauthorizedResponse` and `notFoundResponse` are never accessed in your sample code. Maybe that's just a typo?

Fixed.

> Personally I would prefer if error responses were returned in the same way as success responses rather than using a lower layer (Express) in the error case. Especially as this would be framework-agnostic.

I kinda agree. Maybe we can wrap it more elegantly.

> I currently favour the `@Response<T>(200)` decorator as it feels the most natural to me and would only require a rather small change. That being said, a declarative API would probably be the cleanest solution in the long term.

You can still do `@SuccessResponse<T>` (where you return `T` as the regular return type) and `@Response<U>`, but it's the user's responsibility to throw/catch in a way that the thrown error will be transformed to `U`>

**Comment by WoH** [comment]
Updated based on feedback from @fgnass:

> Personally I would prefer if error responses were returned in the same way as success responses rather than using a lower layer (Express) in the error case. Especially as this would be framework-agnostic.

Since we can't respond exactly like SuccessResponse without interfering with the regular return type, I changed the parameter passed by tsoa to be a function that can be called with `(status, returnType, headers?)`.
While I only implemented Express so far, the same API could be used for Hapi and Koa aswell.

**Comment by aktary** [comment]
> `@Response` is used for documenting responses that are not returned according to method signature, i.e. what you try/catch. These are untyped.
I have been struggling with understanding how the hell to use Response. Thank you for this comment... it should be in the documentation.

**Comment by WoH** [comment]
It's mentioned in the [Error Handling Docs](https://tsoa-community.github.io/docs/error-handling.html#specifying-error-response-types-for-openapi), but we should probably reference that from the Decorators section.
