### ISSUE TITLE
@is[number format] tags only work if a comment is present

### ISSUE THREAD

**Issue by jfrconley** [lukeautry/tsoa#622]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
@is[number format] tags (isInt, isLong, isDouble, and isFloat) should not require a comment after the tag.
```ts
/**
 * @isInt 
 */
export type NumberAlias = number;
```
```json
"NumberAlias": {
  "type": "integer",
  "format": "int32"
}
```

## Current Behavior
Currently, unless a comment is included, no number format is generated.
### Without comment
```ts
/**
 * @isInt 
 */
export type NumberAlias = number;
```
```json
"NumberAlias": {
  "type": "number",
  "format": "double"
}
```

### With comment
```ts
/**
 * @isInt test
 */
export type NumberAlias = number;
```
```json
"NumberAlias": {
  "type": "integer",
  "format": "int32"
}
```

## Possible Solution
Problem seems to be in getJSDocTagNames, where a comment is required
```ts
export function getJSDocTagNames(node: ts.Node) {
  let tags: ts.JSDocTag[];
  if (node.kind === ts.SyntaxKind.Parameter) {
    const parameterName = ((node as any).name as ts.Identifier).text;
    tags = getJSDocTags(node.parent as any, tag => {
      return tag.comment !== undefined && tag.comment.startsWith(parameterName);
    });
  } else {
    tags = getJSDocTags(node as any, tag => {
      return tag.comment !== undefined;               <====== Matcher requires comment
    });
  }
  return tags.map(tag => {
    return tag.tagName.text;
  });
}
```

## Steps to Reproduce
1. Create a numeric type alias
2. Add a "@isInt" tag in the jsdoc comment
3. Compile and see that the format and type are wrong

## Context (Environment)
Version of the library: v3.0.4
Version of NodeJS: 12
* Confirm you were using yarn not npm: [x]

## Detailed Description
It seem likes the function used to get JSDoc tags from the node will only return tags with a comment included, which should not be required for number format assertions. This is the case for type aliases and classes/interface model properties.

**Comment by WoH** [comment]
Have you checked if this also applies to i.e.
```ts
interface MyInterface {
  /**
   * @isInt
   */
  prop: number
}
```

and the class equivalent?

**Comment by jfrconley** [comment]
Just tested and this is indeed the case. I'll update the issue

**Comment by givethemheller** [comment]
This is a snippet from the project im working on. Currently not seeing this read @isInt in the controller declaration. Still formats as a double. Using 3.0.4

``` export class TestResultController {
  @Security("jwt", ["admin"])
  @Get()
  @Tags("Analytics")
  public async AdminFindTestResult(
    @Request() request: express.Request,
    /**
     * @isInt page
     */
    @Header("page") page?: number,
    /**
     * @isInt count
     */
    @Header("count") count?: number
  ): Promise<TestResult[]> {```

**Comment by WoH** [comment]
This is an unrelated issue. Feel free to open up a new issue with a support request.

**Comment by givethemheller** [comment]
@jfrconley @WoH After reviewing the unit tests, I discovered that, for at least method levels, the jsDocs defs need to be complete including the param definition. It did not require a comment to work though.

paramaterController.ts contains a good example. 

``` 
/**
   * Path test paramater
   *
   * @param {string} firstname Firstname description
   * @param {string} lastname Lastname description
   * @param {number} age Age description
   * @param {number} weight Weight description
   * @param {boolean} human Human description
   * @param {Gender} gender Gender description
   *
   * @isInt age
   * @isFloat weight
   */
  @Get('Path/{firstname}/{last_name}/{age}/{weight}/{human}/{gender}')
  public async getPath(
    firstname: string,
    @Path('last_name') lastname: string,
    @Path() age: number,
    @Path() weight: number,
    @Path() human: boolean,
    @Path() gender: Gender,
  ): Promise<ParameterTestModel> {
```

**Comment by jackey8616** [comment]
Hello guys,
I'm currently working on this patch, and here comes with a solution:
```ts
export function getJSDocTagNames(node: ts.Node, requireComment = false) {
  let tags: ts.JSDocTag[];
  if (node.kind === ts.SyntaxKind.Parameter) {
    const parameterName = ((node as any).name as ts.Identifier).text;
    tags = getJSDocTags(node.parent as any, tag => {
      return tag.comment !== undefined && tag.comment.startsWith(parameterName);
    });
  } else {
    tags = getJSDocTags(node as any, tag => {
      return requireComment ? tag.comment !== undefined : true; // <-- Here.
    });
  }
  return tags.map(tag => {
    return tag.tagName.text;
  });
}
```

I've dig a little bit and found out that getJSDocTagNames() is only invoke at two places,
which is typeResolver#getPrimitiveType() and typeResolver#getDateType(),
since Parameter's comment should always follow with a name comment, thus it no need to apply with requireComment parameter.

I think by adding a requireComment parameter can solver this issue,
and won't breaking any exists invoke, also keep future usage can choose not follow adding parameter name in comment.

I need someone help me to confirm this idea is correct in order to send a PR, thx folks!

**Comment by WoH** [comment]
requireComment default should be true imo.
Everything else seems good.

**Comment by jackey8616** [comment]
@WoH , I saw your comment, but don't know why is disappear in GitHub.  
I think it should `false`, please confirm.  
If it set to true, than we need to modify some exists invokes.  

Thank you.

**Comment by jackey8616** [comment]
Also, I want to add some checks to prevent orphan tags like below:
```ts
export function getJSDocTagNames(node: ts.Node, requireComment = false) {
  ...
  if (node.kind === ts.SyntaxKind.Parameter) {
    const parameterName = ((node as any).name as ts.Identifier).text;
    tags = getJSDocTags(node.parent as any, tag => {
      if (tag.comment === undefined) { // This if statment checks orphan tag.
        throw new GenerateMetadataError(`Orphan @${tag.tagName.text} tags should follow a parameter name in comment.`);
      }
      return tag.comment.startsWith(parameterName);
    });
  } 
  ...
}
```
