### ISSUE TITLE
Default tag only supports strings

### ISSUE THREAD

**Issue by jfrconley** [lukeautry/tsoa#623]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
default tag should parse input so that number examples can be provided
```ts
/**
 * @default 10
 */
export type PageLimit = number
```
```json
"PageLimit": {
  "default": 10
}
```

## Current Behavior
Currently all default tags are treated as strings
```ts
/**
 * @default 10
 */
export type PageLimit = number
```
```json
"PageLimit": {
  "default": "10"
}
```
## Possible Solution
A simple solution would be to use the same JSON parsing logic used when getting the node example. This would allow both numeric and object defaults while still keeping support for string defaults.

## Breaking change?
Because this would change parsing logic for existing usages for the default tag, it would be a breaking change. Current string defaults would now require quotes

**Comment by WoH** [comment]
Strings should be fine here. While it may not look great, the validation layer will support casting (default) strings to, i.e. numbers. Other way around is not supported, however, this is exactly what would happen if you specified `@default 10` on a string.

So unless the default parsing from comments is aware of the targeted type, string is probably the better option at first glance.

**Comment by jfrconley** [comment]
my issue is that openapi spec generated is not correct. This makes third party software such as Redoc show bad examples.

**Comment by WoH** [comment]
I mean, if we were to beak stuff, it'd be now, so I'm down to discuss this.
Checking the test suite, we don't use default strings any where, I assume `@default "10"` for strings would be your suggested alternative?

I ran `@default 10` on an integer through an OAS and rendered with redoc. Looks suboptimal, but it doesn't break, is this your issue?

**Comment by WoH** [comment]
I'll summarize the results from the other issue:
All JsDoc annotations that allow for parameters should JSON.parse these parameters to ensure we can distinguish based on data type. Because this would mean implicit strings, i.e. `@default hi` would have to become `@default "hi"`. In order to allow for backwards compat, we will quote these, but log a deprecation notice.
Triple backslashes should be permitted and removed before parsing.

**Comment by WoH** [comment]
@jfrconley are you interested in implementing this? This and #634 are the last changes I'm considering to bring into tsoa 3.

**Comment by jfrconley** [comment]
Sure, this shouldn't take too long

**Comment by jfrconley** [comment]
@WoH Looks like escape characters in strings will break JSON parsing, which kinda breaks RegEx. We might need to think a little bit more about options.

**Comment by WoH** [comment]
According to the rules, this string should:
1: Be taken from the JSDoc (it's a string there, `'` used to indicate that): `'```"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"```'`
2. Triple backslash escaped: `'"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"' `
3. JSON.parsed: `JSON.parse('"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"') // -> '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$'`

Am I missing something?

**Comment by jfrconley** [comment]
There are multiple issues. 
The original regex ([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$) would not be equivalent to the final regex (^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$). 

Additionally, JSON.parse would effectively look like `JSON.parse('"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"')` as JSDOC would preserve the original escape character. This is what causes parsing to fail.

**Comment by WoH** [comment]
> Additionally, JSON.parse would effectively look like JSON.parse('"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"') as JSDOC would preserve the original escape character. This is what causes parsing to fail.

That's what I was counting on. But I didn't think about JSON.parse removing the backslashes, I missed that in my own example. I'll see if I can come up with something that actually works(TM)

**Comment by WoH** [comment]
I think for now, I'd agree with any improvements that treat default like example and parse these Annotations (ideally supporting triple backslashes), while the other annotations remain untouched.

**Comment by WoH** [comment]
@jfrconley What's your opinion on something like this:

```
/**
 * @default {number} 10
 */
export type PageLimit = number
```

Would be similar to `@param {number} asd` for type annotations in JSDoc.

**Comment by niallmc** [comment]
Are there any updates as to when this feature will be rolled out?
