### ISSUE TITLE
@Hidden does nothing on [class based] model fields

### ISSUE THREAD

**Issue by E-gy** [lukeautry/tsoa#626]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [x] feature request
  - [ ] support request

Perhaps it was never inteded to, in which case, this is a feature request.

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Putting `@Hidden` on model [class] fields should hide them from the swagger document.
```ts
export class ClassBasedModelType {
	InstanceField: string;
	@Hidden() HiddenInstanceField: string;
}
```
Should produce
```json
"ClassBasedModelType": {
	"properties": {
		"InstanceField": {
			"type": "string"
		}
	},
	"required": [
		"InstanceField"
	],
	"type": "object",
	"additionalProperties": true
}
```

## Current Behavior
Currently the above model includes fields marked with `@Hidden` in the swagger:
```json
"ClassBasedModelType": {
	"properties": {
		"InstanceField": {
			"type": "string"
		},
		"HiddenInstanceField": {
			"type": "string"
		}
	},
	"required": [
		"InstanceField",
		"HiddenInstanceField"
	],
	"type": "object",
	"additionalProperties": true
}
```

## Context (Environment)
Version of the library: 3.0.4
Version of NodeJS: 13.11.0
* Confirm you were using yarn not npm: [ ]

## Detailed Description
Decorators on class fields are supported in TS, and class based models are supported in tsoa.
However `@Hidden` decorator does not work on fields of class based models - they are present in the generated swagger, instead of the expected not-being-there.

Though the use case of such feature is probably limited.

**Comment by WoH** [comment]
You're correct, but that decorator is not supposed to work on classes.
This should:

```
export class ClassBasedModelType {
  InstanceField: string;

  /**
   * @ignore
   */
  HiddenInstanceField: string;
}
```

**Comment by E-gy** [comment]
`@ignore` in jsDoc indeed works.
Thanks.

**Comment by oreporan** [comment]
Actually `@ignore` is not the same as hidden. 
Look at issue #1041

**Comment by felipe-muner** [comment]
it does not work for me..
