### ISSUE TITLE
Static properties in class based models get included

### ISSUE THREAD

**Issue by E-gy** [lukeautry/tsoa#627]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
When declaring a class based model, only instance (non-static) properties are part of the objects of said type:
```ts
export class ClassBasedModelType {
	InstanceField: string;
	static StaticField: string;
}
```
Therefore, static properties are not part of the response, thus neither the swagger doc
```json
"ClassBasedModelType": {
	"properties": {
		"InstanceField": {
			"type": "string"
		}
	},
	"required": [
		"InstanceField"
	],
	"type": "object",
	"additionalProperties": true
}
```

## Current Behavior
Currently static properties are included in the swagger doc nonetheless:
```json
"ClassBasedModelType": {
	"properties": {
		"InstanceField": {
			"type": "string"
		},
		"StaticField": {
			"type": "string"
		}
	},
	"required": [
		"InstanceField",
		"StaticField"
	],
	"type": "object",
	"additionalProperties": true
}
```

## Context (Environment)
Version of the library: 3.0.4
Version of NodeJS: 13.11.0
* Confirm you were using yarn not npm: [☹]

## Detailed Description
[Static properties](https://www.typescriptlang.org/docs/handbook/classes.html#static-properties) in TypeScript are part of the class rather than the instances. Logically, a JSON response based on a type containing static properties does not include static properties of the type, because they are not part of the instance itself (which is used for the response).
Nonetheless currently tsoa includes static properties in the swagger doc exactly same as instance properties.

**Comment by E-gy** [comment]
Current workaround is to `@ignore` all static properties (ignore works normally despite the props being static).

**Comment by dimitor115** [comment]
@WoH I can try to help with this one also 😁
