### ISSUE TITLE
Provide an example of setting response types other than application/json

### ISSUE THREAD

**Issue by yukipastelcat** [lukeautry/tsoa#641]
I'm writing service that compiles Svelte components to html and css to be injected into multiple frontend projects that will insert them via SSR. It's unclear how to set `Content-Type` header other than `application/json`, so my /html and /css endpoints are resulting into this in swagger.json:

```
"/services/html": {
  "get": {
    "operationId": "Html",
    "responses": {
      "200": {
        "content": {
          "application/json": {
            "schema": {
              "type": "string"
            }
          }
        },
        "description": "Ok"
      }
    },
    "security": [],
    "parameters": []
  }
},
"/services/css": {
  "get": {
    "operationId": "Css",
    "responses": {
      "200": {
        "content": {
          "application/json": {
            "schema": {
              "type": "string"
            }
          }
        },
        "description": "Ok"
      }
    },
    "security": [],
    "parameters": []
  }
}
```

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```json
"/services/html": {
  "get": {
    "operationId": "Html",
    "responses": {
      "200": {
        "content": {
          "text/html": {
            "schema": {
              "type": "string"
            }
          }
        },
        "description": "Ok"
      }
    },
    "security": [],
    "parameters": []
  }
},
"/services/css": {
  "get": {
    "operationId": "Css",
    "responses": {
      "200": {
        "content": {
          "text/css": {
            "schema": {
              "type": "string"
            }
          }
        },
        "description": "Ok"
      }
    },
    "security": [],
    "parameters": []
  }
}
```

## Context (Environment)
Version of the library: 2.5.13
Version of NodeJS: 12.16.1 LTS
* Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
In your case I don't know if tsoa makes a lot of sense for this endpoint, maybe I'd consider writing an endpoint in your application that's not handled by tsoa and potentially merging the docs, similar to how we [handle file uploads](https://github.com/lukeautry/tsoa#uploading-files).

Right now, tsoa is very much built around JSON Responses (with very few exceptions). If there is an approach that makes sure we properly document and return other content types, I am open to suggestions.
