### ISSUE TITLE
feat: avoid sending response

### ISSUE THREAD

**Issue by Eywek** [lukeautry/tsoa#647]
I'm using [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) in one of my controller, but as tsoa is replying when the promise resolves, it prevents events to be sent.

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Possible Solution

Add an option via a decorator? to disable auto response for this route.

**Comment by WoH** [comment]
Would something like https://github.com/lukeautry/tsoa/issues/617 work for you in this case?
You could send on res and return from the controller method once you're done sending events.

**Comment by Eywek** [comment]
I can already access the `Response` object via `req.res`, my issue is more that I'm never done sending events, it stops only when a user close the connection.

**Comment by WoH** [comment]
> my issue is more that I'm never done sending events, it stops only when a user close the connection.

My approach would be to return a Promise that resolves only when this event is called, but given my lack of expertise, maybe you can inform me why this is stupid: 

```ts
return new Promise<void>((resolve, reject) => {
  // write

  req.on('close', () => {
    resolve();
  });
});
```

**Comment by Eywek** [comment]
I thought about that but I was thinking resolving when the request is closed was going to lead to errors but in my tests it seems to work thank you
