### ISSUE TITLE
Composite types give error on swagger codegen

### ISSUE THREAD

**Issue by fantapop** [lukeautry/tsoa#649]
I realize this format was already changed once but the tildes (~) in the generated model names cause swagger code gen to error out.

## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Generated swagger spec should be able to be used in swagger code gen without ignoring errors.

```json
...
"schemas": {
    "Pick_Athlete_Exclude_keyofAthlete_id__OR__creationDate__OR__modificationDate__OR__fullName__": {
        "....": "..."
    }
}
```

## Current Behavior

```json
...
"schemas": {
    "Pick_Athlete.Exclude_keyofAthlete.id~OR~creationDate~OR~modificationDate~OR~fullName__": {
        "....": "..."
    }
}
```

## Possible Solution
I know that this problem has been thought about a lot considering the changes since V3 so I won't belabor this.  I've seen some of the other bug reports about why it was changed.  I just wanted to point out that swagger codegen wants each name to match this regex: `^[a-zA-Z0-9\.\- _]+$` which makes it seem like only dash or underscore or doubles of those would work as a separator character which won't cause errors.  Another potential solution would be to allow users to override those crazy names somehow with their own custom values.

## Steps to Reproduce

1.  Use composite types for a controller
2.  generate the swagger document
3.  use swagger-codegen to point at that generated document.

```
$ node_modules/\@openapitools/openapi-generator-cli/bin/openapi-generator generate -i http://localhost:5000/swagger.json --generator-name swift5 -o swift-app

[main] WARN  o.o.codegen.utils.ModelUtils - [deprecated] inheritance without use of 'discriminator.propertyName' is deprecated and will be removed in a future release.
Generating model for null
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec
(Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 30
Errors:
        -attribute components.schemas.Schema name Pick_Athlete.Exclude_keyofAthlete.id~OR~creationDate~OR~modificationDate~OR~fullName__ doesn't adhere to regular
expression ^[a-zA-Z0-9\.\-_]+$
        -attribute components.schemas.Schema name Omit_Athlete.id~OR~creationDate~OR~modificationDate~OR~fullName_ doesn't adhere to regular expression ^[a-zA-Z0-9\.\-
_]+$
Warnings:
        -attribute components.schemas.Schema name Pick_Athlete.Exclude_keyofAthlete.id~OR~creationDate~OR~modificationDate~OR~fullName__ doesn't adhere to regular
expression ^[a-zA-Z0-9\.\-_]+$
        -attribute components.schemas.Schema name Omit_Athlete.id~OR~creationDate~OR~modificationDate~OR~fullName_ doesn't adhere to regular expression ^[a-zA-Z0-9\.\-
_]+$
        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:471)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:498)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:415)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
```

## Context (Environment)
Version of the library: 3.0.4
Version of NodeJS: 12.12.0
* Confirm you were using yarn not npm: [x]

## Breaking change?
No because V3 is still in beta

**Comment by WoH** [comment]
I'm not convinced this is the right place to report this :smile: 
As far as I can tell, the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml#L38) refers to[ JSON-Schema format uri-reference](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.7.3.5), which refers to [RFC3986](https://tools.ietf.org/html/rfc3986#section-2.2), sections 2.2f are relevant here, the [Swagger Editor](https://editor.swagger.io) and [Swagger Parser](https://apitools.dev/swagger-parser/) also confirm that this is legal.

I'm not sure you can configure that in the CodeGen maybe, but I'd strongly recommend fixing this in their tooling.

**Comment by fantapop** [comment]
I did some spelunking into the open api code base.  I found this issue https://github.com/swagger-api/swagger-parser/issues/1309 which seems to concern easing the regex against non-"fixed-fields" under components. It references this part of the spec which seems to indicate that all the keys of the schemas object should adhere to this regex.

https://spec.openapis.org/oas/v3.0.2#fixed-fields-5

**Comment by WoH** [comment]
Interesting, so the `$ref` is not the issue, that'd be a legal reference to an illegal name.
I'd take a PR to change the naming, if we can make sure name clashes can still be avoided.
Maybe `-OR-` and `-AND-` would make sense.

**Comment by InsOpDe** [comment]
I think this fits to this issue as well:
When declaring an interface like so
```typesript
export interface IApiResTest {
	id: number
	name: string
}
export interface IApiReqCreateTest extends Omit<IApiResTest, "id"> {}
```
My schema ends up having this name:
```
Pick_IApiResTest.Exclude_keyofIApiResTest.%22id%22__
```
which triggers following error when using `openapi-generator`:
```bash
$ openapi-generator generate --input-spec swagger.yaml --generator-name typescript-axios --output gen/api-library --config api-config.json
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 1
Errors: 
        -attribute components.schemas.Schema name Pick_IApiResTest.Exclude_keyofIApiResTest.%22id%22__ doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
Warnings: 
        -attribute components.schemas.Schema name Pick_IApiResTest.Exclude_keyofIApiResTest.%22id%22__ doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:474)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:501)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:418)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
```

Possible solution is to use single quotation marks like so:
```
export interface IApiReqCreateTest extends Omit<IApiResTest, 'id'> {}
```
which results in
```
Pick_IApiResTest.Exclude_keyofIApiResTest.id__
```
which works fine.

**Comment by WoH** [comment]
@InsOpDe This should have been fixed in 3.0.3..3.0.5, see https://github.com/lukeautry/tsoa/commit/55687d7713a5c952d0b5790be763458d4fb3f34e

**Comment by InsOpDe** [comment]
@WoH I am at 3.0.5.
And I dont think this is a whitespace issue as the diff suggests.

I rather think that it has to do with the regex on line 475 ([commented it](https://github.com/lukeautry/tsoa/commit/55687d7713a5c952d0b5790be763458d4fb3f34e#r38668318))

**Comment by WoH** [comment]
I knew I tried to address double quotes, but I got the wrong commit. You're right, the regex is off.
