### ISSUE TITLE
"No matching module found" error when importing module as named

### ISSUE THREAD

**Issue by michaelbeaumont** [lukeautry/tsoa#651]
Using models through a named `import * as` causes route generation to fail, even if it's in an adjacent module
Now obviously there's docs for this error and #195 is related but it seems there the problem was "solved" by not using external dependencies. The docs always refers to `node_modules` and external dependencies though, making it unclear if this use case is supposed to be supported or not.

A workaround is simply to import the interface directly. 
My problem is really that I can't use the new TS 3.8 feature `export * as x` because when using `import { x }` in the Controller I have no way of further destructuring `x`.

Is this possible to solve for modules in the same project? If not, I'll add explicit reference that this case is also not supported.

## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
```
import * as access from "./types";
...
  public async post(@Body() body: AccessRequest): Promise<access.AccessResponse> {
```
compiles

## Current Behavior
Error:
```
Generate routes error.
 Error: No matching module declarations found for access.
```

## Possible Solution
If there's no interest in handling this, I'll update the docs.

## Context (Environment)
Version of the library: `2.5.13`
Version of NodeJS: `13`
* Confirm you were using yarn not npm: [x]

**Comment by calvinwyoung** [comment]
@michaelbeaumont did you ever find a solution to this issue? I'm experiencing the same problem and would love to use the `import * as` syntax if at all possible.

**Comment by michaelbeaumont** [comment]
@calvinwyoung Hi, sorry, no I didn't. I'm not working on the project that's using `tsoa` anymore. I believe I started writing code to handle this case though, I think it's possible, just not yet supported.

**Comment by calvinwyoung** [comment]
@michaelbeaumont Got it, makes sense. Thanks for the follow-up — really appreciate it.
