### ISSUE TITLE
feat: No matching module declarations found for Enum

### ISSUE THREAD

**Issue by Eywek** [lukeautry/tsoa#655]
I want to use `Enum.PROPERTY`

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
export enum EnumStringValue {
  EMPTY = '',
  VALUE_1 = 'VALUE_1',
  VALUE_2 = 'VALUE_2',
}

interface TestModel {
  enumStringProperty?: EnumStringValue.VALUE_1;
}
```

## Current Behavior

```
There was a problem resolving type of 'TestModel'.

~/tsoa/src/metadataGeneration/exceptions.ts:6
    super(message);
    ^
Error: No matching module declarations found for EnumStringValue.
    at new GenerateMetadataError (~/tsoa/src/metadataGeneration/exceptions.ts:6:5)
```

**Comment by WoH** [comment]
https://github.com/lukeautry/tsoa/pull/656 solves this, right?

**Comment by Eywek** [comment]
right
