### ISSUE TITLE
support for path-to-regex

### ISSUE THREAD

**Issue by amitgilad3** [lukeautry/tsoa#657]
i was wondering if tsoa supports path-to-regex on routes
for example:
  @Get('{id}')
  public async getUser(id: number, @Query() name: string): Promise<User> {
    return await new UserService().get(id);
  }

i would like id to be something like ":id([0-9]{6})" is this possible??

* **I'm submitting a ...**
  - [v] support request

* I confirm that I
  - [v] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

**Comment by WoH** [comment]
No, because the OpenAPI specification does not provide a way to correctly express this route currently.

**Comment by amitgilad3** [comment]
ok, thanks for the response. do you know of any solution i can use to overcome this problem ? maybe change the the route @WoH ?

**Comment by WoH** [comment]
Sure, you can split the routing logic from the validation logic. Catch the entire path in the method and validate the Path Parameter:

```ts
/**
 * @isInt id
 * @minimum id 0
 * @maximum id 999999
 */
@Get('{id}')
public async getUser(@Path() id: number, @Query() name: string): Promise {
  return await new UserService().get(id);
}
```
