### ISSUE TITLE
ValidateError should extend Error

### ISSUE THREAD

**Issue by aldenquimby** [lukeautry/tsoa#658]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
- `ValidateError` should extend `Error`

## Current Behavior
- `ValidateError` does not extend `Error`

As a result, tools like [Sentry](https://sentry.io/) do not fully work with `ValidateError`. Sentry makes a [synthetic exception](https://docs.sentry.io/platforms/node/#hints-for-events) and does not include it's full exception info, it only reports:
```
Non-Error exception captured with keys: fields, message, name, status
```

## Possible Solution
- update `ValidateError` to extend `Error`

## Steps to Reproduce
1. Generate an express server
2. Make an API request that triggers a validation error, for example: https://github.com/lukeautry/tsoa/blob/313012a1214f0afa95756cf23bbc13f46277499e/tests/integration/express-server.spec.ts#L463-L470
3. `ValidateError` should be thrown, and it should extend `Error`

## Context (Environment)
Version of the library: 2.5.13
Version of NodeJS: 10.16.3
* Confirm you were using yarn not npm - I use npm, not yarn

## Detailed Description
The simplest non-breaking change would be to update this line: https://github.com/lukeautry/tsoa/blob/533fe059cc8373e31e8ab6d7698c18ae3ea3b709/src/routeGeneration/templateHelpers.ts#L746
to this:
```ts
export class ValidateError extends Error implements Exception {
```

## Breaking change?
- Yes

**Comment by WoH** [comment]
I'd accept a PR on the `3.x` branch. 
There may be people out there that rely on the fact that ValidateError doesn't extend Error. I'd assume this is unlikely, but we know of people that i.e. relied on a Error message strings, so changing that broke their code. Would rather be overly cautious here.

**Comment by aldenquimby** [comment]
@WoH sounds good, thanks for the quick response! I'd be happy to put up a PR. What tests would you recommend here? Should I just check that `ValidateError extends Error` in a unit test here https://github.com/lukeautry/tsoa/blob/313012a1214f0afa95756cf23bbc13f46277499e/tests/unit/templating/templateHelpers.spec.ts ?

Here is how Sentry checks if something is an error, which seems overkill for tsoa: https://github.com/getsentry/sentry-javascript/blob/d32283d6cf0fae7923a7728957cede25ec5d5d51/packages/utils/src/is.ts#L8-L19

**Comment by aldenquimby** [comment]
Fix will go out with 3.x. Thank you for the support here @WoH !

**Comment by WoH** [comment]
Thank you for the PR!
This is already included in [the latest prerelease](https://github.com/lukeautry/tsoa/releases/tag/v3.0.5) if you want to try this.

**Comment by aldenquimby** [comment]
Re-opening because I notice some other issues in the 3.x release are still open after PRs have merged, so I may have jumped the gun.

@WoH what is the process for closing issues? Do you wait until a version has been published to npm?

**Comment by WoH** [comment]
I try to keep them open until they're included in a stable release.
