### ISSUE TITLE
@Inject not working in `tsoa swagger` generator

### ISSUE THREAD

**Issue by jonzee** [lukeautry/tsoa#66]
I installed `tsoa` about 4 days ago and I created some routes with injected parameters, but when I cloned my project today and run swagger there was an error `Error: Error generate parameter method: me argument: req Error: Parameter [object Object] doesn't have a valid type assigned.`, it's seems that there were some breaking changes in the last few days, but version number stayed the same.

**Comment by lukeautry** [comment]
Closing pending reply
