### ISSUE TITLE
Routes generation for Next.js API Routes

### ISSUE THREAD

**Issue by wgcrouch** [lukeautry/tsoa#660]
I was wondering it it would be possible to generate routes/pages for Next.js [API Routes](https://nextjs.org/docs/api-routes/introduction) feature. Not sure how to go about this. 
 
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [ x ] feature request
  - [ ] support request

* I confirm that I
  - [ x ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml

```

```ts

```

## Current Behavior

```yaml

```

```ts

```

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
Version of the library: 
Version of NodeJS: 
* Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
I saw an article that did something like this, maybe it helps:
- You can use [dynamic API routes](https://nextjs.org/docs/api-routes/dynamic-api-routes) to set up a catch-all route like this: `/api/[...catchAll].ts`

- define a handler in there: 
```ts
import { server } from "./path/to/tsoa/server";

export default (req: NextApiRequest, res: NextApiResponse) => new Promise(async resolve => {
  const [ requestHandler ] = server.listeners("request")
  requestHandler(req, res);
  res.on("finish", resolve);
})
```

I don't have any experience with Next, but their server seems to be at least based on express, so maybe making tsoa generate express routes may not be a bad idea,

**Comment by mr-bjerre** [comment]
Cool @ellis . I'm getting this error 

```
[next] Error: error: Unexpected token `@`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, ` for template literal, (, or an identifier
[next]   
[next]    |
[next] 14 | @Route("users")
```

Any idea why? Maybe some tsconfig?

**Comment by mr-bjerre** [comment]
I guess it's related to this: https://github.com/vercel/next.js/discussions/30174

**Comment by mr-bjerre** [comment]
It has just been fixed 1 hour ago in `next@npm:12.0.4-canary.11`. Simply set `experimentalDecorators` to true in `tsconfig.json` and you are good to go.

**Comment by mr-bjerre** [comment]
> @wgcrouch The following worked for me. Here's `pages/api/tsoa/[...catchall].ts`
> 
> ```ts
> import { RegisterRoutes } from ".../routes"; // Import the 'routes' file generated by tsoa
> import { NextApiRequest, NextApiResponse } from "next";
> 
> /** Function signature for route callbacks */
> type FN = (request: any, response: any, next: any) => void;
> 
> /** Map from method to path to the route handling callbacks */
> const methodToPathToFns: { readonly [method: string]: { [path: string]: readonly FN[] } } = {
> 	get: {},
> 	post: {},
> };
> 
> /** Indicate whether setup() has been called yet */
> let ready = false;
> 
> export default async function tsoa(req: NextApiRequest, res: NextApiResponse): Promise<void> {
> 	if (!ready) {
> 		setup();
> 		ready = true;
> 	}
> 
> 	const method = req.method?.toLowerCase();
> 	const path: string = "/" + ((req.query.catchall as readonly string[]) ?? []).join("/");
> 	const fns = method ? methodToPathToFns[method]?.[path] : undefined;
> 	// console.log("method:", method);
> 	// console.log("path:", path);
> 	// console.log("fn:", fns);
> 
> 	if (!fns) {
> 		res.status(401).send("Unknown path");
> 	} else if (fns.length === 0) {
> 		res.status(401).send("Unhandled path");
> 	} else {
> 		return new Promise((resolve, reject) => {
> 			let i = 0;
> 			const next = (err?: any) => {
> 				if (err) {
> 					reject(err);
> 				} else if (i < fns.length) {
> 					fns[i++](req, res, next);
> 				} else {
> 					resolve();
> 				}
> 			};
> 			next();
> 		});
> 	}
> }
> 
> /**
>  * Call the `RegisterRoutes()` function generated by tsoa.
>  * `RegisterRoutes()` expects to be passed an express app, so mock the required functions (e.g. get, post, etc)
>  * in order to record our own list of methods/paths/callbacks.
>  */
> function setup(): void {
> 	const app = {
> 		get: (path: string, ...fns: readonly FN[]) => {
> 			methodToPathToFns["get"][path] = fns;
> 		},
> 		post: (path: string, ...fns: readonly FN[]) => {
> 			methodToPathToFns["post"][path] = fns;
> 		},
> 	};
> 	RegisterRoutes(app as any);
> 	// console.log("methodToPathToFns:", methodToPathToFns);
> }
> ```
> 
> Additionally, I wanted to use the (next-auth)[https://next-auth.js.org/getting-started/introduction] JWT tokens with (tsoa authentication)[https://tsoa-community.github.io/docs/authentication.html], so I integrated an `authentication.ts` file similar to this:
> 
> ```ts
> import * as express from "express";
> import { getToken } from "next-auth/jwt";
> 
> export async function expressAuthentication(
> 	request: express.Request,
> 	securityName: string,
> 	scopes?: string[]
> ): Promise<any> {
> 	if (securityName === "jwt") {
> 		const jwtSecret = process.env.JWT_SECRET;
> 		if (!jwtSecret) {
> 			throw Error("Missing JWT variables");
> 		}
> 		const cookies = getReqCookies(request);
> 		const req = { ...request, cookies };
> 		const token = await getToken({ req: req as any, secret: jwtSecret });
> 		// console.log("JSON Web Token", token);
> 		
> 		// Test scopes
> 		// ...
> 		return token;
> 	}
> }
> 
> /** returns an object with the cookies' name as keys */
> function getReqCookies(req: express.Request): Record<string, string> {
> 	return Object.fromEntries(req.headers.cookie?.split("; ").map((s) => s.split("=")) ?? []);
> }
> ```

@ellis have you managed to handle dynamic routes as well? That's not working with that example?

**Comment by mr-bjerre** [comment]
The following _almost_ does the job.

```typescript
import { RegisterRoutes } from "@tsoa/routes"; // Import the 'routes' file generated by tsoa
import { NextApiRequest, NextApiResponse } from "next";

/** Function signature for route callbacks */
type FN = (request: any, response: any, next: any) => void;

type PathsToFns = { [path: string]: readonly FN[] };

/** Map from method to path to the route handling callbacks */
const methodToPathToFns: {
  readonly [method: string]: PathsToFns;
} = {
  get: {},
  post: {},
};

function isMatch(req: NextApiRequest, path: string, params: string[]): boolean {
  const candidate = path.slice(1).split("/");
  if (candidate.length !== params.length) return false;
  for (let index = 0; index < params.length; index++) {
    if (
      !(candidate[index].startsWith(":") || candidate[index] === params[index])
    )
      return false;
  }

  // it was a match so now we add params
  for (let index = 0; index < params.length; index++) {
    if (candidate[index].startsWith(":"))
      // @ts-expect-error we are adding params
      // TODO: cast to correct type but can't know how to
      req.params = { [candidate[index].slice(1)]: params[index] };
  }
  return true;
}

function getFunctions(req: NextApiRequest): readonly FN[] {
  const method = req.method?.toLowerCase();
  const params = req.query.catchall;
  if (!Array.isArray(params)) throw new Error(`params not an array: ${params}`);
  if (!method) throw new Error(`method not defined: ${method}`);

  const pathsToFns: PathsToFns = methodToPathToFns[method] || {};
  for (const path of Object.keys(pathsToFns)) {
    if (isMatch(req, path, params)) {
      return pathsToFns[path];
    }
  }
  return [];
}

/** Indicate whether setup() has been called yet */
let ready = false;

export default async function tsoa(
  req: NextApiRequest,
  res: NextApiResponse
): Promise<void> {
  if (!ready) {
    setup();
    ready = true;
  }

  const fns = getFunctions(req);

  if (!fns) {
    res.status(401).send("Unknown path");
  } else if (fns.length === 0) {
    res.status(401).send("Unhandled path");
  } else {
    return new Promise((resolve, reject) => {
      let i = 0;
      const next = (err?: any) => {
        if (err) {
          reject(err);
        } else if (i < fns.length) {
          fns[i++](req, res, next);
        } else {
          resolve();
        }
      };
      next();
    });
  }
}

/**
 * Call the `RegisterRoutes()` function generated by tsoa.
 * `RegisterRoutes()` expects to be passed an express app, so mock the required functions (e.g. get, post, etc)
 * in order to record our own list of methods/paths/callbacks.
 */
function setup(): void {
  const app = {
    get: (path: string, ...fns: readonly FN[]) => {
      methodToPathToFns["get"][path] = fns;
    },
    post: (path: string, ...fns: readonly FN[]) => {
      methodToPathToFns["post"][path] = fns;
    },
  };
  RegisterRoutes(app as any);
  // console.log("methodToPathToFns:", methodToPathToFns);
}
```

There's an issue with non-string parameters though. They need to be casted to the correct type but the type definition is only available inside the `FN[]` and we need to cast the params before that.

**Comment by MartinN3** [comment]
Another aproach you can take to make use of TSOA in Next.js - which is i would say **not at all what you wanted**, but just approach to get TSOA and next more cowork. 

Next.js allows you to create custom server so you dont have to use /api/[...routes.ts]. There are certainly downsides for replacing default next server and it is not recommended but for my usecase, it turned out to be really clean solution.

**Comment by Jamadan** [comment]
> @wgcrouch The following worked for me. Here's `pages/api/tsoa/[...catchall].ts`
> 
> ```ts
> import { RegisterRoutes } from ".../routes"; // Import the 'routes' file generated by tsoa
> import { NextApiRequest, NextApiResponse } from "next";
> 
> /** Function signature for route callbacks */
> type FN = (request: any, response: any, next: any) => void;
> 
> /** Map from method to path to the route handling callbacks */
> const methodToPathToFns: { readonly [method: string]: { [path: string]: readonly FN[] } } = {
> 	get: {},
> 	post: {},
> };
> 
> /** Indicate whether setup() has been called yet */
> let ready = false;
> 
> export default async function tsoa(req: NextApiRequest, res: NextApiResponse): Promise<void> {
> 	if (!ready) {
> 		setup();
> 		ready = true;
> 	}
> 
> 	const method = req.method?.toLowerCase();
> 	const path: string = "/" + ((req.query.catchall as readonly string[]) ?? []).join("/");
> 	const fns = method ? methodToPathToFns[method]?.[path] : undefined;
> 	// console.log("method:", method);
> 	// console.log("path:", path);
> 	// console.log("fn:", fns);
> 
> 	if (!fns) {
> 		res.status(401).send("Unknown path");
> 	} else if (fns.length === 0) {
> 		res.status(401).send("Unhandled path");
> 	} else {
> 		return new Promise((resolve, reject) => {
> 			let i = 0;
> 			const next = (err?: any) => {
> 				if (err) {
> 					reject(err);
> 				} else if (i < fns.length) {
> 					fns[i++](req, res, next);
> 				} else {
> 					resolve();
> 				}
> 			};
> 			next();
> 		});
> 	}
> }
> 
> /**
>  * Call the `RegisterRoutes()` function generated by tsoa.
>  * `RegisterRoutes()` expects to be passed an express app, so mock the required functions (e.g. get, post, etc)
>  * in order to record our own list of methods/paths/callbacks.
>  */
> function setup(): void {
> 	const app = {
> 		get: (path: string, ...fns: readonly FN[]) => {
> 			methodToPathToFns["get"][path] = fns;
> 		},
> 		post: (path: string, ...fns: readonly FN[]) => {
> 			methodToPathToFns["post"][path] = fns;
> 		},
> 	};
> 	RegisterRoutes(app as any);
> 	// console.log("methodToPathToFns:", methodToPathToFns);
> }
> ```
> 
> Additionally, I wanted to use the (next-auth)[https://next-auth.js.org/getting-started/introduction] JWT tokens with (tsoa authentication)[https://tsoa-community.github.io/docs/authentication.html], so I integrated an `authentication.ts` file similar to this:
> 
> ```ts
> import * as express from "express";
> import { getToken } from "next-auth/jwt";
> 
> export async function expressAuthentication(
> 	request: express.Request,
> 	securityName: string,
> 	scopes?: string[]
> ): Promise<any> {
> 	if (securityName === "jwt") {
> 		const jwtSecret = process.env.JWT_SECRET;
> 		if (!jwtSecret) {
> 			throw Error("Missing JWT variables");
> 		}
> 		const cookies = getReqCookies(request);
> 		const req = { ...request, cookies };
> 		const token = await getToken({ req: req as any, secret: jwtSecret });
> 		// console.log("JSON Web Token", token);
> 		
> 		// Test scopes
> 		// ...
> 		return token;
> 	}
> }
> 
> /** returns an object with the cookies' name as keys */
> function getReqCookies(req: express.Request): Record<string, string> {
> 	return Object.fromEntries(req.headers.cookie?.split("; ").map((s) => s.split("=")) ?? []);
> }
> ```

Could you point me to an example project where this is working? Struggling to get it going on a boilerplate next app, would like to see it in action, see where I've gone wrong. Please and thankyou

**Comment by ellis** [comment]
> @ellis Could you point me to an example project where this is working? Struggling to get it going on a boilerplate next app, would like to see it in action, see where I've gone wrong. Please and thankyou

@Jamadan I haven't worked with this in a really long time, so I can't be of any help.  Recently, I've been using trpc, which has good documentation about the integration with nextjs.

**Comment by Jamadan** [comment]
> > @ellis Could you point me to an example project where this is working? Struggling to get it going on a boilerplate next app, would like to see it in action, see where I've gone wrong. Please and thankyou
> 
> @Jamadan I haven't worked with this in a really long time, so I can't be of any help.  Recently, I've been using trpc, which has good documentation about the integration with nextjs.

Nice one thanks. Will give it a look
