### ISSUE TITLE
Add decorator to specify Anonymous access to a controller method

### ISSUE THREAD

**Issue by picturelink** [lukeautry/tsoa#665]
If the `@Security` decorator is used on a controller class, there appears to be no way to override that setting for a specify method. It would be useful if there was an `@AllowAnonymous` decorator that we could use to override the security for a specific method - much like the [AllowAnonymousAttribute  in .net Core](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.allowanonymousattribute?view=aspnetcore-3.1)

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
``` ts
@Route("Foo")
@Security("BearerAuth")
export class FooController extends Controller {
  // This method implicitly has security applied to it
  @Get("foo")
  public foo() {}

  // This method implicitly has security applied to it
  @Get("bar")
  public bar() {}

  // This method is explicitly open
  @Get("baz")
  @AllowAnonymous()
  public baz() {}
}
```
## Current Behavior
``` ts
// This controller has no default security
@Route("Foo")
export class FooController extends Controller {
  // This method explicitly has security applied to it
  @Get("foo")
  @Security("BearerAuth")
  public foo() {}

  // This method explicitly has security applied to it
  @Get("bar")
  @Security("BearerAuth")
  public bar() {}

  // This method is implicitly open
  @Get("baz")
  public baz() {}
}
```
## Possible Solution
Add an `@AllowAnonymous` decorator.

## Context (Environment)
Version of the library:  3.0.4
Version of NodeJS: 10.19.0
* Confirm you were using yarn not npm: [x]

## Detailed Description
The current method involves removing the `@Security` decorator from the class and applying it to every method, except the anonymous method. This is undesirable as it an omission will default to insecure. It's also cleaner as fewer decorators are required.

## Breaking change?
No

**Comment by WoH** [comment]
I'd like to find a better name, maybe `@AllowUnauthorized()` or `@NoSecurity()`, but the idea seems good.

**Comment by dimitor115** [comment]
@WoH I would like to add it 😄

**Comment by picturelink** [comment]
I've created a PR  - #684 - that **might** fix this (be gentle, I'm new to this project!). It has no unit tests nor any documentation at the moment, but I'd like to get the opinion of the maintainers before I go all out...

**Comment by WoH** [comment]
> I've created a PR - #684 - that **might** fix this (be gentle, I'm new to this project!). It has no unit tests nor any documentation at the moment, but I'd like to get the opinion of the maintainers before I go all out...

Don't worry, especially because the PR looks great so far :+1: 
I haven't had time to look at the details, but the approach looks good to me!

**Comment by picturelink** [comment]
Wow, that was quicker than I expected. Thanks.

**Comment by kendallroth** [comment]
I just spent approximately 3 hours trying to debug why `@NoSecurity` operator wasn't being applied, crunching through source code and generated code alike, but to no avail... I was confounded why the Swagger docs were working as expected with the `@NoSecurity` decorator, but the API kept catching and failing... Finally, ages later, I finally logged the actual `request.route` in my authentication module...`only to discover that the non-security route (`/todos/stats`) was being registered **after** a similar security route with a regex path (`/todo/:id`)... 😱. Incredibly obvious in hindsight, and something I should have caught _ages_ before, but I was so fixiated on assuming there was an issue here that I missed the blindingly obvious signs 🤦.

TL;RD: Can verify that `@NoSecurity` does indeed work, and is a very welcome feature!
