### ISSUE TITLE
typescript union should be implemented as anyOf

### ISSUE THREAD

**Issue by fantapop** [lukeautry/tsoa#671]
Digging through the openapi docs, I ran across this:

https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#anyof-vs-oneof

It seems that `oneOf` is an exclusive OR.  I believe the correct thing to use for unions is `anyOf`.  

## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Context (Environment)
Version of the library: 3.0.5
Version of NodeJS: 12.12
* Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
There is no perfect equivalent, but here is why oneOf was chosen:
```ts
type U = { value1: string } | {value2: string};
```

If you try to assign `{value1: "", value2: ""}`, TS will complain and so will tsoa if you throw on additional Properties.

**Comment by fantapop** [comment]
I wasn't aware of this until doing some tests just now, but this is actually valid.  There's no errors here.

```typescript
type U = { value1: string } | {value2: string};
const v: U = {value1: "it", value2: "works"};
console.log(v);
```

There's some info about it here:
https://devblogs.microsoft.com/typescript/announcing-typescript-3-5-rc/#improved-excess-property-checks-in-union-types

Is TSOA validating this as a disjointed union?

Before learning that typescript is loose with its unions, my concern with oneOf was about overlapping types.  These are somewhat contrived examples but I think easier to reason about than an example with objects.

```typescript
type Five = 5;
type FiveOrNumber = Five | number;
```

this would get sent over the wire something like:
```yaml
FiveOrNumber:
  oneOf:
    - $ref: '#/components/schemas/Five'
    - type: number
```

According to the open api docs this type should match any number except for 5 because in the case of 5 it will match both the type number and the type Five.  In the typescript version that was written in tsoa it will match any number including the number 5.

Here's a similar one with objects:

```typescript
interface Cat {
  name: string;
  type?: CatBreed;
}
interface Dog {
  name: string;
  type?: DogBreed;
}
type Pet = Cat | Dog;
```

If someone passed in the following valid request:
```json
{
  "name": "bubbles"
}
```
using a `oneOf` should deny the request because it matches both Cat and Dog
use an `anyOf` should allow the request because it matched one or more.

I don't know if this is how you think about TSOA, but to me, an ideal case is that typescript is created in TSOA, then converted to openapi, then if a typescript client is generated from the spec, its as close as possible to the original.   I realize that getting this perfect will never occur partially because of the expressiveness of the language but also due to ambiguities in how things are implemented.

**Comment by WoH** [comment]
Please read the discussion we already had.
https://github.com/lukeautry/tsoa/pull/400
If you have additional concerns, feel free to bring them up.

**Comment by fantapop** [comment]
Is this the comment you’re referring to?

https://github.com/lukeautry/tsoa/pull/400#discussion_r314961781

There is a typo in the example  @dgreene1 included as justification. Notice
that the validation is failing because `value` is not a member of either of
the types.  It should be `value2` in that example.

**Comment by WoH** [comment]
> There is a typo in the example  @dgreene1 included as justification. Notice
that the validation is failing because`value` is not a member of either of the types.  It should be `value2` in that example.

I didn't even notice that, oops.
Certainly would've tried pushing for `anyOf` in that case. I'd be curious to see what the other codegens are doing. Classifying this as a bug then.

**Comment by WoH** [comment]
I'll have to think about the validation implications of this, but maybe we can live without changes for now. If you allow excess props you're already ok, if you wanna throw on excess props I'd assume you want to have the excess prop validation to be as strict as possible and now allow mixed schemas.

**Comment by fantapop** [comment]
I found this open issue. If you read through, there’s clearly a lot of issues implementing this in many languages. Notably this comment sums it up 

https://github.com/OpenAPITools/openapi-generator/issues/15#issuecomment-540003621

I’m curious to see where all this ends up. I personally feel like the spec is pretty explicit about oneOf only allowing one and only one match. This is a useful construct For matching parameter objects of different types. I’m surprised typescript doesn’t have better first class support for this.

**Comment by fantapop** [comment]
here is a post I found informative on the subject. They even call the final product they end up with `OneOf`

https://timhwang21.gitbook.io/index/programming/typescript/xor-type

**Comment by derolf** [comment]
AllOf: That’s just wrong.

**Comment by WoH** [comment]
> AllOf: That’s just wrong.

That's what I thought. But I'm sure once you read this discussion and the referenced threads, you'll understand how TypeScript handles union types by default and the implied complexity of oneOf validation without discriminators you seem to be suggesting. But be careful, you may eventually end up changing your preference (like me)  and start leaning towards modeling TS Unions as anyOf, or at least be able to provide a nuanced opinion (one which would model as oneOf in certain circumstances). Good luck until then @derolf 🍀

**Comment by derolf** [comment]
@WoH , what I actually did was dropping TSOA and using https://github.com/Eywek/typoa . Works like a charm!

**Comment by WoH** [comment]
I'm sure there are no security holes and spec violations in there at all!

**Comment by derolf** [comment]
Btw. how do you model 'type AorB = { a: number, b: string } | { a: string }` in TSOA?

**Comment by derolf** [comment]
Btw. reading through the thread: The alternative solution of turning a type union in a weird allOf, would have been to make TSOA bark if it finds a "type union" that would create a problem with oneOf.

Just imagine how a codegen would turn that allOf back into code.

It would turn `A | B` -> allOf -> `Partial<A> & Partial<B>`, which is completely wrong.

**Comment by fantapop** [comment]
@derolf Are you talking about `allOf` or `anyOf`?  I thought `allOf` was the least contentious of them.

from open api spec [here](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/): `allOf – validates the value against all the subschemas` 

In TSOA intersection is converted to `allOf` not union. See [here ](https://github.com/lukeautry/tsoa/blob/7c05b4d3f67c313752d38e0efc6826f64b4f27fe/packages/cli/src/swagger/specGenerator3.ts#L626)

**Comment by derolf** [comment]
What about a compromise?

Usually, when one uses a union, the rational is most of the time indeed to model some xor-kind of relationship.

If TSOA detects “conflicting” properties that rule out that two subtypes can coexist, it could generate oneOfs.

**Comment by fantapop** [comment]
@derolf Can you give an example of the type and what you're hoping the outcome of the TSOA transformation would be?  The code that transforms unions has a number of different cases depending on how many there are and whether they're nullable or not.  It's somewhat complex.  Another ideal is that the generated output can then be run through the OpenAPI codegen process to regenerate the same or functionaly equivalent code.   This is not always possible currently but hopefully it should get better as Open API and typescript become more expressive.
