### ISSUE TITLE
Support client code generation?

### ISSUE THREAD

**Issue by ivan-shaban** [lukeautry/tsoa#683]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

- I expect that some client services will be generated, that aware of how to work with server.

## Detailed Description

- Are there any plans to generate also client code to work with server? 
- How it is adheres to the goals and philosophy of the project?

**Comment by WoH** [comment]
Hi, client code generation is not what this framework will help you do.
However, the OpenAPI Specification generated by tsoa is the key to an entire ecosystem of tooling.
As a general overview, I can recommend [**OpenAPI.tools**](https://openapi.tools/#sdk).
There you will find an entire list of tools that can help you generate code for clients in pretty much any language your client could be written in (and also [create documentation](https://tsoa-community.github.io/docs/live-reloading.html#supercharging-our-developer-experience-with-swaggerui)).
I have heard from other users that they use [OpenAPI Generator](https://openapi-generator.tech/) specifically and whenever there were issues, we tried to address them.

**Comment by ivan-shaban** [comment]
Thank you for feedback, i'll close this issue and maybe latter update it with some practice information regarding what you said, for futute users.
