### ISSUE TITLE
Error: Unknown type: TupleType

### ISSUE THREAD

**Issue by williamdes** [lukeautry/tsoa#685]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
```
No error.
```

HACK:
```ts
TAGS: string[],
```

## Current Behavior

```
Generate swagger error.
 Error: Unknown type: TupleType
At: company.model.ts:27:27.
This was caused by 'TAGS: [string];'
```

```ts
TAGS: [string],
```

## Steps to Reproduce

Create an interface with:
```ts
TAGS: [string],
```
As a response object.

## Context (Environment)

Version of the library: 3.0.8
Version of NodeJS: 10

- Confirm you were using yarn not npm: [x] :laughing: 

## Detailed Description

This interface is not detected correctly.

**Comment by williamdes** [comment]
`Error: Unknown type: TupleType` is also triggered by 
```ts
categories: [
        {
            catName: string;
        }
    ];
```

**Comment by WoH** [comment]
We can't type tuples in OpenAPI yet, so this is intended.
See https://github.com/lukeautry/tsoa/issues/242

**Comment by williamdes** [comment]
Could a link be added to the error so users know it is not an error but a missing feature ?

**Comment by WoH** [comment]
Sure, feel free to submit a PR!
