### ISSUE TITLE
Error: No matching module declarations found for express.

### ISSUE THREAD

**Issue by williamdes** [lukeautry/tsoa#688]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Build my spec.

## Current Behavior

```
Error: No matching module declarations found for express.
```

## Steps to Reproduce

```ts
    @Get('/local')
    private local(@Request() req: express.Request, res: express.Response): void {
    }
```

**This works:**

```ts
    @Get('/local')
    private local(@Request() req: express.Request): void {
    }
```

## Context (Environment)

Version of the library: 3.0.8
Version of NodeJS: 10

- Confirm you were using yarn not npm: [x] :laughing: 

## Detailed Description

Build my spec.

**Comment by williamdes** [comment]
for now I use `req.res.` to handle my response, how can I have it as a parameter ?

**Comment by endor** [comment]
Out of curiosity, what are you using the response for?

**Comment by williamdes** [comment]
Infact I am migrating a codebase using `(req, res, next)` to TSOA and I would prefer to do 2 passes:
- add TSOA with minimal modification
- consider using TSOA fully

So I use it like any normal express responses. As the express docs shows us to make requests.

If I am convinced that I can use TSOA without having to refactor all my routes to Promises I will start using the tool everywhere.

**Comment by endor** [comment]
I am not sure if tsoa supports this. You might be able to inject the `response` if you use a custom routes template. How do you document the response, if not by returning a typed Promise? Do you use `@Response()`?

I've recently converted an older codebase to TSOA. I did it controller by controller though, to see how much effort it would be. After seeing that it was actually quite quick to turn the old endpoint functions into Promise-returning tsoa style functions, I just migrated all of them. 🤷‍♂️

**Comment by williamdes** [comment]
I use `@Response` because I discovered that `Promise` was not needed to make it work.
Actually I want to have TSOA > openapi generator and build E2E tests to cover the existing code so I am forced to make minimal changes in order to not break everything before adding total coverage..

And yeah I will need to make Controllers but the diff is pretty readable ;)

The response is available as `req.res.`.
I can add `const response = req.res;` on each function to make it run.

**Comment by WoH** [comment]
`@Response` is **not** used to get acces to Res! It's an Annotation used to describe Responses. Working as intended imo.

**Comment by WoH** [comment]
a) Using **untyped** res to hack together responses that can diverge from the produced OpenAPI spec is something you can do with `req.res` if you really want to do something (99.5% of the time) stupid

b) Here's my suggestion how we might want to  handle this properly: https://github.com/lukeautry/tsoa/issues/617

> Error: No matching module declarations found for express.
Have you excluded express / node_modules from your tsconfig? If so, that's why.

**Comment by williamdes** [comment]
> Have you excluded express / node_modules from your tsconfig? If so, that's why.

Nope

> a) Using untyped res to hack together responses that can diverge from the produced OpenAPI spec is something you can do with req.res if you really want to do something (99.5% of the time) contrary to what you want to use tsoa for.

I agree, this is like using `@OA` php doc blocks, they can diverge.

> @Response is used to indicate responses generated from throwing Errors, has nothing to do with res in Express.

It also works fine for normal responses, and yes they can diverge.

![image](https://user-images.githubusercontent.com/7784660/81302266-6dc10e80-907a-11ea-972a-6fdb982d87dd.png)

**Comment by williamdes** [comment]
I did not find any tool that could be as good to make my documentations.
Sure I could go full textual, but no.

TSOA fits my needs quite good for now, except this stupid error.

Infact one of my issues is using Promises. I do not want to do this on all routes.

I hope It is okay ;)

**Comment by WoH** [comment]
> Infact one of my issues is using Promises. I do not want to do this on all routes.

Can you elaborate what issues you're facing? Using Promises should not be a requirement for tsoa's controller method.

**Comment by williamdes** [comment]
> > Infact one of my issues is using Promises. I do not want to do this on all routes.
> 
> Can you elaborate? Using Promises should not be a requirement for tsoa's controller method.

Yes, as I said I am moving some old code to controllers witch is a very big task without any changes.

And I want to have a swagger based on interfaces I wrote and force returned objects to follow the interface.
It will take me ages to migrate everything to Promises and this is why I do not want to have promises for now.

If I did want to write some documentation not using typescript I would want to use https://apidocjs.com/ for example.
As I said this project convinces me except forcing me to refactor all my method to use it

**Comment by williamdes** [comment]
Another of my point of views is: add it and remove it simply without needing a refactor to add the tool and another one to remove the tool.

**Comment by WoH** [comment]
> It will take me ages to migrate everything to Promises and this is why I do not want to have promises for now.

You should be able to just declare a controller method that doesn't return a promise though, right?

**Comment by williamdes** [comment]
> > It will take me ages to migrate everything to Promises and this is why I do not want to have promises for now.
> 
> You should be able to just declare a controller method that doesn't return a promise though, right?

Right it is possible, but I want to be able to use my existing parameters ;) `(req: express.Request, res: express.Response)`

**Comment by WoH** [comment]
Idk what to tell you. tsoa is focused on providing validation, which won't work if you pull stuff off the request directly. tsoa is heavily built around the idea of well designed, complete, accurate response docs, which you're actively trying to fight in order to keep awful API express provides out of the box.

I'd love to have a magic bullet here, but bare express applications are incompatible with tsoa's philosophy of providing a good API on top of these bare metal frameworks. Express is great if you want to quickly prototype but you can't efficiently build complete APIs without additional abstractions or bending over backwards and some mental gymnastics on top.

**Comment by williamdes** [comment]
@WoH I understand your point of view.
I will try to build a tool more flexible and let you know how I managed (or not) to make things safe :)

WIP: https://github.com/wdes/typescript-openapi-builder

I had a lot of hopes about using TSOA
It does not fit very well my point of view and the projects I intend to migrate and document.

So I will share my feedback and maybe rollback on some points afterwards ;)

Thank you for the support anyway !:)

**Comment by williamdes** [comment]
My builder seems to work and slowly I will implement all the spec using the typescript compiler.
