### ISSUE TITLE
Since tslint is deprecated, should we switch to eslint?

### ISSUE THREAD

**Issue by endor** [lukeautry/tsoa#689]

**Comment by WoH** [comment]
Tried it, it's a nightmare and it produces too much churn. (Given the automated migration tool)
Unless someone is committed to actually reproducing the tslint rules more or less 1:1, it's not worth it and I cba to invest more than an hour to configure eslint.
But if someone has the time, sure.

**Comment by spaguette** [comment]
We might try using the tool made by the `typescript-eslint` specifically for this case. I don't know if it can reproduce the current tslint rules of TSOA more or less 1:1 but leaving it here just as a suggestion
https://github.com/typescript-eslint/tslint-to-eslint-config

**Comment by dimabory** [comment]
@WoH I spent a little bit more than 1 hour in order to replace `tslint` with `eslint` having as many same rules as possible. Please check out a recently opened #780
