### ISSUE TITLE
Add conventional commits flow.

### ISSUE THREAD

**Issue by ivan-shaban** [lukeautry/tsoa#694]
As i see, you intend to split project and use lerna to manager subprojects. What do you think about [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) practice?

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

Simplest case that i see, that every merged PR may trigger properly version update and publishing. Also it assumes that commit process will became more strict.

**Comment by WoH** [comment]
I'm down but I'd be worried about other committers. Maybe we don't require it but agree to change the title before merging
