### ISSUE TITLE
Provide custom validation message for string pattern match

### ISSUE THREAD

**Issue by fantapop** [lukeautry/tsoa#695]
The pattern capabilities of string type have been very useful but providing an understandable error message to a user in this circumstance is difficult.  What I find myself doing is catching the tsoa generated error which includes the matched regex and then transforming it some more english like.  It would be great if there was a decorator that could be added where @pattern is added to override the default message.

## Sorting

- **I'm submitting a ...**
  - [x] feature request
- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

This could look something like:
```ts
/**
 * A V4 UUID
 * @errorMessage string not recognized as a valid UUID
 * @pattern ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ABab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
 */
export type Uuid = string
```

I'm not sure if there's an issue adding an unsupported annotion here or if there is a better way? 

## Context (Environment)

Version of the library: 3.0.2
Version of NodeJS: 12.10.0

- Confirm you were using yarn not npm: [x]

## Breaking change?

no

**Comment by WoH** [comment]
Does `@pattern <pattern> rejectionMsg` not work?
See [here](https://tsoa-community.github.io/docs/annotations.html#json-schema-tsoa-keyword-annotations)

**Comment by fantapop** [comment]
It works!  Thank you.
