### ISSUE TITLE
Add Support for Vendor Extensions

### ISSUE THREAD

**Issue by molinab297-unisys** [lukeautry/tsoa#696]
OpenAPI supports [vendor extensions ](https://swagger.io/docs/specification/openapi-extensions/). It would be very useful for Tsoa to add support for this so that developers can easily add properties to their spec files that aren't covered by the standard OpenAPI Specification.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```javascript
  @Extension({
    cmdlet: "Get-Endpoint",
    rolesAllowed: [
      "Administrator",
      "Audit Administrator"
    ],
    since: "1.0"
  })
  @Get()
  getEndpoints() {
    . . .
  }
```

would generate the following in the swagger/openapi spec file:

```json
"paths" : {
    "/endpoint" : {
      "get" : {
        "x-cmdlet" : "Get-Endpoint",
        "x-rolesAllowed" : [ "Administrator", "Audit Administrator"],
        "x-since" : "1.0"
      }
    }
 }
```

Note that in this example, other decorators (and properties in the spec file) were omitted for brevity.

## Current Behavior

Currently there is no way to provide vendor extensions. I suppose one might be able to use the spec merging feature to accomplish this, but you lose the benefit of being able to do this programmatically within your TypeScript source code.

## Possible Solution

My team originally forked this project to make these changes, but essentially a new Extension decorator was added to *src/decorators*, the *src/metadataGeneration/methodGenerator* was extended to look for the new Extension decorator, and the buildMethod() method in *src/swagger/specGenerator3* was extended to extract the values from the decorator and insert them into the spec file.   

## Context (Environment)

Version of the library: 3.0.8
Version of NodeJS: 12.16.1

- Confirm you were using yarn not npm: [x]

## Detailed Description

My team has a need to insert extra properties on our paths that aren't covered by the official OpenAPI spec. Other swagger/openapi libraries that we've used in other languages usually provide an *@extension* annotation for doing this. Our proposal is to add a new Extension decorator that accepts an object (of type Record<string, any>) which contains any extra properties that need to be inserted into the generated route.

## Breaking change?

No

**Comment by WoH** [comment]
There used to be a PR to add this which was abandoned afaik: https://github.com/lukeautry/tsoa/pull/347

Would be nice if someone could pick that back up

**Comment by molinab297-unisys** [comment]
@WoH Yes it looks like this is a duplicate of #294, I just didn't notice it because they referred to them as special attributes instead of *vendor extensions* :-). Okay maybe I'll take a look at #347 and consider completing that instead. Thank you.
