### ISSUE TITLE
Multiple matching models found for referenced type Omit

### ISSUE THREAD

**Issue by simllll** [lukeautry/tsoa#698]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

There are some similar issues, but I couldn't find a solution so far. I was working with tsoa 3 already successfully, but now the following error appears and I cannot quite figure out why:
```
Error: Multiple matching models found for referenced type Omit; please make model names unique. Conflicts found: "/home/simon/Dev/hokify/hokify-server/node_modules/@elastic/elasticsearch/lib/Helpers.d.ts"; "/home/simon/Dev/hokify/hokify-server/node_modules/@types/mongodb/index.d.ts"; "/home/simon/Dev/hokify/hokify-server/node_modules/@types/lodash/ts3.1/common/common.d.ts".
    at new GenerateMetadataError (/home/simon/Dev/hokify/hokify-server/node_modules/tsoa/dist/metadataGeneration/exceptions.js:22:28)
    at TypeResolver.getModelTypeDeclaration (/home/simon/Dev/hokify/hokify-server/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:675:19)
    at TypeResolver.typeArgumentsToContext (/home/simon/Dev/hokify/hokify-server/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:775:32)
    at /home/simon/Dev/hokify/hokify-server/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:814:38
    at Array.forEach (<anonymous>)
    at /home/simon/Dev/hokify/hokify-server/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:811:26
    at Array.forEach (<anonymous>)
    at TypeResolver.getModelInheritedProperties (/home/simon/Dev/hokify/hokify-server/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:807:25)
    at TypeResolver.getModelReference (/home/simon/Dev/hokify/hokify-server/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:515:40)
    at TypeResolver.getReferenceType (/home/simon/Dev/hokify/hokify-server/node_modules/tsoa/dist/metadataGeneration/typeResolver.js:477:38)
```

As far as I know tsoa usually does not lookup type defs in node_modules? Did this change somehow? 

Could it be related to typescript 3.9? Unfortunately downgrading isn't so easy right now to verify this.

## Possible Solution

* Ignore node_modules again?
* Specify some "build in" types to be ignored from "outter" re-definitions? I guess these definitions are only there due to backwards compatibility to older typescript versions.

## Context (Environment)

Version of the library: tested with tsoa 3.0.8 and master
Version of NodeJS: 12.16.1
Typescript Version: 3.9.2

**Comment by simllll** [comment]
I tried to narrow it down, but I couldn't figure it out.
Downgraded typescript: no difference
Downgraded tsoa: no difference

Somehow my environment suddenly included more "Omit"-definitions. I also check the dependent libraries (like mongodb https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongodb/index.d.ts#L46), it's not that they added this recently, it's in there for a while already.

Anyway, as a workaround I defined my own "Omit" type now:
`type MyOmit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;`
and use this type for now, feels pretty much as a hack though ;)

**Comment by WoH** [comment]
I assume you started to expose/use `Omit` and tsoa now tries to resolve it.
As the error message says, there are several declarations and we can't decide which one to use.
Maybe redefine the one you want to use and mark it as `@tsoaModel`

**Comment by simllll** [comment]
Thanks for your answer, in general I understand why tsoa wouldn't be able to determine the type. I'm using @tsoaModel from time to time for some other edge cases. But for "Omit" I don't see the reason behind this, it's an internal type, and all other types are not exported anyway. I'm using Omit, but why does tsoa even see the other types inside of node_modules?

**Comment by WoH** [comment]
Because they are part of your program as specified by your tsconfig.

**Comment by simllll** [comment]
Alright, thanks for the input. Makes kinda sense, even though I'm not aware what I've changed that this error "suddenly" popped up. My git changelog states that "Omit" in this code part hasn't been touched for over 2 months... super strange, but as long as I know how to workaround, it works for me ;)

Thanks again, closing this now

**Comment by lucasrcosta** [comment]
A workaround for this is to create an `Omit` interface somewhere it doesn't conflict and specify it as a "fake model". Then the other references can pass by.
```
/**
 * @tsoaModel
 */
export interface Omit {}
```
Ref: https://tsoa-community.github.io/docs/faq.html#dealing-with-duplicate-model-names

**Comment by dbryar** [comment]
I know this is closed, but for some reason nothing in this or #79 was fixing the errors in building with multiple matching definitions of basic TypeScript elements like `Omit`.

Instead of ignoring the entire code base for node_modules, requiring locally typed interfaces, try just ignoring the `@type` libraries as they seem to double up on a lot of basic type declarations. This works for me, without losing the dependency types present in TypeScript native libraries 

In `tsoa.json`
```
{ 
//..
"ignore": ["**/node_modules/@types/**"]
//..
}
```
