### ISSUE TITLE
Providing configuration to controllers

### ISSUE THREAD

**Issue by danzel** [lukeautry/tsoa#7]
I'd like to pass some settings to my controllers to configure them correctly (db connection details as an example).

Is there a nice way to do this? My current thought is to have them require a static settings object that I set up externally.

Ideally I'd like to do this by passing an object to their constructor, but if there was a post construction init method that'd probably be fine.

Thanks :)

**Comment by lukeautry** [comment]
@danzel I've thought about this, and there's more than db connection details that this might be useful for.

Really, what we're talking about is dependency injection. This could be the raw node.js request, it could be a data access service, anything. Either way, the controller should be fully testable without any knowledge of your middleware or w/e. It also allows you to do things like oauth without having to bake it into the library.

I would like to implement decorator based injection, something like this:

`
@Inject(UserService, Request)
@Route('Users')
export class MyController {

     constructor(private UserService: UserService, private Request: Request) {

     }

     @Get()
     public async getUsers(): Promise<User[]> {
          return this.UserService.getUsers();
     }
}
`

Interested to hear your thoughts on this.

**Comment by danzel** [comment]
That looks great!

**Comment by lukeautry** [comment]
@danzel I looked into this a bit, and it quickly became obvious that I'd basically be creating a dependency injection framework, which isn't the road I want to go down.

That said, I think it's very possible to get an existing DI framework to work within our context. Based on a little bit of research, [Inversify](http://inversify.io/) seems like a robust option.

My plan is to implement something like Inversify in [the example project](https://github.com/lukeautry/tsoa-example) that we can reference going forward.

**Comment by danzel** [comment]
Awesome.
My static vars work fine for now (and are fine for production TBH)

**Comment by andreasrueedlinger** [comment]
I am also very interested in IOC-support. Have you looked more into it?
What would be the suggested way to go? Write an express-inversify template for the routes where the controllers are created by the kernel of inversify?

**Comment by andreasrueedlinger** [comment]
Also, I would like to get a possibility to get access to the request object in the controller methods somehow. For example when using some kind of authorization which stores something in the request context or some other context information.

**Comment by lukeautry** [comment]
@andreasrueedlinger Since two folks are asking for it, I think it's worth taking another stab at it.

> Write an express-inversify template for the routes where the controllers are created by the kernel of inversify

I think so.

> Also, I would like to get a possibility to get access to the request object in the controller methods somehow.

The way to do this now is to set up a singleton-type object (probably an exported namespace/variable) that can be accessed statically.

**Comment by andreasrueedlinger** [comment]
> The way to do this now is to set up a singleton-type object (probably an exported namespace/variable) that can be accessed statically.
I suggest another alternative: Request and/or Response objects can be injected as additional parameters in Controller methods like that
```ts
@Get('user/:id')
public async getUser(id: number, @Request request: express.Request): Promise<User> {
...
}
```
The swagger generator would ignore these kind of parameters with `@Request` and `@Response` decorators and the routing mechanism injects the corresponding parameter in the `getValidatedParams` method.
@lukeautry what do you think?

**Comment by lukeautry** [comment]
Closing, see #25
