### ISSUE TITLE
RoutesConfig error

### ISSUE THREAD

**Issue by Dirrk** [lukeautry/tsoa#70]
When providing iocModule in the RoutesConfig it checks to see if the file exists at the path inside the string name but the docs say:

> Note that the path is relative to the routesDir and does not contain the extension.

I can fix this, but I am not sure if you want to fix it via the docs or code.  

Also as a heads up this bug: https://github.com/vvakame/typescript-formatter/issues/87 is causing a build failure for your code.  Potential solutions would be to lock down to version (4.1.2) until its fixed or pass in vscode param.

**Comment by lukeautry** [comment]
@Dirrk I think we should just fix it in the docs, some of the work @isman-usoh did on working path probably caused this.

Regarding typescript-formatter, I think this isn't an issue if you use "yarn" to install, which I have been. That said there's nothing in the project docs that would indicate to use yarn for dev environment.

**Comment by Dirrk** [comment]
What about yarn is not causing the issue?  Wouldn't a new user, installing with yarn to this repo have problems? Maybe I am just missing something, and its possible because I don't use yarn.  I will put up a pr to fix the docs if thats cool

**Comment by lukeautry** [comment]
Well, I only say that because I'm using yarn to install deps locally and haven't seen the problem; yarn generates a lock file, which prevents weird npm behavior of auto-updated to minor/patch versions with breaking changes.

That said I have no problem pinning the version, will look at your change.
