### ISSUE TITLE
"A 204 response must not include a message-body"

### ISSUE THREAD

**Issue by aktary** [lukeautry/tsoa#702]
Generated swagger.json breaks validation, which breaks SDK generation.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Generated swagger.json should validate properly.

## Current Behavior

Currently, Tsoa generates:
```
"204": {
	"content": {
		"application/json": {}
	},
	"description": ""
}
```
for `Promise<void>` returns.  This causes validation to fail (I'm using https://github.com/IBM/openapi-validator), which, in turn, breaks client generation.

```yaml

```

```ts
```

## Possible Solution

Simply omitting the
```"application/json": {}```
makes it work again.

I believe, though, I haven't tested it yet, that moving the `if (res.schema && !isVoidType(res.schema))` statement [here](https://github.com/lukeautry/tsoa/blob/05e6bcc33bde4ea32aa53ea830895594eb608cb0/src/swagger/specGenerator3.ts#L283) up to [here](https://github.com/lukeautry/tsoa/blob/05e6bcc33bde4ea32aa53ea830895594eb608cb0/src/swagger/specGenerator3.ts#L277) might fix the problem.

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: tsoa@3.0.8
Version of NodeJS: v12.11.1

- Confirm you were using yarn not npm: [x]

## Detailed Description

<img width="298" alt="image" src="https://user-images.githubusercontent.com/6234384/82282098-a43f3900-9958-11ea-9be2-46d8552b0de3.png">

<img width="427" alt="image" src="https://user-images.githubusercontent.com/6234384/82282034-7fe35c80-9958-11ea-9769-6c57d18abadc.png">

**Comment by aktary** [comment]
I've validated that my suggested change "works" locally... but no idea if it has ripple effects beyond my specific case.

**Comment by WoH** [comment]
Can you point me to the part of the OpenAPI spec which says that this is not permitted ("MUST NOT" in OpenAPI spec terms would mean we produce an invalid spec)?

**Comment by jackey8616** [comment]
Help confirm:
I don't see any of OpenAPI spec explicitly mention about code 204's response format.

IMHO, OpenAPI provide a very flexible specification to define responses with/without message-body.
But I do found in [RFC-7231](https://tools.ietf.org/html/rfc7231#section-6.3.5) says that an message-body should not be provide.

I think tsoa should follow RFC-7231 and provide an empty message-body 'in default'.
But tsoa could still keep the field let users who still wants datas in message-body—even they againsts RFC—to have changce to do so.

**Comment by aktary** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.5

```10.2.5 204 No Content

The server has fulfilled the request but does not need to return an entity-body, and might want to return updated metainformation. The response MAY include new or updated metainformation in the form of entity-headers, which if present SHOULD be associated with the requested variant.

If the client is a user agent, it SHOULD NOT change its document view from that which caused the request to be sent. This response is primarily intended to allow input for actions to take place without causing a change to the user agent's active document view, although any new or updated metainformation SHOULD be applied to the document currently in the user agent's active view.

The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields.```

**Comment by WoH** [comment]
Alright, so we produce valid OpenAPI, that's what I thought. So this still applies:

> I'd probably take a PR regardless but I think OpenAPI usually allows this kinda stuff.
