### ISSUE TITLE
XML support

### ISSUE THREAD

**Issue by gthomop** [lukeautry/tsoa#704]
I would like to know if there is a way to generate 'application/xml' or 'text/xml' as the content type of the response bodies. If there is not, I would like to request the addition of this feature.

## Sorting

- I'm submitting a

  - [ ] bug report
  - [x] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit
  - [x] use yarn, not npm

## Detailed Description

We would like to provide a 'format' query parameter into our endpoints with the options: json and xml. However, we have managed to make tsoa generate specs that only contain primitive and json objects content types. We could just make it be a string, but I don't think this is the best solution.

**Comment by WoH** [comment]
I strongly disagree with diverging from the "proper" way to perform content negotiation here.
That said, we don't support XML out of the box and I'd accept a PR that respects the `Accept` header and sends XML if the client asks for it.
