### ISSUE TITLE
Schema in swagger.json is not correct (any -> Map)

### ISSUE THREAD

**Issue by NeoKenshinX** [lukeautry/tsoa#711]
## Sorting

- **I'm submitting a ...**

  - [x ] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

In the express project, I have a TypeScript model defined as follows:

```ts
export interface MyValueInfo {
  ctxKey: string;
  value: any;
}
```

When I use swagger codegen to generate the client, this produces a `any` for value just as the source was. If the swagger.json would be like the following, the generator will generate the correct API client.

**swagger.json**
```json
MyValueInfo": {
    "properties": {
        "ctxKey": {
            "type": "string"
        },
        "value": {
            "type": "object"
        }
    },
    "required": [
        "ctxKey",
        "value"
    ],
    "type": "object",
    "additionalProperties": false
}
```

## Current Behavior

In the express project, I have a TypeScript model defined as follows:

```ts
export interface MyValueInfo {
  ctxKey: string;
  value: any;
}
```

This model is used as a result type in one of my controllers. The command `npx tsoa spec` produces a swagger.json but creates a definition for **value** that will produce a `Map` instead of `any` in the generated client (using swagger codegen).

**swagger.json**
```json
MyValueInfo": {
    "properties": {
        "ctxKey": {
            "type": "string"
        },
        "value": {
            "additionalProperties": true
        }
    },
    "required": [
        "ctxKey",
        "value"
    ],
    "type": "object",
    "additionalProperties": false
}
```

## Possible Solution

At the moment I'm not able to generate a usable client for the endpoint where *any* object may be provided.

## Steps to Reproduce

Use the model above in a result for a controller action and generate the spec file.

## Context (Environment)

Version of the library: 3.0.8
Version of NodeJS: 13.10.1

- Confirm you were using yarn not npm: [x ]

**Comment by WoH** [comment]
It's hard to see if this is an issue with swagger codegen or tsoa from the description.
When reporting bugs, please refer to the OpenAPI specification, not some other tool in the ecosystem if possible.
We explicitly set `additionalProperties` to `true` [here](https://github.com/lukeautry/tsoa/blob/master/src/swagger/specGenerator.ts#L155), I don't think it should harm any codegen that correctly implements the OpenAPI specification given my current understanding, since it's just explicity stating the [default](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#properties).

**Comment by WoH** [comment]
I've quickly tried this using [editor.swagger.io](https://editor.swagger.io/).

Changed the component schema of `Pet` to:
```yaml
  Pet:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
[...]
      name:
        additionalProperties: true
        example: "doggie"
[...]
```

Using the integrated codegen (which I assumed is the same one you're using), this was the generated TS interface:
```ts
/**
 * 
 * @export
 * @interface Pet
 */
export interface Pet {
    /**
     * 
     * @type {number}
     * @memberof Pet
     */
    id?: number;
    /**
     * 
     * @type {Category}
     * @memberof Pet
     */
    category?: Category;
    /**
     * 
     * @type {any}
     * @memberof Pet
     */
    name: any;
    /**
     * 
     * @type {Array<string>}
     * @memberof Pet
     */
    photoUrls: Array<string>;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof Pet
     */
    tags?: Array<Tag>;
    /**
     * pet status in the store
     * @type {string}
     * @memberof Pet
     */
    status?: Pet.StatusEnum;
}
```

**Comment by NeoKenshinX** [comment]
Thanks for your reply, I guess I'll have to investigate further (regarding your  in order to give you a qualified answer. We just tested the following:

Setting `additionalProperties: false` and `type: "object"` leads to generating `any` using the converter. Maybe the templates we're using are to blame. I'll get back to you soon. Thanks for your quick response :-)

**Comment by NeoKenshinX** [comment]
We've now tried your approach using https://editor.swagger.io/ - when switching to OpenAPI Specification 3 and try your example, this also leads to the same output as we're having (so the one we can't work with). When using the OpenApi Specification 2 `any` is generated (as expected). But we need to use Version 3 :-)

When using **Swashbuckle** to generate the swagger.json for our .NET Core Rest Services, for the same property (of C# type `object`, which is comparable to `any` in TypeScript) only the information `type: "object"` is written to the property information (the `additionalProperties` is not there at all). So we'd need `npx tsoa spec` to generate the same for properties having set the `any` type in the models when using OpenApi Specification 3.

If you could change it to generate `any` properties differently for OpenApi Specification 3, the generator also generates the correct TypeScript client with `any`.
