### ISSUE TITLE
Is there a way / documentation to split swagger generation accross multiple express apps?

### ISSUE THREAD

**Issue by ianendboss** [lukeautry/tsoa#713]
In our current Firebase project, we have multiple express apps that are deployed to a single `host url` with each one having its own `basePath`. The folder hierarchy we follow is as below:
```
-docs
    -v1
        -swagger.json
    -v2
        -swagger.json
-src
    -v1
       -routes.ts
       -controllerV1
       -index.ts
       -tsoa.json
    -v2
       -routes.ts
       -controllerV2
       -index.ts
       -tsoa.json
  -index.ts
```

Ideally we'd like to have a single `swagger.json` under `src/docs` that merges both swagger.json into a single one. (Generated pragmatically).

I've been unable to find any clear cut examples / documentation related to this particular issue so any and all help would be appreciated.
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

**Comment by ianendboss** [comment]
Notes: I should specify that since we are using multiple express apps, the `routes.ts` for each one is different.

**Comment by kdeenanauth** [comment]
@ianendboss I'm in the same situation (on Firebase, needing to split across Express instances). I created a custom handlebars template that creates a RegisterRoutes method for each controller. Let me know if that would be helpful to you.

See https://tsoa-community.github.io/docs/templates.html

**Comment by noskiboots** [comment]
@kdeenanauth I am working on the same thing for Firebase functions. Would you mind sharing your template?

**Comment by kdeenanauth** [comment]
@noskiboots here you go https://gist.github.com/kdeenanauth/13ebecfd73eb71eef4bcf2b6d3fcc605 . This creates a separate register function for each controller found. So you can mix it with multiple express servers. YMMV - per the docs there is going to be some long term maintenance issues whenever TSOA updates their own templates.

**Comment by noskiboots** [comment]
@kdeenanauth awesome solution. Thank you!

**Comment by dbryar** [comment]
Necroposting, but you can merge swagger files with open API merge.

I had issues with it, and eded up forking as the maintainer was not acting on PRs
https://github.com/dbryar/openapi-merge
