### ISSUE TITLE
Inject Socket.io into Controllers

### ISSUE THREAD

**Issue by kevin192291** [lukeautry/tsoa#714]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

- Confirm you were using yarn not npm: [x]

## Detailed Description

I am wondering if there is a way to inject Socket.io into the controllers? I have setup socket.io in the app.ts, but it would be amazing to have access to emit messages when specific endpoints are called.

**Comment by WoH** [comment]
The framework does not support this out of the box. However, since this does not have any implications on the OpenAPI Specifications as far as I can tell, you might want to take a look at using your own decorator for this.

Alternatively, almost anything can be done with a custom template, but this means you can't rely on tsoa following SemVer for these, so I'd only recommend this as a last resort.

**Comment by kevin192291** [comment]
I love the idea of the custom decorators. I started to look through the tsoa's built in decorators, but from what I found they are all mostly empty, I am wondering if you have any place to start with me getting a reference of Socket.io in my app.ts to a decorator function. I will be working on this all day today, if I figure it out, I will post my result.

**Comment by WoH** [comment]
tsoa uses decorators at build time to parse the annotated parameter/method/class, think macro instructions at the AST level.
Which means they are not suitable for learning about decorators.
That said, you can still implement a regular decorator. I'm not sure about how you plan to use it, can you share a rough idea of what the API/functionality should look like?

**Comment by kevin192291** [comment]
I am going to close this because I decided the easiest way to get this done is to add the Socket.io code in app.ts, and then export a few variables, In case you or anyone is wondering here it is, I know it is far from perfect, it is getting the job done for now. I will look back into doing this better later on.

app.ts:

`
... boilerplate TSOA stuff here...

const socket_clients: ISocketClient[] = [];
var http = require('http').Server(app);
var io: SocketIO.Socket = require('socket.io')(http);
var gsocket: SocketIO.Socket = null;

io.on('connection', (socket: SocketIO.Socket) => {
  gsocket = socket;
  
  socket.emit('server-ready', {data: 'ready'}); // Alert Client that Server is ready

  socket.on('register', data => {
    socket_clients.push({username: data.username, socket_id: socket.id});
    console.log('all users', socket_clients);
  });

  socket.on('disconnect', data => {
    socket_clients.forEach((client, index) => {
      if (client.socket_id === socket.id) {
        console.log('found user');
        socket_clients.splice(index, 1);
      }
    });
    console.log(`Array after use ${socket.id} left`, socket_clients);
  });

});
http.listen(3001, function() {
   console.log('listening on localhost:3001');
});
export { app, gsocket, io, socket_clients };
`
