### ISSUE TITLE
Could not start server

### ISSUE THREAD

**Issue by Edwardchorius** [lukeautry/tsoa#715]
After running the command node build\server.js it throws:

internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'build/routes'
Require stack:

.*/Node\tsoa\introduction\build\app.js
.*/Node\tsoa\introduction\build\server.js

  code: 'MODULE_NOT_FOUND',

## Sorting

- **I'm submitting a ...**

  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The server should run as its supposed defined by the getting started section in tsoa documentation

## Current Behavior

Instead it throws the error shown above

## Steps to Reproduce

1. Follow the Getting Started Guide in the tsoa documentation
2. In the end run:
_yarn run tsc --outDir build --experimentalDecorators
node build/server.js_ 

## Context (Environment)

I am using YARN instead of NPM

**Comment by WoH** [comment]
Seems like the routes haven't been generated:
Running `yarn run tsoa routes` should do that.
https://tsoa-community.github.io/docs/getting-started.html#building-the-routes-file

**Comment by Edwardchorius** [comment]
Danke! It worked! It turned out that in my manually created 'build' folder after running this command there was a second 'build' folder and I had to run the command 'node build/build/server.js'. After that there was another error about the routes.js not finding the imported 'usersController.js' so I knew that it had something to do with the wrong path. So even though manually editing these auto-generated files is not recommended,  I knew where the usersController.js pointed so I manually edited it and it finally compiled!

**Comment by WoH** [comment]
I'll try to publish the project I used for the guide for reference.
The issue with manually editing those files is that you should automatically call `tsoa routes` when any of the controller's method interfaces change, which will overwrite your manual edits.
So with the recommended setup this should automatically work and work again once things change.
