### ISSUE TITLE
package.json author as object not supported

### ISSUE THREAD

**Issue by ealib** [lukeautry/tsoa#716]
When `package.json` contains `author` as `{ name: string, email: string }`, **tsoa** can't generate the OpenApi specification document.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Command `tsoa spec` should generate the OpenApi document.

## Current Behavior

```sh
$ tsoa spec
Generate swagger error.
 TypeError: _j.sent(...).match is not a function
    at node_modules\tsoa\dist\cli.js:206:39
    at step (node_modules\tsoa\dist\cli.js:45:23)
    at Object.next (node_modules\tsoa\dist\cli.js:26:53)
    at fulfilled (node_modules\tsoa\dist\cli.js:17:58)

$
```
## Possible Solution

Convert `author` from object to string.

## Steps to Reproduce

Edit `package.json`:

**BEFORE**

```json
{
    "name": "example-tsoa-project",
    "author": "John Smith <john.smith@example.com>",
    ...
}
```

**AFTER**

```json
{
    "name": "example-tsoa-project",
    "author": {
        "name": "John Smith",
        "email": "john.smith@example.com"
    },
    ...
}
```

then  run `tsoa spec` again.

## Context (Environment)

Version of the library: 3.1.0
Version of NodeJS: v12.17.0

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
When implementing this, I had the `package.json` format in mind as used by npm:
https://docs.npmjs.com/creating-a-package-json-file#author-field

Maybe we can find a way to log a better error message, but I don't think I've seen anyone use another format.

**Comment by markghareeb** [comment]
Hey @WoH, I ran into the same issue. This page of the npm docs says either way is valid for the author field, a single string or an object.
https://docs.npmjs.com/files/package.json#people-fields-author-contributors

**Comment by WoH** [comment]
If anyone wants to implement this, feel free to send a PR to support this format.
