### ISSUE TITLE
Getting Started directions produces unexpected build artifacts

### ISSUE THREAD

**Issue by chrisahardie** [lukeautry/tsoa#717]
If I follow along with the [Getting Started](https://tsoa-community.github.io/docs/getting-started.html) document, the build folder is populated incorrectly and I end up with this structure:

```
/build
  /build
  /src
  routes.js
```

When I run `node build/server.js`, it fails because `server.js` is under `/build/build`

## Sorting

- **I'm submitting a ...**

  - [ X ] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [ X ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The build folder should be populated with the `server.js` file.

## Current Behavior

`server.js` is placed at `/build/build`

## Possible Solution

I believe the issue is `/src/app` references `/build/routes.ts`. As an alternative, `routes` could be place under `/src/oas` and referenced from there. My tsoa.json:

```
{
  ...
  "routes": {
    "routesDir": "src/oas"
  }
}
```

Then I include `src` in my `tsconfig.json`:

```{
  "compilerOptions": {
    ...
  }.
  "include": ["src"]
}
```
When compilation is outputted, `routes.js` will be placed under the build folder with the other transpiled files. `server.js` is placed correctly at `/build/server.js`

## Steps to Reproduce

Follow the Getting Started guide.

## Context (Environment)

Version of the library: 3.1.1
Version of NodeJS: 12.16.1
OS: Windows 10

- Confirm you were using yarn not npm: [ X ]

## Detailed Description

I'm proposing a change to the description to reflect a working strategy to get started.

It also might be nice to include a link to retrieve the user e..g `http://localhost:3000/users/1` I would hope developers would be able to figure it out, but it would be a convenience.

## Breaking change?

No

UPDATE - I've gone through the Getting Started section three times to make sure I followed the steps properly. I'll try to figure out if there's something local to my machine that would be causing this, but I'm scratching my head... I'll try on my personal laptop later.

**Comment by WoH** [comment]
Thanks for the bug report. 
The relevant section should be [updated now](https://tsoa-community.github.io/docs/getting-started.html#building-the-routes-file).

Just to confirm, since there are some differences between what you described and where you should be at the end of that section:

Your `build` structure should look like this:

```
build/
  - build.ts
  src/
    - app.js
    - server.js
  build/
    - build.js

```

Is this the case or is there some other misleading info in there?

**Comment by chrisahardie** [comment]
@WoH Ok, that makes more sense! I think that lines things up now.

Is there a reason you don't include `routes.ts` and `swagger.json` under `/src`? Otherwise you'll end up with superfluous assets in your distribution.

Thanks!

**Comment by WoH** [comment]
It's a trade off. I tend to think of the routes file as another build asset, one that tsoa produces (the other ones being those that ts produces).
I value a more organized code setup (where all the stuff I don't care about is in `build`) over a more organized build output here, but wouldn't discourage anyone from having his routes.ts in the main folder and pushing just the js files to `build/`.
