### ISSUE TITLE
Unexpected schema generated

### ISSUE THREAD

**Issue by chrisahardie** [lukeautry/tsoa#718]
By following along with the getting started guide, I created this type:

`export type UserCreationParams = Pick<User, "email" | "name" | "phoneNumbers">;`

This creates two schemas - `UserCreationParams` and `Pick_User.email-or-name-or-phoneNumbers_`, with the former referencing the latter.

I then noticed an image in the Getting Started guide that didn't have the second schema:

![image](https://user-images.githubusercontent.com/2429373/83549086-bf6e8480-a4d2-11ea-933c-caa5739af319.png)

Based on the guide, should I be seeing `Pick_User.email-or-name-or-phoneNumbers_` as a schema or did I do something incorrect?

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [ X ] support request

- I confirm that I
  - [ X ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

There should only be the `UserCreationParams` schema.

## Current Behavior

I am seeing a `UserCreationParams` and a `Pick_User.email-or-name-or-phoneNumbers_` schema.

## Context (Environment)

Version of the library: 3.1.1
Version of NodeJS: 12.6.1

- Confirm you were using yarn not npm: [ X  ]

**Comment by WoH** [comment]
There's no really good approach to have any other behavior that doesn't have significant downsides. We need to create 2 schemas (1 per reference). One for the left side of the type alias (`UserCreationParams` -> `Pick`) and one for the reference type on the right side of the schema (`Pick` -> declaration). It's unfortunate that SwaggerUI displays both, when you look at the underlying spec, `UserCreationParams` is a reference to the `Pick` (with potentially additional info).

**Comment by chrisahardie** [comment]
Ok, thanks, just wanted to make sure I wasn't missing something.

**Comment by WoH** [comment]
You aren't and I can understand the confusion when looking at the way SwUI displays the spec, but I think you'd agree that we should create a schema for every type alias. But we can't forget that applies to `Pick<>` aswell though, since that's just an alias for a mapped type:

```ts
/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};
```
