### ISSUE TITLE
ValidateError for GET Request by using TS Enum type in Query Parameter

### ISSUE THREAD

**Issue by Edwardchorius** [lukeautry/tsoa#719]
I'm submitting a ...

- [x]  support request

I confirm that I

 

- [x] used the search to make sure that a similar issue hasn't already been submit

## Expected Behavior
 I expect after calling the endpoint to receive an appropriate result, by also providing 2 query parameters

## Current Behavior

When I add 2 @Query() attributes and add the params in the Get() and provide them in the URI,  I receive a 400 Error and it points me to:
_/node_modules/tsoa/dist/routeGeneration/templateHelpers.js:_

## Possible Solution

When I remove the query params and hardcode the dynamically passed params into the service (in this case all it matters is that they are not provided to the call) it works as supposed to
## Steps to Reproduce

1. Add a @Query() param to the Get() action and provide it via Postman, for example.
2. Create the routes
3. Build and run the project
4. Make the Get() call via Postman and expect the 400 Error. 

Does it have something to do with the generated routes.ts file?

**Comment by Edwardchorius** [comment]
The solution was making the type of the query param (using TS) a 'string enum'. Earlier it was just an regular enum.

**Comment by WoH** [comment]
If you don't mind, I'd like to reopen this. We should support TS Enums in there. Would you mind sharing the enum?

**Comment by Edwardchorius** [comment]
> If you don't mind, I'd like to reopen this. We should support TS Enums in there. Would you mind sharing the enum? Maybe if you still have it, the stack trace.
> 
> E: There are some types that don't make sense in Queries, but we throw an Error if we detect them. So that's at least the expected behavior if something doesn't work.
> Silently failing shouldn't be an option.

It looked something like this:
`@Get()
    public async GetConvertedValue(
        @Query('baseCurrency') baseCurrency: Currency,
        @Query('symbol') symbol: Currency
    ) : Promise<string> {... // Code goes in here}`, where the 'Currency' is the enum:
`export enum Currency {
    EUR = "EUR",
    USD = "USD",
    GBP = "GBP"
}`. This is the 'String Enum', whereas it didn't work when it were just EUR, USD & GBP without their string values.

**Comment by WoH** [comment]
Ah, that's because TS implictly converts these to numbers, so that's what we do aswell.

See: [This Playground](http://www.staging-typescript.org/play?#code/KYDwDg9gTgLgBMAdgVwLZwMLKlJBjATzgG84BRAVQCU4AaOCgZQBF6BxAIQAU4BfIA)

If you look at the produced JS, it's numbers, you can also over over EUR and it should show `(enum member) Currency.EUR = 0`

Sending in 0,1,2 should've worked :laughing:
