### ISSUE TITLE
Descriptions for type-checked responses

### ISSUE THREAD

**Issue by devnev** [lukeautry/tsoa#722]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I can use `@Res` to declare type-checked responses and have it include a description in the resulting spec.

```yaml
openapi: 3.0.0
paths:
    /my/endpoint:
        get:
            operationId: MyEndpoint
            responses:
                '404':
                    description: "entity not found"
                    content:
                        application/json:
                            schema:
                                type: object
```

```ts
class MyController {
  @Get('/my/endpoint')
  public async myEndpoint(
    @Res('entity not found') notFound: TsoaResponse<404, {}>
  ): Promise<void> {}
}
```

## Current Behavior

From what I can tell from docs and reading the code-gen, I cannot have the description field of the response spec filled in.

```yaml
openapi: 3.0.0
paths:
    /my/endpoint:
        get:
            operationId: MyEndpoint
            responses:
                '404':
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
```

```ts
class MyController {
  @Get('/my/endpoint')
  public async myEndpoint(
    @Res() notFound: TsoaResponse<404, {}>
  ): Promise<void> {}
}
```

## Possible Solution

See code in expected behaviour, or an update to the docs to clarify.

## Steps to Reproduce

See above code

## Context (Environment)

Version of the library: 3.1.0
Version of NodeJS: 10.19

- Confirm you were using yarn not npm: [x]

## Breaking change?

Probably not a breaking change if it can be done with a new optional parameter to `@Res`

**Comment by WoH** [comment]
Hi, we parse this like the regular `@param <name> description, so this is how you can already add descriptions:

```ts
class MyController {
  /**
   * @param notFound entity not found
   */
  @Get('/my/endpoint')
  public async myEndpoint(
    @Res() notFound: TsoaResponse<404, {}>
  ): Promise<void> {}
}
```

**Comment by devnev** [comment]
Thanks, that works. 

Having said that, it's a bit weird to read as documentation on the parameter; the parameter is a callback but if I were to document it as "callback to send a not found response" that would show up in the spec. Even the example on error handling documents it with `   * @param notFoundResponse The responder function for a not found response`, which makes sense as parameter documentation but not as the response description in the spec.

**Comment by letmaik** [comment]
Definitely awkward, I think the issue should be re-opened.
