### ISSUE TITLE
Should tsoa require typescript as a runtime (non-dev) dependency?

### ISSUE THREAD

**Issue by tavishf** [lukeautry/tsoa#730]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

A project with tsoa as a dev dependency only should run fine when built via npm ci --production.

_At least, this is what I would intuitively expect, but this might be totally wrong. It might be that it's actually intended for it to be a full runtime dependency, in which case this issue makes no sense. But, it seemed surpising/unusual that it needed to be a runtime dependency to me._

## Current Behavior

App with typescript as a dev dependency only, when built with npm ci --production fails at runtime because typescript-formatter has a peer dependency on typescript, and it's not there.

## Possible Solution

Not sure, don't know enough about why it's a dependency to comment.

## Steps to Reproduce

Not sure if this happens 100% of the time or just with the specific way we're using it - will provide more info if this is in fact not intentional behaviour, otherwise there's no point. :)

## Context (Environment)

Version of the library: 3.1.1
Version of NodeJS: 12.13.1

- Confirm you were using yarn not npm: [ ]

## Detailed Description

Maybe no change, this might be entirely intended!

## Breaking change?

Probably not?

**Comment by kdeenanauth** [comment]
It seems intentional for the time being - see #690

**Comment by IanStorm** [comment]
As the related PR #690 is still under discussion, this issue should not be marked as stale from my perspective.
But I am not sure how this is usually being handled. What do you think?
