### ISSUE TITLE
 TypeError: Cannot set property 'examples' of undefined

### ISSUE THREAD

**Issue by WWL-MikeRoberts** [lukeautry/tsoa#735]
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

swagger.json is generated?

## Current Behavior

```
> tsoa swagger

Generate swagger error.
 TypeError: Cannot set property 'examples' of undefined
    at {root}\node_modules\tsoa\dist\swagger\specGenerator3.js:290:92
    at Array.forEach (<anonymous>)
    at SpecGenerator3.buildOperation ({root}\node_modules\tsoa\dist\swagger\specGenerator3.js:273:26)
    at SpecGenerator3.buildMethod ({root}\node_modules\tsoa\dist\swagger\specGenerator3.js:244:60)
    at {root}\node_modules\tsoa\dist\swagger\specGenerator3.js:237:23
    at Array.forEach (<anonymous>)
    at {root}\node_modules\tsoa\dist\swagger\specGenerator3.js:232:18
    at Array.forEach (<anonymous>)
    at SpecGenerator3.buildPaths ({root}\node_modules\tsoa\dist\swagger\specGenerator3.js:227:35)
    at SpecGenerator3.GetSpec ({root}\node_modules\tsoa\dist\swagger\specGenerator3.js:54:25)
```

## Possible Solution

Change line 299 from
```ts
(swaggerResponses[res.name].content || {})['application/json']['examples'] = examples;
```
to
```ts
(swaggerResponses[res.name].content || {"application/json": {}})['application/json']['examples'] = examples;
```
or maybe throw an exception when this if check on line 287 fails
```ts
      if (res.schema && !isVoidType(res.schema)) {
```

## Steps to Reproduce

not exactly sure what steps are needed. 

## Context (Environment)

Version of the library: 3.2.1
Version of NodeJS: 13.12.0

- Confirm you were using yarn not npm: [ ]

## Detailed Description
This issue appears to have been introduced in commit 75149bc444ccd062899e4bd2bb15d3c23333bf48 when an if check was put around adding a content property to swaggerResponses[res.name] in the buildOperation function in SpecGenerator3. I don't know if there is something else wrong with my setup that is causing res.schema to not be set but this looks like a valid scenario from what I can tell. 
```ts
protected buildOperation(controllerName: string, method: Tsoa.Method): Swagger.Operation3 {
    const swaggerResponses: { [name: string]: Swagger.Response3 } = {};

    method.responses.forEach((res: Tsoa.Response) => {
      swaggerResponses[res.name] = {
        description: res.description,
      };
      if (res.schema && !isVoidType(res.schema)) {
        swaggerResponses[res.name].content = {
          'application/json': {
            schema: this.getSwaggerType(res.schema),
          } as Swagger.Schema3,
        };
      }
      if (res.examples) {
        const examples = res.examples.reduce<Swagger.Example['examples']>((acc, ex, currentIndex) => {
          return { ...acc, [`Example ${currentIndex + 1}`]: { value: ex } };
        }, {});
        /* tslint:disable:no-string-literal */
        (swaggerResponses[res.name].content || {})['application/json']['examples'] = examples;
      }
    });

    return {
      operationId: this.getOperationId(method.name),
      responses: swaggerResponses,
    };
  }
```
If swaggerResponses[res.name].content is not set (due to res.schema not being set) then an empty object is used and since that empty object does not have an 'application/json' property an exception is thrown trying to set it's examples property.

**Comment by WoH** [comment]
I think setting an example on a void response isn't a good think to do, but we should avoid crashing. I'll take a look.
