### ISSUE TITLE
Boolean body property accepts 'true'/'false' string

### ISSUE THREAD

**Issue by devnev** [lukeautry/tsoa#736]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I have a controller with a boolean field in its `@Body` parameter. I expect that this requires the sent JSON to have a boolean value for the field, and fails the request if the value is not a boolean.

## Current Behavior

If the body contains the string `'true'` or `'false'` for the boolean field, these are converted to boolean values on the fly and accepted, despite not conforming to the spec.

## Steps to Reproduce

```ts
@Route('')
class Controller {
  @Post('')
  public async doThing(
    @Body() body: {condition: boolean},
  ): Promise<void> {
  }
}
```

```sh
curl -X POST localhost --data '{"condition": "true"}'
```

## Context (Environment)

Version of the library: 3.1.0
Version of NodeJS: 10.19

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
This is intended behavior. While the input does not conform to the spec, we can make it conform, so we consider it to be a) better UX b) better developer experience, as adhering to the strict behavior would mean all query, path and header parameters would have to be strings.
