### ISSUE TITLE
Retrieve data without having it wrapped.

### ISSUE THREAD

**Issue by kevin192291** [lukeautry/tsoa#738]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Data should be POSTED to the db

## Current Behavior

Data is required to be wrapped in an object

## Possible Solution

Just get the object from the @BodyProp() without wrapping it in the property key

## Steps to Reproduce

Here is my @Post():
```
@Post()
  public async create(@BodyProp() data: ILora): Promise<any> {
    try {
      this.setStatus(200);
      await mapObject(data).save();
    } catch (error) {
      this.setStatus(500);
      return { error };
    }
  }
```
It expects that the data of ILora will arive wrapped in a data object such as:
```
"data": {
    stuff is here
}
```

I am actually expecting data just in an object:
{
stuff is here
}

Is this possible? I could access the data by doing: data.property
But the incoming data (not under my control) cannot be wrapped, and is being rejected at the route level and I am getting the error:
```
ValidateError:
at new ValidateError (/home/...........
```

**Comment by tsimbalar** [comment]
@kevin192291  I think what you want is to just use the `@Body()` annotation instead of `@BodyProp()`, as described in the example in the documentation : https://tsoa-community.github.io/docs/getting-started.html#defining-a-simple-controller 

so you should do : 


```ts
  @Post()
  public async create(@Body() data: ILora): Promise<any> {
    // now if you POST `{whatever : 'x'}` , data will contain `{whatever : 'x'}`
  }
```

**Comment by kevin192291** [comment]
@tsimbalar not sure how I missed that, Thanks!
