### ISSUE TITLE
Direct access to auth result

### ISSUE THREAD

**Issue by devnev** [lukeautry/tsoa#739]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior

I have currently added a `@Request` parameter to most of the methods I've written, to give them method access to `request.user` from the authentication. The `request.user` property must be an optional property as in some cases the request may not have such a property, but in handlers with authentication the property is always present.

## Expected Behavior

Handlers with authentication have well-typed access to the result of the authentication.

## Possible Solution

Allow parameters with `@Security` annotation, with the effect that the result of the auth process is passed in as that parameter.

e.g. instead of

```ts
@Route('')
class Controller {
  @Get('')
  @Security('jwt')
  public async getThings(
    @Request() request: express.Request
  ): void {
    // do things with `request.user`
  }
}
```

write

```ts
@Route('')
class Controller {
  @Get('')
  public async getThings(
    @Security('jwt') user: User
  ): void {
    // do things with `user`
  }
}
```

A mix of any number of method and parameter `@Security` annotations could be allowed. The auth checks would be executed in the same order they appear in the source, i.e. all the method annotations followed by all the parameter annotations.

## Context (Environment)

Version of the library: 3.1.0
Version of NodeJS: 10

- Confirm you were using yarn not npm: [x]

## Breaking change?

The proposed solution would not be a breaking change.

**Comment by fantapop** [comment]
Hi @devnev  in our instance we have 3 types of auth and some methods are unauthenticated.  We're using a discriminated union pattern for our user object and accompany type narrowing functions to help with the typing.  This seems like it could work in your situation as well.  

The users look something like:

```typescript
interface ApiKeyUser {
    type: 'apiKey;,
    name: string;
    permissions: Permission[];
}
interface OAuthUser {
    type 'oauth';
    name: string;
    email: string;
    permissions: Permissions[];
}
type User = ApiKeyUser | OAuthUser;
function isApiKeyUser(user: User): user is ApiKeyUser {
    return user.type === 'apiKey';
}
```

Sometimes we have special handlng for each authentication type in our controllers. Then we do:

```typescript
@Route('')
class Controller {
  @Get('')
  @Security('apiKey')
  @Security('oAuth')
  public async getThings(
    @Request() request: express.Request
  ): void {
    // process the request
   // do something special for oauth users only
   if (isOAuthUser(user)) {
     // user is proper type now.
     sendConfirmationEmail(user.email);
   }
  }
}
```

**Comment by calvinwyoung** [comment]
I would also like to see what @devnev is suggesting — this would vastly simplify things in our application. FWIW, FastAPI has chosen to adopt a similar implementation in the Python world:
https://fastapi.tiangolo.com/tutorial/security/get-current-user/

**Comment by fantapop** [comment]
Just trying to wrap my head around how this would work. Is the proposal for multiple auth types to allow a call signature which only differs per auth?

```typescript
@Route('')
class Controller {
  @Get('')
  public async getThings(
    @Security('jwt') user: JwtUser
  ): void {
    // do things with `user`
  }

 @Get('')
  public async getThings(
    @Security('saml') user: SamlUser
  ): void {
    // do things with `user`
  }
}
```

**Comment by fantapop** [comment]
This would actually be useful for me as well
