### ISSUE TITLE
Dynamically register routes during development to simplify live-reload

### ISSUE THREAD

**Issue by calvinwyoung** [lukeautry/tsoa#742]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Is it possible to dynamically register routes on the app object during development? If so, then that'd drastically simplify the live-reloading workflow since the user won't have to compile a separate `routes.ts` file.

## Current Behavior

The current behavior requires the developer to compile a `routes.ts` file on their own, which complicates the setup.

## Possible Solution

`inversify-express-utils` provides a possible solution — so long as all `Controller` objects are imported during the setup face, then they provide a `server.build()` method that dynamically registers all routes on the express app.

Reference: https://github.com/inversify/inversify-express-utils

## Detailed Description

Why does `tsoa` require compiling a separate `routes.ts` file in the first place? Dynamically registering routes shouldn't add much performance overhead in production, and it vastly simplifies the setup in development.

**Comment by instantepiphany** [comment]
What would tsoa do instead of generating the `routes.ts` file?

**Comment by calvinwyoung** [comment]
@instantepiphany [`inversify-express-utils`](https://github.com/inversify/inversify-express-utils) also provides a set of `@controller`, `@httpGet`, etc. decorators for defining routes. The exampl here shows how the routes get added to the express app at runtime:
https://github.com/inversify/inversify-express-utils#step-2-configure-container-and-server

It looks like this is what's happening under the hood:
1. The `@controller` decorator adds the controller to a global registry
2. When the express app is getting initalized, the developer needs to make sure all controllers get imported (so the `@controller` decorator can add those controllers to the registry), and then calls a `build()` method that adds the routes to the express app
3. The express app now has routes, and we can call `app.listen()` per usual.

Tsoa needs to perform additional validation on the inputs supplied to each route, but it seems like that could be handled at runtime as well.

Does this thinking make sense? Or is there another reason the `routes.ts` file needs to exist?

**Comment by WoH** [comment]
This might work if you register all the controllers manually by importing them explicitly. However, this is not an option for controllerPathGlobs. Instead, an approach that works for both options should be this: https://tsoa-community.github.io/docs/live-reloading.html

**Comment by thawankeane** [comment]
Any updates on this?

I agree that live reloading is a problem, it complicates the development environment.

Another example is [typescript-rest](https://github.com/thiagobustamante/typescript-rest/wiki/Overview#basic-usage) that builds routes at runtime.
