### ISSUE TITLE
Bundle with webpack for MonoRepo scenario

### ISSUE THREAD

**Issue by rudfoss** [lukeautry/tsoa#743]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

We are using tsoa within a mono-repo project built with yarn workspaces. The repo consists of utility packages and "front-facing" packages such as web front-ends and APIs. Everyting uses typescript internally. In order to alleviate a lot of hassle with cross-package dependencies for production code we're using webpack to bundle each front-facing project.

This has been working fine for our other packages. They get bundled neatly into one large file (we remove chunking for server side code) and we can easily deploy this to our production servers. However with tsoa (which is awesome in so many ways btw!) we're running into issues specifically with how controllers are loaded. Since tsoa loads these dynamically we are getting a lot of warnings along the lines of:

```
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (c:\projects\udi-form\node_modules\webpack\lib\dependencies\ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (c:\projects\udi-form\node_modules\webpack\lib\Compilation.js:1454:24)
    at c:\projects\udi-form\node_modules\webpack\lib\Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\projects\udi-form\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (c:\projects\udi-form\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (c:\projects\udi-form\node_modules\webpack\lib\Compilation.js:1253:28)
    at c:\projects\udi-form\node_modules\webpack\lib\Compiler.js:672:17
    at eval (eval at create (c:\projects\udi-form\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
```

We'd love to be able to bundle everything as it avoids us having to manually track down cross-package dependencies and storing them with the production code. Any tips on how to configure webpack for this scenario would be great. We love how tsoa generates specs directly from the source and we'd like to keep that feature

## Current Behavior

Code bundled with webpack returns a lot of Critical dependency warnings. The bundle also ends up being 18MB large due to webpack not resolving these correctly and ending up bundling all of `typescript.js` along with our code.

```
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (c:\projects\udi-form\node_modules\webpack\lib\dependencies\ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (c:\projects\udi-form\node_modules\webpack\lib\Compilation.js:1454:24)
    at c:\projects\udi-form\node_modules\webpack\lib\Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\projects\udi-form\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (c:\projects\udi-form\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (c:\projects\udi-form\node_modules\webpack\lib\Compilation.js:1253:28)
    at c:\projects\udi-form\node_modules\webpack\lib\Compiler.js:672:17
    at eval (eval at create (c:\projects\udi-form\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
```

## Possible Solution

We've been researching this for about a week, trying different permutations of `webpack`, `ts-loader` `babel-loader` and `tsc` as well as different bundles strategies and orderings, but we've not been able to come up with anything that works. The only thing that we can think of is to somehow drop the dynamic controller loading mechanism (personally I would not mind at all simply registering my controllers in a file using normal imports, but I can certainly see the convenience of the dynamic method).

## Steps to Reproduce

Set up a mono repo using yarn workspaces with two packages. Yarn will generate symlinks for the packages in node_modules at root. One should contain the tsoa-powered api while another can contain utilities.

```
/node_modules/tsoa-project // Symlink to /packages/tsoa-project/
/node_modules/utils // Symlink to /packages/utils/
/packages/tsoa-project/server/server.ts
/packages/utils/aUtil.ts
```

Import the utility from server.ts

The generated code when using `tsc` will contain a require statement pointing to the symlink:

```javascript
require("utils/aUtil.ts")
```

This is because `tsc` does not do any bundling (naturally). However it also means that we still have to keep track of all these imports manually and then make sure we build any dependent packages along with `tsoa-project`. We then have to ensure our paths work correctly (there are tools that can help with this, but they require maintenance).

If we could bundle `tsoa-project` with webpack it would effectively eliminate all of this and give us a nice single-file application that we could deploy. But due to the way controllers are resolved we are not able to make this work right now.

## Context (Environment)

Version of the library: `3.2.1`
Version of NodeJS: `12.16.0`

- Confirm you were using yarn not npm: [X]

## Detailed Description

See description above.

## Breaking change?

Disabling dynamic imports for controllers would certainly be a breaking change, though that may not be needed. We do not know exactly what we need in order to resolve this issue, and it may just be a config-change for webpack. For now I'm just wondering if there is any experience out there with this scenario that we also may benefit from.

With this said, tsoa seems like a great library that does exactly what we need so we'll try to find a way to use it regardless of whether we can get bundling working or not.

**Comment by WoH** [comment]
> Since tsoa loads these dynamically we are getting a lot of warnings along the lines of:

I'm not sure what you mean here. We compile a routes file that imports the controllers. If you run `tsoa routes`, we discover the controllers and generate the routes with import statements. You should be able to bundle this just fine.


About the size. I'm not sure why Webpack doesnhttps://github.com/lukeautry/tsoa/pull/690't seem to be able to figure out to only bundle tsoa's valiation helpers and instead bundles tsoa + typescript. However, https://github.com/lukeautry/tsoa/pull/690 should address this.

**Comment by rudfoss** [comment]
If tsoa does not load routes dynamically then I suspect the problem may have to do with our webpack config with typescript. It might be trying to compile more than necessary. I'll have a look and post the results here.

**Comment by rudfoss** [comment]
I think this can be closed as I don't have time to look into it right now and from @WoH's commment it seems to be an issue with my setup. I'll dig into it more and see if I can determine what's happening later.

**Comment by ljwagerfield** [comment]
@rudfoss did you find a solution to this?

I'm also struggling to get `tsoa` and `webpack` to play nicely.

In my case, webpack chokes when your code imports the `routes.ts` file, with numerous warnings and an error:

```
WARNING in ./node_modules/handlebars/lib/index.js 22:38-45
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/handlebars/lib/index.js 23:2-9
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/handlebars/lib/index.js 24:2-9
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/tsoa/node_modules/typescript/lib/typescript.js 2710:20-42
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/tsoa/node_modules/typescript/lib/typescript.js 5708:41-60
Critical dependency: the request of a dependency is an expression

ERROR in ./node_modules/tsoa/node_modules/@tsoa/cli/dist/cli.js 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #!/usr/bin/env node
| "use strict";
| var __assign = (this && this.__assign) || function () {
```

**Comment by rudfoss** [comment]
@ljwagerfield We actually ignored the warnings about static extraction of dependencies and just used the bundle as is. It is probably quite a bit bigger than we need, but since its not downloaded by the client we figured it wouldn't be too much of a problem.

From our perf testing it does not seem that it has much (if any) impact as our API is fast and stable regardless.

Regarding the last error there I don't think we've seen that one. It seems to be a problem with [this file](https://github.com/lukeautry/tsoa/blob/master/packages/tsoa/src/cli.ts) which may be part of the cli tool though I don't know the package well enough to be sure. It seems strange that you need to bundle the CLI though? Is there an import somewhere you don't need? I don't think we bundle files from the CLI at all as they are should not be needed at runtime.

**Comment by ljwagerfield** [comment]
I removed the errors by adding the following to `webpack`:

```
  externals: [/^tsoa$/],
```

This excludes everything from the `"tsoa"` package, while still allowing `"@tsoa/runtime"` to be bundled.

The `"tsoa"` package is only traversed by webpack because the decoration types that are referenced from your controllers. So when webpack crawls your controllers, it sees things like `import { Route } from "tsoa";`, and then pulls the whole of `tsoa` in. However, since these are only definitions and not actual runtime code, it's OK to exclude the whole module from being bundled.

`@tsoa/runtime` is the only thing that's needed at runtime, and this exclude rule doesn't match on that (so it will be included in the bundle).

**Comment by rudfoss** [comment]
If anyone comes back to this thread looking for an answer it seems the easiest way to bundle with webpack is to simply replace all `import { ... } from "tsoa"` entries with `import { ... } from "@tsoa/runtime"`. This will exclude `@tsoa/cli` from the bundle making it work without any other configuration in webpack (or so it seems).
