### ISSUE TITLE
How to implement custom middleware templates? No documentation? 

### ISSUE THREAD

**Issue by Billy-** [lukeautry/tsoa#746]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

I'm trying to explore the custom middleware templates functionality to generate e.g a node library and a node CLI to interact with the API I've created with tsoa (is it worth this being a separate feature request? I figured it's potentially outside the scope of this project?).

My problem is that I can't figure out how to get started. I found the documentation at https://tsoa-community.github.io/docs/templates.html#overriding-route-template but it doesn't go into any details, all it shows me is that I can configure tsoa to look for a `.ts` file, but what should be in that file?

**Comment by WoH** [comment]
Hi. Unfortunately we don't have any guides here yet, sorry about that.
For now, I can point you to https://github.com/lukeautry/tsoa/tree/master/src/routeGeneration, where the template folder contains all the handlebars templates tsoa ships with.

However, I think what you're looking for might not be route templates, which transform the metadata tsoa inferred from your code into the "glue code", that connects Controllers to HTTP requests.
Instead, you might be interested in what's called a client generator, which creates an API client based on the OpenAPI description tsoa creates when you run `tsoa spec`.
If that's indeed the case, I'd like to refer you to https://openapi.tools/#sdk, especially https://openapi-generator.tech which seems to be the most commonly used approach.

**Comment by Billy-** [comment]
I have found the https://github.com/lukeautry/tsoa/blob/master/src/routeGeneration/templates/express.hbs file and used it as reference. In the documentation it uses a `.ts` file in the example configuration, which is what threw me as I usually use `.hbs` extensions on handlebars template files.

I also was able to find all the data passed to the template with a simple `{{json this}}` at the root

**Comment by Limule** [comment]
Hi @Billy- 
Can you update the link https://github.com/lukeautry/tsoa/blob/master/src/routeGeneration/templates/express.hbs plz ?
I can't reach it =/
