### ISSUE TITLE
x-enum-varnames support

### ISSUE THREAD

**Issue by ml1nk** [lukeautry/tsoa#752]
OpenAPI Generator allows with the vendor extension [x-enum-varnames](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/templating.md#extensions) to name enum values. At least for numeric enums it would be very helpful to support this extension.

https://github.com/lukeautry/tsoa/pull/700 does not seem to help in this case.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
enum CorePermissionEnum {
    test = 0
}
```

should lead to

```json
"CorePermissionEnum": {
  "enum": [0],
  "x-enum-varnames": ["test"],
  "type": "number"
}
```

## Current Behavior

```ts
"CorePermissionEnum": {
  "enum": [0],
  "type": "number"
}
```

## Context (Environment)

Version of the library: 3.2.1
Version of NodeJS: 14.5.0

## Breaking change?

As it is not part of the standard but somewhat important for usable numeric enums it should probably be disabled by default and enabled through the spec-configuration.

**Comment by ml1nk** [comment]
I implemented it here:
https://github.com/PAAR-IT-GmbH/tsoa/commit/50d7eee3d3ec83024acca3cd1c17efe6011110c7

Additional tests are still missing, but i'm unsure where to add it.

**Comment by WoH** [comment]
@ml1nk Feel free to open the PR as is and I'll have a look. Probably the schema details and definition specs.

**Comment by nimloth05** [comment]
I think the documentation is not up to date, so foe someone coming here from google:

In your tsoa config file, support for `x-enum-varnames` can be enabled by setting `xEnumVarnames` to `true`. Like this:

tsoa.json:

    {
        ...
        "spec" : {
            "outputDirectory" : "build",
            "specVersion" : 3,
            "xEnumVarnames" : true
        },
    }
