### ISSUE TITLE
Programmatic routes generation don't expose the types as per docs

### ISSUE THREAD

**Issue by spaguette** [lukeautry/tsoa#758]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The types `ExtendedRoutesConfig` and `ExtendedSpecConfig` can be imported directly from `tsoa`, as the docs suggest here:
https://tsoa-community.github.io/docs/generating.html#programmatic

## Current Behavior

The types `ExtendedRoutesConfig` and `ExtendedSpecConfig` cannot be imported directly from `tsoa`, as the docs suggest.
Instead, they can be imported as 

```ts
import { ExtendedRoutesConfig, ExtendedSpecConfig } from 'tsoa/dist/cli'
```

though.

## Possible Solution

There are 2 possible solutions to the problem:
1) fix only the docs with the alternative import solution I mentioned above
2) fix the code so that it exports the mentioned types from the library correctly (probably preferred)

## Steps to Reproduce

1. Follow the docs and copy-paste the programmatic solution (https://tsoa-community.github.io/docs/generating.html#programmatic)
2. Try to compile TS file of the routes & spec generation 

## Context (Environment)

Version of the library: 3.2.1
Version of NodeJS: 12.16.1

- [x] Confirm you were using yarn not npm

## Detailed Description

The detailed proposed solution is the following:

* Export mentioned interfaces from https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/index.ts as well as the `runCli` command.

I can create a PR with this as well.

## Breaking change?

No

**Comment by spaguette** [comment]
This is still the case, so not stale

**Comment by WoH** [comment]
Are you sure this is happening on 3.2.1, not `master` or the 3.3 alpha?
I'm pretty sure we import this interface, but I forgot to check.

**Comment by spaguette** [comment]
I am following the documentation and the `ExtendedRoutesConfig` and `ExtendedSpecConfig` are not exported from the `tsoa` [main file](https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/index.ts), so I can't directly import them as [the docs suggest](https://tsoa-community.github.io/docs/generating.html#programmatic):
```
import {
  generateRoutes,
  generateSpec,
  ExtendedRoutesConfig,
  ExtendedSpecConfig,
} from "tsoa";
```

I could only import them from `tsoa/dist/cli` like the following:
```
import { ExtendedRoutesConfig, ExtendedSpecConfig } from 'tsoa/dist/cli'
```

This is not really a big issue, just a little discrepancy with the docs
