### ISSUE TITLE
 It is not possible to provide examples for @Response if you are using @Res to return responses.

### ISSUE THREAD

**Issue by NicholasKuchiniski** [lukeautry/tsoa#759]
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

It is expected that it will be possible to use @Res and @Response, with examples, at the same time.

```ts
@injectable()
@Route("/v1/users")
@Tags("Users")
export class CreateUserRoute extends Controller {
  @inject(Mediator)
  private readonly mediator!: Mediator;

  /**
   * Create a new user and return it if user was created successfully and was returned with his ID.
   */
  @Response<CreateUserCommandHandlerResultError>(
    503,
    "It was not possible to communicate with any external service needed to perform the action.",
    {
      event: ApplicationEvents.SERVICE_UNAVAILABLE,
      data: "Service unavailable",
    },
  )
  @SuccessResponse(201)
  @Post()
  public async createUser(
    @Body() data: CreateUserCommand,
    @Res() created: TsoaResponse<201, CreateUserCommandHandlerResultSuccess>,
    @Res() serviceUnavailable: TsoaResponse<503, CreateUserCommandHandlerResultError>,
  ): Promise<void> {
    const command = new CreateUserCommand(data);
    const result = await this.mediator.send(command);

    if (result instanceof CreateUserCommandHandlerResultError) {
      serviceUnavailable(503, result);
    }

    if (result instanceof CreateUserCommandHandlerResultSuccess) {
      created(201, result);
    }

    return;
  }
}
```
In this route, i should be able to generate swagger documentation with the example i provided, but, if the @Response contains the same status as the @Res used for return it, the example dont appear at the swagger file.

Change the status used in @Res @Response solves the bug, so i think that is something between this two decorators.

## Current Behavior

When i use the same status used on @Res on @Response, the swagger generated does not have a example, if i use different statuses, it appears.

## Steps to Reproduce

I using tsoa on a study personal project that can be seen on https://github.com/NicholasKuchiniski/animestream-api, to reproduce this bug is necessary change the line 27-30 on ``src/interfaces/api/users/create-user-route.ts`` to

```ts
  @Response<CreateUserCommandHandlerResultError>(
    503,
    "It was not possible to communicate with any external service needed to perform the action.",
    {
      event: ApplicationEvents.SERVICE_UNAVAILABLE,
      data: "Service message",
    },
  )
```
If you run yarn spec:routes or yarn run tsoa spec-and-routes, you can notice that the generated swagger does not have the examples. Then if you change the @Response status code to something else, like 500 (in the @Res or @Response) it appears.

## Context (Environment)

Version of the library: 3.2.1
Version of NodeJS: 13.14.0

- Confirm you were using yarn not npm: [X]

**Comment by WoH** [comment]
Examples for `@Res` responses are declared within JSDoc, just like other Parameter Examples.
