### ISSUE TITLE
Are multiple swagger version documents supported

### ISSUE THREAD

**Issue by eric-caslake** [lukeautry/tsoa#769]
I am looking to support multiple version of the same API endpoint with TSOA.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Detailed Description

I have looked through the documentation but cannot find anything that talks about supporting multiple versions of the same API endpoint within the same Node express application.  Can it be done?

**Comment by WoH** [comment]
Yes, but we don't make any assumptions on how you want to do it.
