### ISSUE TITLE
getHeaders function return empty json

### ISSUE THREAD

**Issue by fans3210** [lukeautry/tsoa#773]
## Sorting

- **I'm submitting a ...**

  - [* ] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [ *] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Should be able to print the header in controller

## Current Behavior

This is a piece of code in my controller. Although I've already passed header in postman, I'm still getting empty json for the this.getHeaders() function
```
    @Get('jobs')
    @Header('aaa')
    async getJobs(): Promise<any> {
        console.log('headers:');

        console.log(this.getHeaders());
        return JenkinsHelper.getJobs();

    }

**Comment by jackey8616** [comment]
`Controller#getHeader` and `Controller#getHeaders` method is use in tsoa not for developer.  
It responsible for insert headers into response.
You can check [here](https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/routeGeneration/templates/express.hbs#L153,L157) and [here](https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/routeGeneration/templates/express.hbs#L169,L171).  

The code you gave has one incorrect usage: `Header` is a parameter decorator.
```ts
@Get('jobs')
async getJobs(@Header() aaa: string): Promise<any> {
   ...
}
```

If you want to get header inside controller method, you can use `Request` decorator like:
```ts
import { Request as exRequest } from 'express';
...
@Get('job')
async getJobs(@Request() req: exRequest): Promise<any> {
  console.log(req.headers); // All headers
  console.log(req.header('aaa')) // Get aaa header
}
```
