### ISSUE TITLE
Add support for importing types from an external dependency

### ISSUE THREAD

**Issue by PeledYuval** [lukeautry/tsoa#774]
Hi, this is a feature request and/or opinion about design decisions, so please forgive me for not sticking to the bug report template.

This issue was discussed as "bug-reports" before, I opened a new Issue to have a centralized location to discuss the design decision.

Before I delve into the details I'd like to say that I love this library and appreciate the contributors' invested time into it. tsoa helped me to bootstrap high-quality REST APIs quickly many times! On that note, if we can come to an agreement about the design of this issue I would be more than willing to help implement it.

## TL:DR
Currently tsoa is not compatible with usage in a microservice/monorepo environment since you cannot import a shared type definition file.

Rebuttal to the current design decision justification:
1. Performance hit - will be on the scale of milliseconds even for a big code base, which is not a big issue for a compile-time tool.
2. Allows for bad REST API practices - I don't think tsoa should make design decisions for its users. Also, I think the current decision *exposes* tsoa users to public API breakages in certain use cases.

I suggest adding support for importing type definition files. It could also be done as a CLI flag that comes with warning if the maintainers don't think it should be allowed by default (`--allowExternalImports` ?). 
I would be happy to help add this feature.

## Background
This issue is regarding the design decision not to support importing Typescript definitions from external dependencies (node_modules).
Here are related threads from users who expected this to be supported: 
https://github.com/lukeautry/tsoa/issues/340
https://github.com/lukeautry/tsoa/issues/377
https://github.com/lukeautry/tsoa/issues/334
https://github.com/lukeautry/tsoa/issues/205

As I understand, @dgreene1 has two main reasons for this not to be supported:
1. Importing external dependencies has a performance price (due to having to traverse the file system all the way to the root for each external import since node_modules can be in any parent folder)
2. Importing external dependencies is a sign of bad API implementation: it means that a change in a dependency would change the the public API and that should be avoided.

While I agree that both of these points are valid and need to be addressed, I believe there are use cases where the points are irrelevant and are actually a deal breaker for using tsoa.

### Description
We have a "search" service that receives a search query and returns matching objects.

Internally, the search service is actually composed of (at least) 2 services calling each other - a "search query" service that takes the search query, filters the object IDs that match the query, and calls a "data" service that takes object IDs and returns the full object. Finally, the "search query" service returns the full objects.

Since the "search query" service and the "data" service return objects with the same shape (the "search query" service can be thought of as a proxy of sorts here), they share the same response type definition. Importantly, I don't mean that they _import_ the same file (even though they do), I mean it in a logical sense - our architecture was defined in a way that the "search query" service does not care about the shape of the "data" service's response, other than that it exposes that shape to the external user.
  
We use a monorepo. "search query" service and "data" are different packages, and they both import a 3rd shared "type definition" package that contains the Response type definition file. 

For a public user - this is transparent. There is one service that receives query parameters and returns a full object with query results.

### Bottom line
Since tsoa does not support importing type definitions file from an external source, this is a deal breaker for usage in a monorepo microservice environment.

I can talk about _why_ we split these services and _why_ we use a monorepo for this, but I don't think this is an area you, as tsoa maintainers, should want to have an opinion about - this is in the realm of microservice architecture, while tsoa is mainly about generation of a single openAPI-compliant REST API service.

I don't think these are mutually exclusive, but due to the current design decision they are.

### Performance issue
This is a true problem - traversing the file system tree will definitely hurt performance. However, I believe that the impact to performance is minimal, and will be completely accepted by developers. 

1. Actual impact to performance: I ran a test that checks how much time it takes to "require" 100 different non-existing dependencies (which makes Node traverse the entire file structure 100 times). I ran the test in a directory that's 11 directories deep into the file system. I think you would agree that's a much more complex scenario than a normal use case. I ran this test 100 times to make sure I get a good average and worst result. The results were an average of 26ms and max of 65ms. You can find the (very hacky) code [here](https://gist.github.com/PeledYuval/b99669b136cbe2953da475607eea64fc).
2. Compile time tools that accept this performance hit are ubiquitous and super popular. See: Typescript, ESLint, prettier, and many many more.

I think as a compile-time library, performance is very important to take into account. However, in this particular case, imports do not have such high performance cost.

### Public API design breakage
The gist of this justification is that if I rely on some external dependency's object shape, and that external dependecy's object shape changes, then my own API changes.
I believe that sometimes that is a bad thing (for example, when there's a missing abstraction like [your own readme](https://github.com/lukeautry/tsoa/blob/0f5176d1187752901693dfc48e72353a6adc777a/docs/ExternalInterfacesExplanation.MD) explains beautifully).
However, sometimes the imported type definition **is** the abstraction. For an example, read our use case as described above.
Changing a public API is indeed something that needs to be thoroughly thought over as it does have ramifications for public users. But it does happen! We will deprecate a field every once in a while. I don't think tsoa should take those decisions. I don't think it does - tsoa doesn't compare the current type definitions to the previously committed ones and warns of breaking changes (even thought that would be a really cool feature!). The only place where tsoa has an opinion on this is related to external dependencies. 

Further, I believe your very own readme suggests something **dangerous** - copying the same interface to two different places can cause runtime breakages (not due to mismatched type _names_, which you explain don't matter, but due to mismatched type _definitions_). This solution is not type safe for generic functions, such as most functions that cross a network boundary (like Axios).

In the example described in our use-case, "search-query" service calls "data" service using Axios to perform an HTTP request. Axios receives the response type as a generic parameter: `const respone = axios.get<ResponseType>(url)`.
If ResponseType is duplicated across "search-query" and "data" services, and "data" service changes its response type, then we could:
1. Run into runtime errors issues in "search-query" because we forget to update the response type in both places
2. Even if there are no run time errors, the generated openAPI definition for "search-query" would be wrong - it would be unaware of the change made to "data" query. In this case, the public API exposed to users changed but the documentation didn't!

The main reason for us deciding to go for a monorepo with a shared "types" package is to avoid this issue. If they share a package, I cannot make a breaking change to the response type without addressing it in both services.

## Thank you
I know this is a huge post, so thank you for reading it. I believe the current design decision will be a deal breaker for many people. I care for this library, and (again) want to state my appreciation for the maintainers so I wanted to show why I think this is the wrong direction and if so agreed, help take a better one.

Let's discuss this!

**Comment by WoH** [comment]
> Currently tsoa is not compatible with usage in a microservice/monorepo environment since you cannot import a shared type definition file.

This is incorrect and I am aware of lerna/monorepo setups that use tsoa. However, as you mentioned, we ususally don't encourage pulling external types in by default as there may be inintended consequences that may require a deeper understanding of tsoa.

As the rest of the issue somewhat builds on this assumption, I don't think it makes a lot of sense to continue analyzing the rest of the argument.

**Comment by WoH** [comment]
However, I think there's a lot of space for a discussion on how we could approach better documentation on how to correctly set up a tsoa project in a monorepo context, with or without yarn workspaces (main issue here seems to be correctly configuring TypeScript paths as TS itself seems (?) to be promoting the exclusion of these type definitions provided by dependencies from your project, which means tsoa can't access the declarations required).

**Comment by PeledYuval** [comment]
> > Currently tsoa is not compatible with usage in a microservice/monorepo environment since you cannot import a shared type definition file.
> 
> This is incorrect and I am aware of lerna/monorepo setups that use tsoa. However, as you mentioned, we ususally don't encourage pulling external types in by default as there may be inintended consequences that may require a deeper understanding of tsoa.
> 
> As the rest of the issue somewhat builds on this assumption, I don't think it makes a lot of sense to continue analyzing the rest of the argument.

Please excuse my phrasing before, it was a little confusing. But I think it's the other way around. What I said is not an _assumption_, it's a _conclusion_ derived from the fact that this feature is unsupported. It's not that the rest of the argument builds on that assumption, it's that the rest of the argument supports that conclusion.
 
Maybe a more precise way to phrase it would be: tsoa is not compatible with microservices sharing a single type definition without duplication of code.

If my conclusion is wrong and there's a way to configure TS in a way that makes it possible to have 2 separate tsoa-based REST APIs share a type configuration without code duplication - please let me know! 

Otherwise, I would be very happy if we could focus on the arguments themselves, I feel like closing this discussion due to disagreement about its conclusion is like not having a discussion at all.

**Comment by WoH** [comment]
> Am I understanding correctly that tsoa does indeed support importing external dependencies? It's just a matter of subtle Typescript configuration? If so, then my conclusion is wrong and there's a way to configure TS in a way that makes it possible to have 2 separate tsoa-based REST APIs share a type configuration without code duplication - please let me know!

tsoa mostly defers to the TypeScript Compiler APIs to create the Program. Therefore, all declarations that are part of the program (according to your TS config) can be traversed by tsoa. I'm obviously skipping a lot of details and steps in between here, but for the end user that means that you can share your types.

**Comment by PeledYuval** [comment]
Thank you for your answers. Something big is still missing here - all signs point to "this can't be done" and you say that it can...

I understand this is possible on a potential level. my impression was that currently there's a design decision and a specific check in the code not to allow this - as evident by the readme [here](https://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD), by the issues I've linked and by the error message I get when trying generate routes that use an externally imported type: 
```
There was a problem resolving type of 'FindResponse'.
Generate routes error.
 Error: No matching model found for referenced type ProviderType. If ProviderType comes from a dependency, please create an interface in your own code that has the same structure. Tsoa can not utilize interfaces from external dependencies. Read more at https://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD
```

If importing an external type is possible - can you please share how?
If it isn't possible and the maintainers don't want this to be possible - this issue was created to open a discussion about this.
If it isn't possible and the maintainers do want this to be possible - I'd love to help contribute.

**Comment by jacobdr** [comment]
@PeledYuval This is the workaround that our team uses to get external types (and mono repos) to work: Add the modules to the tsoa.json compilation context. 

For monorepos, this usually just means changing the rootDir property of tsconfig to `"rootDir": "..",` -- so that resolves to `ROOT/packages/` instead of your usual `ROOT/packages/my-single-lerna-package`.

From here, you can then use the tsconfig paths if you want -- we do a mapping here to convert our `@foobar/module-1` imports.

For example:

```json
paths: {
    "@foobar/module-1": ["../module-1/src"]
}
```

For types themselves, you can continue to mess with the paths and including the node_modules you want into the compilation context. 

Is this clean? No. But its a workaround, and liable to break. 

I think that a version 4 of this repo might want to consider more "official" support, but for now I think its quite reasonable to respect the authors' philosophies.

At the end of the day, the duplication of vendoring in an external interface from a library is FAR more palatable than generating swagger files by hand IMO

**Comment by WoH** [comment]
Pushing the root up which is awkward, I'd agree with that. If you bring the other types in via yarn workspaces and you can avoid that aswell

**Comment by PeledYuval** [comment]
Thank you guys for the replies - I fixed this issue, it was 100% a problem on my end. I simply did not run "build" on the imported package, so the compiler could not find the imported file - it was simply missing.

My bottom line here is that tsoa just works out of the box for external dependencies!

However, the error message is probably a historical vestige from when tsoa did not support this? The error message "Tsoa can not utilize interfaces from external dependencies" is wrong and should be changed.

I'm closing this issue, thank you guys for taking the time to help me!

**Comment by fx-adr** [comment]
Hi everyone, 
I've been having this problem too - we have a repository for all of our TS types and use them throughout different services that require them and communicate with each other. Having to recreate the structure of each request-response pair across the client and server was becoming difficult, especially when using union types.

Initially the tsoa routes/oas builder couldn't resolve structures from dependencies, however I was able to 'ground' the dependency's type into the current project by using this 'clone type' helper.

```
// dependency
const possibleSlugs = ['this', 'that'] as const;
export type Something = typeof possibleSlugs[number];


// CloneType.ts
export type CopyType<X, Y, Tr, Fl> = (<T>() => T extends X ? 1 : 2) extends <
  T
>() => T extends Y ? 1 : 2
  ? Tr
  : Fl;

export type CloneType<T> = CopyType<T, T, T, never>;


// myController.ts
type ClonedSomething = CloneType<Something>;
type MyExampleResponse = {
    foo: ClonedSomething; // OAS is spec is built, field is an enum of [ 'this', 'that']
}
```
However there are some limitations and I haven't yet tried to use full DTO types from dependencies - only those 'enum style' types where the data is hard coded for now. I think there is some weirdness to - where the cloned type can't be imported into the *Controller.ts with the name of the original type, but still allows you to reuse types from dependencies.

**Comment by talfreds** [comment]
> Hi everyone, I've been having this problem too - we have a repository for all of our TS types and use them throughout different services that require them and communicate with each other. Having to recreate the structure of each request-response pair across the client and server was becoming difficult, especially when using union types.
> 
> Initially the tsoa routes/oas builder couldn't resolve structures from dependencies, however I was able to 'ground' the dependency's type into the current project by using this 'clone type' helper.
> 
> ```
> // dependency
> const possibleSlugs = ['this', 'that'] as const;
> export type Something = typeof possibleSlugs[number];
> 
> 
> // CloneType.ts
> export type CopyType<X, Y, Tr, Fl> = (<T>() => T extends X ? 1 : 2) extends <
>   T
> >() => T extends Y ? 1 : 2
>   ? Tr
>   : Fl;
> 
> export type CloneType<T> = CopyType<T, T, T, never>;
> 
> 
> // myController.ts
> type ClonedSomething = CloneType<Something>;
> type MyExampleResponse = {
>     foo: ClonedSomething; // OAS is spec is built, field is an enum of [ 'this', 'that']
> }
> ```
> 
> However there are some limitations and I haven't yet tried to use full DTO types from dependencies - only those 'enum style' types where the data is hard coded for now. I think there is some weirdness to - where the cloned type can't be imported into the *Controller.ts with the name of the original type, but still allows you to reuse types from dependencies.

Tried this since it allows the app to compile but it loops endlessly when actually calling the endpoint. Guess I need to reproduce this in a demo project and create a new issue. 😢 

```
"stack": "RangeError: Maximum call stack size exceeded
   at ValidationService.ValidateParam ({ROOT}\node_modules\@tsoa\runtime\src\routeGeneration\templateHelpers.ts:71:23)
   at ValidationService.validateModel ({ROOT}\node_modules\@tsoa\runtime\src\routeGeneration\templateHelpers.ts:654:21)
```
