### ISSUE TITLE
 Error: Couldn't resolve literal node: null since typescript 4.x

### ISSUE THREAD

**Issue by simllll** [lukeautry/tsoa#778]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I'm not quite sure about the nature of this "bug". I  found several tickets regarding "nullable" and co, but as this just popped up on our side since we upgraded to ts 4.x it seems it is a tleast not directly related.

The first question therefore would be:
Should something like this be possible:
interface IInterviewQuestion {
        ....
	moduleOptions?: { [key: string]: string | number | boolean | null };
        ...
}

I'm refering to the "null" here, we just recently changed this from undefined to null.

But now we get this error:
There was a problem resolving type of 'IInterviewQuestion'.
There was a problem resolving type of 'IStartInterviewResultDTO'.
Generate routes error.
 **Error: Couldn't resolve literal node: null**
    at new GenerateMetadataError (/home/simon/Dev/hokify/hokify-server/node_modules/tsoa/dist/metadataGeneration/exceptions.js:22:28)

Should this work? Or is null still unsupported?
see:
- https://github.com/lukeautry/tsoa/issues/479
- https://github.com/lukeautry/tsoa/pull/670
- https://github.com/lukeautry/tsoa/pull/601

## Current Behavior

It's not working with typescript 4.0.2

## Context (Environment)

Version of the library: 3.2.1

Version of NodeJS: v12.18.3

**Comment by simllll** [comment]
Alright, very good news :-) I just tested it with tsoa 3.3.0-alpha.0 and the issue seems to be gone :partying_face:

**Comment by simllll** [comment]
I'll keep it open till a new release is out :)

**Comment by WoH** [comment]
Assuming this is fixed now, will reopen if the issue remains.
