### ISSUE TITLE
Fix "Cannot read property 'kind' of undefined" error related to missing NodeBuilderFlags.NoTruncation

### ISSUE THREAD

**Issue by jookshub** [lukeautry/tsoa#781]
## Sorting

- **I'm submitting a ...**

  - [ x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [ x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit **- and solved**

## Expected Behavior

```ts
  @Get('abridgedObject')
  public async abridgedObject() {
    return {
      demo01: '',
      demo02: '',
      demo03: '',
      demo04: '',
      demo05: '',
      demo06: '',
      demo07: '',
      demo08: '',
      demo09: '',
      demo10: '',
      demo11: '',
      demo12: '',
      demo13: '',
      demo14: '',
      demo15: '',
      demo16: '',
      demo17: '',
      d: ''
    }
  }
```
This should not break ```tsoa swagger```or ```tsoa routes```.

## Current Behavior

See https://github.com/lukeautry/tsoa/issues/749 and possibly https://github.com/lukeautry/tsoa/issues/681

TSOA is not using ```ts.NodeBuilderFlags.NoTruncation``` which leads to issues like those mentioned or like the following:

```ts
TypeError: Cannot read property 'kind' of undefined
    at TypeResolver.getPrimitiveType (/Users/jook/tsoa/src/metadataGeneration/typeResolver.ts:336:70)
    at TypeResolver.resolve (/Users/jook/tsoa/src/metadataGeneration/typeResolver.ts:39:32)
    at /Users/jook/tsoa/src/metadataGeneration/typeResolver.ts:104:127
    at Array.reduce (<anonymous>)
```

## Possible Solution

See working patch: https://github.com/lukeautry/tsoa/compare/master...cellular:feature/patch_truncation_issue_781

I am working on creating/submitting a PR based on it.

## Steps to Reproduce

1. checkout  https://github.com/lukeautry/tsoa/compare/master...cellular:feature/test_truncation_issue_781
2. run ```yarn build```
3. run ```yarn test```
4. see failing test
5. delete ```d: ''``` from the return object of the ```abridgedObject``` function
6. run ```yarn test```
7. see working test

## Context (Environment)

Version of the library: 3.2.1
Version of NodeJS: 12.18.2

- Confirm you were using yarn not npm: [x]

## Detailed Description

Thanks to the intel of @fantapop (https://github.com/lukeautry/tsoa/issues/749#issuecomment-686312060) and microsoft/TypeScript#26238 (comment) I was able to determine the cause of the truncation to be a missing ```ts.NodeBuilderFlags.NoTruncation``` flag in some of the TS functions used by ```tsoa```.

With this flag in place, the output of TS won't be truncated.

## Breaking change?

This change might lead to a different output of ```tsoa```, however this should not result in regressions and if so, due to errors which were silent otherwise.

**Comment by WoH** [comment]
Can you open the PR for this?
