### ISSUE TITLE
How to construct an endpoint for file upload using multer

### ISSUE THREAD

**Issue by Edwardchorius** [lukeautry/tsoa#782]
As far as I understood from the existing issues dating 3 years back from this day, there is still not a properly documented way to construct an api, using TSOA to receive files via HTTP.
Can somebody guide me to how they managed to do this, even if it's a hacky way?

**Comment by WoH** [comment]
[Duplicate](https://github.com/lukeautry/tsoa/issues/93#issuecomment-690998995) and documented [here](https://tsoa-community.github.io/docs/file-upload.html)

**Comment by calvinwyoung** [comment]
I can confirm that the documented solution works fine. But out of curiosity, are there any plans to support uploading files without having to manually overwriting the generated OpenAPI definition?

**Comment by WoH** [comment]
Not sure if I understand correctly, do you have any plans to propose and implement an API?
