### ISSUE TITLE
A union of unions is returning an empty object in swagger generation

### ISSUE THREAD

**Issue by gdspicer58** [lukeautry/tsoa#785]
When generating swagger based off a union of string unions, the union of unions is being typed as an object. Example below

```ts
type AType = 'A' | 'a'
type BType = 'B' | 'b'
type AOrBType = AType | BType

class LetterType {
	@field theB: BType

	@field theA: AType

	@field aOrB?: AOrBType
}
```

this renders the below swagger.json

<img width="321" alt="Screen Shot 2020-09-14 at 1 13 10 PM" src="https://user-images.githubusercontent.com/51673884/93122461-1ec06100-f68c-11ea-8458-048151d2ca7b.png">

It would be more preferable if aOrB had `type: string` and `enum: ["A", "a", "B", "b"]`

## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [X] feature request
  - [ ] support request

(not sure which of the two above you would classify this as)

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

I searched all issues with "Union" in their titles

## Expected Behavior

The swagger generation should enumerate all of the literals in the given union

```json
LetterType: {
  properties: {
    theB: {
      type: "string",
      enum: [
        "B",
        "b"
      ]
    },
    theA: {
    type: "string",
      enum: [
        "A",
        "a"
      ]
    },
    aOrB: {
    additionalProperties: true,
    type: "string",
      enum: ["A", "a", "B", "b"]
    nullable: true
    }
  }
}
```

```ts
type AType = 'A' | 'a'
type BType = 'B' | 'b'
type AOrBType = AType | BType

class LetterType {
	@field theB: BType

	@field theA: AType

	@field aOrB?: AOrBType
}
```

## Current Behavior

```json
LetterType: {
properties: {
theB: {
type: "string",
enum: [
"B",
"b"
]
},
theA: {
type: "string",
enum: [
"A",
"a"
]
},
aOrB: {
additionalProperties: true,
type: "object",
nullable: true
}
},
```

Or you have to do this below, which is not nice when you have many string union types and you do not want to have to update one in all of its places

```ts
type AType = 'A' | 'a'
type BType = 'B' | 'b'
type AOrBType = 'A' | 'a' | 'B' | 'b'

class LetterType {
	@field theB: BType

	@field theA: AType

	@field aOrB?: AOrBType
}
```

## Possible Solution

recursively check union types and merge them together at the top level (not sure if this is possible using your implementation or not)

## Steps to Reproduce

copy/paste above code and run own swagger generation

## Context (Environment)

Version of the library: 2.5.13
Version of NodeJS: 10.16.3

- Confirm you were using yarn not npm: [X]

## Detailed Description

See above

## Breaking change?

No

**Comment by WoH** [comment]
tsoa 2 has limitations around interference of type aliases. Feel free to try this with tsoa 3+ and I might reopen this is the issue persists.
