### ISSUE TITLE
entryFile should be optional if controllerPathGlobs is given

### ISSUE THREAD

**Issue by letmaik** [lukeautry/tsoa#786]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

`"entryFile"` and `"controllerPathGlobs"` in `tsoa.json` should be mutually exclusive such that only one of them must be given.

## Current Behavior

Both `"entryFile"` and `"controllerPathGlobs"` are required. I currently provide an empty TS file as entry file and everything still works.

## Possible Solution

Allow `entryFile` to be empty if `controllerPathGlobs` is given.

## Steps to Reproduce

See above.

## Context (Environment)

Version of the library: 3.3.0-alpha.0

**Comment by lukeautry** [comment]
@letmaik I think this is a pretty easy thing to tackle here: https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/cli.ts#L148

If I understand, we just need to check here if there's been no entryFile OR controllerPathGlobs, and throw an error. Probably adjusting the error message appropriately.
