### ISSUE TITLE
Returns "invalid object" when req.body.__proto__ is stripped

### ISSUE THREAD

**Issue by patrickgalbraith** [lukeautry/tsoa#791]
I get "invalid object" when req.body is a plain Object without `__proto__`. I'm guessing something is stripping `__proto__` in my project which breaks `tsoa`. For reference I'm doing a partial migration to `tsoa` from an older codebase.

But I imagine it should still work since stripping this from the body seems like a common security fix.

## Sorting

  - [x] bug report

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submitted

## Possible Solution

Seems like this line https://github.com/lukeautry/tsoa/blob/0b45240d386e7760edbf84933093518696453d0b/packages/runtime/src/routeGeneration/templateHelpers.ts#L639 checks if req.body is `instanceof Object` whereas I imagine it should just check that it is `typeof 'object'`.

## Context (Environment)

Version of the library: v3.2.1
Version of NodeJS: v14.8.0
Express: v4.17.1
Body-Parser: v1.19.0

**Comment by aerabi** [comment]
I'll try to fix it.

**Comment by aerabi** [comment]
So, as far as I tested, the mentioned function [`validateModel`](https://github.com/lukeautry/tsoa/blob/0b45240d386e7760edbf84933093518696453d0b/packages/runtime/src/routeGeneration/templateHelpers.ts#L624) accepts any object as `value`, and does not fail if the object is plain (missing `__proto__`). :thinking:

**Comment by patrickgalbraith** [comment]
@aerabi here is an example of how to reproduce (add the following to `app.ts`:

```
export const app = express()

// Use body parser to read sent json payloads
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({
    extended: false
}))

app.use((
    req: express.Request,
    _res: express.Response,
    next: express.NextFunction
) => {
    Object.setPrototypeOf(req.body, null)
    next()
})

RegisterRoutes(app)
```

Then create a test controller like this:

```
export type TestRequestObject = {
  id: number
  email: string
  name: string
  status?: "Happy" | "Sad"
  phoneNumbers: string[]
}

export class TestController extends Controller {
  @Post('object')
  public async createObject(
    @Body() requestBody: TestRequestObject
  ): Promise<void> {
    console.log(requestBody)
    return
  }
}
```

And call like so:

```
POST http://localhost:5000/tests/object HTTP/1.1
content-type: application/json

{
    "id": 1,
    "email": "test@test.com",
    "name": "Test",
    "status": "Happy",
    "phoneNumbers": ["123213213", "324324234"]
}
```
