### ISSUE TITLE
Looking for a way to add options path for pre-flight requests 

### ISSUE THREAD

**Issue by UnlimitedX** [lukeautry/tsoa#795]
Hi there!
I'm working with the AWS infrastructure and I need to add an "option" method route for CORS policy purposes. 
And, I can't find a way to add an _options_ path to the generated swagger file.

Here is what we need to add:
![image](https://user-images.githubusercontent.com/6625963/94274752-5bbb0c00-ff46-11ea-9926-6e64ef70b46d.png)

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

We should be able to use a decorator or maybe modify the tsoa.json file to add _options_ for the paths we need.

This is the output we are expecting in our swagger.json file.

```yaml
"options" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "responses" : {
          "200" : {
            "description" : "200 response",
            "headers" : {
              "Access-Control-Allow-Origin" : {
                "type" : "string"
              },
              "Access-Control-Allow-Methods" : {
                "type" : "string"
              },
              "Access-Control-Allow-Headers" : {
                "type" : "string"
              }
            }
          }
        },
        "x-amazon-apigateway-integration" : {
          "type" : "mock",
          "responses" : {
            "default" : {
              "statusCode" : "200",
              "responseParameters" : {
                "method.response.header.Access-Control-Allow-Methods" : "'OPTIONS'",
                "method.response.header.Access-Control-Allow-Headers" : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-transaction-id'",
                "method.response.header.Access-Control-Allow-Origin" : "'*'"
              }
            }
          },
          "requestTemplates" : {
            "application/json" : "{\"statusCode\": 200}"
          },
          "passthroughBehavior" : "when_no_match"
        }
      }
```

## Current Behavior

It's not possible - or I don't know how - to generate "options" routes for the generated swagger file.

## Possible Solution

I'm trying to figure out what the best approach would be but the options method does not seem to exist (I only found GET,POST,PUT,DELETE,PATCH and Head)
![image](https://user-images.githubusercontent.com/6625963/94275207-f7e51300-ff46-11ea-941a-8c3b01dee3b0.png)

Any suggestion?

## Context (Environment)

Version of the library: 3.2.1
Version of NodeJS: v13.11.0

- Confirm you were using yarn not npm: [ ]
Using NPM

**Comment by WoH** [comment]
Would be happy to see a PR for that. I don't see a reason to not add a `@Options()`  decorator + parser (also applies to any other [method OpenAPI allows](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#fixed-fields-7) that we don't support yet), so we have parity with OpenAPI.
