### ISSUE TITLE
Add @Session annotation to inject Express.Session

### ISSUE THREAD

**Issue by filiplindqvist-netlight** [lukeautry/tsoa#797]
Would like to have `@Session` as a parameter annotation for controllers. 

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
public async getFunction(@Session() session: Express.Session): Promise<MyResponse> {
    ...
}
```

## Current Behavior

```ts
public async getFunction(@Request() req: ExpressRequest): Promise<MyResponse> {
    const session = req.session
    ...
}
```

## Possible Solution

Add the annotation. 

## Steps to Reproduce

1. Install `express-session` package
2. Try to get session from request. 

## Detailed Description

Session is from express-session package, not sure how this complicates implementation.

## Breaking change?

Not a breaking change.

**Comment by filiplindqvist-netlight** [comment]
I just realised that one could potentially do this: 
`@Request() { session }: ExpressRequest`
And be quite happy.

**Comment by WoH** [comment]
I'd suggest implementing your own decorator that maps to a user or a session so you can i.e. ask for `@Request() @InjectSession() session: ExSession` or `Request() @InjectUser() user: User` in your handler. 

As there are many approaches to auth, I don't think tsoa should add a Decorator for each one of them, esp. when we consider that tsoa makes no assumptions as to what you do in the auth function.

**Comment by sdoward** [comment]
@WoH I like your suggestion but I am struggling to find anything in the docs. How would I go about this?
