### ISSUE TITLE
Define custom Routes template

### ISSUE THREAD

**Issue by cadriel** [lukeautry/tsoa#80]
The ability to expose a custom route template would be fantastic. Currently, the route generation isn't completely ideal for us - so giving users control over the handlebars template would be beneficial.

The added advantage of this is you could then define your own middleware against the routes in any order, among other things.

**Comment by lukeautry** [comment]
Fixed with #81

**Comment by anzemur** [comment]
Could you please provide an example of defining custom route template and wiring middleware into the route?

Thank you.

**Comment by cadriel** [comment]
I'm not completely sure where the project is now.. but after my merge there were examples in-place I think.
