### ISSUE TITLE
expressAuthentication with IoC

### ISSUE THREAD

**Issue by jeremyVignelles** [lukeautry/tsoa#801]
Hi,
I'm starting using tsoa for the generation of my APIs, and everything went fine until now, including the integration with `inversify`.

But now, I'm trying to implement the authentication and I'm facing an issue:

My authentication/authorization is delegated to a service I registered in my IoC container, and I'd like to inject it so I could call something like:

```ts
authorizationService.verify(token);
```

Is there a way to achieve this?

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Being able to inject services from the IoC container

## Current Behavior

If there is a way, I don't know it

## Possible Solution

Something like this would be great
```ts
export function expressAuthentication (request: Request, securityName: string, scopes?: string[], @inject(TYPES.Authorization) authorizationService: AuthorizationService): Promise<UserModel> {
```

## Steps to Reproduce

1. Create a new tsoa project
2. Follow the instructions from https://tsoa-community.github.io/docs/di.html#inversifyjs to create a DI system
3. Follow the steps from https://tsoa-community.github.io/docs/authentication.html to create the `authentication.ts` file
4. Inject something from the DI to the `authentication.ts` file, how ?

## Context (Environment)

Version of the library: 3.2.1
Version of NodeJS: 12

- Confirm you were using yarn not npm: [ ] (I don't because that's a legacy project, but I don't think this is related)

## Detailed Description

The `expressAuthentication` function should be able to take as a parameter either:
- The DI container, if any is provided
- The injected object, if possible to read the `@inject()` annotations.

## Breaking change?

Adds a parameter to `expressAuthentication` (and possibly also koa etc...)

**Comment by jeremyVignelles** [comment]
I found a workaround:

in my `authentication.ts` file:

```ts
import { iocContainer } from './inversify.config';
```

then, I can use `iocContainer.get<AuthenticationService>(TYPES.AuthenticationService)` to get my service and use it.

But this feels like an antipattern to me to depend on the iocContainer...

**Comment by WoH** [comment]
This is the way to do it. The idea or ioc is to only depend on the container. Unfortunately the API you suggested doesn't really work out (decotators on function parameters).
