### ISSUE TITLE
Control flow when using typechecked alternate responses

### ISSUE THREAD

**Issue by letmaik** [lukeautry/tsoa#815]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

I'm trying to understand how [https://tsoa-community.github.io/docs/error-handling.html#typechecked-alternate-responses](typechecked alternate responses) work. The example from the docs is:

```ts
  @Get('/')
  public async greet(@Query() name?: string, @Res() notFoundResponse: TsoaResponse<404, { reason: string }>): Promise<string> {
    if (!name) {
      notFoundResponse(404, { reason: "We don't know you yet. Please provide a name" });
    }

    return `Hello, ${name}`;
  }
```

If `notFoundResponse` is invoked, what happens exactly? Won't the function continue to run after that? The only way to avoid that is if  `notFoundResponse` would throw an exception, but I couldn't find relevant code that does that.

**Comment by WoH** [comment]
We send the response to the client, and your code keeps running unless you `return nFR()`.  This is intentional so you can do whatever you want to do after sending.
In your case, you'd try another response, which is not possible as the response is already sent out, so it'll be ignored (by express).

**Comment by letmaik** [comment]
Thanks, I see. `notFoundResponse` returns `any` as type, therefore it works out. I think not returning is a quite unusual case though, or am I missing something? I think it would make more sense to change the docs to have the `return ..` style.

**Comment by WoH** [comment]
I agree
