### ISSUE TITLE
Provide option to append additional yaml to output

### ISSUE THREAD

**Issue by BradenCTC** [lukeautry/tsoa#817]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ X] feature request
  - [ ] support request

- I confirm that I
  - [X ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Context (Environment)

Version of the library: ^3.3.0
Version of NodeJS: 12.16.3

- Confirm you were using yarn not npm: [npm ]

## Detailed Description

In my project, some of my controllers are implemented in a separate project and imported as a npm package. I would like the ability to either import the yaml for these controllers through the tsoa.json so that is appended to our resulting yaml, or I would like the ability to reference the controllers in my node_modules folder somehow. Perhaps there is already some way to do this?

**Comment by WoH** [comment]
You can either set override configs in [`tsoa.json`](https://tsoa-community.github.io/reference/interfaces/_tsoa_cli.extendedspecconfig-1.html#spec), or [programatically generate your spec](https://tsoa-community.github.io/reference/modules/_tsoa_cli.html#generatespec-1) and manually merge the generated and the manual specs yourself.
