### ISSUE TITLE
Question: How to have server-global state without using module globals?

### ISSUE THREAD

**Issue by cakoose** [lukeautry/tsoa#819]
(Please let me know if this is the wrong place for help/questions like this.)

I want my controller code to have access to the server-global DB connection pool object.  Normally, I'd just thread the DB connection pool through when constructing the route handlers, but I'm not sure how to do that in tsoa.

(I could just put the object in a module global variable, but I'd prefer to avoid global variables.)

**Comment by WoH** [comment]
This is a pretty generic NodeJS question IMHO.
Unless I am missing something you export the Pool as a const or Singleton class from a module or your DI container.

**Comment by cakoose** [comment]
I'd prefer not to have any global state, including a singleton class.  (A test: can you create two instances of the application in the same Node.js isolate without having them interfere with each other's state?)

Was hoping there was a way to get tsoa to forward an extra parameter to the controller constructors.  Or even to forward an extra parameter through to the request handling function.

**Comment by WoH** [comment]
How would you have created the Pool before passing it down through the route handlers?

**Comment by WoH** [comment]
> Was hoping there was a way to get tsoa to forward an extra parameter to the controller constructors. Or even to forward an extra parameter through to the request handling function.

You can use DI to create a container so tsoa is no longer in charge of creating the controllers.

**Comment by cakoose** [comment]
> How would you have created the Pool before passing it down through the route handlers?

My `Express` app object isn't a module-level global; it's created in a function called `createApp()`.  So normally I'd either create the pool there or created it outside and pass it in.

> You can use DI to create a container so tsoa is no longer in charge of creating the controllers.

Ah, thanks!  Haven't used a DI library before but will try that out.

> E: For an extra param into the route handler you can use a decorator.

Not sure how to do this.  If you happen to have a example handy, I'd appreciate a link!  Otherwise no problem, I'll look around.

The way I'd do it without a framework:
1. When a new request comes in, get a new DB connection from the pool and start a DB transaction.
2. The authentication function gets passed this connection.
3. The controller function gets passed this connection.
4. When the request finishes, either commit or roll back the transaction, depending on whether the request succeeded.
