### ISSUE TITLE
Error: Controller methods must have a return type / Error: Unknown type: FunctionType 

### ISSUE THREAD

**Issue by mdaymond** [lukeautry/tsoa#82]
I am trying to generate a basic swagger file for my API, but I keep getting the following error:

Error: Controller methods must have a return type.

```
import { Route, Get, Post, SuccessResponse } from 'tsoa';

@Route("User")
export class UserService {
  
  @Get('{id}')
  getUser(req: Request, res: Response) {
    const id = parseInt(req.params.id);
    DataService.getUser(id)
      .then(_.partial(OnSuccess, res))
      .catch(_.partial(OnError, res, "find User Failure"))
  }

```
I thought perhaps the issue was that it wasn't seeing the return type from the DataService, so instead I moved the code to the Data service and got this error:

There was a problem resolving type of 'BluebirdIUser'.
Error: Unknown type: FunctionType 

```
@Route("User")
export class UserDataService {

    @Get('{id}')
    getUser(id: number): Bluebird<IUser> {
        return UserModel.findById(id, {
            include: [
                { model: OrderModel, required: true }
            ]
        })
            .then((data: IUser) => {
                return data
            })
    }
```

My tsoa.json

```
{
  "swagger": {    
    "outputDirectory": "./dist",
    "entryFile": "./server/server.ts"
  },
  "routes": {    
    "entryFile": "./server/server.ts",
    "routesDir": "./server/routes",
    "middleware": "express"
  }
}

```

**Comment by Dirrk** [comment]
Change the type to Promise<IUser> or just IUser

**Comment by mdaymond** [comment]
I don't think that is possible.   I am using Sequelize for my ORM which returns a Bluebird Promise

**Comment by Dirrk** [comment]
@mdaymond a bluebird promise extends a Promise so you can still just put Promise

**Comment by mdaymond** [comment]
Right.  Ok I will need to look into that.  Not sure how to do that as the code change I tried (below) gives errors:

error TS2322: Type 'Bluebird<IUser>' is not assignable to type 'IUser'.

```getUser(id: number): IUser {
        return UserModel.findById(id, {
            include: [
                { model: OrderModel, required: true }
            ]
        })
            .then((data: IUser) => {
                return data
            })

```

**Comment by Dirrk** [comment]
Can you try this: `declare global { export interface Promise<T> extends Bluebird<T> {} }`

To me that seems hacky though.  Currently in tsoa code the promise class is expected to be 'Promise' and I don't know if or how @lukeautry wants to handle changing that or not.

**Comment by lukeautry** [comment]
@mdaymond You'll definitely need to mark the controller with an explicit return type. See #15 - I'd like to be able to do implicit return types, just haven't figured out how to do it with the TypeScript compiler.
