### ISSUE TITLE
TS module resolver: No matching model found for referenced type User

### ISSUE THREAD

**Issue by binle** [lukeautry/tsoa#822]
#### When I try import a file in controllers by relative path. `tsoa spec-and-routes` return error `No matching model found for referenced type IUser`. 

**Error Code:**
  - src/controller/user.controller.ts':
   `import { User } from 'src/interfaces/models/user.model';`

 #### And it `only` return error at controllers: If I use exactly path in controllers but keep relative path for other files, the app run as well.

**Success Code:** 
 - src/controller/user.controller.ts':
   `import { User } from '../interfaces/models/user.model';`
   `import { UserService } from '../services/user.service';`
 - src/services/user.services.ts':
   `import { User } from 'src/interfaces/models/user.model';`

**Source code structure:**
```
src
  controllers
     user.controller.ts
  interfaces
     user.model.ts   
  services
     user.service.ts
```

**==> So, I think the `TSOA` can not matching the exactly the files by relative path for generating routes.ts and swagger.json files**
  - [x] bug report
  - [x] feature request
  - [x] support request

## Expected Behavior

**==> `TSOA` should be support the importing with relative path for this case**

Thanks!

**Comment by DeveloperMartin** [comment]
Did you find a solution?
