### ISSUE TITLE
Support for String attribute like maxLenght

### ISSUE THREAD

**Issue by fsimard** [lukeautry/tsoa#83]
Hello

Do you have any exemple that generate format attribute in swagger. I want to add attribute like maxLenght on String to see it in the swagger file and add validation after.

Thanks

**Comment by isman-usoh** [comment]
see ac20c4015f8ccf54030c94b86fc6f5c63c4f2fff
declare maxLenght in model
```ts
interface Model {
 /**
 * @maxLength 10
 */
  name: string;
}
```

declare maxLenght in parameter 
```ts
class Controller {
  /**
  * @maxLength name 10
  */
  public async hello(@Query() name: string): Promise<void> {...}
}
```

**Comment by adrianbenjuya** [comment]
Hi! is there a complete guide about how to use these validations?
