### ISSUE TITLE
Custom tsconfig.json path

### ISSUE THREAD

**Issue by letmaik** [lukeautry/tsoa#830]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

It should be possible to specify a custom `tsconfig.json` path, e.g. `tsconfig.foo.json`.

## Current Behavior

There is no option in `tsoa.json` to specify a custom path for the tsconfig file. An inline tsconfig object can be given, but that's not always desirable.

## Possible Solution

Add a new tsoa.json option `tsconfig` for providing a custom path.

## Context (Environment)

Version of the library: 3.3.0
Version of NodeJS: 12

- Confirm you were using yarn not npm: [ ]

## Breaking change?

No

**Comment by jackey8616** [comment]
@letmaik 
I don't quite understand.  
You want to specify a custom tsconfig path into tsoa.json? for... 
... how to building your application? (Which should handle by your application's tsconfig.json. )
or control how tsoa builds / works? (But it already done by tsoa's config itself...)

Need more details, thank you.

**Comment by letmaik** [comment]
I don't need this feature anymore. If someone else needs it, add a comment.
