### ISSUE TITLE
Samples in authentication doc page inconsistent

### ISSUE THREAD

**Issue by letmaik** [lukeautry/tsoa#831]
https://tsoa-community.github.io/docs/authentication.html

In the first section, two `securityDefinitions` are defined: `api_key` and `tsoa_auth`, however, in the following, `api_token` and `jwt` are used. This is a bit confusing and should probably be aligned.

**Comment by WoH** [comment]
Please open an issue [here](https://github.com/tsoa-community/docs/issues).
