### ISSUE TITLE
@Example doesn't read value from an imported variable

### ISSUE THREAD

**Issue by asdf123101** [lukeautry/tsoa#834]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
`@Example()` should read variable value imported from another file.

With 
```ts
// file a.ts
export const example = {someKey: 'someValue'}
// file b.ts
import example from a
...
@Example(example)
...
```
tsoa should generate the correct response example from the imported variable.

## Current Behavior
It now creates an empty object `{}` if the variable is imported. It works if the example value is directly supplied to the decorator or defined in the same file.

## Possible Solution
Feels like a TS module resolution issue.

## Steps to Reproduce
See expected behavior section.

## Context (Environment)

Version of the library: 3.4.0
Version of NodeJS: 12.4.0

- Confirm you were using yarn not npm: [x]

**Comment by DigohD** [comment]
This also seems to only be an issue when specVersion is 3. When specVersion is set to 2 it works as expected.

**Comment by nikosgpet** [comment]
Wondering if there is any update, because I just had the same issue.
