### ISSUE TITLE
[BUG] - Errors ignored during multiple security checking

### ISSUE THREAD

**Issue by dobobaie** [lukeautry/tsoa#839]
This lines bellow are invalid : 
[packages/cli/src/routeGeneration/templates/express.hbs#L128](https://github.com/lukeautry/tsoa/blob/8606da96ccc71608b0c07c8cd8384fcb7813d820/packages/cli/src/routeGeneration/templates/express.hbs#L128)
[packages/cli/src/routeGeneration/templates/express.hbs#L136](https://github.com/lukeautry/tsoa/blob/8606da96ccc71608b0c07c8cd8384fcb7813d820/packages/cli/src/routeGeneration/templates/express.hbs#L136)
[packages/cli/src/routeGeneration/templates/hapi.hbs#L109](https://github.com/lukeautry/tsoa/blob/8606da96ccc71608b0c07c8cd8384fcb7813d820/packages/cli/src/routeGeneration/templates/hapi.hbs#L109)
[packages/cli/src/routeGeneration/templates/koa.hbs#L97](https://github.com/lukeautry/tsoa/blob/8606da96ccc71608b0c07c8cd8384fcb7813d820/packages/cli/src/routeGeneration/templates/koa.hbs#L97)

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Steps to Reproduce

```js
  @Security('publicAccess')
  @Security('accessToken') // This one should be invalid and throw an error but nothing happened
  @Get('verifyToken')
  public async verifyToken(): Promise<void> {
    // ...
  }
```

## Detailed Description

Because currently in my code I'm using multi `@Security` and the thing is if one of those failed, only the last one will be reported !
Plus, `expressAuthentication(request, name, secMethod[name])` is executed before to be pushed on the promise stack. It mean in the case of `expressAuthentication` failed in synchro way then the app will literally crash. 

## Expected Behavior

```bash
[info] GET /api/v1/verifyToken?accessToken=&publicToken=test 400 // ERROR INVALID ACCESS TOKEN
```

## Current Behavior

```bash
[info] GET /api/v1/verifyToken?accessToken=&publicToken=test  200
```

## Possible Solution

To replace in `/packages/cli/src/routeGeneration/templates/express.hbs#128` file

```js
  function authenticateMiddleware(security: TsoaRoute.Security[] = []) {
    return (request: any, _response: any, next: any) =>
      new Promise((resolve, reject) => {
        const promises: Promise<any>[] = [];
        for (const secMethod of security) {
          for (const name in secMethod) {
            promises.push(expressAuthentication(request, name, secMethod[name]));
          }
        }
        Promise.all(promises)
          .then(resolve)
          .catch(reject);
      }).then((results: any) => {
        request['user'] = results.shift();
        next();
      }).catch((error) => {
        error.status = error.status || 401;
        next(error)
      });
  };
```

## More

I saw on tests that the logic is :
- if security one is not ok then we choose security two
- or if security two is not ok then we choose security one

But I think we should choose this kind of logic : 
- Ok I set a security on my route then it must be verify
- EXCEPT is the second parameter is OPTIONAL
Ex: 

``` js
@Security('publicAccess') // SHOULD BE VERIFY EVEN IF BELLOW THERE ANOTHER SECURITY
@Security('accessToken', ['optional']) // THIS ONE IS OPTIONAL SO IF THE VERIFICATION FAILED THAT IS NOT A PROBLEM
```

**Comment by dobobaie** [comment]
To avoid the problem I made a script to replace the old function to this one during a "tsoa routes" generating

**Comment by dobobaie** [comment]
Any update?

**Comment by michalzaq12** [comment]
@dobobaie try to use `@Security({'publicAccess': [], 'accessToken': []})`

**Comment by dobobaie** [comment]
@michalzaq12 well yes it works but it doesn't seems to be the right way to do it 
Even for the swagger I guess 🤔 

What do you think ? Should I make a PR or let the community use your way ? 
PS: @WoH any suggestion ?

**Comment by WoH** [comment]
> well yes it works but it doesn't seems to be the right way to do it
Even for the swagger I guess 🤔

Please elaborate how you came to that conclusion.

**Comment by dobobaie** [comment]
Well, I thought one decoration for one kind of security making more sens than an object inside one decoration. And less useless empty array as well. But the logic is already there so maybe I'm wrong to think in that way.
