### ISSUE TITLE
Make @tsoaModel decorator work for enums

### ISSUE THREAD

**Issue by patrickhrastnik** [lukeautry/tsoa#842]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit
There has been issue #328 related to this feature request, but it has been closed before it was resolved.

## Expected Behavior

The @tsoaModel decorator should work for enums as well.

## Current Behavior

Without @tsoaModel decorator on a duplicate enum name, I get the following log output:
`Error: Multiple matching models found for referenced type EntityAttributesTypeEnum; please make model names unique. Conflicts found: ...`

If I add the @tsoaModel decorator, I get the following output:
`Error: Multiple matching enum found for enum EntityAttributesTypeEnum; please make enum names unique.` 

Would be helpful if the decorator would fully work for enums as well.

## Context (Environment)

Our setup looks like this:
- Package ItemSearchApi (using tsoa)
- Package ExternalApiWrapper

ItemSearchApi uses ExternalApiWrapper to provide models from the external API. It's meant to be a wrapper for our business environment.

These two packages contain identical models and enums, since we want to use the same specification the external API provides.
The @tsoaModel decorator works fine for the models, but not for the enums.

Version of the library: 3.4.0 
Version of NodeJS: 12.16.1

**Comment by patrickhrastnik** [comment]
I tried to implement this feature on my own. Since this feature request got a "help wanted" label I will make a pull request with the suggested changes. Thanks

**Comment by InsOpDe** [comment]
hello @patrickhrastnik any news on this?

**Comment by patrickhrastnik** [comment]
Hello @InsOpDe 
I tried to implement some changes but I didn't make it to test them yet. As far as I've seen you prepared similar changes to resolve this issue - Thanks for keeping it alive.
In case you're curious, organization @HolterDev hosts a fork of this repo with a branch named `issue-842`
