### ISSUE TITLE
[Authentication]Improve documentation

### ISSUE THREAD

**Issue by Roman991** [lukeautry/tsoa#846]
The example provided in 
[https://tsoa-community.github.io/docs/authentication.html](Authentication) 
is not working.
Both names should be equal
tsoa.json >> spec.securityDefinitions.securityDefinitions.**api_key**
    and
authentication.ts >> function expressAuthentication(){ ... if (securityName === "**api_key**") {}...}    instead of **api_token**

if names are different (as in docs) u'll see an empty *Available authorizations* popup
![image](https://user-images.githubusercontent.com/10634244/99365967-3bf5f380-28b8-11eb-8aee-f07e40e18237.png)

if name are equal 
![image](https://user-images.githubusercontent.com/10634244/99366052-6182fd00-28b8-11eb-8ca7-314cd4f6fca0.png)

Its not totally related to TSOA, but I think it specifying it can avoid a lot of headaches

**Comment by tsimbalar** [comment]
FYI @Roman991  the docs live in a separate repo : https://github.com/tsoa-community/docs 

If you want to open an issue and/or a PR there ;)

**Comment by Roman991** [comment]
Thanks 👍
