### ISSUE TITLE
Cannot correctly set example for Error Response

### ISSUE THREAD

**Issue by tgouala** [lukeautry/tsoa#847]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I have an error object typed this way:
```ts
export interface ErrorPairResult {
  success: false;
  errorMessage: PairError;
  errorCode: number;
}

export type PairError =
  | "user_not_found"
  | "several_accounts_match"
  | "server_error"
  | "user_already_paired"
  | "service_user_creation_failed"
  | "account_not_compatible";
```

I have this controller function definition:

```ts
  @Post("pair/{serviceName}")
  @SuccessResponse("200", "OK")
  @Response<ErrorPairResult>(
    400,
    "The account returned by the service cannot be paired",
    { errorCode: 0, errorMessage: "user_not_found", success: false }
  )
  public async pair(
    @Path() serviceName: ServiceType,
    @Body() params: PairRequest,
    @Res() failed: TsoaResponse<400, ErrorPairResult>
  ): Promise<SuccessPairResult> {
    const result = await service.pair(serviceName, params);
    if (result.success === false) {
      return failed(400, result);
    }

    return result;
  }
```

I would expect my error 400 example to appear in the swagger UI like : 
```
{
  "success": "false",
  "errorCode": 0
  "errorMessage": "user_not_found"
}
```

## Current Behavior

Instead, here what I see in the swagger UI response example :
```
{
  "success": "false",
  "errorCode": 0
}
```
with the property `errorMessage` missing (but it is visible if I look at the response Schema)

Also, the only workaround I have is to add the example in comments on top of my model which is not great for type checking:
```ts
/**
 * @tsoaModel
 * @example {
 *  "success": false,
 *  "errorMessage": "user_not_found",
 *  "errorCode": 0
 * }
 */
export interface ErrorPairResult {
  success: false;
  errorMessage: PairError;
  errorCode: number;
}
```

## Context (Environment)

Version of the library: 3.2.1 (npm)
Version of NodeJS: v12.15.0

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
This is not how the tsoa API works. Use `@example failed "{}"` as a doc comment on the method

**Comment by tgouala** [comment]
Thanks for the answer. I am a bit confused when I read this page of the documentation :
https://tsoa-community.github.io/docs/examples.html#response-examples

It is mentioned: 

>  you can add examples for other responses (@Response(), used for additional responses, often caused by errors by providing them as the third argument as well.

Isn't it exactly what I am trying to do here ?
I don't mind using `@example failed "{}"` as a doc  comment, but if the type of my object change, then the example may be out of sync. What is `@Response()` used for then ?

**Comment by tgouala** [comment]
I just did a test, 
if I use an other error code, like `@Response< ErrorPairResult >(403, "The account returned by the service cannot be paired", {...}` instead of `@Response< ErrorPairResult >(400, "The account returned by the service cannot be paired", {...}` it works.

It seems that `@Res() failed: TsoaResponse<400, ErrorPairResult>`  will overwrite the content generated by `@Response(400, ...)` when the Open API spec is generated.

**Comment by WoH** [comment]
Yes, and that's intentional. `@Res` is a typesafe way to do it, but i.e. if you throw an error you may want to describe what that error will be serialized to. You can use `@Response` to do that (this is the "legacy" way to do it)
