### ISSUE TITLE
Unable to inject service to controller after following instructions

### ISSUE THREAD

**Issue by frankfajardo** [lukeautry/tsoa#849]
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Having followed the [instructions on using Inversify with tsoa controllers](https://tsoa-community.github.io/docs/di.html#inversifyjs), I should be able to run `tsc` without failures.

## Current Behavior
`tsc` fails saying an argument to the controller constructor was not provided. The argument, being a service decorated with `@provideSingleton` mentioned [here](https://tsoa-community.github.io/docs/di.html#inversifyjs)

## Context (Environment)

Version of the library: 3.4.0
Version of Inversify: 5.0.1
Version of NodeJS: 15.2.1

- Confirm you were using yarn not npm: [yarn]

## Detailed Description

I following the instructions here to setup DI with Inversify: https://tsoa-community.github.io/docs/di.html#inversifyjs
But when I run `tsoa routes` and then `tsc`, I get this error:
```
  src/controllers/customers/customersController.ts:11:17
    11     constructor(@inject(CustomersService) private customersService: CustomersService) {
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'customersService' was not provided.
```
My controller looks like this
```
import { provideSingleton } from "../../util/provideSingleton";

@provideSingleton(CustomersController)
@Route('customers')
export class CustomersController extends Controller {
    constructor(@inject(CustomersService) private customersService: CustomersService) {
        super();
    }
    ...
}
```
And my service like this
```
import { provideSingleton } from '../../util/provideSingleton';


@provideSingleton(CustomersService)
export class CustomersService {
    constructor(@inject(CustomersRepository) private customersRepository: CustomersRepository) {
    }
    ...
}


@provideSingleton(CustomersRepository)
export class CustomersRepository {
    ...
}
```

**Comment by WoH** [comment]
Did you set the iocModule in the tsoa config?

**Comment by frankfajardo** [comment]
Yep, that was what I was missing. Thanks
