### ISSUE TITLE
jsDoc: Can not describe parameters.

### ISSUE THREAD

**Issue by cadriel** [lukeautry/tsoa#85]
We've got a query string parameter on one of our endpoints.

I'd expect that if I describe like this;
```
/** Endpoint description
   * @param {string} product - Optional product name
   */
  @Get()
  public async getSomething(@Query() product?: string): Promise<SomeModel> {}
```

we'd see the product parameter description inside the swagger.json. This however is not the case.

**Comment by amcdnl** [comment]
Ya, I'm looking for this too. Would like to see it add the comments to the description too.

**Comment by pavelkuchin** [comment]
Can it be a decorator (Annotation)?
```
@Get()
@UrlParameters(['page', 'n'])
public async getSomething(page: number, n: number): Promise<SomeModel> {}
```

**Comment by WoH** [comment]
See [Parameter descriptions](https://tsoa-community.github.io/docs/descriptions.html#parameter-descriptions)
Let me know if there are still issues, but I assume this can be closed.
