### ISSUE TITLE
TypeScript intersection type for type branding should parse readable

### ISSUE THREAD

**Issue by meyraa** [lukeautry/tsoa#851]
[Branded types](https://medium.com/@KevinBGreene/surviving-the-typescript-ecosystem-branding-and-type-tagging-6cf6e516523d) are intersection types and parsed like one. But this doesn't provide clear information for the user.

##  Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Branded types should be parsed like normal types. It should at least display the correct type, which ist `number` in this case.

```
type Brand<K, T> = K & { __brand: T };
type CategoryId = Brand<number, "CategoryId">;

export interface ICategory {
    id: CategoryId;
    label: string;
}
```

```
"CategoryId": {
    "type": "number",
    "format": "double"
}
```

## Current Behavior

Currently it is displayed as an intersection of an object and number.

```
"Brand_number.CategoryId_": {
	"allOf": [
		{
			"type": "number",
			"format": "double"
		},
		{
			"properties": {
				"__brand": {
					"type": "string",
					"enum": [
						"CategoryId"
					],
					"nullable": false
				}
			},
			"required": [
				"__brand"
			],
			"type": "object"
		}
	]
},
"CategoryId": {
	"$ref": "#/components/schemas/Brand_number.CategoryId_"
}
```

Which looks like this:
![image](https://user-images.githubusercontent.com/19626280/99943038-ef576000-2d70-11eb-8023-9548e7dc5f74.png)

## Context (Environment)

Version of the library: 3.4.0
Version of NodeJS: 12.19.0

- Confirm you were using yarn not npm: [ ]

## Possible Solution

1. Adding a flag for ignoring certain types in intersection types.
2. Adding a special solution for branded types

## Breaking change?

The second possible solution would be a breaking change, because it would change the output for branded types.

**Comment by WoH** [comment]
Possible Solution 3: Don't expose the TS type system hacks at the edge of your program.

I know this is probably not the answer you were hoping for, but I don't really see any room to add functionality for a special treatment where the OpenAPI spec correctly matches the TS type but said TS type is invalid.

**Comment by benbabic** [comment]
Hey just bumped into this. 

Would you consider a solution that allows us to manually define parts of the schema? For example:

```ts
type Brand<K, T> = K & { __brand: T };

/** 
* @tsoaManualSchema number
*/
type CategoryId = Brand<number, "CategoryId">;
```

Also, while it might seem hacky to add branded types the way we have to currently do in typescript, it works so they are a valid, and [very much used](https://www.google.com/search?q=typescript+branded+types&oq=typescript+branded+types&aqs=chrome.0.0i512j0i390i395l3.2866j1j7&sourceid=chrome&ie=UTF-8), part of typescript. Fun fact, they are [part of typescript's baseline tests for the language](https://github.com/microsoft/TypeScript/search?q=branded+type) and there are several tickets about making them more integrated to the language so this is probably worthwhile supporting.
