### ISSUE TITLE
Feature request: Automatically add 401 and 403 responses to routes using security decorator

### ISSUE THREAD

**Issue by Kampfmoehre** [lukeautry/tsoa#852]
After working with ASP .NET Core and Swashbuckle for a while I got used to a feature that allows to automatically add 401 and 403 responses to all routes that are use a security scheme. Returning to a tsoa project I am really missing that feature because I have the same 2 lines over nearly all of the controller actions.
This particular feature is explained [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#operation-filters) and I would really like to see something like this in tsoa.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

There could be a setting that enables this feature or at least a documentation section explaining how to achieve something like this.

## Current Behavior

As far as I can see there is currently no possibility to manipulate swagger generation for particular routes apart from the decorators provided by tsoa and jsdoc comments. If someone could point out where such a feature should be implemented then maybe I could take a look myself on adding such a feature.

**Comment by WoH** [comment]
a) How would the response schema (Body/Headers) be inferred?
b) Do we have to respond with 401/403? If we document it that way, how would we ensure the HTTP Response actually has the Status?

**Comment by Kampfmoehre** [comment]
Maybe tsoa can define a default response interface from which users can extend from. As tsoa intent is to provide a JSON API this could be a default response like
```json
{
  "status": 401,
  "message": "Unauthorized"
}
```

Of course it would be perfect to include the `www-authenticate` header but for this tsoa must know how authentication is actually done.
As far as I know tsoa already does at least respond with 401 when using an authentication middleware that rejects the promise. We have integrated an additional right check in our auth middleware that would respond with 403 if authorization passed but lacking sufficient rights. For us this means we have to include the `@Response(401)` and `@Response(403)` header on nearly every method and it would be a great relief if this could somehow be done with tsoa.

Maybe this can be a setting in tsoa that enables the feature (opt-in). When set every route that has a `@Security` decorator will have a 401 response added that is displayed in swagger. Maybe with the default response from above.

See for example the Express route template where the 401 response is set for all requests where auth failed and that do not already set a status: https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/routeGeneration/templates/express.hbs#L115
If we could somehow know which authentication failed we could also set the www-authenticate header there.

**Comment by Kampfmoehre** [comment]
Some thoughts about the feature:

I would propose to add a default response interface that Users can extend from like the one above:

```ts
export interface AuthResponseBase {
  status: number;
  message: string;
}

export interface UnauthorizedResponse extends AuthResponseBase {
  status: 401;
  message: "This resource is protected and you need to authorize first.";
}

export interface ForbiddenResponse extends AuthResponseBase {
  status: 403;
  message: "You lack the required rights to access this resource.";
}
```

Not sure if we should hard code the status but it can always be extended from and overwritten. Then somewhere the response type should be set that is returned for responses where the authentication middleware failed (preferably the middleware already returns the object). Then the users could set via the Security decorator or via config a custom Model (or the provided model).
For example the Security decorator could be generic and the generic type is the type of the response:

```ts
export function Security<T extends AuthResponseBase>(name: string | { [name: string]: string[] }, scopes?: string[]): Function {
  return () => {
    return;
  };
}
```

Then the security middleware must somehow return the response object or throw a special provided exception that is converted to the response.
