### ISSUE TITLE
TSOA returned HTTP status code is always 200 when external file import is used

### ISSUE THREAD

**Issue by BloodMotion** [lukeautry/tsoa#856]
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Here is an example of a controller, which sends an SMS message when called.
I want answer with a specific HTTP status code (eg: 204). To perform that,  I'll use `export default const` to set the HTTP status code desired.

So I use `@SuccessResponse(NO_CONTENT, 'HTTP 204 No Content')` and  `this.setStatus(NO_CONTENT )`, and it works, the status code is well sended to the client (400 bad request or 204 no content).

**sms.controller.ts  :**
```ts
import {
  Controller,
  Post,
  Route,
  SuccessResponse,
  Response,
  Tags,
  Body,
} from 'tsoa'
import { SmsRequestBody } from '../models/sms/sms'
import { SmsService } from '../models/sms/smsService'
import { ErrorMiddlewareContent } from '../models/utils/common.interfaces'

export const NO_CONTENT = 204
export const BAD_REQUEST = 400

@Route('sms')
@Tags('SMS')
export class SmsController extends Controller {
  private service: SmsService = new SmsService()

  @Response<ErrorMiddlewareContent>(BAD_REQUEST, 'BadRequest')
  @SuccessResponse(NO_CONTENT, 'HTTP 204 No Content')
  @Post()
  public async send(@Body() requestBody: SmsRequestBody): Promise<void> {
    this.setStatus(NO_CONTENT)
    await this.service.send(requestBody)
    return
  }
}
```
And it works like a charm, the HTTP status code returned is well 400 or 204 depending on the result of the request.

## Current Behavior & Steps to Reproduce

But if I tried to use an external file that regroup each HTTP status code, and try to import it on my controller, I got an unexpected behavior: TSOA (controller) will always return a 200 HTTP status code, no matter error or HTTPS status code set in the controller.

Here is an example based on a _http-codes.ts_ file:

**sms.controller.ts  :**
```ts
import {
  Controller,
  Post,
  Route,
  SuccessResponse,
  Response,
  Tags,
  Body,
} from 'tsoa'
import { SmsRequestBody } from '../models/sms/sms'
import { SmsService } from '../models/sms/smsService'
import { ErrorMiddlewareContent } from '../models/utils/common.interfaces'
import { NO_CONTENT, BAD_REQUEST } from '../errors/http-codes'

@Route('sms')
@Tags('SMS')
export class SmsController extends Controller {
  private service: SmsService = new SmsService()

  @Response<ErrorMiddlewareContent>(BAD_REQUEST, 'BadRequest')
  @SuccessResponse(NO_CONTENT, 'HTTP 204 No Content')
  @Post()
  public async send(@Body() requestBody: SmsRequestBody): Promise<void> {
    this.setStatus(NO_CONTENT)
    await this.service.send(requestBody)
    return
  }
}
```

**http-codes.ts  :**
```ts
/**
 * Hypertext Transfer Protocol (HTTP) response status codes.
 * @see {@link https://en.wikipedia.org/wiki/List_of_HTTP_status_codes}
 */

/**
 * The server successfully processed the request and is not returning any content.
 */
export const NO_CONTENT = 204

/**
 * The server cannot or will not process the request due to an apparent client error
 * (e.g., malformed request syntax, too large size, invalid request message framing, or deceptive request routing).
 */
export const BAD_REQUEST = 400
```
Then it will always return a 200 HTTP status code if the const is imported from an external file.

## Context (Environment)

Version of the library: 3.4.0
Version of NodeJS: v10.15.3

- [x] Confirm you were using yarn not npm

**Comment by BloodMotion** [comment]
Hello, any update ?
On my side I just use the export on local.
Not great but working.

**Comment by WoH** [comment]
I can't reproduce it

**Comment by WoH** [comment]
Quick context: This only affects the OpenAPI spex. f you import a const from another module it's hard to ensure that tsoa can statically analyze your code and reliably determine a documentable status code. However, my advice would be to use an enum to wrap the Status Codes, which will work fine.
