### ISSUE TITLE
Support OpenAPI vendor extensions at swagger.json top level

### ISSUE THREAD

**Issue by cwilso03** [lukeautry/tsoa#858]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I know that in [this PR](https://github.com/lukeautry/tsoa/pull/700), support was added for the `@Extension` decorator.  However, it only works at an individual operation level (which the PR states as such).  

It would be great if there was a way to support vendor extensions for the top-level of the swagger.json file.  In particular, I'd like to take advantage of Redocly's use of the `x-tagGroups` extension (as documented [here](https://redoc.ly/docs/api-reference-docs/vendor-extensions/redoc-supported-extensions/#x-taggroups)).  Because this extension has to be at the top level of the swagger JSON object, the current implementation of the `@Extension` decorator doesn't work for this purpose.

Example desired swagger.json
```json
{
  "components": { ... },
  "info": { ... },
  "openapi": "3.0.0",
  "paths": { ... },
  "servers": [ ... ],
  "x-tagGroups": [
    {
      "name": "User Management",
      "tags": ["Users", "API keys", "Admin"]
    },
    {
      "name": "Statistics",
      "tags": ["Main Stats", "Secondary Stats"]
    }
  ]
}
```

## Current Behavior

The `@Extension` decorator only produces output in the swagger.json file if used on a particular operation.

## Possible Solution

Broaden the allowed scopes of the `@Extension` decorator to allow top-level usage.

## Context (Environment)

Version of the library: 3.2.1
Version of NodeJS: 12.18.3

- Confirm you were using yarn not npm: [x]

## Detailed Description

See above.

## Breaking change?
No.

**Comment by WoH** [comment]
This is supported through `tsoa.json` config as far as I can tell. See `spec` and `specMerging` [here](https://tsoa-community.github.io/reference/interfaces/_tsoa_runtime.specconfig-1.html).

**Comment by cwilso03** [comment]
Yes, that does work, with the caveat (which Redocly documents) that each tag has to be added to a group in x-tagGroups, or it doesn't appear in the generated documentation at all.  It's a shame they don't include other tags automatically, but that's not tsoa's fault.

Thanks for the tip!
