### ISSUE TITLE
[BUG] - Header already sent

### ISSUE THREAD

**Issue by dobobaie** [lukeautry/tsoa#859]
Lines to update : 
[packages/cli/src/routeGeneration/templates/express.hbs#L152](https://github.com/lukeautry/tsoa/blob/8606da96ccc71608b0c07c8cd8384fcb7813d820/packages/cli/src/routeGeneration/templates/express.hbs#L152)
[packages/cli/src/routeGeneration/templates/hapi.hbs#L165](https://github.com/lukeautry/tsoa/blob/8606da96ccc71608b0c07c8cd8384fcb7813d820/packages/cli/src/routeGeneration/templates/hapi.hbs#L165)
[packages/cli/src/routeGeneration/templates/koa.hbs#L160](https://github.com/lukeautry/tsoa/blob/8606da96ccc71608b0c07c8cd8384fcb7813d820/packages/cli/src/routeGeneration/templates/koa.hbs#L160)

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Steps to Reproduce

- Use express as framework
- Install `connect-timeout` or similar package
- Add the middleware with `5s` of timeout
- Add a new controller and put the code bellow in your class
```js
  @Get('list')
  public async retrieveList(): Promise<any> {
    await new Promise((resolve) =>
      setTimeout(() => resolve(), 10000)
    );
    return { status: 'ok' };
  }
```
- Request on the route and watch the console

## Detailed Description

if any external middleware send a response before the request is done then we got the error bellow : 

``` bash
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:547:11)
``` 

## Expected Behavior

```bash
Nothing
```

## Current Behavior

``` bash
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:547:11)
``` 

## Possible Solution

Add a verification to know is the request is already sent

Maybe
```js
response.on('close', () => ...);
```

**Comment by dobobaie** [comment]
Any update?

**Comment by WoH** [comment]
Feel free to submit a PR that adds this check

**Comment by dobobaie** [comment]
> E: Newer versions of Node support [`res.writableEnded`](https://github.com/nodejs/node/commit/f9b61d2bc7), we should use that.

We also should keep old Node.Js compatibility as well !

**Comment by WoH** [comment]
> > E: Newer versions of Node support [`res.writableEnded`](https://github.com/nodejs/node/commit/f9b61d2bc7), we should use that.
> 
> We also should keep old Node.Js compatibility as well !

There's a reason I mentioned that. If `writableEnded` does not exist, we just continue as if we were still able to write.
