### ISSUE TITLE
Omit doesn't seem to work

### ISSUE THREAD

**Issue by bytenik** [lukeautry/tsoa#860]
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Omit should be able to be used to create types.

## Current Behavior

An error is generated:

> Error: No matching model found for referenced type Omit. If Omit comes from a dependency, please create an interface in your own code that has the same structure. Tsoa can not utilize interfaces from external dependencies. Read more at https://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD

## Reproduction Code

```
export interface NewIndicator extends Omit<IndicatorBase, 'formula'> {
    ownerId?: string | null;
    formula?: string;
}
```

## Context (Environment)

Version of the library: 3.4.0
Version of NodeJS: 13.14.0

- Confirm you were using yarn not npm: [X]

**Comment by bytenik** [comment]
Having looked through the code, I don't see how this worked / could have ever worked, but I know stuff was merged in to make it work. So I'm confused. It seems like the models are only searched for in import declarations within the file, and since Omit is not imported but rather ambient, it won't be found.

**Comment by bytenik** [comment]
I'm happy to try to fix this myself, but, I would need some guidance since I'm new to the codebase. Thanks!

**Comment by WoH** [comment]
It will be found if the declaration is included in your program. Make sure the relevant files are not exlcuded in your tsconfig. I don't think there's a bug, if there is, please try to provide a repro.

**Comment by bytenik** [comment]
Omit is built into TypeScript.

**Comment by bytenik** [comment]
Literally any use of Omit will fail:
```
export interface ParentModel { abc: string; def: string; }
export interface ChildModel extends Omit<ParentModel, 'abc'> { ghi: string; }```

**Comment by bytenik** [comment]
@WoH I don't think this should have been closed, as `Omit` is built into TypeScript. Please advise?

**Comment by WoH** [comment]
We use `Omit` a lot throughout our tests, which makes me fairly confident in asserting that it's not us. Everything else you said has nothing to do with the issue.

> Omit is built into TypeScript.

Location is still in `node_modules`, which you probably are still excluding from your program.

My advice would be to not down vote for giving you a hint despite the duplicated issue and instead prove your issue with a repro if you're so confident it's an issue.

**Comment by bytenik** [comment]
Looks like you're correct, its because of the `node_modules` exclusion. My assumption was that would not matter because, since you don't check external dependencies, handling of TypeScript internals would be handled independently of exclusions. Thanks!
I didn't mean anything hostile by the downvote; just that I disagreed with the issue being closed because it didn't seem like it was resolved. Thanks for following up.

**Comment by WoH** [comment]
I don't tend to actively close issues which are unresolved. However, most of this discussion is a duplicate of https://github.com/lukeautry/tsoa/issues/774 and https://github.com/lukeautry/tsoa/issues/784 as well as the list of issues listed in #774:
- #340
- #377
- #334
- #205
