### ISSUE TITLE
Generate routes error (IndexedAccessType + TypeOperator)

### ISSUE THREAD

**Issue by m-doi2** [lukeautry/tsoa#862]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior

This is a problem similar to the Enum problem that was improved with this pull request.
https://github.com/lukeautry/tsoa/pull/636

For example, if you use the `KeyOfKeyword` type generated using the object's key value as the schema, the Generate routes error will occur.

```ts
const genderCds: {
    readonly male: "male";
    readonly female: "female";
};

type GenderCd = typeof genderCds[keyof typeof genderCds];

export interface TestModel {
  genderCd: GenderCd;
}
```

```sh
Generate routes error.
 Error: Unknown type: IndexedAccessType
At: /mypath/to/xxx/index.d.ts:8:8.
This was caused by 'type GenderCd = typeof genderCds[keyof typeof genderCds];'
    at new GenerateMetadataError (/mypath/to/node_modules/@tsoa/cli/dist/metadataGeneration/exceptions.js:22:28)
    at TypeResolver.resolve (/mypath/to/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:308:19)
    at TypeResolver.getTypeAliasReference (/mypath/to/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:529:353)
    at TypeResolver.getReferenceType (/mypath/to/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:505:38)
    at TypeResolver.resolve (/mypath/to/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:341:34)
    at TypeResolver.resolve (/mypath/to/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:294:131)
    at TypeResolver.propertyFromSignature (/mypath/to/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:761:143)
    at /mypath/to/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:727:161
    at Array.map (<anonymous>)
    at TypeResolver.getModelProperties (/mypath/to/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:727:124)
```

## Possible Solution

When parsing a type like `GenderCd` in this example with the TypeResolver class,
`ts.isIndexedAccessTypeNode(this.typeNode)` is true 
and 
`ts.isTypeOperatorNode(this.typeNode.indexType) && this.typeNode.indexType.operator === ts.SyntaxKind.KeyOfKeyword` is true.

Therefore, I confirmed that it works as expected by resolving indexType as a actual type as shown below.

```ts
// ↓added
if (ts.isIndexedAccessTypeNode(this.typeNode)) {
  return new TypeResolver(this.typeNode.indexType, this.current, this.typeNode, this.context, this.referencer).resolve();
}
// ↑added

if (ts.isParenthesizedTypeNode(this.typeNode)) {
...
```

However, I have no experience with TypeScript type analysis, so I'm not sure if this solution is correct.
Is it possible to consider a complete solution?

It's very useful to dynamically type string literals, so I'd be very happy if this could be resolved.

Thank you.

**Comment by m-doi2** [comment]
The fix for https://github.com/lukeautry/tsoa/pull/799 seems to have resolved this issue.
It's a great job for me, who makes heavy use of Template Literal Strings. Thank you. 🙇🏻‍♂️

**Comment by simon-mathewson** [comment]
I'm still getting this error with v3.5.0 using

```typescript
type CountryCodes = typeof countryCodes[keyof typeof countryCodes];
```

**Comment by dgrdl** [comment]
I am running into this exact same problem with tsoa 3.9.0 when using enums in [Prisma](https://github.com/prisma/prisma). Prisma generates types that look somewhat like this:

```
export const ExampleEnum: {
  FOO: 'foo';
  BAR: 'bar';
};

export type ExampleEnum = (typeof ExampleEnum)[keyof typeof ExampleEnum];
```

which produces the same error when put into a model:

```
There was a problem resolving type of 'ExampleEnum'.
There was a problem resolving type of 'ExampleModel'.
Generate routes error.
 Error: Unknown type: IndexedAccessType
At: /my/project/root/xxx/enum.d.ts:6:6.
This was caused by 'export type ExampleEnum = typeof ExampleEnum[keyof typeof ExampleEnum];'
    at new GenerateMetadataError (/my/project/root/node_modules/@tsoa/cli/dist/metadataGeneration/exceptions.js:22:28)
    at TypeResolver.resolve (/my/project/root/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:339:19)
    at TypeResolver.getTypeAliasReference (/my/project/root/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:581:353)
    at TypeResolver.getReferenceType (/my/project/root/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:556:38)
    at TypeResolver.resolve (/my/project/root/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:372:34)
    at TypeResolver.propertyFromSignature (/my/project/root/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:799:143)
    at /my/project/root/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:765:161
    at Array.map (<anonymous>)
    at TypeResolver.getModelProperties (/my/project/root/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:765:124)
    at TypeResolver.getModelReference (/my/project/root/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:605:31)
```

I can confirm that the possible solution provided by @m-doi2 gets rid of the error and seems to produce correct routes and specs for the simple example above.

It would be great if this issue could be reopened and reevaluated.

Thank you!

**Comment by ngaer** [comment]
I'm having the same issues on the latest version (v.3.14.1) as well. I also use Prisma which generates enum types like described above:
```ts
export const MessageState: {
  pending: 'pending',
  available: 'available'
};

export type MessageState = (typeof MessageState)[keyof typeof MessageState]
```
And it gives me the same `Error: Unknown type: IndexedAccessType` error.

I tested it using #799 version and it also produces the same errors. 

And I could also confirm what the fix suggested by @m-doi2: 
```ts
// ↓added
if (ts.isIndexedAccessTypeNode(this.typeNode)) {
  return new TypeResolver(this.typeNode.indexType, this.current, this.typeNode, this.context, this.referencer).resolve();
}
// ↑added

if (ts.isParenthesizedTypeNode(this.typeNode)) {
...
```
resolves the issues and produces correct types. And all tests are passed, so it doesn't seems to break anything.

I can create a PR with suggested fix. @WoH can you please take a look if this is a correct solution?

**Comment by WoH** [comment]
Afaik we resolve `keyof typeof T` correctly via the type the compiler infers. However, the proposed piece of code breaks down quickly if the index type (`keyof (typeof MessageState)`) is not the `keyof` of the object type (`(typeof MessageState)`).

Or, a quick test that'd have to pass:
```ts
const a = {
  a: 1,
  d: 4
} as const

const b = {
  a: "a",
  d: "d"
} as const

type Correct = (typeof a)[keyof typeof b] // 1 | 4
type Incorrect = keyof typeof b // "a" | "d"

```

The code proposed generates JSON Schema for `Incorrect`, as it simply discards the object type, which will only work in the special case I mentioned.

**Comment by ngaer** [comment]
Ok, I see. 

Maybe you have some ideas about what needs to be changed to cover the "different index type" case as well? I'm not really experienced in type analysis and unfortunately can't change the type definitions cause they come from Prisma.

And I guess in either case we should reopen the issue since the problem still can be reproduced.

**Comment by WoH** [comment]
Please open a new issue, just for this problem, and I'll tag it properly.

**Comment by WoH** [comment]
@niklass08 Would you like to provide a PR to fix this?

**Comment by RohitRox** [comment]
I think the issue is still present or does this need some special configuration?
I am trying to do something like this:

```ts
enum SortKeys {
    CREATED = 'createdTs'
}

export interface SearchRequest {
    sort: {
        [k in keyof typeof SortKeys]: string
    }[]
}

```
I get following error during build:

```
There was a problem resolving type of 'SearchRequest'.
Generate routes error.
  GenerateMetadataError: Unknown type: MappedType
At: ....
This was caused by '{
        [k in keyof typeof SortKeys]: string
    }[]'
```

I am using tsoa ver 4.1.2
