### ISSUE TITLE
How to perform manual dependency injection (i.e. no DI framework)?

### ISSUE THREAD

**Issue by ljwagerfield** [lukeautry/tsoa#869]
## Sorting

- **I'm submitting a support request / feature request**

- I confirm that I used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behaviour

I would like to instantiate my controllers (and their dependencies) manually, rather than using a DI framework.

## Further Context

In some development teams, manual DI is preferred over automatic DI, as it provides the fewest surprises.

If `tsoa` is an opinionated framework that couples to automatic DI, then that's obviously fine (and I still love it).

But if `tsoa` supported manual constructor DI too... well that would be awesome.

**Comment by WoH** [comment]
[The docs](https://tsoa-community.github.io/docs/di.html#ioc-module) should provide all the info you need. TL;Dr: Implement the interface and reference it as an ioc module and tsoa will use it.

**Comment by ljwagerfield** [comment]
Would it be possible to provide an example of how to achieve manual constructor DI through `interface IocContainer`?

Is it essentially the following?

```typescript
const ioc: IocContainer = {
  get<T>(controller: { prototype: T }): T {
    if (controller.prototype instanceof FooController) {
      return new FooController(a, b, c) as any
    }
    if (controller.prototype instanceof BarController) {
      return new BarController(x, y, z) as any
    }
    if (controller.prototype instanceof QuxController) {
      return new QuxController(a, b) as any
    }
  }
}
```
