### ISSUE TITLE
Unable to find a readme for tsoa@3.4.0 on npm page

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [lukeautry/tsoa#871]
"Unable to find a readme for tsoa@3.4.0" Error message on npm page.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

User can see README on this repo

## Current Behavior

I only see an error message saying "Unable to find a readme for tsoa@3.4.0".

![Screen Shot 2020-12-15 at 12 42 22 PM](https://user-images.githubusercontent.com/15520015/102168091-fcc8bb80-3ed2-11eb-8034-a1f809acb525.png)

## Steps to Reproduce

check to the npm page: https://www.npmjs.com/package/tsoa

**Comment by WoH** [comment]
I assume we should symlink the top level readme in the package and npm will pick that up.

**Comment by WoH** [comment]
Symlinked the gh readme to the main package's readme, which means both npm and github have something understandable to work with.
