### ISSUE TITLE
Validation errors cannot be captured using Koa

### ISSUE THREAD

**Issue by ljwagerfield** [lukeautry/tsoa#872]
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behaviour

Validation errors can be captured in a custom error handler middleware using `error instanceof ValidationError`, with Koa.

## Current Behaviour

Validation errors are transformed to generic `Error` types in Koa, so are unhandleable.

## Possible Solution

I will probably switch to Express.

## Detailed Description

The problem does not exist in Express:

**Koa Route Template:**
```typescript
let validatedArgs: any[] = [];
try {
  validatedArgs = getValidatedArgs(args, context, next);
} catch (error) {
  context.status = error.status;
  context.throw(error.status, JSON.stringify({ fields: error.fields })); // original 'error' is lost
}
```

**Express Route Template:**
```typescript
let validatedArgs: any[] = [];
try {
    validatedArgs = getValidatedArgs(args, request, response);
} catch (err) {
    return next(err); // original error is bubbled
}
```

**Comment by midori0507** [comment]
+1 this is annoying

**Comment by ericwong3** [comment]
+1 for being annoying, here is a temporary (ugly) workaround if you are dedicated to using Koa though..

```js
if (err instanceof HttpError && err.status === 400 && err.message.startsWith('{"fields":{"')) {
  ctx.status = 422;
  ctx.body = {
    status: 'validation_failed',
    details: JSON.parse(err.message)?.fields,
  };
  return;
}
```

**Comment by akhan5** [comment]
+1 this is annoying

**Comment by WoH** [comment]
+1 for a PR
