### ISSUE TITLE
Union types give codegen error for some languages (e.g. C++)

### ISSUE THREAD

**Issue by bytenik** [lukeautry/tsoa#875]
When using union types and then running openapi-codegen-cli on it for certain language targets, the generator errors out with the following error:

```inheritance without use of 'discriminator.propertyName' has been deprecated in the 5.x release. Composed schema name: null. Title: null```

It would be good to be able to specify the discriminator propertyName at the time of creation of the union type by using a decorator... something like:

```
export interface Type1 { type: 'asdf', x: number }
export interface Type2 { type: 'abcd', a: string } 
@Discriminator('type')
export type MyUnionType = Type1 | Type2;
```

I would be happy to implement this myself if I could get a bit of guidance as to where to start in the tsoa codebase.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

**Comment by WoH** [comment]
#833
