### ISSUE TITLE
Using Kebab case on query paramters

### ISSUE THREAD

**Issue by admirkadriu** [lukeautry/tsoa#877]
Is there any way to add Kebab case query parameters e.g. `next-cursor`

- **I'm submitting a ...**
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I should be able to add a Kebab case query paramter

## Current Behavior

I get a syntax error on this case.

```ts
@Query() next-cursor: string,
```

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
you can use it like this:

```
@Query("next-cursor") nextCursor: string,
```

**Comment by admirkadriu** [comment]
@b6pzeusbc54tvhw5jgpyw8pwz2x6gs thank you
