### ISSUE TITLE
typegoose virtual as swagger model field

### ISSUE THREAD

**Issue by josh-burton** [lukeautry/tsoa#878]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

I'm using tsoa with typegoose and attempting to define some mongodb virtuals on my models.

Typegoose supports virtuals as simple functions: https://typegoose.github.io/typegoose/docs/api/virtuals/

e.g.

```
    @prop()
    public firstName: String;
    @prop()
    public lastName: String;

    public get fullName() :string {
        return `${this.firstName} ${this.lastName}`;
    }
```

My issue is, how can I get fullName to be defined as a field in the swagger doc of my model. Is there a tsoa annotation I need to use?

**Comment by WoH** [comment]
If you return classes, these fields will not get serialized (by default), therefore tsoa does not document them. However, you can solve that with the solution suggested in https://github.com/lukeautry/tsoa/issues/631
