### ISSUE TITLE
please support recursive type

### ISSUE THREAD

**Issue by kahirokunn** [lukeautry/tsoa#881]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

**Comment by jbhurruth** [comment]
@WoH why was this closed? Are recursive types supported now?
