### ISSUE TITLE
Mapped type results in empty object in schema unless explicitly declared as return value

### ISSUE THREAD

**Issue by jon-v** [lukeautry/tsoa#884]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The "Related_children_" schema should be populated correctly (this is what happens currently if I declare the return type of the controller function, ie. the last of the four code snippets):
```json
{
	"components": {
		"schemas": {
			"PersonValues": {
				"properties": {
					"name": {
						"type": "string"
					},
					"age": {
						"type": "number",
						"format": "double"
					}
				},
				"required": [
					"name",
					"age"
				],
				"type": "object",
				"additionalProperties": false
			},
			"Related_children_": {
				"properties": {
					"children": {
						"items": {
							"$ref": "#/components/schemas/PersonValues"
						},
						"type": "array"
					}
				},
				"type": "object"
			}
		}
	},
	"paths": {
		"/Test": {
			"get": {
				"operationId": "GetJohnWithChildren",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{
											"$ref": "#/components/schemas/PersonValues"
										},
										{
											"$ref": "#/components/schemas/Related_children_"
										}
									]
								}
							}
						}
					}
				}
			}
		}
	}
}
```

... based on this code with no declared return type in the controller function:
```ts
import { Controller, Get, Route } from 'tsoa'

export interface PersonValues {
  name: string
  age: number
}

export interface Relations {
  children?: PersonValues[]
  cousins?: PersonValues[]
}

export type Person = PersonValues & Relations

type Related<T extends keyof Relations> = {
  [key in T]: Relations[T]
}

const jane: Person = { name: 'Jane Doe', age: 5 }
const john: Person = { name: 'John Doe', age: 32, children: [jane] }

function getJohn<R extends keyof Relations> (relation: R) {
  const obj = { name: john.name, age: john.age } as PersonValues & Related<R>
  obj[relation] = john[relation]
  return obj
}

@Route('Test')
export class TestController extends Controller {
  @Get('')
  public async getJohnWithChildren () {
    return getJohn('children')
  }
}
```

## Current Behavior

This is what is currently returned if I don't declare the return type:
```json
{
	"components": {
		"schemas": {
			"PersonValues": {
				"properties": {
					"name": {
						"type": "string"
					},
					"age": {
						"type": "number",
						"format": "double"
					}
				},
				"required": [
					"name",
					"age"
				],
				"type": "object",
				"additionalProperties": false
			},
			"Related_children_": {
				"properties": {},
				"type": "object"
			}
		}
	},
	"paths": {
		"/Test": {
			"get": {
				"operationId": "GetJohnWithChildren",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {
									"allOf": [
										{
											"$ref": "#/components/schemas/PersonValues"
										},
										{
											"$ref": "#/components/schemas/Related_children_"
										}
									]
								}
							}
						}
					}
				}
			}
		}
	}
}
```

This is what I currently have to do to achieve the desired result (ie. the first of the four code snippets):
```ts
import { Controller, Get, Route } from 'tsoa'

export interface PersonValues {
  name: string
  age: number
}

export interface Relations {
  children?: PersonValues[]
  cousins?: PersonValues[]
}

export type Person = PersonValues & Relations

type Related<T extends keyof Relations> = {
  [key in T]: Relations[T]
}

const jane: Person = { name: 'Jane Doe', age: 5 }
const john: Person = { name: 'John Doe', age: 32, children: [jane] }

function getJohn<R extends keyof Relations> (relation: R) {
  const obj = { name: john.name, age: john.age } as PersonValues & Related<R>
  obj[relation] = john[relation]
  return obj
}

@Route('Test')
export class TestController extends Controller {
  @Get('')
  public async getJohnWithChildren (): Promise<
    PersonValues & Related<'children'>
  > {
    return getJohn('children')
  }
}
```

## Context (Environment)

Version of the library: 3.4.0
Version of NodeJS: 14.15.0

## Detailed Description

Apologies for the long report with perhaps unnecessarily complete code examples, but hopefully it helps make my issue as clear as possible. In short, tsoa seems to be able to infer the return type of the getJohn function and even determine a good name for the mapped type Related<'children'>, but it doesn't actually populate the schema for it unless I explicitly declare it as a return type of the controller function.

Of course in this simple example it's very easy to just declare the return type explicitly, but the point of the generic function and mapped type is to be able to compose an object that includes different subsets of various related objects and have it be correctly typed without a lot of boilerplate for each possible combination of related objects.

Sadly I have no knowledge of tsoa or Typescript API internals to be able to determine whether this is a small bug or a deliberate design choice or something in between, but the fact that a well named schema is generated in the "current behavior" example above makes me suspect/hope there's just a bug causing it to not be populated.

**Comment by WoH** [comment]
If there is no return type annotation, we rely on the TS API to give us a TypeNode based on the return Type the TypeChecker infers.
It seems like this does not work well in that case unfortunately. While we may introduce a proper Type -> JSON Schema functionality without relying on a "virtual" TypeNode as an intermediary, the best way is to explicitly declare the return type right now.
