### ISSUE TITLE
CLI skip @Hidden decorator

### ISSUE THREAD

**Issue by elaygl** [lukeautry/tsoa#886]
I use `tsoa spec` to generate an OAS file. This file is used to deploy to API Gateway and to readme.io docs. I'm looking for a way to be able to hide some endpoints from the docs but not from the API Gateway.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Add flag in `tsoa` CLI that ignores the `@Hidden()` decorator
Example: `tsoa spec --include-hidden`

## Current Behavior

There's no option to build the `tsoa` spec including the hidden endpoints.

## Possible Solution

`tsoa spec --include-hidden`

**Comment by WoH** [comment]
I think this is too specific to be handled at the framework level. Imho, you should use `@Extension()` to mark these EPs with a custom attribute and feed the generated spec into a utility that strips out the EPs marked.
