### ISSUE TITLE
 Error: Duplicate path parameter definition signature found in controller...

### ISSUE THREAD

**Issue by simllll** [lukeautry/tsoa#890]
The new version throws an error, which I can not exactly figure out:
Generate routes error.
` Error: Duplicate path parameter definition signature found in controller SitemapController at [method GET getJobsSitemap, getLpSitemap, getLpSitemapIndex], JobfeedController at [method GET getJobFeedsPrioBranch, getJobFeedsPrioDefault, getJobFeedsBranchRegion, getJobFeedsBranch, getJobFeedsDefault]`

We have methods like this:
```ts
@Get('/jobprio-{page}-{prio}-{branch}.{format}')
	public async getJobFeedsPrioBranch(
		@Request() req: express.Request,
		@Path('page') page: string,
		@Path('format') format: JobfeedOutputs, // 'xml' | 'csv' | 'json',
		@Path('prio') prio?: JobPrioLevel | '0',
		@Path('branch') branch?: string,
		@Query('utm_campaign') utm_campaign?: string,
		@Query('utm_source') utm_source?: string,
		@Query('utm_medium') utm_medium?: string
	)
```

```ts
@Get('/jobprio-{page}-{prio}.{format}')
	public async getJobFeedsPrioDefault(
		@Request() req: express.Request,
		@Path('page') page: string,
		@Path('format') format: JobfeedOutputs, // 'xml' | 'csv' | 'json',
		@Path('prio') prio?: JobPrioLevel | '0',
		@Query('utm_campaign') utm_campaign?: string,
		@Query('utm_source') utm_source?: string,
		@Query('utm_medium') utm_medium?: string
	)
```

this worked before, and should still work right?

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
the routes should be computed correctly.

## Current Behavior

throws error

## Possible Solution

not quite sure yet where the error is coming from..maybe from the path parameters?

## Steps to Reproduce

add two methods with different dynamic path paramters. (see example above)

## Context (Environment)

Version of the library: 3.5.0
Version of NodeJS: 15.2.1

**Comment by simllll** [comment]
When I debug the "paths" vars.. I get somethign like this:
```
  paths: [
    { isParam: false, path: '' },
    { isParam: true, path: 'jobfeed-{page}.{format}' }
  ],

```
```
tester.paths [
  { isParam: false, path: '' },
  { isParam: true, path: 'jobfeed-{page}-{branch}-{region}.{format}' }
]
{
  paths: [
    { isParam: false, path: '' },
    {
      isParam: true,
      path: 'jobfeed-{page}-{branch}-{region}.{format}'
    }
  ],

```

not quite sur ewhat sohuld be in it, but accoridn go the code it tests the length of the array, and the first element is kinda empty, the second one has the whole path in it.. is this the bug?

**Comment by simllll** [comment]
This got introduced in https://github.com/lukeautry/tsoa/pull/829

It seems my case has just not been covered. @jackey8616  do you an idea how we could solve this nicely?

**Comment by WoH** [comment]
Released a fix (3.5.1).
While the overlap detection very much seems to work as intended, I should have made sure we don't break your builds, I'm sorry about that.

**Comment by simllll** [comment]
Oh sorry I just saw your comment @WoH 
I've created a PR to improve the detection. Let me check how you solve it.

**Comment by simllll** [comment]
Ah great, you changed it to a warning. Like that too, if you find time please also check my PR, it improves the detection and makes it more bullet proof :-)
