### ISSUE TITLE
Is this warning correct? *partially collides* 

### ISSUE THREAD

**Issue by JimmyBjorklund** [lukeautry/tsoa#894]
We have code that works perfect using tsoa 3.4.0 ( and prior) but after upgrading to 3.5.1 i get this warning and it seams to be 
a bit strange. I would not expect this to be an issue. as it has worked for a long time.

Method setLocationConsent route: /locations/{locationId}] may never be invoked, because its route is partially collides with [Method enterOrLeaveLocation route: /locations/{locationId}/event]

  @Post("/locations/{locationId}")
  public async setLocationConsent(

  @Post("/locations/{locationId}/event")
  public async enterOrLeaveLocation(

**Comment by simllll** [comment]
I guess "locationId" could also be a string like "locationa/partB" .. and then it would be correct, not quite sure how all the frameworks handle this, as far as I remember it's not an issue with express and koa, but could be on other frameworks. 

It's just a warning, maybe allow some options to add "ignore" this warning?

**Comment by JimmyBjorklund** [comment]
Location Id is a string, and we use it with express, we have used this a long time and never seen a problem. 
An option specifying target, to remove irrelevant warnings would be nice ;)

**Comment by WoH** [comment]
We are too strict right now, this should not trigger a warning. Will be fixed in the next release

**Comment by JimmyBjorklund** [comment]
Thanks
