### ISSUE TITLE
Exporting Controller Classes as Default Export Causes TSOA to Generate Invalid route.ts

### ISSUE THREAD

**Issue by kuasha420** [lukeautry/tsoa#897]
```
src/tsoa/routes.ts(6,10): error TS2614: Module '"../api/user/controller"' has no exported member 'UsersController'. Did you mean to use 'import UsersController from "../api/user/controller"' instead?
```

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml

```

```ts
@Route('users')
export default class UsersController extends Controller {
  @Get('{userId}')
  public getUser(@Path() userId: number) {
    return UsersService.get(userId);
  }
}
```

## Current Behavior

```yaml

```

```ts
@Route('users')
export default class UsersController extends Controller {
  @Get('{userId}')
  public getUser(@Path() userId: number) {
    return UsersService.get(userId);
  }
}
```

## Possible Solution

Emit Default Exports Correctly in routes.ts

```ts
import  UsersController  from './../api/user/controller';
```

Instead of

```ts
import { UsersController } from './../api/user/controller';
```

when class is a default export. 

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [ ]

**Comment by kuasha420** [comment]
@WoH  What did I do wrong to get closed without even a response? Thank you.

**Comment by WoH** [comment]
You're suggesting an alternative way of exporting your controller which is not supported. As a framework, tsoa supports exporting controllers in a certain way, breaking that contract does not constitute a good basis for a bug report.

**Comment by kuasha420** [comment]
Understood. I just didn't realize that named exports were mandatory. Maybe it would be a good idea to mention this in the docs since (I'm assuming here) many developers put one controller per file and some famous linting configs (ie. airbnb) enables [preferdefault export](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/prefer-default-export.md) for single exports per file. 

Best regards.
