### ISSUE TITLE
Throwing `TsoaResponse` conflicts with 404 handler: cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by cakoose** [lukeautry/tsoa#899]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I set up a 404 handler this way:

```typescript
// After all other handlers
app.use('*', (_req, res) => {
    res.status(404).json({error: 'notFound'});
});
```

I use `TsoaResponse` in my controller this way:

```typescript
type SayHelloOk = string;
type SayHelloError = {type: 'idHasSpace'};

@Route('users')
export class UsersController extends Controller {
  @Get('{id}/sayHello')
  public async sayHello(
    @Path() id: string,
    @Res() error: TsoaResponse<409, SayHelloError>,
  ): Promise<SayHelloOk> {
    if (id.indexOf(' ') >= 0) {
      throw error(409, {type: 'idHasSpace'});
    }
    return `Hello, ${id}!`;
  }
}
```

The server functions correctly from the outside:

```
$ curl -i 'localhost:3000/users/goose/sayHello'
HTTP/1.1 200 OK
...
"Hello, goose!"

$ curl -i 'localhost:3000/users/go%20se/sayHello'
HTTP/1.1 409 Conflict
...
{"type":"idHasSpace"}

$ curl -i 'localhost:3000/users/goose/xyz'
HTTP/1.1 404 Not Found
...
{"error":"notFound"}
```

## Current Behavior

The problem is that on the third request, the 404 handler throws an exception:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
    at ServerResponse.header (tsoa-404-exception/node_modules/express/lib/response.js:771:10)
    at ServerResponse.contentType (tsoa-404-exception/node_modules/express/lib/response.js:599:15)
    at tsoa-404-exception/build/app.js:18:21
    ...
```

Am I setting up the 404 handler incorrectly?  Is Tsoa not correctly marking the request as "handled" when I use `TsoaResponse`?

## Steps to Reproduce

Clone this repo: https://github.com/cakoose/tsoa-404-exception

Use the instructions at the bottom of the ReadMe to run.

## Context (Environment)

Version of the library: 3.5.1 (from "yarn.lock")
Version of NodeJS: 14.15.0

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
Not how it's supposed to be used. You're invoking a function which has side effects (sending the response), then you throw an error, somewhere down the Middleware chain an error handler gets triggered which does not check if the response has already been sent -> error.
Looks like it's working as intended, but not as you expected?
