### ISSUE TITLE
--host shouldn't be required for swagger generation

### ISSUE THREAD

**Issue by danzel** [lukeautry/tsoa#9]
This configures the host field in the `swagger.json` file.

The spec says this field is optional:
http://swagger.io/specification/ (ctrl-f `host`)
And if removed from the `swagger.json` file output by `tsoa`, things still work (assuming you follow the rules they state)

**Comment by lukeautry** [comment]
Fixed in 0.0.46: https://github.com/lukeautry/tsoa/commit/325f73bfd5a297635cdd8668ee188ec4a264d1c3
