### ISSUE TITLE
How do use @Query() with an object or class? I don't want a bazillion positional arguments

### ISSUE THREAD

**Issue by tmaiaroto** [lukeautry/tsoa#900]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I was hoping for something like the following to work:

```
class finderOptions {
  @Query() email!: string
  @Query() name?: string
}

@Route("/users")
class UsersController {

 @Get()
  public async find(
    @Query() options: finderOptions
  ): Promise<any> {
  }

}
```

But I run into errors like `Can't support 'refObject' type.` ... I saw another issue about this, but it seemed like there was some sort of resolution? Though I can't find anything in documentation or source code. (I saw this https://github.com/lukeautry/tsoa/issues/353)

I have no problem getting the API to work by passing my class of options or a plain object, etc. It's the `@Query()` decorator that I want to use to get OpenAPI JSON built with the proper querystring parameters.

Everything is is _super perfect_ really awesome stuff, but I'm not insane...I can't pass positional arguments to a method that I know will change.

I'm likely not using tsoa as intended, I'm adding it on top of an existing express API I have. So I am handling the routing (which is under a versioning middleware) on my own. So I am not using `tsoa routes` command, I'm just looking to use `tsoa spec` to generate OpenAPI JSON. While positional arguments aren't the _worst_ thing ever as the method being called is pretty much just going to be limited the the function handling the route and perhaps an integration test of some sort - a change in arguments or argument order isn't the worst, but it's a _tremendous_ convenience to be able to pass a single argument. It's even more powerful when you add on top of that packages like https://github.com/typestack/class-transformer ... Because I can now easily manage the request body and querystring parameters taking parts of it, transforming, validating, etc.

Any ideas? Thanks! Super super cool package my dreams of perfect OpenAPI docs for minimal effort are almost within reach :)

**Comment by WoH** [comment]
An arg like `@Query() asdf: string` in tsoa is used to capture the query parameter `asdf`, for example `?asdf=hi`. As far as I can tell, that's not what the API would be with whatever you're trying to generate a specification for. #353 would allow for something close to the API, but not 100% similar. I'd encourage you to adapt tsoa to your needs yourself, we likely will not support any other framework's API, esp. not officially.

**Comment by WoH** [comment]
I believe the "capture all" part of the ticket would be covered in #353, the API you suggested would not be bw compat and needlessly break users when `@Query('/')` would be backwards compatible, but not compatible with your idea.

**Comment by tmaiaroto** [comment]
Sorry, I'm away from my computer, but does `@Query('/') params: { one: string, two: number }` work? Or was it an idea for something to potentially implement?

Unfortunately I'm in a spot where I need to convert a lot of stuff to use the conventions of tsoa. I don't have a very complicated api, but I do need the versioning middleware for routing. I'm really just looking for the openapi decorators so keeping docs up to date isn't such a hassle. Do you know of any other solutions for that?

Though tsoa is pretty darn close to getting me exactly what I'm after. It generated the json quite nicely.
