### ISSUE TITLE
File Upload example does not work

### ISSUE THREAD

**Issue by yangricardo** [lukeautry/tsoa#901]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [ x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I have followed the getting started pages with success on usage of Tsoa, but only with Json or Parameters data.

But when i try [File Upload](https://tsoa-community.github.io/docs/file-upload.html) section, the code just appears to be wrong about how usage of `multer`

```typescript
import { Get, Route, Security, Response } from "tsoa";
import express from "express";
import multer from "multer";

@Route("files")
export class FilesController {
  @Post("uploadFile")
  public async uploadFile(@Request() request: express.Request): Promise<any> {
    await this.handleFile(request);
    // file will be in request.randomFileIsHere, it is a buffer
    return {};
  }

  private handleFile(request: express.Request): Promise<any> {
    const multerSingle = multer().single("randomFileIsHere");
    return new Promise((resolve, reject) => {
      // undefined need to receive express.Response object
      multerSingle(request, undefined, async (error) => {
        if (error) {
          reject(error);
        }
        resolve();
      });
    });
  }
}
```

As multerSingle needs to receive an `express.Response` object, this code seems not work anymore. Also, i was not able to found a way to get this, like exists to `express.Request`.

**Comment by WoH** [comment]
You can typecast the `undefined`. Feel free to ping me to reopen if that does not work.

**Comment by JeroenMBooij** [comment]
@WoH If I follow the file upload documentation on Tsoa the result is stored in request.file instead of request.randomFileIsHere.

`import 
{
    Controller,
    Get,
    Route,
    Tags,
    Post,
    Patch,
    Delete,
    Body,
    Request
} from "tsoa";
import * as express from "express";
import * as multer from "multer";

@Tags("Files")
@Route("files")
export class OrderController extends Controller 
{

    @Post('uploadFile')
    public async UploadFile(@Request() request: express.Request): Promise<any> 
    {
        try
        {
            await this.handleFile(request);
        }
        catch(error: any)
        {
            throw new Error(error);
        }

        let test = (request as any).file;
    }



    private handleFile(request: express.Request): Promise<any> 
    {
        const multerSingle = multer().single("randomFileIsHere");
        return new Promise((resolve, reject) => {
            multerSingle(request, undefined, async (error: Error) => {
                if (error) 
                {
                    reject(error);
                }
                resolve("file will be in request.randomFileIsHere, it is a buffer");
            });
        });
    }
}`

Further more according to the documentation The OpenAPI definition can be merge-overwritten inside tsoa.json and an example for OpenAPI 2.0 (correct me if I am wrong) is provided. 

I am using OpenAPI 3.0, so my OpenAPI definition for uploading a file needs to look like this:
`"requestBody": {
					"required": true,
					"content": {
						"multipart/form-data": {
							"schema": {
								"type":"object",
								"properties":{
									"randomFileIsHere":{
										"type": "string",
										"format": "binary"
									}
								}
							}
						}
					}
				}`

However even if I copy the provided example or use the definition I require for OpenAPI 3.0 into my tsoa.json file, nothing happens. the configuration is not added to my swagger.json file when I run the tsoa swagger command.

My tsoa.json file
`{
    "entryFile": "src/app.ts",
    "noImplicitAdditionalProperties": "throw-on-extras",
    "controllerPathGlobs": [
      "src/**/*.controller.ts"
    ],
    "spec": {
      "basePath" : "/",
      "description": "",
      "outputDirectory": "dist/api/public",
      "specVersion": 3,
      "specMerging": "recursive",
      "paths": {
        "/commands/execute": {
          "post": {
            "consumes": [
              "multipart/form-data"
            ],
            "parameters": [
              {
                "in": "formData",
                "name": "randomFileIsHere",
                "required": true,
                "type": "file"
              }
            ]
          }
        }
      }
    },
    "routes": {
      "routesDir": "src/api"
    }
  }`

**Comment by tsimbalar** [comment]
In case that's useful, 


This is what we ended up for a `multipart/form-data` upload (with both files and fields)  
( partial, not the full code)

```ts
interface CoachCreationParams {
  readonly displayName: string;
  readonly avatar: Buffer;
  readonly profileImage: Buffer;
  readonly presentation: string;
}

@Tags('Coach')
@Security('bearerAuth')
@Route('/v1/coaches')
export class CoachController extends Controller {
  public constructor(private readonly coachService: CoachService) {
    super();
  }

  /**
   * Create a new coach
   */
  @Post()
  @SuccessResponse(201, 'Coach created')
  public async create(@Request() request: express.Request): Promise<{}> {
    const postedData = await this.extractAndValidateFormData(request);

    // snipped : do something with all the data we got

    this.setStatus(201);
    return {};
  }

  private async extractAndValidateFormData(request: express.Request): Promise<CoachCreationParams> {
    const FIELDS = {
      displayName: 'displayName',
      presentation: 'presentation',
      avatar: 'avatar',
      profileImage: 'profileImage',
    } as const;

    await this.readMultiFormDataFields(request, Object.values(FIELDS));

    const displayName = this.getFormFieldFromRequest(request, FIELDS.displayName);
    const presentation = this.getFormFieldFromRequest(request, FIELDS.presentation);

    const avatar = this.getFileFromRequest(request, FIELDS.avatar);
    const profileImage = this.getFileFromRequest(request, FIELDS.profileImage);

    // snipped - some extra code to validate the content of those fields and throw ValidateError if incorrect
    const extractedValues: Array<[string, any]> = [
      [FIELDS.avatar, avatar],
      [FIELDS.profileImage, profileImage],
      [FIELDS.displayName, displayName],
      [FIELDS.presentation, presentation],
    ];


    return {
      avatar: avatar!.buffer,
      profileImage: profileImage!.buffer,
      presentation: presentation!,
      displayName: displayName!,
    };
  }

  /**
   * this will populate files in the request
   * and body with posted form
   */
  private async readMultiFormDataFields(
    request: express.Request,
    fieldNames: string[],
  ): Promise<void> {
    const acceptedFields: multer.Field[] = fieldNames.map((name) => ({ name: name, maxCount: 1 }));
    const multerhandler = multer().fields(acceptedFields);
    return new Promise((resolve, reject) => {
      multerhandler(request, undefined as any, (error: any) => {
        if (error) {
          reject(error);
        }
        resolve();
      });
    });
  }

  private getFormFieldFromRequest(req: express.Request, fieldName: string): string | undefined {
    return req.body?.[fieldName];
  }

  private getFileFromRequest(
    req: express.Request,
    fieldName: string,
  ): Express.Multer.File | undefined {
    if (!req.files) {
      return undefined;
    }
    if (Array.isArray(req.files)) {
      throw new Error(
        'request.files is an array ... we expected an object with a key for each uploaded file',
      );
    }

    // multer supports multiples files/fields with the same name ... but we expect only one
    const filesForField = req.files?.[fieldName];
    return filesForField?.[0];
  }
}

```


And the following in `tsoa.json`to generate the proper OpenAPI spec 

```json
{
  /*  ...  */
  "spec": {
    "specMerging": "recursive",
    "spec": {
      "paths": {
        "/v1/coaches": {
          "post": {
            "requestBody": {
              "required": true,
              "content": {
                "multipart/form-data": {
                  "schema": {
                    "type": "object",
                    "properties": {
                      "displayName": {
                        "type": "string"
                      },
                      "presentation": {
                        "type": "string"
                      },
                      "avatar": {
                        "type": "string",
                        "format": "binary"
                      },
                      "profileImage": {
                        "type": "string",
                        "format": "binary"
                      }
                    }
                  },
                  "encoding": {
                    "avatar": {
                      "contentType": "image/png, image/jpeg"
                    },
                    "profileImage": {
                      "contentType": "image/png, image/jpeg"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by JeroenMBooij** [comment]
@tsimbalar I was missing the nested "spec" property, which is also described in the documentation, but I simply missed it. I got it working now. Thank you. I ended up with the following tsoa.json file:
```

{
    "entryFile": "src/app.ts",
    "noImplicitAdditionalProperties": "throw-on-extras",
    "controllerPathGlobs": [
      "src/**/*.controller.ts"
    ],
    "spec": {
      "basePath" : "/",
      "description": "",
      "outputDirectory": "dist/api/public",
      "specVersion": 3,
      "specMerging": "recursive",
      "spec":{
        "paths": {
          "/files/uploadFile": {
            "post": {
              "requestBody": {
                "required": true,
                "content": {
                  "multipart/form-data": {
                    "schema": {
                      "type":"object",
                      "properties":{
                        "randomFileIsHere":{
                          "type": "string",
                          "format": "binary"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "routes": {
      "routesDir": "src/api"
    }
  }
```
