### ISSUE TITLE
How to properly set response statusCode for "Typechecked Alternative Responses"?

### ISSUE THREAD

**Issue by szymon-planeta** [lukeautry/tsoa#904]
I am using "Typechecked Alternative Responses" and enabled logging with [morgan](https://github.com/expressjs/morgan) middleware and am struggling to sync the status code observed by the user that receives the response and what I observe in the server logs.
Status code is the same when I don't use any async/await calls, the proper status code that I defined is observed both in the response that the user receives and in the server logs.
As soon as I add any async/await call, the user still receives proper statusCode, but in the server logs, I observe default success response status code (200/204).

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Response status code has the same value in the response sent to the user and logged with the middleware.

## Current Behavior

I observe different statusCode reported to the user and different statusCode in the server logs (using morgan) when the controller contains async/await calls.

## Steps to Reproduce

1. Setup simple server e.g. according to https://tsoa-community.github.io/docs/getting-started.html
2. Add morgan middleware to the app
```ts
import morgan from 'morgan';
/*
...
*/
app.use(morgan('dev'));
```
3. Change `UsersController` to:
```ts
@Route("users")
export class UsersController {
  @Get()
  public async getUser(
    @Res() res: TsoaResponse<400, string>,
  ): Promise<User> {
      return res(400, 'data');
  }
}
```
4. Run the server and send the request, client properly receives response 400 and the same status is logged in the server logs by morgan
5. Now change the controller to
```ts
@Route("users")
export class UsersController {
  @Get()
  public async getUser(
    @Res() res: TsoaResponse<400, string>,
  ): Promise<User> {
      await new Promise(resolve => setTimeout(resolve, 10));
      return res(400, 'data');
  }
}
```
in the controller before the return.
6. Run the server and send the request, client properly receives response 400, but now the logger logs 204 (default success response) in the server logs.

What am I missing here?

## Context (Environment)

Version of the library: 3.5.1
Version of NodeJS: 14.15.0

- Confirm you were using yarn not npm: [x]

**Comment by szymon-planeta** [comment]
I did some debugging and I think there might be something wrong with the implementation. 
Responder function calls `returnHandler` when the route code is executed https://github.com/lukeautry/tsoa/blob/79bbde16ea0dbefc94ca2d1104c5b2692b65bc5e/packages/cli/src/routeGeneration/templates/express.hbs#L188 
but since typechecked response is not an error and doesn't throw one, `returnHandler` is executed once again when the promise is resolved https://github.com/lukeautry/tsoa/blob/79bbde16ea0dbefc94ca2d1104c5b2692b65bc5e/packages/cli/src/routeGeneration/templates/express.hbs#L164

This results in `returnHandler` being called twice for any responder if the error is not thrown (and if you're using responders I guess you don't want to throw).

For me it seems like a bug, WDYT?

**Comment by WoH** [comment]
See https://github.com/lukeautry/tsoa/issues/859

**Comment by szymon-planeta** [comment]
Ok, I think I kinda understand how these two are related, but I'm not sure if the solution for both should be the same - it's the response of tsoa itself not some 3rd party middleware.

My understanding, looking at the templates, is that the check if tsoa already replied is present in both koa and hapi:
https://github.com/lukeautry/tsoa/blob/79bbde16ea0dbefc94ca2d1104c5b2692b65bc5e/packages/cli/src/routeGeneration/templates/hapi.hbs#L186
https://github.com/lukeautry/tsoa/blob/79bbde16ea0dbefc94ca2d1104c5b2692b65bc5e/packages/cli/src/routeGeneration/templates/koa.hbs#L184

But it is missing in `express` template, which causes tsoa to reply twice?
Maybe we could add similar check to `returnHandler` for `express` template?

**Comment by WoH** [comment]
Ideally tsoa prevents writing no matter who was responsible for sending the response. The `_isTsoaResponded` i.e. would not work if some other middleware sends the response (let's say 429), but for some unexplainable reason still calls `next()` tsoa would still try i.e. the status (let's say 418) and morgan would apparently still assume it's a 418.

**Comment by szymon-planeta** [comment]
@WoH I've started working on the improvement, got couple of question and would appreciate some tips:
1. Is the start of `returnHandler` where the check should be placed? Same where `_isTsoaResponded` is checked.
2. I was thinking of checking if `headersSent` instead of `writableEnded`, WDYT? I guess it prevents writing in more situations and is compatible with more node versions.
3. Should the same check be added for koa and `hapi`? I've browsed their docs and thought to go with similar `context.headerSent` for koa, but couldn't find anything appropriate to use for hapi.
4. I'm not sure how to test it - since the response that client receives from the server is correct I couldn't figure out if this feature is testable with the current setup for integration tests?

**Comment by WoH** [comment]
1. Yes

2. `headersSent` is fine as invoking `write()` will send them.

3. I'm not sure about their API (how to get to the underlying node response), but yes.

4. Easiest repro is to get a tsoa response and call it twice. Then assert there's no longer an issue? Something like that?

**Comment by szymon-planeta** [comment]
I've added WIP PR https://github.com/lukeautry/tsoa/pull/908 and described my issues with tests
