### ISSUE TITLE
Don't assume one controller instance per request

### ISSUE THREAD

**Issue by matthewadams** [lukeautry/tsoa#906]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ x ] feature request
  - [ ] support request

- I confirm that I
  - [ x ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Allow for a single controller instance to be used for each request instead of a new controller instance per request.  What you currently have is what I would call "tear-off controllers", where they are instantiated for the request, then left to be garbage collected (putting unnecessary pressure on the garbage collector).

## Current Behavior

The current definition of `Controller`, with its instance variables, implies that a given `Controller` instance is unique to each request:
```ts
export class Controller {
  private statusCode?: number = undefined;
  private headers = {} as { [name: string]: string | string[] | undefined };

  // ...
}
```
This is problematic for us because we assemble an application-wide context that instantiates & wires our components with their dependencies using constructor injection.  In this design, a single instance of any given `Controller` handles _all_ requests routed to it, and it has no client-specific state.  Its only state is its dependencies.
```ts
// NOTE:  example of our pattern adapted from tsoa doc example

import {  Body,  Controller,  Get,  Path,  Post,  Query,  Route,  SuccessResponse } from "tsoa";
import { User } from "./user";
import { IUsersService, UserCreationParams } from "./usersService"; // note dependence on users service _interface_, not implementation

@Route("users")
export class UsersController { /* doesn't extend Controller -- it's a plain, ol' JavaScript class */
  usersService: IUsersService;

  constructor(usersService: IUsersService) { // controller receives its dependencies via constructor injection
    this.usersService = usersService;
  }

  @Get("{userId}")
  public async getUser(
    @Path() userId: number,
    @Query() name?: string
  ): Promise<User> {
    // instead of:
    // return new UsersService().get(userId, name);
    // do the following:
    return this.usersService.get(userId, name); // here, "get" is an _instance_ method on IUsersService, not static like above
  }

  @SuccessResponse("201", "Created") // Custom success response
  @Post()
  public async createUser(
    @Body() requestBody: UserCreationParams
  ): Promise<void> {
    // this.setStatus(201); // unnecessary, since @SuccessResponse decorator says to return 201 if no error is thrown
    this.usersService.create(requestBody);
    return;
  }
}
```

## Possible Solution

In order to remove the need for a controller's instance properties for `statusCode` & `headers`, the controller method could inform tsoa that it's returning something shaped like this, which tsoa could inspect in its `promiseHandler` based on configuration (new decorator described below or in `tsoa.json`):
```ts
export interface IResponse<T = any> {
  statusCode?: number = 200;
  headers?: { [key: string]: string }
  body?: T
}
```
If the controller method carries a new decorator, `@Response()`, then the `promiseHandler` would know to inspect the return value for the possible `statusCode`, `headers`, and `body` properties.  In the _absence_ of a `@Response()` decorator (the default), the returned value is assumed to be the body, as it is today.

For example:

```ts
// example of what a new method in UsersController above would look like with these features

  @Get("{fooId}")
  public async getFoo(
    @Path() fooId: number
  ): Promise<IResponse<Foo>> {
    const foo = await this.foosService.get(fooId); // assume this.foosService is of type IFoosService
    return {
      statusCode: foo?.bar === 1 ? 203 : 200, // dynamic status code calculation
      headers: foo?.bar === 1 ? { 'X-Foo': `bar=${foo.bar}` } : undefined, // dynamic headers
      body: foo
    } // (this return value conforms to IResponse<Foo>)
  }
```

With this design, there is no need to instantiate a new controller on each request, and controllers become plain, ol' classes with plain, ol' methods (albeit decorated).  Then, I can write my own implementation of `IoCContainerFactory` and `IoCContainer` that adapts my application context to your expectations, so that when you call `const controller: any = container.get<{{../name}}>({{../name}});` as you do in the templates, I can return my _sole instance_ of the controller of type `T`.

## Steps to Reproduce

N/A

## Context (Environment)

Version of the library: `tsoa@3.5.2`
Version of NodeJS: `14.15.4`

- Confirm you were using yarn not npm: [ ] (N/A)

## Detailed Description

* Make use of `Controller` optional when consumers define their own controllers
* Enhance HTTP method decorators (`@Get`, `@Post`, etc) to examine return type of method, allowing a method to return optional dynamic status codes, HTTP headers, and/or a body
* Add new decorator `@InstancePerRequest(perRequest: boolean = true)` for backward compatibility (see below)
* Enhance `promiseHandler` to
  * first, be sensitive to return type of controller method (`IResponse<T>`) that signals to tsoa that controller method return value is shaped as an `IResponse<T>` & use its values if present,
  * second, use configured `@SuccessResponse` value to return its status code and the controller method's return value if no error is thrown
* Enhance templates to not invoke `setStatusCode` and to _only_ use `IoCContainer.get()` if the controller bears an `@InstancePerRequest(false)` decoration (see "Breaking Change?" section below)
* Update documentation

## Breaking change?

This doesn't have to be a breaking change.  You could allow developers to inform tsoa globally via `tsoa.json` as to whether or not to assume a `controller-instance-per-request` strategy, or a `single-controller-instance` strategy, defaulting to the former for backward compatibility.  Additionally, instead of `tsoa.json` or in addition to it, individual controller classes could opt-in to the `single-controller-instance` strategy by including a new decorator `@InstancePerRequest(false)`

**Comment by matthewadams** [comment]
I just realized that `@Response` may be unnecessary if the return type of the method is available at decorator execution time, which I expect it is.  In this case, if the return type of the controller method is `IResult<Xxx>` or `Promise<IResult<Xxx>>`, then there is no need for `@Response`.  Updating description now.

**Comment by matthewadams** [comment]
FYI, so no one's duplicating effort, I'm going to take a stab at a PR for this.

**Comment by matthewadams** [comment]
Beginnings.... :) WIP at https://github.com/northscaler/tsoa/tree/issues/906

**Comment by matthewadams** [comment]
All existing tests passing with new functionality.  Getting ready to add tests for new functionality.

**Comment by matthewadams** [comment]
@lukeautry I just saw https://github.com/lukeautry/tsoa/blob/master/docs/CONTRIBUTING.md#contributing-features after I had already begun this work.  Could you please add the help wanted label or discuss?

**Comment by WoH** [comment]
What part of the functionality you want to introduced can't be modelled using `@Res`?

**Comment by matthewadams** [comment]
_NB: I may not fully understand what `@Res` or `TsoaResponse` do.  Please correct me if I'm wrong._

The fundamental issue that I'm dealing with using `tsoa` is that your library makes the assumption that controllers have instance state that is specific to each request:   `statusCode` & `headers`.  That is certainly one approach to controllers (often termed "tear-off controllers").  Another pattern that is _very_ common is one where controllers have _no_ request-specific instance state, and each method handles potentially concurrent requests.  The only state my controllers have are the services on which they depend.  If I extend your `Controller` class, the implication (and requirement, as far as I can tell) is that my controllers have request-specific instance state, which is false in my case.  Any given controller instance could be servicing any number of requests concurrently, and if the processing of one request changes `statusCode` then pauses (for some `await`, say) and another concurrent request completes, then the second request may return a `statusCode` that was set by the preceding request, which is not correct.

If you remove the assumption that a new controller must be instantiated for each request, you not only decrease pressure on the garbage collector, but also can support the pattern where a single instance of a controller can support simultaneous requests without clobbering each other.  The corollary to this is that everything that needs to be given and returned in a request must pass into and out of the controller's methods without changing the controller's instance state.

In some cases, the status code that you want to return is dynamically calculated rather than statically known at design time.  This is where I might be confused.  If `@Res` or `TsoaResponse` allows me to _dynamically_ (meaning at run-time) return any status code, then the only enhancement this PR provides for is to be able to have a single controller instance simultaneously handle multiple requests.  If not, however, this PR will additionally ensure that a controller author can dynamically calculate at run-time whichever status code they wish to return, rather than fixing it at design time.

Capice?  I'd be happy to have a video chat with you to discuss, too, in case I'm misunderstanding something about `tsoa`.  Just send me an invitation at matthew@matthewadams.me.

**Comment by matthewadams** [comment]
I've looked at some of your tests that use `@Res` & `TsoaResponse`.  Is it possible for a controller method to _return_ an instance of `TsoaResponse`, rather than taking an argument decorated with `@Res()`?

**Comment by WoH** [comment]
From the [docs](https://tsoa-community.github.io/docs/error-handling.html#typechecked-alternate-responses):

```ts
import { Route, Controller, Get, Query, Res, TsoaResponse } from 'tsoa'

@Route('/greeting')
export class GreetingsController extends Controller {
  /**
   * @param notFoundResponse The responder function for a not found response
   */
  @Get('/')
  public async greet(@Query() name?: string, @Res() notFound: TsoaResponse<404, { reason: string }>): Promise<string> {
    if (!name) {
      return notFound(404, { reason: "We don't know you yet. Please provide a name" });
    }

    return `Hello, ${name}`;
  }
```
