### ISSUE TITLE
Feature Request: Servers Swagger Property In tsoa.json (Tsoa Config)  

### ISSUE THREAD

**Issue by FahdAlShalhoub** [lukeautry/tsoa#909]
## Sorting

- **I'm submitting a Feature Request**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
 Much like "securityDefinitions", I'd highly appreciate if there is a "serverDefinitions" array where  I write all of my servers info (As specified in the Swagger/openAPI Standard) and have it pasted into the swagger servers property on spec generation

**Comment by ferfrey** [comment]
Hello! Hope this helps and is what you're referring to:

![image](https://user-images.githubusercontent.com/2099565/109343755-948c4380-784c-11eb-901c-618385d75f5c.png)

that's in the tsoa.json file, you can add a prop "spec" under "spec" and according to documentation in code it will

> Extend generated swagger spec with this object
> Note that generated properties will always take precedence over what get specified here

[here ](https://github.com/lukeautry/tsoa/blob/master/packages/runtime/src/config.ts#L129) is the link to source code.

Regards, 
Fernando
