### ISSUE TITLE
Add an override in tsoa.json to allow models to come from external modules

### ISSUE THREAD

**Issue by jeffmounce** [lukeautry/tsoa#912]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x ] feature request
  - [ ] support request

- I confirm that I
  - [x ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Generate swagger using interfaces in external modules if I want to when I know the risks/concerns.

## Current Behavior

https://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD

## Possible Solution

Add a config entry in tsoa.json to allow for interfaces to be defined in external modules.

## Steps to Reproduce

n/a

## Context (Environment)

all 

## Detailed Description

Monorepos... Monorepos!

## Breaking change?

No

**Comment by WoH** [comment]
Closing as duplicate

**Comment by jeffmounce** [comment]
Link for dup?
