### ISSUE TITLE
nullable array of enum request body not handled correctly

### ISSUE THREAD

**Issue by cakoose** [lukeautry/tsoa#913]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The request body should not be altered incorrectly.

## Current Behavior

```ts
import { Route, Controller, Post, Query, Res, Body } from 'tsoa'

enum Color {
  red = 'red',
  blue = 'blue',
  green = 'green',
}

type T1 = {
  colors: Array<Color> | null;
};

@Route('/blah')
export class BlahController extends Controller {
  @Post('/f1')
  public async f1(
    @Body() arg: T1,
  ): Promise<string> {
    console.log('inside controller:', JSON.stringify(arg));
    return 'blah';
  }
}
```

Issue a request:

```
curl localhost:3000/blah/f1 -X POST -H 'Content-Type: application/json' -d '{"colors": null}'
```

The server has code to print out the request body before the controller, and I see:

```
before controller: {"colors":null}
inside controller: {"colors":[null]}
```

The value inside the controller is wrong.

## Steps to Reproduce

Full runnable example: https://github.com/cakoose/tsoa-bug/tree/issue-913

## Context (Environment)

Version of the library: 3.5.2
Version of NodeJS: 14.15.0

- Confirm you were using yarn not npm: [x]

## Detailed Description

See above.

## Breaking change?

Probably not breaking, since the current behavior seems like a bug.

**Comment by WoH** [comment]
Seems like we coerce null into `Color` which is probably not desirable.

If you don't want the issue to happen, typing this as `null | Color[]` would work fine.

**Comment by WoH** [comment]
Can you check if #994 does indeed fix this? I suppose it will, but your scenario adds another layer on top.
