### ISSUE TITLE
"Overlapping path parameter" false positive

### ISSUE THREAD

**Issue by cakoose** [lukeautry/tsoa#914]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

No warning.

## Current Behavior

```ts
import { Route, Controller, Post, Query, Res, Path } from 'tsoa'

@Route('/')
export class BlahController extends Controller {
  @Post('{userId}/abc')
  public async f1(
    @Path() userId: string,
  ): Promise<string> {
    return 'blah';
  }
  @Post('{userId}/abcdef')
  public async f2(
    @Path() userId: string,
  ): Promise<string> {
    return 'blah';
  }
}
```

When I run `tsoa spec-and-routes`, I get a warning:

```
Overlapping path parameter definition signature found in controller BlahController [ method POST f2 route: {userId}/abcdef ] collides with [ method POST f1 route: {userId}/abc ]
```

## Steps to Reproduce

See above.

This didn't happen in 3.5.1.  It started happening in 3.5.2.

## Context (Environment)

Version of the library: 3.5.2
Version of NodeJS: 14.15.0

- Confirm you were using yarn not npm: [x]

**Comment by laktak** [comment]
I have the same problem with

```
Overlapping path parameter definition signature found in controller PostController [ method GET getTodo route: /:id ] collides with [ method GET getTodos route: / ]
```

This might be caused by a dependency though - even if I go back to `3.5.0` I still get the error now.

**Comment by WoH** [comment]
Pinging @simllll

**Comment by simllll** [comment]
I will look into it, I guess I just haven't covered all cases yet.
