### ISSUE TITLE
Missing support for oneOf

### ISSUE THREAD

**Issue by carlnordenfelt** [lukeautry/tsoa#917]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
It should be possible to define a request that accepts a `oneOf` parameter.

## Current Behavior
I have looked through the code and issues and it appears that support for `oneOf` was dropped (#671) after being added (#400).

I won't debate wether or not the changes that stemmed from #671 make sense or not but I for one still need support for `oneOf`.  At least in my experience, `oneOf` is used a lot more often than `anyOf` & `allOf` as it is usually that the case that an API accepts _either_ A or B, not an intersection of the two.

## Possible Solution

N/A. I am new to typescript and can't really speculate as to what type of language construct would accommodate `oneOf` without breaking the current implementation.

## Steps to Reproduce

N/A

## Context (Environment)

Version of the library: 3.5.2
Version of NodeJS: v15.x

- Confirm you were using yarn not npm: [ ]

## Detailed Description

N/A

## Breaking change?

N/A

**Comment by fantapop** [comment]
@carlnordenfelt Can you talk more about your use case for `oneOf`? Are you doing client generation from the generated open api document? If so what openapi generator template are you using?

**Comment by carlnordenfelt** [comment]
Hi @fantapop,

The use case for `oneOf` is quite literally the purpose of it; I have an API endpoint where one property, or the entire request, can be _either_ A or B. Not a union of them (`anyOf`) and not all of them (`allOf`) but exactly one of them.

Most of the time A and B will represent the same thing in the end but we have slightly different required fields depending on what is provided. 
Perhaps not the best example and certainly not in our domain but: "If you give us a social security number you can skip a lot of other info but if you don't, first name and last name is required." Either you give us the SSN  _or_ you give us the names. If you give us both we won't accept the request.

The swagger docs further describe this quite well: https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#oneof

**Comment by carlnordenfelt** [comment]
I actually came across a live example from our API that illustrates the need very well.
I've just renamed the attributes in this schema.

Basically we want one of the following and anyOf wouldn't meet our requirements:

* idType1 [& idType3]
* idType2 [& idType3]
* idType3 & name

```
schema: {
    type: 'object',
    oneOf: [
        {
            required: [
                'idType1'
            ],
            additionalProperties: false,
            properties: {
                idType1: {
                    type: 'integer',
                },
                idType3: {
                    type: 'string',
                },
            },
        },
        {
            required: [
                'idType2'
            ],
            additionalProperties: false,
            properties: {
                idType2: {
                    type: 'integer',
                },
                idType3: {
                    type: 'string',
                },
            },
        },
        {
            required: [
                'idType3',
                'name'
            ],
            additionalProperties: false,
            properties: {
                idType3: {
                    type: 'string',
                },
                name: {
                    type: 'string',
                },
            },
        },
    ],
},
```

**Comment by WoH** [comment]
We model the OAPI Schema based off TS, and TS allows this:

```ts
interface TypeOne {
  idType1: number,
  idType3?: string
}

interface TypeTwo {
  idType2: number,
  idType3?: string
}

interface TypeThree {
  idType3: string,
  name: string
}

type Validator = TypeOne | TypeTwo | TypeThree;

const validated: Validator = {
  idType1: 1,
  idType2: 2,
  idType3: "hi",
  name: "hi"
}
```

Therefore, anyOf is a better match to represent Unions. However, that does obviously not mean you can't discriminate between the types in your code.

**Comment by fantapop** [comment]
@carlnordenfelt The reason I ask about the client generation is because there is a lack of support for generating clients in open api for this construct last I checked. I couldn't find any languages which implemented this to spec.  I'm curious to know if you find otherwise.

**Comment by carlnordenfelt** [comment]
@WoH 
> Therefore, anyOf is a better match to represent Unions. 
Yes, I agree that `anyOf` is a suitable representation of TypeScript unions.
The problem with `anyOf` and the example is that this would be a valid request whereas we would find a conflict because both idType1 & idType2 are provided. The only way to solve this problem is to add custom validation in the controller.
```
{
  idType1: 'a',
  idType2: 'b',
  name: 'foo'
}
```

@fantapop 
> @carlnordenfelt The reason I ask about the client generation is because there is a lack of support for generating clients in open api for this construct last I checked. I couldn't find any languages which implemented this to spec. I'm curious to know if you find otherwise.

I did a little more digging into this and it turns out that AWS API Gateway doesn't support `oneOf` either.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html
This does take the pressure off a little but I still stand by my initial point that `oneOf` is a construct that should be supported.
Again, I don't really have a suggestion as to how one would achieve that apart from adding a specific annotation which might be able to solve the issue.

Perhaps this issue should be flagged as a nice to have feature?

**Comment by WoH** [comment]
> This does take the pressure off a little but I still stand by my initial point that oneOf is a construct that should be supported.
Again, I don't really have a suggestion as to how one would achieve that apart from adding a specific annotation which might be able to solve the issue.

Let's revisit this when there's a more specific proposal available. OneOf validation is pretty tricky.
