### ISSUE TITLE
How to specify a prefix route or a basepath

### ISSUE THREAD

**Issue by cddemar** [lukeautry/tsoa#923]
Hi! I'm new using tsoa and it is fantastic. The one thing that I can't find how to do or get around of it is to specify a sort of prefix for all the controllers such as 'api/v1'.

**Comment by kYem** [comment]
To specify route prefix, you need to set  `routes.basePath` property in your `tsoa.json` file 
```json
{
  "routes": {
    "basePath": "/api/v1"
  },
}
```
or pass it as cli option with `--basePath /api/v1`

**Comment by cddemar** [comment]
Thanks!
