### ISSUE TITLE
Anonymous functions in route templates make tracing by tools such as NewRelic difficult

### ISSUE THREAD

**Issue by sambernard** [lukeautry/tsoa#926]
The use of anonymous functions for route handlers + authentication middleware makes it hard to debug performance issues.

For example, in NewRelic, I get the following traces: 

<img width="737" alt="skitch" src="https://user-images.githubusercontent.com/170295/109341940-61d05400-7828-11eb-8e5e-93a85a7f4e19.png">

<img width="968" alt="skitch (1)" src="https://user-images.githubusercontent.com/170295/109341937-5f6dfa00-7828-11eb-80e6-61f469fe56af.png">

The `Nodejs/Middleware/Expressjs/<anonymous>` portions are the route handler and the authentication middleware used by my app.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The templates should provide names to middleware / route functions so that they be debugged more easily.

## Current Behavior

The functions are anonymous.

## Possible Solution

Within the route templates:

1. Add names to route functions in the format of `Controller_function` - for example change
```hbs
function (request: any, response: any, next: any) {
```
to
```hbs
function {{../name}}_{{name}}(request: any, response: any, next: any) {
```

2. Name the function returned by `authenticateMiddleware` - eg change
```
    function authenticateMiddleware(security: TsoaRoute.Security[] = []) {
        return (request: any, _response: any, next: any) => {
```

to

```
    function authenticateMiddleware(security: TsoaRoute.Security[] = []) {
        return function runAuthenticationMiddleware(request: any, _response: any, next: any) {
```

## Steps to Reproduce

1. Set up new relic (or similar)
2. Generate traces by making requests
3. Observe anonymous functions

## Context (Environment)

Version of the library: 3.5.2
Version of NodeJS: v14.11.0

- Confirm you were using yarn not npm: [X]

**Comment by sambernard** [comment]
If this approach looks good, I'm happy to open a PR for it, as the change is pretty straightforward.

**Comment by WoH** [comment]
I think this should be helpful, feel free to submit a PR. I'm not sure why there's no span for the call to the controller method that tsoa calls, what am I missing here?

**Comment by sambernard** [comment]
Great- will do!

I don't really understand how the tracing works, but I think the fact that the controller method is enclosed in an anonymous function causes it to stop tracing any further.
