### ISSUE TITLE
Question about complex query string parameter reuse

### ISSUE THREAD

**Issue by taschmidt** [lukeautry/tsoa#935]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I have an existing API that I'm trying to port over to tsoa and I'm hung up on how to easily do it in a way that makes sense and is maintainable. Essentially, I have a set of options to an internal service that are defined as an interface. For example:

```ts
interface ServiceOptions {
  optionA?: string;
  optionB?: boolean;
  optionC?: number;
}
```

These options are common across a number of API methods and I'd really rather not duplicate it since the above example is greatly simplified, the number of options is over a dozen. Ideally, I would do the documentation on the interface itself with jsdoc and then use the interface on each method but I can't get that to work. I tried getting cute and doing `@Query() ...opts: ServiceOptions` but I get the error "error TS2370: A rest parameter must be of an array type".

Is there an easy way to do this?

**Comment by taschmidt** [comment]
Does anyone know if this is possible?

**Comment by taschmidt** [comment]
Ping

**Comment by WoH** [comment]
Your suggested API won't work, as TS indicates. 
There is currently no easy way to do this, but there are similar open issues.
