### ISSUE TITLE
Unable to generate Route level descriptions

### ISSUE THREAD

**Issue by oegonzalts** [lukeautry/tsoa#936]
## Sorting

- **I'm submitting a ...**

  - [ x] bug report
  - [ x] feature request
  - [ ] support request

- I confirm that I
  - [ x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Expected behavior is to try jsdoc doc generation formatting on class controller to create description at a controller level
Tried with @summary, @description, @classdesc

Swagger doc should generate controller/route level description

## Current Behavior

No controller level description gets generated 

## Steps to Reproduce

Try adding comment like this over a class: 

/**
 * Try here
 * @summary try here
 * @description try here
 * @classdesc try here
 * 
 */
@Route("v2/users")
@Tags("Users")
@Response<E_SERVER_ERROR_500>(500, "Internal Server Error")
export class UsersV2Controller extends Controller {
    ...
}

Is this supported with the current tsoa version to get controller level descriptions into the OAS generated file?

**Comment by WoH** [comment]
Where in the OAS should they show up?

**Comment by speed-of-light** [comment]
I believe you'll need something defined in `tsoa.json` in path `spec.tags[*].description`, where `spec.tags[*].name` should match the tag in @Tags(), and that works for me.
