### ISSUE TITLE
Json Spec files should output spaces instead of tabs

### ISSUE THREAD

**Issue by RBornost** [lukeautry/tsoa#937]
## Sorting

- **I'm submitting a ...**

  - [ X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [ X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Spec files should not have tabs (json files specifically tested).
Using 'npx @stoplight/spectral lint --verbose ./src/swagger/openapi.json'
should NOT return 'warning parser Using tabs can lead to unpredictable results'

## Current Behavior

Using 'npx @stoplight/spectral lint --verbose ./src/swagger/openapi.json'
returns 'warning parser Using tabs can lead to unpredictable results'

## Possible Solution

on line 42 of the following snippet

```javascript
let data = JSON.stringify(spec, null, '\t');
```
https://github.com/lukeautry/tsoa/blob/fd1915f9506e9cff8368a2c2cc404bc8336e668c/packages/cli/src/module/generate-spec.ts#L42-L45

replace the '/t' with 2 or 4

## Steps to Reproduce

Generate a spec with version 3.5.2
Using `npx @stoplight/spectral lint --verbose ./src/swagger/openapi.json`

**Comment by WoH** [comment]
Don't think this is a bug at all. Is there any reference in the JSON standard(s) you can point me to (why tabs may be causing issues) that I may not be aware of?

**Comment by RBornost** [comment]
I am not sure about the JSON spec. But how I discovered this "problem" is following the TSOA docs. In them it mentions using stoplight/spectrum to validate the Open Api file. In doing so it outputs thousands of lines of warnings regarding the tabs. The "rule" cannot be turned off as it considers it a parsing error. Effectively hiding all other warnings.

**Comment by WoH** [comment]
Will there are several things to consider:
1) Is this a bug in tsoa? Given the provided details I'd say no.
2) Is the output json something spectral's parser should be able to handle? I'd argue yes, but that shouldn't be tracked here.
3) Is it a problem you can't turn these parser warnings off? Yes, but again, that's a spectral issue (which is being tracked at https://github.com/stoplightio/spectral/issues/1550)
4) Should we use spaces instead of tabs in the json output? I personally don't have a strong opinion either way, but if someone sends me a PR to change this, there's no reason to reject it.

**Comment by RBornost** [comment]
I have be utilizing prettier to work around this. It is a pain, but workable.

**Comment by RBornost** [comment]
If there is no interest in fixing this please close.

**Comment by gitizenme** [comment]
👍  would like this to be implemented

**Comment by apokryfos** [comment]
I find it a bit crazy that the docs state that "they love spectral" and yet the default output on a standard spectral setup will raise a warning about every single line.

**Comment by awildeep** [comment]
> I find it a bit crazy that the docs state that "they love spectral" and yet the default output on a standard spectral setup will raise a warning about every single line of the generated spec.

Agreed.  There appears to be no option to stop output with tabs, yet spectral hates tabs.  How much love is there for spectral if it hates the specs your code generates?
