### ISSUE TITLE
Using 'useSuccessResponseCode' doesn't set response code

### ISSUE THREAD

**Issue by brian-pinwheel** [lukeautry/tsoa#938]
The code change in PR #850 was awesome.  

## Sorting

- **I'm submitting a ...**

  - [ X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

When using SuccessResponse, it should return the response defined in the SuccessResponse.

## Current Behavior

For performance, I am using a singleton Controller.  My create method needs to return a 201, but since the status is shared across all methods, the 201 was "leaking" to other requests.

When I found the feature to use SuccessResponse, I thought it solved my problems.  Unfortunately, it didn't. When I got it enabled, I saw the routes.js was generated successfully.  Unfortunately, the value was being overwritten by an undefined value.  

Specifically, the if statement for isController is executed because I am using the controller.  Hence, the value from my SuccessResponse is passed into the method correctly, but overwritten by an undefined value.

```
            let statusCode = successStatus;
            let headers;
            if (isController(controllerObj)) {
                headers = controllerObj.getHeaders();
                statusCode = controllerObj.getStatus();
            }
```

## Possible Solution

Don't overwrite the value if the status from the controller.getStatus is undefined.  This makes existing behavior work along with it working as expected (passing the SuccessResponse)

## Context (Environment)

Version of the library: 3.5.2
Version of NodeJS: 12

- Confirm you were using yarn not npm: [ X]

## Breaking change?

Should not break

**Comment by WoH** [comment]
Closed by #939
