### ISSUE TITLE
Requests with "null" values in payload are rejected during TSOA Validation but "undefined" are passing.

### ISSUE THREAD

**Issue by penaczko** [lukeautry/tsoa#941]
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior

For example - request body for one of our endpoint looks like: 
```
export interface TestInterface {
  firstField: string;
  secondField?: AnotherTestInterface;
  thirdField?: Number;
}
```

and in our `routes.ts` we have:
```
...
const models: TsoaRoute.Models = {
    "TestInterface": {
            "dataType": "refObject",
            "properties": {
                "firstField": {"dataType":"string","required":true},
                "secondField": {"ref":"AnotherTestInterface"},
                "thirdField": {"dataType":"double"}
            },
            "additionalProperties": true,
        }
}
...
```

My question is - why `null` values are not passing tsoa validation, but `undefined` does? Shouldn't be treated in the same way? Don't you guys think that `null` values should also pass tsoa validation?

## Possible Solution

In 17 line in [Validation Service](https://github.com/lukeautry/tsoa/blob/fd1915f9506e9cff8368a2c2cc404bc8336e668c/packages/runtime/src/routeGeneration/templateHelpers.ts#L12)  there should be also check if `value` equals `null`:
```
if (value === undefined || value === null) {
.
.
.
}
```

## Steps to Reproduce

In case described above - just send request with following payloads
    That request doesn't pass tsoa validation:
```
{
    "firstField": "TEST",
    "secondField": null
}
```
That request pass tsoa validation:

```
{
    "firstField": "TEST",
    "secondField": undefined,
    "thirdField": undefined
}
```

## Context (Environment)

Version of the library: "3.5.2"
Version of NodeJS: "12.21.0-alpine"

- Confirm you were using yarn not npm: [ ]

## Detailed Description

I want to clarify that situation with that two values - `null` and `undefined`

**Comment by WoH** [comment]
> My question is - why null values are not passing tsoa validation, but undefined does? Shouldn't be treated in the same way? Don't you guys think that null values should also pass tsoa validation?

No

**Comment by penaczko** [comment]
Ok, so how about `undefined`? Why requests with `undefined` are passing?

**Comment by tsimbalar** [comment]
`undefined` is not valid in JSON 🤔 

(`JSON.stringify({'foo': undefined})` throws )

```js
{
  'foo': 'value',
  'toto': undefined
}
```

is equivalent to


```js
{
  'foo': 'value',
}
```


`undefined` or `property?` means the property is optional. `null` means the property should be there , but has the value `null`

**Comment by penaczko** [comment]
What I send is:
```
{
    "test": null
}
```

What message I can see:

 ```
 [
     {
         keyword: 'type',
         dataPath: '.test',
         schemaPath: '#/test/type',
         message: 'should be object',
         data: null
     }
 ]
 ```
 
 But when I send request with following body:
 ```
 {
     "test": undefined
 }
 ```
 
 I receive `200` as status Code and there is no any message about some problems during payload validation.

**Comment by tsimbalar** [comment]
@penaczko is it ok to close this issue ?

**Comment by penaczko** [comment]
Sure, thanks again.

**Comment by Kampfmoehre** [comment]
Sorry if I answer this old issue but I currently face the same problem and do not understand the logic here. I have a model with an optional property:
```ts
export interface NewUser {
  // ...
  externalUserId?: string;
}
```
which is generated to
```json
{
  "NewUser": {
    "dataType": "refObject",
    "properties": {
      // ...
      "externalUserId": {"dataType":"string"},
    },
    "additionalProperties": true,
  }
}
```

So for me the following JSON is perfectly valid
```json
{
  // ...
  "externalUserId": null
}
```
If the property is completely missing in JSON, TSOA validation is fine with it, why not with null?

The JSON in this case is generated by a .NET application where there is adifference between empty strings (e.g. `""`) and null and the JSON converter needs to be modified to leave out the property instead of generating `"property": null`.

Is there anything I can do on the TSOA side to make this work?

**Comment by tsimbalar** [comment]
Hi @Kampfmoehre 

`?` means "optional" as in "not present in the payload" , so this : 

```ts
export interface NewUser {
  // ...
  externalUserId?: string;
}
```

will accept payloads like : 

```json
{
  "externalUserId": "something"
}
```

```json
{
  "externalUserId": ""
}
```

or

```json
{
}
```


if you want this to be accepted : 

```json
{
  "externalUserId": null
}
```

then the type should be 

```ts
export interface NewUser {
  // ...
  externalUserId: string | null;
}
```

(or this if you also want to make it optional 

```ts
export interface NewUser {
  // ...
  externalUserId?: string | null;
}
```

)


There is a difference between "optional" (i.e.the property does not need to be present at all ... and have a nullable value )

**Comment by Kampfmoehre** [comment]
@tsimbalar Thanks for the quick response. I thought that I already tried that and got the same error, however I just tried it again and this time it works.
