### ISSUE TITLE
@FormField - properties should be marked as non-optional

### ISSUE THREAD

**Issue by tsimbalar** [lukeautry/tsoa#945]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

When using the `FormField('myField')` annotation on a argument in a controller method, that field should be considered required, and documented as such in the Open API spec.

Given the following method : 

```ts
public async create(
    @FormField('displayName') displayName: string,
    @FormField('presentation') presentation: string?,
  ): Promise<{}> {
```

the Open API spec should look like this : 

```yaml
        post:
            operationId: Create
            parameters: []
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                displayName:
                                    type: string
                                presentation:
                                    type: string
                            required:
                              - displayName
```

## Current Behavior

`@FormField` annotated argument are always considered optional in the generated doc.
oa actually generated  -->

```yaml
        post:
            operationId: Create
            parameters: []
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                displayName:
                                    type: string
                                presentation:
                                    type: string
```

## Possible Solution
?

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: v3.6.1
Version of NodeJS: v14.16.0 (current LTS)

- Confirm you were using yarn not npm: [ ] - using `npm`

## Breaking change?

This might be a breaking change for current users of `@FormField` as properties would now be considered required ... I do consider it an improvement though. 

Note : this is similar to #942 , but applied to `@FormField`s instead of `@UploadedFile`

**Comment by pauliyobo** [comment]
Hello. I believe this issue should be closed, as I see the PR that was merged included this issue in the list of issuses that it would fix.

**Comment by WoH** [comment]
Seems like that is the case.
@tsimbalar please ping me if this is still an issue, and I'll reopen.
