### ISSUE TITLE
In the latest version, custom http error codes cause compile issues. 

### ISSUE THREAD

**Issue by JimmyBjorklund** [lukeautry/tsoa#947]
In the latest version, custom http error codes cause compile issues. 

`error TS2345: Argument of type '441' is not assignable to parameter of type '"default" | 100 | 101 | 102 | 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 226 | 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308 | 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | ... 90 more ... | "5XX"'.
`

```

  @Get()
  @Security("apikey+jwt")
  @Response(200, "OK")
  @Response(441, "Oauth Login Required")
  public async getHomes(): Promise<Home[]> {
    return this.x.getHomes();
  }
```

**Comment by WoH** [comment]
Please use declaration merging to allow for custom status codes without TS Errors. As some of the underlying frameworks may have issues, we probably don't want to support them officially.

**Comment by WoH** [comment]
I assume this worked out fine, if there are any issues with the suggested approach, I'll happily reopen the discussion

**Comment by rlubaschewski** [comment]
@WoH could you provide an example on how to allow for a custom status code (let's say 600) with declaration merging? 
Not quite sure, how this is accomplished.
