### ISSUE TITLE
How to use custom middleware?

### ISSUE THREAD

**Issue by zxxc** [lukeautry/tsoa#948]
Currently, we are moving a lot of non business logic in middleware
and using them per route, for example:

```
router.post('/some/path', accountValidator, userValidator, prometheusMetrics, someOtherMiddleware, myController.getSomethingUseful);
```
How can i add custom middlewares to automatically generated routes.ts?
Are there any other ways like custom decorators or base controller that I should consider using with tsoa?
I think I'm fine migrating custom middlewares to something else but I don't understand what is an alternative tsoa way of doing this?

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I expected to find some 
`@Middleware` decorator or a guide how to create custom decorators

## Current Behavior

@Route decorator doesn't have options parameter where i could add functions or middleware to execute before or after main haindler

## Possible Solution

* add an options to @Route ('/my/path', { before: promMetrics } )
* add a custom @Middleware decorator
* add a documentation how to add custom shareable code

- Confirm you were using yarn not npm: [ npm]

**Comment by panwauu** [comment]
Were you able to resolve the issue?

**Comment by cheng81** [comment]
Sounds like I'm late to the party, but in my company we want to use `tsoa` and would really love to be able to use custom middlewares, so I made a PR to do just that, and I would love some feedback.

**Comment by marklawlor** [comment]
@cheng81 Thanks for the PR :partying_face:  Is there any change you can update it to include error middleware as well? This middleware should be included after the controller middleware.

Maybe via a new directive `ErrorMiddlewares`?

**Comment by RevanthGovindan** [comment]
@cheng81 could you pls add working example here, since @middleware doesn't works as expected
