### ISSUE TITLE
Super decorator

### ISSUE THREAD

**Issue by zxxc** [lukeautry/tsoa#949]
I have to copy-paste the same number of parameters:
```
@Route('/public')
export class AccountsController extends Controller {

  @Get("accounts")
  public async getAccounts(
    @Header('x-account-id') account_id: string,
    @Header('x-correlation-id') correlation_id: string, //i need this to be shown on swagger.json
    @Header('x-user-id') user_id: string, //i need this to be shown on swagger.json
  ): Promise<AccountsGetResponse> {
return await service.getAccounts(account_id)
  }
  @Get("approved")
  public async getApprovedAccounts(
    @Header('x-account-id') account_id: string,
    @Header('x-correlation-id') correlation_id: string, //i need this to be shown on swagger.json
    @Header('x-user-id') user_id: string, //i need this to be shown on swagger.json
  ): Promise<AccountsGetResponse> {
return await service.getApprovedAccounts(account_id)
  }

@Get("deleted")
  public async getDeletedAccounts(
    @Header('x-account-id') account_id: string,
    @Header('x-correlation-id') correlation_id: string, //i need this to be shown on swagger.json
    @Header('x-user-id') user_id: string, //i need this to be shown on swagger.json
  ): Promise<AccountsGetResponse> {
return await service.getDeletedAccounts(account_id)
  }
}


```

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I need a way to create maybe some super decorator to combine
  @Header('x-account-id') account_id: string,
  @Header('x-correlation-id') correlation_id: string, //i need this to be shown on swagger.json
  @Header('x-user-id') user_id: string, //i need this to be shown on swagger.json

to avoid copy paste
## Current Behavior

Just a lot of copy-paste in all my methods

**Comment by WoH** [comment]
Same thing with Query is being discussed here, I'll merge the discussion as it's the same underlying API that's being requested: https://github.com/lukeautry/tsoa/issues/353
