### ISSUE TITLE
Add support for header decorator on method

### ISSUE THREAD

**Issue by hasyimibhar** [lukeautry/tsoa#955]
It would be nice to have a decorator similar to `@Header` that works on method or class. Example use case: for certain requests, I have a middleware which requires certain custom headers to be present. But outside of the middleware, these headers are not used. Currently it's possible to achieve this by doing this:

```ts
class FoobarController {
  foobar(
    @Header() header1: string,
    @Header() header2: string
  ) {
    // ...
  }
}
```

But it's annoying because `header1` and `header2` aren't used by `foobar`, so there will be compiler warnings.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Something like this:

```ts

class FoobarHeader {
  header1: string;
  header2: string;
}

class FoobarController {
  @MethodHeader(FoobarHeader)
  foobar() {
    // ...
  }
}
```

## Current Behavior

Instead of this:

```ts
class FoobarController {
  foobar(
    @Header() header1: string,
    @Header() header2: string
  ) {
    // ...
  }
}
```

## Possible solution

I'm guessing the implementation will be similar to the `@Extension` decorator. If the idea makes sense, I'm willing to contribute to implement it.

**Comment by WoH** [comment]
The feature is similar to #949, the API i'd prefer is outlined in https://github.com/lukeautry/tsoa/issues/353
