### ISSUE TITLE
Extensions don't allow scalar / primitive values

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#958]
`@Extension('x-internal','true')`

Creates: 

`"x-internal": "true"` as expected.

`@Extension('x-internal',true)` a primitive type like a bool / int won't be serialized

**Comment by WoH** [comment]
This could be supported, as the spec [says](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#specificationExtensions):
```
The value can be null, a primitive, an array or an object. Can have any valid JSON format value.
```

**Comment by mhyeun** [comment]
Hi! I found the `tsoa` library to be really useful and was hoping to get into contributing to open-source projects.

Could I take on this issue?

**Comment by WoH** [comment]
Sure! No need to ask, but esp. issues marked as "help wanted" are great candidates for PRs
