### ISSUE TITLE
"emitDecoratorMetadata": false, supported or not?

### ISSUE THREAD

**Issue by mscottnelson** [lukeautry/tsoa#961]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Detailed Description

I am attempting to evaluate tsoa for suitability in my stack. 

We use esbuild to produce a bundle. esbuild *DOES* support the tsconfig of "experimentalDecorators": true, but *DOES NOT* support "emitDecoratorMetadata": true. I am seeking to understand in what ways tsoa requires emitDecoratorMetadata (if at all). Can someone help me understand if this is necessary? If it is necessary, is there either 1) a workaround for using tsoa without decorators or 2) a recommended way to approach this problem (eg, isolating the controllers in some specific way).

Many thanks!

**Comment by WoH** [comment]
I'm not aware of any lines where we rely on TS's metadata decoration (as it's so limited anyway)

**Comment by mscottnelson** [comment]
That’s great. I also did a cursory glance through the code and it appeared that way. I’m going to forge ahead. 

If I happen to run into any issues specifically with using this in an esbuild context (where type checking is still performed by typescript, but not generating code), then I’ll try to remember and come back to update this issue for documentation purposes. But based on your assurance and from looking over the decorator code, I don’t anticipate any problems.
