### ISSUE TITLE
Can generateSpecAndRoutes please be a module export?

### ISSUE THREAD

**Issue by mscottnelson** [lukeautry/tsoa#964]
Hello, I'm wondering if you would mind exposing/re-exporting the generateSpecAndRoutes function? And also allow me to pass in the configuration object manually at this point (ie, ConfigArgs referenced by generateSpecAndroutes would be of type `string | Config`? I'd like to bundle this in with my existing build system and it would be convenient for this to be directly exposed.

I'm already watching my filesystem, and the rest of my build process and build configuration (using esbuild) is colocated. It would help consolidate both process and documentation for me to be able to codify in the same place as everything else in our build that:

"Whenever these controller files change, run generateSpecAndRoutes". I could just replicate what you're already doing with that function, but it would be nice to gain ongoing compatibility with whatever updates/improvements/changes you end up making down the road.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
import { generateSpecAndRoutes } from 'tsoa';

generateSpecAndRoutes({
  configuration: { 
    routes: {
      routesDir: "src/server"
      //...etc
     },
    spec: {
      specVersion: 3 
      // ...etc
    }
  }
});
```

## Current Behavior

```ts
import { generateSpecAndRoutes } from 'tsoa' // no exported member
```

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 
Version of NodeJS: 

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
We expose `generateSpec` and `generateRoutes`. Any reason why you need the combined one aswell?

**Comment by mscottnelson** [comment]
Not especially, was mostly to get downstream of "validate then generate, and don't rebuild if it's not necessary based on metadata". In essence, for the same reasons that it is already exposed in the cli.

Opening a PR with what I was thinking. If you think it aligns, I'd be happy to add unit tests to cover the various scenarios.

**Comment by WoH** [comment]
I think we can get this in.
