### ISSUE TITLE
SuccessResponse decorator doesn't accept variables

### ISSUE THREAD

**Issue by gclotault** [lukeautry/tsoa#966]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I have a TS file that contains a bunch of constants that are used in my controllers to send status codes (in case of error or success).
When using the SucessResponse decorator with one of the constant, the status code in the Swagger documentation generated is always 200.

```ts
// src/common/sendHelper.ts

export const CREATED = 201;
...

// src/news/newsController.ts

import { CREATED } from '../common/sendHelper';
...
@Route('/api/news')
@Tags('News')
export class NewsController extends Controller {
  /**
   * Add a news to the Intranet.
   * @param news The news' body (title and content)
   */
  @Example<News>({
    id: 1,
    authorId: 1,
    date: new Date('2018-09-22T15:00:00'),
    title: 'News 1',
    content: 'First news',
  })
  @SuccessResponse(CREATED, 'News created')
  @Post()
  public async addNews(@Body() news: BaseNews): Promise<News> {
    try {
      const authorId = 1;
      this.setStatus(CREATED);
      const newNews = await new NewsService().add(news, authorId);
      return newNews;
    } catch (e) {
      throw new HttpException(
        e.status || GENERIC_ERROR,
        e.message || GENERIC_ERROR_MESSAGE
      );
    }
  }
}
...
```

Here is what I should get on the swagger.json generated
```yaml
...
"post":{
   "operationId":"AddNews",
   "responses":{
      "201":{
         "description":"News created",
         "content":{
            "application/json":{
               "schema":{
                  "$ref":"#/components/schemas/News"
               },
               "examples":{
                  "Example 1":{
                     "value":{
                        "id":1,
                        "authorId":1,
                        "date":"2018-09-22T13:00:00.000Z",
                        "title":"News 1",
                        "content":"First news"
                     }
                  }
               }
            }
         }
      }
   }
...
}
...
```

## Current Behavior

In the current situation, I always have a 200 reponse. I can only get a 201 response if I replace the constant CREATED by 201 in the decorator.

```yaml
...
"post":{
   "operationId":"AddNews",
   "responses":{
      "200":{
         "description":"News created",
         "content":{
            "application/json":{
               "schema":{
                  "$ref":"#/components/schemas/News"
               },
               "examples":{
                  "Example 1":{
                     "value":{
                        "id":1,
                        "authorId":1,
                        "date":"2018-09-22T13:00:00.000Z",
                        "title":"News 1",
                        "content":"First news"
                     }
                  }
               }
            }
         }
      }
   }
...
}
...
```

## Possible Solution

Stop using constant in the decorator

## Steps to Reproduce

1. Export a constant for a status code in a file
2. Import that constant and use it in one of the controller SuccessReponse decorator

## Context (Environment)

Version of the library: 3.6.1
Version of NodeJS: 12.18.3

- Confirm you were using yarn not npm: [ ]

**Comment by WoH** [comment]
I am pretty sure I've given this answer before. As an imported const of type number, typescript does not provide us with a way to reliably determine the status code at build time. Please use an enum which works differently in these cases under the hood.
