### ISSUE TITLE
Support for vendor media types

### ISSUE THREAD

**Issue by pittenga** [lukeautry/tsoa#968]
OpenAPI provides support for [vendor media types](https://swagger.io/docs/specification/media-types/). Is there a way to use the middleware to define that request body media type in the swagger output? Or maybe use a tag for it?

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Show the content type in the request body of a vendor specific media type.

```js
"requestBody": {
      "content": {
            "application/vnd.mycompany-v1.0+json": {
```

## Current Behavior

```js
"requestBody": {
      "content": {
            "application/json": {
```

## Possible Solution

```ts
private buildRequestBody(controllerName: string, method: Tsoa.Method, parameter: Tsoa.Parameter): Swagger.RequestBody {
    const mediaType = this.buildMediaType(controllerName, method, parameter); 
    const mediaTypeName: string = this.buildMediaTypeNameFromMiddleware(); <-- add something like this

    const requestBody: Swagger.RequestBody = {
      description: parameter.description,
      required: parameter.required,
      content: {
        mediaTypeName: mediaType,
      },
    };

    return requestBody;
  }
```
 Or if we can't tap into the middleware like that, maybe we can add a tag for it?
```ts
@Route('Controller')
@Response<ErrorResponseModel>('401', 'Unauthorized')
export class HiddenMethodController extends Controller {
  @Get('protectedGetMethod')
  public async protectedGetMethod(): Promise<TestModel> {
    return Promise.resolve(new ModelService().getModel());
  }
  @MediaType("application/vnd.mycompany-v1.0+json");
  @Post('protectedPostMethod')
  public async protectedPostMethod(): Promise<TestModel> {
    return Promise.resolve(new ModelService().getModel());
  }
}
```
## Steps to Reproduce
  
In the middleware (I'm using express), add something like this:
```ts
app.use(bodyParser.json({ type: "application/vnd.mycompany-v1.0+json" }));
```
And that comes out in the swagger output

## Context (Environment)

Version of the library: 3.6.1
Version of NodeJS: 12.18.2

- Confirm you were using yarn not npm: [ ]

**Comment by mrl5** [comment]
if I understand correctly @pittenga description is about **request** body media type.

I was redirected here because I was asking for a way of setting **response** content type.

@WoH is it OK to provide PR for my usecase (**response** not request) linked to this ticket or should I create a separate one that strictly describes my usecase? (I have already a working draft here: https://github.com/mrl5/tsoa/tree/issue-1126)

**Comment by WoH** [comment]
> if I understand correctly @pittenga description is about **request** body media type.
> 
> I was redirected here because I was asking for a way of setting **response** content type.
> 
> @WoH is it OK to provide PR for my usecase (**response** not request) linked to this ticket or should I create a separate one that strictly describes my usecase? (I have already a working draft here: https://github.com/mrl5/tsoa/tree/issue-1126)

Yeah my bad, the confusion is because I remembered this issue and sent you here. Please send a PR for response content types, I'd be happy to review. You can create a new issue and link it in the PR, but I know what it'll address regardless.

**Comment by mrl5** [comment]
for the record: 
1. it's possible to define response media type in generated spec. here you can see all possible ways to achieve this: https://github.com/lukeautry/tsoa/blob/b0cd9533821a7ed76111665ef01b655b62a775e3/tests/fixtures/controllers/mediaTypeController.ts
2. it's still not possible to define request body media type

**Comment by mrl5** [comment]
I started progress on:
1. ability to define multiple `@Produces`
2. introducing `@Consumes` (which is the original subject of this ticket)

PR soon
