### ISSUE TITLE
FAB Middleware Support

### ISSUE THREAD

**Issue by horrox** [lukeautry/tsoa#969]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

We've considered using tsoa for a lightweight middleware tier in an application deployed using the [FAB](https://fab.dev/) standard ([some words about server-side logic](https://fab.dev/guides/adding-server-side-logic)). It does not fall under any of the middleware options currently given. In your documentation about overriding routing, you request that we bring it to your attention. Have you ever considered creating a FAB routine implementation?

We're considering writing our own custom template.

**Comment by WoH** [comment]
I've never heard any of these words in the context of server side logic, but I'd be curious if there is demand for this. If there is, we could consider adding a template.

**Comment by horrox** [comment]
The FAB is pretty new and as far as I can tell so far only associated with [Linc](https://linc.sh), which was recently acquired by CloudFlare. I can't tell how much interest there is. For the current time, we've decided to move another direction. We may revisit this in the future.
