### ISSUE TITLE
Custom labels for examples

### ISSUE THREAD

**Issue by davidqqq** [lukeautry/tsoa#970]
Currently example labels are Example 1,2,3 .... I would like to customise example labels.
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

Yes I tried " Custom example label/name".

## Expected Behavior

It would be nice to have a way to customise example labels. 

```yaml
examples:
  MyCustomExample1:
    - attr1
  MyCustomExample2:
    - attr2
```

```ts
```

## Current Behavior

```yaml
examples:
    Example 1
     - attr1
    Example 2
     - attr2
```

```ts
@example onError {"code":"customErrorCode1","messsage":"Invalid book name"}
@example onError {"code":"customErrorCode2","messsage":"No such book"}
```

## Possible Solution
Maybe adding a dot follow by example label
```
@example onError.Invalid_book_name {"code":"customErrorCode1","message":"Invalid book name"}
@example onError.No_such_book {"code":"customErrorCode2","message":"No such book"}
```

## Steps to Reproduce

```
class Controller(){
  /*
   * @example onError {"code":"customErrorCode1", "message":"Invalid book name"}
   * @example onError {"code":"customErrorCode2", "message":"No such book"}
   * /
  @Get('/book')
  public getBook(@Res() onError: TsoaResponse<400, SomeError>,):string{
    return
  }
}

```
## Context (Environment)

Version of the library:
v3.7.0
Version of NodeJS: 
v12.19.0
- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
If you're able to reliably determine if the string is the example name, not the actual example (by looking at the length of the parsed array), I'd be happy to review a PR.

**Comment by steven130169** [comment]
I want this feature. I think this is nice.

**Comment by WoH** [comment]
Awesome! Looking forward to your PR.
