### ISSUE TITLE
I want to upload file but in swagger documentation shows text input instead of upload file button

### ISSUE THREAD

**Issue by dheerajscrrum** [lukeautry/tsoa#972]
![Screenshot (93)](https://user-images.githubusercontent.com/68528888/116666042-1e28d080-a9b8-11eb-92e4-d23c14409022.png)
![Screenshot (95)](https://user-images.githubusercontent.com/68528888/116666049-1ff29400-a9b8-11eb-9868-65be6775cecb.png)

**Comment by dheerajscrrum** [comment]
I am trying to create a route of upload file using following link https://tsoa-community.github.io/docs/file-upload.html

But instead of upload file button it shows me input field to upload file. How can i upload file in input field.

**Comment by WoH** [comment]
I think I know what the issue may be, but can you please provide the part of the spec that is produced by tsoa.

**Comment by dheerajscrrum** [comment]
"swagger": {
        "basePath": "/api/v1",
        "outputDirectory": "./src/api-docs/v1",
        "entryFile": "./src/server.ts",
        "specMerging": "recursive",
        "spec": {
            "paths": {
                "/files/uploadFile": {
                    "post": {
                        "consumes": [
                            "multipart/form-data"
                        ],
                        "parameters": [
                            {
                                "in": "formData",
                                "name": "imageFile",
                                "required": true,
                                "type": "file"
                            }
                        ]
                    }
                }
            }
        },
        "noImplicitAdditionalProperties": "silently-remove-extras",
        "securityDefinitions": {
            "apiKey": {
                "type": "apiKey",
                "name": "Authorization",
                "in": "header"
            }
        }
    },

**Comment by dheerajscrrum** [comment]
Here is the spec of tsoa.json

**Comment by WoH** [comment]
That's not what I am looking for, I am looking for the relevant parts in the spec/swagger.json file.

**Comment by dheerajscrrum** [comment]
"/files/uploadFile": {
			"post": {
				"operationId": "UploadFile",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					}
				},
				"tags": [
					"File"
				],
				"security": [],
				"parameters": [
					{
						"in": "formData",
						"name": "imageFile",
						"required": true,
						"type": "file"
					}
				],
				"consumes": [
					"multipart/form-data"
				]
			}
		},

**Comment by dheerajscrrum** [comment]
Here is the part of the swagger.json spec

**Comment by WoH** [comment]
Actually looks good at first sight, the upload button really doesn't show up if you click on 'Try-it-out'?

**Comment by dheerajscrrum** [comment]
![image](https://user-images.githubusercontent.com/68528888/116871354-c09fb880-ac31-11eb-8acd-370baa6319e4.png)

**Comment by dheerajscrrum** [comment]
I tried all possible solutions. But none working

**Comment by WoH** [comment]
I just had a minute to look at this a but more carefully. The docs sample is for OpenAPI 2. However, according to the last snippet from the produced doc, you're using OpenAPI 3, right?

There you want something like
 
```yaml
  '/files/uploadFile':
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: 'object'
              properties:
                imageFile:
                  type: 'string'
                  format: 'binary'
```

See https://swagger.io/docs/specification/describing-request-body/file-upload/ for more examples which may best describe your case.


Again, please fill out your templates, people. Without this I can't tell if you're on a recent version of tsoa, which support `@FileUpload` which gets rid of all the manual spec stuff for file uploads.

**Comment by dheerajscrrum** [comment]
Yes, I am using OpenAPI 3. How to add this in tsoa.json

**Comment by WoH** [comment]
Convert it to json and insert it instead of what you have there before?

**Comment by WoH** [comment]
I assume this solved the issue, for anyone stumbling across this. Use the new Decorators in the future (`@FileUpload`)
