### ISSUE TITLE
Property validators are not distributed over unions

### ISSUE THREAD

**Issue by nlang** [lukeautry/tsoa#973]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Consider the following interface:

```ts
export interface SomeInterface {

    /**
     * @isInt
     * @minimum 1
     * @maximum 31
     */
    someNumberProperty?: number | null;
}
```

I would expect to get an error because the number exceeds the maximum of 31 if I send the following payload:
```
{
  "someNumberProperty": 500
}
```

## Current Behavior

The payload is accepted and not validated against validation rules.

## Context (Environment)

Version of the library: 3.7.0
Version of NodeJS: 14.16.1

- Confirm you were using yarn not npm: [ ]

## Detailed Description

Nullable properties should not disable validation.

**Comment by WoH** [comment]
Null is not really the issue that's leading to this behavior. We don't currently distribute property validators over each union element.
So this issue would equally be reproducable for:

```ts
export interface SomeInterface {

    /**
     * @isInt
     * @minimum 1
     * @maximum 31
     */
    someNumberProperty?: number | string;
}
```

However, this shows a bit more clearly, why distributing validators over the union is actually was not the instinctively correct thing to do back at the time.

I'll gladly open this up for discussion though, based on your feedback and how [Typescript distributes conditions](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) we should maybe add this as a breaking change/feature.

**Comment by nlang** [comment]
Thanks for the Feedback.
Your example is probably rare to see in the wild, but I get the point.

Random thoughts:
- maybe null should be treated differently?
- maybe validators are bound to a type and only distributed to the type they belong to?
- maybe a @nullable annotation could solve the problem and would eliminate the need for the union?
