### ISSUE TITLE
DeepRequired for Req Body

### ISSUE THREAD

**Issue by karlismelderis** [lukeautry/tsoa#985]
## Reuse same all optional interface for "deep required" Request body

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

We have interface that's used for GET Request responses and for POST body

Fun started when we needed to make almost all response optional and still keep POST (create entity) as all required.

I tried DeepRequired from utility-types but that breaks tsoa.

## Current Behavior

Maybe topic was already discussed but I failed to find an answer in issues.

I cannot find an easy way to get this to work:

```ts
//GET response body - all is optional
export interface VersionData {
  key?: string
  keyA?: {
    keyB?: {
    }
  }
}

// expected definition for POST request body
export type VersionDataWithAllData = DeepRequired<VersionData>;

```

**Comment by karlismelderis** [comment]
it somehow works if we do it like this.
But in generated OpenAPI `required` is set only for first level keys
```ts
export interface KeyA {
    keyB?: {
     keyC:? string
    }
}
//GET response body - all is optional
export interface VersionData {
  key?: string
  keyA?: KeyA
  }
}

// expected definition for POST request body
export interface VersionDataWithAllData {
 keyA: DeepRequired<keyA>
};
```

**Comment by WoH** [comment]
There is an issue with the `UndefinedKeyword` explaining why that is.
However, the `DeepRequired` seems like a bug. Do you want to send a PR for that?
