### ISSUE TITLE
Support application types from npm packages

### ISSUE THREAD

**Issue by cmckni3** [lukeautry/tsoa#986]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I expect to be able to use interfaces from application packages.

## Current Behavior

tsoa emits the external interface error.

https://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD

## Context (Environment)

Version of the library: 3.7.0
Version of NodeJS: 12.x

- Confirm you were using yarn not npm: [x]

## Detailed Description

I want to use a private package that is shared between my application. The package contains services and code for multiple components of my application.

**Comment by WoH** [comment]
There are several issues which will help you solve this issue.
One of many examples: https://github.com/lukeautry/tsoa/issues/774

**Comment by cmckni3** [comment]
Ok, I saw that issue but wasn’t able to resolve my issue in a timely manner.

I’ll try adjusting the import too in case the top level import doesn’t work.

**Comment by cmckni3** [comment]
Works for some reason now. I think it was due a messed up package export.
