### ISSUE TITLE
Use validator instead of moment to validate dates

### ISSUE THREAD

**Issue by elaygl** [lukeautry/tsoa#988]
`moment.js` is a pretty heavy library that tsoa uses to validate dates.
`validator` which is also already installed, can validate dates the same way.

Removing moment.js lib from tsoa will save **~4.2MB** from `@tsoa/runtime` size.

## Sorting

- **I'm submitting a ...**

  - [X] feature request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
if (!validator.isISO8601(String(value), { strict: true })) {
  ...
}
```

## Current Behavior

```ts
const momentDate = moment(String(value), moment.ISO_8601, true);
if (!momentDate.isValid()) {
  ...
}
```

## Possible Solution

Use `validator` lib

## Context (Environment)

Version of the library:  3.7.0
Version of NodeJS: 12.20.0

- Confirm you were using yarn not npm: [X]

## Detailed Description

Use `validator` lib instead of `moment.js`

## Breaking change?

None.

**Comment by SteveVaknin** [comment]
Would be awesome! 👍

**Comment by elaygl** [comment]
Opened PR #989
