### ISSUE TITLE
refEnum not handled in query parameter validation

### ISSUE THREAD

**Issue by gpichot** [lukeautry/tsoa#991]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
import { Controller, Get, Query, Route, Request } from 'tsoa'
import Koa from 'koa'
type Alert = {id: string}

enum AlertTag {
    Foo = 'foo',
    Bar = 'bar',
}

@Route('/')
export class AlertsController extends Controller {
    @Get('/')
    public async getAlerts(
        @Request() request: Koa.Request,
        @Query() alertTags?: AlertTag[]
    ): Promise<Alert[]> {
        void request, alertTags;
        return []
    }
}
```
TSOa should validate query params for the enum values of the array.
```sh
curl http://localhost:3000/alerts/\?alertTags\=foobar
```
should validate query params with
```
{"fields":{"alertTags.$0":{"message":"should be one of the following; ['foo','bar']","value":"foobar"}}}
```
Note: I manually edited `node_modules/@tsoa/runtime/dist/routeGeneration/templateHelpers.js` to add case `refEnum` to generate this error message.

## Current Behavior

`refEnum` is not handled in `src/routeGeneration/templateHelpers.ts` but it's the type generated in `app/routes.ts` file.

Query param `alertTags` is not validated.

## Possible Solution

Either the refEnum type should be handled in `validateParam` as `enum` case, or the template generator/metadata parser should change `refEnum` to `enum` in some cases.

## Steps to Reproduce

See repo https://github.com/gpichot/tsoa-refenum-query-param for minimal reproducible example.

## Context (Environment)

Version of the library: 3.7.0
Version of NodeJS: 14.16.0

- Confirm you were using yarn not npm: [x]

## Detailed Description

I don't know, but if you have ideas on how to solve this I may find some bandwidth to make a PR.

## Breaking change?

I don't know

**Comment by WoH** [comment]
I think this should reject, can you confirm?

 ```shell
curl http://localhost:3000/alerts/alertTags[]=foobar
```

**Comment by gpichot** [comment]
@WoH it does not :s

```sh
$ curl http://localhost:3000/alerts/\?alertTags\[\]\=foobar
> []
```
And most of the time I use `http://localhost:3000/alerts/\?alertTags=foobar&alertTags=hello` syntax.

The generated route has the corresponding code: (note `alertTags` schema).
```ts
        router.get('/alerts',
            async function AlertsController_getAlerts(context: any, next: any) {
            const args = {
                    request: {"in":"request","name":"request","required":true,"dataType":"object"},
                    alertTags: {"in":"query","name":"alertTags","dataType":"array","array":{"dataType":"refEnum","enums":["foo","bar"]}},
            };

            let validatedArgs: any[] = [];
            try {
              validatedArgs = getValidatedArgs(args, context, next);
            } catch (error) {
              context.status = error.status;
              context.throw(error.status, JSON.stringify({ fields: error.fields }));
            }

            const controller = new AlertsController();

            const promise = controller.getAlerts.apply(controller, validatedArgs as any);
            return promiseHandler(controller, promise, context, undefined, next);
        });
```

**Comment by WoH** [comment]
Working on a fix, I reproduced it with the sample, thanks for reporting.

**Comment by gpichot** [comment]
You are welcome!
Thanks for the quick replies

**Comment by WoH** [comment]
[Release v3.8.0](https://github.com/lukeautry/tsoa/releases/tag/v3.8.0) should fix this. Please ping me to reopen if there are any remaining issues.

**Comment by gpichot** [comment]
@WoH thanks for the fix. I tested here https://github.com/gpichot/tsoa-refenum-query-param and it's working
Cheers !
