### ISSUE TITLE
Put swagger version at the top of generated spec so IDE recognises swagger file

### ISSUE THREAD

**Issue by seagullmouse** [lukeautry/tsoa#993]
IntelliJ does not recognise the generated spec file as a swagger file, and just opens it as a YAML/JSON file.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
swagger: '2.0'
basePath: ...
...
```

```ts
```

## Current Behavior

`swagger: '2.0'` is near the bottom of the generated spec file

```yaml
...
paths: ...
produces: ...
swagger: '2.0'
```

```ts
```

## Possible Solution

`specGenerator2.ts`
```ts
let spec: Swagger.Spec2 = {
      swagger: '2.0',
      basePath: normalisePath(this.config.basePath as string, '/', undefined, false),
      consumes: ['application/json'],
      definitions: this.buildDefinitions(),
      info: {
        title: '',
      },
      paths: this.buildPaths(),
      produces: ['application/json'],
    };
```

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 3.7.0
Version of NodeJS: v15.11.0

- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment]
If (and to be honest, I doubt it) the reason for unexpected behaviour occurs because the swagger attribute is not the first key, that'd be a VSCose (Extension) issue, not a tsoa issue

**Comment by seagullmouse** [comment]
Yes, it's IntelliJ's built-in recognition of swagger files. For some reason it does expect it to be the first key and I can't configure it. I will raise this with IntelliJ.

Just a minor issue, with a simple tsoa fix to make my life easier but I understand if this is wontfix!

Thanks

**Comment by WoH** [comment]
Can you link the Jetbrains issue, so I can keep track of the progress? If they don't decide to fix this, we should consider moving up the swagger/openapi key on our side to avoid the inconvenience, at least for tsoa users. However, I would prefer if Jetbrains decided to fix the detection on their end for everyone.

**Comment by seagullmouse** [comment]
Finally got around to raising this with IntelliJ https://youtrack.jetbrains.com/issue/IDEA-273733

**Comment by dPetruniak** [comment]
The same problem with [Cortex](https://www.cortex.io/). It expects `openapi: 3.0.0` on the first row
![image](https://user-images.githubusercontent.com/79448443/134674205-2b8bfc78-2c7d-4d69-9967-8958665d5fbe.png)
